### ISSUE TITLE
Steganography for saving battle data on screenshots

### ISSUE THREAD

**Issue by dragonjet** [KC3Kai/KC3Kai#1000]
Ability to share screenshots to friends, but when then use it, they can see the whole shit.
Yes one PNG screenshot file will contain all battle data, then be able to "replay" the feature somewhere.
Or at least show what happened if not animated replay

**Comment by LostLogia4** [comment]
How is that even possible lol?

**Comment by Crazyteitoku** [comment]
It is possible to embed stuff into some image files and not just for images. http://www.instructables.com/id/How-to-hide-one-image-in-another-An-introduction-/

**Comment by dragonjet** [comment]
I got this idea, to be honest, from illusion games - you know the one that makes those 3D ero games. We used to share our character files as PNGs and it carries their character data such as appearance (hair styles, body sizes, colors,etc ) and personality, etc.

it is possible and as I've looked for more info about it, turns out it's called Steganography  and i've got my eyes on a JS plugin which is also on github.

though the biggest problem to this right now is that even if the other parties are able to get the data, how to replay? :laughing:

**Comment by Crazyteitoku** [comment]
They probably will need to use KC3 Kai to replay the data and have KC3 Kai somehow feed that image. :laughing:

**Comment by dragonjet** [comment]
tested this right now, it works
https://github.com/petereigenschink/steganography.js

http://puu.sh/l5jZn.png

**Comment by LostLogia4** [comment]
How much image quality degradation we can expect from steganographing anyway?
If the image were compromised too much then many player would simply do without.

**Comment by dragonjet** [comment]
as i can see it, no visual difference from original

**Comment by LostLogia4** [comment]
A sample, pls.

**Comment by dragonjet** [comment]
http://puu.sh/l5qzh.jpg

**Comment by LostLogia4** [comment]
Oh lol a pre-kai2 Shigure-chan.

**Comment by dragonjet** [comment]
ah had been testing the taiha alert and had a disposable sheep as secretary all along XD
sorry pvp pplz
