### ISSUE TITLE
[wiki]Link to wikia blog

### ISSUE THREAD

**Issue by Yukinyaa** [KC3Kai/KC3Kai#1002]
at Download page : 

http://kancolle.wikia.com/wiki/User_blog:Dragonjet/KC3%E6%94%B9?page=9#comm-290776

"comm-290776" part scrolls page down to certain comment, please check

**Comment by LostLogia4** [comment]
What? Missing kancolle tab in devtools?

**Comment by dragonjet** [comment]
I am unsure what this means XD

**Comment by ethrundr** [comment]
I think he meant the URL.

The `comm-290776` part in the URL means it's redirected to the page on that specific comment, not directly to the top of the page.

**Comment by dragonjet** [comment]
but isn't that natural? XD
that's a direct link for a comment

is there anything we need to do on the app? :sweat_smile:

**Comment by ethrundr** [comment]
Well I don't know the entire case, though, but I think @Yukinyaa suggest that it linked to the page instead of comment....

**Comment by ReiFan49** [comment]
`#comm-290776` means refer the current page to the specified comment id,
which means, browser will navigate the referenced comment instantly after the page loads...
