### ISSUE TITLE
Corrections to Rank Points Counter

### ISSUE THREAD

**Issue by dragonjet** [KC3Kai/KC3Kai#1004]
http://kancolle.wikia.com/wiki/User_blog:Dragonjet/KC3%E6%94%B9#comm-351079

> The formula is actually HQ exp / 1428

> Also it should reset 1 hr before pvp reset, not at pvp reset as rank point cut-off for that reset is counted 1 hr early.

more info linked by @c933103 
http://sp.ch.nicovideo.jp/noisy_k5/blomaga/ar538827

**Comment by McDohl** [comment]
bonus rank points from EO also not applied

**Comment by ethrundr** [comment]
as reminder as well, the rank counting ended at 00:00 JST instead of 02:00 JST (2h earlier) on the last day of the month, in case we want to adjust this as well.

**Comment by dragonjet** [comment]
what are the bonus rank points for EO?

**Comment by ethrundr** [comment]
@dragonjet every month on the last day

EO bonus points: (total 780pts)
1-5, 75pts
1-6, 75pts
2-5, 100pts
3-5, 150pts
4-5, 180pts
5-5, 200pts
