### ISSUE TITLE
Screenshot without taiha alert blur

### ISSUE THREAD

**Issue by bcc32** [KC3Kai/KC3Kai#1005]
Currently, taiha alert blur seems to mess with screenshots.  Is there a way to make screenshots temporarily disable blur, or to take them _through_ blur?

**Comment by dragonjet** [comment]
hm, that's a problem. one thing is that we can't take it through blur - but possibly the one-tick off, but may cause more problems to low-end comps XD

**Comment by dragonjet** [comment]
Fixed in #1424
