### ISSUE TITLE
DMM buttons leaking thru in the iframe

### ISSUE THREAD

**Issue by mikenzb** [KC3Kai/KC3Kai#1012]
Okay not the best title but I didn't quite know how to name it, Well anyways I noticed a small bug which I guess DMM did something on their side but there's two or three buttons that are just barely visible and well... they cause some DMM stuff to show up.
![capture2](https://cloud.githubusercontent.com/assets/5982780/10966845/2ea2d4ba-841b-11e5-8387-9797e62d407b.PNG)
The barely visible button is above there ^ 
and there's 2-3 buttons there that cause this the dmm to overlay into the iframe
![capture3](https://cloud.githubusercontent.com/assets/5982780/10966868/5a66893e-841b-11e5-8c72-15b3b3f5b339.PNG)
![capture](https://cloud.githubusercontent.com/assets/5982780/10966870/5c22b180-841b-11e5-8b81-e4396405a1a5.PNG)

Nothing major really, just quality of life fixes,I'm guessing this was something DMM did, I wouldn't mind if that stayed there I'm sure no one would really mind it. 

Oh also using the latest pull 33a707c669e9bdd79f5d6a99720975c85a4be227

**Comment by dragonjet** [comment]
This is a new DMM toolbar that has just appeared yesterday. This will be added this into the hidden elements for next version

**Comment by Bikidup** [comment]
How do I get rid of it? I keep accidentally clicking it and a new page opens.

**Comment by dragonjet** [comment]
@Bikidup for quick fix, some have suggested to play via api link for now until the next update
