### ISSUE TITLE
natsuiro.html tab title????

### ISSUE THREAD

**Issue by nagatoyk** [KC3Kai/KC3Kai#1013]
![img](http://ww1.sinaimg.cn/large/64909e84jw1exr75j1x8sj206u012mx4.jpg)

**Comment by dragonjet** [comment]
it has recently been added to the translation terminologies, and not all languages has it yet

**Comment by McDohl** [comment]
https://github.com/KC3Kai/KC3Kai/pull/1008
https://github.com/KC3Kai/KC3Kai/pull/1010
https://github.com/KC3Kai/KC3Kai/pull/1011

**Comment by dragonjet** [comment]
As of 03a2dbf1dc9f12c4561304576cdd4185c690f0c1 it will inherit the english terms even if the translators have not yet added it to their local language files
