### ISSUE TITLE
mistake on mission

### ISSUE THREAD

**Issue by vincent121416** [KC3Kai/KC3Kai#1014]
The mission, "機動部隊の運用を強化せよ！"should be 26 and 35.
but in the chinese version it shows 26 and 36.

**Comment by LostLogia4** [comment]
I only [fixed](https://github.com/KC3Kai/kc3-translations/commit/6ec301a66e0c79d57d0d3f8c9ee4155033af5fd6) the numbers cuz I don't couldn't really read Chinese myself.

**Comment by Javran** [comment]
it looks good, closing.
