### ISSUE TITLE
Negative quest reset timer

### ISSUE THREAD

**Issue by bcc32** [KC3Kai/KC3Kai#1017]
![screen shot 2015-11-09 at 15 21 03](https://cloud.githubusercontent.com/assets/1239097/11045460/92900eb6-86f5-11e5-932f-a00b9e2e4bdb.png)
Is this supposed to happen?

**Comment by dragonjet** [comment]
nope, I am unsure why that happened :open_mouth:

**Comment by bcc32** [comment]
src/pages/popup.js
I think I found the culprit.  If TimeNow (in UTC) is 20:30 or something, getUTCHours() > 20 is still false, so you get the negative time (else branch).
```
if(TimeNow.getUTCHours() > 20){
	remaining = UTC8PMTomorrow.getTime() - TimeNow.getTime();
}else{
	remaining = UTC8PMToday.getTime() - TimeNow.getTime();
}
```
I think this can be fixed by simply changing the ">" to ">=" or reversing the order of the clauses and using "<" instead.  Or I could rewrite it to be a bit more generic.  I'll open PR and let you decide.

**Comment by dragonjet** [comment]
ah thanks :+1: 
let's use yours

**Comment by LostLogia4** [comment]
Alreday resolved, closing.
