### ISSUE TITLE
support of Read Cache file from external source.

### ISSUE THREAD

**Issue by c933103** [KC3Kai/KC3Kai#1019]
Just read that because it is time-consuming to re-download kancolle caches if you don't have a fixed computer to play on, some people opt to use chrome portable to play kancolle so that they can carry their cache file around, but reportedly it would cause weird behavior and redirection loop if cookie hack is used. So is it possible to save and read cache file of the game to/from external location, thus that people would only need to bring the cache file and redownload kc3kai everyday when using a different computer instead of packing the whole browser around?

**Comment by dragonjet** [comment]
Unfortunately, that involves some kind of man-in-the-middle like a proxy or similar mechanisms. As we stand right now, we never touch the requests to-and-from the client-server but only reading responses.

Also, by being a flat-javascript extension without nodejs support or anything fancy, we could only rely on [https://developer.chrome.com/extensions/api_index chrome extension APIs] which does not have anything about controlling cache (*except for clearing it*).

though I'd like to know more about this one
>it would cause weird behavior and redirection loop if cookie hack

**Comment by LostLogia4** [comment]
Sounds like a major hassle. I simply delete the cookies everytime I move to new computer.

**Comment by dragonjet** [comment]
you might also be interested in [Ooi2](https://ooi.la-foret.me/)

**Comment by c933103** [comment]
@dj see http://kancolle.wikia.com/wiki/Thread:338546

**Comment by LostLogia4** [comment]
Oh, that... simply deleting the "zombie" DMM cookies would do... there are 14 of them every single time this happens.

**Comment by LostLogia4** [comment]
impractical to implement in KC3Kai, closing.
