### ISSUE TITLE
Add spacing in Expedition Tab

### ISSUE THREAD

**Issue by LostLogia4** [KC3Kai/KC3Kai#1022]
@Javran, think you can add some spacing so it become more readable?

From this:
```
Flagship:level65
Fleet:6ships, total lv240
DD:5
8canisters on4ships
```
to this:
```
Flagship: Level 65
Fleet: 6 ships, total Lv240
DD: 5
8 Canisters on 4 ships
```

**Comment by mikenzb** [comment]
I had a quick suggestion, do you think you could also a quick line below the "Check requirements" to show "resupply needed" as well (in red if needed), I know there's already a line for that which isn't in the expedition tab but when i'm in a rush something my mind just skips looking at that and assumes the fleet is already resupplied

**Comment by LostLogia4** [comment]
@dragonjet u seriously intend to add the resupply notice in expedition tab?

**Comment by dragonjet** [comment]
isn't that what @mikenzb mentioned above

**Comment by mikenzb** [comment]
Well it was only a suggestion, you were free to not add it in if you guys didn't want to. It does help tho. but maybe you should've kept the check requirements there as well and added a new line below with a resupply status.

**Comment by dragonjet** [comment]
though this was slightly discussed with @Javran at gitter, we agreed that we didn't need the "check requirements" indicator because the mere fact that one of the items was highlighted in red will basically mean it does not pass

**Comment by LostLogia4** [comment]
hmm, maybe i should move it as a new issue?

**Comment by dragonjet** [comment]
Yep so we can continue discussing there are leave the spacing issue closed

**Comment by LostLogia4** [comment]
allright, I'll move it then.
