### ISSUE TITLE
Quest id:504

### ISSUE THREAD

**Issue by nagatoyk** [KC3Kai/KC3Kai#1025]
dev
![quest id:504](http://ww1.sinaimg.cn/large/64909e84jw1exzc3jyuwmj205q026mxb.jpg)

webstorage
![web](http://ww4.sinaimg.cn/large/64909e84jw1exzcyvoxzmj20t70fv11h.jpg)

How 15 supply schedule becomes the case, the original supply will be recorded each time, but is now completely not show progress, I do not know where the problem is!

**Comment by dragonjet** [comment]
this might be from the new "Check for new Quest TLs" settings, can you try unchecking it, then refreshing the browser, then going back to the quest page
