### ISSUE TITLE
AirCalc is Failed

### ISSUE THREAD

**Issue by nagatoyk** [KC3Kai/KC3Kai#1027]
![AirCalc](http://ww3.sinaimg.cn/large/64909e84jw1ey08kt50r2j216s0kxjys.jpg)

这是何故？ 这个问题存在有段时间了

**Comment by Javran** [comment]
额...好像确实没这个东西..

@dragonjet  did you forget to commit your `aircalc` directory?

**Comment by nagatoyk** [comment]
还以为是预留的功能= = 也就没在意 (●'◡'●)
话说，不知道有没有计划加入经验计算器 (●'◡'●)

**Comment by Javran** [comment]
经验计算嘛.. 相关的印象中有 #27 #326 #886 不过目前貌似没人在实现这个东西的样子.

**Comment by dragonjet** [comment]
I haven't done the aircalc yet :laughing:

**Comment by nagatoyk** [comment]
(●'◡'●)

**Comment by Javran** [comment]
since aircalc has been removed, I think this issue can be closed now?

**Comment by dragonjet** [comment]
yep, although this is the same as #1683
which could still be up for discussion

**Comment by Javran** [comment]
@dragonjet ok, I'm closing this one and further discussion are continued on #1683
