### ISSUE TITLE
[TCN] Update terms.json

### ISSUE THREAD

**Issue by angel84326** [KC3Kai/KC3Kai#1029]
Sorry I don't know clearly how to use Github....
https://drive.google.com/file/d/0B1dn__pGjMoBdUl4NnNNZjhMcEE/view?usp=sharing

**Comment by c933103** [comment]
@dragonjet Please help merge this to tcn folder of translation file and give him access to the translation repo.

**Comment by dragonjet** [comment]
ah nice @angel84326 is on board, no problem, I'll DL that and push to TL repo

adding him to the [TL team](https://github.com/orgs/KC3Kai/teams/translators), you just need to accept the invitation to organization

**Comment by dragonjet** [comment]
hm lots of changes, do you mean to merge like, overwrite the whole file?

**Comment by c933103** [comment]
@dragonjet how about the "also" part in my reply?

**Comment by angel84326** [comment]
@c933103  Kololz said he tried to translate the tab name in strategy room but it doesn't work.

**Comment by dragonjet** [comment]
@c933103 right now it cannot be translated as we still have to overhaul the whole thing at #810, but last time I talked to @kololz we agreed that the tab names wont change and can be translated but not implemented into code yet.
