### ISSUE TITLE
Expedition Logs

### ISSUE THREAD

**Issue by dragonjet** [KC3Kai/KC3Kai#103]
As suggested by wikians. disabled by default. only for those doing case studies

**Comment by ReiFan49** [comment]
looks like my data format on ships is a bit wrong,
however i would like to ask something,

if i remember, expedition result is possible to be guessed out by looking at the first value on mission array `[status , timeComplete, expedNum]` or something format.

nah, what is the difference between "cancelling the expedition" and "naturally failed expedition" ?

because `api_clear_flag` does not give a difference about that,

(ps: i started to log those expedition after `api_req_mission/result` api is called)

**Comment by dragonjet** [comment]
hm it is also possible to listen to the action when the recall button is clicked and just set a flag so that when they return if true, then it was recalled(?)

**Comment by ReiFan49** [comment]
```JSON
{
  "api_result":1,
  "api_result_msg":"assume the dev says -seikou-",
  "api_data": [
  {
    "api_member_id":16015130,"api_id":1,
    "api_name":"\u30e1\u30a4\u30f3\u8266\u968a",
    "api_name_id":"123990924",
    "api_mission":[0,0,0,0],
    "api_flagship":"0",
    "api_ship":[1791,56,328,-1,-1,-1]
  },  {
    "api_member_id":16015130,
    "api_id":2,
    "api_name":"\u5bfe\u6f5c\u8266\u968a",
    "api_name_id":"129857413",
    "api_mission":[1,36,1441422918307,0],
    "api_flagship":"0",
    "api_ship":[28,247,1102,232,-1,-1]
  }, {
    "api_member_id":16015130,
    "api_id":3,
    "api_name":"\u99c6\u9010\u8266\u968a",
    "api_name_id":"129857436",
    "api_mission":[1,37,1441400398745,0],
    "api_flagship":"0",
    "api_ship":[24,1119,9,623,221,2112]
  }, {
    "api_member_id":16015130,
    "api_id":4,
    "api_name":"\u7b2c4\u8266\u968a",
    "api_name_id":"",
    "api_mission":[1,38,1441401009312,0],
    "api_flagship":"0",
    "api_ship":[235,22,2,116,1,4]
  }]
}
```

uh oh... sounds like `expedState 1` for on going one....
`expedState 3` always recall i guess... (fleet 2, sent to wrong expedition)

**Comment by dragonjet** [comment]
wait, since when did we have an expedition result under the activity :laughing:

**Comment by ReiFan49** [comment]
oh, i just working on it xD (yeah, it just somewhat prototype, feel free to modify later on)
my `expedition-minipansion` branch works about database expansion to support `expedition` (and `battle` addons such as `node XP` and `MVP`, because database input change on #747)

**Comment by ethrundr** [comment]
Might well re-upping the issue....
Logging expedition is sure will be useful.

We already manage to detect and display the expedition result, so why won't we log it just like the sortie?

**Comment by dragonjet** [comment]
iirc @ReiFan49 said it's already logging, but I don't see on my IndexedDB :cry:

**Comment by nekoworkshop** [comment]
+1 for the expedition log. I really missed this feature since I came from KancolleSniffer.

![image](https://cloud.githubusercontent.com/assets/1346257/9800316/5c3f1e3c-57da-11e5-9423-c166b7f16f88.png)

**Comment by dragonjet** [comment]
@ReiFan49 I was making the UI for expedition history on strategy room but when I checked the database contents, it doesn't say which fleet number did it XD

though it did contain data for all 4 fleets, but can't show which one :sweat_smile:
