### ISSUE TITLE
Add Strategy Room to translate-able?

### ISSUE THREAD

**Issue by kololz** [KC3Kai/KC3Kai#1032]
Well actually I know there is a way to make things translatable, via adding the i18n tag. However, this didn't worked in Strategy.html...
Meanwhile, Angel and I want to translate the strategy room. I hope the coders here can help us.

**Comment by hufuhufu** [comment]
It's because strategy.js doesn't call ```KC3Translation.execute()``` function so the page don't translate anything
You need to add ```KC3Translation.execute()``` in strategy.js below the initialize data managers and it should translate the page
