### ISSUE TITLE
DMM网页模式 截图不能?

### ISSUE THREAD

**Issue by nagatoyk** [KC3Kai/KC3Kai#1033]
@Javran 点击development面板上的那个截图按钮, 但是却不能截图,不知道你们有没有发现

**Comment by Javran** [comment]
might be related: #49 #425
I also tried to screenshot (Direct DMM mode) and the icon seems to disappear and re-appear again, no screenshot is taken.

**Comment by nagatoyk** [comment]
Will is a screenshot of the script is not inserted into the reasons of the page? I see dmm.html and api.html which has this festival eh figure script, but the pattern is to jump to the official web site, view it with a development tool the code did not find the theme script, split test and this may be related.

**Comment by nagatoyk** [comment]
猜测可能是screenhot.js 这个脚本没有加入到网页模式的缘故
