### ISSUE TITLE
Background images setting idea and issue

### ISSUE THREAD

**Issue by weejiaquan** [KC3Kai/KC3Kai#1037]
I was messing around in the setting to set a background image and only see margin-top but no margin-left(right?) to let me move the player around to where I desire. 

Game Window (background image) is able to use "file:///" to use local images for it's background but Panel (background image) can't use "file:///" to use local images for it's background. (Just incase if you're wondering "Allow access to files URLs" is enabled".

**Comment by LostLogia4** [comment]
Horizontal alignment of the game window is at relative center : meaning it'll always be in the center regardless of the window's size.

**Comment by dragonjet** [comment]
it will always be horizontal center. unless we implement custom layouts which isn't in the foreseeable future and will in case be tracked in another pull request
