### ISSUE TITLE
Estimate time for PVP and quest reset

### ISSUE THREAD

**Issue by AlanSchaeffer** [KC3Kai/KC3Kai#104]
There could be some page that would show us the estimated time for PVP and quest resets.
I'm a bit lucky that the JP timezone is exactly 12 hours ahead of where I am, so unless there is DST it's easy to remember the times. But for other timezones, I think it would be helpful to have some places to check if you are unsure.

**Comment by bamboo3250** [comment]
We have already had the estimate time for the quest reset. It's also possible (and pretty easy) for PvP as well but the problem is "where to put the timer".

**Comment by ethrundr** [comment]
I believe that the horizontal panel is only around 450px in height (CMIIW)

If it's the case, then I assume it'll be safe to add some pixels in height, to fit the timer just below the quest tracker.

**Comment by dragonjet** [comment]
we don't need everything on the panel though XD

what if it's on the menu, below the Next update countdown timer. A player doesn't really need to see it 24/7 while playing xD
