### ISSUE TITLE
Transport Point Gauge Implementation

### ISSUE THREAD

**Issue by LostLogia4** [KC3Kai/KC3Kai#1044]
Here's the mapinfo extract of the map data.
The gauge is green, btw.
```
"api_id":322,
"api_cleared":0,
"api_eventmap":{
	"api_now_maphp":100,
	"api_max_maphp":100,
	"api_state":1,
	"api_selected_rank":1,
	"api_gauge_type":3
	}
```

**Comment by dragonjet** [comment]
hm I think the current still works, for I can see it in sortie history and battle tab on panel

anyone on E-3 and E-5 to confirm this also works on those maps?

![ss 2015-11-19 at 05 05 50](https://cloud.githubusercontent.com/assets/557312/11266494/dba269c2-8edf-11e5-9e48-8c4b5bfef4bb.png)

**Comment by ethrundr** [comment]
@dragonjet It works on E3, I checked it yesterday
however, can't say about E5. still on E4 farming for Zeppe

**Comment by dragonjet** [comment]
works on E-5 too, I'm crying there atm. no need for further adjustments :+1:
