### ISSUE TITLE
Combined fleet returned ships

### ISSUE THREAD

**Issue by AlanSchaeffer** [KC3Kai/KC3Kai#1047]
The ships that have been sent to return via Fleet Command Facility are not getting highlighted in the panel like they used to in the last event

**Comment by dragonjet** [comment]
directly connected to the bug at https://github.com/KC3Kai/KC3Kai/issues/1046#issuecomment-157996591

**Comment by dragonjet** [comment]
Fixed as of https://github.com/KC3Kai/KC3Kai/commit/6cf8a989930f3011c7f6334b42709ccd7c927158
