### ISSUE TITLE
Damage Prediction not working again in E-3

### ISSUE THREAD

**Issue by RredderR** [KC3Kai/KC3Kai#1049]
The damage prediction of both teams aren't working. Basically, I can't see which one of my ships are getting damages. Also the enemy fleet.

**Comment by RredderR** [comment]
![image](https://cloud.githubusercontent.com/assets/14126825/11264673/619ae0d2-8ed0-11e5-9e95-890b00204063.png)

**Comment by dragonjet** [comment]
duplicate #1045
