### ISSUE TITLE
[Bug] Expedition tab doesn't update if fleet is empty.

### ISSUE THREAD

**Issue by mikenzb** [KC3Kai/KC3Kai#1057]
Noticed this bug when I was getting ready to send out new expeditions after event farming and well.

If a fleet is empty the expedition number will change as you switch fleets but the time, resources and all that info below won't update (it will retain old values from the last expedition you were looking at)

![exp1](https://cloud.githubusercontent.com/assets/5982780/11299983/3c71d11e-8ff0-11e5-8c33-fef15bb5e66c.PNG)

and if you put anything in that fleet the expedition info will update.
![exp2](https://cloud.githubusercontent.com/assets/5982780/11300004/5a19c384-8ff0-11e5-84e6-8f484f2cb2dd.PNG)

**Comment by ReiFan49** [comment]
how about skip every fleet that were on expedition **and** *fleet that consists less than two ships* ?

**Comment by dragonjet** [comment]
:+1: happened on my side too

**Comment by Javran** [comment]
perhaps we've forgotten to close this. I just tried to repeat the same process and it now works as expected. so I'm closing this issue.
