### ISSUE TITLE
Unconverted Nodes Letter

### ISSUE THREAD

**Issue by ethrundr** [KC3Kai/KC3Kai#1058]
Don't know whether if there is already thread for this or not, but it'll be wiser to collect all forgotten nodes that still have their routing ID instead of node letter here.

E1:

E2:

E3:

E4:
- Node M. It shows "13" (branching from K - manual selection node)

E5:
- Node B. It shows "2" (branching from A - manual selection node)

**Comment by bamboo3250** [comment]
All node letters are kept track in this issue #540 (very old thread).
And don't worry, I have already added those 2 nodes in fcca665476fad9a87c77c6e39ea59a9a7bdcec60.
