### ISSUE TITLE
Mute taiha alert heartbeat

### ISSUE THREAD

**Issue by AlanSchaeffer** [KC3Kai/KC3Kai#1059]
Oh god can we have a button to temporarily mute the current taiha alert? I just had to watch the entire E-3 aftermath, plus two expeditions arriving and then about 6 ships worth of repairs to finally turn the alarm off, I think I may be going insane now :stuck_out_tongue:

**Comment by mikenzb** [comment]
There's currently a temporally way to disable the annoying taiha alert when your in a sortie, just pick a fleet that isn't in the sortie (support expedition/expeditions fleets), and it will disable it.

**Comment by AlanSchaeffer** [comment]
Why didn't I think of that XD

**Comment by ethrundr** [comment]
All in all, having mute feature to temporarily mute the alert still a good option.

**Comment by dragonjet** [comment]
:+1:

**Comment by dragonjet** [comment]
Fixed in #1424
