### ISSUE TITLE
Completed quests fail to disappear

### ISSUE THREAD

**Issue by Isokaze** [KC3Kai/KC3Kai#1061]
Issue: Completed quests that are cleared within the game while the KC3 panel is closed will remain present the next time the panel is opened again, and cannot be removed even after refreshing or restarting the browser.

In addition, as the panel can only display a maximum of six quests at a time (additional quests get pushed offscreen without the ability to scroll), this issue eventually clogs up the panel and renders subsequent active quests unviewable. 

Example: (note that the "Weekly Modernization" quest has already been completed and cleared in-game but is still present in the KC3 panel; the same problem is present with the "Daily Sortie 1" quest, and a seventh quest below is cut off and unviewable)
![ss](https://cloud.githubusercontent.com/assets/15951877/11316506/707ef59c-904d-11e5-85dd-b92ebdd3f5f5.png)

**Comment by ethrundr** [comment]
It happened because the KC3kai unable to update its database while you close the Panel.
Once the quest is completed and the reward is claimed, there is no way for the KC3kai to tell whether the quest is still locked, on progress or already completed. Thus, it'll stay there until the next reset.

Try navigating to the Strategy Room > Quest > Flowchart, and manually update the completed quest. This is the only way to solve the quest issue if you don't want to wait until the reset.

**Comment by Isokaze** [comment]
Yes, that helped resolve the issue, thanks.

Perhaps it would be possible to code it to scan the quest list every time the quest menu is accessed in-game, and assume that any quest last recorded with a full counter and which is no longer in the in-game list has been completed, then update the KC3kai database accordingly?

But in any case your fix will work.

**Comment by bamboo3250** [comment]
@Isokaze Unfortunately, scanning in-game quest list is impossible unless the player does so himself. The KanColle server only sends at most 5 quests of a page at a time when we navigate the quest menu and there is no guarantee that everyone will open all the pages all the time. Therefore the best we can do, in my opinion, is providing a convenient button to close individual quest on the panel.

**Comment by Isokaze** [comment]
I see. Regarding adding buttons on the panel – I'm sure you and your team are far more qualified than myself to decide on its feasibility and implementability, but at least my issue has been resolved, so I suppose this ticket can be closed.

Thanks again for your help and explanation!

**Comment by ethrundr** [comment]
You're welcome and glad we can help.
Just feel free to drop by, to ask or suggesting something. 
We are always welcome to every idea and reports we got, although we cannot promise we can fix or implement all of them.
