### ISSUE TITLE
Save fleet composition

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#1062]
This is a feature request.

Can we have something in strategy room that saves current fleet compositions?
The idea is to allow user to keep fleet and equipment configurations, name and share them.
This could be extremely useful for events - you need to remember your E1, E2, etc. configs, for last dance or for farming ships etc.

With feature implemented in #754, it's also good for sharing preset configurations - not just wikiacode

**Comment by dragonjet** [comment]
:+1:

**Comment by Javran** [comment]
just bumping this thread. I think this might be useful for incoming events.

**Comment by Javran** [comment]
assigning myself working on this. see branch [dev-fleet-viewer](https://github.com/KC3Kai/KC3Kai/tree/dev-fleet-viewer)

**Comment by Javran** [comment]
already done long time ago, closing.
