### ISSUE TITLE
[Bug] Expedition tab still displays a tick for unfulfilled conditions

### ISSUE THREAD

**Issue by LostLogia4** [KC3Kai/KC3Kai#1064]
![conditional](https://cloud.githubusercontent.com/assets/12930396/11324266/d68ee4e4-9167-11e5-93ec-1d7d1f1f6467.png)

Current implementation only checks if the fleet is resupplied, but not the rest of the conditions for expedition.

**Comment by dragonjet** [comment]
hm this is as intended. the bottom one is actually only for supply. there mere fact that something is red will tell the user the fleet is not qualified, as discussed in [this gitter moment](https://gitter.im/KC3Kai?at=564a9f3d6296df7f6efedbc7)

**Comment by LostLogia4** [comment]
You mean make the expedition box into green/red for conditions?

**Comment by dragonjet** [comment]
not sure I can follow xD

**Comment by dragonjet** [comment]
ah did you mean, if that bottom item is only for resupply status, then to have an indicator for the overall compliance would reflect on the expedition box, something like this?

![ss 2016-01-11 at 10 08 28](https://cloud.githubusercontent.com/assets/557312/12235655/02e54e56-b8b0-11e5-8ae3-2161000a72c6.png)

and this?

![ss 2016-01-11 at 10 10 04](https://cloud.githubusercontent.com/assets/557312/12235668/183b6bfa-b8b0-11e5-901c-7af0531c2c4b.png)

**Comment by LostLogia4** [comment]
That's more conspicuous than what I asked for. It's not the background that has the green/red color, it's the expedition box like [ Expedition #n ]

**Comment by LostLogia4** [comment]
Javran had already implemented the conditionals, closing.
