### ISSUE TITLE
Construction History

### ISSUE THREAD

**Issue by nagatoyk** [KC3Kai/KC3Kai#1065]
headers.Date lost
![headers.Date lost](http://ww4.sinaimg.cn/large/64909e84jw1eyaoktvggrj20h50dd76j.jpg)

Construction History The Time unrecorded
![Construction History The Time unrecorded1](http://ww2.sinaimg.cn/large/64909e84jw1eyaokyn9rrj20h20co0uv.jpg)
![Construction History The Time unrecorded2](http://ww1.sinaimg.cn/large/64909e84jw1eyaokw29kcj20jr06qjsg.jpg)

Our approach

The Kcsapi.js 413 lines of code
```js
var UTCtime = Math.hrdInt ("floor", (new Date (headers.Date)).getTime (), 3,1.);
```
Revised to
```js
var UTCtime = Math.hrdInt ("floor", (typeof headers.Date != "undefined" ? new Date(headers.Date) : new Date ()).getTime (), 3,1);
```
Analyzing headers.Date are undefined, if not defined, then the record with the current time, time parameters without api head

The above problem is due ShimakazeGo result, our approach is to give all the headers.Date increase a judge to decide the solution of the problem!

**Comment by ReiFan49** [comment]
hmm i don't really recall if there's a completion time,
by knowing the at least which ship is build, it's possible to know each ship buildtime (master data)

**Comment by nagatoyk** [comment]
I would say that at the time of construction, because the relationship between shimakazego, leading api return headers which lost Date of information, so I hope the record construction time plus the time to judge whether there Date field headers inside

**Comment by nagatoyk** [comment]
There is a new method, that is, in the browser api proxy, ip is set to direct connection, there would not be lost headers.Date field!

![新方法](http://ww4.sinaimg.cn/large/64909e84jw1eyd2xa4aemj212t0jnjwy.jpg)

**Comment by Crazyteitoku** [comment]
@nagatoyk Not that I openly condone the support the use of ShimakazeGO but I had a hunch that it is possible to make it work with KC3 Kai. It was an idea that I very much had in mind except that it was a slight modification to the [PAC file](https://myfleet.moe/assets/proxy.pac) made available via [myfleet.moe's](http://myfleet.moe) site. 

Too bad however proxy chaining ShimakazeGO with KC3 Kai and other viewers/tools that requires going through proxies would be harder. In theory however it might, just might be doable if ShimakazeGO for those instances be set as the last proxy server. 

The author and owner of MyFleetGirls made [a blog entry](http://d.hatena.ne.jp/ponkotuy/20140330/1396184917) about getting MyFleetGirls to work via browsers. The information is in Japanese however but the idea is not much different from what is demonstrated here.

**Comment by dragonjet** [comment]
marked as wontfix since there is a workaround outside KC3, but no further actions needed at the moment
