### ISSUE TITLE
Panel seems to be loading excessively slowly

### ISSUE THREAD

**Issue by NicolaosGreene** [KC3Kai/KC3Kai#1066]
As of version e6e4562be55f3262af5789fc4a5db81fba18861b my panel seems to be loading so slowly as to be of almost no use. Even going to the main screen repeatedly doesn't get it to acquire ship info or morale reliably, any idea what might be causing this? However, it appears that sending an expedition will get the panel to update.

**Comment by NicolaosGreene** [comment]
Reverting to version ce800b571feb5fa995d22f42c3b045e4d4642448 appears to fix the problem so there is some issue causing this in the commits after this time

**Comment by ReiFan49** [comment]
well, there are extra listener for every ships to fetch expedition return or not (as async database writing from expedition, to retrieve it's id and fetch it to the lodger for further supply use), part of lodger feature that is not easy to implement though..

**Comment by NicolaosGreene** [comment]
Well when I had it on the latest commit I was not seeing buckets, torches, screws, repair docks, or even the ships in my fleet when I initially logged in and they did not appear for me until I sent out an expedition. Thus I was wondering what exactly was happening to the base listener for things.

**Comment by ReiFan49** [comment]
there must be an error shows up, can i see the whole error on the console ?

**Comment by NicolaosGreene** [comment]
Well I re-updated to latest and now it seems to be working. Maybe there was some error in the one I pulled before, sorry for the fuss.
