### ISSUE TITLE
Detect damaged boss flag

### ISSUE THREAD

**Issue by LostLogia4** [KC3Kai/KC3Kai#1067]
According to the [intel HQ](http://kancolle.wikia.com/wiki/Thread:353436#48) several enemies have a damaged form and a flag in the battle API call to indicate it.

```
"api_boss_damaged":1,
```

**Comment by ReiFan49** [comment]
not applied to e-7 hime right?

**Comment by LostLogia4** [comment]
Applies only on Fall 2015 e4 and e5 boss so far.

**Comment by Javran** [comment]
it is suspected that the same mechanism will appear in E3 and E5, maybe we can change the HP bar style a bit whenever we detect it. I believe this will come in handy, so players don't have to pay attention to voice / lines / whatever to get a confirm.

**Comment by dragonjet** [comment]
world number will now become red, and hovering over it will tooltip "debuffed".
still to be pushed

![ss 2016-11-19 at 04 35 04](https://cloud.githubusercontent.com/assets/557312/20454258/2881c27c-ae76-11e6-87ea-2610f4066075.jpg)
