### ISSUE TITLE
[Bug report] various bugs.

### ISSUE THREAD

**Issue by Crazyteitoku** [KC3Kai/KC3Kai#1070]
**Date Seen**:
25-11-2015

**Version**:

**KC3 Kai v244 (git build) ID**: jljpednjlkddlmahfoljfjlnbollampe
**KC3 Kai v244 git revision**: e6e4562be55f3262af5789fc4a5db81fba18861b
**Browser**: Chromium 64bit (currently on: 46.0.2490.86 (Developer Build 2ca4f08cf229279a8c2ed565ac34ebc72f3883b4 Linux)
**OS**: Archlinux 64bit (currently on: Linux: 4.2.5-1-ARCH)

**Bug Description**:
- At start, ship girl faces and all not shown.
- Ship slots inaccurate for player, on one account it shows more ships than maximum applicable.
- Combined fleet HP prediction broken; at times it shows chuuha/taiha for the wrong set of ships.
- Combined fleet HP prediction broken also for ships that are still active within sortie - instead a grey bar is displayed over their HP which may mean they're either sunk or retreated.
- Sometimes enemy fleet formations not shown at E-4.
- Equipment count does not go down when equipments are scrapped.
- Support expedition fleet still on sortie when in game they have already returned. Happened on E-4.

Please refer to the screenshots provided below.

**Severity**:
Moderate - Major

**Steps to Reproduce**:
1. Start KC3 Kai and KanColle as usual.
2. First bug with ship girl faces are not shown as well as ship slots are inaccurate.
3. ... (more to come). 

**Actual Behavior**:
- Ship girls faces are missing.
- Ship counts are totally incorrect.
- HP prediction bar for a certain girl who was not to be damaged was indicated as to be damaged and instead some other girl gets damaged. Notably in combined fleets whereby the HP prediction bar for a girl predicted to be damaged was actually for the escort fleet if it was main fleet to be damaged. HP prediction for any girls in the escort fleet gets omitted as a subsequent result.
- For girls that were retreated via Fleet Command Facility, their bars were greyed out. That is correct, however their HP bar remains greyed out. After awhile other girls' HP bar is shown grey instead for no apparent reason.
- Enemy fleet formation field for certain nodes remain blank during sortie on the specified node.
- Equipment count either increments or stays the same after the count in the game has been decreased. At times this bug also happens with ship girl counts.

**Expected Behavior**:
Well needless to say that all these should not been happening. Presumably if reverting to much other version of git revision the bug would not appear.

**Troubleshooting/Testing Steps Attempted**:
None yet.

**Workaround**:
None yet.

**Attachments**:
![kc3 kai bug 001](https://cloud.githubusercontent.com/assets/12234182/11369815/89ceb43a-930c-11e5-88b6-bac2e349807d.png)
![kc3 kai bug 002](https://cloud.githubusercontent.com/assets/12234182/11370033/82dfd324-930d-11e5-8ab6-c852c1937fe5.png)
The following screenshots are from Fall 2015 Event, node O (Boss node):

![kc3 kai bug 003](https://cloud.githubusercontent.com/assets/12234182/11373670/fb204024-931e-11e5-8a76-9e55a5d3fa03.png)

![kc3 kai bug 004](https://cloud.githubusercontent.com/assets/12234182/11373668/fb1c5748-931e-11e5-855e-13aebe08c74e.png)
![kc3 kai bug 005](https://cloud.githubusercontent.com/assets/12234182/11373669/fb1fe1c4-931e-11e5-9712-482dee576d99.png)

**Comment by nagatoyk** [comment]
This problem was mentioned before, the question must be restored to ce800b5 Solutions  #1066

**Comment by ReiFan49** [comment]
the error that shows up on stacktrace .. somehow related to altered `KC3ShipManager.set` function, which automatically remove any ship that is not registered on `api_ship` data that were received from `port` api call.

ok, i guess i know why, fixing this.
```Javascript
rem.forEach(function(rosterId){
	slf.remove(rosterId); // KC3ShipManager.remove('x12345');
});
```

after
```Javascript
rem.forEach(function(rosterId){
	slf.remove(rosterId.slice(1)); // KC3ShipManager.remove('12345');
});
```

**Comment by NicolaosGreene** [comment]
Just a quick question related to this where should the error be printing to? I can't seem to find it now that it decided to happen again to me.

**Comment by Crazyteitoku** [comment]
@NicolaosGreene [here is one of the places on how you can potentially make errors show up.](https://github.com/KC3Kai/kc3-docs/blob/master/en/Setup_development_build.md#how-do-i-debug-kc3-kai)

**Comment by ReiFan49** [comment]
nah, haven't tested the boss gauge recording on Node part, gonna check first

**Comment by ethrundr** [comment]
not to blame anyone, but I also experienced the same error.
the latest stable pull I remember is on ce800b5 by @bamboo3250.
the commits afterward, however, contain and trigger all of these errors

**Comment by mikenzb** [comment]
Im not sure if this helps or not but I still get this error on the latest pull, I can get it to fix itself afterwards by sending out an expedition then everything comes back to normal.

![capture](https://cloud.githubusercontent.com/assets/5982780/11392856/40401772-93c1-11e5-9ae4-dd191e0494f1.PNG)

*shrugs*

**Comment by ethrundr** [comment]
same as @mikenzb, by doing anything: send a sortie, send an expedition, consume an item, the error somehow resolved, but the first of each one will be an error.

**Comment by dragonjet** [comment]
I'm getting the same error with @mikenzb as of latest pull

**Comment by ethrundr** [comment]
Updated list of errors:
- Any quests regarding to sortie is now cannot be tracked. I assume this happened due to the broken sortie data.
- Sortie history is now also got an error. As long as the sortie data is not properly displayed, ALL sorties in the same map is collated into ONE sortie history.
- Experience in Panel is NOT updated after sortie unless we go directly to the Player Information pages. The gained experience also will not be reset unless we reload the game. It keep stacking up per sortie, making my last exp is as much as 20k exp.
- Any items obtained in sortie that are being displayed on the panel is NOT updated unless we consume any item in the Item Menu.
- Any completed expedition will stay displayed as "Completed" until we resend the fleet to other expedition.
- Battle tab will not automatically switched back to Home tab upon returning to port. We need to switch it manually. Similarly, battle tab won't be triggered upon sortie unless we open it manually.
- First node of each sortie always recorded as error, thus cannot be displayed. Similarly, end of sortie is also recorded as error, thus rendering the KC3kai unable to tell that the sortie actually has been ended, which lead it to keep adding the next sortie nodes into the previous one.

**Comment by Crazyteitoku** [comment]
git revision: 6c83e869843d9d07be90eb1f9b5364988e32af8b
Upon returning to main screen I get this in console:
![kc3 kai bug 006](https://cloud.githubusercontent.com/assets/12234182/11415215/e08fe74a-944b-11e5-8534-53636b240790.png)

Also not that I wanted to blame anyone in particular for potentially opening up a can of worms really. It just has been a long while since I last opened up the developer console from within KC3 Kai just to notice there were errors popping up all over the place. What triggered that was well a few git pulls seems to have opened up these issues all over the place. Ironically it started happening when I sortied to certain maps, etc that these bugs and all became apparent.

As a beta tester, it is pretty much my duties to report them as needed. Not to point my finger at anyone in particular for the blame. :sweat_smile: In hindsight, I anticipate this is probably going to be one of the longest issue threads. :laughing:

**Comment by ReiFan49** [comment]
```Javascript
supply   = [
		function(a,b){return a.fuel - b.fuel;},
		function(a,b){return a.ammo - b.ammo;},
		0,
		function(a,b){
			return Array.apply(null,{length:a.slots.length}).map(function(x,i){return (a.slots[i] - b.slots[i])*5;})
			.reduce(function(x,y){return x+y;});
		}
].map(function(f){return f(before,after);})
```

:sweat_smile:

**Comment by ethrundr** [comment]
while we're at this....
why won't we fix the variable and function naming as well?

naming a function as f is not giving any explanation on what is it all about, thus making things harder for both tester and developer to address the issue accurately, especially if in future the person making that f function is not part of us anymore

**Comment by Crazyteitoku** [comment]
Enemy pattern is broken, it doesn't automatically switch to battle tab as well. Along with what @ethrundr said for "Any quests regarding to sortie is now cannot be tracked." I agree.

Here are the following screenshots with stack trace:
![kc3 kai bug 007](https://cloud.githubusercontent.com/assets/12234182/11415443/a505ad38-944e-11e5-937f-896378811dce.png)
![kc3 kai bug 008](https://cloud.githubusercontent.com/assets/12234182/11415444/a5082126-944e-11e5-844d-e56f0b29ace4.png)

**Comment by bcc32** [comment]
I am getting a somewhat-related error when Kanmusu is scrapped and count doesn't go down.

**Comment by dragonjet** [comment]
Temporarily I checked out my local git to ce800b571feb5fa995d22f42c3b045e4d4642448 until this is resolved :sweat_smile:

**Comment by ethrundr** [comment]
I checked out mine as well to ce800b5
If the bug is solved and ready to be tested, please notify here so I can continue to the actual head and test~

**Comment by Crazyteitoku** [comment]
I have also pulled the plug on being with the bleeding edge versions. According to @ReiFan49 the new experimental stuff has been moved into a new branch but the bugged version still exists in the master copy.

Now I have reverted to ce800b5 as well. Sorry @ReiFan49 but my patience ran thin. Whilst it is a good new thing to add, the timing of it all was just bad.

**Comment by ethrundr** [comment]
If the experimental stuff has been completely moved to the server, would we like to try to push `revert-commit` to our master, so all added-deleted lines from the bugged commit will be reverted to it's precommit condition?

**Comment by bamboo3250** [comment]
As @ethrundr 's suggestion, I think we'd better do `revert-commit` in the master back to ce800b5 while @ReiFan49 can continue developing the lodger in another branch.

**Comment by dragonjet** [comment]
alright got my internet back just tonight, so I had to catch up on support/inquiries on kc3 page and on my facebook page.

will check this `revert-commit` thing, and if no one has reverted tomorrow morning I'lll push it, and I'll also merge @bamboo3250's PR on the website, looks good stuff when I skimmed over.

**Comment by dragonjet** [comment]
is the `dev-lodger` branch updated? seems `6c83e869843d9d07be90eb1f9b5364988e32af8b` from master is not yet on the other branch

**Comment by ethrundr** [comment]
regarding the `revert-commit`, as I mentioned before:
https://github.com/blog/2019-how-to-undo-almost-anything-with-git

**Comment by dragonjet** [comment]
pushed the reverts, marked 25.0 as the "back to working version"
it can now be pulled and it works as I'm playing with it right now (havent sortied though)

naval ledger development will be continued in it's own branch, and other fixes and features can now be safely started or branched from the current `master`
