### ISSUE TITLE
Escort Flagship Critical trigger

### ISSUE THREAD

**Issue by Miguoo** [KC3Kai/KC3Kai#1071]
Escort flagship critical trigger

Moderate Damage would trigger critical alarm
Taiha Damage would not trigger critical alarm

Applies only to escort flagship.

Picture link:
http://puu.sh/lz4dF/c32ae433cb.jpg

P.S.
Mutsu just got Taiha'd on Day battle and will not trigger critical alarm after sortie/night battle, however Yahagi was already moderate damage at the start of Day battle.

**Comment by ethrundr** [comment]
I believe this has been discussed somewhere before....

**Comment by ethrundr** [comment]
Yep, the Chuuha alert has been discussed in #1043 
While for the Taiha alert for escort flagship, might as well to merge this issue to that thread.

So, closing this for now, and move the discussion to the aforementioned thread.
