### ISSUE TITLE
Screenshot doesn't align correctly on higher resoltuions

### ISSUE THREAD

**Issue by SmokeyTheButt** [KC3Kai/KC3Kai#1072]
I've noticed this when I start playing on my laptop which has a resolution of 2880 x 1800. It's happened three separate times where I took screenshots. 

![smokythebutt 2015-11-26 15-26-06 17](https://cloud.githubusercontent.com/assets/13164250/11430814/0ea8a7e2-9452-11e5-8ba4-e1e3ca83f053.jpg)
![smokythebutt 2015-11-26 15-25-23 50](https://cloud.githubusercontent.com/assets/13164250/11430816/116e8618-9452-11e5-895f-8991dae26611.jpg)
![smokythebutt 2015-11-13 18-45-16 91](https://cloud.githubusercontent.com/assets/13164250/11430818/17f89e24-9452-11e5-885e-0561ac6cb7a5.jpg)

**Comment by dragonjet** [comment]
Duplicate #49
