### ISSUE TITLE
Kancolle Tab not showing when using Chrome OS (Acer Chromebook)

### ISSUE THREAD

**Issue by Hibiki-Chan** [KC3Kai/KC3Kai#1073]
I tried opening the DMM frame and when I open source, there doesn't seem to be a Kancolle Panel in there. FYI I just got a new computer 
![no kancolle tab](https://cloud.githubusercontent.com/assets/14304892/11447868/be22df8e-9502-11e5-864f-c5f2f1f2150a.png)

**Comment by dragonjet** [comment]
Try checking cookie settings, must be on "allow local data to be set"

**Comment by Hibiki-Chan** [comment]
What URL do I use to put for the exceptions? Or do I just unclick the block third party app cookies?

**Comment by dragonjet** [comment]
* press the "allow local data to be set"
* uncheck "block third-party cookies and site data"

![ss 2015-11-28 at 06 38 59](https://cloud.githubusercontent.com/assets/557312/11448766/bd0b4fa8-959a-11e5-833e-69dd57019d87.png)
