### ISSUE TITLE
[Bug report] Event sortie history missing a portion of sortie ID - IDs were overwritten?

### ISSUE THREAD

**Issue by Crazyteitoku** [KC3Kai/KC3Kai#1077]
**Date Seen**:
04-12-2015

**Version**:

**KC3 Kai version**: 24.4 (Webstore build)
**Browser**: Google Chrome 47.0
**OS**: Windows

**Bug Description**:
*According to @MiyanoHiro*
Fall 2015 Event E-3 and E-4 missing. Later discovered that the sortie ID were overwritten.

Fall 2015 Event E-2 ended at sortie ID 270, whereas Fall 2015 E-5 event started at ID 271. E-3 and E-4 sorties shows up blank and a good 100 sorties were gone.

Please refer to the screenshots provided below.

**Severity**:
Moderate

**Steps to Reproduce**:
1. Start KC3 Kai and KanColle as usual.
2. Go into Strategy room, and into Sortie > Events.
3. Click on E-3, and E-4.
4. Data missing.
5. Click on E-2 and E-5, Data is there.

**Actual Behavior**:
E-3 and E-4 sortie history is completely blank as shown in screenshots whereas E-2 and E-5 shows sortie history.

**Expected Behavior**:
E-3 and E-4 sortie history to be shown and that E-5 sortie ID was not writing E-2. 

**Troubleshooting/Testing Steps Attempted**:
It was suspected that perhaps the sortie history was still stored in transient location known as cache/temp storage area. A third party software was used known as CCleaner may have been responsible for clearing out the transient data that KC3 Kai/Google Chrome stores before it is to be sent into User's Chrome storage area (i.e. under Users directory).

**Workaround**:
None yet.

**Attachments**:
![](https://scontent-syd1-1.xx.fbcdn.net/hphotos-xlp1/v/t35.0-12/12343194_1088261094518670_1576359489_o.jpg?oh=ae88eab57e541a6977d91025a5ab2302&oe=5664080F)
![](https://scontent-syd1-1.xx.fbcdn.net/hphotos-xpt1/v/t35.0-12/12343072_1088261197851993_1764579653_o.jpg?oh=f35135369655738c743b121cbfef6b4a&oe=5663FC46)
![](https://scontent-syd1-1.xx.fbcdn.net/hphotos-xpa1/v/t35.0-12/12343289_1088261361185310_1443294453_o.jpg?oh=a23366a210faf634b7925af02700bda9&oe=5662E421)
![](https://scontent-syd1-1.xx.fbcdn.net/hphotos-xal1/v/t35.0-12/12334226_1088261504518629_1839855947_o.jpg?oh=8b6ea4030bb67455e28d99979778e334&oe=5663D41C)
![](https://scontent-syd1-1.xx.fbcdn.net/hphotos-xtp1/v/t35.0-12/12333017_1088265211184925_1367960590_o.jpg?oh=8bb666ad213ae4f3326905202f1e1e29&oe=5663EC1B)

**Comment by dragonjet** [comment]
if he did E-3 and E-4 sorties before 24.x it means it still has the combined transport bug and recordings on that time frame is expected to be bugged. remember we had it right after the update, and we weren't able to fix it for some time.

**Comment by Crazyteitoku** [comment]
With regards to that, E-4 didn't require combined transport escort fleet if I am not mistaken. E-4 had a regular HP gauge for the boss. It would be understandable if the bug is only triggered on E-3 as that definitely did require the training of the TP gauge as well as combined fleet.

After talking to @MiyanoHiro he provided a screenshot that he found for E-4 earlier on:
![20151207130931](https://cloud.githubusercontent.com/assets/12234182/11618278/5a9a9fb2-9ce4-11e5-9934-ea2f60b0aac9.jpg)
Unless if in some way the bug affected both E-3 and E-4 in the same way for some strange reason. @MiyanoHiro also stated that by that time he also did recall he was on version 24.0. Not sure of the minor version but he did recall he was already on 24.0.

I am thinking of de-escalating the issue from moderate to minor as there has been no solid leads as to why the sortie history for the two selected maps (especially E-4) went awol. Besides @MiyanoHiro only wanted to provide the bug report as a feedback in hoping that it would better KC3 Kai, it was just coincidence that when he wanted to show off a portion of the history to his friends about it that as soon as he went to check back into sortie history for those maps all of the sudden the data went missing. He also mentioned that he isn't fussed about the loss of the sortie history but as well hoping that it won't happen in the future. With the lack of information with what lead up to this point, I guess it has already long become finding a needle in the haystack. :sweat_smile:

**Comment by dragonjet** [comment]
hm I checked changelog and it seems the transport fix only came after 24.2, probably `.3` or `.4` so we can dismiss E-3. But for E-4, if it's not transport, I'm also not sure. probably relates to the missing server dates as well? can still ask if he's an island winder?
