### ISSUE TITLE
[Bug] Team 1 and 3 are missing and quest doesn't disappear.

### ISSUE THREAD

**Issue by Chanary** [KC3Kai/KC3Kai#1080]
Just like picture.
Team1 missing (and team 3 is already give supply but it show red)
![image](https://cloud.githubusercontent.com/assets/16169539/11609962/76162aae-9bc7-11e5-9509-52bac479f0c6.png)

Team 3
![image](https://cloud.githubusercontent.com/assets/16169539/11609970/af30bf66-9bc7-11e5-9042-4b4cd8debf8d.png)

This quest didn't disappear after finish (make team has Ashigara as flag and have Kuma and Nagara)
![image](https://cloud.githubusercontent.com/assets/16169539/11609975/c3b76af2-9bc7-11e5-97e9-a997ff50b2a3.png)

**Comment by ethrundr** [comment]
For the quest, you might want to try this one: https://github.com/KC3Kai/KC3Kai/issues/1061#issuecomment-158590726

For the other error, this might not be a direct fix, but you can try some minor troubleshooting first here:
https://github.com/KC3Kai/KC3Kai/issues/1068#issuecomment-159528644

If the error still occurs, please leave a note here. We will also check our codes in meantime.

**Comment by Chanary** [comment]
Thanks a lot.
Quest is fix (I'm using [x])
*this problem I'm using keyword "missing" that's why I can't find it, sorry.

And missing team problem is solve it by using second method.

Truly thanks you.

**Comment by ethrundr** [comment]
Glad we can help.
We'll keep this issue opened for another day, just in case it appears again.

Just let us know if the problem occurs again in this issue thread.
