### ISSUE TITLE
world 4-5 node lost

### ISSUE THREAD

**Issue by nagatoyk** [KC3Kai/KC3Kai#1083]
![错误1](http://a1.qpic.cn/psb?/19196626-6f8d-40c4-a039-0de6fe1e724e/DIYG.pP4RsCElbaDz0mE*dN5GW.bdZ1d0SR7emsisZk!/b/dFwBAAAAAAAA&bo=2gLqAQAAAAAFABA!&rf=viewer_4)

![错误2](http://a1.qpic.cn/psb?/19196626-6f8d-40c4-a039-0de6fe1e724e/uNSv7Lc2.1jflFS6fZgmEpem8*X7DsFSAdJl5a4QCkI!/b/dFwBAAAAAAAA&bo=fgOPAQAAAAAFANA!&rf=viewer_4)

**Comment by LostLogia4** [comment]
Neither were properly mapped because most people had never actually go to the north route until now.
Seems like we'll need to rectify that quick now that Littorio has arrived...

**Comment by Javran** [comment]
https://github.com/KC3Kai/KC3Kai/blob/master/src/data/edges.json#L296

hm, edge 15 is from G to H ..? doesn't seem correct.

**Comment by LostLogia4** [comment]
Derp, corrected that now.

**Comment by Javran** [comment]
@LostLogia4 I just tried, I -> F is 16

**Comment by Javran** [comment]
good to close this issue? 11 and 12 should be one of J -> L and H -> K, but I think no one would try going there anyway.

**Comment by LostLogia4** [comment]
Already updated, closing.
