### ISSUE TITLE
Regarding Seasonal CGs

### ISSUE THREAD

**Issue by kololz** [KC3Kai/KC3Kai#1084]
Make it an option, as I think some people may not feel so familiarized with the seasonal icons. (Though I like this feature though). If it is disabled, then the icons will revert back to standard and non-seasonal ones.

**Comment by dragonjet** [comment]
:open_mouth:

**Comment by kololz** [comment]
:openmonth:

**Comment by LostLogia4** [comment]
...which seasonal icon are you talking about?
