### ISSUE TITLE
An little quest title error

### ISSUE THREAD

**Issue by nicolas22g** [KC3Kai/KC3Kai#1086]
http://puu.sh/lPjEN/84887453a3.png ( see the first quest)

I see an little error for an quest title.
Did the title was not supossed to be " A new Journey!"?

This is the quest WA02

**Comment by dragonjet** [comment]
This is one translations going back to [Zharay's KCV](https://github.com/Zharay/KanColleViewer/blob/master/resources/translations/Quests.xml#L755), which I think is still grammatically correct. The wikia now has it as "*A New Voyage*" though
