### ISSUE TITLE
legacy theme...

### ISSUE THREAD

**Issue by c933103** [KC3Kai/KC3Kai#1087]
As there seems to be a number of people accidentally switched to legacy theme like in http://kancolle.wikia.com/wiki/User_blog:Dragonjet/KC3%E6%94%B9#comm-377710 and complain about that, should the option to switch to legacy theme be removed?

**Comment by dragonjet** [comment]
Will do this on 26.x

**Comment by dragonjet** [comment]
* Fix will not force users to natsuiro theme. They still need to set natsuiro if previously on legacy
* Theme selection not removed for future themes
