### ISSUE TITLE
[Suggestion] Export KC3改 Settings into a file

### ISSUE THREAD

**Issue by Erodynamics** [KC3Kai/KC3Kai#1088]
As it says in the title, exporting KC3改 Settings into a file would be really useful since each update would reset your settings and you'd have to go through the setting all over again. When the KC3改 website's fully implemented, you can tie those settings into your account so you'd never have to go fill in the settings again, even if you switch computers.

**Comment by LostLogia4** [comment]
We already have export function in Profile Tab in strategy room, which is *in the default page* there...

**Comment by qqzzxx** [comment]
speaking of export setting， anyway  export all date to a file, like Sortie history,Expeditions history...?

**Comment by Crazyteitoku** [comment]
No, that isn't possible as yet.

**Comment by dragonjet** [comment]
the original post's exporting issue can be done by profile tab in strategy room.

for exporting other data like history, it will be discussed in other threads like: https://github.com/KC3Kai/KC3Kai/issues/1106 https://github.com/KC3Kai/KC3Kai/issues/1105
