### ISSUE TITLE
bgm doesn't work.

### ISSUE THREAD

**Issue by Kriegs-marine** [KC3Kai/KC3Kai#1089]
Bgm doesn't work when I apply furniture 冬の飾り付け.
Bgm冬の抜錨 would be played If there were no plobrem.
There is no music but silence.
Other bgm is fine about furniture.
I apply latest version of KC3Kai.

**Comment by LostLogia4** [comment]
Why do you think this has anything to do with KC3Kai?

**Comment by Crazyteitoku** [comment]
An example to prove this case is not specifically related to KC3 Kai is by playing the game without it first before playing with KC3 Kai.

Other than that KC3 Kai does not do anything with user's BGM.

**Comment by Kriegs-marine** [comment]
There was no problem when I played the game without KC3 Kai. 
I don't kow the reason why this problem has been solved, Now there is no problem.
Anyway thank's for reply and someone who apply to KC3 for someone like me.

**Comment by McDohl** [comment]
seems like your cache error. and after re-download the said bgm. it fixed your problem
