### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Katsuga** [KC3Kai/KC3Kai#1095]
Hi,
I am having problems seeing my fleets. I followed the three methods fix, but it didn't work
![1](https://cloud.githubusercontent.com/assets/16491138/12060495/aae8c2ba-afa3-11e5-9a39-5a11404c7a87.png)
![2](https://cloud.githubusercontent.com/assets/16491138/12060496/aaeba28c-afa3-11e5-9635-ccdc976f83e3.png)
![3](https://cloud.githubusercontent.com/assets/16491138/12060497/aaf055e8-afa3-11e5-8b0b-0e1ffd734e26.png)
![4](https://cloud.githubusercontent.com/assets/16491138/12060498/aaf0705a-afa3-11e5-8044-51c049dcb7f1.png)

Also, some tabs in Strategy Room are blank, like the showcase 
![showcase](https://cloud.githubusercontent.com/assets/16491138/12060510/f3a31eba-afa3-11e5-910b-14af29a84848.png)

Some tabs just blank and free the Strategy Room, I cannot switch to any other tabs, just close the Strategy Room.
 
I encounter this before, then change to KCV, but now I try again, still the same problem.

So, what should I do?

**Comment by Crazyteitoku** [comment]
Hi, which version of KC3 Kai are you using?

Also can you please try [this](https://github.com/KC3Kai/kc3-docs/blob/gh-pages/en/Setup_-_Development_build.md#how-do-i-debug-kc3-kai) as well. Ideally before you enter into the game with it setup. Maybe there might be some errors somewhere.

**Comment by Katsuga** [comment]
Oh it works now. I just went into the game then open the developer tools. Sorry for not reading the guide carefully.

**Comment by ethrundr** [comment]
despite closed already..
edited the title for so can be easily recognized just by seeing the title
