### ISSUE TITLE
Game Window Location

### ISSUE THREAD

**Issue by NizarAI** [KC3Kai/KC3Kai#1096]
Is there a way for me to edit where the game window goes? Like if I want it to be in the bottom left corner? I'm asking this because the Settings page only has "Top-Margin"

I usually play my games on the top left corner and the background I have set is in the top-right corner (the pic itself takes up the entire right side)

**Comment by dragonjet** [comment]
usually other players just make the top margin to a high value, given their windows are always maximized so it goes on the same spot each time.

**Comment by NizarAI** [comment]
So I tried making the top margin 9000px and it just sent the game window down off-screen and I had to scroll down to play

Is there no way for me to change the Left/Right margins?

**Comment by dragonjet** [comment]
This would be possible if #1076 is implemented with support for the game box
