### ISSUE TITLE
Natsuiro (??) Bug?? What??

### ISSUE THREAD

**Issue by Reddo-KanColle** [KC3Kai/KC3Kai#1101]
lol here's a hilarious bug that I found.
![bug](https://cloud.githubusercontent.com/assets/14126825/12388968/ecd2b426-be10-11e5-954b-e82daf4a5a91.png)

**Comment by Yukinyaa** [comment]
Can you explain what you did, or provide any additional information?
Screenshot doesn't explain anything :p

**Comment by dragonjet** [comment]
try pulling the TL submodule again

**Comment by Reddo-KanColle** [comment]
@Yukinyaa lol okay:
1. I opened Chrome
2. I clicked the KC3Kai Dev plug-in
3. I clicked Play via API Link
4. I pressed opened the developer tool
5. I ran KC with KC3Kai Dev
6. I see those
Is this clear enough?

@dragonjet Okay, I'll try.

**Comment by Reddo-KanColle** [comment]
@dragonjet that fixed it!

**Comment by Yukinyaa** [comment]
I have to seriously work on my "tone" of writing english

**Comment by Crazyteitoku** [comment]
@Yukinyaa I don't think what you said was offensive if anything.

Though yeah that issue is somewhat prevalent if you don't have TL submodules pulled. I still see that from my end here. :sweat_smile: 

Anyway closing issue as it seems to have been addressed.
