### ISSUE TITLE
[New Stuff]Full Manual Backup

### ISSUE THREAD

**Issue by Yukinyaa** [KC3Kai/KC3Kai#1106]
I uninstalled KC3 with storage backed up with <a href="https://chrome.google.com/webstore/detail/storage-area-explorer/ocfjjjjhkpapocigimmppepjgfdecjkb">storage explorer</a>
when I re-installed it and there (I think) were all data, except some, which turned out to be saved in "window.KC3Database"
any idea to fully back up whole thing?

**Comment by Yukinyaa** [comment]
Managed it myself... i keep asking unnecessary questions..

**Comment by dragonjet** [comment]
would you like to explain how you did it just in case anyone wanders around here thinking of doing the same thing? it would be nice to link this thread to FAQ in the later docs.

**Comment by Yukinyaa** [comment]
I am kinda working on it both soft way(in the extension) and the hard way(chrome data backup)

**Comment by Yukinyaa** [comment]
The Hard way could work - tested, and

**Comment by Yukinyaa** [comment]
https://github.com/Yukinyaa/KC3Copystuff/commit/60261e1c77a58abf62569579b9fe53ee89a53739

no. It totally works. I made a stupid mistake and It makes full backup now(I think)

**Comment by Yukinyaa** [comment]
https://github.com/Yukinyaa/KC3Copystuff/releases/tag/indev_build01 yay! some stuff!

**Comment by dragonjet** [comment]
:+1: good work, will link this copystuff whenever someone asks this.

FAQ will wait until we move into [kc3-docs](https://github.com/KC3Kai/kc3-docs) :sweat_smile:

**Comment by dragonjet** [comment]
did I do anythign wrong :laughing: 

![ss 2016-01-30 at 07 51 21](https://cloud.githubusercontent.com/assets/557312/12691382/4ffe9600-c726-11e5-8b86-7c9fdfd4a691.png)

**Comment by Yukinyaa** [comment]
@dragonjet no, I didn't build old one... on my way to build it

**Comment by Yukinyaa** [comment]
people won't use this when they have automated 'soft' backup
so closing this
