### ISSUE TITLE
"Next Remodel" event handler stacks up

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#1109]
try putting some debug messages after the following line:

https://github.com/KC3Kai/KC3Kai/blob/ad7daa448fa8e784a5327ed2e1ce57b220ab0091/src/pages/strategy/tabs/mstship/mstship.js#L267

then open up console, navigate to Ship Library of the Strategy Room. Click any "Next Remodel" link several times, and you can see console outputing far more debugging messages (probably exponentially) than expected:

![2016-01-25_210942_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/12570698/04f027d6-c3a8-11e5-9f48-0e06edf61a77.png)

This eventually slows down "Next Remodel" link.

**Comment by ReiFan49** [comment]
hmm, maybe i should take a look at the file difference between the one that i've changed on my side (but not commited yet) and the master one,

![image](https://cloud.githubusercontent.com/assets/9847780/12582597/b5feb61e-c470-11e5-998c-df7991c45db4.png)
to ensure if it was stacked over,

**Comment by dragonjet** [comment]
happens on my side as well, going to take a look at this too
