### ISSUE TITLE
[Suggestion] Cross-saving quest markers

### ISSUE THREAD

**Issue by CptBrown** [KC3Kai/KC3Kai#1111]
I use KC3Kai on 2 computers, sometimes even 3, which means completing quests on all 3 too. However, all 3 computers don't have their quests trackers sync-ed, leading to bad quest tracking. An online cross-save can allow quest tracking multiple game access at different locations.

**Comment by Yukinyaa** [comment]
I'm trying to work on it.
Step by step, from manual backup.

**Comment by dragonjet** [comment]
I feel that this would be better solved by similar features such as:
* #1283 on implemented on #1285
* Some ideas on updating quests states at #933
* Chrome sync as mentioned by #17

The manual backup by @Yukinyaa I could see better at syncing histories but not playing on mobile phones, or systems that they dont have KC3Kai installed.

Marking duplicates as this could be solved by any of the three issues mentioned.
