### ISSUE TITLE
Adding goal template to exp calculator

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#1112]
I want to add a goal template to exp calculator:

A goal template can save Map & Rank & FS & MVP configurations, together with a ship type filter. User can have many goal templates. The idea is when user adds a ship to "Current Goal" section, we can pick up one of those templates that ship type matches. And apply its preset values to it.

For example: we can have following two templates (omitting some flags):

1. "BB CV" 3-2 S
2. "DD CL" 4-3 S

when adding a battleship, template 1 will be applied.
but when adding a destroyer, template 2 will be applied.

there are some tentative plans:

* highlight ships that one template can be applied to. for example, when selecting template 2, all DDs and CLs not listed in current goal gets highlighted. this could be a replacement of ship type filter (seems to be a planned feature).
* recommended templates, some common places are well known for leveling, when there's no template saved. user can choose to load these templates.
* apply a template to all ships applicable in Current Goal section (overwriting current settings)
* enabling / disabling / move up / down templates, since we will always use the first applicable template.
* might need some modifcation to "Current Goal" section, allowing user to apply one template to current leveling ship.

self-assigned for now.

**Comment by dragonjet** [comment]
as input the @Javran's current idea, we can put this in a new tab, and retain the current leveling coals page. this new tab will only list the possible configurations.

when adding a new ship to the leveling list, one can choose a configuration via drop-down, so he doesn't need to re-input all the map, fs, mvp config.

e.g.
* Create Config: CA / 3-2 / No MVP / No FS
* Add Tone to leveling list, select Config 1, automatically applies those parameters.

Pros:
* Able to make multiple configurations for each ship type (a CA config as secondary to leveling a CV, a CA config as primary flagship, etc)

----

my other idea is to have a configuration, with not just ship type on each slot, but the ability to specify which ship is being leveled in that configuration already.

![ss 2016-01-30 at 11 23 21](https://cloud.githubusercontent.com/assets/557312/12693403/e9e5285c-c743-11e5-89e1-8821a1fc4d6e.jpg)


so it's not like a "template" where it can be used many times. you can call it "leveling teams".

**Pros**
* We can add a button to easily adapt current fleets into a configuration
* In terms of UX, he can easily visualize the compositions, and not just wildcard ship types

**Cons**
* Will need multiple instances of a specific composition, even if it has exactly the same ship type line-up. This is because the new team will have different girls even if it's the same ship type.
* If a ship was used on multiple teams, we don't know which one to calculate. e.g. her being on this team as flagship, or her being on the other team being only as secondary. We can't actually do a calculation.

because of the second con, it's pretty much not doable. If anyone else has any input, please do comment.

**Comment by LostLogia4** [comment]
@dragonjet how about an Individual (current) and Team (proposed) Leveling into the same tab separated by a toggle?

**Comment by Javran** [comment]
with @dragonjet 's suggestion, what about this plan:

I can imagine the following user workflow:

* **manage templates**. e.g. adding few templates, change order of template (because they will be attempted in order) 

* **add ships** into current goal list. user don't have to choose a template because choosing template is automated also it would be inconvenient for users when there are many templates.
  We can still leave an option to user: place two buttons on non-goal ships,
  one is the old "+" icon, it automates template choosing, another, asks user to pick one template.

There are some other reasons I want goal-template to share the same tab as leveling goals:
user might go back and forth between managing templates and adding ships, keeping controls on same tab makes it easier.

also, templates can be used to highlight shps, this might even be better than the ship filter on ship list page. for example, a goal template can have a ship type filter of `CV CVL CVB`
whereas on ship list page we have to check `CV` `CVL` `CVB` manually. Keep goal template on the same tab makes this filtering feature possible.

We can also have "leveling configuration" feature at the same time, but the purpose might be slightly different:

- on "leveling goal" tab we are interested in goals: it can tell us how many runs we need for a particular ship to reach certain level 
- on "leveling configuration" tab we are trying to be more accurate: given a fleet compo, how many battles do we need for each member of the fleet (we can even calculate how many fuel & ammo is required)

this two methods could give different results and users might prefer one over the another,
if we want to implement both, we might leave user an option to determine which number to show in devtools page.

**Comment by Yukinyaa** [comment]
I think we already have too many tabs on strategy room. and @LostLogia4 's idea was great.
@Javran I really can't clearly draw image of what you are saying, but I get the idea for the page. And yes. that would totally work.
It will be a lot of work tho.

**Comment by LostLogia4** [comment]
Preview from Javran
[![2016-02-03_120231_3840x1080_scrot.jpg](https://files.gitter.im/KC3Kai/Public/kSIu/thumb/2016-02-03_120231_3840x1080_scrot.jpg)](https://files.gitter.im/KC3Kai/Public/kSIu/2016-02-03_120231_3840x1080_scrot.jpg)

**Comment by Javran** [comment]
I have implemented "goal template" part I describted above. The UI definitely needs some tweak, which I'm not good at.

Checkout branch [expcalc-goal-template](https://github.com/KC3Kai/KC3Kai/tree/expcalc-goal-template) and let me know what you think XD

Anyway, here is a quick manual about how to use it:

There'll be a new section "Goal Templates" after "Current Goals" and before "Recommended":

![2016-02-03_171039_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/12798748/1b8859ee-ca99-11e5-9e24-364b93910f5c.png)

Click "New template" to add new templates, initially there should be none.

Basically editing templates is the same as editing goals, "S", "E", "X" have the same functions. Only thing new is "ship types".
This field is a comma-separated list of ship types, for now only English abbrs and `*`(will be explained shortly) are accepted (case-insensitive), following inputs are all valid:

* `cl, dd, ca`
* `CL,    DD, CA, DD, CA`
* `*, ca, dd`

Don't worry about case or putting extra spaces, they will all be normalized when saving.

`*` is a wildcard that matches all ship type, so any ship type containing `*` can be applied
to arbitrary ships.
You can keep a template with ship type `*` at the end of the template list, to serve as a "default setting".

When adding a ship to the current goal section, templates are attempted in order, the first one containing the correct ship type is applied.

There are two green buttons on each template to change their orders.

"Enabled" button, when clicked, changes to "Disabled", and template's background turns grey:

![2016-02-03_172359_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/12799078/f5a4db9c-ca9a-11e5-8b09-9e8848770a96.png)

A disabled template won't be used when adding new ships to "Current Goal" section.

"Filter" button highlights all ships whose ship type matches the template's,
here is a screenshot of filtering `DD,CL`:

![2016-02-03_172835_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/12799189/9e961cfc-ca9b-11e5-839e-0332627d4ed1.png)

Highlights can be cleared using `Clear Highlight`.
Note that even if you template matches that ship, it doesn't mean that particular template will be applied,
because there might be an applicable template prior to this one (appears earlier than template in the list), or this template is disabled.

Finally, "Apply to Current Goals" does what its name says. In case one accidentally clicked that button, there is a confirm dialog:

![2016-02-03_173646_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/12799415/beb89252-ca9c-11e5-9463-e7dd164c45b5.png)

**Comment by Javran** [comment]
Update: I put some FAQs in Help Topic, anyone interested can checkout branch [expcalc-goal-template](https://github.com/KC3Kai/KC3Kai/tree/expcalc-goal-template) and read.

![2016-02-05_002343_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/12838656/d8e322a2-cb9e-11e5-8051-0e60edbec1da.png)

let me know what you think.

**Comment by Javran** [comment]
bumping this thread, I think my goal template is almost done, just resync-ed with master branch.

@dragonjet hi dj could you help on tweaking the UI on branch [expcalc-goal-template](https://github.com/KC3Kai/KC3Kai/tree/expcalc-goal-template)?
