### ISSUE TITLE
Twitter account or FB page For KC3 update log and news, data collection

### ISSUE THREAD

**Issue by Yukinyaa** [KC3Kai/KC3Kai#1113]
Hey, why not?

**Comment by Yukinyaa** [comment]
Twitter could be automated. So we can avoid conflicts for tweets
(I am no expert for twitter, but I found update notice from KanColle_STAFF pritty handy)

**Comment by dragonjet** [comment]
alright we can do a twitter account. The fb page exists here though https://www.facebook.com/kc3kai/
PM me on gitter on your facebook email if you want to get added to editors.

I'll update this thread again once done with the twitter account

**Comment by dragonjet** [comment]
Twitter account is at https://twitter.com/kc3kai
Come into the non-public gitter channel for login details
