### ISSUE TITLE
[Bug report] Weekly Quests keeps resetting even when user did not request for one

### ISSUE THREAD

**Issue by Crazyteitoku** [KC3Kai/KC3Kai#1116]
**Date Seen**:
01-02-2016

**Version**:

**KC3 Kai v260 (git build) ID**: jljpednjlkddlmahfoljfjlnbollampe
**KC3 Kai v260 git revision**: 3a6562c64d2aab9f72e2e5f34b4cbfa53c22b8d9
**Browser**: Chromium 64bit (currently on: 48.0.2564.97 (Developer Build 76bc56ae79e5f501eaf1ed311ff828f6daf8538a Linux))
**OS**: Archlinux 64bit (currently on: Linux: 4.3.3-3-ARCH)

**Bug Description**:
Weekly Quest keeps on resetting even though it is already new week. Selecting the weekly quests in game would make it appear on KC3 Kai panel on that screen only but would disappear when the user either goes to another quest page or exits out of quest screen.

Weekly Quest will continue resetting as noted when debugging KC3 Kai panel even when the user visits other parts of the game (e.g. "receiving" fleets from expeditions).

*This bug also happens on Google Chrome browser, not just Chromium builds. Below is a snippet output on chrome://version from Google Chrome on Linux.* 
**Google Chrome**: 48.0.2564.97 (Official Build) (64-bit)
**Revision**: 97d2b858fc7c3d480a52f4b58ed72c76fa535598-refs/branch-heads/2564@{#&#8203;631}
**OS**: Linux 
**Blink**: 537.36 (@&#8203;97d2b858fc7c3d480a52f4b58ed72c76fa535598)
**JavaScript**: V8 4.8.271.17
**Flash**: 20.0.0.286
**User Agent**: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36
**Command Line**: /opt/google/chrome/google-chrome --flag-switches-begin --flag-switches-end

Please refer to the screenshots provided below.

**Severity**:
Moderate - Major

**Steps to Reproduce**:
1. Start KC3 Kai and KanColle as usual.
2. Go into Quests inside the game
3. Go and select weekly expeditions. In my case I have selected weekly expedition quests such as complete 30 expeditions as well as complete Tokyo express expedition once.
4. Go either into another Quests page or exit out of Quests section in-game.
5. Notice the KC3 Kai panel no longer displays the weekly quests that you previously selected. 

*Open KC3 Kai debug console*
1. Go into Quests page in-game.
2. Click on any of the quests pages or exit out of quests pages in-game.
3. Notice how the debug console keeps informing that the weekly quests has been reset.

**Actual Behavior**:
- Weekly quests keeps on resetting

**Expected Behavior**:
- Weekly quest should only be reset once, not for every time the user visits other in-game pages.

**Troubleshooting/Testing Steps Attempted**:
- Pulled the latest version of KC3 Kai development version and the issue persists - was previously on 8e2b19ca8c6caab13bae2087af6839cd32eb31d3 when the bug first surfaced.
- Tried pressing on reset daily/weekly/monthly/everything quests button inside the strategy room just once in a bid to "un-stick" quests reset. Bug still is present.  

**Workaround**:
- Perhaps ````git rebase```` on older git commits would resolve the issue but I have a pressing issue with Chromium automatically resetting my cache for Kancolle game. :sweat: 

**Attachments**:
![screenshot_20160201_100236](https://cloud.githubusercontent.com/assets/12234182/12706216/944dad18-c8cb-11e5-841e-8875dca0cc9e.png)

**Comment by ReiFan49** [comment]
![image](https://cloud.githubusercontent.com/assets/9847780/12707766/aa085974-c8ca-11e5-9dc3-007b336e7aaf.png)
somehow it is the issue that i haven't checked off (i didn't know for this case for sure...)

pretty sure have problem over day offset control which overflows over than 1 day count (as calibrator).

**Comment by Crazyteitoku** [comment]
A "bump" on this issue:

[Hideo Kanzaki](http://kancolle.wikia.com/wiki/User:Hideo_Kanzaki) via [Kancolle wikia chat (requires Wikia account)](http://kancolle.wikia.com/wiki/Special:Chat) has mentioned the same bug now appearing on the webstore version of KC3 Kai.

Information:
**OS:** Windows
**KC3 Kai webstore version:** 26.3
**Google Chrome:** 48.0.2564.116 m

**Comment by ReiFan49** [comment]
monthly issue? hmm
