### ISSUE TITLE
Kasumi Kai 2 & Kai 2B icon missing

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#1118]
just a reminder.

**Comment by LostLogia4** [comment]
hmm, how do we make the icons then?

**Comment by Javran** [comment]
I guess only @dragonjet can do that, he is also planning to put the tool on https://github.com/KC3Kai/kc3-icons

**Comment by Yukinyaa** [comment]
wasn't this fixed?

**Comment by Javran** [comment]
no, https://github.com/KC3Kai/KC3Kai/blob/master/src/assets/img/ships/470.png is still missing.

**Comment by Javran** [comment]
![2016-02-09_202525_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/12936280/4c7c9bec-cf6b-11e5-8394-df5ef75ec0b7.png)

also these abyssal icons are missing, at least PT Imp Pack is likely to present again so I think it doesn't hurt to update them as well.

**Comment by Javran** [comment]
Fixed by https://github.com/KC3Kai/KC3Kai/commit/98ce4a7b692025038c45c8b0947f455de1de8a46
and https://github.com/KC3Kai/KC3Kai/commit/82392133723ceb086fdd14a94287fc938412bbb1
closing.
