### ISSUE TITLE
[Feature] Resource graph more fluid

### ISSUE THREAD

**Issue by Yukinyaa** [KC3Kai/KC3Kai#1122]
More data should be able to be accessed when display resource(Consumable) graph shows.
#420 should be first one on the list, then $420, not certain about #75 though.

**Comment by ReiFan49** [comment]
configurable time range?
i don't know if ledger feature will be copied over `graphable` data or not, it does a bit complex time range reading though. (i remember there's an issue that were meant for what i tell just now... #420)

**Comment by dragonjet** [comment]
Related:
* https://github.com/KC3Kai/KC3Kai/issues/73 Resource Graph, filter one resource at a time
* https://github.com/KC3Kai/KC3Kai/issues/75 Resource Graph: Count difference
* https://github.com/KC3Kai/KC3Kai/issues/420 [Suggestion] Resource and Consumables Graph

**Comment by Yukinyaa** [comment]
Will work on this as soon as I finish data saving feature to usable level..

**Comment by Nya-chan** [comment]
I think this is pretty much complete. All related issues are closed now and graph fluidity looks okay to me.

**Comment by Javran** [comment]
yup this can now be closed.
