### ISSUE TITLE
IconManager

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#1123]
I've implemented an `IconManager` that works like a cache: fetching ship icons from URL and storing them in IndexedDb for later use. You can checkout [dev-icon-fetch](https://github.com/KC3Kai/KC3Kai/tree/dev-icon-fetch) branch and try.

For now the performance is a little worse than original one: icon slightly blinks when click on fleet icons / changing equipments / modernalization / etc. and I'm not sure if I can find an easy fix. So I open this issue and list few pros and cons about using both for discussion:

* The master branch has ship icons stored locally
    * fast enough that no icon blink is noticeable
    * increased app size
    * icons are shipped with app, no chance for updating ship icons without updating the app

* `IconManager` (ship icon caching)
    * uses IndexedDb (via Dexie), little slower. I believe this can be solved by reducing amount of unnecessary UI updates(e.g. don't update fleets when clicking same fleet tab twice, or only update equipments when changing equipments), but not sure to which extent can we optimize.
    * no need to ship with the app (might need a standalone icon repo)
    * when new ship comes out, we can just update ship icon repo instead of the whole app
    * could be one solution for #1084: in the icon repo can have separated directories for different icon sets, (e.g default one keep sync with seasonal CGs, and have a different icon set that only update with new ship is available)

**Comment by dragonjet** [comment]
tbh I'm not much into this. I feel saving blobs/base64 into indexeddb is too heavy. I'm not very familiar on how indexeddb stores data, but too much bytes going in-and-out of the system doesn't sound attractive xD imho I prefer having assets remain as cachable files.

**Comment by Javran** [comment]
maybe looking for a site that supports caching would be better. for now I have no confidence making it better and that might worth trying. closing issue.
