### ISSUE TITLE
[Bug Report] Missing fleet and no information strategy room

### ISSUE THREAD

**Issue by Marono83** [KC3Kai/KC3Kai#1124]
Hi everyone

A friend is come back to kancolle and use now KC3 KAI.
But when he uses KC3 KAI there are all fleet who are missing:

![kancolle bug](https://cloud.githubusercontent.com/assets/17091044/12861077/fa9538dc-cc60-11e5-9808-2a0320a1c7d6.png)

And when he goes to the strategy except the first screen everything is blank
![kancolle bug 2](https://cloud.githubusercontent.com/assets/17091044/12861086/17cead70-cc61-11e5-95f3-faf07306f138.png)
![kancolle bug 3](https://cloud.githubusercontent.com/assets/17091044/12861087/1ab98500-cc61-11e5-87af-86029cdeb927.png)

Just in case he use windows 10.(I'm not very good in english i hope i dont have do too many much error)
If someone know something about that can you help us please?
P.S: He cannot see his construction too

**Comment by dragonjet** [comment]
This is usually attributed to opening the panel after starting the game.

Make sure he opens the F12 panel before game start

**Comment by Marono83** [comment]
He has test and it's worked ^^.
Thank you dragonjet and sorry for the disturb.

**Comment by LostLogia4** [comment]
Already resolved, closing.
