### ISSUE TITLE
Unable to download replay image.

### ISSUE THREAD

**Issue by htomeload** [KC3Kai/KC3Kai#1128]
I do every step in guide.
- I install git and clone KC3Kai by git clone command.
- I change directory to KC3Kai.
- I generate new ssh key and add it to ssh-agent and my github account.
- I do submodules update by git submodule update --init -- "src/data/lang".

everything work as regular version that can download from google store but replay image still can't download. Console give error with more detail.

I use
- Chromium Version 48.0.2564.82 on Linux Lite 2.6 x86(Base on Ubuntu 14.04 LTS) latest kernel.
- KC3Kai Dev Version 26.

<a href="http://imgur.com/f2R0lZ9"><img src="http://i.imgur.com/f2R0lZ9.png?1" title="source: imgur.com" /></a>

**Comment by Crazyteitoku** [comment]
Adding to what was previously missing in this conversation, @htomeload was previously using the webstore version of KC3 Kai (version 25.1) which also faced the same issues. As well in addition, here are what were previously mentioned (via facebook) that the user has tried on:

- Ubuntu Gnome x64
- Linux Lite x32 (It base on Ubuntu 14.04.03 LST)
- Windows 7 x86
- Windows 10 x64.

Almost those OS using Google chrome. Linux Lite ever used Google chrome but now using Chromium. (Because Google will not support Google chrome on linux x32. So, I have to move to similar browser that still can use extension from Google chrome and update still alive for avoid that.)

**Comment by dragonjet** [comment]
What's your screenshot config settings? Like this

![ss 2016-02-08 at 07 50 36](https://cloud.githubusercontent.com/assets/557312/12876239/ad82a190-ce38-11e5-8607-99c521c8a77c.png)

The "Download Sub-directory" is supposed to be an actual subdirectory, **without** the `E:\FolderName1\FolderName2\etc`. It's supposed to be saved into the "Downloads" folder, but we allow you to put a subdirectory name of the Downloads folder.

This setting also affects replay downloads.

**Comment by htomeload** [comment]
Yes, I config settings as picture. I forgot to tell that I ever try even pre-create folder name "KanColle" inside and outside my default Download folder on all OS I have tired but still get error.

For currently, here is error before clear console.
<a href="http://imgur.com/vs3pJRR"><img src="http://i.imgur.com/vs3pJRR.png" title="source: imgur.com" /></a>

Error after clear console.
<a href="http://imgur.com/rTdPlp4"><img src="http://i.imgur.com/rTdPlp4.png" title="source: imgur.com" /></a>

**Comment by dragonjet** [comment]
what OS and dev build are you using now? I may have to ask you to edit a few code, just for logging more info which I will instruct, if you're using one from a "load unpacked extension" build.

**Comment by ReiFan49** [comment]
hmm invalid filename consists of some special/reserved symbols, can i ask you for the admiral name? i'm just afraid if unicodes aren't supported or something though..

**Comment by htomeload** [comment]
@dragonjet Here is info about OS I use currently.
<a href="http://imgur.com/cskO7zb"><img src="http://i.imgur.com/cskO7zb.png?1" title="source: imgur.com" /></a>

For KC3Kai.
<a href="http://imgur.com/NfeKEV2"><img src="http://i.imgur.com/NfeKEV2.png" title="source: imgur.com" /></a>

@ReiFan49 My admiral name is "Kire~desu". It have "~", is it problem ?

**Comment by ReiFan49** [comment]
```Ruby
StringToFileFilter = /[\/\\\:\*\?\"\<\>\|]/ # / \ : * ? " < > |
```
welp.. i don't see tilde on forbidden... except \*nix i guess?
maybe i should try to make a folder with a name contains a tilde..

**Comment by Crazyteitoku** [comment]
@ReiFan49 as far as I understand it the "~" is a special and reserved alias for "home directory" like:
````cd ~````
Goes straight into your home directory or sets your present working directory to home.

**Comment by htomeload** [comment]
I try to rename some file name to "kire~desu" then I open it with chromium then I save it again. I found that file name change a bit from "kire~desu" to "kire-desu".

**Comment by ReiFan49** [comment]
should we change `[Admiral Name]_[Sortie ID].png` into `[Admiral ID]_[Sortie ID].png` then? and test whether it still have problem or not?

**Comment by htomeload** [comment]
@ReiFan49 Um, if file have only number then shouldn't be problem with any admiral name.

**Comment by htomeload** [comment]
Ok, guy. Now I can download replay image now. :D
I edit sortielogs.js, change from name to id. Then It can download but have little problem. Download image is come with "趴￡" in last line of file. How can I remove it ?

**Comment by htomeload** [comment]
I have used "git pull" command and get latest KC3 Kai Dev build in today before testing.

I have setting "Screenshot" section, I change Output Mode to "imgur" and test download replay image(with local edit sortielogs.js at line 635 to make it possible for me.) then hit screenshot button. Everything work well,  replay image can download and screenshot upload success to imgur.
