### ISSUE TITLE
Bring back the Fit Window button

### ISSUE THREAD

**Issue by arghblargh** [KC3Kai/KC3Kai#1130]
The Fit Window button was replaced with the Mute button, but I can already mute the tab through Chrome.

I play KanColle in a separate window, so the Fit Window button is much more useful to me than a redundant mute function.

**Comment by dragonjet** [comment]
humu humu, considering this :+1:

**Comment by joncppl** [comment]
I also use this feature every time I play. __Please__ add it back, there is plenty of room there.

**Comment by jameszors** [comment]
Upvoting this. I use it every time as well. Thanks for always keeping KC3改 top notch :)

**Comment by dragonjet** [comment]
Available in the upcoming `plain` theme, with preview at  #1133 but will also be available in `natsuiro` at a later date
