### ISSUE TITLE
Expeditions cleared but still showing on

### ISSUE THREAD

**Issue by ENE001** [KC3Kai/KC3Kai#1131]
Well i kinda just wanted to report this bug im having since 2015 Mackerel event where i left the expedition on and, the expedition track kept showing until today february 9th, as of now it just shows "unidentified quest", and right now just finished the 3 daily expedition, went to the page for the reward and all, but the kc still thinks i haven´t got it and its showing it (for the rest of this day thou because it happened before, for tomorrow daily it resets as normal)... Not a big problem for me thou, its still a bug :3

**Comment by Crazyteitoku** [comment]
That is a small tracking issue, you will need to reset the quests manually. Go into Strategy room > Quests > Flowchart and the buttons on the top of the page slightly closer to the right of the tabs you will see Reset buttons.

Don't forget that after resetting quests through strategy room, you will need to revisit the Quest section in-game for it to somewhat "keep track" of it again.
