### ISSUE TITLE
Legacy Theme

### ISSUE THREAD

**Issue by dragonjet** [KC3Kai/KC3Kai#1133]
With 26.0, many people were outraged by the removal of the legacy theme. Even if old theme is now generating an error, we should still deal with this.

I'm thinking of making a new theme, out of natsuiro, but will be light-colored and reminiscent of the legacy UI.

**Comment by dragonjet** [comment]
New theme, called `plain`

![ss 2016-02-09 at 10 51 41](https://cloud.githubusercontent.com/assets/557312/12919575/b50d152e-cf7f-11e5-99e7-563fad697013.png)

**Comment by ReiFan49** [comment]
i think the glow on great morale makes the not-so `plain`

**Comment by dragonjet** [comment]
Added at 26.2 in d92a67f611e401d66b81db62d9d914329dda8a7f but is still ongoing enhancement

**Comment by ReiFan49** [comment]
the major different between this and natsuiro is only styles right?

**Comment by dragonjet** [comment]
yep, only colors. and some disabled features. some people complain about natsuiro being cramped with so much data what some others don't need so it's a part of being `plain`. Not the same amount of data as natsuiro, but it works for casuals. i.e. No battle info UI, but has prediction
