### ISSUE TITLE
KC3 winter event FCF glitch?

### ISSUE THREAD

**Issue by Herodouble33** [KC3Kai/KC3Kai#1138]
Hi there,anyone suffering from a glitch while using KC3 when the fleet command facility is activated,somehow after they whited out your ships in the middle of sortie,after the ships are back,they still remain white instead and even after I repaired my ship,the problem still persist,anyone can help?
![kc3 glitch](https://cloud.githubusercontent.com/assets/17173883/12971533/13edda1c-d0d7-11e5-8b2f-2e7803f1c275.JPG)

**Comment by ReiFan49** [comment]
gotta wait for check after commit ee22fc01715778420d6f1aac4df4cb68a5c04549 pushed directly
