### ISSUE TITLE
Ex-Item does not counted towards Equipment

### ISSUE THREAD

**Issue by ReiFan49** [KC3Kai/KC3Kai#1140]
## Problem Details
**Operating System**: Any
**KC3Kai Version**: Webstore/26.0
**Description**: item that placed on extra slot does not count towards ownership of the equipping ship

## Screenshots
In-game and Development Panel: (With **only** damegod that is equipped on ex-slot)
![image](https://cloud.githubusercontent.com/assets/9847780/12975297/18637b4a-d0ed-11e5-8fcd-631439c13120.png)

Before Equipped on Ex-Slot:
![image](https://cloud.githubusercontent.com/assets/9847780/12975330/557ec296-d0ed-11e5-8f5a-b304d4d07a7c.png)

After Equipped on Ex-Slot: (**Damecon** on basic slot, **Damegod** on extra slot)
![image](https://cloud.githubusercontent.com/assets/9847780/12975355/782cc568-d0ed-11e5-9913-019d49e98a5e.png)

**Comment by sinsinpub** [comment]
May fixed by #1339
