### ISSUE TITLE
PoiDBSubmission send wrong data

### ISSUE THREAD

**Issue by Gizeta** [KC3Kai/KC3Kai#1146]
I'm the developer of PoiDB(http://db.kcwiki.moe/).
It seems that PoiDBSubmission send all ship drop data with mapLv=0 which presents the level of the event map(甲=3, 乙=2 and 丙=1). Maybe the code doesn't work correctly.
Here is some data reported by PoiDBSubmission.
![poi-db](https://cloud.githubusercontent.com/assets/1572561/13014290/67fc9b64-d1f6-11e5-84bf-eb1c0b83188d.png)

**Comment by Javran** [comment]
thanks for reporting the issue, I'm the developer of this module, will be working on the fix today.

**Comment by Javran** [comment]
Fix done in branch https://github.com/KC3Kai/KC3Kai/tree/dev-poi-db-submission
needs verification, will do it tonight (EST).

@Gizeta sorry for sending wrong data, the module was made when events were unavailable and I forgot to check if it has worked correctly during events. meanwhiel I also implemented `select_rank` and `pass_event` support, does poi-server welcome submissions to these two APIs? if so, can you make sure to enable CORS support? I keep seeing thse error messages:
![2016-02-12_164216_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/13021705/8f8da78c-d1aa-11e5-8e52-4e7d273446cd.jpg)


@KC3Kai/testers could any of you verify is this db submission is working? you need to checkout remote branch `dev-poi-db-submission` and make sure "Send data to poi-statistics" is enabled in settings. Keep devtools console open and keep an eye on the output:

- when proceeding to battle result screen, see if there are any output reads "PoiDBSubmission: mapInfo debug: {x}", for regular map x is 0, and for event map, x is 1(Easy) or 2(Normal) or 3(Hard) depending on the difficulty you've chosen.
- when clearing an event map, see if there is an output reads "Passing an event map!"

**Comment by dragonjet** [comment]
I'll join in the testing today, but could only do a few runs since 8 bucket :laughing:

**Comment by Javran** [comment]
![2016-02-12_194400_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/13024328/049df2aa-d1c1-11e5-92ec-6b74c882b231.jpg)
mapLv is fixed, I want to see whether pass_event works, need some luck though

**Comment by dragonjet** [comment]
oh I finished E-2 last night. doubt I can finish E-3 soon

**Comment by Javran** [comment]
![2016-02-12_202523_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/13024690/dd13cdee-d1c6-11e5-8a23-cf6cc1304012.jpg)
okay, tested and it's working nicely. Will clean up debugging logs and get ready for PR xD

**Comment by dragonjet** [comment]
alright, will schedule a webstore update tonight so at least people will get notified beforehand of possible auto-updates

**Comment by Gizeta** [comment]
Thanks for fixing the bug.

@Javran
I have told magicae(owner of poi-server) about the missing CORS support, and it has been added now.

**Comment by Javran** [comment]
@Gizeta great! I can confirm submission module is now running without error. you may keep an eye on `select_rank` and `pass_event` data submission from KC3 and see if the format is correct, I just implemented them according to poi's  plugin. our next version is scheduled [on Sat](https://github.com/KC3Kai/KC3Kai/blob/master/update).

**Comment by dragonjet** [comment]
@Gizeta I just want to check up if there are any more wrong data sent? We've updated last week which should have solved the problem. If there's any one or two still sending, it might have been people who has just opened their chrome for a long time and haven't updated, but it should be automatic for everyone.

**Comment by Gizeta** [comment]
@dragonjet 
I have checked the database, and all the drop ship data sent by KC3Kai 26.3 is correct.
Thanks.
