### ISSUE TITLE
Ledger UI

### ISSUE THREAD

**Issue by NizarAI** [KC3Kai/KC3Kai#1148]
Could you group the materials to the numbers a bit more so it doesn't clash with the others?

![screen shot 2016-02-13 at 2 32 58 pm](https://cloud.githubusercontent.com/assets/16519729/13026250/10aa3fc4-d264-11e5-86d1-331ea5d6f070.png)

Sort of like this?

**Comment by ReiFan49** [comment]
![image](https://cloud.githubusercontent.com/assets/9847780/13027893/f9a2d588-d291-11e5-893f-b169542a1134.png)
hmmm something like this?

**Comment by NizarAI** [comment]
@ReiFan49 Yeah, I have trouble making full use of it when every time I look at it, I keep seeing 
-1240 Blowtorches

**Comment by dragonjet** [comment]
@ReiFan49 tell me when you're done with ledger, I can update its UI

**Comment by ReiFan49** [comment]
@dragonjet for now it's ready
