### ISSUE TITLE
Can't increase the game window size

### ISSUE THREAD

**Issue by lastreddit** [KC3Kai/KC3Kai#1149]
I've been trying to increase the Game Player Scale setting from 100% to 200% but nothing seems to be happening.  Or does that setting do something entirely different?

**Comment by mikenzb** [comment]
If you hold down ctrl and scroll up/down you can zoom into the game window to make the game bigger. You can also do this if you zoom in your strategy room to make your strategy room bigger. it applies to the game window too.

**Comment by lastreddit** [comment]
I feel like an idiot now that you mention this. I'm wondering though, what exactly does Game Player Scale do in that case?

**Comment by ReiFan49** [comment]
page zooming applies to a single domain, so basically if you zoom the api page, it'll zoom the strategy ones,
maybe i should checkout this

**Comment by dragonjet** [comment]
> if you zoom the api page, it'll zoom the strategy ones

this is why the gameplayer scale was added. you can change the size of the game area without affecting other extension page. 

one thing to note though is that you will need to refresh the game page after changing the settings

**Comment by dragonjet** [comment]
related and fixed in #1212
