### ISSUE TITLE
Unable to use KC3 on my desktop

### ISSUE THREAD

**Issue by HippoRiko** [KC3Kai/KC3Kai#1150]
Usually when i play Kancolle, i play it on my Desktop on Chrome. Everything worked fine until a few days ago, i was using KC3 on Chrome on my laptop cause i was out, after logging out my laptop and going back to my desktop, i was met with an error when i was trying to sign into DMM. It didn't allow me to log in to my account on my desktop due to some notification error. However, i was able to do it normally on my laptop and other browsers. Is there a way to fix this issue or am i stuck with this for good? FYI, i cleared cache, re-installed KC3, disable abblock, VPN everything but the problem still persist. Hell, i can't even access the DMM website because of the login error.

**Comment by Crazyteitoku** [comment]
This has nothing to do with KC3 Kai.
