### ISSUE TITLE
Request translation repo access

### ISSUE THREAD

**Issue by sinsinpub** [KC3Kai/KC3Kai#1151]
To help update JP translation. See my PR: KC3Kai/kc3-translations#39

**Comment by McDohl** [comment]
@dragonjet seems like team maintainers cannot invite people

**Comment by dragonjet** [comment]
invited to translation team :+1:
you just need to approve it from the [org page](https://github.com/KC3Kai)

**Comment by sinsinpub** [comment]
:smile: thanks.
btw, it's impossible to follow the README directive as there is no privilege for non-member to add any label to issue.
