### ISSUE TITLE
Reset Quests?

### ISSUE THREAD

**Issue by Kuro71** [KC3Kai/KC3Kai#1152]
It would be good to have the option to reset the quests tracked in Natsuiro or Plain theme since legacy is disabled.

**Comment by Crazyteitoku** [comment]
I do believe the quests are tracked, at least for Natsuiro theme.

The new term for "Legacy" theme is now known as "Plain" theme.

**Comment by Kuro71** [comment]
Yes, the quests are tracked, but i was talking about the Reset daily,weekly,etc quest option of the old legacy theme. So you can clear the tracked quests of the game panel.

**Comment by McDohl** [comment]
i dont think theres a plan to let it happen besides we usually suggest to do it on strategy room --> flowchart

**Comment by dragonjet** [comment]
Strategy Room > Flowchart tab
