### ISSUE TITLE
A bug when request behind a proxy

### ISSUE THREAD

**Issue by sinsinpub** [KC3Kai/KC3Kai#1153]
I have met some strange problems when I play with KC3kai v26 in specified environment:
* Ships data corrupt, no any ship showed except combined fleet
* Ship building face disappear no matter there is any building one or not
* Equipment list empty (Strategy Room) if quick data clear is cleared (I have tried: clear quick data, reinstall extension, update Chrome, etc)

Today I tried tracing it at inconvenience laptop environment and finally found some interesting stuffs:
* These Exceptions thrown at extension startup, and the stack trace:
![image](https://cloud.githubusercontent.com/assets/160240/13056422/2b8c38cc-d450-11e5-83e7-e9ffd1330d28.png)
* Following the stack and source code, I am on to the direct reason, that a JST server date-time response header is expected but got none as I'm using ShimakazeGo. (the serverJstTime var become NaN).
![image](https://cloud.githubusercontent.com/assets/160240/13056513/c82ff632-d450-11e5-94bd-b4f433080b7a.png)
* These problems gone if I connect DMM directly or try another proxy impl...

I've no idea about complete solution, but at least there should be a try...catch on invoking these functions (Date.prototype.shiftWeek) or no Exception thrown at all but a logging for debugging instead ...isn't it? 
Javascript exception, u know... :sweat_smile:

**Comment by dragonjet** [comment]
see discussion here: https://github.com/KC3Kai/KC3Kai/issues/1074

especially one comment from @Crazyteitoku https://github.com/KC3Kai/KC3Kai/issues/1074#issuecomment-160431153

he put links on there, try to read on them as well

**Comment by sinsinpub** [comment]
I see. but I'm not requesting 'a support for ShimakazeGo', just considering the 'exception handling'.
There's no reason for our program to just stop when unexpected data is incoming. Exception handling means trying to recovery these 'bad' states to acceptable, not leave them alone, just throw them to console or somewhere else, even if we found them :smile:

**Comment by dragonjet** [comment]
>missing date headers can happen not just in the mentioned software's environment, but also somewhere else, which kc3kai should clearly not be dependent on such a volatile variable

exactly what I said

but I remember something being done about this, but I never followed the progress. In any case closing this thread is because of it being "duplicate" not because we're closing the doors for it. If there will be any updates regarding the date headers, let's continue on the linked threads.

**Comment by ReiFan49** [comment]
missing date headers, should we add some catbomb reminder or something along with forced server date treated as current computer date?

**Comment by dragonjet** [comment]
@ReiFan49 iirc we use timestamps, which should always be in UTC, so if date headers are missing, we should resort to computer time which should generate the same timestamp regardless of where they are

**Comment by ReiFan49** [comment]
![image](https://cloud.githubusercontent.com/assets/9847780/13069211/015589a4-d4b5-11e5-9545-7de2e35ca540.png)
something like this then? (prompt only once per devtools session)

**Comment by sinsinpub** [comment]
I'm reading source codes and considering.
I notice there are plenty of `new Date(headers.Date)` at `Kcsapi.js` for getting the UTC time...All these should be proceeded not only the one at `Request.js`, maybe. :sweat: 
Is this possible that just compute the UTC time from local as a fail-safe fallback, and reminder final user fix their computer clock keep synced?
btw, server response Date header for API always indicates UTC time (I'm not sure), So the var `serverJstTime` name may misleading?

**Comment by dragonjet** [comment]
maybe we need to abstract the get UTC time into a function. iirc it's also being used widely in Kcsapi.js
