### ISSUE TITLE
Storing api master data

### ISSUE THREAD

**Issue by LostLogia4** [KC3Kai/KC3Kai#1157]
Now that the master data is at around 150KB since the Summer event patch, it is now possible to save them in localstorage. This enables us to, among other things, store the version numbers of the shipgirls for the swf links in the ship library.

This thread will cover all potential usage of the api master data that is saved in localstorage in any of KC3Kai functionality, and will be updated accordingly.

**Comment by dragonjet** [comment]
Added the saving of full raw data on localStorage at: 3b07edbcdbc2ac8ee948d8918a34f4736745ad0c
Branch: `dev-rawmaster`
