### ISSUE TITLE
Some form of automatic back up?

### ISSUE THREAD

**Issue by NizarAI** [KC3Kai/KC3Kai#1158]
So my KC3Kai broke... Again
And I lost all of my data.... Again

**Comment by LostLogia4** [comment]
The only way for the extension to implement an automatic backup by itself is by syncing with an online server, a feature that we neither had the money or the coders to implement at the moment.

**Comment by dragonjet** [comment]
@Yukinyaa has been working on a back up tool

**Comment by NizarAI** [comment]
@dragonjet is it possible to download all of the data from the Strategy Room? Lodgers, Histories, Resources etc

**Comment by NizarAI** [comment]
@dragonjet is it possible to download all of the data from the Strategy Room? Lodgers, Histories, Resources etc

**Comment by Yukinyaa** [comment]
Yes it does, but it has some Optimization issues.

**Comment by dragonjet** [comment]
For updates, players can follow https://github.com/KC3Kai/KC3Kai/issues/1106 or https://github.com/KC3Kai/KC3Kai/issues/1105
