### ISSUE TITLE
KC3Kai reset back to iframe menu

### ISSUE THREAD

**Issue by Hikarunu** [KC3Kai/KC3Kai#1160]
Not sure if this is a bug or what, but I noticed my KC3kai when tab left open reset back to iframe menu,
which mean I lost my game progress thanks to that.

KC3kai is latest version, while Google Chrome is latest version
I use KC3kai for a long time already and this is 1st time happened

**Comment by sinsinpub** [comment]
I guess it's thanks to the Chrome new feature: chrome://flags/#automatic-tab-discarding
try to disable it?

**Comment by dragonjet** [comment]
Try to disable the chrome flag that sinsinpub mentioned. Many have reported this to me recently as well and I've been giving the same advice, but no one got back to me if it worked or not.
