### ISSUE TITLE
[Improvement] More noticeable low HP warning

### ISSUE THREAD

**Issue by thorbwahahahaha** [KC3Kai/KC3Kai#1161]
Title says it all, I think it is a pretty simple request.

Make the HP good/critical label more noticeable somehow when there are ships in the red. A simple one would be switching the background.

**Comment by bcc32** [comment]
There is the taiha warning, although some might find that _too_ annoying.

**Comment by SmokeyTheButt** [comment]
It kind of already does that doesn't it? The background switches to red
once a ship is in red and you continue on to the next screen

**Comment by thorbwahahahaha** [comment]
I don't know why I didn't notice that before... I'll go try the setting out

**Comment by ReiFan49** [comment]
the heartbeat **comes from the devtools panel** not from the respective tab, which handled differently though

**Comment by dragonjet** [comment]
Muting taiha heart beat can be tracked here: https://github.com/KC3Kai/KC3Kai/issues/1059
