### ISSUE TITLE
[Feature Request] Manual +1/-1 for quest progress

### ISSUE THREAD

**Issue by c933103** [KC3Kai/KC3Kai#1175]
Per http://electronicobserver.blog.fc2.com/blog-entry-52.html , doing so can allow accurate quest tracking even when user do part of their quest without kc3kai

**Comment by bcc32** [comment]
Strategy Room > Flowchart

**Comment by LostLogia4** [comment]
Seems like our Flowchart menu in Strategy Room goes under the radar.

**Comment by dragonjet** [comment]
this probably calls for a more user-friendly approach. probably an on-hover on the quest list with a button that says "manage quests" and opens the flowchart. however on-hover is now used for title attributes to display tooltip of the whole quest name, or the whole quest count (Bw1). I'll think about this.
