### ISSUE TITLE
Voice filenames got updated again

### ISSUE THREAD

**Issue by gakada** [KC3Kai/KC3Kai#1180]
New keys for `voiceLineKeys` in https://github.com/KC3Kai/KC3Kai/blob/master/src/pages/strategy/tabs/mstship/mstship.js:

```
[604825,607300,613847,615318,624009,631856,635451,637218,640529,643036,652687,658008,662481,669598,675545,685034,687703,696444,702593,703894,711191,714166,720579,728970,738675,740918,743009,747240,750347,759846,764051,770064,773457,779858,786843,790526,799973,803260,808441,816028,825381,827516,832463,837868,843091,852548,858315,867580,875771,879698,882759,885564,888837,896168]
```

**Comment by dragonjet** [comment]
thanks again for finding this out every time :+1: 

this might become a problem once we start detecting voice numbers for subtitling.

**Comment by LostLogia4** [comment]
Updated now.

Reference code (Valentine + Hinatsuri):
```
608614, 611089, 612644, 615991, 624682, 632529, 636124, 637891, 641202,
643709, 653360, 658681, 663154, 670271, 676218, 685707, 688376, 697117,
703266, 704567, 711864, 714839, 721252, 729643, 739348, 741591, 743682,
747913, 751020, 760519, 764724, 770737, 774130, 780531, 787516, 791199,
800646, 803933, 809114, 816701, 826054, 828189, 833136, 838541, 843764,
853221, 858988, 868253, 876444, 880371, 883432, 886237, 889510, 896841
```

Reference code (White Day):
```
604825, 607300, 613847, 615318, 624009, 631856, 635451, 637218, 640529,
643036, 652687, 658008, 662481, 669598, 675545, 685034, 687703, 696444,
702593, 703894, 711191, 714166, 720579, 728970, 738675, 740918, 743009,
747240, 750347, 759846, 764051, 770064, 773457, 779858, 786843, 790526,
799973, 803260, 808441, 816028, 825381, 827516, 832463, 837868, 843091,
852548, 858315, 867580, 875771, 879698, 882759, 885564, 888837, 896168
```

**Comment by LostLogia4** [comment]
Updated now.

Reference code (Valentine + Hinatsuri):
```
608614, 611089, 612644, 615991, 624682, 632529, 636124, 637891, 641202,
643709, 653360, 658681, 663154, 670271, 676218, 685707, 688376, 697117,
703266, 704567, 711864, 714839, 721252, 729643, 739348, 741591, 743682,
747913, 751020, 760519, 764724, 770737, 774130, 780531, 787516, 791199,
800646, 803933, 809114, 816701, 826054, 828189, 833136, 838541, 843764,
853221, 858988, 868253, 876444, 880371, 883432, 886237, 889510, 896841
```

Reference code (White Day):
```
604825, 607300, 613847, 615318, 624009, 631856, 635451, 637218, 640529,
643036, 652687, 658008, 662481, 669598, 675545, 685034, 687703, 696444,
702593, 703894, 711191, 714166, 720579, 728970, 738675, 740918, 743009,
747240, 750347, 759846, 764051, 770064, 773457, 779858, 786843, 790526,
799973, 803260, 808441, 816028, 825381, 827516, 832463, 837868, 843091,
852548, 858315, 867580, 875771, 879698, 882759, 885564, 888837, 896168
```

**Comment by gakada** [comment]
Number of keys is number of voice lines + 1 (54, so 9*6 is arbitrary), also, those keys can be replaced with differences (53 keys, one per each line):

    // Valentine + Hinatsuri
    var keys = [2475, 1555, 3347, 8691, 7847, 3595, 1767, 3311, 2507, 9651, 5321, 4473, 7117, 5947, 9489, 2669, 8741, 6149, 1301, 7297, 2975, 6413, 8391, 9705, 2243, 2091, 4231, 3107, 9499, 4205, 6013, 3393, 6401, 6985, 3683, 9447, 3287, 5181, 7587, 9353, 2135, 4947, 5405, 5223, 9457, 5767, 9265, 8191, 3927, 3061, 2805, 3273, 7331]

    // Valentine + Hinatsuri
    var keys = [2475, 6547, 1471, 8691, 7847, 3595, 1767, 3311, 2507, 9651, 5321, 4473, 7117, 5947, 9489, 2669, 8741, 6149, 1301, 7297, 2975, 6413, 8391, 9705, 2243, 2091, 4231, 3107, 9499, 4205, 6013, 3393, 6401, 6985, 3683, 9447, 3287, 5181, 7587, 9353, 2135, 4947, 5405, 5223, 9457, 5767, 9265, 8191, 3927, 3061, 2805, 3273, 7331]

so that `voiceLineKeys` is

    return 100000 + 17 * (ship_api_id + 7) * (keys[voice_line_id - 1]) % 99173;

only keys[1] and keys[2] changed (for secretary 1 and 2).

**Comment by LostLogia4** [comment]
but where do we store the initial value?

**Comment by dragonjet** [comment]
hm we might need to store this now online so if anything changes, the client data can adapt

**Comment by gakada** [comment]
Don't know if it helps, but if `voice_line_id` is known (on a mismatch), then it's possible to automatically update the keys without going through Core decoding every time

    if (getVoiceLineFileName(ship_api_id, voice_line_id) !== filename) {
      var newKey = solveForKey(ship_api_id, filename);
      if (newKey) {
        voiceLineKeys[voice_line_id - 1] = newKey;
      }
    }

    function solveForKey(ship_api_id, filename) {
      for (var i = 0; i < 1000; ++i) { // 17 * (500 + 7) * 10000 / 99173 = 869
        var a = filename - 100000 + i * 99173, k = 17 * (ship_api_id + 7);
        if (a % k === 0) {
          return a / k;
        }
      }
      // log ship_api_id, filename somewhere
      return undefined;
    }

**Comment by dragonjet** [comment]
was able to make `dev-subtitle` branch work again at #751. I wanna thank you again @gakada for your work for the community :+1:

**Comment by dragonjet** [comment]
Now I got a long weekend and my mind cleared up, I re-read @gakada's posts. I understand now. Voice lines are determined by their difference, not necessarily dependent on the set of keys used. With it, we could easily determine which voices changed, etc. I will try to come up with a logic that will fit KC3's subtitle feature better.

**Comment by dragonjet** [comment]
since I only see updates in Poke 1 for white day, can we assume `1471` is the original value for Poke 2?

**Comment by gakada** [comment]
Mogami also has [Poke 2](http://kancolle.wikia.com/wiki/Seasonal/White_Day_2016#Mogami) (100000 + 17 * (70 + 7) * 1471 % 99173 -> http://203.104.209.71/kcs/sound/kclcmobkdeizph/141252.mp3).

**Comment by dragonjet** [comment]
@gakada what I'm currently doing in subtitles is like this

I followed your voice key diff, but I put poke 1 and 2 as `0` coz we don't know the original yet
```
voiceDiffs: [
	2475,    0,    0, 8691, 7847, 3595, 1767, 3311, 2507,
	9651, 5321, 4473, 7117, 5947, 9489, 2669, 8741, 6149,
	1301, 7297, 2975, 6413, 8391, 9705, 2243, 2091, 4231,
	3107, 9499, 4205, 6013, 3393, 6401, 6985, 3683, 9447,
	3287, 5181, 7587, 9353, 2135, 4947, 5405, 5223, 9457,
	5767, 9265, 8191, 3927, 3061, 2805, 3273, 7331
],
```

I also added the special diffs for seasonal lines
```
specialDiffs: {
	"1555": 2, // valentines 2016, hinamatsuri 2015
	"3347": 3, // valentines 2016, hinamatsuri 2015
	"6547": 2, // whiteday 2015
	"1471": 3 // whiteday 2015
},
```

I used your `solveForKey` function to compute for the "diff ID" on the fly using ship ID and filename
```
getVoiceDiffByFilename :function(ship_id, filename){
	ship_id = parseInt(ship_id, 10);
	var k = 17 * (ship_id + 7), r = filename - 100000;
	for (var i = 0; i < 1000; ++i) {
		var a = r + i * 99173;
		if (a % k === 0) {
			return a / k;
		}
	}
	return false;
},
```

and in the end, for the subtitles where we only know the ship_id and filename:
```
getVoiceLineByFilename :function(ship_id, filename){
	var computedDiff = this.getVoiceDiffByFilename(ship_id, filename);
	var computedIndex = this.voiceDiffs.indexOf(computedDiff);
	return computedIndex > -1 ? computedIndex+1 : computedDiff;
},
```
If computed diff is not in the existing voiceDiffs, this will return the computedDiff itself - it's like the "diff ID" is the voice line number itself (`6547` is returned as the voice line number)

so that on the quotes JSON, we can just add the "diff ID" as the seasonal quote

```
"434": {
    "1": "I'm Mutsuki. Let's work together!",
    "2": "Oh? Admiral? You called Mutsuki?",
    "3": "What is it~What is it~?",
    //...........
    "6547": "Umm, I made some cookies for Kisaragi and the Admiral.... Would you like to try some?~"
},
```

in case `6547` is not found in the quotes, it will check the number in `specialDiffs`, and if found, will use the default voice for that
```
"6547": 2, // whiteday 2015
```
so it will use line number 2 (the original poke 1)

the down-side is that we have to make sure all quotes are filled each update so there will be no wrong subtitles.
