### ISSUE TITLE
seaplane updates

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#1181]
Due to recent updates, seaplane can now have both improved level and proficiency.
We might need to:

- [x] show both improved level and proficieny in UI
- [x] figure out improvement effects on seaplaces (might have something to do with air power)

meanwhile we can think about the first task.
second one is still under investigation, and might take a long time.

**Comment by LostLogia4** [comment]
Maybe prepend the stars into before the plane rank?

**Comment by dragonjet** [comment]
the good thing is, we already show seaplanes in strategy room proficiency tab. and Gear.js detects any proficiency as long as it has `api_lv`, and natsuiro.js shows anything with `ace` value. might not need further adjustments to UI.

the 2nd one, another thing to wait the wikia for :sweat_smile:

**Comment by Javran** [comment]
@dragonjet equipments on devpages might need some adjustment to show both, as an example the following is Tone equipped with an obs plane, max proficiency and +1 improvement, but only proficiency is shown:

![2016-03-14_141510_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/13754975/66edd72c-e9ef-11e5-98dd-ffb6778d3ec2.jpg)

**Comment by dragonjet** [comment]
ahh good point, but I never knew seaplanes could be improved, via akashi? or was that the update?

**Comment by Javran** [comment]
@dragonjet yes, seaplanes are now improve-able via akashi:

![2016-03-14_221638_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/13765747/8ce21432-ea32-11e5-8d36-7564027eaf0f.jpg)

so they now have both proficiency and improvement level.

**Comment by arialypse** [comment]
[Bug] Type 2 Seaplane Fighter Kai Don't add any ELOS to fleet status
![05-04-2559 16-55-58](https://cloud.githubusercontent.com/assets/13535817/14277903/6456d1e6-fb4f-11e5-8b16-2e6c26145100.jpg)

**Comment by Javran** [comment]
bumping this issue, I think we need some priority on this, as more and more fighters are becoming improvable...

**Comment by Javran** [comment]
@arialypse just notice your report, I think the ELOS has been taken into account in Formula 33 which is now the default LoS shown in the panel:

without improvement: (3 obs plane)
![2016-07-17_144518_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/16899194/57c903de-4c2d-11e6-92c4-02dff6fb72e0.jpg)

with improvement: (3 obs plane, 2 improved to +1)
![2016-07-17_144610_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/16899201/7f94371c-4c2d-11e6-91c6-265979c66369.jpg)
