### ISSUE TITLE
Strategy Room to-enhance Index

### ISSUE THREAD

**Issue by LostLogia4** [KC3Kai/KC3Kai#1182]
Opened this issue to keep track of all of these requests.
- Improvement for Leveling tab:
  - Tracked in #1164
  - Goal template implementation in #1112
- Improvement for Akashi tab:
  - Tracked in #944
  - Planner proposed in #1183 
- Improvement for Aircraft tab:
  - Discussed in #1181
- Improvement for Expedition History tab:
  - Tracked in #1024
- Improvement for Sortie History tab:
  - PvP history mentioned in #904.
- Improvement for Library Ships tab:
  - Version params link tracked in #1030, pending release in v27.
  - Voice links tracked in #1180.
- Improvement for Library Encounter tab:
  - Tracked in #1139
- Help Page Improvement
  - Tracked in #1179, partially implemented

All of the aforementioned issues is now listed in SR Enhancement milestone.

**Comment by sinsinpub** [comment]
anyone would like to try #1179 (in branch `dev-sroom-helps`) ?
it's convenience that link to ship/gear library from everywhere :smile_cat:

**Comment by dragonjet** [comment]
We can now use [GitHub Projects](https://github.com/KC3Kai/KC3Kai/projects) for organizing lists.
