### ISSUE TITLE
Admiral Panel to-enhance Index

### ISSUE THREAD

**Issue by LostLogia4** [KC3Kai/KC3Kai#1187]
- Enhancement for Natsuiro Theme
  - Previous encounter table: Discussed in #1142
  - Resupply tallied in Activity Tab: Discussed in #1082
  - Base PvP EXP in in Activity Tab: Discussed in #904
  - AACI flag detection: Fulfilled by #1294
- Reintroduction of Plain (Legacy) Theme
  - Discussed in #1133, implemented as of v27.
- Theme-independent Enhancement
  - Heartlock reminder: Discussed in #1137 and #1016 
  - 201 error detection: Discussed in #1267

**Comment by dragonjet** [comment]
We can now use [GitHub Projects](https://github.com/KC3Kai/KC3Kai/projects) for organizing lists.
