### ISSUE TITLE
[Bug] Fleet Command Facility Display bug left over from winter event.

### ISSUE THREAD

**Issue by Alexavis** [KC3Kai/KC3Kai#1190]
KC3 kai still has the leftover glitched display for ships retreated with the fleet command facility item. Yuudachi, Ayanami and Verniy were all retreated using the equipment during winter event and KC3 still has the white outline from it. Not really bothering right now, but for next event it will become confusing.

http://imgur.com/W8dHCRB

**Comment by dragonjet** [comment]
Strategy Room > Profile > Clear FCF Infections

**Comment by mikenzb** [comment]
As I learnt today... you need to have kancolle closed before you run that fix... I was wondering why it wasn't working.
