### ISSUE TITLE
[for scn translators] some rules to keep in README.md

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#1192]
For those who can't read Chinese, I just want to have some discussion among scn translator about putting some rules in https://github.com/KC3Kai/kc3-translations/blob/master/data/scn/README.md for future translators to know.

cc  @Diablohu @Nangcr @sinsinpub 

因为最近参与中文翻译的多了些,希望在 https://github.com/KC3Kai/kc3-translations/blob/master/data/scn/README.md 放一些规则性的东西供将来参考,同时也是避免每做一点改动都发PR刷大家的通知.

目前草拟规则:

* 版面宽松的情况下尽量使用全角标点符号
* 以下情况可以直接push至repo:
    * 翻译缺失项目(包括将现存英文条目翻译中文)
    * 修正笔误 / 调整缩进
* 修改已有翻译超过三条请尽量发PR并cc其他scn翻译者
* 统一缩进? (此项不确定大家的偏好,一开始缩进有点乱我全用空格缩进了,但是感觉其他的目录用的全是tab)
* 其他情况下可自行判断

**Comment by Javran** [comment]
额没有收到回复...给一星期时间,如果没有异议的话我就把这部分写进README了.

**Comment by Diablohu** [comment]
你看，你这贴子就没用全角标点！

说起标点，装备名里的括号是不是要统一下？我个人觉得半角和全角都可以

**Comment by Javran** [comment]
@Diablohu 我个人日常习惯用半角标点,翻译的时候会注意的...

装备名我觉得可以统一下用半角.刚才看了下原始装备名也都是半角.

**Comment by Javran** [comment]
加上两个改动:

- 装备中的括号使用半角
- 缩进就和其他目录一样都改成tab了

如果没异议的话,我就把上述东西写到README.md里去了?

**Comment by Javran** [comment]
已经写在README.md里了:
https://github.com/KC3Kai/kc3-translations/blob/master/data/scn/README.md
今后按这个规则来就行,减少点PR的必要.
