### ISSUE TITLE
battleforecast cannot work

### ISSUE THREAD

**Issue by yeshasuicide** [KC3Kai/KC3Kai#1202]
I have removed this app and reinstalled it for several times ,but it doesn't work.
for version 27.2
![qq 20160319210138](https://cloud.githubusercontent.com/assets/17948412/13898735/74875d60-ee16-11e5-823f-0b6034726b39.png)

**Comment by dragonjet** [comment]
I checked an I encounter this problem for maps without gauges. Trying to do another hotfix 27.4, thanks for reporting :+1:

**Comment by LostLogia4** [comment]
...at this rate we'll hit version 28 by the time we fixed everything...
