### ISSUE TITLE
Reload Confirmation

### ISSUE THREAD

**Issue by boreslayer** [KC3Kai/KC3Kai#1206]
Even though I have the exit confirmation box checked, KC3Kai does not give me the reload warning as seen in the link below.  It just closes my window/tab when I click on the 'X'  

https://gyazo.com/611fd5c121f70d8f3121df36e0207bad

Is this a bug from KC3Kai or just my end?

**Comment by dragonjet** [comment]
probably a side-effect from the reverts made in API page last night. will mark as bug until I check it out in my desktop. still in bed atm
