### ISSUE TITLE
[Bug report] Rank point cutoff time incorrect

### ISSUE THREAD

**Issue by HKGPsy** [KC3Kai/KC3Kai#1207]
The current rank point counter updated two times a day at [GMT+9] 03:00 and 15:00.
.
Although the in game rank list update at [GMT+9] 03:00 and 15:00, the actual cutoff time is [GMT+9] 02:00 and 14:00. In other word, the cutoff time is 1 hour before the update of rank list.

Besides, is it possible to add a function to manually reset the counter?

**Comment by dragonjet** [comment]
This 1 hr cut-off correction is tracked here #1004
This will stay open as the suggestion to add "manual rank point reset button"

**Comment by sinsinpub** [comment]
and when I read codes, I found that profile tab of SR never display the values of `Amount earned on previous cut-off` and `Cut-off value from last interval`...
