### ISSUE TITLE
localstorage.maps = 'null'

### ISSUE THREAD

**Issue by Yukinyaa** [KC3Kai/KC3Kai#1210]
I recently cleared local storage data,
and I have no idea why but, localstorage.maps remains 'null'.
this causes map tab to be distorted with error ```Uncaught TypeError: Cannot read property 'm11' of null```, 
and sortie log not being displayed.

**Comment by LostLogia4** [comment]
Plane key is not recorded either it seems...

**Comment by dragonjet** [comment]
I figured this would happen. I knew it, but failed to act upon it. I saw it happen to me, and had to remove my localSotrage to make it work again. I experienced it at a specific sub-version of v27. Well - I actually fixed the saving of `maps` here: f1c7940e36aee4a54b3cd5d595aee9fa6672faa0

However, I failed to put a check that if `maps` in localStorage is already bugged to `null`, to reset it to a working version.

**Comment by Yukinyaa** [comment]
edit : no, sortie log is being recorded, but sortie log is not being displayed

**Comment by dragonjet** [comment]
but let me make this clear, I didn't cause the bug, I just experienced it myself :sweat_smile: 

@Yukinyaa the reason why it's still `null` even though you've been revisiting the sortie page is that it currently just extends the existing `localStorage.maps` into the new data. so if you already have an existing maps = null.. then `null extend newdata = null`
