### ISSUE TITLE
KC3 not retrieving data from KC

### ISSUE THREAD

**Issue by Shimakazze** [KC3Kai/KC3Kai#1213]
I completed a quest whilst the KanColle tab was closed, so when I reopened the tab, the completed quest stayed there. So I cleared all the data in KC3 via the Strategy Room, but now whenever I load the game via the KanColle tab, there is no data retreived: no fleet status, no quest status, it just shows that I have 0 ships. I tried reinstalling it and it stayed the same. Is it a bug or am I missing something?

**Comment by LostLogia4** [comment]
It's a bug. KC3Kai is currently at open beta stage atm.

**Comment by dragonjet** [comment]
next time the quest thing happens, you can just go to the strategy room, under flowchart tab to manage quest states or counts. this feature was made exactly for this situation where quests are completed on other computers, other viewers, or just when the panel is closed.

when you clear the data via strategy room > profile, it should clear everything - not just quests. so the next step is to re-enter the game while devtools panel is open to re-fill the data

**Comment by dragonjet** [comment]
Also similar: #1215
