### ISSUE TITLE
Panel KC3 isn't working properly

### ISSUE THREAD

**Issue by RitoMatsushima** [KC3Kai/KC3Kai#1215]
Right at the Internet cafe. I tried to play KC, so when I log on my DMM account and loading the game. It's weird, my panel won't show anything such as my shipgirls and everything in there. 

Help, is there any solution behind this problem?

Here's the picture:
Imgur: http://imgur.com/51iTsmE

**Comment by MrThisguy978** [comment]
I'm having a similiar problem where some of the data is pulled but other parts are left incomplete, like the max for both ships and equipment and fleets. On a side note, game player scale also does not seem to be working either.

Link: http://i.imgur.com/unCbi0F.jpg

**Comment by dragonjet** [comment]
@RitoMatsushima how about yours? was it fixed in 27.6 or not yet?

**Comment by RitoMatsushima** [comment]
Sorry for the late reply. 

Previous update is fixed. Until now, the problem is still same. (Current update: 28.3)

**Comment by dragonjet** [comment]
were you opening the F12 panel before game start button?

**Comment by RitoMatsushima** [comment]
Yes, I did.

Proof: http://imgur.com/UHJtRWg

**Comment by dragonjet** [comment]
the last pic you have is a symptom of an old version, can you check if you're on latest 28.3

**Comment by dragonjet** [comment]
Fixed in various 28.x updates, most probably including #1271
