### ISSUE TITLE
Mission kept showing in KC3Kai after its actually finished.

### ISSUE THREAD

**Issue by FrontBlood** [KC3Kai/KC3Kai#1216]
I took the second step mission for getting Z1. After 48 hours, I finished it and accepted the third step. However, the mission part of the KC3Kai still showing the 2nd mission as accepted.

This also happened to me in another day. I took the daily mission of Akashi and finished it. The mission showed as finished 1/1 but remained there for the rest of the day. It kept there until the daily mission refreshed.

http://i.imgur.com/HipjDoC.png
http://i.imgur.com/1r5oLHU.png
http://i.imgur.com/PK4CW6Q.png

**Comment by FrontBlood** [comment]
Found the solution.
[https://github.com/KC3Kai/KC3Kai/issues/1213](url)

KC3Kai Strategy Room→Quests→Flowchat→Reset Quests.

**Comment by Yukinyaa** [comment]
Glad you found the solution ```:D```
