### ISSUE TITLE
Display bug with API link and Frame

### ISSUE THREAD

**Issue by lojzek91** [KC3Kai/KC3Kai#1217]
Basically, if I try to play the game via either of those options, I get a display that is ridiculously small. When I start the game, there's only the upper left part of the game screen showing. It has only happened now. Earlier I was able to play normally, right now I can only do it via DMM.com.

Album: http://imgur.com/a/z0GWb

**Comment by dragonjet** [comment]
go to settings > game player scale > make it 100

**Comment by lojzek91** [comment]
Works, thanks! I'm interested as to how it came to be, though... I haven't touched any settings for at least a week.

**Comment by dragonjet** [comment]
you might have enabled it, and didn't work before so you didn't notice. we recently just re-implemented scaling in the latest version, but the setting is still saved so it automatically applied when you updated
