### ISSUE TITLE
0 sortie data for today / this week & month

### ISSUE THREAD

**Issue by LostLogia4** [KC3Kai/KC3Kai#1220]
There's no sortie or PvP data in version 27.6, unless if I lookup at previous times.

![blob](https://cloud.githubusercontent.com/assets/12930396/14011142/1557f2cc-f1d7-11e5-8973-a921c817a4e1.png)

Apparently the old DB model isn't compatible with the current version, since it starts on the day I installed the latest version.

**Comment by ReiFan49** [comment]
#1209 handles it

**Comment by LostLogia4** [comment]
Gotta resolve the conflict and merge the pull request before this issue is closed.
