### ISSUE TITLE
[Suggestion] Adding new formula for LoS calculation

### ISSUE THREAD

**Issue by HKGPsy** [KC3Kai/KC3Kai#1223]
The new "33 Los formula" had been shown to be more accurate than the old formula. It would be nice if the next update can include this new formula as a reference for player.

Here is the source for the formula
http://ja.kancolle.wikia.com/wiki/%E3%83%9E%E3%83%83%E3%83%97%E7%B4%A2%E6%95%B5

**Comment by c933103** [comment]
Sth similar is also available in Formula 33 section in EN Wikia's LoS
section. (despite indirect).

Note that other viewer like poi viewer have already included the new LoS
calculation method.
2016/03/25 14:46 "HKGPsy" <notifications@github.com>:

**Comment by dragonjet** [comment]
Merged #1352
