### ISSUE TITLE
Blank menu, cannot open panel

### ISSUE THREAD

**Issue by rimedigit** [KC3Kai/KC3Kai#1224]
http://imgur.com/rToS423

As you can see my Kc3kai icon isn't gold, it's dark orange and the menu, which I can't screenshot, is blank with only the icons visible, and below all the timers are zeroes. Clicking on any menu option does not open up Kc3kai, nor with F12, the page is completely blank. 
I tried to download the zip first, then I git cloned the repo, then I closed all other applications and did it again. I also tried it with Chromium, just to check (cleared the cache/cookies/passwords, everything), but with the same result. 
-> Chromium, though, links to the "errors" section where the following line is highlighted: 

"console.log("KC3改 Messengers loaded");"

I browsed the "issues" section but couldn't find the same as mine. If I didn't look hard enough, would you please point me to it?
(Normal Kc3kai works fine, I just wanted to try the dev build).

**Comment by dragonjet** [comment]
downloading the zip wouldn't work as dev build since we separated the translations into another repository, thus you cannot see most words, and features are not expected to work correctly.

In order to use dev build, you might want to use a git client to "clone" this repository into your computer, then do a submodule update to also pull in the translations.

**Comment by rimedigit** [comment]
I see. I have experience with Git for Desktop and Tortoise, and a bit with Smartgit and GitEye. 
Do you suggest a specific client?

**Comment by rimedigit** [comment]
http://imgur.com/TcQtnvW

Turned out Tortoise is still more than enough for something so simple. I just updated the submodules, as you said. Thanks DJ.

**Comment by dragonjet** [comment]
:+1: good to see more trying out dev builds
