### ISSUE TITLE
Wrong line of Kasumi

### ISSUE THREAD

**Issue by Agc0de6** [KC3Kai/KC3Kai#1233]
![2016-03-27 1](https://cloud.githubusercontent.com/assets/14156630/14065037/ac1fd334-f432-11e5-98ed-8ae310087cd1.png)

**Comment by dragonjet** [comment]
a part of the large subtitle feature, where we're not yet done with verification:

Verification instructions:
https://github.com/KC3Kai/KC3Kai/pull/1186#issuecomment-201733667

Continue Tracking thread:
https://github.com/KC3Kai/KC3Kai/issues/751#issuecomment-202033407
