### ISSUE TITLE
Preliminary check to save time

### ISSUE THREAD

**Issue by rephira** [KC3Kai/KC3Kai#1234]
As I have realized there are nearly 17K line in the quotes.json.

While it does sound really daunting, a lot of this 17K lines can actually be reduced imo.
As a matter of fact I think this work should be done before any of the languages go into subtitle translation

https://docs.google.com/spreadsheets/d/1wg7pCv3l6g8BfOye3-DbrCuYDhTvSX4h1UuiRCp0_K8/edit?pref=2&pli=1#gid=588353302

I took the liberty of adding a new sheet to the subtitle verification spreadsheet.
The point is to identify when a specific voice line changes as a ship goes through remodel.

Wikia may be a good starting point for populating this. Eventually I would like to do a full scale check... but that will take way too much time which will take translator's time away from actually doing QC.

We could probably work out division of labor as well.

**Comment by dragonjet** [comment]
the problem is, sometimes only kai ones got seasonal lines, but normally they'd be different voice, so we should still be able to support individual IDs

**Comment by LostLogia4** [comment]
How about prioritized referrals like this one? 

```
    "275": {
        "base":"80"
        "1": "I, Nagato, still won't lose to newcomers.",
        "4": "W-wha, n-no, I-I... don't hate it.",
```
With api_id for Nagato = 80 and Nagato Kai = 275, line 1 and 4 is different, while Line 2, 3 and 25 is different. That way it'll refer to 

Also, for seasonal lines, i would prefer it to have their own json file (with api_id and quote number swapped) for easier editing.
```
"WhiteDay": {
    "2": {
        "42": "Admiral! Here! Give me the best return gift for Valentine's! Eh!? There isn't any~!? ",
        "43": "Admiral, is....this....for me? Thank you!",
        "44": "Hmm.... A return gift for Valentine's? It's going great. Murasame has been expecting this. ",
        "45": "What is this package, Admiral? Smells nice~ It's cookies-poi! Perhaps these are handmade-poi?"
        }
}
```

**Comment by sinsinpub** [comment]
shipgirl's name should be shown with underline in front of subtitles :trollface:

**Comment by rephira** [comment]
Okay just finished sorting shit out XD
