### ISSUE TITLE
Latest Devbranch pull

### ISSUE THREAD

**Issue by SmokeyTheButt** [KC3Kai/KC3Kai#1235]
So I just pulled the newest Devbranch (28.2) and now nothing shows up.
http://puu.sh/nVW6u/7666386ae7.jpg

Suggestions on what to do or what could be causing it?

**Comment by dragonjet** [comment]
try to do submodules update

**Comment by SmokeyTheButt** [comment]
Ah ha! Yeah that fixed the problem. Everything is displaying now

Thanks, DJ!

**Comment by dragonjet** [comment]
:+1:
