### ISSUE TITLE
Murasame expedition line translation

### ISSUE THREAD

**Issue by DrDDevil** [KC3Kai/KC3Kai#1236]
---Not sure in should be a separate thread, but---
Apparently, Murasame uses Line for (equipment-2) which is "I can do it!" for the expeditions.
Translation in kc3 is saying "Murasame, Power-u~p!".
![m](https://cloud.githubusercontent.com/assets/18104975/14067950/d3cf2b78-f441-11e5-8b91-1c1bac08b8d2.JPG)
Solution -- exchange translation from equipment 3 to equipment 2.

**Comment by LostLogia4** [comment]
Currently tracked [here](https://docs.google.com/spreadsheets/d/1wg7pCv3l6g8BfOye3-DbrCuYDhTvSX4h1UuiRCp0_K8/edit)
