### ISSUE TITLE
Taigei's subtitles are Ryuuhou's

### ISSUE THREAD

**Issue by rimedigit** [KC3Kai/KC3Kai#1239]
http://imgur.com/a/MqAc0

I looked for an identical topic but I didn't find one so I guess this is my bug report as tester. 
Well, just what the title says. Taigei's subtitles (I like this thing by the way) are Ryuuhou's. I took a couple of screenshots to provide proof. 
(VERSION 28.2)

**Comment by dragonjet** [comment]
Currently tracked [here](https://docs.google.com/spreadsheets/d/1wg7pCv3l6g8BfOye3-DbrCuYDhTvSX4h1UuiRCp0_K8/edit)
