### ISSUE TITLE
jszip library missing

### ISSUE THREAD

**Issue by LostLogia4** [KC3Kai/KC3Kai#1240]
Missing jszip library prevented the data backup function from working properly in webstore version.

Error 404 chrome-extension://hkgmldnainaglpjngpajnnjfhpdjkohh/assets/js/jszip.min.js

**Comment by dragonjet** [comment]
I'll take care of this

**Comment by sinsinpub** [comment]
but what is the reason for grunt copy task not including all assets (eg `*.min.js`)?

**Comment by dragonjet** [comment]
@sinsinpub need to add it to gruntfile > initConfig > copy > statics > src
