### ISSUE TITLE
[Request] Flash Quality Changer

### ISSUE THREAD

**Issue by pwjusticed** [KC3Kai/KC3Kai#1242]
If possible, I'd like an option to change the flash quality. Is there a way to change the flash quality anyway? I've tried using FRQc to change the quality but, it doesn't seems to work.

**Comment by LostLogia4** [comment]
Lemme guess, performance issue?

**Comment by pwjusticed** [comment]
Yeah specifically when I'm playing on my Windows tab. It's a low end one, so it sometimes has frame lags and high memory consumption, especially during the battle.

**Comment by Yukinyaa** [comment]
I did some research, and there is currently no way to change quality of flash except html <object>tag.

**Comment by dragonjet** [comment]
@Yukinyaa in that case, unfortunately we can't fulfill this, as we are using iframe on API links, and we have no control over the flash client when on DMM frame or DMM website.

If anyone else have an idea, feel free to re-open the issue.
