### ISSUE TITLE
databackup broken on webstore build

### ISSUE THREAD

**Issue by Yukinyaa** [KC3Kai/KC3Kai#1244]
Error says : JSZip not detected.
I think this problem came from minifing process.
(could try not minifing already processed files)

**Comment by LostLogia4** [comment]
Already referenced in #1240
It's because it has to be registered into statics in gruntfile.js, otherwise the minifier (grunt) won't include it.

**Comment by Yukinyaa** [comment]
@LostLogia4 I have to read
