### ISSUE TITLE
Missing Icons as of 31/3

### ISSUE THREAD

**Issue by kololz** [KC3Kai/KC3Kai#1247]
**Satsuki** is angry now.
**Artillery IMPs** are going to crush our home now.
**Seaweed** is not satisfied with KC3Kai now.

Just a reminder.

**Comment by LostLogia4** [comment]
Seaweed?

**Comment by kololz** [comment]
The new Isolated Demon Hime.
**Ooshio** is now bragging for the new image too.

**Comment by dragonjet** [comment]
Seaweed = nagatsuki?

**Comment by LostLogia4** [comment]
Seaweed = Isolated Demon Hime
