### ISSUE TITLE
Screenshot resizing broken post Ver 28

### ISSUE THREAD

**Issue by rephira** [KC3Kai/KC3Kai#1248]
Seems like following the implementation of version 28, the screenshot resizing is malfunctioning.

This picture was taken when the Game Player Scale in the settings was set to 120%. As you can see the picture is somewhat off in the first place, while the right side looks like it's all white, it is actually all empty. (Image format is PNG. Probably the reason why)

![2016-04-01 01-44-35 71](https://cloud.githubusercontent.com/assets/13478649/14183596/061cdc02-f7ac-11e5-9c11-bf19cb1f6ce6.png)

100% scale looks and functions fine, as below.

![2016-04-01 01-36-36 56](https://cloud.githubusercontent.com/assets/13478649/14183595/04fc51e0-f7ac-11e5-8b4d-1e7ca42d12ae.jpg)

Anyone have any short answer and likelihood of resolution of this?

@dragonjet @LostLogia4 @Javran

**Comment by dragonjet** [comment]
this is related to the devicePixelRatio scaling applies to screenshots on v28 to support retina and other high density displays. these might be chrome detecting dppx wrongly.

the solution i can think of for this is just to let users to manually check on settings if they are using retina, so the whole population won't be affected by the scale.
