### ISSUE TITLE
subtitle quotes translation support

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#1249]
now subtitle supports have been pushed to master branch, lots of translations are needed.
here are some ideas about adding better support for translators:

- use descriptions as line keys rather than using the number

current keys are numbers
```javascript
...
   "80": {
        "1": "I am Battleship Nagato, pleased to meet you. Leave the enemy battleships to me.",
        "25": "Born as the first battleship of the 8-8 fleet programme, the nameship of the Nagato-class battleships, Nagato. Until Yamato was commissioned, I served as the flagship of the Combined Fleet. I was called one of the 'Big 7'.",
        "2": "What is it?",
...
```

it could be easier for translators if the keys are more descriptive:
```javascript
...
   "80": {
        "Intro": "I am Battleship Nagato, pleased to meet you. Leave the enemy battleships to me.",
        "Library": "Born as the first battleship of the 8-8 fleet programme, the nameship of the Nagato-class battleships, Nagato. Until Yamato was commissioned, I served as the flagship of the Combined Fleet. I was called one of the 'Big 7'.",
        "Poke(1)": "What is it?",
...
```

the mapping between numbers and descriptions has been established in:
https://github.com/KC3Kai/KC3Kai/blob/master/src/pages/strategy/tabs/mstship/mstship.js#L12-L66

so we can either change numbers to descriptions or having some helper program to allow translators to write out "descriptive-key" version and convert to the current one.

- reuse pre-remodel ship quotes

as many ships are just reusing quotes of their pre-remodel version, in `quotes.json` we can just add quotes that are different or missing from their pre-remodel version. and we can use https://github.com/KC3Kai/KC3Kai/blob/master/src/library/modules/RemodelDb.js to figure out ship id before remodeling, so there is no need to put pre-remodel relation into quotes.json

**Comment by LostLogia4** [comment]
That's a great idea, oh, but what about different languages?

**Comment by LostLogia4** [comment]
@sinsinpub language for intro and stuff in JSON file.

**Comment by dragonjet** [comment]
agreed on all this :+1: 
we might even need to move the "descriptive-key" into `Meta.js` for global use

I have one suggestion for subtitle translators though: since I have setup our mini-server at 54.238.219.109 we can try use @bamboo3250's script for filling quotes. this would be used when we're gonna fix all the mix-ups, etc. but especially helpful for translator of other languages, which they can input quotes in textboxes even without knowing JSON, and having a UI on which line it is.

**Comment by Javran** [comment]
I'm trying to get premodel quote  re-using work, and it turns out the problem is more complicated than I thought, because KC3Translation.getJSON extends missing quotes by using eng version, so quote's table-lookup will always succeed as long as the eng version exists.

might need to do some preprocessing on quotes.json:
- first extend language specific quotes.json first, by using previous-remodel relation
- then extend any missing parts using eng version

will be working on this tomorrow.

**Comment by Javran** [comment]
All done:

- no special handling on English version, as it'll be used as the last resort if anything is missing.
- #1264 implements both features as described in OP
- a tool for converting to use descriptive key: KC3Kai/kc3-translations/pull/98
    - note that if both numeric key and descriptive key are used, the latter will be used, so I'd suggest converting all `quotes.json` (except for English version) using this tool after PRs being merged.
