### ISSUE TITLE
1-6 boss gauge gets one off

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#1251]
on node B, the gauge looks like (3/7):

![2016-03-31_204259_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/14194942/c1145826-f781-11e5-890e-7a6e04282641.jpg)

but after proceeding from node B's battle result screen, it goes immediately to (2/7), with last one turning red:
![2016-03-31_204430_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/14194968/05344a5c-f782-11e5-91b9-6c815997b030.jpg)

**Comment by LostLogia4** [comment]
So basically the number is correct but the gauge is off?

**Comment by Javran** [comment]
@LostLogia4 both number and gauge are off. the final node of 1-6 is supposed to be N,
but both the number and gauge decreases just after proceeding from B, not yet reaching N.

**Comment by sinsinpub** [comment]
but ur node list has shown N... is that a special case for 1-6 only the node before N can receive the api result?

**Comment by Javran** [comment]
@sinsinpub I think so, at least for now, 1-6 is the only regular map that has no battle on final node.

**Comment by LostLogia4** [comment]
@Javran FYI the clear flag is included in api_next. The game doesn't have a dedicated API for resource nodes, including 1-6N node.

**Comment by dragonjet** [comment]
i think node B is being detected as isBoss = true

**Comment by Javran** [comment]
seems to have been fixed. closing.
