### ISSUE TITLE
[Bug Report] Combined fleet escort history not cleared

### ISSUE THREAD

**Issue by OTLFrostA** [KC3Kai/KC3Kai#1261]
I think a screen shot could explain everything.

![image](https://cloud.githubusercontent.com/assets/5652631/14228743/abbaacb6-f8d3-11e5-9cc8-e2f2aeae77e5.png)
Note Yuudachi

And I doubt if there is any way to trigger this bug now, since combined fleet is time-limit option. What I wanna ask is how to clear this manually (not entire data, just this "escort status“)? It's annoying, and keep telling me not fully supplied, probably because escort ship counted as 0-supply.

**Comment by LostLogia4** [comment]
Close the game and Admiral Panel, go to Strategy Room and press "Clear FCF Infections"
