### ISSUE TITLE
[Bug report] Issues typing in frame

### ISSUE THREAD

**Issue by dsota** [KC3Kai/KC3Kai#1262]
I've been having issues being able to enter my username and password at the login screen while on the frame. The cursor only remains active for a very short amount of time and your only able to enter about one character before you have to click on the box to activateit again. A friend of mine has also been experiencing the same issues .

**Comment by sinsinpub** [comment]
Typing via API game also has problem: Input box has no focus, IME never activated and non-char keys such as <kbd>BackSpace</kbd>, <kbd>Delete</kbd>, <kbd>Space</kbd>... do not responded at all.
But copy and paste works and there is so little place needs to use keyboard for this game... :sweat_smile:

**Comment by LostLogia4** [comment]
Press <kbd>F7</kbd>. Already resolved in #942.
