### ISSUE TITLE
Kongou and hatsuzuki subs problem

### ISSUE THREAD

**Issue by rayo329** [KC3Kai/KC3Kai#1266]
Kongou has a problem with the subs. The secretary lines are mixed and the translation that is showed is from a different line that is not being said at the moment.
Also, hatsuzuki moderate damage line is subbed twice.

**Comment by LostLogia4** [comment]
Currently tracked [here](https://docs.google.com/spreadsheets/d/1wg7pCv3l6g8BfOye3-DbrCuYDhTvSX4h1UuiRCp0_K8/edit)

**Comment by dragonjet** [comment]
For subtitle lines mixed, swapped, wrong, has grammar issues or anything about the text being the correct corresponding line for the voice spoken: https://github.com/KC3Kai/KC3Kai/issues/751#issuecomment-202033407
