### ISSUE TITLE
201 Auto-detector

### ISSUE THREAD

**Issue by dragonjet** [KC3Kai/KC3Kai#1267]
http://himeuta.org/showthread.php?7333-Bot-detection-cat-errors-201-cat&p=960701

**Comment by LostLogia4** [comment]
How are we supposed to detect that?

**Comment by dragonjet** [comment]
there's a something on `Request.js` that will let us know the http status code
https://github.com/KC3Kai/KC3Kai/blob/master/src/library/objects/Request.js#L28

**Comment by dragonjet** [comment]
reference
```
svdata={"api_result":201,"api_result_msg":"xxxx"}
```
