### ISSUE TITLE
dev-only strategy room pages

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#1270]
I'm thinking about having some dev-only strategy rooms (can be toggled in settings, with "here be dragons" to frighten normal users XD)

this might be useful for:
- playground: since strategy room has access to all KC3 functions, it'll be convenient for developing things interactively, we can leave a blank page, and `.gitignore` all changes to this specific page
- translations: some lines might be missing and default to English version, we can have a big table to help translators to see what's been default to English
- voices: same as "translations" but we might need a dedicated page for ships' voice lines, after #1249 is done, we'll need to distinct:
  - lines that have been translated 
  - lines that comes from pre-remodels.
  - lines defaulted from English version

**Comment by LostLogia4** [comment]
Can we have [this](https://github.com/KC3Kai/KC3Kai/issues/1168) one as well?

**Comment by Javran** [comment]
@LostLogia4 sure, I'm just purposing having some pages only visible to developers, so it'll be easier to test or visualize some internal stuff.

**Comment by ethrundr** [comment]
this actually a great idea 😆

**Comment by LostLogia4** [comment]
need some input from actual testers tho. anyone knows who I should contact for their testing procedure?

**Comment by Javran** [comment]
I think this can be closed now. dev-only pages have been implemented and discussion about gunfit testing can be continued on #1168
