### ISSUE TITLE
[Bug] Empty KC3

### ISSUE THREAD

**Issue by Agc0de6** [KC3Kai/KC3Kai#1271]
Where I turned wrong?
![2016-04-04](https://cloud.githubusercontent.com/assets/14156630/14234912/68f4e352-fa08-11e5-98e4-296ec3af56aa.png)

**Comment by samato120** [comment]
![image](https://cloud.githubusercontent.com/assets/18267798/14255831/449cd2d6-fac0-11e5-8eb0-a1bcda928b91.png)
ลบลงไหม่ก็ยังเป็นหมือนเดิม
