### ISSUE TITLE
[Bug report] Game freezing on right click in frame

### ISSUE THREAD

**Issue by dsota** [KC3Kai/KC3Kai#1274]
I've run across this issue a couple of times today when the game will freeze on the last screen you were on when I accidentally right-clicked on the game in the frame. This issue doesn't clear and I had to refresh the game to get to work again. This same issue also causes the Strategy Room to be inaccessible as a result.

**Comment by dragonjet** [comment]
check if you are using the latest flash player with PPAPI,
and using google chrome latest stable version

**Comment by dsota** [comment]
This issue only occurred when I was playing on the frame. Playing on the website was fine. 

I will say at the moment I'm not experiencing the same issues when right clicking on the frame right. What I've noticed is that nothing pops up when you right click on the frame, but when I was having this issue, the right click menu for flash did pop up.

**Comment by Yukinyaa** [comment]
@dsota 
I was couldn't reproduce the situation. can you be more specific?
To start, how the game "freeze"?
did whole plugin crash?```can check by opening strategy room tab, if not working, yes```
or something else happen?
What chrome version/OS are you using?
>version check by going to chrome://help/ (or settings>about on the left bar)
fyi, For OS I am using windows 10, and Chrome ver is ```Version 49.0.2623.112 m
```
