### ISSUE TITLE
[Suggestion] make subtitle transparent when mouse hovers over it

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#1280]
just as title says, sometimes subtitles will be rendered on top of what we really want to see.

**Comment by dragonjet** [comment]
just to add notes, the current problem is that subtitles are set to `pointer-events: none` to make it non-responsive to clicks and it will click the game instead of the overlay. The downside is that it also won't respond to hovers XD

**Comment by sinsinpub** [comment]
that's why I said display subtitles on devtools panel (as subtitles position option). is it reasonable? :joy:

**Comment by nonsensed** [comment]
What if you change the position of the subtitles depending on the screen?

For example

After battle XP screen: align to top (when aligned to bottom, it covers the lower 2 ships, can't see experience gain)

ship encyclopedia: top left?

Quest window: actually... not sure... but on the bottom it covers the page buttons. Maybe only slightly up, enough to not cover the numbers.
