### ISSUE TITLE
dev build doesn't load

### ISSUE THREAD

**Issue by Reddo-KanColle** [KC3Kai/KC3Kai#1281]
My dev build doesn't load. I'm stuck with a background of a naval dock.

**Comment by dragonjet** [comment]
pull again, you might have the older subversions of 28.x

**Comment by Reddo-KanColle** [comment]
I did, 3x already. And yes, I keep getting the 28.5 version. I'm using Tortoise btw.

**Comment by Reddo-KanColle** [comment]
Update: I reinstalled the whole thing. It's fixed now.
