### ISSUE TITLE
[Sugesstion]Reset Ongoing Quest list on panel load

### ISSUE THREAD

**Issue by Yukinyaa** [KC3Kai/KC3Kai#1283]
>(Anon(ㅈㄱ)39.7)
>그리고 제독업무처럼 kc3 접속하면 퀘스트 지워지는거 필요하다고 생각한다. 밖에서 폰코레하다가 집에와서 kc3틀면 전략실 매번 들어가서 퀘스트 지우는거 번거로움

Translation)
>When I run kc3, quest should be deleted like ttk viewer. When I play kkl out of the house with a smartphone, I have go clear quest from strategy room every time and it is hassling.

Reseting quest manually could be hassle. Should implement this like this guy suggests :/

**Comment by dragonjet** [comment]
hm well it is possible but difficult. if the quest is not in the list anymore we can remove it. but he has to visit all pages for it to work. not in priority though, unless a dev wanna tackle this

**Comment by sinsinpub** [comment]
u mean add a button on panel for each quest to tell KC3: "this quest I have completed at other place (computer/device), mark its tracking status as completed (and removed from panel)"?

**Comment by Yukinyaa** [comment]
@sinsinpub yeah #1285 should work better
