### ISSUE TITLE
Battle Prediction with DameCon

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#1284]
I just updated https://github.com/Javran/purescript-kancolle-helpers to support battle prediction with damecon.
I've tested it on 32k sortie data of myself and it works as good as the old one.

But so far I haven't used any repair team or repair goddess. @KC3Kai/testers @KC3Kai/developers if any of you has battle that consumed either repair team or repair goddess, would you like to share that for testing? Simply sharing your replay will do and I'll include that in my test suite for further development.

keeping a TODO list for myself
- [x] test on battle data that consumed damecon
    - [x] Repair Team
    - [x] Repair Goddess
- [x] KanColleHelpers cleanup
    - [x] remove deprecated interfaces
    - [x] update docs
- [x] adapt KC3 to use new interface
- [x] verify changes
    - [x] battle prediction
    - [x] expedition condition
    - [x] expedition calculator
    - [x] way to test combined fleets?
- [x] assume no damecon when practicing
- [ ] ~~update UI when damecon is consumed?~~

**Comment by Javran** [comment]
I have pretty much adapted to use the new interface.

now there are 2 things need to be done:

- is it possible to test code on combined fleets? I've adapted that part of code but haven't found ways to get its coverage

- what happens when damecon is consumed? (extra slot become empty? shift slot items when damecon on main slots is consumed?)

@KC3Kai/developers @KC3Kai/testers please let me know if you know any answer to questions above. also the branch is pushed to `dev-battle-prediction` and feel free to test.

**Comment by sinsinpub** [comment]
how about daemon consuming UI on prediction: highlight (red border or somehow) the item slot icon on ship list which is consumed? (next time refreshed, that slot may become empty)

btw, shifting will not happen i think, just empty the consumed slot... although i never used a daemon anyway :joy:

**Comment by Javran** [comment]
I've adapted codes to use new battle prediction module. also added some test cases to ensure it works on combined fleets:

https://github.com/KC3Kai/KC3Kai/blob/dev-battle-prediction/tests/library/modules/BattlePrediction.js

I'll open a PR for this. and let's open a new issue dedicated to damecon problems.

also thank @sinsinpub for the info.
