### ISSUE TITLE
hp left to taiha(大破) (on panel)

### ISSUE THREAD

**Issue by Yukinyaa** [KC3Kai/KC3Kai#1289]
suggested from DCinside by anon

**Comment by dragonjet** [comment]
not where it would be ultimately useful though XD

regardless if you know the HP left, you don't have control how much damage she takes, and the fact remains that you can continue as long as it's more than or orange HP

**Comment by Yukinyaa** [comment]
yes, but we can estimate if it will survive next battle node like 
1 hp left = nope friend one hit and you're gone
3 hp left = maybe one or two hit by dd is fine
but nvm, just suggestion it will fill up debug panel

**Comment by sinsinpub** [comment]
haha I made the similar one to current hp tooltip of panel :joy: 
left me send a PR
