### ISSUE TITLE
Update damecon properly on UI

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#1292]
Now that battle prediction also predicts damecon usage. I think we can start to think about updating equipment info for damecon properly on UI:

* on battle result screen, if damecon is consumed, remove that from UI (I'm not sure whether this part has been implemented)
* as @sinsinpub has suggested in https://github.com/KC3Kai/KC3Kai/issues/1284#issuecomment-210549076 if battle prediction says a damecon will be consumed, we can make some special indicator on top of it.

I'm not familar with UI code, so I'll just give what I know and hope someone can take care of it:

* `KC3Ship.prototype.findDameCon` finds the first damecon of a ship.

```javascript
	   /* FIND DAMECON
	   Find first available damecon.
	   search order: extra slot -> 1st slot -> 2ns slot -> 3rd slot -> 4th slot
	   return: {pos: <pos>, code: <code>}
	   pos: 0-3 for normal slots, 4 for extra slot, -1 if not found.
	   code: 0 if not found, 1 for repair team, 2 for goddess
	   ----------------------------------------- */
````

* `KC3Fleet.prototype.getDameConCodes` does the same thing for a fleet. but only return an array of code (return array is always of length 6)

    example: `[2,1,1,-1,-1,-1]` means flagship can use a repair goddess when necessary. and 2nd, 3rd ship can use repair teams. last 3 `-1` means either the ship is not equipped with damecon or there is no ship in that place.

* new battle prediction result format:
    I think it's more straight forward to just give examples: https://gist.github.com/Javran/c8e36378e8a70e1959162843847ca865

**Comment by dragonjet** [comment]
ah I'd like to work on this UI

**Comment by dragonjet** [comment]
is there a way to test this without wasting damecon :sweat_smile:

**Comment by dragonjet** [comment]
@Javran, I got a negative hp, sunk true, but dameconconsumed false, using latest pull from `dev-battle-prediction`

![sunk_but_not_consumed](https://cloud.githubusercontent.com/assets/557312/14581187/e2e44c94-0420-11e6-90e2-48e2a60133f1.png)

**Comment by Javran** [comment]
@dragonjet sorry I just woke up, I suspect dameconcode array is not set properly.. can I see the replay (just texts from "Load from text" in the battle replayer will do)

also there is a way to test without damecon, I made a fake environment for testing sorties:

https://github.com/KC3Kai/KC3Kai/blob/master/tests/library/modules/BattlePrediction.js

maybe I should modify that to also test damecon consumption.

**Comment by Javran** [comment]
Fixed on: https://github.com/KC3Kai/KC3Kai/commit/ba721c3e1739fcb1ad421d15774e12d98af3e41f

and fixed another minor bug:
https://github.com/KC3Kai/KC3Kai/commit/ad36f2a2b5d2b80f5d28ab2ccec34a1b3b0ec982

**Comment by dragonjet** [comment]
hmm too bad qunit can't test UI. There's also casperjs for automated UI testing but since we also rely on Chrome.* APIs we can't run through.

I'm thinking of bringing back the first tests, that we click on buttons in the UI while the F12 panel is open and it will AJAX a local file that will look like a kcsapi, and detected as game, but the results are predefined, so we can repeat the tests over and over
