### ISSUE TITLE
Z1 Kai subtitles

### ISSUE THREAD

**Issue by Double13** [KC3Kai/KC3Kai#1303]
The subtitles for Z1 Kai are swapped on the main menu
"Einen schönen Tag." displays in the subtitle the  "Nn, what is it? My boiler needs servicing..."
and the
"ん、何かな？僕はボイラーの整備をしたいんだけど" displays in the subtitle "Have a nice day."

This should be vice versa

**Comment by Agc0de6** [comment]
quote of DJ for [#1233](https://github.com/KC3Kai/KC3Kai/issues/1233) (the same problem here):

> a part of the large subtitle feature, where we're not yet done with verification:
> 
> Verification instructions:
> #1186 (comment)
> 
> Continue Tracking thread:
> #751 (comment)
