### ISSUE TITLE
New quests

### ISSUE THREAD

**Issue by Agc0de6** [KC3Kai/KC3Kai#1306]
Can someone get text of new quests?
I think we should translate them before releasing 29.0. Or not?

●艦隊、三周年！
●「第一航空戦隊」西へ！
●強行高速輸送部隊を編成せよ！
●強行高速輸送部隊、出撃せよ！
●新装備の準備
●上陸部隊演習
●上陸戦用新装備の調達

**Comment by dragonjet** [comment]
yes we should TL them before 29.0, I'm adjusting the release dates, but we don't have IDs as always XD

**Comment by Javran** [comment]
not sure about quest ids, but here are quest texts from kcwikizh:

* 艦隊、三周年！

> 三周年を記念しバシー島及び東部オリョール海に出撃、同海域の敵艦隊を撃滅せよ！

* 「第一航空戦隊」西へ！

> 旗艦「赤城」同僚艦「加賀」を中核とする艦隊で、深海東洋艦隊漸減作戦を貫徹せよ！

* 強行高速輸送部隊を編成せよ！

>「川内改二」旗艦、「江風改二」「時雨改二」他駆逐2隻による水雷戦隊を編成せよ！

* 強行高速輸送部隊、出撃せよ！

>「江風改二」「時雨改二」「川内改二」他駆逐2隻を含む艦隊で、ジャム島攻略作戦を実施せよ！

* 新装備の準備

>「工廠」で装備を5つ「廃棄」して、新装備配備の準備をします。

* 上陸部隊演習

> 島嶼攻略部隊の練度向上のため、本日中に演習で4回以上「勝利」せよ！

* 上陸戦用新装備の調達

> 「工廠」で「7.7mm機銃」及び「12.7mm単装機銃」を二つずつ廃棄！

**Comment by Agc0de6** [comment]
maybe we should postpone release for a couple of hours to find these ids?

**Comment by Javran** [comment]
update: added quest id.

**Comment by dragonjet** [comment]
Updated English on https://github.com/KC3Kai/kc3-translations/commit/9b3a9cd8216ee37d7ea8df6765be661f4afe2ce2
```
"173":{
	"code": "A68",
	"name": "Organise a Forced High-speed Transport Fleet!",
	"desc": "Have Sendai Kai Ni as flagship, Kawakaze Kai Ni, Shigure Kai Ni and two other destroyers in your fleet.",
	"unlock": []
},
"814": {
	"code": "B68",
	"name": "Forced High-speed Transport Fleet, sortie!",
	"desc": "Sortie a fleet with Sendai K2 as flagship, Kawakaze K2, Shigure K2 +2DD and up to one wildcard to W4-1 and obtain at least an A-Rank at the boss."
},
"815": {
	"code": "B69",
	"name": "\"1st Carrier Division\", into the West!",
	"desc": "Sortie a fleet with Akagi Kai as flagship, Kaga Kai and up to four wildcards to World 4-5 and obtain an S-Rank at the boss."
},
"816": {
	"code": "B67",
	"name": "Fleet, Third Anniversary!",
	"desc": "Sortie a fleet to World 2-2 and World 2-2 and obtain an S-Rank at both bosses."
},
"312": {
	"code": "C9",
	"name": "Landing Force Practice",
	"desc": "Get 4 victories in Exercises within the same day",
	"tracking": [ [0,4] ]
},
"635": {
	"code": "F32",
	"name": "Preparations for New Equipment",
	"desc": "Scrap 5 pieces of equipment",
	"tracking": [ [0,5] ]
},
"636": {
	"code": "F33",
	"name": "Supply of New Landing Force Equipment",
	"desc": "Scrap two 7.7mm Machine Guns and two 12.7mm Machine Guns"
},
```

**Comment by Agc0de6** [comment]
@dragonjet, Verniy says: Спасибо большое!

**Comment by nonsensed** [comment]
Small typo in [EN] 816:
Sortie a fleet to World 2-2 and World 2-**2** and obtain
The second one was 2-3 I believe

**Comment by dragonjet** [comment]
thanks for pointing that out, this was copy-paste from wikia :laughing:

**Comment by dragonjet** [comment]
I know I fixed that 816 in c3bbeece10758e5b5c316b8426cdf295c03ec555. Master is pointing to it (https://github.com/KC3Kai/KC3Kai/tree/master/src/data).. but someone just reported on Facebook:
http://i.imgur.com/Ig4bMUc.png

**Comment by dragonjet** [comment]
are the active @KC3Kai/translators done with their TLs? unless someone says they wants to do follow-up TL in 29.x within tomorrow, @Agc0de6 can close this

**Comment by Agc0de6** [comment]
closing this
