### ISSUE TITLE
Russian subtitles

### ISSUE THREAD

**Issue by Darkzarich** [KC3Kai/KC3Kai#1309]
Hello. I have one question:
When russian subtitles?
Thank's

**Comment by dragonjet** [comment]
tagging translators @Agc0de6 @Kvazikvark

**Comment by Agc0de6** [comment]
@Darkzarich Слишком много текста, не успеваем оформлять. Также ещё есть неполадки в английских субтитрах, Если хотите, буду рад вашей помощи.

**Comment by Darkzarich** [comment]
@Agc0de6 А в каком состоянии находится в данный момент то, что готово? Сколько всего насчитано фраз и сколько готово? Я прикинул, выходит ~ 5300 фраз.

**Comment by Agc0de6** [comment]
@Darkzarich на данный момент файл с субтитрами имеет 17464 строки. Знаю точно, переведена Нагато. Сейчас все силы брошены на проверку английских субтитров, так что пока переводом не занимались больно.

**Comment by IAmVisco** [comment]
@Agc0de6 вам лишний помощник не нужен?

**Comment by Agc0de6** [comment]
@IAmVisco буду только рад!

**Comment by IAmVisco** [comment]
@Agc0de6 тогда какой фронт работ? все выходные буду тута

**Comment by Agc0de6** [comment]
@IAmVisco свяжитесь со мной в ВК (vk.com/c0de_6)

**Comment by dragonjet** [comment]
russian subtitles currently implemented. if there's any other case, you may re-open or create a new thread.
