### ISSUE TITLE
Completed quests do not go away

### ISSUE THREAD

**Issue by pet3rpan** [KC3Kai/KC3Kai#1310]
![image](https://cloud.githubusercontent.com/assets/16596674/14754708/0f4c1806-0918-11e6-8f1a-08c7f4af3375.png)

The completed quests do not disappear and the newer quests lines up off the screen.    
Using the latest version on chrome Version 49.0.2623.112 m, running on windows 10. 
Not sure if anyone else has this issue. Refreshing the page did not fix this.

**Comment by dragonjet** [comment]
just to make sure, these quests are completed in the same gameplay session while the F12 panel is open?

**Comment by pet3rpan** [comment]
I do believe so, although I refreshed the page with the KC3 kai open. Some quests have cleared themselves but I still have a few that remains on the list and the list still goes off the viewer.

**Comment by dragonjet** [comment]
you might want to manually remove them by going to Strategy Room > Flowchart, until a fix is done on #933
