### ISSUE TITLE
[EN] Remaining subtitle corrections

### ISSUE THREAD

**Issue by dragonjet** [KC3Kai/KC3Kai#1311]
This will be updated when we get new reports of wrong lines
- Arashi (Non-kai)
  - Join Fleet (includes both non-kai and kai lines)

**Comment by nonsensed** [comment]
What I have logged:

Graf Zeppelin #1290 

Blank/nothing there:
- 103/105/107 Chiyoda AV  (Attack)
- 24/57 Ooi (Poke 2)
- 137/305 Agano (Yasen 2)
- 283 Hiyou Kai (Poke 3)
- 186/322 Tokitsukaze (Sortie)
- 347/443 Libeccio (Yasen 2)
- 359 Okinami (many hourly lines)
- 404 Unryuu (Equip 2)
- 469 Kawakaze Kai Ni (all)

Has a line, but is wrong:
- 118 Ooi Kai Ni (Poke 2)
- 55/159/223 Jintsuu (Sortie)
- 108/291/296 Chitose CVL (Attack)

**Comment by sinsinpub** [comment]
Dev-Only Quotes page has updated to fit for EN quotes too. See branch `dev-sroom-helps`
And if the blank line (eg: `"Poke(2)": "",`) had been removed, it would detect and show which ship has missing quote.

**Comment by nonsensed** [comment]
I had left them that way specifically because it made it easy for me to detect, as I don't use that page.

The problem with those missing quotes isn't detection, but a lack of translations available, else they would have been filled in already.

**Comment by sinsinpub** [comment]
@nonsensed  before that update, not "u don't", is "u can't". It was not working for EN :joy: 
Recommend using it if u r able to checkout dev branch.
With its help, u can benefit from:
 * Missing line detection and direct viewing list
 * Remove duplicated lines from modeled ships, use "descriptive-key" instead of "voice number" (feature at #1249)
 * Compare with JP lines and check via playing the real voice, compare with seasonal Pokes

**Comment by nonsensed** [comment]
Hey, nice. Sounds good. The first time I looked at it, I saw no romanized ship names and simply ran away.

So it can't detect empty quotes as false like the library and treat this as a missing line? Well, it's easy to remove the : "" lines I currently use if I begin to use that page. And go ahead if anyone else wants to.

I promise I only added some of those : "" lines... others were already there (such as Okinami).

**Comment by sinsinpub** [comment]
Memos of found en quotes issues when verify jp quotes:
 * unescaped characters (fixed)
 * 135 Naganami: swap Poke1, Poke2

**Comment by nonsensed** [comment]
Sorry about the unescaped characters. I have a method to avoid those in the future.

**Comment by nonsensed** [comment]
The Naganami and Arashi issues should now be fixed.

**Comment by nonsensed** [comment]
I've at least addressed all of the missing lines I had listed and a few others in recent commits. It's a virtual guarantee that there are more broken or misplaced lines out there, but I'm not aware of any of them as of this writing. (not including awkward translations)

**Comment by dragonjet** [comment]
thanks @nonsensed :+1: 

btw are there are TLs that are pending for release? we can release this weekend if any. sorry haven't checked TL repo yet

**Comment by nonsensed** [comment]
@dragonjet 2 new quest TLs and 13 seasonal lines. I can't speak for everyone but I don't consider it very important considering the situation with chrome screwing up the window close warning.
