### ISSUE TITLE
strategy room encounter tab: duplicated nodes

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#1314]
many nodes appear more than once in this tab:

![2016-04-22_223327_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/14758836/6bc01986-08da-11e6-9d88-9ce7eddfa32f.jpg)

I guess this might result from the fact that different edges leads to the same node. - we need to merge same nodes.

**Comment by sinsinpub** [comment]
why not statistics how many times encountered for each assemble :joy: 
percentage of encounter for specified assemble (related to map left HP) is useful :trollface:

**Comment by dragonjet** [comment]
@Javran ah that might be true, will need to combine by node letters.

@sinsinpub this was only for people to report encounters in wikis/communities, but since it's only one person, making statistics won't help much :v
