### ISSUE TITLE
Akashi Timer not working properly

### ISSUE THREAD

**Issue by rephira** [KC3Kai/KC3Kai#1317]
http://prntscr.com/avvi45

Seems like as soon as Akashi timer goes past 20 minutes, it is set to be equivalent to the docking timer. Think the Docking tab might be bugging out @Javran @dragonjet

**Comment by Javran** [comment]
@rephira If you have ships that takes more than 20 mins to recover HP, her akashi repair time will differ from the docking one.

I'm not sure if the time calculation is correct, but my lib is no longer in charge of this:

https://github.com/KC3Kai/KC3Kai/blob/master/src/library/objects/Ship.js#L240-L263

**Comment by dragonjet** [comment]
we will need to revert it into @Javran's lib

**Comment by Javran** [comment]
@dragonjet hm, I meant if the calculation is correct then we can keep it as-is. basically what my lib does is to calculate and compare between: (1) recovering 1HP per 20 min (2) using docking time rounded by 20 min and take the shortest one. I learned that from wikia, but not sure if this matches the latest theory.  @ReiFan49 might have some idea on this.

**Comment by ReiFan49** [comment]
ah it's not a bug.
Akashi requires first 20 minutes to prepare a repairing mode for any ship included within her range, and then for any ships that have docking time less than 20 minutes per HP, will treated normally like docking time unless it's 20 minutes+ per HP.

**Comment by rephira** [comment]
Yes this was a mistake on my end. Closing it
