### ISSUE TITLE
Pre-Event: Spring 2016 Goals

### ISSUE THREAD

**Issue by dragonjet** [KC3Kai/KC3Kai#1319]
This post will be updated if we have urgent things needed BEFORE the even, or anyone has a special request on what they want to see.

* #1062 Save fleet composition
* #1137 Heartlock reminder
* #1324 TP Calculation

**Comment by LostLogia4** [comment]
There's the #1137 Heartlock reminder, ofc.

**Comment by Javran** [comment]
could include #1324 if someone is interested in it.

**Comment by dragonjet** [comment]
Moved list to https://github.com/KC3Kai/KC3Kai/pull/1332
