### ISSUE TITLE
TP calculation

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#1324]
we can do TP calculation when using transport escort combined fleet this might be useful for the coming event.

related documents:

- [Wikia: Events](http://kancolle.wikia.com/wiki/Events)
- [WhoCallsTheFleet TP calculator](http://fleet.diablohu.com/calctp/)

I don't have much time working on this before the event, so feel free to take over if you are interested.

**Comment by ReiFan49** [comment]
how about wikiwiki one ?
