### ISSUE TITLE
Disable prediction for land-based air battle nodes

### ISSUE THREAD

**Issue by dragonjet** [KC3Kai/KC3Kai#1333]
As reported on Facebook, prediction was D, battle result becomes A or S

here's a replay file from his 6-4:

http://i.imgur.com/VhHUrTF.png

**Comment by Javran** [comment]
rank prediction could be wrong on air raid battles. since there's no way to attack the enemy, the ranking rules are different:

http://kancolle.wikia.com/wiki/Events/Mechanics

**Comment by Javran** [comment]
for a quick fix, I'd suggest disabling the prediction on air raid battle nodes. as there is no yasen involved in these battles, rank prediction won't be helpful in decision making.

**Comment by dragonjet** [comment]
ohh I see, thanks for the info. I'll update this ticket to be a "disable prediction for air battle nodes"

**Comment by sinsinpub** [comment]
there's no direct flag in api data indicating `airbattle` and `ld_airbattle`, required to add a flag via `Kcsapi.js`?

**Comment by dragonjet** [comment]
im guessing node types in SortieManager like `api_event_type` or something like that

**Comment by sinsinpub** [comment]
@dragonjet  `api_event_kind` is in `api_req_map/next`...indicator flag must be set before entering node?

**Comment by dragonjet** [comment]
Merged #1335
