### ISSUE TITLE
Node prediction analysis using incorrect fleet data for sortielogs

### ISSUE THREAD

**Issue by sinsinpub** [KC3Kai/KC3Kai#1342]
After reading codes, directly says it's a design miss.

sortielogs (Map/Event history) rebuilding battle `KC3Node` instances in loop at [sortielogs.js#L471](https://github.com/KC3Kai/KC3Kai/blob/master/src/pages/strategy/sortielogs.js#L471), it send the fleetId to `Node.js`
and `Node.js` builds battle prediction data by retrieving ship's data from player fleets via `PlayerManager.fleets[fleetId-1]` following lines of [Node.js#L353](https://github.com/KC3Kai/KC3Kai/blob/master/src/library/objects/Node.js#L353).
this only works if and only if the current fleets of player is completely the same with the fleets in sortie record.
for example, if my first fleet now only left one ship there, nearly all sortielogs will throw an exception: `TypeError: Cannot read property 'hp' of null`, coz there is no 2nd and more ships for my first fleet at all, this line will failed on `i>0`: `ship.afterHp[0] = result.main[i].hp`.

we properly need to rebuild the whole fleets instances from sortie history records and pass them to the `Node`, or disable the prediction analysis?

**Comment by Javran** [comment]
not sure why I'm assigned to this, but I've never touched that part of the code.

**Comment by sinsinpub** [comment]
:open_mouth: ofc it's you maintain the codes of battle prediction, right?

**Comment by sinsinpub** [comment]
there is other risk using global property of `PlayerManager` to show sortie history, like this line:
```
	PlayerManager.combinedFleet = sortie.combined;
```
if the player is on another sortie with normal fleet, but during that, he switches to Strategy Room tab let a combined fleet shown at last. The current sortie fleet type will be affected accidentally... :sweat:

**Comment by Javran** [comment]
whoever has passed the wrong fleet to my lib should be responsible. the battle prediction itself is only responsible when the result is wrong AND the input data passed is correctly.

**Comment by sinsinpub** [comment]
@Javran it's not about the lib, it's the `Node.js` who using wrong data...(ofc that part is yours)
read my description again :sweat:

**Comment by Javran** [comment]
it was PR https://github.com/KC3Kai/KC3Kai/pull/380 that introduced battle prediction, the only thing I do was putting that lib into KC3Kai and giving some usage about how to use it. I can't imagine what in a world could have made you think this is something "ofc"?

nonetheless I admit this is a design flaw: `Node` should be independent of `PlayerManager`. a possible fix could be to leave `PlayerManager.whatever` as an argument instead of asking `PlayerManager` to provide it - just providing a suggestion, I don't have time working on this.

**Comment by dragonjet** [comment]
I made the first Map history and Event history pages, but was then moved into a common sortielogs.js, iirc by @ReiFan49. Never touched it since iinm.

**Comment by sinsinpub** [comment]
what u guys are misunderstanding for? :joy: 
I'm NOT looking into 'who did it?' or 'who have to handle it'. it's just a 'bug report'.
Different from normal user, I describe my analysis from a developer view instead of phenomenon.
and looking for some suggestions from the recent modifier of codes who directly causing the exception. it's the 'ofc'. :trollface:

**Comment by Javran** [comment]
first, stop using these emoji, it doesn't make you look smarter and I can hardly feel what's the fun in this.

second, you said you are not looking for 'who have to handle it'? then please enlighten me why assigning me on this issue and keep saying "ofc" I'm the maintainer.

if you are looking for suggestions I've gave mine. also I'm tired of talking about these nonsense. from now on I'm out of this thread.
