### ISSUE TITLE
land-based airstrike support

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#1344]
I just got some sample data, will be working on a support.

**Comment by Javran** [comment]
@KC3Kai/testers I just implemented support for land-based airstrike, if any of you have made it to E4 or E5, please keep an eye to see if the battle prediction result is correct.

**Comment by dragonjet** [comment]
someone reported that still thinks enemy is alive when it was actually sunk. thus we should release this even without confirmation from testers - there's a problem as it is so this fix should get out to public

thanks :+1:
