### ISSUE TITLE
Some info in the panel getting stuck

### ISSUE THREAD

**Issue by AlanSchaeffer** [KC3Kai/KC3Kai#1348]
It has been happening occasionally lately, that some of the info will get stuck in the panel. I'm not sure how to reproduce this bug. Might, or might not have anything to do with sortieing in combined fleets, but I think it's happened before the start of the event too.
Some random infos in the panel will freeze up on their old state. In the case of this screenshot, 
![sem titulo](https://cloud.githubusercontent.com/assets/11778507/15059193/3e60a934-12f7-11e6-9986-1f9dae7cc8d1.png)

Daily sortie 1 was stuck as completed after I collected it, which I just used the manual removal to get it out by clicking on the green block and going back to the HQ home. The fleet states also got stuck, it shows that fleets 1 and 2 require resupply while fleet 2 has damaged ships, but as can be seen in the screenshot, they have been replenished already

**Comment by rephira** [comment]
This sometimes happens when KC3Kai is updated in the background... there are a lot of small updates happening to accommodate for nodes and stuff so I suspect that might be the issue. Does it work properly again after you take measures like restarting everything?

**Comment by AlanSchaeffer** [comment]
You might be right. It did work properly on my next game session. I did not notice whether it had an update or not at the time

**Comment by dragonjet** [comment]
will close for now until encountered again :+1:
