### ISSUE TITLE
localStorage limit exceeded

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#1356]
I think this is critical problem that has to be addressed quickly:

![2016-05-09_034802_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/15106695/16d9d8b4-1599-11e6-91be-82ead9de9cee.jpg)

somethng has occupied all space of localStorage, making KC3 itself unusable (devtools cannot be initialized properly because of this)

the sources of this might be:
* `localStorage.raw`: by removing `localStorage.raw` I managed to enter the game with devtools initialized properly, but the error message will appear whenever entering main screen or do something related to ship list.
* `localStorage.ships`: might not be a big issue for now, but I feel something is wrong with it:
![2016-05-09_035721_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/15106894/45a2a080-159a-11e6-8c08-961024db8049.jpg)

not sure what `lastSortie` is used for, but it's definitely taking many spaces. and the variable name `lastSortie` suggests this array might be intended to keep only few of last sorties instead of accumulating them all...

**Comment by ReiFan49** [comment]
`lastSortie` should only retain it's latest sortie and sortie0 as placeholder, maybe there's some design flaw (i should recheck this),
also `chrome.storage.local` is the other solution for non string based item store (but it means migrating and yeah, whole change on the way storage system works)

**Comment by Javran** [comment]
update: might not be that urgent after all, I have `localStorage.master`, where some parts of `api_start2` is stored in the past. clearing localStorage works for me.

but I think this problem still need to be solved, as chrome has hard-coded localStorage size quota to 5MB, and we have at least used half of it:

![2016-05-09_050808_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/15108464/11b11900-15a4-11e6-9bae-b04b2801e3a5.jpg)

(see: http://stackoverflow.com/a/17887889/315302 , put code in your strategy room's console to see the actual size.)

here are few things I think we can do:

* move master data to IndexedDb or somewhere else
* remove `localStorage.raw` if detected, it now has no used and user might have the risk of using up localStorage space just as I did)
* `lastSortie` issue, as I'm writing a reply @ReiFan49 is aware of it and hopefully this one can be resolved soon.

**Comment by sinsinpub** [comment]
> remove localStorage.raw if detected,
it's a typo. `.master` is the deprecated one... 

remove unused item is necessary, but there is a final solution for extension: permission of `unlimitedStorage`
https://developer.chrome.com/extensions/declare_permissions

**Comment by Javran** [comment]
ok, it turns out to be a failure on my own side: when I tried to attempt faking `KC3Fleet` and `KC3Ship` from raw data, I stored `GearManager` as a field of `KC3Ship` and `ShipManager` as a field of `KC3Fleet`. when serializing data, `JSON.stringify` is used directly on the object, which means serializing each ship results in storing a complete copy of `KC3GearManager` and likewise for each fleet, a complete copy of `KC3ShipManager` is stored. this will definitely blow up space.

my solution to this is to [remove XXXManager before serializing](https://github.com/KC3Kai/KC3Kai/commit/2348ff6d68d2cb790eea799dcc0c05b5afb6935b). and this turns out working fine.

so my own problem is solved. but I'll leave this issue open since I'm still a bit worried about storing master data on `localStorage`.

**Comment by Javran** [comment]
I just did some investigation on @sinsinpub 's suggestion about using `chrome.storage.local`.

* [pros and cons](http://stackoverflow.com/a/24281357/315302)
* we'll lost the convenience of viewing localStorage under devtools > Resouces > Local Storage, but we can have a dev-only page under strategy room to do something similar.
* we [already have all permissions we need](https://github.com/KC3Kai/KC3Kai/blob/5f3df82fc96b76ae2beb0e0517d3597172a9d16e/src/manifest.json#L19-L20)

for now, there are 3 parts of localStorage that takes up most of the spaces: (1) master data, (2) ship data, (3) equipment data. if `chrome.storage.local` turns out to be a right choice, we can consider storing (1) and optionally (2) & (3) in it.

@ReiFan49 @sinsinpub @dragonjet just asking for your opinions on this.

**Comment by dragonjet** [comment]
i think being a bit more conservative about space, and how we assign data to `KC3Ship` and `KC3Gear` objects, the current localStorage mechanism can still hold up. There will just be a few reminders that I have been doing but not properly communicated before:

* If you need temporary variables attached to a ship object, use a function:
instead of `ThisShip.something = my_value;`, use `ThisShip.something = function(){ return my_value; }`. This will prevent it being included in JSON stringifies that will be saved on localStorage.

* `lastSortie` can be moved to indexedDB instead of localStorage. In conjunction with #840, about the individual ship stats page. lastSortie is a "history property" of a ship, and we might need to even record all sorties, not just the last one.
  * If we can be a bit more complex, we can even run through all sortie records and find the ship instead of recording it.

* I've been looking at `chrome.storage` as early as #17, as the `unlimitedStorage` permission is already in `manifest.json` for a long time even though it doesn't apply yet.
  * I am not against this idea, but just noting that if we're gonna move it, might as well do an "online" version `chrome.storage.sync` instead of local, to carry the data over different computers.

**Comment by ReiFan49** [comment]
`lastSortie` basically only points to a latest sortie **that damaged the respective ship**, `sortie0` means an empty entry, somehow i need to recall how i construct the ledger system along this `lastSortie` thingy,
<hr>
about the storage itself, there will be some huge change if the storage itself is changed, there might be, but it'll slowly, as we try to play with callbacks and such. i'll be ok with this, only if this implemented slowly through the time.

**Comment by dragonjet** [comment]
merged #1358, will close this for now, until encountered again just in case.

for storage changing into chrome API, let's separate it into a different thread if we'll really push it through
