### ISSUE TITLE
Support for land-based airstrikes in air raid nodes.

### ISSUE THREAD

**Issue by LostLogia4** [KC3Kai/KC3Kai#1361]
Battle prediction doesn't work when I send air supports to air raid nodes.
http://pastebin.com/raw/ZAdfkW1e

![nopredict](https://cloud.githubusercontent.com/assets/12930396/15138995/ff935058-16c5-11e6-8a14-818f72a8add5.png)

**Comment by Javran** [comment]
should be fixed now.
