### ISSUE TITLE
Fighter power calculation without airpro?

### ISSUE THREAD

**Issue by c933103** [KC3Kai/KC3Kai#1369]
Because fighter power calculation for aerial support neglect airpro, is it possible to obtain the value from within kc3kai?

**Comment by dragonjet** [comment]
yes, on the devtools panel, you may click on the fighter power icon-value to switch it on different modes:
* native calculation without proficiency
* calculation with proficiency as a whole number (average bonuses)
* calculation with proficiency as a range (with min-max)

**Comment by LostLogia4** [comment]
I'm in latest version and can't seem to toggle it...

**Comment by sinsinpub** [comment]
seems toggle event not added to theme.js, could add it at once.
but fighter power for combined fleets is still the sum of power without proficiency from fleets 1+2... is this still okay?

**Comment by dragonjet** [comment]
i remember it from earlier versions but not sure where it went if it doesnt do it now XD

**Comment by c933103** [comment]
Fighter power of combined fleet fleet #2 should be neglected
2016/05/12 13:31 "dragonjet" <notifications@github.com>:

**Comment by sinsinpub** [comment]
@c933103 yea, fleet 2 should be excluded
from wikiwiki
```
* 航空戦参加部隊は第一艦隊のみ(制空値等も全て)
* 第二艦隊の空母や航巡等の制空値は加算されず、また撃墜もされない。
* 対空カットイン判定は第一第二艦隊共にある。防空も同様。
* ただし第二艦隊も航空戦では攻撃対象になる。
* 同様に彩雲搭載可否によるT時不利軽減判定も第一艦隊のみの模様
```
