### ISSUE TITLE
E6 node L and N mix up

### ISSUE THREAD

**Issue by prokia123** [KC3Kai/KC3Kai#1372]
The line of circles in between the map HP bar and enemy fleet thing that tells you which node you got routed to has L and N switched. It shows N if you got branched to L and vice versa.
![untitled](https://cloud.githubusercontent.com/assets/13274247/15248096/dfe43a92-194a-11e6-8bb8-9ca553937a39.jpg)

**Comment by dragonjet** [comment]
what;s your version, this has been fixed in some 30.x.x version

**Comment by prokia123** [comment]
30.1.1

**Comment by nonsensed** [comment]
I think node N was fixed but node L still displays "N".

**Comment by McDohl** [comment]
@dragonjet i test it myself, its broken. from M to N / L are swapped, will do the fix and seems like theres no image for abyssal hagikaze http://prntscr.com/b3xfwo

**Comment by sinsinpub** [comment]
(a troll) about icon image, these are focus on wrong face :laughing: 
![image](https://cloud.githubusercontent.com/assets/160240/15268810/2c55e76c-1a1e-11e6-8491-239772a30603.png)

**Comment by dragonjet** [comment]
ah sorry about 668-672, I thought that was the enemy already, I have limited vision when I dragging XD

will try to make 676-678, back on the update, there was no swf for those IDs

made #1374 for these
