### ISSUE TITLE
Quest tracking multi-device discussion

### ISSUE THREAD

**Issue by Kirayao** [KC3Kai/KC3Kai#1380]
I got 2 computer switching playing Kancolle. 
If you change the computer to play, the "quest tracing" would hang on the panel.
The one finished on the other computer won't disappear unless that quest is refreshed, 
unless the quest changed state, the number on the panel would also be wrong.
However, the in-game counter is correct. These 2 code snipplets should share the same counter.

**Comment by rephira** [comment]
Sadly, we can't do that because the response will only give out percentage completion at best (at least that is to my knowledge).

I believe the API response never gives an exact number of times something has been completed. We would have to create another method. (like KC3 would need to have a method to store all the user's data on a server which can then be retrieved on another machine when the person switches place)

I play on multiple devices myself. There really isn't a way to fix it without having to start data syncing via server.

**Comment by Kirayao** [comment]
Still some way could be done. 
We know the hierarchy of the quests. So if 50 supply ship quest appears, then no.A quest is done.
At least we could do something to remove the quest that is done.

**Comment by rephira** [comment]
We know the hierarchy of the quest, but how can we tell if the quest is not present on the quest screen because you haven't finished the previous quest or because you have already completed it?

I mean we could just erase the quest off the list if we go through the list and the quest isn't there, but then I dunno if any API response gives the number of pages that are on the quest list. Without that, there would be no way to know if a person has cycled through all of their quest list.

**Comment by LostLogia4** [comment]
@Kirayao There are several ways to solve your problem, assuming that you're signing in from multiple computers into a single account:
* Backup your KC3Kai data via Data Backup in Strategy Room.
* Sign into your account in Google Chrome and perform data sync to synchronize KC3Kai data.
* Play on Google Chrome Portable or Chromium browser. This is what I did, but with GC portable you'll have to _reinstall the extension_ every single time you switch computer, though fortunately the data remained intact.

**Comment by ToadnoChikara** [comment]
@rephira I believe @Kirayao was suggesting something like this:

If a quest exists that requires the completion of another quest to be available, then we can strike the other one off. For example, 3x exped daily leads into 10x exped daily. If you have 10x exped daily available, remove the list/auto-complete the entry for 3exped daily. Similarily, 3x transport is required to be done before 5x world-2 boss, so if 5x world-2 boss is available we can assume 3x transport has been completed. That would solve a significant number of the quests that persist when switching between devices.

**Comment by LostLogia4** [comment]
So we'll basically check and flush for the dependent quests whenever we visit the quest page then.

**Comment by dragonjet** [comment]
yea, probably when we receive the list of active quests from the game, we check backwards based on our quests.json::`unlock` attribute and mark quests as complete if it was a prerequisite of the currently active quest..

however, there is a problem when a daily unlocks a weekly. when the weekly is active, the daily will be marked complete all the time even after reset. unless we make whitelist exceptions, which is not advisable.

i still think the best solution is cross-device sync via `chrome.sync` API

**Comment by Kirayao** [comment]
At least we know that daily/weekly/monthly/once quests are independent of
the reset problem. If we were to avoid sync, this still could be possible
to eliminate some done quests.

dragonjet <notifications@github.com> 於 2016年6月23日 週四 上午9:03 寫道：

**Comment by SirDiazo** [comment]
Was going to open this issue up when search found this, can confirm this is still an outstanding issue.

Reading through the responses, I'm puzzled why a simple check to see if the quest is available won't work.

IE: Is the quest visible in the quest log in-game? If not, remove if from the quest tracker if present.

I don't see how all this talk about pre-req quests and checking for completion come in, if the quest isn't visible in the game's quest list, it can't be active in KC3's quest list either so remove it if it is.

**Comment by dragonjet** [comment]
@SirDiazo we can make a way if we just want to clear the quest state, like you said if user revisits all quest pages (not just one page), and if the quest isn't there, we can remove it from kc3 list.

the discussion about quest hierarchies is just a branch topic, but there are still problems that remain, e.g. should we mark it _not done_, or complete (needed in quest flowchart in strategy room). what about the tracking counts e.g. `3/5`, etc.

this is the thing that comes to our mind immediately when talking about cross-device tracking. sorry if there are easier solutions right in front of us that are doable, but we usually tend to think about it like how everything can be solved in one nice solution.

**Comment by mikenzb** [comment]
Feature has been added in #1959 and #1965, will close PR now.
