### ISSUE TITLE
Having Trouble Playing while KC3 Window is Open

### ISSUE THREAD

**Issue by blizzardofflames** [KC3Kai/KC3Kai#1387]
Recently I've often found that whenever the game enters a loading screen (switching out equips, reorganizing fleets, sorting, etc.), the game will load for a long time and then subsequently crash. 

I've tried multiple different things, such as playing on the DMM site and playing on frame without the KC3 window open and found that I never got this error while the KC3 window was closed.

Is there a way to fix this issue?

EDIT: I've tried reinstalling the app entirely, but the issue still carries over.
EDIT: Running the game with the KC3 window open on other sites (DMM, OOI) does not result in crashes. The issue only seems to persist while the KC3 frame AND the KC3 window are both open.

**Comment by Shakerino** [comment]
Also getting this issue, haven't found a fix yet

**Comment by Kam0laZ** [comment]
Yep, having this issue too. Version 30.2.0. 
Running in DMM Website mode. Cleared browser cache, reinstalled KC3Kai extension, issue still persists.
Playing without the KC3Kai panel, the game runs fine.

**Comment by dragonjet** [comment]
KC3 window means the F12 panel?

I'll try to play the game today to observe this.

**Comment by blizzardofflames** [comment]
I've asked a few acquaintances of mine, and the problem has only been present with some of them. However the problem only occurred for them with the same conditions (both KC3 frame and window opened), so I can only assume that the problem lies there.

**Comment by dragonjet** [comment]
hm I've checked the reddit post you made @blizzardofflames and seems some have been getting this problem too on KCV, but we can't be sure if it's the same condition. I am not getting this in my current session.

**Comment by dragonjet** [comment]
@blizzardofflames can you open your chrome task manager <kbd>Shift</kbd>+<kbd>Esc</kbd> and see the CPU and RAM usage of the extensions and tabs when you get the crash/hang

**Comment by blizzardofflames** [comment]
![stuff](https://cloud.githubusercontent.com/assets/19508001/15451970/39b581c8-1fab-11e6-8b26-4c744611fd63.png)

They looked like this during one simulated crash, but at times the CPU usage of flash would go as high as 5 and the RAM usage would go above 100k

**Comment by Kam0laZ** [comment]
![crashed1](https://cloud.githubusercontent.com/assets/19510561/15453439/cd03c57c-200d-11e6-8430-b36fbd4a670c.jpg)
![crashed2](https://cloud.githubusercontent.com/assets/19510561/15453441/d412a0f4-200d-11e6-82fa-e69a27066ad7.jpg)

Here is a simulated crash. 
Opened the browser (the game tab is pinned, so it goes straight to login screen), opened the F12 panel, logged in to the game, as per usual.
First thing I did was go to the quest board and manage some quests, Then went straight to the equipment change room.
Just tried changing equipments on my ABKM K2.
First change was somewhat smooth, second change lagged a few seconds, third change triggered the issue.
It stayed in loading mode for half a minute ~ one minute, and then catbombed.

**Comment by dragonjet** [comment]
thanks for the screenshots @blizzardofflames @Kam0laZ 

unfortunately though, we don't get this crash problem, so we can't debug easily. you may want to get the dev builds if you want a lower version

**Comment by Kam0laZ** [comment]
What I can find is that the latest release on GitHub (other than the most recent v30.2.0) is v24.2. That's awfully outdated, about 6 months old. Is there any way I can get something like v30.0?

Thanks.

**Comment by dragonjet** [comment]
I will manually build a `30.2.1` taken from an [earlier release: `30.1.2`](https://github.com/KC3Kai/KC3Kai/pull/1375)

try to use then for a couple of days, and see if the problem is really in `30.2.0`

I will post here again when it's available from the webstore

**Comment by dragonjet** [comment]
30.2.1 is now approved on the webstore, try to update your extension and see if the problem persists. recommended to restart your browser after making sure you are updated to 30.2.1

**Comment by Kam0laZ** [comment]
Thank you very much.
I'll give it a try and post how it goes.

**Comment by blizzardofflames** [comment]
![image](https://cloud.githubusercontent.com/assets/19508001/15454331/c4c6eb14-2003-11e6-922e-8cb2c86890a7.png)
After trying out the new build, I found that the bug still persists, so it seems that there might not be something wrong with KC3, but rather something with the computers of all the people affected.
I'm going to try to restore my computer to a previous state (2 days ago when a minor update went into effect) and see if that has any results.

**Comment by dragonjet** [comment]
wait if the problem is catbomb, we can debug it differently, I suggest coming into our [gitter chat](https://gitter.im/KC3Kai/Public) to discuss it

**Comment by blizzardofflames** [comment]
As it seems that the error has been resolved as of today (for unknown reasons), I am closing this thread.
