### ISSUE TITLE
Ships sent by FCF still considered "away"

### ISSUE THREAD

**Issue by StalkerGrike** [KC3Kai/KC3Kai#1389]
![screen shot 2016-05-22 at 8 37 11 pm](https://cloud.githubusercontent.com/assets/19522614/15457743/21f32eca-205d-11e6-810d-a49f4487006b.png)

While clearing a map yesterday, I had four ships sent back home using the Fleet Command Facility. After their sortie, they still seem to be regarded by the viewer as "away," with the white background and the whited-out HP gauge. This also appears to be interfering with the checklist at the bottom, which considers them unsupplied. I've reloaded the game and the viewer several times, sent them on sorties to sparkle, and I think KC3改 even had an update between then and now. None of this has changed their status.

**Comment by dragonjet** [comment]
Strategy Room > Profile > Clear bugged FCF states

**Comment by mikenzb** [comment]
Close KC3/Kancolle and open up the strategy room, in the Profile page there is a "Clear FCF Bugged States" under "Bug fixes".

That should fix your issue.
