### ISSUE TITLE
translator.js console error spam on DMM website

### ISSUE THREAD

**Issue by Kam0laZ** [KC3Kai/KC3Kai#1391]
![clipboard01](https://cloud.githubusercontent.com/assets/19510561/15521104/d3296ef2-2201-11e6-9d09-7127dd47bd49.jpg)

As the picture shows. 
I play in DMM Website mode, and the developer console gets those errors.
The error with most counts happens when a voice line plays, maybe it has something to do with the frame translation scripts thinking that it is Frame mode, while it is not.
Tested it in Frame mode, the subtitles work fine with none of those error spams.

It's not game breaking, I mean, I can just close the console and ignore, it doesn't affect the gameplay.
Not sure if it's some setting that I have activated or something.
Just posted to let the devs know about this.

Also, where is the composition export feature?
Will it get fixed when it comes back (Zuikaku A/ -> Zuikaku/Kai Ni A, Chitose Kou/ -> Chitose/Carrier Kai Ni, just a couple examples).

Oh, and those catbombs from the other day, they stopped.
Game is running fine again.

**Comment by dragonjet** [comment]
hm I don't think we have a `translator.js` file though

can you try opening the F12 panel for DMM website gameplay, but _not clicking on kancolle tab_ so KC3 won't load. see if the errors persist even without our scripts running.

**Comment by Kam0laZ** [comment]
Sorry for the late reply.

Indeed, without the KC3 running, there is no error spam.
There is, however, still the error shown in this picture:
![clipboard01](https://cloud.githubusercontent.com/assets/19510561/15552060/c0893e9e-22b0-11e6-846c-9c6e116aa248.jpg)

**Comment by dragonjet** [comment]
still unable to reproduce, does it still persist?

**Comment by Kam0laZ** [comment]
Wow, I didn't expect you to still be following this thread.

Anyway, that particular issue is long since gone. Sorry for not updating the status, and thanks for the fix.

What I have now is this:
![clipboard01](https://cloud.githubusercontent.com/assets/19510561/16958302/de5ea51a-4dd7-11e6-998d-1c2d4a541f48.jpg)
But otherwise it works just fine, no problems at all.

Thanks for the support, kepp up the excellent work.
You can close this thread now
