### ISSUE TITLE
[ Suggestion ] Bauxite Cost Indicator

### ISSUE THREAD

**Issue by JD-Kurotoshigami** [KC3Kai/KC3Kai#1392]
Detect if the current bauxite is enough to resupply all the planes in the current fleet, or how much bauxite is needed.
As far as I know, 1 plane = 5 bauxite

**Comment by LostLogia4** [comment]
Been requesting that one to be added into Activity Tab since quite some time ago.

**Comment by sinsinpub** [comment]
Calculating resupply cost (prediction) and show resupply results activity (via API) are two different tasks, I think.
According `calcExpeditionCost` methods, I guess I can add the resupply cost (including bauxite) to the panel tooltip. This may be more useful than just show up result activity :smiley: 

btw, land base resupply results (bauxite) are shown in game already...?

**Comment by sinsinpub** [comment]
A question: is bauxite cost also applying 85% rule for married ship? where should the 85% be applied to? equip slot max capacity or just `bauxite cost * 85%`? anyone could test it or give a doc link?

**Comment by mikenzb** [comment]
Already implemented when you mouse over supply status? Reopen if needed.
