### ISSUE TITLE
.SWF network status "cancelled" when choosing "Play via API Link"

### ISSUE THREAD

**Issue by si54l2e** [KC3Kai/KC3Kai#1404]
Ever since the June 10 update, KC3 Kai (30.3.1) has not been loading properly, as it seems to fail to acknowledge the game's presence, like so:
![capture1](https://cloud.githubusercontent.com/assets/13566391/15983939/f5294cf2-2f6c-11e6-9eb7-df3152d37f2e.PNG)
(Yes, I did start the game like normal, opening the dev tools once the API was extracted, selecting the KanColle tab, etc.)
In my attempt to find the cause of this problem, I decided to take a look under the Network section of the Dev Tools, and found this:
![capture2](https://cloud.githubusercontent.com/assets/13566391/15983963/be64164c-2f6d-11e6-8bcc-38f52ed8ecd2.PNG)
Is this behavior responsible for the extension not loading properly? Are there other steps I can take besides reinstalling the extension (attempted to no avail)?
If it helps at all, here is the problem resource copied as cURL (cmd):
`curl "http://125.6.188.25/kcs/mainD2.swf?api_token=68712e757ff916e5698fccd94347b2b67b761590&api_starttime=1465628873163" -H "Upgrade-Insecure-Requests: 1" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2763.0 Safari/537.36" --compressed`
and as HAR:
[har.txt](https://github.com/KC3Kai/KC3Kai/files/310156/har.txt)
Hopefully this will be enough to get to the root of this problem!
P.S. I apologize for my long inquiry, any suggestions to make any future queries less unwieldy are appreciated.

**Comment by dragonjet** [comment]
the only way I can think of that network requests from flash cannot be detected is that you're not using the built-in chrome's pepperflash. can you check your chrome settings if any plugins have been changed?

**Comment by si54l2e** [comment]
As it turns out, I seem to have resolved the problem by disabling Flash, restarting Chrome, then reenabling Flash, and restarting Chrome once more.  Weird.  Anyways, thanks for your help with my unexpectedly simple problem! :-)
