### ISSUE TITLE
F22 Quest name error

### ISSUE THREAD

**Issue by nicolas22g** [KC3Kai/KC3Kai#1405]
I find a small error on the quest F22. She is noted as F23 on the panel and F25 in the flowchart in the strategy room.

![sans titre](https://cloud.githubusercontent.com/assets/14291618/15993479/1c9e84b0-30e8-11e6-98cf-0929cc41d029.png)
![sans titre3](https://cloud.githubusercontent.com/assets/14291618/15993489/65d8f34a-30e8-11e6-8583-878b11e87a74.png)

Wikia picture (just for check)
![sans titre2](https://cloud.githubusercontent.com/assets/14291618/15993482/37f08ef2-30e8-11e6-9a95-7734b2e33444.png)

**Comment by sinsinpub** [comment]
Thx for report, fixed at 
https://github.com/KC3Kai/kc3-translations/commit/de8911542c36b562035a32f5e4d18c60a7bf0ce8

ps. F25 is another quest which quite similar with F22, it might be correct.
