### ISSUE TITLE
[Feature Request] one column in ship list for ships' expedition status

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#1406]
see: https://www.reddit.com/r/kancolle/comments/4mryrm/the_admirals_lounge_month_6_week_2/d45qqke

> Wishful thinking: KC3Kai adds a column in the ship list page that shows if a ship is out on expedition or not. This would make sparkling idle ships (DDs and CLs, mainly) easier.

> The idea is to enhance it a little bit, so we can see "this ship" is on fleet number N, doing expedition. If possible :)

**Comment by sinsinpub** [comment]
I've added a colored name to indicate which fleet she belongs to. 4 coloring is like 'locking tab': blue: fleet 1, green: fleet 2, yellow: fleet 3, orange: fleet 4
![image](https://cloud.githubusercontent.com/assets/160240/16072978/4a121de6-3316-11e6-84ac-3ad1821e6544.png)
like this, which also tell me which ships are on exped, is this alright?
retrieving expedition status seems not be efficiency...

**Comment by Javran** [comment]
@sinsinpub I'm getting the same idea as yours: as might not have room for adding another column, some kind of indicator would be better, in this case you have made color to tell the difference, I think it's good.

just having 2 concerns: (1) I feel some colors are hard to see, maybe you can try to make them a bit darker or change the color of background instead (2) what to do with married ships? as they are colored in pink already.

**Comment by sinsinpub** [comment]
yep, use lighter background instead, not affect marriage color:
![image](https://cloud.githubusercontent.com/assets/160240/16077226/2cea5706-332a-11e6-8895-9696a204b80e.png)

**Comment by dragonjet** [comment]
agree on backgrounds :+1:

**Comment by nonsensed** [comment]
Nice change. One small problem: married ship text color + fleet color. The married ship text color is fairly bright and so is the fleet color.

Small note: Colorblind people will have trouble distinguishing the orange and yellow. Not a big deal for this, though.

**Comment by sinsinpub** [comment]
@nonsensed lol, I have no change to get the feeling of bigamy, and colorblind neither :joy: 
tried to add text shadow to clarify pink text viewing

**Comment by nonsensed** [comment]
@sinsinpub Hmm... you have no married ships? Here is how they look in the list:
(1-2 webstore version, 3-5 white border)

![image](https://s32.postimg.org/e04cbfd0l/border.png)

I made the last set. Is it bad? I feel the contrast is needed. I'm color blind and I can't see pink. I don't know if that text is still pink..... hahaha.

```
.tab_ships .ship_item .ship_kekkon-color {
	color: #ECC7D9;
	text-shadow: #555 -0px -0px 1px, #555 1px 1px 1px;
	-webkit-font-smoothing: antialiased;
```

**Comment by nonsensed** [comment]
Btw, I'm not saying what I changed should be used (I like it, but maybe it feels too much like bubble text). I'm not sure if the white background is effective. It does improve the visibility of the letters to a point, but it still lacks contrast.

I'm not sure if non-colorblind people can see the blue background/pink text with no problems. Let me try to show this sort of how a colorblind person can see it. Almost no people are 100% colorblind, but this still works:

![image](https://s32.postimg.org/7gvmfbsfp/borderbw.png)

The pink text doesn't have much contrast with the blue backgrounds. Similarly, the yellow and orange colors are difficult to see a difference in. Tanaka is an evil, evil man for choosing those shades of yellow/orange/green.

5-8% of people in the world are colorblind, and it's mostly men. Considering it's mostly men playing this game, the % is higher for KC3 users. Most colorblind people are red-green spectrum, so mixing green->yellow->red is the most dangerous color scheme to use for web design.

**Comment by dragonjet** [comment]
maybe if we use double/triple text shadow instead? I abuse that sometimes just to make it viewable, e.g. subtitles.

**Comment by nonsensed** [comment]
Didn't ssp already make it a double shadow?
```
+	text-shadow: #fff -1px -1px 1px, #fff 1px 1px 0px;
+	-webkit-font-smoothing: antialiased;
```
^ This is in the latest commit.

But it's white, so I was being a pain in the ass about it because I want a grey or black shadow* !

*because colorblind reasons

**Comment by dragonjet** [comment]
I agree with black, I usually use it coz they are also used in anime subtitles, so black is a proven :sweat_smile:

**Comment by nonsensed** [comment]
Does the shadow make these difficult to read? Kanji is so compact.... but I can't read kanji anyway.
![Image](https://s31.postimg.org/wz1pts4xn/border2.png)

```
.tab_ships .ship_item .ship_kekkon-color {
	color: #eec5c3;
	text-shadow: #2f2727 -0px -0px 1px, #2f2727 1px 1px 1px;
	-webkit-font-smoothing: antialiased;
}
```
![Image](https://s32.postimg.org/6crlh5shh/borderb.png)

```
.tab_ships .ship_item .ship_kekkon-color {
	color: #eec5c3;
	text-shadow: #000 -0px -0px 1px, #000 1px 1px 1px;
	-webkit-font-smoothing: antialiased;
}
```

**Comment by dragonjet** [comment]
@nonsensed are the shadows in `master` branch? I don't see it in the shiplist :sweat_smile:

**Comment by nonsensed** [comment]
Oh right this thing! Nah, what I did was never added. I wasn't sure so I let it go.

**Comment by nonsensed** [comment]
If colorblindness issues become important, I or whoever else will make a new issue about it. I think this issue can safely be closed, right?
