### ISSUE TITLE
French translation ?

### ISSUE THREAD

**Issue by Xwilarg** [KC3Kai/KC3Kai#1409]
Hi,

I noticed that the interface is translated in french, but the dialogues aren't.
I wanted to know if it's was planned, or if there was a way to help with that.

Thanks in advance.

**Comment by dragonjet** [comment]
Unfortunately, we do not have active french translators as far as I know but guys can correct me if im wrong. Our translation efforts are on this repository:
https://github.com/KC3Kai/kc3-translations

We appreciate all help we can get. If you can use git, you may submit pull requests and we'll merge it into the app. :+1:

**Comment by Xwilarg** [comment]
I'll try to see how the website is working, thanks for your answer :).
