### ISSUE TITLE
Request translation repo access

### ISSUE THREAD

**Issue by Xwilarg** [KC3Kai/KC3Kai#1410]
Hi,

I'm new in GitHub, so I don't know how everything is working, but I would like to help about french translations.

Thanks in advance :).

**Comment by dragonjet** [comment]
Good day, thank you for taking interest in working with us in KC3 translations. However, as mentioned in the [readme file in the TL repo](https://github.com/KC3Kai/kc3-translations/blob/master/README.md),  you will first need a fork, and a pull-request for us to be able to check you work first before giving anyone direct write access

**Comment by Xwilarg** [comment]
Oh, sorry :p.
I'll do that.

**Comment by Xwilarg** [comment]
Um... I'm sorry, but I'm not sure about what I'm suppose to do, I made a fork, etc, but I think I'm stuck in this step: "Commit your new language files, and push to your own GitHub repo"
Here's what I have: https://i.gyazo.com/6ef164bc9b1aadc9aa702574c09d544b.png

Sorry if my question is stupid but... Why should I do ?

Thanks in advance.

**Comment by Crazyteitoku** [comment]
This may help: http://stackoverflow.com/questions/7555551/adding-files-to-a-github-repository

**Comment by dragonjet** [comment]
closing since @Xwilarg is now added
