### ISSUE TITLE
Incorrect prediction results in anti-submarine battles

### ISSUE THREAD

**Issue by bcc32** [KC3Kai/KC3Kai#1416]
Looks like there is a new battle phase before the initial torpedo phase where ASW ships can shell subs.  This is causing some bugs with battle result prediction and results.

Screenshots [here](http://imgur.com/a/RZ9as).  Log of battle and battleresult API calls [here](https://gist.github.com/bcc32/0458bd4db74e2f4029e637849d10e6e8).

**Comment by LostLogia4** [comment]
Duplicate of #1412, should be fixed now.
