### ISSUE TITLE
F38 not counting

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#1418]
I scrapped 12.7mm machine gun 6 times one by one with F38 in progress, none of them get counted.

cc @sinsinpub

**Comment by sinsinpub** [comment]
F38 is a typo, correct one is F34 (id 638)...
But after I just scrap this (the same with 12.7mm, type[2]==21)
![image](https://cloud.githubusercontent.com/assets/160240/16563086/b55f29c4-4232-11e6-959c-25eff7847af6.png)
tracking progress becomes:
![image](https://cloud.githubusercontent.com/assets/160240/16563124/defe2fbe-4232-11e6-8faa-ec0b5657f60c.png)

and scrap 2 guns in row tested too days ago.  Codes are simple, maybe a debug needed?
oh, and progress tracking requires `tracking` data (in `en/quests.json`) and codes ready before opening F34 quest. Remove the F34 once, and re-active it may fix?

**Comment by Javran** [comment]
@sinsinpub ah I got it, I have pulled the latest translation repo but not with the lastest commit in this repo. that explains why my F34 quest tracking was showing `0/6` but not counting.
will keep an eye on F34 next week, but for this issue it's good enough to close, as you've tested it.
