### ISSUE TITLE
KC3改 Credits

### ISSUE THREAD

**Issue by dragonjet** [KC3Kai/KC3Kai#142]
@nevrending @bamboo3250 @tmerta @Crazyteitoku @ReiFan49 @Javran 

I'm going to redo the About/Settings page. If you guys have preferred links to your fan pages or twitter accounts, put them here so I can put the proper icons. We can support up to 5 links. Put in anything you want, twitch, pixiv or dA :sparkles:

This will also apply for future contributors so I'll keep this thread open.

**Comment by bamboo3250** [comment]
That's nice :+1: I would like to have these links in the About page :relaxed: 

Kancolle Wikia: http://kancolle.wikia.com/wiki/User:bamboo3250
Github: https://github.com/bamboo3250
Twitter: https://twitter.com/bamboo3250
Pixiv: http://www.pixiv.net/member.php?id=3875741
DA: http://bamboo3250.deviantart.com/

I haven't drawn for a while but... oh well... xD

**Comment by Crazyteitoku** [comment]
:+1: I think for now I am fine with the wikia links. I don't use much other services :laughing:

**Comment by nevrending** [comment]
Wow, this is cool :+1: 
I would like to have these if it's possible:

Github: https://github.com/nevrending
Kancolle Wikia: http://kancolle.wikia.com/wiki/User:NevREnding
(^ nothing to see there tho lol)
Facebook: https://www.facebook.com/y458m
Twitter: https://twitter.com/yefta458
Web: https://yefta.com

Tho I rarely use some of them >.<

**Comment by Javran** [comment]
Cool XD
Mines are:

Github: [Javran](https://github.com/Javran)
Twitter: [JavranC](https://twitter.com/JavranC)
Web: [Javrania](http://javran.github.io/)

**Comment by dragonjet** [comment]
@McDohl @Erupi @LostLogia4 @AlanSchaeffer

**Comment by McDohl** [comment]
GitHub : https://github.com/McDohl
kancolle wikia : http://kancolle.wikia.com/wiki/User:McDohlJr
Facebook: https://www.facebook.com/endruhugen

**Comment by dragonjet** [comment]
@Diablohu

**Comment by Diablohu** [comment]
Diablohu

Web: http://diablohu.com
GitHub: https://github.com/Diablohu
Twitter: https://twitter.com/Diablohu
Weibo: http://weibo.com/diablohu

**Comment by dragonjet** [comment]
@nicky008

**Comment by nicky008** [comment]
GitHub: https://github.com/nicky008
Twitter: https://twitter.com/nicky_008
Facebook: https://www.facebook.com/jamesnicky008
kancolle wikia: http://kancolle.wikia.com/wiki/User:Nicky008

**Comment by dragonjet** [comment]
@kololz

**Comment by dragonjet** [comment]
@Arkayda963

**Comment by Arkayda963** [comment]
GitHub : https://github.com/Arkayda963
Facebook : https://www.facebook.com/ryu.nagakawa
Kancolle Wikia : http://kancolle.wikia.com/wiki/User:Arkayda

**Comment by dragonjet** [comment]
@c933103

**Comment by c933103** [comment]
English KanColle Wiki: kancolle.wikia.com/wiki/User:Qunow
twitter: twitter.com/c933103
github: github.com/c933103
Chinese MoeGirl Wik:ihttp://zh.moegirl.org/wiki/User:C933103

**Comment by dragonjet** [comment]
@rephira can add up to 5 links you want

also, what do we put in the language selection text for korean? It's usually in the native writing of that language

**Comment by rephira** [comment]
@dragonjet 한국어 would be the way to go. Sorry for the oversight. Prolly should have specified XD

**Comment by nicky008** [comment]
Nice, nice...

I'd add Thai for my next TL work if I have more time to do.

**Comment by ethrundr** [comment]
@dragonjet mind adding my credits:

Facebook: https://www.facebook.com/ethrundr
Himeuta: http://www.himeuta.net/members/1056-ethrundr/

**Comment by dragonjet** [comment]
@NicolaosGreene

**Comment by NicolaosGreene** [comment]
Github: https://github.com/NicolaosGreene
Steam: http://steamcommunity.com/profiles/76561198023180048/
Himeuta: http://www.himeuta.net/members/8927-nicolaos/
English KanColle Wiki: http://kancolle.wikia.com/wiki/User:NicolaosGreene

**Comment by ReiFan49** [comment]
Facebook: http://facebook.com/ReiHakurei
Twitter: http://twitter.com/Rei_Fan39 (49 ones are protected and inactive, 39 ones are public and active, for SIF)
(actually i'm confused lol since i comeback again `:p`)

**Comment by ethrundr** [comment]
I'd like to add one more link to my credit if still possible:

KAORI Nusantara Forum: http://www.kaorinusantara.or.id/forum/index.php?members/ethrundr.18705/
For the icon, you can use this (the image color is white, 40x40):
![logo kaori-nt](https://cloud.githubusercontent.com/assets/13522800/9349002/3a337caa-467a-11e5-87e5-e2e96ae1742d.png)

**Comment by Javran** [comment]
ah, you can also add a Sina Weibo to me (Chinese): http://weibo.com/JavranC

**Comment by dragonjet** [comment]
updated

**Comment by dragonjet** [comment]
btw @ethrundr and @bcc32 are you guys on dev build or webstore?

**Comment by ethrundr** [comment]
I'm using the dev build
![screen shot 2015-09-08 at 12 24 39](https://cloud.githubusercontent.com/assets/13522800/9725799/9e3559a8-5624-11e5-9dfd-3cb274760419.png)

**Comment by bcc32** [comment]
@dragonjet dev build

![screen shot 2015-09-08 at 13 01 19](https://cloud.githubusercontent.com/assets/1239097/9741677/b49ca638-5629-11e5-9cbf-642e8223ce64.png)

**Comment by dragonjet** [comment]
aye thanks @ethrundr @bcc32

**Comment by nekoworkshop** [comment]
Nekoworkshop

Twitter: https://twitter.com/nekoworkshop

Github: https://github.com/nekoworkshop

**Comment by Crazyteitoku** [comment]
@arialypse and @Anime-Thai

**Comment by kololz** [comment]
kololz

KCWikia http://kancolle.wikia.com/wiki/User:Kololz

Facebook https://www.facebook.com/kololz

Github https://github.com/kololz

**Comment by arialypse** [comment]
@Arialypse
https://github.com/arialypse
https://www.facebook.com/Arialypse
http://kancolle.wikia.com/wiki/User:Arialypse
http://www.zeitvier.com/

@Anime-Thai
https://github.com/Anime-Thai
https://www.facebook.com/profile.php?id=100009261752211
http://www.anime-thai.net

**Comment by dragonjet** [comment]
These days I talk to new contributors one by one

**Comment by ethrundr** [comment]
adding @HR-xero for new ID Translator 
@dragonjet

**Comment by dragonjet** [comment]
:+1:
