### ISSUE TITLE
Hiryu quotes

### ISSUE THREAD

**Issue by tinefanforvettel** [KC3Kai/KC3Kai#1427]
I'm confused about her attack quotes [16] because she only say short sentence

> Contact with enemy vessels, get ready for battle. Second attack phase required. Hurry! Alright Tomonaga Squadron, I'm counting on you.

Obviously she say 
> Second attack phase required. Hurry!

Can you change it @dragonjet ?

**Comment by nonsensed** [comment]
Thanks for the report! It'll be fixed the next time kc3kai is updated. If you notice any more issues like that, you can report them in #1311.

**Comment by dragonjet** [comment]
pulled in the updates made by @nonsensed and the translators from the TL repo for the next 30.5.0 update
