### ISSUE TITLE
No Subtitles

### ISSUE THREAD

**Issue by HeroFighte** [KC3Kai/KC3Kai#1428]
i know this is not realy urgent... but i would love to have subtitles... i tried everything to get them to work... but there are no subtitles apearing for me... thank you for listening ^^

**Comment by dragonjet** [comment]
have you tried playing via DMM frame or API Link?

**Comment by HeroFighte** [comment]
Yes i actualy tried that... Still there would nothing appear... ^^;

**Comment by LostLogia4** [comment]
Check the settings menu and check that the subtitle option is ticked.

**Comment by HeroFighte** [comment]
It is i checked it like 4-5 times already just to be sure

Am 18.07.2016 03:49 schrieb "LostLogia4" <notifications@github.com>:

**Comment by Crazyteitoku** [comment]
Ah right here is the background information if interested: http://kancolle.wikia.com/wiki/Thread:453852

**Comment by dragonjet** [comment]
I recommend teamviewer as I do to everyone else :wink:

**Comment by HeroFighte** [comment]
Well then i gotta find time in the next days first... Busy days lately...
^^;

Am 18.07.2016 13:26 schrieb "dragonjet" <notifications@github.com>:

**Comment by kagaposting** [comment]
Try this: go into the devtools pannel (ctrl+shift+J or command+shift+I or f12) and  click on the >> to the right of proflies. once there, click on the "kancolle" tab. This shall activate the admiral dashboard and enable the subs. maybe this is a bigger problem for you, but it worked for me.

**Comment by dragonjet** [comment]
more possible causes on why subtitles won't appear:
* voice / sound is disabled in-game
* kancolle tab not open in devtools
* using direct DMM website gameplay (this one will be solved on #1645)

closing for now until more info from reporter
