### ISSUE TITLE
Can't login, told to refresh the page constantly

### ISSUE THREAD

**Issue by refiero** [KC3Kai/KC3Kai#1431]
Hi there! I felt the sudden urge to play Kancolle today but whenever I try to login to dmm I get [this](http://puu.sh/q3O8Z/80c945e628.png) error and after it pops up a few more times, I block the page  from making it pop up.

After I enter my email and password however, I get the same error, just in the form of words on the [page](http://puu.sh/q3Oqq/b9f2c013fd.png)

I've tried clearing my cache, and reinstalling KC3Kai

**Comment by dragonjet** [comment]
this is normal when playing via DMM frame or DMM website. I usually just press on Cancel to avoid refreshing the page. This is natural DMM behavior and KC3Kai has no touch on this endpoint.
