### ISSUE TITLE
Annoying taiha gui conflicting during provisional marriage

### ISSUE THREAD

**Issue by happyh0rse** [KC3Kai/KC3Kai#1432]
![unknown](https://cloud.githubusercontent.com/assets/13378888/16901273/293d8fd2-4c71-11e6-8a6a-ae0459576cba.png)

Visual only, though KC3 SS capture somehow shows a clean screen.

Awesome nosebleed, I'd say.

**Comment by dragonjet** [comment]
I believe this is the same bug as #1433, which triggered the Taiha alert regardless of ship HPs, as long as you took a screenshot. This is now fixed for the next release #1438
