### ISSUE TITLE
About latest update error

### ISSUE THREAD

**Issue by Lyphese** [KC3Kai/KC3Kai#1433]
http://imgur.com/a/2eRq4

1. If I click the screenshot button, suddenly highly-damaged warning occurs, regardless of situation. Warning disappears if i back to port. Also, during sortie, warning disappears in battle screen.

2. This is a kind of korean translation error...
New seasonal quest which gives Skilled Crew Member is translated as mass anti-air gun production.
And existing mass anti-air gun production quest is blank.

"대공기총 양산"
"기총"계 장비를 양산해, 공창에서 6개를 폐기! "장비개수"의 강화를 지원하라!(대공기총 6개 폐기, 일괄로도 가능)

I retyped as korean for someone who wants to use google translator.

**Comment by dragonjet** [comment]
will look into the screenshot-alert error

tagging @rephira and @Yukinyaa for the KR translation
