### ISSUE TITLE
Hard to see Aircraft Type becuse of Aircraft Proficiency badge

### ISSUE THREAD

**Issue by Natsu-kun** [KC3Kai/KC3Kai#1434]
With new update, it's hard to identify which type of aircraft that my ship equipped.
Yellow aircraft is fine but others are terrible to see it.

My Hiyou is equipped with Ryusei, Suisei, Reppu, and Saiun.
![screenshot 2016-07-17 23 30 40](https://cloud.githubusercontent.com/assets/7970907/16901763/b9c99abe-4c76-11e6-9fd7-b1c97530bab5.png)

**Comment by Javran** [comment]
might not have time on this today, just some ideas:

- move air proficiency indicator to somewhere else, maybe just the top-right color, I doubt it'd look better though
- color number indicators correspondingly, but by doing so we'll still have the same problem when the entire slot is shot down (I guess that's okay, as an empty slot of plane contributes to nothing except maybe eLoS)

will experiment when I have time, but I'd like to know what others are thinking? @dragonjet @sinsinpub

**Comment by sinsinpub** [comment]
how about this?
![image](https://cloud.githubusercontent.com/assets/160240/16904835/4e7c1684-4ccf-11e6-8571-23affbeda76e.png)

**Comment by Natsu-kun** [comment]
Look great.

**Comment by Javran** [comment]
@sinsinpub lgtm!
