### ISSUE TITLE
Error on strategy room

### ISSUE THREAD

**Issue by ramaratus** [KC3Kai/KC3Kai#1437]
Help please, after the latest update of KC3Kai (30.5.0) (it automatically update, i was afk when the update happened), everytime i opened the ships tab on library in the strategy room, it always show blank page. I've already refresh it in page (heart logo) several times and reload the chrome tab, also restart my chrome, but it still showing blank page. and whenever i got into the ships tab, it stuck there, i can't navigate to other tabs, so i must close the strategy room tab and open new strategy room tab. is there any way to fix this ?

**Comment by dragonjet** [comment]
open the F12 panel on the Strategy Room, then go to the Console tab and see if there are any errors.

In any case, this might help:
* Resources > Local Storage > `chrome-extension://...` > Click on `ships` record > Delete using **X**. Refresh the game, and wait until Home Port > Go back to Strategy Room Ships tab

**Comment by ramaratus** [comment]
@dragonjet i've tried to delete the ships record on the resources tab, restart my chrome opened it again but it still giving me those errors. i also already checked the console tab for the strategy room tab, there's 3 errors:

1. chrome-extension://hkgmldnainaglpjngpajnnjfhpdjkohh/assets/css/bootstrap-slider.min.css
Failed to load resource: net::ERR_FILE_NOT_FOUND

2. chrome-extension://hkgmldnainaglpjngpajnnjfhpdjkohh/assets/js/bootstrap-slider.min.js
Failed to load resource: net::ERR_FILE_NOT_FOUND

3. Uncaught TypeError: a.atLvlSlider.slider is not a function allstrategytabs.js:22

is reinstalling and installing the kc3kai again can fix this ? or is there another method ?

**Comment by dragonjet** [comment]
ah! you're right, I thought it was the ship list, sorry I misunderstood.

I see this error now and will fix it.

**Comment by ramaratus** [comment]
@dragonjet no problem, glad i could help pointed out the bug
