### ISSUE TITLE
Strategy Room translating. "To be or not to be?"

### ISSUE THREAD

**Issue by Agc0de6** [KC3Kai/KC3Kai#1439]
With this quote from Shakespeare, I'll open a discussion about Strategy Room (StR) translation, 'cause it is last and biggest untranslated part of KC3's main program.

Should we do to StR the same thing as to pre-loading pages (will take a big ton of new text variables)? Or there is another way to do this?

Your thoughts, please.

**Comment by dragonjet** [comment]
iirc @kololz started on this but only for the menu / tab items. before, I'd recommend not to as there is a planned overhaul of the strategy room. but I don't think it will come soon, not at least for a few more seasons, so if there is a desire to translate them, we can go ahead and do so. it's not like we will use different words once we do an overhaul :smile:

**Comment by sinsinpub** [comment]
i planed a separated terms.json file loaded only for SR to hold tons of new messages

**Comment by Agc0de6** [comment]
Ok, @dragonjet. I'll close this issue until this overhaul will be done.
