### ISSUE TITLE
Screenshots not working

### ISSUE THREAD

**Issue by Dirtnap86** [KC3Kai/KC3Kai#1440]
hey all, first time contributing to the bug reports. I seem to have an issue with screenshotting. I click the button and instead of saving an image an error pops up in the chrome console. attached is said error.

Hope these help.
![error 1](https://cloud.githubusercontent.com/assets/20550264/16974741/b17f2796-4e0d-11e6-9d83-0ab5d92c0127.JPG)
![error 2](https://cloud.githubusercontent.com/assets/20550264/16974740/b17a716a-4e0d-11e6-83df-9cde0371d4df.JPG)

**Comment by dragonjet** [comment]
thanks for reporting I'll take a look at this tonight
