### ISSUE TITLE
nonsensed in credits list

### ISSUE THREAD

**Issue by dragonjet** [KC3Kai/KC3Kai#1443]
@nonsensed you've been a big help with the lines and looking at the issue / PR list for the repos. I'm not sure if I've asked you this before, but you can give up to 5 links that we can put under your name to be added as a box in the credits list.

also if there's any contributor I've forgotten to add to the list, please do notify me on this thread. don't be shy, I want to make sure everyone who had a hand on this are credited correctly. and if I did forget anyone, sorry for missing it out, but I'll add you no worries. just link the PR or issue so that I can be reminded on which section to put.

**Comment by nonsensed** [comment]
It's cool. I'm a social media luddite. Ain't got no links! Get off my lawn!

**Comment by LostLogia4** [comment]
And there ya go... you don't mind if we add you in the credits section, would you?

**Comment by nonsensed** [comment]
Anything is fine!

**Comment by dragonjet** [comment]
hehe still, we know your github link :smiling_imp:
