### ISSUE TITLE
regarding highlighting close-to-remodel ships

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#1445]
I feel there are several things can be improved:

- leaving this strategy page on seems to cause some moderate CPU usage, I'll recommend leaving an option for user to decide whether they want it to be blinking

- there are several ships whose level is beyond remodel-level, (or has a cyclic final form) and these ships keep blinking regardless of the setting, I guess this is not an intended behavior:

![2016-07-22_005200_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/17031396/8aa5bc12-4fa6-11e6-9bc9-30b5f69c3ed9.jpg)

- I've tried changing leveing difference to `-1` and `0`, but in both case ships mention in the bullet above are still blinking.

**Comment by sinsinpub** [comment]
suggest that move leveling diff option out from Settings page,
Strategy Room specified options may be kept inside page tab itself (persistable and take effect immediately)

**Comment by dragonjet** [comment]
hmm when I set it to `0`, it didn't blink anymore or was this fixed in between?

**Comment by sinsinpub** [comment]
@dragonjet special case: convert remodel (kai 2 <--> kai 2 A/B/C/D)

**Comment by dragonjet** [comment]
ohh, in those cases we probably should uhm, make a whitelist exceptions

**Comment by Javran** [comment]
I think the CPU usage need to be addressed quickly, for now I have to comment out those blinking css rules so that CPU won't constantly be busy (not heavily loaded, but my CPU fan is making some noise) (it also slows down the game a bit). I'm already on a gaming laptop and I suspect the situation for other players won't be better.

@sinsinpub hm I don't get it where can these options be replaced other than Settings pages, you meant moving these setting controls to the leveling tab and make it persistent?

**Comment by dragonjet** [comment]
or better if an option to make it just change background color and not animate?

**Comment by dragonjet** [comment]
also a user suggested to have an option to hide level 99s for those who don't buy rings

**Comment by Javran** [comment]
hm, I just assume none of you have been working on this. self-assigned to make some progress during this weekends.

**Comment by dragonjet** [comment]
:+1: I'm currently on the dark theme for strategy room and next is LBAS interface on the panel so feel free to take this

**Comment by Javran** [comment]
I took a closer look at CPU usage when animation is enabled, and it was really high:
![2016-08-06_234741_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/17457632/459e90b2-5c30-11e6-880c-23d5036b25c7.jpg)

the animation is setup by CSS so I have no idea whether there are ways of optimizaiton. but I begin to feel there is simply no need to make it animated - in my opinion strategy room tabs are ususally opened along with the game, besides performance issues, I find an animated strategy room tab distracting as I only expect things in game screen to be changing without mouse actions.

to address the performance issue, I plan to simply remove animations and want to know what do you think about this @dragonjet @sinsinpub @DynamicSTOP

**Comment by DynamicSTOP** [comment]
@Javran 
Yep, it was pure css. I don't think that there is a way to optimize it without editing chrome sources. I am ok with static background since animation causes troubles.

**Comment by Javran** [comment]
@DynamicSTOP got it, thanks for the response!

I can't find my exact pc spec, just listing few things that would matter: Intel(R) Core(TM) i7-4700MQ, 16G mem, GeForce GTX 770M

**Comment by dragonjet** [comment]
that's a really good spec, better than my desktop actually. now i start to think there's an underlying problem than causes this. chrome is latest stable right?

**Comment by Javran** [comment]
@dragonjet not the latest, might be a bit out-dated: 50.0.2661.102
my network environment isn't good so I'm reluctant to perform any non-critical system update.

**Comment by Javran** [comment]
@dragonjet um, are you suggesting the CPU usage isn't as high on your machine?

I think another factor might be ship capacity, I have more than 270 ships so there are lots of stuff blinking

**Comment by dragonjet** [comment]
ah that's probably it, I'm only using my alt and doesnt have that much ships. let me try on my side adding the blink to all ships and see if the same happens

* normal animation: 10~15 CPU
* animation on all boxes (60 ships animating): 25~30 CPU
* no animation: 0~1 CPU
