### ISSUE TITLE
Some sentences are too long when translated

### ISSUE THREAD

**Issue by Xwilarg** [KC3Kai/KC3Kai#1446]
Hi,

I noticed that problem in some language : 
https://gyazo.com/29e8c215341487f4dbcca51e5fa95251

The sentences are too long and so they can't be displayable entirely.

**Comment by dragonjet** [comment]
which language is this? usually it's up to the translators to shorten the statement as long as the idea doesn't change. if we can specify which language this is, we can tag corresponding translators

**Comment by rephira** [comment]
You can use the break tag <br> to force line change.

**Comment by Xwilarg** [comment]
The languages are portugues, espanol and dutch.
