### ISSUE TITLE
[Suggestion] Effect of Akashi's improvement on AA of Fighter and Fighter-Bomber plane

### ISSUE THREAD

**Issue by HKGPsy** [KC3Kai/KC3Kai#1455]
For each level of improvement (star), there would be 0.2 additional AA value for carrier based fighter plane and 0.25 for fighter-bomber plane

It would be nice if the fighter power calculator can take this into account for more accurate calculation

Source: 
Carrier based Fighter plane: [http://ja.kancolle.wikia.com/wiki/%E3%82%B9%E3%83%AC%E3%83%83%E3%83%89:951#26]
Fighter-bomber plane: 
[(http://ja.kancolle.wikia.com/wiki/%E3%82%B9%E3%83%AC%E3%83%83%E3%83%89:951#32)]

**Comment by Javran** [comment]
carrier-based fighters are already taken into account in PR #1430 
will do the same for fighter-bombers.
