### ISSUE TITLE
Problem with the KC3 Kai pluggin: blood appear on the screen

### ISSUE THREAD

**Issue by Xwilarg** [KC3Kai/KC3Kai#1457]
Hi,

I'm using the 51.0.2704.103 m version of Google Chrome, I'm on Windows 7 64 bit and I'm using the latest version of KC3 Kai.

Here's my problem : 
I installed KC3 Kai in a computer so my little sister can play Kantai Collection, but when I opened the game, there was a lot of blood in it and we were able to hear heartbeat.
Here's a screenshot: https://i.gyazo.com/7cc05d16b2cdd84855db620d56074ede.png

This is only happening when I'm using KC3 Kai, I have no problems without it.

Thanks in advance :).

**Comment by Xwilarg** [comment]
Oh, ok, I found something about that in the KC3 Kai options, something named 'Annoying Taiha Alert".
But I still can't understand what is it.

**Comment by nonsensed** [comment]
It gives you an alert when a ship has low HP (Taiha). In your image, Yuudachi is Taiha'd. The warning is to help prevent people from sinking their ships.

You can customize it as you wish thanks to a pretty nice update from dragonjet. For a minimal alert, you can try only using "Red shade on panel".

**Comment by Xwilarg** [comment]
Oh, well, that was a little scarry ><.
It's weird because I never had this in my game.

**Comment by dragonjet** [comment]
thanks for letting us know when you see something that doesn't seem right though, this keeps us alert if there are things we missed that might affect only certain systems. in this case however, you might wanna ask your sister to repair the damaged girl, she might sink it :wink:
