### ISSUE TITLE
sunk ships not marked

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#1462]
latest master branch. sunk ships not marked  in battle panel. (isn't this supposed to be grayed out a bit with a "sunk" flag"?)

![2016-07-31_000911_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/17271618/37f8a7c2-56b3-11e6-8f9d-3166e36b741b.jpg)

**Comment by dragonjet** [comment]
hmm it marks on my side, latest master branch, 1-1-C

![ss 2016-07-31 at 11 09 33](https://cloud.githubusercontent.com/assets/557312/17274186/46866476-570f-11e6-9e1a-4d2bdf370400.jpg)

**Comment by Javran** [comment]
not sure why it happens, but seems it's gone on my side too. I could have pulled the latest master branch but didn't reload the extension. closing until maybe it happens again.
