### ISSUE TITLE
[Question] is travis-ci unit testing working?

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#1466]
this is the latest travis-ci build log:
https://travis-ci.org/KC3Kai/KC3Kai/builds/150249450
despite logs about building, I can't see any indication of running unit tests, so I'm wondering whether the code is properly tested.

**Comment by dragonjet** [comment]
you're right, i was under the impression that travis does an `npm test` right after installation.

I checked [older builds](https://travis-ci.org/KC3Kai/KC3Kai/builds/146776530) and seems `npm test` was actually running the unit tests before. I'll investigate

**Comment by dragonjet** [comment]
now fixed by 1cb7e4fe5a9b6a3de565ad78561e7eec4e835317 on [latest build](https://travis-ci.org/KC3Kai/KC3Kai/builds/150257197)
