### ISSUE TITLE
Replays with Boss Gauge

### ISSUE THREAD

**Issue by dragonjet** [KC3Kai/KC3Kai#1469]
Add `max_maphp` and `now_maphp` to the root of the replay JSON to support gauges in the replay animation

**Comment by fourinone41** [comment]
Also `api_defeat_count` for non-event maps.

**Comment by Vultren** [comment]
After a lot of jumping around i think I found where to add `max_maphp`. `now_maphp`, and `defeat_count`. Just noting it's in `Database.js:get_sortie_data` for later. I don't think we have `max_defeat_count` saved. 

Hey @fourinone41 the replay map data is up-to-date right? We can use that for the non-event EO maps

**Comment by fourinone41** [comment]
Yeah, my MAPDATA is up to date currently, so it's fine if it's not saved by KC3, was just hoping for convenience.

**Comment by Vultren** [comment]
Was implemented in #2014 and released in #2067
