### ISSUE TITLE
few TODOs for the event (Summer 2016)

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#1472]
- [ ] icons for new ships / abyssals
- [x] battle prediction, especially how preemptive anti-sub mechanism works for combined fleet (I will be working on this but first I need sample data)
- [x] update `nodes.json` to show letters (E1-E3 done, E4 missing)

**Comment by Javran** [comment]
all edges are now marked. just managed to clear E2H, will hopefully get some data for analysis.

@dragonjet will you be working on icons?

**Comment by dragonjet** [comment]
sure, ill make them before the scheduled release tonight :+1:

**Comment by Javran** [comment]
it turns out only escort fleet will do OASW regardless of what kind of combined fleet it is.
the current KanColleHelpers can already predict the result correctly, despite that it thought the damage was dealt by the main fleet.

updated accordingly on f2a6c4e, nothing should be changed on the surface.
