### ISSUE TITLE
Blur screenshot

### ISSUE THREAD

**Issue by etcet54** [KC3Kai/KC3Kai#1477]
Please make sure that you have these details on hand when submitting your issue/bug report as this will greatly speed up the issue triage process -- thank you!

- [52.0.2743.116 ] Your Chrome version - via chrome://version/
- [ Win 7 SP1] Your OS and its version
- [ 64 bit] 32bit or 64bit?
- [30.7.0 ] Your KC3 Kai version - via chrome://extensions/
- [ Chrome Web Store] Which build you have tried running? webstore version as in the one from [Chrome Web Store](https://chrome.google.com/webstore/detail/kancolle-command-center-%E6%94%B9/hkgmldnainaglpjngpajnnjfhpdjkohh) or Github variant (better known as developer builds).

------------------------------------------

Hello, I seems to have an issue with the screenshot feature. I've searched there's similar issue in here https://github.com/KC3Kai/KC3Kai/issues/174 and the solution was to reinstall chrome. I've tried the solution but unfortunately it seems the issue still exist. Tried changing screenshots settings one by one(download, new tab, jpg, png) but it doesn't help too.

For comparison I'm using kcv screenshot feature

**sample 1:**
kc3kai
![gr00](https://cloud.githubusercontent.com/assets/19471603/17646309/3d9fa8e2-61ee-11e6-90be-817d2bc752dd.png)
kcv
![gr01](https://cloud.githubusercontent.com/assets/19471603/17646310/3e7618fa-61ee-11e6-87b8-584a25c71655.jpg)

**sample 2:**
kc3kai
![er00](https://cloud.githubusercontent.com/assets/19471603/17646278/34d3e850-61ed-11e6-864e-b5da6cc86d7e.png)
kcv
![er001](https://cloud.githubusercontent.com/assets/19471603/17646279/3aa84262-61ed-11e6-8a32-689e557c10a8.jpg)

**sample 3:**
kc3kai
![fr00](https://cloud.githubusercontent.com/assets/19471603/17646264/a8a03596-61ec-11e6-9e28-e8e2138d9c3b.png)
kcv
![fr01](https://cloud.githubusercontent.com/assets/19471603/17646266/b565a37e-61ec-11e6-91f9-248a57f09dfc.jpg)

Does someone here might have experienced similar issue and found another way to fix it? Really appreciate the help.

Thanks.

**Comment by dragonjet** [comment]
hmm personally I think our screenshot is better since there are no artifacts.

currently, our screenshot quality setting though, is 70. as a solution, let's make it so that this quality is configurable by user.

**Comment by etcet54** [comment]
Thanks a lot dragonjet, I hope that would solve the issue

**Comment by dragonjet** [comment]
see this pull request for image quality samples:

https://github.com/KC3Kai/KC3Kai/pull/1488

**Comment by dragonjet** [comment]
@etcet54 I experienced this just now. It's because we are zoomed in on chrome. Screenshots get blurry. 

Try <kbd>Ctrl</kbd><kbd>0</kbd> and take another screenshot

**Comment by etcet54** [comment]
Tried Ctrl+0 and took another screenshot. doesn't seems to help. My chrome zoom is at default 100%.

update: 
Man, I think I found the problem. 
I realized that my screenshot quality doesn't even seem the same to your default 70% setting.
It's because I don't maximize the google chrome window. I was just using half of my screen for chrome
When I tried maximizing the chrome window and took another screenshot, the result is different.

**windowed mode**
![gamerz 2016-08-19 19-09-40 99](https://cloud.githubusercontent.com/assets/19471603/17809606/f8c55156-6641-11e6-8ff8-2478d96088e7.jpg)

**maximize mode**
![32r](https://cloud.githubusercontent.com/assets/19471603/17809608/febc6d56-6641-11e6-9d12-3419cb45b64b.jpg)

So yeah, once I maximize the chrome screen, the blur on my screenshots seems to gone. I don't know if I'm the only one experiencing this bug or something.

I've seen the 100% setting and it looks very good. Would you still implement it in future updates?
Thanks a lot

**Comment by dragonjet** [comment]
ah glad to see you solve the problem, though it's still a limitation on chrome that we can't do anything about as far as I know.

for the image quality, yes we're still going to add this option :+1:
