### ISSUE TITLE
Formula 33 on Strategy Room

### ISSUE THREAD

**Issue by dragonjet** [KC3Kai/KC3Kai#1479]
on Fleet Manager tab

as requested on community chat

**Comment by sinsinpub** [comment]
already, see branch `dev-fleet-viewer`

**Comment by dragonjet** [comment]
@sinsinpub can we merge that? we can continue other to-do's in another PR / branch

**Comment by sinsinpub** [comment]
@dragonjet yes, we can merge it first

**Comment by dragonjet** [comment]
included in 30.8.0
