### ISSUE TITLE
Disable Taiha Alert on Home Port

### ISSUE THREAD

**Issue by dragonjet** [KC3Kai/KC3Kai#1480]
Settings so that we can enable/disable Taiha alert when not on sortie, because it doesnt matter when in Home Port

**Comment by ethrundr** [comment]
conclusion regarding the taiha alert on Discord:
- alert will turned off for all flagships altogether
- alert will turned off for ships that have equipped damecons
- optional setting to toggle between alert availability: on every screen or only during sorties
- by default, the current availability settings will be implemented

**Comment by sinsinpub** [comment]
@dragonjet not sure is it necessary to disable Taiha alert at home port, because it DOES matter when in Home Port. Only Taiha of flagship is not allowed to sortie in game, other ships with Taiha is able to sortie and ofc possible sunk.

**Comment by nonsensed** [comment]
I'm not trying to be difficult here, but

>alert will turned off for ships that have equipped damecons

I would really like it if this were optional, and I doubt I'm the only one. I grind 1-5a because the only ships I still need to level up are destroyers. They all have damecons on to avoid a mistake. However, I absolutely want the taiha alert to occur when a ship is Taiha. I only have damecons on as a precaution, I'm not actually trying to use them.

Also 100% agree about the homeport thing, which is why above it was requested as an option.

**Comment by sinsinpub** [comment]
@nonsensed ...agree with which? should be a option to disable alert?

**Comment by nonsensed** [comment]
I 100% agree with what you wrote - 
>not sure is it necessary to disable Taiha alert at home port? because it DOES matter when in Home Port.

I actually remember the discussion on discord. Basically, they agreed there should be an optional setting to disable taiha alert at home port.

**Comment by sinsinpub** [comment]
off-topic: there are 'too many' options in settings page for some ppl making them know little about possible variants of feature. but like 'ppl refuse to read long texts', i doubt if will it help to add a tool-tip to every settings to introduce the options what will exactly affect 😂

**Comment by sinsinpub** [comment]
Making both things to be optional is not difficult. Just make sure the default value should be introduced to new player, and claim the option should be toggled on player's own risk.

default will be:
* Annoying Taiha Alert
   * Enabled : false   (not changed)
   * Disable on Home Port : false  (new)
   * Enabled even equip Damecon : false  (new)
