### ISSUE TITLE
[Bug] E2 Boss drop isn't predicting

### ISSUE THREAD

**Issue by Agc0de6** [KC3Kai/KC3Kai#1482]
- Chrome version 52.0.2743.116
- Win10
- 32bit
- KC3 Kai ver. 30.7.0
- webstore version
- As said in title
![2016-08-15](https://cloud.githubusercontent.com/assets/14156630/17667505/a2c190ec-631e-11e6-96e0-f91d069f6818.png)

**Comment by mikenzb** [comment]
One of my friends also reported the issue might be happening on E4 too

**Comment by dragonjet** [comment]
is this when you cleared the map? the boss fight might have multiple rewards, and the data structure becomes an array instead of just one ship get. will check this out when I get to E-2, but since my internet died there's no guarantee when. but if someone can confirm by submitting response JSON when they encounter it, that would be nice

**Comment by Javran** [comment]
hm, I cleared E2 with drop prediction working. so I guess it's not the case.

**Comment by Agc0de6** [comment]
@dragonjet yes, I already cleared that map

**Comment by IamKenshin** [comment]
I also have this problem.  It would predict the boss drop until I cleared the map.  After that, every time I cleared the boss node it would not predict what the drop would be.  I can post a screen the next time I clear it.

**Comment by chronomeister** [comment]
[Same thing](http://i.imgur.com/mkC6ZgH.png). Cleared it days ago.
json dump of battle result: `{"api_result":1,"api_result_msg":"成功","api_data":{"api_ship_id":[-1,696,501,501,-1,-1,-1],"api_win_rank":"S","api_get_exp":260,"api_mvp":1,"api_member_lv":116,"api_member_exp":11635210,"api_get_base_exp":230,"api_get_ship_exp":[-1,828,276,276,276,276,276],"api_get_exp_lvup":[[571292,584500],[2200039,2210000],[1123743,1125000],[1064929,1065000,1077000],[1042589,1046000],[1114704,1125000]],"api_dests":3,"api_destsf":1,"api_lost_flag":[-1,0,0,0,0,0,0],"api_quest_name":"南西海域 エンドウ沖","api_quest_level":7,"api_enemy_info":{"api_level":"","api_rank":"","api_deck_name":"深海東洋艦隊 Z部隊先遣艦隊"},"api_first_clear":0,"api_mapcell_incentive":0,"api_get_flag":[0,1,0],"api_get_ship":{"api_ship_id":21,"api_ship_type":"軽巡洋艦","api_ship_name":"長良","api_ship_getmes":"軽巡、長良です。<br>よろしくお願いします！"},"api_get_eventflag":0,"api_get_exmap_rate":0,"api_get_exmap_useitem_id":0}}`
[Zip file json dump of the entire map](https://s3-ap-northeast-1.amazonaws.com/chronokcdata/E-2bug.zip)

**Comment by sinsinpub** [comment]
i guess what we need is the console message of the devtool (not game tab, some exceptions may occurred there) when the issue appear

**Comment by dragonjet** [comment]
@all thanks for the screenshot, additional info and response data

@sinsinpub something like that is on #1465

the data looks alright, `api_get_ship` is still an object. might have to put this on the api sim to test

**Comment by dragonjet** [comment]
![ss 2016-08-20 at 07 27 15](https://cloud.githubusercontent.com/assets/557312/17830636/1ec92592-670c-11e6-8a82-036c54c06cce.png)

**Comment by Agc0de6** [comment]
@dragonjet ?

**Comment by dragonjet** [comment]
@Agc0de6 I just sortied to E-2 post-clear, this is the error that stops drops from showing up. Already did a fix, now testing it for another run
