### ISSUE TITLE
battle prediction bugged out in E4 I node night battle

### ISSUE THREAD

**Issue by asylvanus** [KC3Kai/KC3Kai#1484]
only not predicting in night battle, no problem if cleared in day battle

![1471323330247](https://cloud.githubusercontent.com/assets/21052242/17689002/803ac5b2-63ae-11e6-9513-4636d903e9a6.jpg)

**Comment by Javran** [comment]
would you mind uploading your replay of this sortie for debugging? (imgur is recommended)

**Comment by asylvanus** [comment]
https://imgur.com/a/NQK86

i hope this is correct one

**Comment by Javran** [comment]
@asylvanus sorry for the late response, I've figured out what's wrong, will be working on a fix.

for those interested in the detail: for the battle data mentioned above, despite day battle has a hp array of length 13 (with the first one always being -1 as a placeholder), the yasen one has a hp array of length 12 (the last enemy ship is not present), it's easy to fix this but I don't know why the data is represented this way: usually the array is always of length 13 with `-1`s to indicate non-existing ships.

**Comment by Javran** [comment]
should be fixed now by b095a92
