### ISSUE TITLE
French translation 

### ISSUE THREAD

**Issue by Syntax7error** [KC3Kai/KC3Kai#1487]
Hello

I would like to report some mistakes and typographic errors in the French translation:

- in the expedition return popup, the adjective is not accorded well in the title ("Expedition fini!" should be "Expedition fini**e** !" but it would be better to write "Expédition terminée !" or "Expédition revenue !")
- in the same popup, the verb "viens" is not correct and should be written "vien**t**".
- in the same popup, the infinitive verb is mistaken with a past participle ("La flotte 3 vient juste d'arrivé de l'Expedition 3" should be "La flotte 3 vient juste d'arriv**er** de l'expédition 3.", but it would be better to write "La flotte 3 vient de revenir de l'expédition 3." )
- the ordinal number abbreviations should be "1re", "2e", etc. not "1ère", "2ème", etc. Ideally, the abbreviation would be in superscript.
- ideally, there is a non-breaking space before double punctuation marks ( ! ?  :  ;) and %
- in French, it is not usual to capitalize words inside a sentence, only the first world (en eventually proper nouns) should have a capital letter (e.g. "La flotte 3 vient de revenir de l'expédition 3." is better than "La flotte 3 vient de revenir de l'**E**xpédition 3."

This page can be consulted for the proper typography in French: [http://revues.refer.org/telechargement/fiche-typographie.pdf](url)

![kc3](https://cloud.githubusercontent.com/assets/21103170/17780849/d495a744-65a7-11e6-8a9b-f186c12b2047.png)

I really appreciate your tool, so if you need any help for its translation in French, feel free to ask me (I have some programming skills).
 
Regards, Olivier.

[EDIT] I also found this:

- "Pas Combinné" should be "Pas combiné" ("Non combiné" would be better).
- "Morale Bon" should be "Moral bon" ("Bon moral" would be better).
- "Enemies" should be "Ennemis" (or "Ennemies" if they are considered as females, but then "Alliés" should be "Alliées").
- "Detection" should be "D**é**tection".
- "Engage" should be "Engagement".
- "De Front" could be changed to "Frontal"

![kc3](https://cloud.githubusercontent.com/assets/21103170/17779832/1597b52e-65a4-11e6-8dda-84cc56522749.png)

- "Morale de la Flotte Rétabli!" should be "Moral de la flotte rétabli !"
- "sélectionné" should be "sélectionnée"

![kc3](https://cloud.githubusercontent.com/assets/21103170/17782677/b3fd9c82-65af-11e6-9388-730850338343.png)

- "Vous avez maintenant 18 de cet objet!" should be "Vous avez maintenant 18 fois cet équipement !".

![kc3](https://cloud.githubusercontent.com/assets/21103170/17789333/c9fd8da4-65cc-11e6-9c04-a89b8f052ac7.png)

- "La fabriquation d'équipement à échoué" should be "La fabri**c**ation d'équipement **a** échoué.".

![kc3](https://cloud.githubusercontent.com/assets/21103170/17789567/be75879c-65cd-11e6-88cb-bf2aaa139132.png)

- "Ceci est votre première!" should be "C'est la première fois que vous obtenez cet équipement !"

![kc3](https://cloud.githubusercontent.com/assets/21103170/17789699/515b1360-65ce-11e6-855f-8647e85fdd01.png)

- "Construction Fini!" should be "Construction finie !" ("Construction terminée !" would be better)
- "Une nouvelle fille-navire Hibiki à été construite" should be "Une nouvelle fille navire Hibiki **a** été construite" ("La fille-navire Hibiki vient d'être construite" would be better).

![kc3](https://cloud.githubusercontent.com/assets/21103170/17790901/8ca8d588-65d3-11e6-9bc2-c9c2e7092202.png)

**Comment by dragonjet** [comment]
tagging @Xwilarg

**Comment by Xwilarg** [comment]
I'll answer in french, I hope it's not a problem.

@Syntax7error 
Bonjour,
Je suis actuellement en charge de la traduction française de KC3Kai.
Merci d'avoir rapporté ces fautes, je corrigerais ca dès que je pourrais (dans une semaine et demi environ).

Désolé encore pour toutes les fautes présentes.

**Comment by Syntax7error** [comment]
Bonjour @Xwilarg

Merci pour ta réponse. Je continuerai d'ajouter les fautes que je vois dans le premier message.
Il y a notamment des petits ennuis avec les quêtes, où l'infinitif, et les secondes personnes du singulier et du pluriel sont mélangées (par ex. "Déployez le Xe squadron. Avoir A, B et C dans ta flotte."), le mieux serait de tout mettre à l'infinitif. Il y a également certaines quêtes qui ne sont pas traduites.
Si j'avais une liste des textes des quêtes avec leur traduction proposée, je pourrais faire les corrections et les traductions moi-même.
En ce moment, j'ai du temps libre.

I also answer in English for others to understand clearly:

Thank you for your answer. I will continue to add the mistakes I see in the first post.
There is some small trouble with quests, where the infinitive, the second person of singular and plural are mixed (eg. "Deploy the Xth squadron. Have A, B and C in your fleet."), The would be best to put everything in the infinitive. There are also some quests that are not translated.
If I had a list of texts of quests with their proposed translation, I could make the corrections and translations myself.
Right now, I have some free time to spare.

**Comment by Xwilarg** [comment]
Si vous voulez, vous pouvez rejoindre l'equipe de traduction en suivant ces etapes: https://github.com/KC3Kai/kc3-translations
Sinon je peux vous envoyer le fichier contenant toutes les quètes.

**Comment by Syntax7error** [comment]
@Xwilarg; merci, je vais regarder ça, ça sera sans doute plus simple.
On peut se tutoyer si cela ne te dérange pas.

**Comment by Xwilarg** [comment]
@Syntax7error Ca ne me derange pas du tout.
Si tu as besoin d'aide pour le fonctionnement de Git, n'hesite pas a me contacter.

**Comment by Syntax7error** [comment]
@Xwilarg; je ne vais pas faire le travail sur GitHub, ça me semble un peu compliqué pour moi pour le moment. J'ai téléchargé le dossier ZIP sur mon ordi.
Si j'ai bien compris, il faut que je corrige les erreurs des fichiers JSON du dossier français de « data » de « kc3-translations-master » (e.g. battle.json, developers.json, equiptype.json, etc.) ?

**Comment by Xwilarg** [comment]
Oui, apres tu peut faire un "Pull request" pour demander a valider tes modifications, une fois ca fait tu pourras demander a aider officielement l'equipe de traduction (si tu le souhaite).

**Comment by Syntax7error** [comment]
@Xwilarg; d'accord, merci pour tes conseils.

**Comment by ethrundr** [comment]
@Syntax7error don't know whether this has been addressed before or not by @Xwilarg (I don't understand French lol): 
Instead of updating the first post, just make a new comment for new updates on the translation errors you've found. That way everyone involved in the issue will receive the notification that you've added/replied with something.

**Comment by Syntax7error** [comment]
@ethrundr: I'll try to correct the translations myself in fact: I just downloaded the files and I am currently trying to learn to use GitHub Desktop.

**Comment by ethrundr** [comment]
@Syntax7error sure, it's great to have more contributors to the team.
Just ping me on Discord or reply here if you have anything you'd like to ask about GitHub.

**Comment by Syntax7error** [comment]
I see a problem in the arsenal quests: the quest 601 to 604 are misplaced in the English version of the quests.json file (they are put between 609 and 610, togheter with the 619 that is also not at the right place).
In the French version, it makes an error in the quests codes (eg. F1 is given to 605).

I'll correct the errors in the French version, but the order should be fixed in the English version (the codes seem to be good).

**Comment by dragonjet** [comment]
thanks for the notice @Syntax7error 

do you need write access to the TL repo or have you forked it?

**Comment by sinsinpub** [comment]
:smiley:  there's no 'correct answer' for the order of json elements. Any order is okay. The order is just arranaged by maintainer based on some kinds of reasons for easier future maintanence, eg: type of quests (as the codes), or group by the time period, etc.

**Comment by Syntax7error** [comment]
@dragonjet: actually, I do not understand how to use GitHub Desktop... I do not have the courage to learn this today, so I make the changes with notepad++ in the raw JSON files (like this I can use Find and Replace, possibly with regexes).

@sinsinpub: I know that the order of the code is not important in itself, but here it led to mistakes in the French version of the file, so I think it is better to make a correct layout understandable easily by everyone.
If there is a good reason to use a certain order, it should be put in comments (especially if the code is meant to be used by many different persons).

**Comment by Syntax7error** [comment]
@dragonjet: I notice that some things could be added to the newest quests (I prefer to say it here rather than opening a new thread):

Some old quests are like this:

    "613": {
        "code": "F12",
        "name": "Weekly Dismantlement",
        "desc": "Scrap equipment 24 times",
        "tracking": [ [0,24] ]
    },

But the new ones are missing the tracking line:

    "624": {
        "code": "F21",
        "name": "Preparation of the Prototype Equipment",
        "desc": "Scrap equipment 7 times"
    },

It concerns the quests 624, 625, 634, 635, (636), 638 and 640 (I do not know if this can be added though).

**Comment by dragonjet** [comment]
I see, though those are probably one-time quests, that would probably be good to have

A rework on quest tracking where the "`tracking`" field is separated from the languages is probably started here: https://github.com/KC3Kai/KC3Kai/pull/1259 so that all languages dont need to have that extra data, which is actually common to all

**Comment by Syntax7error** [comment]
@dragonjet: separating the translations from the other features is certainly the best thing to do (but I cannot help on this, I know nothing about how this tool is programmed).

I have noticed that the numbers used in the JSON quests file do not always follow the quests number order

eg.:

    "629": {
        "code": "F26",
    },
    "630": {
        "code": "F28",
    },
    "631": {
        "code": "F27",
    },

Could you tell me the reason for that?

**Comment by dragonjet** [comment]
this is because the wikis are on the opposite side of things - they see the quests, they name it, but they don't know the hidden IDs of the quests, and this their way of naming quests isnt always the same as they really are in the backend

**Comment by Syntax7error** [comment]
@dragonjet: thank you, I understand better now.

**Comment by Syntax7error** [comment]
@dragonjet: in the French version, are the lines containing the quest code and the unlocked quests necessary? Because on the oldest quests they are missing but are present on some of the newest ones.

Should I remove them, add them where they are missing or just leave it as it is ?

I also added some new quests I took from the english version that have these parameters.

**Comment by Syntax7error** [comment]
@dragonjet: I finished correcting the French JSON files and I also translated the newer quests.
In addition, I improved the layout of some English files that I translated or used: I have aligned the values on one line using /TAB for an easier editing. You could use these files for the next version of KC3Kai.

I just need to know if the "code", "unlock", and "tracking" lines need to be added to the French quests file , so I can upload my work here as I am currently not capable of using GitHub to make a fork myself.

Waiting for your answer.

**Comment by Xwilarg** [comment]
@Syntax7error (Pourrais tu me donner un moyen de te contacter ? Vu qu'on est tout 2 dans l'equipe fr, je pense que dialoguer entre nous pourrais aider.)

**Comment by Syntax7error** [comment]
@Xwilarg email envoyé

**Comment by dragonjet** [comment]
@Syntax7error I'll give you write access to the translation repo so you can do it all in github without needing git commands or software.

this will be the process:
* Go to the root of the translation repository (https://github.com/KC3Kai/kc3-translations)
* In the "Branch: master" dropdown, type a new name of a branch (e.g. "fr-updates") then click on create branch
* Make sure the drop-down button changes to the name you just specified (not "Branch: master" / should look like "Branch: fr-updates"), which means you are currently viewing your own branch
* Feel free to navigate the source code in GitHub (e.g. data > fr >) and click the file you want to edit
* On the top-right of the code viewer, click on "Edit this file" with the pencil icon, edit codes, then save
* Click on code in the main navigation of GitHub, then look at the Branch button drop-down, should still show your branch name (e.g. "Branch: fr-updates", if not, select it from drop-down).
* Beside the Branch button, theres another button "New pull request". Write description and submit. Tag involved users if needed

**Comment by dragonjet** [comment]
sent you an invite for kc3kai organization, after accept, you'll have write access to TL repo and you can do the above steps

**Comment by dragonjet** [comment]
by the way @KC3Kai/translators  in case you want to translate more terminologies, this is a tool to compare your file with EN. Then look for `*****`, those are the ones not yet translated

http://kc3kai.github.io/kc3-translations/updater/

type the language code in the textbox, e.g. `fr`

**Comment by sinsinpub** [comment]
by the way @KC3Kai/translators there is another tool always available inside KC3Kai Strategy Room (just enable it at Settings):
![image 2](https://cloud.githubusercontent.com/assets/160240/17855663/73a98e48-68ac-11e6-846a-9da1088f558b.png)

**Comment by Syntax7error** [comment]
@dragonjet: I made the changes, but it seems that there is a problem in the terms.json file: in the lines 232, 243, 247 and 250, I tried to add links because the text was going on two lines in the options page, but I probably made a mistake when I copied the code: the "target=\" appear in red.

Also, I still do not know if the "code", "unlock" and "tracking" lines need to be added in the French version.

**Comment by ethrundr** [comment]
@sinsinpub tbh, I just know we had that Dev-only menu on the SR XD

**Comment by dragonjet** [comment]
oh yea I forgot about that, yea that's an easier way to compare TL

**Comment by Syntax7error** [comment]
@dragonjet: I think I have uploaded all the changes I wanted to make (it is certainly not perfect, but still much better than the current version)
There is still that thing with the "code", "unlock" and "tracking" lines that may be added (I am waiting your answer) and the problem (?) with the red "target=\" in the lines 232, 243, 247 and 250 of the French terms.json file that may need to be fixed (I do not really know what is the problem so I cannot solve it).

In fact, what does "TL" stands for ? (I am not very good with abbreviations...).

**Comment by dragonjet** [comment]
TL is translation. code, unlock and tracking dont need to be there. as far as I can remember if it's not in the language, it will extend from english by default.

usually, this is where you can see the problem:
https://travis-ci.org/KC3Kai/kc3-translations/branches

then click on the left most box of your branch, earlier to latest is right to left.
it will show a log, and usually at the bottom you can see the error

on your last one as of time of writing:
https://travis-ci.org/KC3Kai/kc3-translations/builds/154172961

this shows you where the problem is, and points at it
```
Warning: Parse error on line 1312:
... de navire."    },}
---------------------^
Expecting 'STRING', got '}' Use --force to continue.
```
usually, you don't use comma if it's the last item in the list

**Comment by Syntax7error** [comment]
@dragonjet: I think that I corrected all the mistakes. I also removed all the "code", "unlock" and "tracking" lines as they are not useful in the French versio. It makes things clearer.

I have a question: how can I add a comment to the code?
Also, when do you think that these changes will be put in the new version (v. 30.8.2 maybe)?

**Comment by dragonjet** [comment]
there are no set rules as to when we do releases. usually when we just see enough content has been pushed enough, or not yet when we need something done before a specific event or maintenance.

right now we I haven't wrote a release PR yet, but might make one soon. I just want to see some of the urgent bugs fixed before a 30.8.2

**Comment by Syntax7error** [comment]
Okay, thank you.
I might have some changes to make and I also asked to Xwilarg to read over the files I changed.

Can you please tell me how to comment the code without affecting it? (maybe it is by writing the comments after "//", but I do not know what language is used for KC3Kai).

**Comment by dragonjet** [comment]
for the translations files though, is using JSON - and you cannot do comments on those files, unfortunately :disappointed:

**Comment by dragonjet** [comment]
you can, however, comment per-line in github once you make a pull request

**Comment by Syntax7error** [comment]
In fact, it is for the quests "wiki" numbers, so I may use the "code" line, even if it is already taken from the English file.

Actually, wouldn't it be possible to add _fake_ parameters to add comments, like

`"comment": "this is a comment"`

??

**Comment by dragonjet** [comment]
it is possible, but do so lightly, these JSON files are loaded by all players during runtime and it _may_, depending on the amount of text added in, would eat more ram (not like anything can beat `quotes.json` in terms of size :stuck_out_tongue: ).

**Comment by Syntax7error** [comment]
@dragonjet: hello

My translation is done (even if some files can still be modified a bit), so do I need to make a "Pull requests" or something?
I do not know if the changes made will be in the next update (I do not even know when it will be available in fact... :sweat:).

Can you take care of this (or explain me what to do)?
I could also translate quickly the last quests if they are available in English already.

**Comment by dragonjet** [comment]
on the translations repository, you may [create a pull request](https://github.com/KC3Kai/kc3-translations/compare) so that your changes will be merged into the main codebase and thus can be included for next release.

in the pull request creation page, there are two buttons, "base" and "compare". click on "compare" and on the drop-down, select your branch `fr-updates`. It will then become:
`base:master` : `compare:fr-updates`

proceed to create the pull request and add in description if you like. tag your co-translator in the description so we can peer-review it. in the mean time, our automated build job, travis will also check your files for any errors.

**Comment by Syntax7error** [comment]
@dragonjet: thank you for the answer.

Do I still need to make a pull request, since I think that you already made one?

>  dragonjet  merged 20 commits into master from fr-updates 25 minutes ago.

**Comment by Syntax7error** [comment]
I just translated the summer 2016 quests that were missing in the French quests.json file.
I checked it with Travis CI and it is good, but I think it is too late to appear in version 30.9.0...

I also created a branch by mistake: [Syntax7error-patch-1](https://github.com/KC3Kai/kc3-translations/commit/618c8f3a9fa20a3d4526a4466fa8a3a12b429f67), but I do  not know how to erase it. :sweat:

**Comment by dragonjet** [comment]
to delete a branch, go to "Code" then on the menu above the colored bars, click on branches. If you can't see your branch there, select All branches. there is an icon to delete branches from there

**Comment by dragonjet** [comment]
If all items have been pushed so far, you may close this thread. there is no need to keep one open as you can make branches and create pull requests anytime for FR updates

**Comment by Syntax7error** [comment]
Thank you for the advices.

I close this thread as suggested, if new changes need to be made in the French files, please make a new thread.
