### ISSUE TITLE
LBAS Fighter Power is "None" even with legit planes

### ISSUE THREAD

**Issue by dragonjet** [KC3Kai/KC3Kai#1493]
Planes in an LBAS base that will cause this
- Type 3 Fighter Hien (244th Air Combat Group)
- Ginga
- Type 1 Land-based Attack Aircraft Model 34
- Type 1 Land-based Attack Aircraft (Nonaka Squadron)

**Comment by HKGPsy** [comment]
Just to report a bit more details. 
Interceptors also caused similar problems. When the team only include interceptors, the fighter power will display as "None". If interceptor is mixed with carrier fighter plane, the interceptor will be ignored and only carrier fighter will be counted in the LBAS fighter power.

This bug still exist in the latest version of 30.12.5

**Comment by dragonjet** [comment]
thanks for confirming this
