### ISSUE TITLE
KC3 issue

### ISSUE THREAD

**Issue by PsiDubs** [KC3Kai/KC3Kai#1496]
Chrome version: 52.0.2743.116 (Official Build) m (32-bit)
Windows 10 64 bit
KC3改 30.8.0 (from webstore)

Issue started today when my quests stopped updating. After closing and reopening KC3, hitting F12 and selecting the KanColle tab no information would appear. Additionally, the game doesn't load after selecting the KC tab as it normally would (hitting "start the game anyway" still works for just playing the game). I've tried going through the installation process again but that doesn't seem to help the problem. Strategy room seems to still be working and gets information from the game, the F12 panel is the only issue.

![Issue](http://i.imgur.com/ySVk6GN.png)
*Stuck on this. Nothing happens.*

For the sake of avoiding redundancy, I have read [this](https://github.com/KC3Kai/KC3Kai/issues/144) thread and the apparent solution doesn't work in my case :/

**Comment by ethrundr** [comment]
After you manually start the game using the "Start the game anyway", did the panel load normally or stays as in your screenshot?

Since whether if its just unable to directly load the game with unable to be loaded at all even after the game started is two different bugs, and need different treatment to it.

**Comment by PsiDubs** [comment]
@ethrundr No, the panel doesn't load at all. I can get into the game but the panel will remain blank.

**Comment by dragonjet** [comment]
before starting the game, do you see the message "_Waiting for game actions..._"?

**Comment by PsiDubs** [comment]
@dragonjet Nope

**Comment by Valkyrie170** [comment]
Just thought I'd chime in and say I've also been experiencing this problem since yesterday. The solution that he linked in OP also doesn't work. Tried starting up on two separate computers (Windows and Mac) and still no success.

**Comment by dragonjet** [comment]
tbh, that's very odd - the first page you should see is the "_Waiting for game actions_" page. Also, that interface, with black boxes, I might not have seen before (coz our natsuiro and plain themes, do not have boxes per ship).

Though I just realized, I probably know how to fix it. Will try something in a hotfix branch

**Comment by PsiDubs** [comment]
@dragonjet Those black boxes and with the picture are part of a custom image I made specifically for the KC3 panel background image (the interface opacity of the panel is set to 0). And yes, under normal circumstances I would see "waiting for game actions" but that doesn't seem to happen.

**Comment by dragonjet** [comment]
try updating to 30.8.1
