### ISSUE TITLE
Panel Icons Reset Upon Navigating to LBAS Information

### ISSUE THREAD

**Issue by ethrundr** [KC3Kai/KC3Kai#1497]
Continuing report from my FB group:
Seems switching into the LBAS information resets all warning status on the fleet icon on the panel, including supply and damage warning.

Chrome v52, KC3kai v30.8

Video Screenshot attached:
http://puu.sh/qIB0S/e5c2062598.mp4

**Comment by sinsinpub** [comment]
not sure exactly, this will be fixed by Release 30.9.0 (#1511)
