### ISSUE TITLE
Minor ship name error

### ISSUE THREAD

**Issue by jimmy5517** [KC3Kai/KC3Kai#1499]
I am farming 1-5a and hoovered my mouse over the enemy submarine icon and it read "潜水ヲ級", when the correct title should be "潜水カ級"

I checked the library and found this
![image](https://cloud.githubusercontent.com/assets/8700123/17835779/50206ec4-6730-11e6-89fd-a1ef2bf3fe3c.png)
The correct name is listed, but for some reason the display name is incorrect.
This got me confused for a moment because this submarine class doesn't exist, I checked the Japanese wiki to make sure it isn't new. I think this deserves a quick fix.

I am using the Chinese language interface.

**Comment by Javran** [comment]
thanks for spotting that out, that was my fault. should now be fixed by https://github.com/KC3Kai/kc3-translations/commit/6debb9ea6449862bc3ed69b2abd1725b1f77aafc
