### ISSUE TITLE
Colored enemy borders for elite/flagship

### ISSUE THREAD

**Issue by dragonjet** [KC3Kai/KC3Kai#1500]
On battle details on F12 panel, make the circle border colored, red for elite, yellow for flagship

**Comment by ethrundr** [comment]
additional input: blue for kai flagship (Wo, Ru, Ri)

**Comment by dragonjet** [comment]
not sure if we can detect those though, as far as I've seen, `api_yomi` only has values elite and flagship, though I'd have to check again for those specific abyssals. which ID are they?

**Comment by sinsinpub** [comment]
:open_mouth: i thought icon images themselves will be updated... it's going to use css border?

yomi of Kai flashship are all `flashship`, their names suffix are all `改` (565,566,567,616-618)

**Comment by dragonjet** [comment]
yes I dumbly made the background for abyssal icons as red, which makes it confusing to differentiate normal vs elite versions of enemies. I guess we can put it back to old gray backgrounds

**Comment by ethrundr** [comment]
isn't it possible to use lighter shade of red, just to make sure those elites can be differentiated with the normal ones?

**Comment by dragonjet** [comment]
there's no solid reason to keep them red actually. we can just put it back to being gray backgrounds

**Comment by Javran** [comment]
implemented, closing.
