### ISSUE TITLE
Name in kanji in Ship Library and bug with the "image-switching-disaster" notice

### ISSUE THREAD

**Issue by Syntax7error** [KC3Kai/KC3Kai#1503]
Hello

I am using the latest version of KC3 (30.8.1) on Comodo Dragon browser (a Chromium clone), in Windows 7.

I see three things that can be improved in the _Ship Library_ ot the _Strategy Room_:
- the name of the ship-girl in Japanese is written in hiragana, that is useless because the in-game names are mostly written in kanji. When one is looking for a particular ship in his fleet, it is impossible to do it using names in hiragana.
- there is a problem with the "image-switching-disaster" notice: if one clicks on it, it disapears and it is not possible to copy the link to pase it in the Flash player options, or even to reach Adobe's Global Security Settings panel page. The only other way is to open the _Help topics_ menu, but it is not evident for everyone that the solution to the "image-switching-disaster" is in this menu.
- some of the names of the statistics of the ship are not in English (eg. souk for armour, soku for speed, etc.) It seems to be Malaysian or Tagalog maybe.

![ship library](https://cloud.githubusercontent.com/assets/21103170/17852666/5897d6fe-68a3-11e6-8f33-cd0b3523c88a.png)

Thanks.

**Comment by dragonjet** [comment]
by the way, @Syntax7error you can comment here up to 5 links we can add under your name for the about page

**Comment by Syntax7error** [comment]
@dragonjet : "comment here up to 5 links we can add under your name for the about page"

I do not understand, which "about page"? The one of KC3Kai? And which kind of links?

**Comment by dragonjet** [comment]
the ones like this

![ss 2016-08-22 at 08 56 44](https://cloud.githubusercontent.com/assets/557312/17854045/f36a324c-68aa-11e6-8544-93b40777f63f.jpg)

**Comment by Syntax7error** [comment]
Understood.

You can put [http://kancolle.wikia.com/wiki/User:Syntax_Terror](http://kancolle.wikia.com/wiki/User:Syntax_Terror) and [https://github.com/Syntax7error](url) then.

Can you also answer my question in the [French translation thread](https://github.com/KC3Kai/KC3Kai/issues/1487) also, so I can edit the JSON files or upload them here.

**Comment by dragonjet** [comment]
added :+1:

**Comment by ethrundr** [comment]
locking the thread since it's no longer used
