### ISSUE TITLE
Fleet Focusing on Combined Fleet

### ISSUE THREAD

**Issue by ethrundr** [KC3Kai/KC3Kai#1510]
As mentioned by @nonsensed in Discord:

"When making changes to the fleet in combined fleet, the kc3 panel switches to the single fleet where a change occured. While in various cases, this could be preferred, I kept accidentally sortieing my combined fleet with the panel only focusing on one fleet. It's potentially dangerous in terms of sinking ships with no taiha alert on.

ex. combined fleet->change to a new ship in fleet 2->focus is now switched to fleet 2 even though combined fleet view is preferred

When in a combined fleet, if the escort flagship is chuuha, it shows an X flagship in the hp status line of the kc3 panel. During a sortie, this is a little annoying. If a user has the annoying taiha alert turned off, this notification is too similar to the X taiha hp indication."

**Comment by sinsinpub** [comment]
is it ok if adding an option to Settings to disable auto switching? (mentioned at #1452)

**Comment by nonsensed** [comment]
Hmm... auto switching is usually ok. But when a combined fleet is active, this is when things change...

A different possibility: when going to the sortie screen, if a combined fleet is active, the panel switches to combined fleet. This is like how if you are on the expedition screen, the panel switches to fleet 2, 3, or 4.

The most important thing for me is... I don't want to see people talk about how they sank their ships when using kc3.

(someone sank a Zui or Shoukaku Kai Ni A this event, but not for this reason)

**Comment by dragonjet** [comment]
I noticed this myself when playing, agreed :+1: 

@sinsinpub yes we can make it configurable

**Comment by sinsinpub** [comment]
> When in a combined fleet, if the escort flagship is chuuha, it shows an X flagship

about this, it just indicates combined fleet is not able to sortie (for the next time) when escort flagship is chuuha according this thread #1043. I think we could improve the TL to clarify its meaning and use another icon (eg a caution) to 'downgrade' its severity?

**Comment by nonsensed** [comment]
Yes, please!

**Comment by sinsinpub** [comment]
![image 3](https://cloud.githubusercontent.com/assets/160240/17954045/ca56ac58-6aaa-11e6-90bb-1c49a8814b80.png)
there is no enough space to display `Flagship Chuuha` in English... so I reuse the 'Chuuha Icon' and just show `Flagship` instead?

**Comment by nonsensed** [comment]
I'm fine with that icon. [Here are some alternatives.](http://www.freeiconspng.com/icons/warning-icon-png)

For the text, I agree, it's difficult to say what the warning is for in a small number of characters. The best I can come up with quickly is

"FS Can't Sortie"

In the layout you use, this would still get cut off a little... if all else fails, there is "FS Low!" or "Flagshp Low" or "Flgshp Low"

If we only say "Flagship Low" or "Flagship Chuuha", we tell the user what the problem is, but we don't tell the user why it is a problem. A new player might get confused and choose retreat in a sortie even though they don't need to.

**Comment by sinsinpub** [comment]
yep, I got it too.

Add a different tooltip to it and use different icons for Chuuha and Taiha flagship:
![image 4](https://cloud.githubusercontent.com/assets/160240/17955767/22e63e9a-6ab7-11e6-8799-7f75a0b54eb6.png)
For English:
![image 5](https://cloud.githubusercontent.com/assets/160240/17955775/2efd6fd2-6ab7-11e6-97a5-04827fae8a23.png)

**Comment by nonsensed** [comment]
Alright, good enough for me. Thank you for your time!

(poor Okinami...)
