### ISSUE TITLE
Game won't open when using the Kancolle Frame

### ISSUE THREAD

**Issue by Soulshaper** [KC3Kai/KC3Kai#1512]
I'm new using KC3 Kai. In a fresh install of both Chrome (x64) and KC3 Kai, I'm getting this screen while following the instructions, both on Play on DMM Site, and on Play via DMM Frame:

![kc3kai](https://cloud.githubusercontent.com/assets/21297180/18036796/134b3dd2-6d4b-11e6-979c-be125e70010e.png)

If I put Start the game anyway, it works fine.

The console output is:

KC3改 Messengers loaded
RemodelDb.js:1 RemodelDb: no update required
RemodelDb.js:1 RemodelDb: database unavailable, need to re-initialize with master data
global.js:3 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
Translation.js:1 Translation: failed to load RemodelDb, please make sure it's been initialized properly
objects.js:4KC3改 Messengers loaded
jquery.min.js:1'//@ sourceURL' and '//@ sourceMappingURL' are deprecated, please use '//# sourceURL=' and '//# sourceMappingURL=' instead.
objects.js:4 KC3改 Messengers loaded

**Comment by dragonjet** [comment]
what does the message say? sadly, I can't read Japanese. I would've machine translated it but it's in a pic :sweat_smile: 

but for the error messages, all seem good. nothing out of the ordinary

**Comment by Soulshaper** [comment]
I can't read Japanese, either.

Original message:

このゲームは PC 専用となっております。 推奨環境をご確認の上、ご利用ください。

Machine Translation:

This game has become a PC-only. On the recommended environment of the check, please use.

**Comment by dragonjet** [comment]
ah I see. thanks for the info, but unfortunately, we cannot do anything about having the device mode enabled. it's a chrome thing :sweat_smile: at least we now know how to help future players who encounter this :+1:
