### ISSUE TITLE
Name of enemy ships in Enemy Encounters

### ISSUE THREAD

**Issue by Syntax7error** [KC3Kai/KC3Kai#1514]
Hello

I think it would be better to have the full name of the enemy ships in the _Enemy Encounters_ page (the display of the name when mouse hovers the ship image would be perfect).

Also, the text displayed when the mouse hovers the enemy formation would be more useful if it was in English (what does it means in fact ?).

![2016-08-31_10-53-40](https://cloud.githubusercontent.com/assets/21103170/18113286/6ab682fa-6f69-11e6-9a0d-40bd2d7de3f7.png)

**Comment by sinsinpub** [comment]
ship name is added by commit be3888e

and the tool-tip on formation is the 'node name' x 'encounter times (of your own)'. node name is in Japanese only extracted from API data. I wonder if someone would like to translate it?
