### ISSUE TITLE
Map completion bar colour and rate

### ISSUE THREAD

**Issue by Syntax7error** [KC3Kai/KC3Kai#1517]
Hello

I think that the completion bar coulour should be changed from green to red:
In-game, the bar is red (it represents the enemy and thus, this colour has a negative connotation), but in KC3Kai, it is green (with a positive connotation).

Also, the completion rate should be inversed:
When the map is not completed at all, the rate is 100% (eg. 4/4), but it should be 0% (eg. 0/4).

![image](https://cloud.githubusercontent.com/assets/21103170/18149216/e7af485e-7019-11e6-9035-af3194bcdd67.png)

**Comment by dragonjet** [comment]
I see what you mean by the color, but red is also used when you damaged the boss. tbh I'm fine with the colors as it is, though we may need more input from other players. I don't have the best eye on this :sweat_smile: 

In terms of the gauge, I still think counting down is the way to go. 4 is the "gauge" not a quest counter. If it was a quest counter, I'd agree with having 0, 1, 2, 3, 4. but when dealing with a bar than goes down, count must also go down from 4, 3, 2, 1, 0

**Comment by LostLogia4** [comment]
Problem is the red didn't contrast well with dark blue, which is the current theme of the Admiral panel atm.
