### ISSUE TITLE
Post Summer Event update subtitle issues

### ISSUE THREAD

**Issue by jamest35** [KC3Kai/KC3Kai#1518]
Not sure if this has been noticed, but I noticed a minor issue with the subtitles since the update that concluded the summer event passed. I noticed that the subtitles still display lines from their summer conversations despite the characters speaking their usual lines sometimes.

**Comment by jamest35** [comment]
Not sure if this has been noticed, but I noticed a minor issue with the subtitles since the update that concluded the summer event passed. I noticed that the subtitles still display lines from their summer conversations despite the characters speaking their usual lines sometimes.

**Comment by nonsensed** [comment]
Yeah, sorry about that. When a new patch rolls around, it takes a bit before we're switched to the new seasonal lines and quests translations and such.

@dragonjet btw the seasonal lines are in a releasable form right now. The only part not done is new lines. I read about the ph internet situation, though, I hope it stabilizes soon and I hope you're not too stressed out!

**Comment by jamest35** [comment]
Oh no problem, just thought i bring it up if the team wasn't aware.

**Comment by dragonjet** [comment]
might be able to take care of the release Friday evening JST

**Comment by DarkZX00** [comment]
Also want to add something since the topic focuses on subs....

Just found out Isuzu Kai Ni's Modernization lines are reversed....

This one: Heheh, that'll do. Now I'm more ready to fight!
and this one: That modernization... saved me. Now I can work harder!

Thanks and keep up the good work!

**Comment by nonsensed** [comment]
Thanks! Tagging #1311 That's a more general issue you can use if you encounter more of those line swaps.

Thanks for the heads up, @dragonjet , gonna see how much progress I can make with new lines then.

**Comment by dragonjet** [comment]
30.9.0 released earlier today, we can close this now, and just create new one or reopen if there are other requests
