### ISSUE TITLE
Admiral Dashboard Graphical Bug

### ISSUE THREAD

**Issue by IamKenshin** [KC3Kai/KC3Kai#1522]
The Admiral Dashboard's GUI seems to be bugged.  All the icons in the Battle Tab are offset, and the XP bars for the shipgirls seem to be shifted up.  Also, when a quest is completed, the list updates and the list bugs out(graphically, functionality is fine).  My environment and a screen of the issue is listed below.

- Chrome Version 53.0.2785.89 m
- Windows 10 Home 64bit
- KC3 Version 30.9.0
- Webstore build 
![admiral dashboard graphical bug](https://cloud.githubusercontent.com/assets/7230929/18227620/62ab0316-7265-11e6-8bc5-07c89a170a10.jpg)

- It is like this every time i open up the Admiral Dashboard.

**Comment by dragonjet** [comment]
seems some icons are also missing. im guessing the extension has become corrupt. can you check the console tab for any errors';

**Comment by IamKenshin** [comment]
Here are the errors.

![errors](https://cloud.githubusercontent.com/assets/7230929/18228242/f18483f4-727f-11e6-9ccb-b106ca333774.jpg)

**Comment by IamKenshin** [comment]
I tried the development build and it worked fine.  I then reinstalled the webstore version and it works fine too.  Maybe the extension got corrupted when Chrome updated earlier.

**Comment by dragonjet** [comment]
oh reinstalling have cleared your history though, did you backup?

**Comment by IamKenshin** [comment]
I didn't back it up unfortunately.  It's a little frustrating but nothing I can do at this point.  Thanks for the help!

**Comment by dragonjet** [comment]
closing issue for now since it was fixed. should re-open if problem persists.
