### ISSUE TITLE
Weekly quest with wrong translation ?

### ISSUE THREAD

**Issue by Tamachan12** [KC3Kai/KC3Kai#1524]
![tama 2016-09-05 08-40-23 13](https://cloud.githubusercontent.com/assets/14944570/18234550/b5563eb6-7344-11e6-8d0f-efc35ab732bd.jpg)

Weekly sortie is wrong on number of times ? isnt it just 6 sorties instead of 7 ?

**Comment by nonsensed** [comment]
It's including D9, the prerequisite quest which asks you to do expedition 37 or 38 once. You only need to do that quest until the counter says 6/6.

I agree, that wording isn't the best. I'm going to change the wording to "six more times" for the next kc3 update.

**Comment by nonsensed** [comment]
This was adjusted in 30.9.1
