### ISSUE TITLE
Little display problem in Ship List for Chiyoda Kou Kai

### ISSUE THREAD

**Issue by Syntax7error** [KC3Kai/KC3Kai#1529]
Hello

I noticed that in the Ship List page of the Strategy Room, the name of Chiyoda Kou Kai is not displayed correctly: "Kai" is missing.

![chiyoda kou kai](https://cloud.githubusercontent.com/assets/21103170/18343142/19f8cd02-75ed-11e6-9e76-33534b93c986.png)
_(the excerpt of the side panel is here to show that it is really Chiyoda Kou Kai in fact)_

I didn't see that problem elsewhere or for another ship.

**Comment by Sinnermighty** [comment]
This issue happens with a few ships that have long remodel names. Off the top of my head, Hatsushimo Kai Ni and Shoukaku Kai Ni A are two others.
