### ISSUE TITLE
Improvement for Expedition Scorer

### ISSUE THREAD

**Issue by Syntax7error** [KC3Kai/KC3Kai#1530]
Hello

I have a little improvement to propose (I use this to calculate the best expeditions to do):

In the Expedition Scorer, there is already a nice function that allows to get the best expeditions by giving values to the different ressources.
It would be a good thing to add the same kind of function that would use the current ressource ammounts to get the best expeditions to go back to an even level of ressources (ie. 1/1/1/1).
This can be done by calculating the reciprocal of the amount of each ressource (or 100000 times this value for practical reasons).
For exemple, if I have 15000 fuel, 10000 ammo, 8000 steel and 5000 bauxite, the values would be 
- fuel = 100,000/15,000 = 6.66
- ammo = 100,000/10,000 = 10
- steel = 100,000/8,000 = 12.5
- bauxite = 100,000/5000 = 20

This could be calculated automatically and this function could be enabled with a check box near the Resource Priority input boxes.

**Comment by Javran** [comment]
sorry for my late response, I do have plan working on some improvements regarding expedition scorer for a while, probably will add this to my todo list as well.
but keep in mind though that I'm busy working on other things so don't expect them to come very soon.
assigning myself on this just for keeping track.
