### ISSUE TITLE
Map health and strategy room map health are not synced

### ISSUE THREAD

**Issue by NicolaosGreene** [KC3Kai/KC3Kai#1537]
### Versions:
Google Chrome:	52.0.2743.116 (Official Build) (64-bit)
Revision:	9115ecad1cae66fd5fe52bd9120af643384fd6f3-refs/branch-heads/2743@{#728}
OS:	Mac OS X 10.11.6
JavaScript: V8 5.2.361.49
Flash: 23.0.0.166
KC3Kai: 30.9.2 (Dev)

### Steps to reproduce:
Go to strategy room and check any map that has a boss gauge that you have damage and the strategy room currently will display that it has full health regardless of what its gauge is at.

### Actual behavior:
The gauge in the strategy room does not update with the maps and always shows them all as being undamaged.

### Expected behavior:
The strategy room should display the maps gauge health according to the damage it actually has.

**Comment by dragonjet** [comment]
check if going to the sortie page (where you can see the map list) but not necessarily starting a sortie, and see if that syncs the strategy room

**Comment by nonsensed** [comment]
It's happening to a lot of people after today's maintenance, going by what I saw on discord chat spam.

I cleared a 3-5 and it incremented the kill count -1. Later I checked again and my kc3 had reverted it back to 4/4 kills remaining. Kc3 is actively putting it back to full hp on all maps with an HP bar when it does its sync.
