### ISSUE TITLE
Sortie and Battle predict problem

### ISSUE THREAD

**Issue by Archduke88** [KC3Kai/KC3Kai#1539]
Please make sure that you have these details on hand when submitting your issue/bug report as this will greatly speed up the issue triage process -- thank you!

- Chrome version: 53.0.2785.143 m (64-bit)
- Your OS version: Windows 10 Version 1607(X64)
- KC3 Kai version - via chrome:// 30.9.2/
- webstore version(https://chrome.google.com/webstore/detail/kancolle-command-center-%E6%94%B9/hkgmldnainaglpjngpajnnjfhpdjkohh?hl=ko)

I install win 10 and chrome, and load my data and uninstall and install KC3

at practice battle, battle predict has no problem, but

![01](https://cloud.githubusercontent.com/assets/22642483/19122830/3dbc9608-8b67-11e6-8892-7294002cb7a4.png)

battle predict and sortie cannot work at the all map(ex 1-1, 1-5)

![02](https://cloud.githubusercontent.com/assets/22642483/19123052/29a968de-8b68-11e6-8a54-75321be2ab0e.png)

and sortie history also cannot see any statics

I guess these problem because of map file like this
(https://github.com/KC3Kai/KC3Kai/issues/826, https://github.com/KC3Kai/KC3Kai/issues/848)

is it correct?

**Comment by dragonjet** [comment]
this has been fixed in 30.9.3: https://github.com/KC3Kai/KC3Kai/pull/1538

as reported by the issue: https://github.com/KC3Kai/KC3Kai/issues/1537

**Comment by Archduke88** [comment]
Thank you.
