### ISSUE TITLE
battle prediction regarding abyssal combined fleet

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#1542]
abyssal combined fleet is a new mechanism, so as always I need some battle data to have battle prediction support implemented.

@KC3Kai/everyone it'll be appreciated if you can post any of battle data about 6-5 's boss node:

- day & night battle data, when facing against abyssal main fleet at night
- same as above, but facing agaist abyssal escort fleet at night

I guess @fourinone41 might also need this for the battle replayer (or have you happened to have some already?)

(P.S. the api request might look like `api_req_combined_battle/ec_battle` `api_req_combiend_battle/ec_midnight_battle` in your network tab)

**Comment by dragonjet** [comment]
`api_req_combined_battle/ec_battle`
http://pastebin.com/M2zLWXD1

`api_req_combiend_battle/ec_midnight_battle`
http://pastebin.com/LK6K8ib9

`api_req_combiend_battle/battleresult`
http://pastebin.com/8p1G65LP

**Comment by fourinone41** [comment]
API info, if it helps:
`api_kouku.api_stage3_combined.api_edam` has escort damages, main damages are still in `api_stage3`.
`api_kouku.api_plane_from` changed: before, it used 7-12 for enemies, now it uses 1-6 for main and 7-12 for escort. This happens now in non-combined battle responses too: now they always use 1-6. But I don't think this is relevant to battle prediction.

raigeki can target both fleets. The arrays are now length 12, 1-6 refer to main and 7-12 refer to escort.

hougeki is messy. Normally, 1-6 are your ships and 7-12 are enemies. Here, 1-6 are your ships, 1-6 are also main enemies, and 7-12 are escort enemies. New `api_at_eflag` shows if the number is for you or for enemy: 0 = you, 1 = enemy.

midnight probably uses new `api_active_deck' to mark which fleet you fight. [1,1] means main fleet, and I have no data yet for escort. Enemies are still 7-12 regardless of fleet like in normal battles.

`api_ship_ke_combined` is new, contains escort master IDs. `api_nowhps_combined` and `api_maxhps_combined` has escort HPs in elements 7-12.

**Comment by Javran** [comment]
@fourinone41 thanks for the info, that sounds quite messy indeed...

**Comment by yukixz** [comment]
I guess `api_active_deck` stand for fleet entered night battle. [0] for ours and [1] for enemy.
Current [1, 1] means deck 1 of ours and deck 1 of enemy entered night.
It may be [1, 2] if we didnt destory flagship of escort enemy fleet. (Its so hard to keep him alive!)
Also it predicts combined fleet vs combined fleet in future.

**Comment by fourinone41** [comment]
Can confirm that `api_active_deck[1]` is for enemy, and 2 means fighting the escort.
http://pastebin.com/dLCXTZWh

**Comment by LostLogia4** [comment]
We have abyssal combined fleet now? :open_mouth: 
Anyway, it seems like DJ already have the solution in #1544

**Comment by mikenzb** [comment]
Just making sure you're also aware but 6-5 boss bar does not show up on the KC3 panel telling you how many kills you need/have left atm on latest master, not sure if #1544 fixes that also.

I should've tested this branch today when I was clearing 6-5 however it totally slipped my mind as I thought this feature was still being working on.

**Comment by Javran** [comment]
finally got some time to work on this, I've uploaded lastest battle prediction to master branch 0bf67af
now only day battles are supported (tested on sample data @dragonjet gave).

for night battle, I still need data against enemy escort fleet to figure it out.

you can try it out for yourself, open console in Strategy room > Dev-Only > Playground


```javascript
var DA = PS["KanColle.DamageAnalysis.FFI"]
svdata={"api_result":1, ... }
var damecon =  [0,0,0,0,0,0]
DA.analyzeAbyssalCTFBattleJS(damecon,svdata.api_data)
```
the result should look like:

```json
{
    "main":[
        {
            "hp":87,
            "sunk":false,
            "dameConConsumed":false
        },
        {
            "hp":38,
            "sunk":false,
            "dameConConsumed":false
        },
        {
            "hp":56,
            "sunk":false,
            "dameConConsumed":false
        },
        {
            "hp":50,
            "sunk":false,
            "dameConConsumed":false
        },
        {
            "hp":16,
            "sunk":false,
            "dameConConsumed":false
        },
        {
            "hp":23,
            "sunk":false,
            "dameConConsumed":false
        }
    ],
    "enemyMain":[
        {
            "hp":225,
            "sunk":false,
            "dameConConsumed":false
        },
        {
            "hp":-123,
            "sunk":true,
            "dameConConsumed":false
        },
        {
            "hp":-137,
            "sunk":true,
            "dameConConsumed":false
        },
        {
            "hp":-112,
            "sunk":true,
            "dameConConsumed":false
        },
        {
            "hp":-55,
            "sunk":true,
            "dameConConsumed":false
        },
        {
            "hp":-35,
            "sunk":true,
            "dameConConsumed":false
        }
    ],
    "enemyEscort":[
        {
            "hp":-175,
            "sunk":true,
            "dameConConsumed":false
        },
        {
            "hp":71,
            "sunk":false,
            "dameConConsumed":false
        },
        {
            "hp":9,
            "sunk":false,
            "dameConConsumed":false
        },
        {
            "hp":-84,
            "sunk":true,
            "dameConConsumed":false
        },
        {
            "hp":-66,
            "sunk":true,
            "dameConConsumed":false
        },
        {
            "hp":-141,
            "sunk":true,
            "dameConConsumed":false
        }
    ]
}
```

**Comment by Javran** [comment]
about the night battle data on https://github.com/KC3Kai/KC3Kai/issues/1542#issuecomment-251841453 I notice it contains both `api_nowhps_combined` and `api_maxhps_combined`, but `api_hougeki` doesn't have a `api_ateflag` thing. depite I think this is just a regular hougeki data with some special care to which one we are engaging at night, I still need some night battle data against enemy escort fleet.

I'll add a new API for abyssal combined fleet night battle. But for now, if you want battle prediction to work on night battles, you can trick battle prediction by modifying `api_nowhps` and `api_maxhps` of battle data to make it look like a regular night battle (no need to remove any field)

**Comment by fourinone41** [comment]
I had already linked to a response where you fight the escort fleet, please see here: http://pastebin.com/dLCXTZWh

You're right that it's just a regular hougeki data for slot IDs. It probably includes `api_nowhps_combined` because it show both fleets briefly before one of them retreats, and it uses `api_active_deck[1]` to determine which you fight.

**Comment by Javran** [comment]
@fourinone41 I see, thanks for the info!

**Comment by Javran** [comment]
update: battle prediction support for abyssal combined fleet is now fully implemented, check out lastest master branch to play with it.

the api for day battle is:

`analyzeAbyssalCTFBattleJS(<damecon>, <data>)`

and night battle: 

`analyzeAbyssalCTFNightBattleJS(<damecon>, <data>)`

the output format is exactly the same for both, so for night battle you still need to check `api_active_deck` to determine which enemy fleet you are fighting against.

we still need some work to put it on UI, which I'm not good at and not going to do. maybe @dragonjet can take over this?

**Comment by dragonjet** [comment]
yep, will do :+1:

**Comment by ethrundr** [comment]
still haven't passed 6-3 yet, so unfortunately I can't help here :(
