### ISSUE TITLE
no node prediction on 6-3 resource nodes (G and H)

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#1543]
request `kcsapi/api_req_map/next`, data from each node:

on node G

> svdata={"api_result":1,"api_result_msg":"\u6210\u529f","api_data":{"api_rashin_flg":1,"api_rashin_id":3,"api_maparea_id":6,"api_mapinfo_no":3,"api_no":7,"api_color_no":9,"api_event_id":7,"api_event_kind":0,"api_next":1,"api_bosscell_no":10,"api_bosscomp":1,"api_comment_kind":0,"api_production_kind":0,"api_airsearch":{"api_plane_type":2,"api_result":1},"api_itemget":{"api_usemst":4,"api_id":7,"api_getcount":1,"api_name":"","api_icon_id":7}}}

on node H

> svdata={"api_result":1,"api_result_msg":"\u6210\u529f","api_data":{"api_rashin_flg":0,"api_rashin_id":0,"api_maparea_id":6,"api_mapinfo_no":3,"api_no":12,"api_color_no":9,"api_event_id":7,"api_event_kind":0,"api_next":2,"api_bosscell_no":10,"api_bosscomp":1,"api_comment_kind":0,"api_production_kind":0,"api_airsearch":{"api_plane_type":2,"api_result":1},"api_itemget":{"api_usemst":4,"api_id":4,"api_getcount":40,"api_name":"","api_icon_id":4}}}

**Comment by sinsinpub** [comment]
but all nodes with `api_itemget` will be defined as Resource Node? (see `SortieManager.js@L197`: `if (typeof nodeData.api_itemget != "undefined")`) despite of `api_event_kind: 0, api_event_id: 2 or 7`

**Comment by dragonjet** [comment]
whats is it detected as at the moment? I haven't unlocked it, so I can't test. seems it should fall under resource elseif though

**Comment by ethrundr** [comment]
It is detected as a blue "Battle Avoided"

**Comment by dragonjet** [comment]
I just got full sample data from @Mikenzb for 6-3
(which I can re-run in https://github.com/KC3Kai/kancolle-api-sim)

going to take a look at this
