### ISSUE TITLE
Hope to distinguish Emergency Repair Goddess from Emergency Repair Personal in additional slot

### ISSUE THREAD

**Issue by yeshasuicide** [KC3Kai/KC3Kai#1547]
Sometimes I want to make sure which one is equipped,they are all shown as a little white hammer.
in common slots,  a hint can be seen on hover
wish my expression is clear,thanks

**Comment by dragonjet** [comment]
added glow. difference between goddess and regular repair. also applies when equipped on extra slot

![ss 2016-10-09 at 03 25 30](https://cloud.githubusercontent.com/assets/557312/19215118/108db8fe-8dd0-11e6-8e4a-b7aa76db1ef3.jpg)
