### ISSUE TITLE
Quests.json not being read correctly for the most recent quests

### ISSUE THREAD

**Issue by rephira** [KC3Kai/KC3Kai#1548]
There is currently on issue with quests.json not being read correctly.

It seems to be a global issue, where KC3Kai can retrieve the English translation, but for all the other languages it is failing to do so.

If other languages just do not have these IDs, then at least Korean for sure is suffering it.
Problem is apparent with Quest ID 647 (F43)

**Comment by dragonjet** [comment]
confirmed the expected quest IDs were not included in previous release. @rephira you should see it now in 30.9.5 :smile:
