### ISSUE TITLE
Annoying Taiha Alert Screenshot Issue

### ISSUE THREAD

**Issue by nonsensed** [KC3Kai/KC3Kai#1550]
![discord chat](http://i.imgur.com/DG5B9cW.png)

Personal testing, may or may not match with Tedster's experiences:

I can repeat this randomly without having to trigger a taiha in night battle. It seems it's 50/50 whether the screenshot will have the blood animation or not regardless of night battle. I'm fairly sure there's a timing or animation lag issue here where the blood animation isn't always hidden before the screenshot is taken.

Tedster mentions night battle at a boss node specifically, which is difficult to test reliably, but when I enter yasen with a taiha'd ship, if I spam screenshot, the blood appearance chance is 50/50. Usually the first screenshot has blood on it, but that may be a coincidence.

**Comment by dragonjet** [comment]
hmm yes this might be animation lag, which I didn't foresee. I'll have to check it out and probably just put back the blood to fade in after 5 seconds after the last screenshot was taken
