### ISSUE TITLE
New Version of Chrome not opening KC3

### ISSUE THREAD

**Issue by BranOtaku** [KC3Kai/KC3Kai#1552]
- [ ] Screenshots which accurately paint the issue(s) you are facing.
- [ ] A step by step method that you did to describe how you got to that issue.

### Versions:
- Chrome Version 54.0.2840.59 m
- Windows 8.1
- 64 Bit
- KC3 Version 30.9.4
- Current using Webstore Version

### Steps to reproduce:
1. Using the extension on the taskbar, select the using API link to load up DMM. 
2. Log in using account details
3. Wait as the original site loads before the new page pops up to prompt you to open up the Admiral Dashboard
4. As you open it up, wait as the page never loads.

### Screenshots (if applicable): http://imgur.com/a/dFo01

Note: This has only recently popped up most likely due to the new Chrome version update. The only way to play now is through the DMM website however you will have no access to the English subs in the game.

**Comment by mikenzb** [comment]
See #1549

**Comment by ethrundr** [comment]
Locked and discussion moved to the other thread.
