### ISSUE TITLE
Stuck in "Waiting for game actions..."

### ISSUE THREAD

**Issue by Reddo-KanColle** [KC3Kai/KC3Kai#1558]
Please make sure that you have these details on hand when submitting your issue/bug report as this will greatly speed up the issue triage process -- thank you!

- [Version 54.0.2840.71 m ] Your Chrome version - via chrome://version/
- [ Windows 10 Pro / 1607] Your OS and its version
- [ 64bit] 32bit or 64bit?
- [ 30.10.0] Your KC3 Kai version - via chrome://extensions/
- [ developer build] Which build you have tried running? webstore version as in the one from [Chrome Web Store](https://chrome.google.com/webstore/detail/kancolle-command-center-%E6%94%B9/hkgmldnainaglpjngpajnnjfhpdjkohh) or Github variant (better known as developer builds).
- [http://imgur.com/a/qFlMO ] Screenshots which accurately paint the issue(s) you are facing.
- [ Opened Chrome > Clicked "Play via API Link" > Logged-in on DMM > KC3Kai pops-up > I pressed Ctrl+Shift+J > Clicked DevKC3Kai in the developer tools > I got this error] A step by step method that you did to describe how you got to that issue.

**Comment by dragonjet** [comment]
API Link white screen fix here: https://github.com/KC3Kai/KC3Kai/issues/1549

**Comment by ethrundr** [comment]
locked and labelled for duplicate
