### ISSUE TITLE
program is not loaded

### ISSUE THREAD

**Issue by oconor** [KC3Kai/KC3Kai#1559]
Please make sure that you have these details on hand when submitting your issue/bug report as this will greatly speed up the issue triage process -- thank you!

- [x] Your Chrome version - 54.0.2840.71
- [ ] Your OS and its version
- [x] 32bit or 64bit? 64
- [x] Your KC3 Kai version - 30.9.4 
- [ ] Which build you have tried running? webstore version as in the one from [Chrome Web Store](https://chrome.google.com/webstore/detail/kancolle-command-center-%E6%94%B9/hkgmldnainaglpjngpajnnjfhpdjkohh) or Github variant (better known as developer builds).
- [http://f5.s.qip.ru/UvvpmrFn.jpg ] Screenshots which accurately paint the issue(s) you are facing.
- [ ] A step by step method that you did to describe how you got to that issue.

**Comment by dragonjet** [comment]
API Link white screen fix here: https://github.com/KC3Kai/KC3Kai/issues/1549

**Comment by ethrundr** [comment]
locked and labelled for duplicates
