### ISSUE TITLE
Dev-only menu no longer shows up

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#1570]
latest master branch, the whole "Dev-only" section is missing despite having `ConfigManager.devOnlyPages` set to true.

the current workaround is to bring up console and execute `$("#menu .submenu.dev-only").show();`

**Comment by dragonjet** [comment]
hmm that's odd, the code is still there. also happens on my side

**Comment by Javran** [comment]
@dragonjet I tried but can't figure out why. from what I know, `.show()` in `ready` callback does trigger, but it disappears afterwards, commenting out other parts in `ready` callback didn't make a difference. it could be wrong but my theory is CSS rule gets re-applied somewhere after `.show()` is called.

**Comment by sinsinpub** [comment]
because the theme css is appended by JS inside `ready` function, async process make `.show()` running beofore style `display:none` applied. So the `#error` element will not be shown either...

**Comment by Javran** [comment]
maybe a more appropriate fix is to setup css-related stuff after `.append` is done?

**Comment by sinsinpub** [comment]
yea, a solution like [this](http://stackoverflow.com/questions/3498647/jquery-loading-css-on-demand-callback-if-done) may be better

**Comment by Javran** [comment]
@sinsinpub I was thinking about promises, something like the following might work:

`.append(css).promise().then( function() {  <do stuff>  } );`

just an idea, I'm good with whatever works better.

**Comment by dragonjet** [comment]
ay, the fix I did was just revert the thing
css wont have the style definition, so by default it's shown
if config dev pages is false, hide it.
so regardless of when the css is loaded will not affect the showing or hiding the tabs

**Comment by sinsinpub** [comment]
so what about the `#error` element?

suggest that add another fixed loaded css file which contains those common and logical styles only 😅

**Comment by dragonjet** [comment]
that's a good idea actually :+1:
