### ISSUE TITLE
Strategy room dark theme improvement

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#1571]
just some feedback on dark theme, mainly that some tabs have weird color scheme / layout:

(using todo list for tracking)
- [x] Leveling: header background is still in light blue
- [x] ~~Flowchart: I feel these buttons are a bit "too light", not a big issue though~~
    won't fix. not a serious problem, might need some darker icon which sounds overkill to me.
- [x] Encounters: formations are in light blue background
- [x] PvP history: not dark-themized
- [x] Ship Library: not dark-themized
- [x] Equipment Library
- [x] Quotes: not dark-themized
- [x] Expedition History: not dark-themized
- [x] Expedition Scorer: not dark-themized 
- [x] Compare: "FULL VIEW" text is hard to see

feel free to edit and make this list more structured as necessary

**Comment by Javran** [comment]
would there be ppl working on this? I'm too busy to have a plan.

**Comment by dragonjet** [comment]
not in my immediate to-do list, but I'd like to continue on that

**Comment by Javran** [comment]
@dragonjet do you have plan to work on this recently? if not I might volunteer myself on some of these.
since it's been a while since related issues from users (like #1670) are popping up, and the reason some ppl (like me) are still using the legacy theme.

**Comment by dragonjet** [comment]
ah it's not in my immediate list, and haven't touched in code yet. so you can take over if you want

**Comment by Javran** [comment]
start working on this, see `dev-sr-dark` for updates.

**Comment by sinsinpub** [comment]
a suggestion: don't remove some styles of colors related to the logic from `XXpage.css` (might comment out them), as they are useful to see: there are color-dependence things when devs try to update pages, and will be reminded to update both `legacy.css` and `dark.css`.
for the same reason, also applied to those class only defining color thingy, keep a empty class like `.class { }` instead of removing it.

**Comment by Javran** [comment]
@sinsinpub done with your suggestions in mind, see PR #1751. also feel free to take over, this is pretty much best I can do as I'm never confident about my personal taste of color themes xD

**Comment by Javran** [comment]
done by #1751
