### ISSUE TITLE
Screen capture function triggers screen blur and blood overlay from Taiha alert

### ISSUE THREAD

**Issue by TawiTawiTeitoku** [KC3Kai/KC3Kai#1573]
### Versions:

Chrome version: 54.0.2840.71 m (64-bit)
KC3 Kai version: 30.10.1
Settings for screen capture:
- Output mode: Download
- Filetype: PNG
- Image quality: 100%
- Download Sub-directory: KanColle
- Device Pixel Ratio: Normal

Settings for Taiha alert:
Checked options: "Enabled", "screen blur", "screen blood"
### Steps to reproduce:

Just by pressing the screen capture button, with the screen blurring and/or blood overlay taiha alert enabled.
### Actual behaviour:

Capturing the game screen, triggering the screen blurring and/or blood overlay alert afterwards.
The blur/blood cannot be removed until refreshing of fleet status, like moving to next node, or going back to port.
### Expected behaviour:

Capturing the game screen at that particular moment.
Taiha alert only be triggered when ship is in taiha status.
### Screenshots (if applicable):

As an example, capturing this fleet by the screen capture function: http://i.imgur.com/3sjIF3I.png
The proper captured image is still downloaded to my computer: http://i.imgur.com/r9Mx1z8.png
Yet the taiha alerts are also triggered: http://i.imgur.com/oD4tKoW.png
Taiha alerts can be removed by refreshing of fleet information (going to port in this case): http://i.imgur.com/YcVdyzg.png

May I ask if there is any way of preventing the taiha alert to be triggered by screen capture function, while still remaining the alerts enabled? Thanks for any help will be provided.

**Comment by Tedster59** [comment]
I am experiencing the same issue.

**Comment by ethrundr** [comment]
@KC3Kai/developers @dragonjet 
Seems the issue in #1550 still occurs during 30.10.0?

**Comment by Tedster59** [comment]
no, this is a separate issue.  clicking the screenshot button triggers the taiha alert to appear over the main game window (but it does not in the screenshot)

**Comment by TawiTawiTeitoku** [comment]
@ethrundr It seems to be a different case
#1550 states the taiha warning already triggered to be appearing in the captured image.
#1573 (this case) is the screen capturing function triggers the taiha warning without any ship in fleet actually in the state of taiha.
Screenshots attached above may be helpful for clarifying none of the ship is in taiha state
> Yet the taiha alerts are also triggered: http://i.imgur.com/oD4tKoW.png
I hope this may help.

**Comment by TawiTawiTeitoku** [comment]
May I also mention some testing I have done towards this issue.
- With "Screen Blur" and/or "Screen Blood" option not checked, screen capturing will not cause the blur/blood to appear on the screen as stated above (with "Enabled" option still being checked).
- "Red shade on Panel" option operates normally, which capturing the game screen will not trigger the red shading on the KC3 panel.
I wish this piece of information will be helpful, and once again thank you for the help provided.

**Comment by ethrundr** [comment]
ah ok. I misunderstood the extent of the bug.
thanks for clarifying

**Comment by dragonjet** [comment]
yep this bug was spawned from the fix. sorry about that, will fix on next release
