### ISSUE TITLE
[EN] quests.json memo override

### ISSUE THREAD

**Issue by nonsensed** [KC3Kai/KC3Kai#1574]
In the TL file quests.json, it's possible to use the optional field, `memo`

I want to use this in the [EN] quests.json, but I noticed it carries over into other language files that don't use `memo`.

![img](http://i.imgur.com/2ncw02M.png)

This is not a desired result. Is it possible to add an exception for `memo` so that if `name` or `desc` exists in another language's quests.json file, `memo` does not carry over from [EN]?

**Comment by dragonjet** [comment]
merged #1575
