### ISSUE TITLE
Fit Gun Display Bug

### ISSUE THREAD

**Issue by ethrundr** [KC3Kai/KC3Kai#1580]
Report from Facebook:

> On the Panel, it shows the red color even for guns that actually gives out bonus / properly fitted to a ship.

Versioning details:
- Chrome version 54.0.2840.71
- OS Windows 10, 64 bit
- KC3kai version 30.10.2 Webstore

Screenshot will be provided later.

**Comment by vanzstrike** [comment]
![bug](https://cloud.githubusercontent.com/assets/14976760/19914704/4d39dedc-a0df-11e6-847b-d73bc2cc9862.png)
![bug 2](https://cloud.githubusercontent.com/assets/14976760/19914708/5f3a3abe-a0df-11e6-9dab-9413268cd97c.png)

**Comment by dragonjet** [comment]
thanks for the notice, it has something to do with not removing the previous styles on that box before we re-apply the colors. same way that if you fitted a green one for the first time, it will forever be green until devtools is reopened
