### ISSUE TITLE
.crx release?

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#1582]
kcwiki is creating [a mirror site](https://mirrors.kcwiki.moe/) that collects many kancolle-related tools, and I had a conversation with kcwiki owner few days ago, he asked whether it is possible to have .crx release for KC3Kai?

**Comment by dragonjet** [comment]
sure, I will revisit the automated releases on github. I failed to integrate it last time to our travis builds but hopefully it will go smooth this time so each release will have crx version and tagging.
