### ISSUE TITLE
About page logo for contributing sites

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#1583]
This suggestion also comes from kcwiki owner, the idea is to put some contributing site logos on our about page. This might include sites providing game related-data & quote translations. For now our about page credits developers & tester & translators but for websites like kcwiki and wikia, we are just mentioning them by texts. considering the time and effort spent for site contributors, I think this is a more proper way of crediting them.

**Comment by dragonjet** [comment]
agreed, sounds good to me :+1:

**Comment by ethrundr** [comment]
agreed as well 👍

**Comment by dragonjet** [comment]
is there a logo we can put on kcwiki's box? I see the site has a favicon but probably a 64x64 would be better case

**Comment by Javran** [comment]
I got some feedbacks from kcwiki side:

1.  regarding About page description of kcwiki (`AboutPartnerZHKcWikiDesc`), they have not only provided Simplified Chinese translation for quests and quotes, a large part of original Japanese quotes are also comming from them. so @KC3Kai/translators might consider changing their translation to credit their contribution to jp quotes as well.

2. for this one we need to do nothing but wait, there are trying to make an icon for poi-statistic so expect an icon update in future.

However I don't know if they have anything more to say, as my means of communicating with them are sort of delayed. so for now let's keep this issue open until I think kcwiki side feels satisfied.

**Comment by dragonjet** [comment]
I see, sorry I probably missed something in the migration, I do remember an entry before that says about JP subtitles but is not in the list. thanks for notice

**Comment by sinsinpub** [comment]
kcwiki about JP quotes do be in the list of subtitles credits, nothing missed

**Comment by dragonjet** [comment]
implemented

**Comment by dragonjet** [comment]
backread a bit, we need to keep this open until kcwiki is good with the changes

**Comment by Javran** [comment]
just had a little conversation and they seems to be good with this, so yeah we can close this now.
