### ISSUE TITLE
White screen and java is enabled

### ISSUE THREAD

**Issue by Kingshound** [KC3Kai/KC3Kai#1595]
Please make sure that you have these details on hand when submitting your issue/bug report as this will greatly speed up the issue triage process -- thank you!

- [ ] Your Chrome version - via chrome://version/
- [ ] Your OS and its version
- [ ] 32bit or 64bit?
- [ ] Your KC3 Kai version - via chrome://extensions/
- [ ] Which build you have tried running? webstore version as in the one from [Chrome Web Store](https://chrome.google.com/webstore/detail/kancolle-command-center-%E6%94%B9/hkgmldnainaglpjngpajnnjfhpdjkohh) or Github variant (better known as developer builds).
- [ ] Screenshots which accurately paint the issue(s) you are facing.
- [ ] A step by step method that you did to describe how you got to that issue.

### Versions:
Chrome version: 54.0.2840.98 (64bit)
OS: MacOS Sierra version 10.12.1
KC3 version: 10.30.3
16bit mac desktop
### Steps to reproduce:
Opened using play via api link
pressed f12 and clicked kancolle extension 
### Actual behaviour:
White screen  
### Expected behaviour:
Open kancolle with the viewer. 
### Screenshots (if applicable):
https://images-2.discordapp.net/.eJwNwksKwyAQANC7uK86_ibmDoVCDiBiRAOJBp2uSu_ePt6HvcfJVlaJ7rkKsR8z9bHzSX3EknnpvZw53sfkqV8iEsVUr9xoClBqQTTOgQdUxhoUyjj0VmmpUVpvFnBiSyPnFrbaKSgJ7gHwHyIF5Npyg-H15Hcr7PsDXeMqcA.B8Ew9bWvoNIQ6iv1uFSsdXTrdTk

**Comment by dragonjet** [comment]
Explanation is already on the screen. Please read the message on the red box :disappointed:
