### ISSUE TITLE
Console totally not working

### ISSUE THREAD

**Issue by mirrorpurple** [KC3Kai/KC3Kai#1598]
Please make sure that you have these details on hand when submitting your issue/bug report as this will greatly speed up the issue triage process -- thank you!

- [ ] Your Chrome version - via chrome://version/ 
- [ ] Your OS and its version
- [ ] 32bit or 64bit?
- [ ] Your KC3 Kai version - via chrome://extensions/ 
- [ ] Which build you have tried running?
- [ ] Screenshots which accurately paint the issue(s) you are facing. 
- [ ] A step by step method that you did to describe how you got to that issue.

### Screenshots (if applicable):

Is it because my Chrome build is too new that it's not compatible anymore? If it is, I can try to revert to the version.

**Comment by dragonjet** [comment]
refer to [this table](http://omahaproxy.appspot.com/) and find the `stable` version number to see what's the ideal version of chrome. `beta`, `dev`, and `canary` all have experimental features that could break stuff, but those usually don't get released, and get fixed when moving into the stable release. Thus, we don't spend efforts into fixing bugs on kc3 side if it's from those advanced versions.
