### ISSUE TITLE
www.dmm.com didn't send any data

### ISSUE THREAD

**Issue by Ganford** [KC3Kai/KC3Kai#1600]
Windows 8.1 Pro
64-bit
KC3 Kai  30.11.0

Hi, I got an error that states "www.dmm.com didn't send any data". I play Kancolle in my office and it worked fine until the latest KC3 Kai update. Is there something I didn't notice about it. Thx for the help.

**Comment by dragonjet** [comment]
does this problem still persist? looks like internet problem
