### ISSUE TITLE
Battle prediction, 12 vs. 12

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#1606]
as always, open up an issue for collecting data for E3 12vs12 battles so I can work on battle prediction.

**Comment by fourinone41** [comment]
I got some API responses from Tedster: https://cdn.discordapp.com/attachments/249389023364251648/249389063298088962/recorded_kcsapi_3.json

12vs12 data is in `api_req_combined_battle/each_battle`.

We also need to update Kcsapi.js to record this for sortie history.

**Comment by yukixz** [comment]
@fourinone41 What's type of combined fleet of the record?

**Comment by fourinone41** [comment]
@yukixz It's a CTF.

**Comment by yukixz** [comment]
Thanks. Seems the new developer of C2 is smarter than old.

**Comment by Tedster59** [comment]
Not that that response is from easy difficulty, hard difficulty might be different (probably just different enemies)

**Comment by dragonjet** [comment]
excerpt from the json file for easier copying:

`api_req_combined_battle/each_battle`

```
svdata={"api_result":1,"api_result_msg":"\u6210\u529f","api_data":{"api_deck_id":1,"api_ship_ke":[-1,708,525,525,594,575,575],"api_ship_ke_combined":[-1,555,527,527,520,501,501],"api_ship_lv":[-1,1,1,1,1,1,1],"api_ship_lv_combined":[-1,1,1,1,1,1,1],"api_nowhps":[-1,67,57,83,52,57,45,370,88,88,80,35,35],"api_maxhps":[-1,67,67,83,57,57,45,370,88,88,80,35,35],"api_nowhps_combined":[-1,50,35,31,52,53,43,57,76,76,55,20,20],"api_maxhps_combined":[-1,50,37,31,52,53,43,57,76,76,55,20,20],"api_eSlot":[[501,541,571,571,-1],[520,517,524,-1,-1],[520,517,524,-1,-1],[505,505,515,525,-1],[502,545,542,-1,-1],[502,545,542,-1,-1]],"api_eSlot_combined":[[506,525,542,543,-1],[505,506,515,525,-1],[505,506,515,525,-1],[506,513,525,-1,-1],[501,-1,-1,-1,-1],[501,-1,-1,-1,-1]],"api_fParam":[[64,0,82,76],[57,0,84,75],[98,0,82,95],[77,79,69,75],[77,79,69,75],[29,0,39,59]],"api_fParam_combined":[[70,98,68,69],[60,54,110,54],[53,84,81,51],[78,77,65,72],[78,74,66,73],[63,139,43,63]],"api_eParam":[[95,90,100,175],[0,0,40,55],[0,0,40,55],[73,66,72,82],[38,60,30,22],[38,60,30,22]],"api_eParam_combined":[[48,80,30,39],[68,48,40,70],[68,48,40,70],[36,48,24,36],[5,15,6,5],[5,15,6,5]],"api_midnight_flag":1,"api_search":[1,1],"api_formation":["14",13,1],"api_stage_flag":[1,1,1],"api_kouku":{"api_plane_from":[[1,2,6],[1,2,3]],"api_stage1":{"api_f_count":192,"api_f_lostcount":1,"api_e_count":206,"api_e_lostcount":74,"api_disp_seiku":1,"api_touch_plane":[144,-1]},"api_stage2":{"api_f_count":60,"api_f_lostcount":1,"api_e_count":91,"api_e_lostcount":50,"api_air_fire":{"api_idx":7,"api_kind":1,"api_use_items":[122,122,106]}},"api_stage3":{"api_frai_flag":[-1,0,0,0,0,0,0],"api_erai_flag":[-1,0,0,0,0,1,0],"api_fbak_flag":[-1,0,0,1,1,0,0],"api_ebak_flag":[-1,0,0,0,0,0,0],"api_fcl_flag":[-1,0,0,0,0,0,0],"api_ecl_flag":[-1,0,0,0,0,0,0],"api_fdam":[-1,0,0,0,0,0,0],"api_edam":[-1,0,0,0,0,65,0]},"api_stage3_combined":{"api_frai_flag":[-1,0,1,0,1,0,0],"api_erai_flag":[-1,0,0,0,0,0,0],"api_fbak_flag":[-1,0,0,0,0,0,0],"api_ebak_flag":[-1,0,0,0,0,0,0],"api_fcl_flag":[-1,0,0,0,0,0,0],"api_ecl_flag":[-1,0,0,0,0,0,0],"api_fdam":[-1,0,4,0,0,0,0],"api_edam":[-1,0,0,0,0,0,0]}},"api_support_flag":0,"api_support_info":null,"api_opening_taisen_flag":0,"api_opening_taisen":null,"api_opening_flag":1,"api_opening_atack":{"api_frai":[-1,0,0,0,0,0,0,0,0,0,0,0,3],"api_erai":[-1,0,0,0,0,0,0,0,0,0,0,0,0],"api_fdam":[-1,0,0,0,0,0,0,0,0,0,0,0,0],"api_edam":[-1,0,0,91,0,0,0,0,0,0,0,0,0],"api_fydam":[-1,0,0,0,0,0,0,0,0,0,0,0,91],"api_eydam":[-1,0,0,0,0,0,0,0,0,0,0,0,0],"api_fcl":[-1,0,0,0,0,0,0,0,0,0,0,0,1],"api_ecl":[-1,0,0,0,0,0,0,0,0,0,0,0,0]},"api_hourai_flag":[1,1,1,1],"api_hougeki1":{"api_at_eflag":[-1,0,1,0,1,0,0],"api_at_list":[-1,3,1,5,4,4,1],"api_at_type":[-1,0,0,2,0,0,0],"api_df_list":[-1,[6],[2],[2,2],[3],[4],[4]],"api_si_list":[-1,[103],[501],[50,90],[505],[90],[-1]],"api_cl_list":[-1,[1],[1],[1,1],[0],[1],[1]],"api_damage":[-1,[133],[25],[82,72],[0],[25],[54]]},"api_hougeki2":{"api_at_eflag":[-1,0,1,0,1,0,1,0,0,0],"api_at_list":[-1,12,7,10,9,7,8,11,8,9],"api_at_type":[-1,0,0,2,0,2,0,2,0,0],"api_df_list":[-1,[10],[11],[7,7],[7],[11,11],[10],[8,8],[12],[9]],"api_si_list":[-1,[50],[506],[50,50],[505],[90,50],[505],[50,90],[122],[-1]],"api_cl_list":[-1,[1],[2],[2,1],[0],[1,1],[1],[1,1],[1],[1]],"api_damage":[-1,[55],[7],[171,90],[0],[117,117],[6],[65,51],[71],[7]]},"api_raigeki":{"api_frai":[-1,0,0,0,0,0,0,9,9,1,9,9,9],"api_erai":[-1,0,0,0,0,0,0,0,0,11,0,0,0],"api_fdam":[-1,0,0,0,0,0,0,0,0,0,0,0,0],"api_edam":[-1,34,0,0,0,0,0,0,0,237,0,0,0],"api_fydam":[-1,0,0,0,0,0,0,60,53,34,0,23,101],"api_eydam":[-1,0,0,0,0,0,0,0,0,0,0,0,0],"api_fcl":[-1,0,0,0,0,0,0,1,2,1,0,1,1],"api_ecl":[-1,0,0,0,0,0,0,0,0,0,0,0,0]},"api_hougeki3":{"api_at_eflag":[-1,0,1,0,0,0],"api_at_list":[-1,1,1,3,4,5],"api_at_type":[-1,0,0,2,0,2],"api_df_list":[-1,[4],[11],[1,1],[1],[1,1]],"api_si_list":[-1,[-1],[501],[103,103],[90],[50,90]],"api_cl_list":[-1,[1],[1],[1,1],[1],[1,1]],"api_damage":[-1,[98],[13],[44,43],[32],[22,26]]}}}
```

**Comment by Javran** [comment]
I've implemented battle prediction for CTF and night battle. 

usage:
```javascript
var DA = PS["KanColle.DamageAnalysis.FFI"]
svdata={"api_result":1, ... }
var damecon =  [0,0,0,0,0,0] + [0,0,0,0,0,0]
// for CTF battle
DA.analyzeBothCombinedCTFBattleJS(damecon,svdata.api_data)
// for night battle
DA.analyzeBothCombinedNightBattle(damecon,svdata.api_data)
```
for both function, the result format is almost the same as described in https://github.com/KC3Kai/KC3Kai/issues/1542#issuecomment-254040218
except fleets are identified by these field names: `allyMain`, `allyEscort`, `enemyMain`, `enemyEscort`.

Note that the night battle API expects a damecon info array of 12 elements despite that damecon info for ally main fleet doesn't really matter for night battle -- this is just to make it consistent with KCAPI.

For the same reason, the result contains 4 fleets (i.e. `{ally,enemy}x{Main,Escort}`), please check `api_active_deck` to see what are the actual fleets involved in night battle:

- `api_active_deck[0]` should always be `2` for combined fleet, so ally escort fleet always enter night battle
- `api_active_deck[1]` could be either `1` (for enemy main fleet) or `2` (for enemy escort fleet)

**Comment by Javran** [comment]
update: thanks for the help from @yukixz, STF support is now up. 

- the API name is `analyzeBothCombinedSTFBattleJS`.
- no sample data for testing though, so I'm still accepting STF battle data just for verification
- I don't think anyone is brave (or bored) enough to try TECF on E-3, treat it as CTF in that case....

**Comment by dragonjet** [comment]
`analyzeBothCombinedSTFBattleJS` means the enemy is the one STF right? not player's fleet

**Comment by Javran** [comment]
@dragonjet that STF means player's fleet. enemy fleet is fixed and I think the order of shelling & torpedo salvo depends only by the type of combined fleet player's using.

**Comment by dragonjet** [comment]
hmmm seems I'm getting wrong results for `analyzeCTFBattleJS` when player is combined, and enemy is single fleet, which leads to something like this, bars are longer than max HP

![chrome_2016-11-20_12-05-40](https://cloud.githubusercontent.com/assets/557312/20460304/b44e00c4-af19-11e6-9f55-9d6d3ee5a5c7.png)

**Comment by Javran** [comment]
@dragonjet good to know the problem is not on my side, that'll be really weird if that happens, I have a test suite that covers almost every case and KC3Kai itself also have some tests covering combined fleet xD.

**Comment by dragonjet** [comment]
we could close this by the merge of 30.11.2, we can reopen in case there's another report

**Comment by Tedster59** [comment]
apparently STF doesn't work, courtesy of Sao-link over on subreddit discord

[https://cdn.discordapp.com/attachments/205766705463427072/250051999024807946/unknown.png](url)

**Comment by Javran** [comment]
@Tedster59 I can't open the link, also I need a replay (image exported from history) for debugging.

**Comment by Tedster59** [comment]
@Javran 
image should be https://cdn.discordapp.com/attachments/205766705463427072/250051999024807946/unknown.png

replay should be https://cdn.discordapp.com/attachments/205766705463427072/250059414097100800/12895.png

**Comment by Javran** [comment]
@Tedster59 thanks for the data! it seems the battle data for node Q is not even recorded in that replay, this might be a case where KC3 doesn't recognize the API .. @dragonjet might have a better idea on this.

**Comment by fourinone41** [comment]
I got the API response from Sao-Link. http://pastebin.com/kTabx4yj
The response name we need to add is `api_req_combined_battle/each_battle_water`.

**Comment by Javran** [comment]
I just checked the data in detail and had it included in the test suite, the battle prediction itself works correctly. so we should be good to go when the handler is added.

**Comment by dragonjet** [comment]
added `battle_water` but I haven't tested it yet. hopefully an API recording would be nice if we can get it or teach those who reached the node on how to use it.

though I already scheduled the released tonight at 1am JST to have least number of people online. some still complain about auto-closing of the game when the app updates in the background.

**Comment by Javran** [comment]
found a bug: when main fleet is fully wiped, but there are remained abyssal in escort fleet, we should face escort fleet but the UI shows the main fleet instead. battleplayer works fine so which fleet we are facing should be contained in the battle data.

here is a replay for debugging: https://i.imgur.com/miyhDWi.png

**Comment by Javran** [comment]
bumping this issue, I reopened this long ago (see my last comment right above) but no one has yet responded

**Comment by sinsinpub** [comment]
UI issue should be fixed? as long as active_deck is refered to escort

**Comment by Javran** [comment]
maybe try simulating the replay in https://github.com/KC3Kai/KC3Kai/issues/1606#issuecomment-262710211 and see if it works? (would https://github.com/KC3Kai/kancolle-api-sim help in this case?)

**Comment by dragonjet** [comment]
oh sorry, the API sim cannot use the battle record from export. it has to be recorded via API recorder in panel. the main problem is that the IDs will reference player ship IDs not the masters so I don't have record of the shiplist and equiplist doing the battle.

**Comment by Javran** [comment]
I think we can close this issue for now, as 6-5 has an abyssal combined fleet node and no one has reported any problem alike so far. (I think regarding night battle-engaging API data, abyssal combined fleet works the same despite of whether it's 6 vs. 12 or 12 vs. 12)
