### ISSUE TITLE
Wrong subtitle (Fusou)

### ISSUE THREAD

**Issue by SubZero0** [KC3Kai/KC3Kai#1607]
One of Fusou's subtitles is probably wrong.
Subtitle: Yamashiro, let's do our best together.

But she starts saying "Teitoku"

**Comment by nonsensed** [comment]
It's one of the recent fall/autumn seasonal lines (even though it doesn't sound fall/autumnish at all). I've already adjusted that one, just gotta wait on the next kc3 update.
