### ISSUE TITLE
TP calculator needs to be updated for Toku Daihatsu

### ISSUE THREAD

**Issue by mikenzb** [KC3Kai/KC3Kai#1608]
There is no TP estimate on E1 (Fall Event 16) and I think it is because of the Toku Daihatsu I have on my Mutsuki, not a high priority fix as I think a lot of people can live without it but thought I would make an issue regardless.

I also have the recorded API data of the sortie if you need it, poke me if you need it.
![img](http://i.imgur.com/a4kLAGQ.png)

**Comment by sinsinpub** [comment]
Updated by 86d6da2 ... forgot to type `#` 😓
