### ISSUE TITLE
Pumping Sound Triggering Panic Attacks

### ISSUE THREAD

**Issue by Cashmerella** [KC3Kai/KC3Kai#1609]
I really appreciate the work y'all put into this helper app, but I'm having a problem possibly by own error. I've noticed since recently, when one of your girls is in red, it makes a blood-pumping noise and makes the screen flash red at the sides. I'm not sure if there's a way to but I can't figure out how to turn this off, if there's an option to do so. This sort of sound can easily give me severe panic attacks, but I really don't wanna turn off the helper, especially during an event. If there's an option to turn it off I'm probably missing it, could someone maybe help? If there isn't an option to turn it off, perhaps I could request one? I tried muting my tab and muting kancolle and the mute button in the helper top corner, but nothing gets rid of it. Thanks in advance!

**Comment by Tedster59** [comment]
There is options for this under the "annoying taiha alert" section in the settings window.  the option you are looking for is "heartbeat sound"

**Comment by Cashmerella** [comment]
Thank you very much! I feel so silly I missed that. I really appreciate it!
