### ISSUE TITLE
E3E Game Data Error

### ISSUE THREAD

**Issue by richarddoge8079** [KC3Kai/KC3Kai#1613]
- Your Chrome version - 54.0.2840.99 m
- Your OS - Win 10 Pro 64bit
- Your KC3 Kai version - 30.11.1 Webstore

![screenshot 972](https://cloud.githubusercontent.com/assets/19426598/20457376/ee0ed572-aec4-11e6-86be-ae047d726510.png)
![screenshot 973](https://cloud.githubusercontent.com/assets/19426598/20457377/f09ab8ce-aec4-11e6-8eea-e7f1bf4af891.png)

Only occurs when going into Boss Node, both day and night battle result can't be displayed along with enemy pattern and hp.

**Comment by dragonjet** [comment]
12 v 12 prediction will be supported in 30.11.2 as fixed by @Javran in 7cb6753eb10741f47840aef24eb51f88e3db3e39
