### ISSUE TITLE
Interface all over the place.  

### ISSUE THREAD

**Issue by boreslayer** [KC3Kai/KC3Kai#1619]
- Chrome version: [54.0.2840.99 (Official Build) m (64-bit)]
- OS and its version [Windows 10 Build 14393]
- 32bit or 64bit? [64 bit]
- Your KC3 Kai version - via chrome://extensions/ [30.11.2]
- Which build you have tried running? [Webstore version]
- Screenshots which accurately paint the issue(s) you are facing. [https://gyazo.com/009d5f13e6b3f6d82601f6bd509cc8d5]

A step by step method that you did to describe how you got to that issue.
- [I just started the game and tried running some sorties.  The interface is just all over the place.]

**Comment by LostLogia4** [comment]
Looks like the same symptom as #1592
