### ISSUE TITLE
[Feature request]Adding "Requirement for improment weapon" in Akashi improvement weapon tab.

### ISSUE THREAD

**Issue by Ensoreave** [KC3Kai/KC3Kai#1621]
First of All. Thanks you for your effort for doing this great Plugin. 
It very smooth to use and update is very fast.

Back To the story ... I think I want to tell my through.
When I using strategy to looking for item that can improve weapon in that day, I found that it tell which one you can or can't but I don't find what is using for improvement. That make I always need to check wiki.
So I think that it maybe good if author can adding one of this

[Most that If can ... it will very useful] telling which item have improvement level and what require
EX. 
12.7mm            akashi    
Weapon                    | rank | Number you have | Requirement for next rank             | change to
12.7mm                    |   10  |              2             |   3/6 improve material / 2 * 12.7    | 12.7 type B
12.7mm                    |   3    |              1             |   1/2 improve material                   |         -
12.7mm                    |   0    |             14            |   1/2 improve material                   |         -
..........
10cm+Fire Director    akizuki
Weapon                    | rank | Number you have | Requirement for next rank             | change to
10cm+Fire Director   |   4    |               1            |   3/4  improve material                  |         -
..........

[Lower than first sample but maybe easier to coding] Only tell what it want at the back of Ship requirement to improve weapon
EX.
12.7mm            akashi            0-5   ..... 1/2 improvement material
                                              6-10  ..... 1/2 improvement material / 12.7mm *1
                                               10+  .....  3/6 improvement material / 2 * 12.7[Change to 12.7 type B ]
.............

[And last and easiest method] Add data requirement to improvement weapon into help link

Lastly ... I just telling my through. And it isn't thing that I require that hardly. So if author think it will be great and having free time[that not make you headache too much with time or code ...], please fell free to use this suggestion to add some function or improvement.

thanks for reading ... and sorry if my English isn't good enough
p.s. sorry if there anyone have suggest something like this before or wrong with the rules [Or your rules]

**Comment by KyungwhaPark** [comment]
I'm hoping to see this feature in next version update.

I have to search through Kancolle Wiki to find out how many Screw bolts needed

**Comment by LostLogia4** [comment]
I think it should be added as part of the [Akashi Improvement Planner](1183)
