### ISSUE TITLE
Screenshots coming out as completely black

### ISSUE THREAD

**Issue by Byakushiki** [KC3Kai/KC3Kai#1623]
- Your Chrome version - via chrome://version/
  Version: 54.0.2840.99 (Official Build) m (32-bit)

- Your OS and its version
  Windows 8.1

- 32bit or 64bit?

  64-bit
- Your KC3 Kai version - via chrome://extensions/

  Version: 30.11.3
- Which build you have tried running? webstore version as in the one from [Chrome Web Store] 

  Webstore version
- Screenshots which accurately paint the issue(s) you are facing.

![](http://i.imgur.com/cuKtjhL.jpg)

- A step by step method that you did to describe how you got to that issue.
  
I am playing the game normally and just pressing the screenshot button to get screenshots. I didn't check them since I thought they would come out like they usually do as you can see from the earlier screenshots, but all the recent ones have been black.

Edit: Wanted to add that restarting the game, restarting chrome, restarting my computer, and uninstalling/reinstalling KC3 has made no changes. Screenshots are still coming out completely black.

**Comment by dragonjet** [comment]
encountered this will doing the "special dmm mode" but the feature branch at the time included "to-be-expected" broken feature as capturing screenshots via frame is different from the direct DMM injection.

**Comment by Nya-chan** [comment]
This is probably fixed now via fixing the branching.

**Comment by mikenzb** [comment]
^ Probably fixed with the new dmm game mode in KC3 version 31, reopen if issue still persists.
