### ISSUE TITLE
HP bar on UI for 12 vs 12 battles looks weird

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#1624]
Here is what I saw on the HP bar:
![2016-11-22_213803_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/20549689/a9ceb550-b0fc-11e6-91ea-0dd0067d2731.jpg)

it seems the HP bar value doesn't change, despite its color being green / yellow / red.

my replay for debugging http://i.imgur.com/O40GjGC.png  I've tried `DamagaAnalysis.analyzeXXXX` and the result looks fine.

**Comment by Javran** [comment]
also think it might be helpful to indicate which fleet will player face in the night battle, since we already have a "night battle" icon on interface, we might consider re-using that.

**Comment by Tedster59** [comment]
@Javran Right now, there seems to be an "off-by-one" error in the escort fleet.  note how the escort flag HP bar is grey.  

also, in this battle, note the prediction:
https://cdn.discordapp.com/attachments/205766705463427072/250530883126165504/bossupport.PNG

At the end of said battle, Ancient DD Princess was alive
https://cdn.discordapp.com/attachments/205766705463427072/250530939434696705/Tedster59_2016-11-22_02-59-43_96.png

**Comment by sinsinpub** [comment]
i found some mistakes(typo?) causing the grey bar.

what's the idea detail about "night battle" icon...? u mean show a tool-tip saying: Night battle will be facing enemy Escort(or Main) fleet?

**Comment by sinsinpub** [comment]
... auto closed by github.
Grey bar issue tested on my side (E3 CTF), feel free to reopen this if other discussion would be continued.

**Comment by mikenzb** [comment]
afa336e seems to have caused some API issues for me again on E5 combined fleet vs combined fleet nodes on O and T.
![capture](https://cloud.githubusercontent.com/assets/5982780/20561717/cb8cc0e0-b1e4-11e6-9116-4b65f983bbae.PNG)
![capture](https://cloud.githubusercontent.com/assets/5982780/20561721/d43b9612-b1e4-11e6-955c-a3fecdca99dc.PNG)

**Comment by sinsinpub** [comment]
@mikenzb found reason, fixed at e331edf

**Comment by Javran** [comment]
@sinsinpub about that night battle icon thing, will open a separate issue for it.
