### ISSUE TITLE
Can't Open KC3 Via API Link

### ISSUE THREAD

**Issue by zika1307** [KC3Kai/KC3Kai#1625]
Excuse Me, I Want Now To Solve This Problem ... :"3

- [ ] My Current Chrome version
Version 54.0.2840.99 m (64-bit)

My Current OS and its version
Windows 8.1 Enterprise

- [ ] 32bit or 64bit?
64-bit

- [ ] My Current KC3 Kai version - via chrome://extensions/
Version 30.11.3

- [ ] Which build I have tried running? webstore version as in the one from [Chrome Web Store]
Webstore Version

- [ ] Screenshots which accurately paint the issue(s) you are facing.
![2016-11-23 10 55 19](https://cloud.githubusercontent.com/assets/23690773/20550030/9cc61a54-b16c-11e6-8dd0-c4028a0c8d28.png)

- [ ] A step by step method that you did to describe how you got to that issue.
I've Been A Month I Think Since The Last Time I Open This Game. But I Can Open It Via DMM Website, So I Don't Know What is Wrong Right Now That Why I Can Open It Via API Link Now o_oa
Hope You Can Help Me :'3

#thank_you

**Comment by mikenzb** [comment]
"Explanation is already on the screen. Please read the message on the red box"

Find more info here #1549
