### ISSUE TITLE
API error using carrier support on E4-V boss node

### ISSUE THREAD

**Issue by Amelek** [KC3Kai/KC3Kai#1632]
Version 30.11.3

That battle predictor fails with API error when carrier support fleet is used on 6v12 combined fleet node.

I got the bug yesterday on my final clear of the E4, but did not thought enough to make a screenshot :(

**Comment by dragonjet** [comment]
thanks for the report is the problem related so the escort fleet HP bars, where it seems one of them is gray HP bar and the other enemies look like the bars are offset by one?

**Comment by Amelek** [comment]
No idea, maybe. Offset bug just causes the enemy HP to be slightly wrong, but otherwise the battle predictor works fine. This one displays red api error message box (similar to one you get after kc3 updates in background) and no battle prediction at all.

Sorry if I wasn't clear in my original post

**Comment by dragonjet** [comment]
seems to have been fixed in the patches around event time. I used the prediction during E-5 clearing in the last days of event and didn't get the errors on 6v12
