### ISSUE TITLE
Transport ships in Abyssal escort fleet are not counted

### ISSUE THREAD

**Issue by LostLogia4** [KC3Kai/KC3Kai#1637]
### Steps to reproduce
1. Kill transport ships in escort fleet in Node A. (I'm at 17 kills when the bug is discovered)

### Expected behaviour:
The killed transport ships are correctly recorded into the quest counter

### Actual behaviour:
The transport ships in escort fleet are not counted towards the quest counter. It is counted towards quest completion in game.

### Screenshots (if applicable):
![transport0](https://cloud.githubusercontent.com/assets/12930396/20669178/a8ed1ee6-b5ad-11e6-8a36-1f4a22945f91.png)
![](http://i.imgur.com/K5AWqMz.png)
![](http://i.imgur.com/VSJYX1C.png)

**Comment by sinsinpub** [comment]
are u using dev master branch? iirc I have fixed it

**Comment by LostLogia4** [comment]
Seems like I'm using the webstore version. Guess I'll wait it out.
