### ISSUE TITLE
Chrome Version 55: Black screen

### ISSUE THREAD

**Issue by arialypse** [KC3Kai/KC3Kai#1641]
Chrome version - 55.0.2883.75 m (64-bit)
OS Windows 10/1511 64bit
KC3 Kai version 30.11.3

I can play game in DMM or API as usual. but  DMM Frame got Black screen

![v55](http://i.imgur.com/AAjdDgc.png)

**Comment by sinsinpub** [comment]
55 totally owata/ 😭 
only dmm site works thanks to same domain. api not work for web request / network monitoring (even viewing elements inside iframe with devtools not allowed), dmm frame even black the flash player with its shit html5 stuff

**Comment by dragonjet** [comment]
R.I.P. KC3 :joy_cat:

**Comment by dragonjet** [comment]
the only idea I can think of is to execute the old plan where we inject styles and overlays onto the DMM website itself - so no more iframes. everyone visites DMM gameplay page directly and they get the cropped screen with custom background etc.

**Comment by Javran** [comment]
sorry but I don't understand what's going on, is new version of chrome applying some new awkward mechanism of security, or dmm has figured out how to prevent user from using devtools or something? I haven't run into this problem but it seems everyone else is experiencing it...

**Comment by HitomaruKonpaku** [comment]
@Javran I think its chrome problem. Try update your Chrome to ver 55

**Comment by dragonjet** [comment]
on chrome 55 now on stable channel of releases, playing via DMM frame now only shows black screen. playing via API link works, but the devtools do not detect the network requests and stays in the "waiting for game actions" screen. it's just chrome problem though, no DMM intervention

**Comment by HakenBrowning** [comment]
Hello, just to confirm it's not only Chrome problem. Using latest vivaldi snapshot (based on Chromium 55.0.2883.64), 2 main problems : 
- devtools not detected by game window
- when launching "Play on Frame", only white screen but sounds play too, so game only invisible.

**Comment by arialypse** [comment]
I was recommended my team to use Chrome Portable for now if v54 still worked
just use separately from normal Chrome for playing KC only

http://portableapps.com/apps/internet/google_chrome_portable

**Comment by DynamicSTOP** [comment]
@HakenBrowning 
> Using latest vivaldi snapshot (based on Chromium 55.0.2883.64), 2 main problems

try this:
go to chrome://flags/ 
1) disable replace flash with html
2) enable always run flash

Not sure about vivaldi but it works in Chromium 57.0.2940.0

**Comment by dragonjet** [comment]
@DynamicSTOP is that the "Prefer HTML over Flash" option?
chrome://flags/#prefer-html-over-flash
I tried this on 55 and still doesnt work

**Comment by dragonjet** [comment]
for this, we will be adding a "Special DMM Mode" as a new gameplay options. This customizes the DMM website directly, not enclosed in any iframe: #1645

**Comment by arialypse** [comment]
After game update today
Chrome 55.0.2883.75 m (64-bit) is worked with 30.12.0
???

**Comment by dragonjet** [comment]
still black screen for me though :(

Version 55.0.2883.75 m
stable chrome

**Comment by myrrhmidon** [comment]
Works fine for me too with latest chrome build 55.0.2883.75 m (64-bit)
proof: http://imgur.com/a/53FtQ

**Comment by mikeyblitz21** [comment]
Tried it right now, it works. 
![screenshot 44](https://cloud.githubusercontent.com/assets/20335976/21057919/954a77ea-be76-11e6-941e-d4685d86d240.png)
![screenshot 43](https://cloud.githubusercontent.com/assets/20335976/21057920/9550e508-be76-11e6-986d-7b6223e0d4e7.png)

**Comment by nicolas22g** [comment]
I confirm that API Link rework on Chrome.
Kc3 kai version 30.12.0
Chrome version 55.0.2883.75 m
Weird, I change nothing on my browser. I was using Chronium for Kancolle.

@dragonjet Did you reset the flash flags on Chrome? Or did they still enabled? Mine are default

**Comment by HitomaruKonpaku** [comment]
Confirm it work with API link
KC3 Kai Version 30.12.0
Chrome Version 55.0.2883.87 m (64-bit)

But i still waiting for the new update xD

**Comment by dragonjet** [comment]
The Chromium Issue: ([Post in Facebook page](https://www.facebook.com/10154371097262730))

## Mini-FAQ

### What was the problem?
Chromium has a new security feature called [OOPIFs (Out-of-Process iframes)](http://www.chromium.org/developers/design-documents/oop-iframes). In short, this mechanism restricts cross-site rendering by separating browser process. This means our extension at `chrome-extension://xxx` cannot render elements from any other site, in this case, DMM. 

### Why was it fixed in my Chrome 55?
Chrome stable release **55.0.2883.87** has an update which turned off the mechanism by default. This can be toggled in your chrome flags. Just type in your address bar the following URL:
```
chrome://flags/#enable-top-document-isolation
```
This will take you to a setting called "Top document isolation". In the previous Chrome 55 release, i.e. **55.0.2883.75**, this flag is **enabled** by default so we get the black screen.

### What can we expect moving forward?
We should still slowly move into the new mode, as this is an experimental flag in Chrome and still exists, they still plan to implement this in the future (means to enable by default).

**Comment by Javran** [comment]
so it's indeed yet another "security" feature of chromium, just making things more convenient for us.

**Comment by sinsinpub** [comment]
but there still question: why it works on dmm official site when iframe isolated despite of flash player inside gadgets' different domain (ip addr direct) iframe? 😅

**Comment by dragonjet** [comment]
likely because osapi is still under dmm.com domain, not exactly treated as cross-site

also, there is a special rule for chrome extensions specifically:
https://bugs.chromium.org/p/chromium/issues/detail?id=531810

**Comment by sinsinpub** [comment]
keep tracking at https://groups.google.com/a/chromium.org/forum/#!topic/site-isolation-dev/
and thread about the ninja patch: https://groups.google.com/a/chromium.org/forum/#!topic/site-isolation-dev/76HvK5DowwU
