### ISSUE TITLE
Ledger error after using LBAS

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#1644]
just cleared 6-4 and 6-5 today, and find Ledger in strategy room no longer works:

![2016-12-02_223720_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/20856573/eec32ebc-b8df-11e6-9017-d45832406c92.jpg)

everything is zero and I found following error message in console:

![2016-12-02_223808_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/20856578/096864e4-b8e0-11e6-996f-1d3a92b56913.jpg)

the line number might differ because I tried to troubleshot and added some code for debugging.
The line that error message refered to is https://github.com/KC3Kai/KC3Kai/blob/afdb3188bec8e5334850bf57288b5171546a4983/src/pages/strategy/tabs/overlodger/overlodger.js#L1022

I inserted some `console.log` messages, and found the error happens when `givenType` is a structure of the following:

```javascript
["lbas", "lbas", "", index: 0, input: "lbas"]
```

which then causes `givenAry = self.dataBuffer[givenType[1]]` to result in `undefined`.

I have no knowledge about how Ledger works. so I can't offer more help than providing more info on my side.

**Comment by sinsinpub** [comment]
anticipated... as lbas must be on its own type, ledger has to be updated...

**Comment by Javran** [comment]
I just applied a workaround by e4e7663, the LBAS data is skipped for now, to at least make Ledger usable.

@sinsinpub would you like to work on this? feel free to ask me for any info as necessary.

**Comment by sinsinpub** [comment]
i could try.
and i need to know if the resources consumed by resupply of lbas is counted as type 'sortie' or not. its type also needs to be defined.

**Comment by Javran** [comment]
@sinsinpub I have no idea, is there a command that I can put into my console to figure this out?

**Comment by LostLogia4** [comment]
It does counted towards the sortie category if we're fitting it in. That said, I would've preferred the LBAS consumptions to be in its own category if possible.

**Comment by sinsinpub** [comment]
hmm, new type of 'lbas' has been added, and new data will be counted towards this category.
but my old data seems not accuracy as I modify my IndexedDB so much...

there are a auto fixing codes (replacing all `sortie0` and `lbas` type to `lbas6`) at SRoom profile page, before open it and check the ledger, should stop(reopen) the game to save more wrong type data

**Comment by sinsinpub** [comment]
ps. it seems some ledger data typed as 'sortie0' (which consuming ammo/steel/bucket...) also replaced.

could use this at console to check if there is such data before open profile page:
```
KC3Database.get_lodger_data(Range(0,Infinity,0,1), function(t){t.forEach(function(b){ if(b.type.startsWith("sortie0")){console.log(b);} })});
```
