### ISSUE TITLE
Screen problem

### ISSUE THREAD

**Issue by Kel786** [KC3Kai/KC3Kai#1646]
After the new version released, my KC3 kai screen shown some problems. 

Before the new version released, it will go to dmm page first. However, it doesn't go to the page anymore now. Furthermore, the screen doesn't fit as shown in the screenshot below.

![1](https://cloud.githubusercontent.com/assets/24354589/20859448/9ec54efc-b99a-11e6-8403-ac403e032fb9.jpg)

The function is still normal but not all of them. The kanmusu line didn't translate and I can't screenshot as well. 

I tried to solve these problem by remove and reinstall it, close my chrome and reopen and restart my computer but it didn't help at all.

Can someone help me?

**Comment by wrinkledm** [comment]
Second that, I am having the same issue. I mentioned it on the Glitter chat window as well.  I checked through the settings menu and nothing jumped out at me either.

**Comment by dragonjet** [comment]
are you using "play via DMM website" or "play via DMM frame"? that's the expected bahavior for "play via DMM website"
