### ISSUE TITLE
picture for new planes?

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#1649]
just a reminder that in directory https://github.com/KC3Kai/KC3Kai/tree/master/src/assets/img/planes pictures for new planes (id > 189) are missing.

**Comment by dragonjet** [comment]
now that I think about it, are we breakign some rules by packaging these ripped images into the app?

**Comment by Nya-chan** [comment]
@dragonjet Not as long as you don't sell them or use them for a different game / product.
