### ISSUE TITLE
Suggestion:  Allow us to remove quests from the tracker

### ISSUE THREAD

**Issue by Gengarism** [KC3Kai/KC3Kai#1650]
The reason why I ask this is because I use two computers to play this game (both use this plugin).  When you accept and turn in a quest on one computer, it will pop up on the other and will not go away.  It will show itself as ready to be turned in, but obviously that cannot be done as in the game we've already completed it.

**Comment by Tedster59** [comment]
if you click the square on the kc3kai panel next to the quest, the quest will turn green and will be removed from the list the next time you enter the quest screen.  you can also remove them from the quests tab in Strategy Room
