### ISSUE TITLE
battle prediction with jet air assault

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#1652]
just an issue for collecting info about this new jet air assault phase.
so as always, any info is appreciated!

**Comment by LostLogia4** [comment]
```
        "api_injection_kouku": {
            "api_plane_from": [[1], [-1]],
            "api_stage1": {
                "api_f_count": 34,
                "api_f_lostcount": 0,
                "api_e_count": 0,
                "api_e_lostcount": 0
            },
            "api_stage2": {
                "api_f_count": 34,
                "api_f_lostcount": 0,
                "api_e_count": 0,
                "api_e_lostcount": 0
            },
            "api_stage3": {
                "api_frai_flag": [-1, 0, 0, 0, 0, 0, 0],
                "api_erai_flag": [-1, 0, 0, 0, 0, 0, 0],
                "api_fbak_flag": [-1, 0, 0, 0, 0, 0, 0],
                "api_ebak_flag": [-1, 0, 0, 1, 0, 0, 0],
                "api_fcl_flag": [-1, 0, 0, 0, 0, 0, 0],
                "api_ecl_flag": [-1, 0, 0, 0, 0, 0, 0],
                "api_fdam": [-1, 0, 0, 0, 0, 0, 0],
                "api_edam": [-1, 0, 0, 55, 0, 0, 0]
            }
        },
``

**Comment by Javran** [comment]
I've also just got some replay from @欧米嘉·风焰 on ngacn. will be working on this shortly.

**Comment by Javran** [comment]
update: jet assault support has been pushed to the lastest master branch. still need data in which jet comes from LBAS rather than cranes. (this case should have been dealt with and I just need a sample for confirmation)

**Comment by Javran** [comment]
I just collected data for jet assault from land base, tests have been performed and I see no need of changing anything on my part. I'll call this done.

for those interested in the data sample I collected, you can find them in https://github.com/Javran/purescript-kancolle-helpers/blob/ce8daad37f9ed481f3ff9736e1cd869698b0ba8c/test/BattleData.js#L1483-L1679

also want to give my thanks to @yukixz for sharing info regarding jet assault.

cheers!
