### ISSUE TITLE
Frame problem

### ISSUE THREAD

**Issue by lojzek91** [KC3Kai/KC3Kai#1653]
Hello!

I have Chrome version 55 and when I try to launch the game from Frame, it tells me that the service has been moved to Nutaku, with a button to press to redirect to Nutaku.

The problem is even worse because for some reason playing through the webpage is extremely slow lately, with disconnections being very common.

**Comment by lojzek91** [comment]
http://i.imgur.com/0h2Z2Uu.png

This is what it looks like.

**Comment by MegaAbsol** [comment]
Have you tried force cookie hack?

**Comment by lojzek91** [comment]
That helped. Thanks!
