### ISSUE TITLE
Subtitle error

### ISSUE THREAD

**Issue by nicolas22g** [KC3Kai/KC3Kai#1654]
There a error for Commandant Teste subtitle

Seem like Secretary 1 (Comment allez-vous ? ) and sinking lines are switched

![sans titre](https://cloud.githubusercontent.com/assets/14291618/21074424/30770b16-bef9-11e6-8a66-f16d903de97a.png)

**Comment by nonsensed** [comment]
She gonna turn back into an abyssal ship if you don't start loving her more. Don't say I didn't warn you.

Fixed in the translation repository, just gotta wait for the next kc3kai update.
