### ISSUE TITLE
wrong bauxite resupply cost in panel

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#1657]
the bauxite cost is correct only when all slots are filled with aircrafts:

![2016-12-10_225442_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/21077977/15079d9a-bf2c-11e6-94da-73473d065b2f.jpg)

![2016-12-10_225516_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/21077978/1794a1f2-bf2c-11e6-9b89-01180ac5d89e.jpg)

![2016-12-10_225652_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/21077979/1afbec1a-bf2c-11e6-8309-d3cace64e00e.jpg)

notice Katsuragi's full slot capacity is 18,21,27,3.

should be an easy fix just removing all condition checks in 
https://github.com/KC3Kai/KC3Kai/blob/c6cbfc5727275cd587bfe5fd9806f096460fc9ce/src/library/objects/Gear.js#L213-L217 but I'm not sure what was the concern regarding these checks.

**Comment by sinsinpub** [comment]
yep, it was thought that supply cost applied to equipped aircraft, but game mechanism is applied to slots only 😂 

and i'm interest in the fuel and ammo consume when send LBAS to sortie. it's appreciated if watching their change when sortie with LBAS specially for some slot of squadrons not full supplied (<18 or sth)
