### ISSUE TITLE
Air denial/incapability confusion?

### ISSUE THREAD

**Issue by LostLogia4** [KC3Kai/KC3Kai#1658]
I really should've asked about this since a year ago, because this term has been swapped from day 1 when KC3Kai came out. In fact, I'm surprised that this thing had went unreported for nearly two years.

AD = Air Denial (enemy have more favorable position in air battle, but doesn't have full dominance)
AI = Air Incapability (enemy have full dominance of the skies)

Both [Wikipedia](https://en.wikipedia.org/wiki/Air_supremacy#Types) and [Kancolle Wiki](http://kancolle.wikia.com/wiki/Aerial_Combat#Fighter_Combat) have stated as such, so I'd say KC3Kai was in the wrong in that regard,

**Comment by dragonjet** [comment]
Back then, it was denial at bottom, incapability above it

http://kancolle.wikia.com/wiki/Aerial_Combat?oldid=503702#Fighter_Combat

**Comment by LostLogia4** [comment]
Man I should've corrected it back then... guess it's high time we correct this in this extension.

**Comment by dragonjet** [comment]
@KC3Kai/translators need to update your `battle.json` so that the air battle section is

```
"airbattle" : [
	["AP", "", "Air Parity"],
	["AS+", "good", "Air Supremacy"],
	["AS", "good", "Air Superiority"],
	["AI", "bad", "Air Incapability"],
	["AD", "bad", "Air Denial"],
	["None", "", "No Air Battle"]
],
```
incapability first, then denial last
