### ISSUE TITLE
[API Help] `api_get_member/useitem` Usable Items ID analysis

### ISSUE THREAD

**Issue by sinsinpub** [KC3Kai/KC3Kai#1659]
Trying to analyze the items inventory (see http://kancolle.wikia.com/wiki/Shop) which could be get from API `api_get_member/useitem`. ~~but not found in our repo or online yet...~~ it's in master data, `useitem` with ID, jp name and description.
~~it's appreciated if someone could give a database url, or paste his inventory screenshot and the json of `api_useitem` (can be found at game start of `api_get_member/require_info`, or after using some items, such as furniture boxes)~~

Current result based on my account:
```
				switch(thisItem.api_id){
					case 10: PlayerManager.consumables.furniture200 = thisItem.api_count; break;
					case 11: PlayerManager.consumables.furniture400 = thisItem.api_count; break;
					case 12: PlayerManager.consumables.furniture700 = thisItem.api_count; break;
					case 52: PlayerManager.consumables.fairy = thisItem.api_count; break;
					case 54: PlayerManager.consumables.mamiya = thisItem.api_count; break;
					case 56: PlayerManager.consumables.chocolate = thisItem.api_count; break;
					case 57: PlayerManager.consumables.medals = thisItem.api_count; break;
					case 58: PlayerManager.consumables.blueprints = thisItem.api_count; break;
					case 59: PlayerManager.consumables.irako = thisItem.api_count; break;
					case 60: PlayerManager.consumables.presents = thisItem.api_count; break;
					case 62: PlayerManager.consumables.hishimochi = thisItem.api_count; break;
					case 64: PlayerManager.consumables.expansion = thisItem.api_count; break;
					case 68: PlayerManager.consumables.pike = thisItem.api_count; break;
					case 69: PlayerManager.consumables.mackerel = thisItem.api_count; break;
					case 70: PlayerManager.consumables.skilledCrew = thisItem.api_count; break;
					case 74: PlayerManager.consumables.newAircraftBlueprint = thisItem.api_count; break;
					default: break;
				}
```

**Comment by LostLogia4** [comment]
They're the same as their useitem ID. I've personally confirmed this with the links.

[65](http://203.104.209.71/kcs/resources/image/useitem/card/065.png) is Prototype Flight Deck Catapult.
[66](http://203.104.209.71/kcs/resources/image/useitem/card/066.png) is Combat Ration
[67](http://203.104.209.71/kcs/resources/image/useitem/card/067.png) is Underway Replenishment
[71](http://203.104.209.71/kcs/resources/image/useitem/card/071.png) is Ne-type Engine
[72](http://203.104.209.71/kcs/resources/image/useitem/card/072.png) is Decoration Material
[73](http://203.104.209.71/kcs/resources/image/useitem/card/073.png) is Construction Corps

**Comment by sinsinpub** [comment]
thx. but i confirm that ration & replenishment are not in `api_useitem` list, although we know their IDs

**Comment by dragonjet** [comment]
will this be something like a tab in strategy room where he can see all this items?

**Comment by sinsinpub** [comment]
that also feasible, to add a page in SRoom, TLed json from master and more works needed  
but just list out all the items without more info seems lack of strategy 😄

**Comment by LostLogia4** [comment]
ah that, it's partly because they're actually equipable items. We might as well keep them in jic they're actually given as items.
