### ISSUE TITLE
Off by one error in leveling goals in panel

### ISSUE THREAD

**Issue by MegaAbsol** [KC3Kai/KC3Kai#1661]
Since the experience bar updates after the battle has ended but the "battles left until goal" number shows up before this, the "battles left until goal" is off-by-one.

![image](https://cloud.githubusercontent.com/assets/10118751/21080800/72afedd0-bf86-11e6-879d-f7cec896cf84.png)

1-5 FS+MVP gives 540 exp, ceil(4752/540) is indeed 9 (goal is level 60). However, the experience bar has not yet updated to reflect the 540 experience that was gained during this battle.

![image](https://cloud.githubusercontent.com/assets/10118751/21080805/b166f974-bf86-11e6-877c-47f99aada973.png)

So the number that should be displayed should always be one less than is displayed.

Not sure if this was intentional or not. It's not really a big problem, it just sort of bugged me.

**Comment by dragonjet** [comment]
thanks for noticing and reporting this :+1: 
it wasnt intentional and your expected behavior is correct
