### ISSUE TITLE
Can't play kancolle 

### ISSUE THREAD

**Issue by bismarck0232** [KC3Kai/KC3Kai#1662]
- Your Chrome version - 54.0.2840.99
- windows 10 home
- 64bit
- Your KC3 Kai version - 30.12.1
- Which build you have tried running? webstore version
- Screenshots which accurately paint the issue(s) you are facing.
- A step by step method that you did to describe how you got to that issue.

### Versions: KC3: 30.12.1
chrome: 54.0.2840.99
OS: Windows 10 home

### Steps to reproduce: 
click  Kancolle command center in top right corner 
click play via DMM on frame
press F12
click chevron then Kancolle
on left side it say "this service has been moved to Nutaku.com on right side says waiting for game actions..." (screenshot 1)
click Nutaku.com new window opens to differnt website (screenshot 2) 

### Actual behaviour:
new window opens to different website can't figure out how to play

### Expected behaviour:
to be able to play the game

### Screenshots (if applicable):

![capture](https://cloud.githubusercontent.com/assets/24511627/21083024/9e09eeac-bfb5-11e6-877d-4ca67ed0d1e4.PNG)
![capture](https://cloud.githubusercontent.com/assets/24511627/21083026/a0e8ed9e-bfb5-11e6-89f4-aca0d763bf82.PNG)
![capture2](https://cloud.githubusercontent.com/assets/24511627/21083027/a3d22d86-bfb5-11e6-969e-c139aaac4d1f.PNG)

**Comment by mikenzb** [comment]
Go into the settings of KC3 and enable force cookies hack.

**Comment by dragonjet** [comment]
@mikenzb's suggestion fixes this 99.9% of the time. closing this until OP informs that it persist after enabling the feature and restarting browser.

**Comment by bismarck0232** [comment]
well i did the force cookies hack and it asked me to log in which i did but then it took me to yet another website

**Comment by bismarck0232** [comment]
never mind it worked thanks

**Comment by bismarck0232** [comment]
ok it brings up kancolle and when i click the big red button it takes me to a website in Japanese and when i click the English button at the top it takes me back to the nutaku thing

**Comment by dragonjet** [comment]
@bismarck0232 is it possible that this is your first time opening the game?

**Comment by Tedster59** [comment]
You can not have the DMM website set to english when you are using the cookie hack.

**Comment by bismarck0232** [comment]
the whole point of getting the extension was so it would be in english

**Comment by dragonjet** [comment]
@bismarck0232 you just need to have Japanese language selected on DMM website, not the game. We even put on screen quest translations for the game itself, and even subtitles. This is a technical limitation that you need to have Japanese DMM, the embedding website on Japanese.

This is the checklist to be able to make it work:

* Player must have Japanese language selected for DMM
* Player must have the cookies enabled in the browser
* It must not be the player's first time to play kancolle. There is a registration process where you need to input your nickname and the like, and that process is not supported by this extension, and must be done on the website first.
* Player must have correct computer/system time
* Although not required, but for dire circumstances, player must have "Force cookie hack" enabled in KC3 Kai settings

**Comment by Tedster59** [comment]
@bismarck0232 basically what dragonjet said.  you will not see the japanese part of DMM while playing this game unless you decide to spend money on it (and while registering).

**Comment by Nya-chan** [comment]
Can be closed, the user was on a wrong site that doesn't work with the extension.

Though, upon reconsidering - would we be able to recognize it somehow and let the user know that he should switch the language and relaunch the extension? I've seen this like once or twice more around.
