### ISSUE TITLE
Fleet Manager: eLos incorrect

### ISSUE THREAD

**Issue by arialypse** [KC3Kai/KC3Kai#1665]
Fleet Manager: eLos incorrect when view load save from Sortie History

Chrome version - 55.0.2883.87 m (64-bit)
OS Windows 10/1511 64bit
KC3 Kai version 30.12.1

Current Fleets show 33.95
![33.95](http://i.imgur.com/KL8RTBO.png)
![33.95](http://i.imgur.com/6zD9TOR.png)

but when load save from Sortie History elos it show only 24.26

![24.26](http://i.imgur.com/mZLXkYL.png)
![24.26](http://i.imgur.com/E89gW1j.png)

**Comment by sinsinpub** [comment]
known issue. just see FAQ in Help Topics
