### ISSUE TITLE
Suggestion: battle replay text version?

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#1667]
I'm not a 航海日誌 user, but someone else suggested if it is possible to have a text version of battle replay just like 航海日誌 did? we currently have a battle replayer for literally just replaying the whole animation, the point here is to also have a text version which would be more convenient for technical analysis.

**Comment by Javran** [comment]
@LostLogia4 sure, I think this should be quite close despite I haven't seen the counterpart in 航海日誌. so there are existing tools for this?

**Comment by LostLogia4** [comment]
No, I have no knowledge of such a tool. Seems like we'll have to build one from scratch.

**Comment by Javran** [comment]
I feel this could be a separated project just like our replayer.

**Comment by LostLogia4** [comment]
We could start by forking [kancolle-replay](KC3Kai/kancolle-replay), or at least use it as reference.

**Comment by fourinone41** [comment]
You probably shouldn't add the text generation to the animation code.....it's messy enough as it is, hah. Plus I think printing it all out at once is closer to the original request.

I went ahead and made a prototype, you can see it in `playertext.js`. You can run it by doing `processText(API)` in console on [the replay page](http://kc3kai.github.io/kancolle-replay/battleplayer.html) after loading a replay. We can give it a section on the replayer page or just make a new page for it. If you guys want you can take over from here, otherwise I can probably just fill out the rest eventually.

**Comment by Vultren** [comment]
I'm going to try my hand in this. is there a place that has the meaning of all the json fields like api_midnight_flag and api_hourai_flag?

**Comment by Javran** [comment]
@Vultren https://github.com/andanteyk/ElectronicObserver/blob/master/ElectronicObserver/Other/Information/apilist.txt is usually a good bet.

**Comment by Vultren** [comment]
@fourinone41 Started linking up the text to the player. How's this for starters:
![image](https://cloud.githubusercontent.com/assets/10458410/24313149/2258d8ba-10b2-11e7-89c1-307b190a8eb3.png)
Only works for PVP right now.

**Comment by LostLogia4** [comment]
Why only PvP tho? 😮

**Comment by Vultren** [comment]
because it's only one battle. starting small and working my way up. That and before I added the tabs, there was quite a bit of text to go through

**Comment by LostLogia4** [comment]
Yeah, that was a freakin' lot of text in there... 💦

**Comment by Vultren** [comment]
that's just for optorp, shelling 1&2, and closing torp. Air phase, I haven't had much time to do due to Master's classes, but it is probably the harder phases to write (only have phase 3 done). I got to find a LBAS battle next

**Comment by Vultren** [comment]
Well then, tried to test the text version on a combined fleet and ended up with 2 BBs and Hiyou doing opening torpedoes. gotta re-code it again

**Comment by mikenzb** [comment]
Has been implemented, Will close for now.
