### ISSUE TITLE
Microsoft Surface 4

### ISSUE THREAD

**Issue by Wetworth** [KC3Kai/KC3Kai#1669]
Please make sure that you have these details on hand when submitting your issue/bug report as this will greatly speed up the issue triage process -- thank you!

- Chrome version [Version 55.0.2883.87 m (64-bit)]
- OS version [Windows 10 Pro 64bit]
- KC3 Kai version - Webstore [30.12.1]

I restarted the tablet earlier today. KC3 displayed a message that it may be unable to run with the latest version of Chrome. The program works fine. However, the Microsoft Surface Pen no longer interacts with KC3. It works in every other regard (other Chrome pages, other programs, Windows, etc.), will move the cursor over KC3, but cannot select anything. Must use the my finger or the track pad. 

I can't really provide a screenshot illustrating this.

**Comment by dragonjet** [comment]
Hi, I have a few questions
* Does it not interact with KC3 elements only, but you can play the game fine? Or is it the game that doesnt response to input?
* Does it work when playing via direct DMM website without KC3?

**Comment by Wetworth** [comment]
I can play the game using the touch screen with my finger, or with a mouse/track pad. So I have no problem actually playing the game. The pen highlights buttons and stuff (I imagine that's just the animation from when the cursor is placed over them) but I press and press, nothing happens. 

I never thought to log into the site to try from there. The same issue exists from DMM.com as it does in KC3.

**Comment by todkapuz** [comment]
This is a chrome problem, not a kc3kai problem. It exists on all flash applications in the latest stable build.  I submitted on there. Chrome canary (the bleeding edge version, non-stable) it has been fixed.. don't know when it will roll to normal stable chrome.  ( https://www.google.com/chrome/browser/canary.html ) .

**Comment by Wetworth** [comment]
OK, that's what I figured after I logged into the site and nothing happened. Thanks for the help.

**Comment by dragonjet** [comment]
thanks for shedding light into this. good to have noted in case others have similar reports :+1:
