### ISSUE TITLE
KC3 Strategy Panel dark theme issues

### ISSUE THREAD

**Issue by Accelyte** [KC3Kai/KC3Kai#1670]
### Versions:
- Chrome Version 54.0.2840.99 m (64-bit)
- Windows 10 Pro 64-bit
- KC3 Version 30.12.1 Chrome Web Store version
### Steps to reproduce:
Open the levelling tab in the strategy panel.
### Actual behaviour:
The colours do not match the dark theme, and are unreadable.
### Expected behaviour:
The bounding boxes and text boxes should be in grey; the text should be white, like the other tabs.
### Screenshots (if applicable):
http://imgur.com/a/M6ZfD

**Comment by dragonjet** [comment]
duplicate of #1571
