### ISSUE TITLE
6-2-F LoS

### ISSUE THREAD

**Issue by c933103** [KC3Kai/KC3Kai#1671]
The current value noted in kc3k nouse over value for 6-2-F is apparently 50, but according to https://docs.google.com/spreadsheets/d/1didHxkaXqGZ-ZyaupAlh4CE-mCO1g5t7oAnNIyeHMtc/edit?usp=drive_web it need to be less than 43 to be certain to get desired routing

**Comment by sinsinpub** [comment]
should suggest everyone to read wiki for detail values of their desired route, not just see kc3's 😺
