### ISSUE TITLE
Jet Plane bug ?

### ISSUE THREAD

**Issue by 2sugoi2die** [KC3Kai/KC3Kai#1672]
![kc31](https://cloud.githubusercontent.com/assets/24616595/21283862/e8dd8770-c44e-11e6-8d36-670bf616f042.jpg)
![kc32](https://cloud.githubusercontent.com/assets/24616595/21283863/f14fc706-c44e-11e6-9b19-d5c5d96834d8.jpg)

- [Version 55.0.2883.87 m ]
- [Window 10 pro ] 
- [64 ] 
- [30.12.1  ] 
- [webstore ] 
- [ everytime i equip jet plane this message appears and it keeps appearing every time i do anything]

**Comment by dragonjet** [comment]
duplcate of #1664
