### ISSUE TITLE
New formula for LoS

### ISSUE THREAD

**Issue by HKGPsy** [KC3Kai/KC3Kai#1673]
It has recently been clear that the effect of LoS on map campus is Map specific (perhaps node specific).
The formula is outlined here:
[Map specific 33 formula](http://ja.kancolle.wikia.com/wiki/%E3%83%9E%E3%83%83%E3%83%97%E7%B4%A2%E6%95%B5)

As described in the formula, there is a map/node specific parameter, Cn, which influences only the equipment LoS. The map specific parameter for 2-5 happened to be 1 and that is why the old 33-Los formula was accurate in 2-5. It explained why the same formula did not predict accurately in map 6-2. Using the new formula, we can now accurately predict the campus in World 6 and even event map, here is the reference:
[Original reference of new 33 formula](http://ja.kancolle.wikia.com/wiki/%E3%82%B9%E3%83%AC%E3%83%83%E3%83%89:887#23)
The Japaneses wiki has already included the map specific parameter and it is clearly the trend for campus prediction:
[Japanese wiki adopting the map specific 33 formula](http://wikiwiki.jp/kancolle/?%C3%E6%C9%F4%B3%A4%B0%E8#area2)

In response to this new discovery with clearly better performance, it would be nice if KC3Kai could adapt to the newest formula. Since the new formula is map specific, updating the new formula would imply a change to the panel and include option to pick a map specific LoS (or simply map specific parameter if more flexibility is preferred). I am looking forward to future updates, thank you very much for the great job in maintaining KC3Kai.

**Comment by sinsinpub** [comment]
https://github.com/KC3Kai/KC3Kai/pull/1663

is this meeting ur needs?

**Comment by HKGPsy** [comment]
Oh yes, exactly.
Sorry I didn't notice this issue has been addressed, my fault.
