### ISSUE TITLE
anti-torp bulge not showing evasion stat in library

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#1682]
supposed to have negative evasion stat, but it is not shown in the library:

![2016-12-22_064831_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/21424744/b6b2a286-c812-11e6-8402-3682906c8f9b.jpg)

**Comment by sinsinpub** [comment]
yep, all negative values are not shown 😂
