### ISSUE TITLE
In-app AS calculator

### ISSUE THREAD

**Issue by Agc0de6** [KC3Kai/KC3Kai#1683]
My idea is to create AS calculator as part of Strategy Room.

Two reasons behind this:
1st. English AS calculators [like this](https://a4b81641afe20619f5ed716627d72ef95dcd42d1-www.googledrive.com/host/0B37L_d6zeTfUS0puRTRFVml1czA/) are dead.
2nd. [Japanese AS calculator (original of previous one)](http://aircalc.net/) wasn't update from november. [Author](https://twitter.com/no1244/status/799786222881296384) said that he won't do this anymore.
Tanaka added too many aircraft and ships that could be used in calculator, so I think we should do this for our players' sake.

Sorry for my bad English.) As Verniy said, "Если что не так, кидайтесь тапками" ("If something is wrong, just throw slippers at me").

**Comment by Agc0de6** [comment]
UI interface sample (can be changed afterwards).
Player selecting ships from lists. White fields are for slot power of every ship.
Calculator gets list of plane that player have from Aircraft tab (Aircraft Profiency and improvement bonus are excluded for now).
Then player selecting map and expecting result for this map. Orange fields are here:
1st - for max EFP of the map,
2nd - for AA buffer,
3rd - for expecting AS+/AS,
4th - for real AS+/AS.
+-D shows the difference between values in 3rd and 4th orange fields.
And then calc showing result in green fields.
*can't explain properly*
![as_calc_scheme](https://cloud.githubusercontent.com/assets/14156630/21736286/615790fe-d491-11e6-8710-6306ce6dc710.jpg)

**Comment by Agc0de6** [comment]
# Requesting help for programming
*actually can't understand coding at all >.<*

**Comment by ethrundr** [comment]
@Agc0de6 you can actually mention @KC3Kai/developers to ping all devs :>

**Comment by Agc0de6** [comment]
@KC3Kai/developers, *requesting help for programming!*

**Comment by dragonjet** [comment]
oh the existing AS calculator websites are now, for the lack of term, abandoned?

**Comment by sinsinpub** [comment]
as I mentioned at [#1711](https://github.com/KC3Kai/KC3Kai/pull/1711#issuecomment-271156709), the hardest work is keeping updating the data about: every slots' capacity of all abyssal ships, encounter patterns of every nodes and every map.
I guess this is why they stopped to updating, rather than updating the algorithm of air power.

**Comment by dragonjet** [comment]
@sinsinpub is this data available through API? I guess we have received enough donations to bring back the kc3 servers if need be.

also if we don't need to show the "compare to enemy node" feature, I guess just calculating player AS is fine. if he wants to compare it to enemy, then another service or tool can provide real time info about enemy slot + encounter.

**Comment by sinsinpub** [comment]
@dragonjet not available in API ofc. Just get player AS is not enough, and that's already done... See the prototype picture, there is a "Map" selector. That means expecting compare player's AP with all enemy nodes' of that map (even if just max one), we have to get and update the enemy AP of that map at least (maybe just copy from wiki thingy).
My assumption is all detail things can be calculated accurately if all slots size and formation patterns of abyssal enemies are available.

**Comment by Agc0de6** [comment]
@sinsinpub I thought we can use maximum value of enemy AS in every map. Is it wrong?

**Comment by KagamiChan** [comment]
There's no such data. What will be known to us about AS, is enemy
slots(without counts for each slot though), total planes, total  shot
downs, and air control result(AS+, AS,etc), I don't know if I'm missing
something, but in a word information is limited and it is blackbox alike

Agc0de6 <notifications@github.com>于2017年1月16日 周一02:12写道：

**Comment by Javran** [comment]
I'm actually not sure why would this calculator be useful whereas you can simply just messing around with the actual in-game fleet and see fighter power on the panel. (maybe something like deckbuilder and fleet.moe will do the trick if we don't want to affect our actual fleet)

there are too many options to be dealt with, few examples:
- when 2 fighters can provide same fighter power, what else would user prioritize? evasion? LoS? firepower? having multiple ships complicates the matter further: we might want more FP on one ship but more evasion on the other.
- what if the user wants to save some bauxite and put non-aircraft equipment on the maximum slots?

besides, there are even more to worry about: LBAS configs, jets (as for now only cranes (K2A remodel) are capable of equiping them). I think the aircraft system of the game is getting to a point where telling a program what exactly does a user want takes no less time than letting users to figure this out themselves...

**Comment by KagamiChan** [comment]
Dispite the blackbox status, we can guess, or estimate the missing information with statistics , but that means heavy analyzing and data maintenance works, as mentioned above.

**Comment by dragonjet** [comment]
It would be easier for some if they didn't need to re-equip the items in game, looking for who had it back-and-forth in strategy room equipment list. also equipping especially when done many times has an annoying loading in-game.

it might help if we have an offline version where they can just drag-drop planes from a list into a ship to plan out their carrier loadouts

I'm also extending this idea with my own ideas from back then. you can lock planes into ships and be able to press an automatic, "choose slots for me" where best planes go to best slots depending on your carriers in fleet. there will be a minimum fighter power input, where excess will be swapped out for bomber planes.

**Comment by sinsinpub** [comment]
i guess the main purpose of 'calculator' is not only to arrange the fleet and equipment to see how much air power could be got, but also to compare with the abyssal's of the map to where wanna sortie, to see if 'AS(+)' could be got.

without that for now, we are able to arrange it in game and see AP at viewer, then open the known abyssal AP (via wiki or this [digest image](http://i.imgur.com/muDK4oF.png)), to finish comparing. it does not be convenient enough. 'offline' knowing AP requirement before sortieing is more useful for me :joy:

**Comment by Agc0de6** [comment]
Maybe we can use [this](http://kancollecalc.web.fc2.com/air_supremacy.html) calculator as reference?
