### ISSUE TITLE
Seasonal Ship Names in Library

### ISSUE THREAD

**Issue by Vultren** [KC3Kai/KC3Kai#1685]
I noticed that all of the Seasonal ship entries in the library weren't being translated. A bit of code scanning later and I saw that it was due to the prefix kanji not being translated. I did a bit of tinkering on the ship name reader and added a prefix regex loop to with the suffix one. The end result works for the most part though I need to test it a bit more to fix a few mistakes in the reading

![seasonal_example](https://cloud.githubusercontent.com/assets/10458410/21447084/39995980-c89d-11e6-86d4-d35796132c4a.JPG)

Here are all the prefixes  in the library that I found (en):

Prefix | Season 
-|-
Xmas | Christmas
浴衣 | Yukata
法被 | Akimatsuri Happi
秋刀魚 | Saury
夏 | Summer
夏2016 | Summer 2016
親子丼 | Oyakodon
買い出し | Shopping
梅雨 | Rainy Season
携帯 | Mobile
記念日 | Anniversary

Should any of these be changed?

**Comment by dragonjet** [comment]
updates like these are welcome, you can make a pull request if you want to integrated into the webstore versions :+1:

**Comment by Vultren** [comment]
Well then, after though the ship list, other than Summer Mikuma (being misspelled, it seems that the other seasonals aren't in the list. Ryuujou's is merged in her base swf file, but I don't see the others. I'll just push what I have and wait and see

**Comment by sinsinpub** [comment]
my server's Xmas... swfs are still all 404, how about yours?

**Comment by Vultren** [comment]
same

**Comment by Vultren** [comment]
Ok, I did a bit of searching and you won't find the Xmas swf files in those locations. Not sure if they were there before but I checked Tone's, Suzuya's and Kuma's main swf files and their Xmas CG are in there instead under id 17 and 19. should be the same for the others who have Xmas images.

**Comment by sinsinpub** [comment]
u sent a PR for translations repo, but where is the modification of Meta.js for main repo...?
if not ready yet, here is my patch for this:
```diff
diff --git a/src/library/modules/Meta.js b/src/library/modules/Meta.js
index 7ddc2c5..1da408c 100644
--- a/src/library/modules/Meta.js
+++ b/src/library/modules/Meta.js
@@ -155,6 +155,21 @@ Provides access to data on built-in JSON files
 					" zwei" : '_Zwei',
 					" drei" : '_Drei'
 				},
+				combinPrefix = [],
+				repTabPrefix = {
+					"買い物"  : 'Mitsukoshi_',
+					"Xmas"    : 'Xmas_',
+					"浴衣"    : 'Yukata_',
+					"法被"    : 'AkiHappi_',
+					"秋刀魚"  : 'Saury_',
+					"親子丼"  : 'Oyakodon_',
+					"買い出し": 'Shopping_',
+					"夏2016"  : 'Summer2016_',
+					"夏"      : 'Summer_',
+					"梅雨"    : 'Rainy_',
+					"携帯"    : 'Mobile_',
+					"記念日"  : 'Anniversary_'
+				},
 				repRes = null,
 				replaced = false;
 			// in here, the regular expression will read which one comes first (which mean, to be in the end of the name
@@ -162,9 +177,16 @@ Provides access to data on built-in JSON files
 			// the matched one, added to the combination stack (FILO)
 			// removing from the replacement table in order to prevent infinite loop ^^;
 			// if there's no match, it'll instantly stop and return the actual value
+			// used to replace prefix of seasonal, such as 'Summer Taigei'. so translate those end with '_', and keep necessary suffix space
+			while( !!(repRes = (new RegExp("^("+(Object.keys(repTabPrefix).join("|"))+").+$",'gi')).exec(bare)) ){
+				bare = bare.replace(repRes[1], "");
+				combinPrefix.unshift(this._ship[repTabPrefix[repRes[1]]]);
+				delete repTabPrefix[repRes[1]];
+				replaced = true;
+			}
 			// just translate the items start with '_' in ships.json, and keep the necessary prefix space
 			while( !!(repRes = (new RegExp(".+("+(Object.keys(repTab).join("|"))+")$",'gi')).exec(bare)) ){
-				bare = bare.substr(0, bare.length-repRes[1].length);
+				bare = bare.replace(repRes[1], "");
 				combin.unshift(this._ship[repTab[repRes[1]]]);
 				delete repTab[repRes[1]];
 				replaced = true;
@@ -180,8 +202,9 @@ Provides access to data on built-in JSON files
 					}
 				}
 				
-				this._cache[jp_name] = (this._ship[bare] || this._cache[bare] || bare) +
-					(combin.length > 0 ? combin.join("") : "");
+				this._cache[jp_name] = [(combinPrefix.length > 0 ? combinPrefix.join("") : ""),
+					(this._ship[bare] || this._cache[bare] || bare),
+					(combin.length > 0 ? combin.join("") : "")].join("");
 				return this._cache[jp_name] ;
 				// console.log("this._cache[jp_name]", this._cache[jp_name]);
 				// return this._cache[jp_name]; // being here means the jp_name is not cached. there's already a cache checker at the start of this function
```

btw, the Xmas SWFs are ready now after today's online maintenance :joy:

**Comment by Vultren** [comment]
Ah.. I was waiting for the the translation merge to go through before I push the merge on the Meta side. without the translation part it makes it look like certain ship are there twice. Let me go push it anyway

**Comment by Vultren** [comment]
Well I think this works, so I'm closing
