### ISSUE TITLE
[Bug] KanColle flash app not responding to mouse through "Natural DMM Site"

### ISSUE THREAD

**Issue by mignonette** [KC3Kai/KC3Kai#1689]
My Chrome had automatically updated to ver. 55 so I can't play KanColle through KC3 my usual way anymore ("DMM in Frame") and have to choose the "Natural DMM Site" 

- Chrome version: 55.0.2883.95
- OSX 10.9.5
- 64bit
- KC3 Kai version: 30.12.3
- I'm using the Google Store build of KC3
- A step by step method that you did to describe how you got to that issue:
Clicking the "Natural DMM Site" and then opening the Admiral panel to start it from there. The page itself loads fine and the flash app too. The "Start Now" button does not respond to my mouse, and can't be clicked. Doing the same, and just selecting "Just Play the Game Now" and then letting the page load results in the same. 

"Force Cookie Hack" is not checked. Adobe Flash for Chrome is up-to-date (Version: 24.0.0.186) and is set to "Always allowed to run" in Chrome's settings. The other buttons, like the ones below the flash app, can be hovered over and clicked just fine. Going to another DMM game from the KanColle page (Touken Ranbu), the flash app for that game also can't be interacted with (the buttons outside of the flash app can be clicked on though).

Restarting the computer didn't help.

**Comment by dragonjet** [comment]
the only similar bug reported was #1669 but on a different OS. @todkapuz then found it out to be a problem with Chrome, and seemed to be fixed in the canary releases.
