### ISSUE TITLE
Japanese Translations

### ISSUE THREAD

**Issue by dragonjet** [KC3Kai/KC3Kai#169]
Ah yes, we need help with this.

Interested translators may signup here by replying, or just go to [KC3改 dev blog](http://kancolle.wikia.com/wiki/User_blog:Dragonjet/KC3%E6%94%B9)

To get an idea of how this will go, [see this wiki article](https://github.com/dragonjet/KC3Kai/wiki/How-to-help-out#local-translations).

Although we're not yet giving a green light on translating so you'll have to wait for now xD

**Comment by bamboo3250** [comment]
Just to clarify, are we going to translate KC3Kai's UI into Japanese?

**Comment by dragonjet** [comment]
yes, that's the plan, via `\src\data\translations\en\terms.json`

**Comment by nicky008** [comment]
`\src\data\translations\jp\terms.json` done. #265
