### ISSUE TITLE
Flowchart: Retaining Quest Codes even after completion

### ISSUE THREAD

**Issue by dragonjet** [KC3Kai/KC3Kai#1691]
_Can you do something about not removing the Quest name tags after they have been finished? Well instead of replacing it with a check mark, you can just put a 'completed' tag after the quest name. XD_

_Since I check the chains especially since next week, all of the weekly quests will be reset and I wanna know if there are some monthy chain quests beside it so I can guess if completing that would lessen the days I need to complete the weeklies xD Iirc, weekly and monthly, it took me 4-5 days._

~Lorenz Acain on facebook

![15682838_1392755157442099_2026910348_n](https://cloud.githubusercontent.com/assets/557312/21473007/6ea01198-cb2f-11e6-87d6-55febd61cbc7.png)

**Comment by sinsinpub** [comment]
....? is there any difficult to see the code from tooltip?

**Comment by LostLogia4** [comment]
Tooltips are useful and all, but vital information such as quest ID should be made available at first glance rather than being kept hidden.
