### ISSUE TITLE
Suggestion: Strategy Room Screenshot

### ISSUE THREAD

**Issue by HitomaruKonpaku** [KC3Kai/KC3Kai#1693]
Hi

Can you guys add the screenshot button to the Strategy Room to capture full page? Maybe under Back to Top button.

Sometime I need to share my ship list with my friend but it take to long to take a pic and merge them into 1 pic

**Comment by sinsinpub** [comment]
recommend a screenshot tool for Windows: PicPick
a ship list exporting feature is under construction by @DynamicSTOP

**Comment by HitomaruKonpaku** [comment]
@sinsinpub since my screen resolution is 1366 x 768, the page is very long, i wonder that tool can screenshot full page?

Also I think about we can screenshot any page in Strategy Room, not only ship list

**Comment by DynamicSTOP** [comment]
@HitomaruKonpaku i have tried couple screenshot plugins but it looks like they work only with actual web pages, not plugin pages.
Something like [this](https://gist.github.com/DynamicSTOP/ae72262d1a20d1951df4269adffaf99c) might work. For the current downsides:
- it does not take into account width
- it does not take into account zoom
- it does not tested on hdpi

As for my plans i was planning to do something much more simpler then we have on strategy room page.

**Comment by HitomaruKonpaku** [comment]
@DynamicSTOP ya the plugins not work with chrome page, that is my problem.

And thanks for your js file, it works pretty good. Also I think [this](http://html2canvas.hertzen.com/examples.html) could help too.

Btw: Hope to see your thing soon xD Thanks again.

**Comment by dragonjet** [comment]
#1792 has option to export shiplist to an image in one click
