### ISSUE TITLE
Suggestion: same ship finder in Strategy Room - Ship List

### ISSUE THREAD

**Issue by atikabubu** [KC3Kai/KC3Kai#1694]
Hiyo!

Would it be possible to add an easy double finder, ie. you click a checkbox in the Ship List tab of the Strategy Room, and all the same ships (ie. three Nakas), including their remodels are shown separately? This would speed up the scrapping of stuff just a weeee bit..

**Comment by Javran** [comment]
will fitlering by heartlock, and then sorting by name do?

**Comment by atikabubu** [comment]
Heartlocking is a tedious task, especially if you're someone like me, who can't decide which ships to scrap to make some space (herp derp hoarding instinct). But that is a valid solution... kinda... 😛 
Also thanks for all those code drops lately, lol you're basically carrying this project.

**Comment by nonsensed** [comment]
Nahhhhhh, it's the trinity of dragonjet, javran and sinsinpub that are carrying this project. The community is much better off for all three of their efforts. In the last several months they've all done some pretty big things in kc3.

/off topic

**Comment by Nya-chan** [comment]
An idea for this (more of a self-note) - text field that filters ship name interactively.
