### ISSUE TITLE
[API Data Help] Looking for ship master data ID > 900

### ISSUE THREAD

**Issue by sinsinpub** [KC3Kai/KC3Kai#1699]
Looking for a method to complete ship of master data which api_id > 900.

Reason:

 * KC devs hold a server-side master ship data whose api_id range in (800, 997], representing the seasonal ship CGs. We can find them in `shipgraph` objects, which are referred in Picture Book API to load seasonal CGs.
 * But for client-side, `ship` master object is truncated at api_id: 900 for unknown reason. I guess they forget (or unable) to update the threshold to smaller value which should prevent seasonal ship data being leaked to client-side. That is a just 'bug', which client ship master data only hold partially seasonal CG data, the ones with ID > 900 are missing.
 * If our Ship Library would like to show up all the seasonal CGs, we have to complete the missing data by ourselves. This is related to #1685.

So I wonder if there is anyone or anywhere had ripped the ship data (ID>900)? If not, is this possible to manually construct the left 97 objects and append to given one? (seems a hard work 🤔 )

**Comment by sinsinpub** [comment]
To build 1 object manually, seems only `api_name`, `api_yomi` and `api_stype` are required to know.
For example, ID 900 is Mizhuho:
`{"api_id":900,"api_name":"記念日瑞穂","api_yomi":"みずほ","api_stype":16,"api_soku":5,"api_slot_num":2}`
And 901 is Xmas Naka, should be:
`{"api_id":901,"api_name":"Xmas那珂","api_yomi":"なか","api_stype":3,"api_soku":-1,"api_slot_num":-1}`
`api_soku`, `api_slot_num` may be useless for now. btw, I guess the ship info by downloading and viewing this seasonal CG swf file.

**Comment by dragonjet** [comment]
if it's not in api_start2, I don't know of any other way to get master. Seems we'll need to do it manually like whocallsthefleet db

**Comment by Vultren** [comment]
I've checked this out while looking for the seasonal translations. I was looking for Kuma and Tone Since Xmas Kuma and Xmas Tone Kai Ni wasn't in the api_start2 dump I took. their Seasonal CGs were in the base files. I actually haven't tried it after the season ended, but you may need to change the version number when using the image API call

**Comment by sinsinpub** [comment]
I manually built: https://gist.github.com/sinsinpub/29f874f2cb0ae101d55983c9b7b284fb

JP names are from [wikiwiki](http://wikiwiki.jp/kancolle/?%B4%CF%CC%BC%A5%AB%A1%BC%A5%C9%B0%EC%CD%F72#G_graphic), but some may be not matched with KC official's. For example, official `夏(Summer)XX` they call `水着(Swimsuit)`; `記念日` they call `春の花束`, etc.

**Comment by Vultren** [comment]
checking to see what @sinsinpub meant on my master dump (12-22-2016) and it does seem like the shipgraph does go past 900. The seasonals in mst_ship also start at 829, cutting off poor Pola. Also when did the Christmas CGs start working?

**Comment by sinsinpub** [comment]
@Vultren KC devs made online updating on these days, including tonight.

**Comment by sinsinpub** [comment]
it seems there is no opposition my crafted seasonal data for now. So @KC3Kai/translators could translate the left prefixes in `ship_affix.json` now.

Note: As there is already a reserved ship name `夏潮` in `ships.json` which conflicted with prefix `夏(Summer)`, so I changed the crafted name prefix from `夏` to `水着` for ship `Ushio` as a special case. `夏` of other summer ships are not changed.
