### ISSUE TITLE
[Suggestion] Display overall interceptor power on LBAS panel

### ISSUE THREAD

**Issue by HKGPsy** [KC3Kai/KC3Kai#1710]
In the current LBAS panel, the interceptor power are separated as against fighters and against bombers.

In practice, the more important features would be the overall interceptor power so that we can calculate how much we need to get a sufficient power for AS+ (e.g. 16 Autumn event E5). It would be convenient if this value is also displayed in the LBAS panel, thanks.

**Comment by sinsinpub** [comment]
this issue forgotten... it's implemented at #1848, released at #1899
