### ISSUE TITLE
[bug] Using pure fighter LBAS causes API error in predictor

### ISSUE THREAD

**Issue by Amelek** [KC3Kai/KC3Kai#1713]
As in title, nothing particularly hard to reproduce

1. Fill LBAS with fighters only
2. Use them (I was using 6-5 for this).
3. Api error will occur after battle start, and no prediction will be available.

"TypeError: Cannot read property 'api_e_lostcount' of null"

**Comment by sinsinpub** [comment]
Fixed at c0986c5 already
