### ISSUE TITLE
[Suggestion] dynamic min-max value for resource graphs

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#1717]
Resource graphs are not informative when resources are stockpiled exceeding certain amount.
This is my per day graph, these are almost straight lines and I can barely see the difference:

![2017-01-06_183130_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/21736398/6ae35d18-d43e-11e6-8290-f2ade7e0cac0.jpg)

my suggestion is to scale y-axis based on min and max value of the data we are rendering.

as a side question, what is the version of `Chart.js` we are using? I think it's outdated and perhaps we should bump its version and adjust the code accordingly. I want to make improvement related to resource graphs but sadly can't find the corresponding doc to refer to.

**Comment by Amelek** [comment]
Maybe it would be possible to create a relative graph? Even with dynamic scale, it won't help for items - for example, 200 screws vs 3000 instant construction relative graph will inevitably decay to current unreadable state

Also, it is a technical limitation that only single month is displayed? Given that kancolle works in monthly cycle due to extra operation reset, it would be great if we could see few more iterations (like 3 months) to compare the clear performance.

**Comment by sinsinpub** [comment]
seems it's Chart.js-1.0.x... no docs to be found online 😭

**Comment by Javran** [comment]
@sinsinpub yep, I used to think that a popular lib without a straightforward way of viewing past-version document was unbelievable...

**Comment by Javran** [comment]
not sure how the actual range is computed, but the graph becomes funny when you have stockpiled enough resources:

![2017-01-30_165102_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/22443278/5ac93124-e70c-11e6-99ed-9c9ddda2ffc1.jpg)

**Comment by dragonjet** [comment]
`src\pages\strategy\graphable.js`
we just need to make this false
`Chart.defaults.global.scaleBeginAtZero = true;`

**Comment by Javran** [comment]
@dragonjet just tried and that does look better, any concerns about setting it to `false` previously ?

**Comment by dragonjet** [comment]
there's no problem with setting it to false, but we might want to make it configurable, though I wouldn't recommend adding to global settings page since this is a view-only configuration that affects 2 pages

**Comment by Javran** [comment]
@dragonjet I think putting a toggle on UI will do. also we might need to bump chart.js first because the current one we are using is outdated and kind of unmaintainable as there's no way to find the document for this version..

**Comment by dragonjet** [comment]
ah sure, ill assign this to myself for now
