### ISSUE TITLE
[Discussion] Issue Label Reworks

### ISSUE THREAD

**Issue by ethrundr** [KC3Kai/KC3Kai#1730]
After looking back for the previous year regarding the issue labels, I do think we need to add/adjust few labels so it may meet its original meanings, as well as to align with our new policy regarding PR Reviews:

1. Add **type:priority** to indicate a priority issue all members should pay higher attention to and quickly solve it,
2. Rename **status:needs-correction** to **status:change-requested** to adhere with the GitHub Reviews.
3. Add **status:pending** to indicate that a current work (especially those that have been **status:WIP**-ed) for a issue/update is stalled or even dropped, so others may take over the work.
4. Rename **rework** to **status:rework**, **other** to **type:other**, **wiki** to **type:wiki** and **update_adjustment** to **type:update_adjustment**, just for standarized naming. So the only orphaned labels are **duplicate** and **wontfix**, which better to be left as is.

Also, I think it's a good practice if someone going to work on an issue reported assigns themselves to the issue. This is to make sure any other devs or reporters know who to address when testing the update or facing the same issue.

This is just my opinion tho. Any other opinion are welcomed before we actually do some changes to those labels.

**Comment by dragonjet** [comment]
true, our labels are not standardized atm, gonna add my input but in list form

* `status:needs-correction` can be removed, Github reviews shows this better with "request changes"
* `status:pending`, or possibly `status:shelf`(?) but either is fine
* rework though is a type, so probably `type:rework`, others I agree

add:
*  `ready-for-merge` can also be removed, GitHub approvals does this better
* `status:testing` for me, can be named to `status:review` to let us know it's done with coding

**Comment by ethrundr** [comment]
Will update the labels accordingly later at night, when my connection is better :>
