### ISSUE TITLE
I get Fatal error when loading {0} TL data of {1}: {2} Contact developers plz! >_<

### ISSUE THREAD

**Issue by Reddo-KanColle** [KC3Kai/KC3Kai#1732]
Please make sure that you have these details on hand when submitting your issue/bug report as this will greatly speed up the issue triage process -- thank you!

- [ ] Your Chrome version - via chrome://version/
- [ ] Your OS and its version
- [ ] 32bit or 64bit?
- [ ] Your KC3 Kai version - via chrome://extensions/
- [ ] Which build you have tried running? webstore version as in the one from [Chrome Web Store](https://chrome.google.com/webstore/detail/kancolle-command-center-%E6%94%B9/hkgmldnainaglpjngpajnnjfhpdjkohh) or Github variant (better known as developer builds).
- [ ] Screenshots which accurately paint the issue(s) you are facing.
- [ ] A step by step method that you did to describe how you got to that issue.

**Comment by dragonjet** [comment]
`git submodules update --init`
