### ISSUE TITLE
LBAS / Jet consumption testing request

### ISSUE THREAD

**Issue by sinsinpub** [KC3Kai/KC3Kai#1733]
Tests on consumption timing of fuel/ammo/steel when LBAS support/Jet assault phase triggered.
Recommended steps:

 1. Remember the resources of fuel & ammo
 2. Send LBAS sortieing to a node
 3. After entering the node battle, trigger a catbomb intendedly (by blocking network access or reload page or sth)
 4. Return to game home port, to see if fuel & ammo consumed or not, and how many it decreased (regeneration excluded would be better)
 5. Retry 1~4, change the catbomb timing of step 3. For example, after entering battle result screen, before entering home port when sortie finished, or even just after LBAS attack points selecting committed.

Similar with above, the steel consumption timing of jet bombers also needed.

btw, my assumption of that two consumption timings are both the API call of `/battle` series, not `/battleresult` or others.

**Comment by LostLogia4** [comment]
Jet catbombing result (Before):
![before](https://cloud.githubusercontent.com/assets/12930396/21917447/c8253b2e-d982-11e6-989b-c3741ee4c30d.png)
Jet catbombing result (After):
![after](https://cloud.githubusercontent.com/assets/12930396/21917449/c9132cb2-d982-11e6-93c9-88dbf4ccb32d.png)

**Comment by sinsinpub** [comment]
@LostLogia4 which catbomb timing? during battle, not reach battle result?

**Comment by LostLogia4** [comment]
This one is catbombed after battle but before battleresult.

**Comment by sinsinpub** [comment]
@LostLogia4 it seems good enough already. as consumption of steel depends on count of engaged jets, its timing must not be before battle.
