### ISSUE TITLE
[Bug] Evas of extended slot item counted even when "Equip Stat" in Ship List is switched to No

### ISSUE THREAD

**Issue by HKGPsy** [KC3Kai/KC3Kai#1735]
As shown in this picture, the machine gun in the extended lot was Bofors 40mm (2 Evas)
![image](https://cloud.githubusercontent.com/assets/16491462/21931047/3ff45422-d9d4-11e6-9529-4c4cc79f1583.png)

Here is a picture showing Saratoga Kai unarmed stat
![image](https://cloud.githubusercontent.com/assets/16491462/21931061/5038a054-d9d4-11e6-8daa-8fd811b32184.png)

The Evas of Saratoga Kai at 122 level should be 59, but it was shown as 61. My guess is the Evas of Bofor was counted? However, FP, AA and Armor of the Bofors was not counted.

The Evas returned correct after removing the item
![image](https://cloud.githubusercontent.com/assets/16491462/21931062/543225b8-d9d4-11e6-925e-cbc7657c89ff.png)

**Comment by sinsinpub** [comment]
thx for reporting. btw, this title is too long 😂
