### ISSUE TITLE
Jet planes no longer contribute to Air Power Calc

### ISSUE THREAD

**Issue by dragonjet** [KC3Kai/KC3Kai#1738]
> Thank you very much for the great work!

> Just wondering though, after today's 30.15.0 update, jet planes no longer contribute anything to the air power calculator. Was that intentional, or a bug?

~ [_Samy Chua‎  on Facebook_](https://www.facebook.com/kc3kai/posts/1837621906525300)

**Comment by sinsinpub** [comment]
fix this air power config (or just replace all with `{}`)

**Comment by dragonjet** [comment]
ah if we have an update to configuration where users need to be reset, we can just bump up the config version in ConfigManager, it will reset the saved localStorage copy
