### ISSUE TITLE
devtools keeps switching back to basic tab while changing equipments

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#1740]
as title says. it is possible that user are looking at the exped tab panel so when there is no gunfit or AACI info available, it shouldn't switch back to basic tab by default. or at least when equiping daihatsu-like / drums, exped tab should be kept focused if it has been selected already.

I believe this behavior is introduced by the following patch:
https://github.com/KC3Kai/KC3Kai/commit/33eef1bdd4cb13fe2b8d045ebc332c300bbd975b#diff-a7317f61c20e51078ed9a657bdc79d7dR2884

@sinsinpub is there any concerns about this auto-dismissing?

**Comment by sinsinpub** [comment]
easy. just dismiss it only if activity tab is activated via checking `$("#atab_activity").hasClass("active")`
patch it later.

**Comment by Javran** [comment]
@sinsinpub what if we also prevent switching if exped tab is active? I feel that could work better because usually when users are looking at the exped tab they are working on exped fleets and don't really care about gunfit & AACI kind of stuff

**Comment by sinsinpub** [comment]
it's okay for me. but ur situation means ur exped fleet also equipped AACI or main gun...?

**Comment by Javran** [comment]
@sinsinpub none of them, I tried equipping satsuki k2 with T89 and it popped up despite no gunfit / AACI info are available.
![2017-01-17_230626_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/22050536/b6c35a66-dd09-11e6-885c-673d1e3a833a.jpg)

**Comment by sinsinpub** [comment]
oh, that's caused by another issue... try latest master, just fix it.

**Comment by Javran** [comment]
@sinsinpub I see, will do a follow up patch for keeping exped tab, although I don't think there will be regular expedition gears that has something to do with AACI / gunfit, just to be safe.
