### ISSUE TITLE
[Request/Suggestion] Quest B89 description

### ISSUE THREAD

**Issue by IMCF007** [KC3Kai/KC3Kai#1750]
I feel kinda stupid asking for this but I think it would be useful to add some kind of warning to it.

Current: 'Sortie 2 BB(V) and up to 4 additional ships to [W2-4], S-Rank the boss node.'
Suggest: 'Sortie 2 BB(V) (must be slow BB! not FBB) and up to 4 additional ships to [W2-4], S-Rank the boss node.'

The current one is actually already clear enough, as you didn't make it (F)BB(V). Still someone like me has to mess up with that >.>.

I was like so mad at myself. As you might know, it's hard to get the route lol...

**Comment by nonsensed** [comment]
That's horrible, sorry to hear that. I've added a notice not to use FBB for that quest. Honestly I should've had such a warning in the first place for that quest description. Sorry again.
