### ISSUE TITLE
display bug via Frame

### ISSUE THREAD

**Issue by Yukii18** [KC3Kai/KC3Kai#1759]
Chrome Version 55.0.2883.87 m
Windows 7 ultimate 32bit
KC3 Kai ver. 30.16.0 from webstore

how i fix it ?
![ss 2017-01-25 at 06 09 18](https://cloud.githubusercontent.com/assets/25343061/22287368/991df758-e32d-11e6-81c9-319ef2219e4c.jpg)

**Comment by wrinkledm** [comment]
+1

**Comment by sinsinpub** [comment]
#1758
