### ISSUE TITLE
a completed quest is not saved upon removal. (was: Bd5 counter doesn't bump.)

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#1762]
- on master branch commit abafaf6a04295c847db756a20887f11089c25a6e.
- chrome: Version 54.0.2840.100 (64-bit)

~~as the title has said, I noticed there were more active quests than what I actually have and found Bd5 was still `0/3` despite I've completed it. had sunk 3 transports on 2-2G and the counter didn't bump at all, nor does it remove itself upon completion. should be 3 transports in one go because I encountered the following formation and got a S rank:~~

![2017-01-26_163027_3360x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/22351198/d0f9b68c-e3e4-11e6-80ca-ca95b4cf61c8.jpg)

~~sorry that I couldn't recall the sequence of reproducing this bug so keep an eye and see if something similar has happened to you.~~

Edit: turns out the problem is not that counter doesn't bump, but rather a completed quest is not saved upon removal. I completed C3 yesterday but when I logged in today, I can see a completed C3 quest with `5/5` still present in the panel.

**Comment by Tsubakura** [comment]
I actually just finished Bd5 through 5-4 and so far, I can tell that the quest counter works fine. Maybe its actually caused by destroying 3 transports at once?

**Comment by Javran** [comment]
@Tsubakura probably, I'm also a bit confused because this doesn't explain why I didn't run into this problem yesterday. in my first sortie of yesterday I encountered the 4-transport formation on 2-2G and S-ranked it, so sinking 4 at a time looks fine.

**Comment by Javran** [comment]
turns out actually the counter does bump properly, but the progress is not saved. so when next time I reopen the browser the recorded progress is lost. but I haven't run into this problem before, are there recent changes that involves reducing the frequency of saving?

**Comment by sinsinpub** [comment]
not sure what is happening... but I'm worry about: is ur local storage quota exceeded again?
iirc ur localStorage had been reaching the 5MB, and recently new added keys: player newsfeed (<1KB), lbas converting slots (4B ~ 160B),  consumables (up to 0.5KB), although all these  are really small, but if ur saved fleet data is large...?

**Comment by Javran** [comment]
@sinsinpub no, everything looks fine in console, besides if it's a quota problem the panel itself should stop functioning.

**Comment by sinsinpub** [comment]
hmm, no recent change on codes... and a known possible is overwriting by sroom flowchart page, but i donot think u did that.

i guess the most possible reason is downgrading ur chrome which make profile data files unstable. i known chrome will prompt: ur user data is from newer ver, old chrome may corrupt things when ver diff > 2. extension local storage is also possibly affected. check if not only quest but also other keys not saved? if true, try to rebuild local storage by removing data and journal files and ofc remember to full backup all (both raw files and exported texts) at ur own risk...
![image](https://cloud.githubusercontent.com/assets/160240/22393197/c0ae78a8-e53d-11e6-85fb-c289a9c2ef12.png)

**Comment by Javran** [comment]
@sinsinpub I won't bother doing that though .. not a big issue anyway, if no other user has encountered this problem I think it's fine. I did switch between versions / KC3 branches / game play modes a lot while using the same chrome profile directory, I'm not surprised if this turns out to be the case.

I'll keep an eye on C3, if everything works fine we can close this issue unless others have the same problem.

**Comment by Javran** [comment]
closing this as I've previously said, perhaps just a problem from my own side.
