### ISSUE TITLE
wrong rank prediction result

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#1766]
replay http://i.imgur.com/Db3230b.png

- predicted result: B rank
- actual result: C rank

**Comment by fourinone41** [comment]
Our calculation may have slightly different rounding than the game's. If you want to use Vita version's calculation for B vs C, which seems to be consistent with your case, theirs is:
```
enemyPercent = floor(100 * totalEnemyDamageTaken / totalEnemyHP)
playerPercent = floor(100 * totalPlayerDamageTaken / totalPlayerHP)
if enemyPercent > 2.5*playerPercent: return B
else if enemyPercent > 0.9*playerPercent: return C
else: return D
```
So in your example, enemyPercent = `floor(100 * 70 / 341)` = 20, and playerPercent = `floor(100 * 4 / 49)` = 8. `20 > 2.5 * 8` is false, so C.
This is different from no flooring, where `70/341 > 2.5 * 4/49` is true and meets the condition for B.

**Comment by Javran** [comment]
so our formula was indeed correct until https://github.com/KC3Kai/KC3Kai/commit/e7b01ccfeadf71f753aecf5578b2876d1f6f8cdb ...

@sinsinpub what is the reason for this "accuracy up"?

**Comment by sinsinpub** [comment]
so how about long distance air raid for vita? rounding to percent make damage < 10 get S
just use different for them?

**Comment by Javran** [comment]
@sinsinpub I think long distance air raid doesn't share the same mechanism.. if that's the concern we can use a separated `allyGaugeRate` (working on it)

**Comment by sinsinpub** [comment]
i guess they can share, just change the 'no damage' cond to hp comparing, not depend on rate?

**Comment by fourinone41** [comment]
Well, long distance air raid doesn't exist in Vita, so no help there, hah.

**Comment by Javran** [comment]
just did a little digging, the only thing I can find this wikia page: http://kancolle.wikia.com/wiki/Events/Mechanics , which is refering to http://nga.178.com/read.php?tid=8989155 (Chinese). not sure if there are other source, but for now I think there's no non-perfect `S` rank.

also I'm not sure what's the bound between rank D and rank E, it seems both rank is possible but it's unclear to be where does the 80% bound we are currently using come from.

**Comment by sinsinpub** [comment]
it's just typo, i mean SS.
for 80%, there is comment of source which ref to eo74 repo

**Comment by Javran** [comment]
@sinsinpub can you show me the link? or you can update in comments and push to `fix-battle-rank` branch directly.

**Comment by sinsinpub** [comment]
typing with pad is slow 😂 
https://github.com/KC3Kai/KC3Kai/blob/87880e53eed2f5f86e42d6228ce03a65094c3bca/src/library/objects/Node.js#L25

may move it down

**Comment by Javran** [comment]
@sinsinpub nice then, I'll move it down myself since you are not on pc.

so for SS rank I decide to just check whether ally fleet take any damage at all instead of checking the rate and for rest of the prediction let's keep 74EO's approach
