### ISSUE TITLE
Screenshot area not correct

### ISSUE THREAD

**Issue by yeshasuicide** [KC3Kai/KC3Kai#1775]
![shimadaze 2017-02-01 16-12-10 19](https://cloud.githubusercontent.com/assets/17948412/22499418/a5894c74-e899-11e6-90f9-9d9b21f01514.jpg)

**Comment by dragonjet** [comment]
try experimenting with screenshot setting, Device Pixel Ratio to match your system

**Comment by yeshasuicide** [comment]
thanks,it works.
