### ISSUE TITLE
API error notice

### ISSUE THREAD

**Issue by leslinspringfield** [KC3Kai/KC3Kai#1777]
The API error notice keeps popping up every time when there is an action (like battle or create new equipment) in game, indicating api error. I'm not sure about this problem since I always play through DMM webpage mode.

Thanks!

- [55.0.2883.87] Your Chrome version - via chrome://version/
- [Windows 7 SP1] Your OS and its version
- [64] 32bit or 64bit?
- [30.16.2] Your KC3 Kai version - via chrome://extensions/
- [webstore version] Which build you have tried running? webstore version as in the one from [Chrome Web Store](https://chrome.google.com/webstore/detail/kancolle-command-center-%E6%94%B9/hkgmldnainaglpjngpajnnjfhpdjkohh) or Github variant (better known as developer builds).
- [![image](https://cloud.githubusercontent.com/assets/25492707/22529331/099f40be-e8a5-11e6-98d2-0c5d1f162f86.png)] Screenshots which accurately paint the issue(s) you are facing.
- A step by step method that you did to describe how you got to that issue.

**Comment by dragonjet** [comment]
if it's enabled on settings, that popup will show a "download error report file". please enable it, and attach the file here so we can see whats happening on that side

**Comment by sinsinpub** [comment]
i think we should update ISSUE_TEMPLATE for two things: don't use TODO list markdown; add a section about download and send error report to us...

**Comment by leslinspringfield** [comment]
I did not see a "download error report file" in the "Error" section in setting. 
![image](https://cloud.githubusercontent.com/assets/25492707/22551385/a1578c5e-e922-11e6-85c9-51743ec4afd4.png)

**Comment by leslinspringfield** [comment]
I think I got one of the error report and attached here.
Thanks for help!

**Comment by sinsinpub** [comment]
so just download and send the report to us when this popup
https://cloud.githubusercontent.com/assets/25492707/22529331/099f40be-e8a5-11e6-98d2-0c5d1f162f86.png

**Comment by leslinspringfield** [comment]
I think I got one of the error report and attached here. Looks like I cannot upload *.json file, so I changed to .txt and upload here.
Thanks for help!
[KC3-Error-1486042568.txt](https://github.com/KC3Kai/KC3Kai/files/747855/KC3-Error-1486042568.txt)

**Comment by sinsinpub** [comment]
thx for report. error itself has been fixed already. will disappear at 30.17.0.
further reason will be reported here if u have interest.

**Comment by sinsinpub** [comment]
it seems that there is something wrong with your quest data. to check if ur local storage goes wrong or a problem of SChinese translation, would u please switch to `Console` tab from `KanColle` tab and execute this:
```
JSON.stringify(KC3QuestManager.getActives())
```
then copy & paste the result JSON here.

**Comment by leslinspringfield** [comment]
Thanks for help! I tried to execute the command you provided in Console tab and it gave this feedback. I'm not sure where I can find the JSON file.
![image](https://cloud.githubusercontent.com/assets/25492707/22561217/4522fe78-e945-11e6-8af6-f49a8af9db87.png)

**Comment by dragonjet** [comment]
we will release 30.17.0 this week so will be fixed soon

**Comment by sinsinpub** [comment]
hmm, as it's not easy to reproduce the issue of your side... although the handler is fixed and fail-safe on unexpected data, but after update to 30.17.0, you might keep eyes on the quest list of panel, to see if there is any `undefined` displayed on the tool-tip of quest.
