### ISSUE TITLE
Badge generation not working

### ISSUE THREAD

**Issue by Green-Cat** [KC3Kai/KC3Kai#1781]
### Versions:
Chrome: 56.0.2924.87
OS: Windows 10 Pro version 1607 (64 bit)
KC3 Kai: 30.16.2 (chrome web store)

### Steps to reproduce:
1) Open Strategy Room
2) Click on Badge tab under Ships
3) Leave default settings
4) Click the export button

### Actual behaviour:
Nothing happens, error in the console.

### Expected behaviour:
Badge generated through http://threebards.com/kaini/

### Console error
```
Form submission canceled because the form is not connected
trigger @ global.js:2
(anonymous) @ global.js:2
each @ global.js:1
each @ global.js:1
trigger @ global.js:2
n.fn.(anonymous function) @ global.js:3
(anonymous) @ allstrategytabs.js:4
dispatch @ global.js:2
r.handle @ global.js:2
```

**Comment by Javran** [comment]
it's yet another "feature" coming from chrome side, I'm not in the slightest surprised (.. swearing omitted).

related commit: https://chromium.googlesource.com/chromium/src/+/962c2a22ddc474255c776aefc7abeba00edc7470%5E!/

does some other @KC3Kai/developers has chrome 56 installed already? we need to find a workaround for this but I've literally blocked all chrome >54 versions in my system and not willing to unblock it if possible.

**Comment by sinsinpub** [comment]
maybe just appending the form elements to body before submit will make it 'connected'...
