### ISSUE TITLE
[Suggestion] Profile tab newsfeed timestamp

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#1782]
it seems every item in newsfeed is showing the exactly same time, instead of repeating the same timestamp 6 times, why don't we just change the section title to `Newsfeed at {time}` and remove timestamp from newsfeed items?

**Comment by sinsinpub** [comment]
it's ok for me to change. but just lemme tell the meme: timestamp for each line looks like real logs in various situations.
and for me, wanna reserve the column for someday the log API could give us the chance to recognize the real time stamp.

**Comment by Javran** [comment]
you do have a point, but now I just realized there is another problem: with same timeline on all log entries, there's no way to tell with one is newer, so that would be against the meaning of having a timestamp, what about keeping the timestamp column, but instead replaced by just numbers: 1, 2, 3, 4 ..  or so?

**Comment by sinsinpub** [comment]
the order is telling thing: newer on top. it depends on the API result...
maybe u have no idea yet, there is no time in API, and there no way to recognize which log line is already recorded since last time. so the timestamp is just a fake thing (to make it looks more like logs), it's the time when handle the home port API.

**Comment by Javran** [comment]
@sinsinpub then what I thought was right - there's simply no timestamp from KCAPI.

also numbering `1`, `2` ... might be a bad idea, it is still ambiguous and doesn't really suggest user of how logs are ordered.

perhaps we can do no better than we currently are. I'm gonna close this issue and update some comments just to refer to this discussion.
