### ISSUE TITLE
Suggestion: Option to modify dashboard's left box's opacity

### ISSUE THREAD

**Issue by Shurichan** [KC3Kai/KC3Kai#1786]
It would be a nice QOL change to allow it's opacity to be modified to block less of the background.
![2017-02-04 23_20_17-kc3](https://cloud.githubusercontent.com/assets/13228415/22621661/80fa7ffa-eb31-11e6-8f04-671123b00444.png)

**Comment by sinsinpub** [comment]
i just wanna troll: what do you want to see exactly, the bg picture? contents of panel?
give a suggestion: photoshop your bg picture, let the character avoid the panel box. 😂
