### ISSUE TITLE
Feature Request: Estimate experience gain from PvP

### ISSUE THREAD

**Issue by Accelyte** [KC3Kai/KC3Kai#1790]
Since the new update can now detect the fleet composition before PvP starts, I was thinking if it is possible to calculate the experience gain according to the table on wikia: http://kancolle.wikia.com/wiki/PvP. It would be convenient to see whether a PvP experience is worth the resource consumption.

**Comment by nonsensed** [comment]
You mean this?
![image](http://i.imgur.com/ZPJXhiT.png)
It's the "base exp" around the bottom.
mouse over the base exp to see the tooltip

**Comment by Accelyte** [comment]
Ah, I couldn't see it. I was looking at the top of the info box. Thanks for pointing it out to me.
