### ISSUE TITLE
Toolbars and detail box sizes for small monitor resolutions (question). 

### ISSUE THREAD

**Issue by HalfbreedAndrij** [KC3Kai/KC3Kai#1801]
Sorry if this doesn't belong here.

![low res monitor](https://cloud.githubusercontent.com/assets/25641655/22745001/bf7c7ffa-ee27-11e6-8f2a-22a074732cc2.png)
Is there any way to solve the Yellow issue so that the Red one won't pop up, othe than decreasing player scale and raising the toolbar?
As, whenever i hover over enemy ships with 4 equipment, the larger detail box appears below the pointer and procs the "scroll edge", which also makes the toolbar twitch to the side whenever i do that. The detail box of my fleet appears next to the mouse so it doesn't cause that problem.
I'm using the horizontal toolbar displacement as the vertical position would have me drasticaly decrease player scale to solve that problem, and i don't want that. Is there any way to make the enemy detail box smaller or appear next to the mouse like the friendly fleet one or make the entire viewer toolbar smaller (rather than the game scale)? The version pre .17.0 didn't have this minor issue (for me, as the detail boxes were smaller and simpler).

**Comment by sinsinpub** [comment]
The position rules for tooltip has been update for next release, it will try to auto fit to display inside the window, as long as your window size is large enough to show the tooltip, no scroll bar again.
different from former native tooltip, a float div element is not able to display outside of window, it's the trade off to get a stylish tooltip.
(i though nobody's screen size should be smaller than mine, as i have to zoom the game player scale to quite small to get kc3 panel shown 😸 )
