### ISSUE TITLE
new play mode doesnt load

### ISSUE THREAD

**Issue by lolbob** [KC3Kai/KC3Kai#1813]
i get white screen when i try to use the play on website option..

and this weird counter thing http://i.imgur.com/eviLTWc.png

using chrome 56, win8.1 flash in chrome://plugins/ always allowed to run is checked

Frame works fine though..?

**Comment by dragonjet** [comment]
can you try disabling adblock, or at least marking DMM as allowed

**Comment by lolbob** [comment]
@dragonjet i disabled adblock altogether, still white screen.

**Comment by sinsinpub** [comment]
> Tibi - Today at 9:43 PM
> anti-adblock killer in tampermonkey causes it
> (https://github.com/reek/anti-adblock-killer)

**Comment by Tibo442** [comment]
If you are using Anti Adblock killer, add dmm.com to the excludes in the userscript. http://i.imgur.com/19KvZhC.png

**Comment by lolbob** [comment]
@sinsinpub @Tibo442  thanks! Fixed, this was the problem!

**Comment by dragonjet** [comment]
followup, there was a similar report but was using `uBlock Origin`. have to take note for future users

**Comment by sinsinpub** [comment]
@dragonjet clearify: it's not caused directly by 'adblock' or 'ublock', it's `anti-adblock`. i'm using ublock origin too, and kc3 working

**Comment by Tibo442** [comment]
@dragonjet It's not exactly caused by `uBlock`, but by an extra addon, `Anti-Adblock Killer` (it blocks those 'disable adblock to view xxx'). I've made [a PR](https://github.com/reek/anti-adblock-killer/pull/2833) yesterday to fix this issue.
