### ISSUE TITLE
Nothing happens when I click 'Kancolle' tab on a new 'Play on DMM Website' panel after latest 31.0.1 update.

### ISSUE THREAD

**Issue by Eankun** [KC3Kai/KC3Kai#1814]
So you guys decided to break an extension on the very first day of the event?
Great job.

https://i.imgur.com/8QdZGv7.png

**Comment by dragonjet** [comment]
hi, sorry for the inconvenience, but to debug this error we ask to provide the following:

- Chrome version
- Your OS and its version
- enabled extensions

**Comment by kaungsijohn** [comment]
I am having similar problem, since i saw that play on dmm website is the only one that isn't old so i tried that and the game froze like all 3 times i tried it. Currently back to playing on dmm frame and so far no problem on that one.

Anyway ... 

Chrome ver : 56.0.2924.87 (64 bit)
OS : Window 10 Home Version 1607  64 bit
Extensions
 Adblock
 Battlelog Emblem Editor Extended
BetterDiscord
Google Docs
Google Docs Offline
Google Slides 
Google Sheets
MEGA
Reddit Enhancement Suite
Sad Panda
Viramate
グランブルーファンタジー[ChromeApps版] ( Granblue Fantasy )

**Comment by dragonjet** [comment]
@kaungsijohn by similar you mean you are also stuck in the page with all the toggles, and you can't start it because the devtools panel is whitescreen?

**Comment by HakenBrowning** [comment]
I don't know if my case will be taken into account (see the browser I use), but I have the same problem on all my computers (I use the same browser on all computers). KanColle tab doesn't detect the Dev Tools with KanColle tab opened.

Browser : 1.7.735.39 x64 (Chromium 56.0.2924.88)
OS : Windows 10 Pro at home, Windows 7 Pro at work
Extensions that are on all computers : LastPass, uBlock Edge, KC3Kai 31.0.5

**Comment by Eankun** [comment]
47.0.2526.80
Windows 7 Sp1
No extensions excepT kc3Kai

Okay, so I cleared the event and now I can attend this issue.
I was using Google Chrome Portable v47 on a several PCs. All suffered from the issue. If I choose "Play via API link (old)" option, then game just loads kancolle right on the DMM website
https://i.imgur.com/1fz1r8i.png

I updated my GCPortable to the latest version (56 or something?) and that completely resolved the issue.
But I hate late chrome versions because of anti-flash faggotry (and Google tries VERY HARD to not let you download any chrome except the latest one), so I decided to determine exact 'broken' vesion.
I downloaded and installed Chromium Portable version 49 (49.0.2623.23)
Extension is working fine, confirmed on several PCs with different hardware (all with W7Sp1 though).

**Comment by dragonjet** [comment]
thanks for the update @Eankun we will let others of the same chrome preferences know of the latest working patch when they ask.

@kaungsijohn and @HakenBrowning I suggest creating a new issue thread if updating chrome does not solve your issues
