### ISSUE TITLE
31.0.1 update has bricked KC3

### ISSUE THREAD

**Issue by timmy112** [KC3Kai/KC3Kai#1817]
Thanks to the 31.0.1 update i can no longer play kancolle on this computer (which is a little annoying while there is an event happening), whenever i try to play with 
this extension active i always get a blank screen, if it turn it off kancolle is zoomed (150% scaling) in and is still unplayable.

Playing via Api Link has the same effect as disabling the extension, strategy room and settings no longer work so I can't disable the Scaling...

Chromium Version 47.0.2498.0
Windows 10 X64
KC3 Kai 31.0.1 and KC3 Kai 31.0.3 Dev

I'll upload a video soon

**Comment by mikenzb** [comment]
Maybe try updating your chromium version because version 47 sounds like it's quite old.

**Comment by timmy112** [comment]
https://youtu.be/HIHfF-z0-_4

TBH I'd rather not update, and anyways it was working perfectly until version 31.0.1, I'm wondering if it has something to do with this: "DMM website gameplay mode overhaul"  ... from https://github.com/KC3Kai/KC3Kai/pull/1789

So I wondering if this overhaul broke a few things....

**Comment by mikenzb** [comment]
Please have a read at the version 31 patch notes #1789.

**Comment by sinsinpub** [comment]
first time to hear 'brick' a software :joy:
it should not work perfectly before 31.0.1, as ES6 already included in earlier version. maybe u just not notice the issue.

Here are some options:

* Upgrade your chromium ofc, at least v49. v54 is a good choice to keep API/Frame mode working
* No necessary to keep updating as your browser, just not use webstore version, download old KC3 instead

**Comment by timmy112** [comment]
I assume I was on 29.xx before KC3 decided to skip ahead and update to 31.0.1 (It has done this to me heaps of times before).... *Sigh* It would've been nice if KC3 update window told me I needed to update my browser.... Meh Looks like I'll be screwing around for the next few hours to update.....

**Comment by dragonjet** [comment]
issue determined as chromium version. you can re-open this thread if it persists after updating the browser.
