### ISSUE TITLE
Expedition table reset configuration not loading?

### ISSUE THREAD

**Issue by zork787** [KC3Kai/KC3Kai#1818]
### Versions:
Chrome 56.0.2924.87
Windows 10 64x version 1607
KC3Kai Webstore version 31.0.3
### Steps to reproduce:
Since the addition of the Expedition Scorer Table I have been unable to use use because teh reset configuration option doesn't appear and I have no idea why
### Actual behaviour:
Reset Configuration doesnt appear
### Expected behaviour:
Reset Configuration appears
### Screenshots (if applicable):
https://i.gyazo.com/874f62bd83df4f14bc983ed7130d3301.png

**Comment by Javran** [comment]
weird, at least cost model section should always visible, could you try opening console in that page and see if there is any output?

**Comment by zork787** [comment]
opend teh console using F12 and got this https://gyazo.com/7f1382f764628f8de6a9645c847526b1

**Comment by Javran** [comment]
I can reproduce this bug in release build. @dragonjet would you mind taking a look at building process? I think something is wrong but cannot pinpoint it.

**Comment by Javran** [comment]
![2017-02-12_123721_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/22864464/0b8e38c0-f120-11e6-8c7e-3838777549b7.jpg)

turns out the HTML structure is completely changed, any @KC3Kai/developers knows about why this is happening?

**Comment by Javran** [comment]
@zork787 the problem should be fixed in next release, also thanks for the report.

@KC3Kai/developers turns out I didn't know the fact that `<div />` is invalid and has to be written as `<div></div>`. is it possible to make `htmlmin` more strict so we can detect these problems earlier?

**Comment by dragonjet** [comment]
@Javran I think we can even remove htmlmin if it causes something like this. it's not like a few kb of data makes any difference with out 10mb app

**Comment by Javran** [comment]
@dragonjet htmlmin is fine I think, but should have been more verbose than just silently let something like this pass through. until this issue I've never be aware of the fact that `<div>` shouldn't be self-closing.

**Comment by sinsinpub** [comment]
it's known behavior... self-close container (div, span etc) is recognized as 'empty' to be cleaned up.
