### ISSUE TITLE
KC3 interface stopped working completely when playing via API or DMM frame

### ISSUE THREAD

**Issue by Deygotwingsnow** [KC3Kai/KC3Kai#1819]
Since the 31.0.3 KC3 Kai has not been working for me. Whenever I use playing via API link or DMM frame, the interface does not load and is stuck at "waiting for game actions" no matter what I do. It does work when I'm playing on DMM website (and that's what I'm doing right now until there's a solution to this), but the background wallpaper is all messed up. It's cut off from the bottom of the game window.

I'm using what I assume is the newest version of chrome (56.0.2924.87), 64 bit. I'm using windows 8.1 if that matters. 
![wtf](https://cloud.githubusercontent.com/assets/25724582/22863716/862f676e-f113-11e6-8690-663f855551d0.png)
![wtf2](https://cloud.githubusercontent.com/assets/25724582/22863717/897ee6ce-f113-11e6-9736-dcc5779be8aa.png)

**Comment by Deygotwingsnow** [comment]
Update: all issues persist with the newest update.

**Comment by sinsinpub** [comment]
those two old modes not work as expected thanks to new chrome, search around to see more. don't use them if not demanded.

new dmm website mode about bg image size issue is known thing, just go to settings, change the `Background Size`

**Comment by dragonjet** [comment]
the insight is in the patch notes
* #1789 Release 31.0.0

more info
* #1645 Merged Gameplay Option
* #1722 New Gameplay Mode
* #1641 Chrome Version 55: Black screen
* #1643 [Issues] Panel don't start

**Comment by dragonjet** [comment]
as @sinsinpub mentioned, you can play around with the "background size" property as it does not work with DMM website. for the easiest way, use pixels. e.g., `1000px` and see the result, you can increase or decrease until satisfied with the height

**Comment by Deygotwingsnow** [comment]
This is going to be the last time I reply to this because one, it isn't a game-breaking problem and two, you don't seem to be willing to truly address the issue (I even wrote it in bold in my last comment and you still ignored it). 

I will explain this as clearly and specifically as a layman can. I already know that you can set the position and size of the background. The problem is that when the background position in KC3 Kai setting is set to **bottom center** or anything **bottom** at all, the entire background is **stuck in the top margin** as demonstrated in my second screenshot, and it's stuck like that **no matter what I put in the size. Cover, contain, percentages, pixels, NOTHING fixes it**.

**Comment by dragonjet** [comment]
maybe you should create a new thread with a title that doesn't say about API link and DMM frame being broken.

**Comment by dragonjet** [comment]
@Deygotwingsnow sorry for my attitude earlier. I'm just tired of seeing API link and DMM frame reports recently in all of our support channels and just a sight of them is already getting a flag in my thoughts.

we clearly put effort into creating a new game mode just to avoid the API link and DMM frame problems, and intentionally added "(old)" in their menu names.

for the background issue, I'm sure the conversation would've went in a better exchange if it was reported in a new thread, since this one is already flagged for me personally.
