### ISSUE TITLE
user report of experiencing API error on E3

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#1821]
generated error report: https://gist.github.com/Javran/6c1eae45baa236f8fa643cc42848224d

this user is experiencing API error on E-3 air raid node and boss node. you can also find one of his replay at http://img.ngacn.cc/attachments/mon_201702/13/-4ada3Q2g-doayZvT3cSb4-b4.png

btw can anyone tell me how do you deal with these json files? the error messge is for uglified js code so I don't even want to attempt to locate the actual problematic code block.

**Comment by Javran** [comment]
so the error report leads me to the following line of code:

https://github.com/KC3Kai/KC3Kai/blob/667d205ba028407bb4eb94a85a4581735a711605/src/pages/devtools/themes/natsuiro/natsuiro.js#L3275

and `api_maxeq` is `undefined` at that moment. I'm not familar with that part of code though

**Comment by dragonjet** [comment]
probably a case of missing equipment info from whocallsthefleet db for the new enemies?
