### ISSUE TITLE
Positioing of background picture is broken

### ISSUE THREAD

**Issue by Nya-chan** [KC3Kai/KC3Kai#1824]
Please make sure that you have these details on hand when submitting your issue/bug report as this will greatly speed up the issue triage process -- thank you!

- [x] Your Chrome version - 56.0.2924.87
- [x] Your OS and its version - Win 10
- [x] 32bit or 64bit? 64bit
- [x] Your KC3 Kai version - 31.0.6
- [x] Which build you have tried running? Webstore version stable
- [x] Screenshots which accurately paint the issue(s) you are facing. - See below
- [x] A step by step method that you did to describe how you got to that issue.

### Steps to reproduce:
- Enable a background with a background-position set to 100% of Y position or similar (calc based off of 100 %, etc).

### Actual behaviour:
- The background gets shifted upwards, ending way above the frame

### Expected behaviour:
- The background should stay where it's told to by background-position property, with 100 % being the bottom of the window

### Screenshots (if applicable):
https://i.imgur.com/HlCkS4d.png
https://i.imgur.com/k3vNg31.png

**Comment by sinsinpub** [comment]
@dragonjet is it still counted as bug...? 😅  i've already tell this issue at PR: https://github.com/KC3Kai/KC3Kai/pull/1722#issuecomment-274439407

**Comment by dragonjet** [comment]
@sinsinpub I was thinking we can workaround something on DMM to make it work correctly. I have failed to do it once in local, but haven't given up that we can make the DMM page background to work the same way as any other page
