### ISSUE TITLE
Possible bug with showcase export

### ISSUE THREAD

**Issue by MegaAbsol** [KC3Kai/KC3Kai#1825]
In the new showcase export, the 4 corners seem to be colored if the corresponding stat is maxed - FP, Torp, Armor, and AA (clockwise from top left). However, my Maya K2 is colored:

![image](https://cloud.githubusercontent.com/assets/10118751/22907822/10446336-f219-11e6-94c2-c97a18ceb055.png)

Even though her AA is not maxed:
![image](https://cloud.githubusercontent.com/assets/10118751/22907858/39933b04-f219-11e6-9e5e-175b52b437f3.png)
![image](https://cloud.githubusercontent.com/assets/10118751/22907875/474e4068-f219-11e6-9bc0-f364dd7b7647.png)

Maybe it's something to do with equipment? Or it's just me.
Chrome version: 56.0.2924.87 (Official Build) (64-bit)
KC3Kai version: 31.0.6

**Comment by MegaAbsol** [comment]
This was the only instance i noticed in my export page, so I think it might either be due to holepunch, an incorrectly coded Maya max aa value, or me being stupid.

**Comment by DynamicSTOP** [comment]
Looks like it takes into account equip. That's actually unexpected.

**Comment by DynamicSTOP** [comment]
@MegaAbsol added a fix, hopefully would be rolled out in the next version. Thanks for your report!
