### ISSUE TITLE
[Suggestion] TP calculator

### ISSUE THREAD

**Issue by HKGPsy** [KC3Kai/KC3Kai#1830]
It would be a very handy tool if we can have a TP calculator for map like E2. The calculation formula has been quite stable across event. The calculator value (for A and S) can help us to estimate how many time we need to transport and maybe adjust the amount of drum we would like to take in one round.

**Comment by sinsinpub** [comment]
move your mouse pointer around panel, get the surprise...

**Comment by HKGPsy** [comment]
Oh..I found it, sorry for that

**Comment by nonsensed** [comment]
As the tooltip when mousing over the combined fleet type appears to satisfy your needs, it looks like this is taken care of. And no worries if you didn't notice it-- it's not the first time this has been asked!
