### ISSUE TITLE
[Suggestion] Migrate KCBadge to updated version

### ISSUE THREAD

**Issue by Nya-chan** [KC3Kai/KC3Kai#1832]
The current KCBadge has been abandoned by its author and the site for export isn't updated. The author published it on github, though, and the development continues.

I am now hosting the latest version at http://www.sanya.moe/kcbadge/ and plan to update it as long as the github is updated, so it should be possible to direct the export there.

**Comment by ethrundr** [comment]
Is it possible if you create a pull request instead of making an issue?
It'd be a great help if possible to be done.

**Comment by Nya-chan** [comment]
I'll look into it (haven't worked with GH that much so far, but it will be handy in the future, so why not) and try~

**Comment by Javran** [comment]
let's keep this issue open for keeping track.

**Comment by Vultren** [comment]
we can close this now. strategy room points to the right location,
