### ISSUE TITLE
Feature: Strategy Room: List of ships required by quests

### ISSUE THREAD

**Issue by reinforce** [KC3Kai/KC3Kai#1834]
Hi,
I'm working on adding new feature: List of ships required by quests.
My work adds new page in strategy room and shows list of available ships and quests, linked with them.
It also should mark completed and active quests, but this function not well tested yet.

Why do I need it?
Suppose, I have some ships, which I don't need anymore, but can be required for some quests completion. I go to this page and see quests list and they statuses. If all quests marked as completed, I can freely destroy those ships.

If you interested in my work, I'll share it.

Versions: Build on top of 31.0.6
Screenshots: http://i.imgur.com/nkXw47R.png

**Comment by dragonjet** [comment]
this is interesting :+1: feel free to create a pull request to this repo, we'll check it out

**Comment by dragonjet** [comment]
related #279

**Comment by reinforce** [comment]
Pull request: #1836

**Comment by sinsinpub** [comment]
i thought there would be a db to record those `quests marked as completed`... (which is quite hard to be perfect)
seems quests are already completed and removed from QuestManager will not hold any 'status'

**Comment by mikenzb** [comment]
Going to close as PR has been merged and released, @reinforce if you plan on working on the above suggestion go ahead but I don't think we need this "issue" open.
