### ISSUE TITLE
[Bug] Ship killed by Jets appear as alive by the end of combat

### ISSUE THREAD

**Issue by Maledictumrus** [KC3Kai/KC3Kai#1838]
### Versions:
56.0.2924.87 (Official Build) (64-bit)
Win10 1601 64-bit
- [ ] Your KC3 Kai version - 31.0.7
Webstore build
### Steps to reproduce:
1) Shoukaku and Zuikaku CVB equipped with Jets
2)Sortie to E2, let them kill things with jets
3)look at health prediction of the enemies
### Actual behaviour:
Unit killed in jet phase appears to be alive
### Expected behaviour:
Everything is dead
### Screenshots (if applicable):
![image](https://cloud.githubusercontent.com/assets/6248119/23061108/96593eec-f511-11e6-8a61-bd1bd1705d42.png)
![malediction_77](https://cloud.githubusercontent.com/assets/6248119/23061412/ccce3742-f512-11e6-8897-10d638fe0596.png)

**Comment by mikenzb** [comment]
Issue was fixed in 8cdb802bdb6b257dd754bc034b11689f7855c0db so when the next KC3 version releases it should come with that fix.

Reopen if issue still persists after the next KC3 release.
