### ISSUE TITLE
Flash Player Blocked in Ship Library

### ISSUE THREAD

**Issue by dsota** [KC3Kai/KC3Kai#1839]
- [ ] Your Chrome version - 56.0.2924.87
- [ ] Your OS and its version- Windows 10 
- [ ] 32bit or 64bit? 64 bit
- [ ] Your KC3 Kai version - 31.0.7
- [ ] Which build you have tried running? webstore version

Recently, I've noticed that Flash Player is being blocked in the Strategy Room when I enter the Ship Library. There doesn't appear to be any way for me to tell Chrome to allow Flash to run in the Strategy Room. I've tried adding KC3 extension into the Flash player security settings but that didn't fix anything.

![image](https://cloud.githubusercontent.com/assets/18238488/23095900/f53f64d0-f5df-11e6-9423-5f010051b44d.png)

**Comment by dragonjet** [comment]
have you tried some solutions on this page?
https://github.com/KC3Kai/KC3Kai/wiki/Startup-problems

**Comment by dsota** [comment]
Problem was resolved after going into **chrome://plugins** and selecting Always allowed to run for Adobe Flash Player

![image](https://cloud.githubusercontent.com/assets/18238488/23108225/572ee0b4-f6d8-11e6-973f-a4397a49b14a.png)

**Comment by sinsinpub** [comment]
prediction: future chromium has removed `chrome://plugins` page, to allow flash player to run, go Settings -> Advanced settings -> Privacy Content settings dialogue, will find `Allow sites to run Flash`
![image](https://cloud.githubusercontent.com/assets/160240/23110228/a23edfc8-f75a-11e6-9e85-12f0535aa914.png)
