### ISSUE TITLE
Not translating the quests

### ISSUE THREAD

**Issue by 21GrainsofRice** [KC3Kai/KC3Kai#1842]
Whenever I launch it, i find that the extension is not translating the vocals or the quests. I made sure that it was enable in the settings. How do I fix this?
Chrome version - 56.0.2924.87
Windows 10
32 bit
KC3 Version -  31.0.8
Chrome exstension

**Comment by Nya-chan** [comment]
Did you enable "Use enhancements" switch on the startup screen?

**Comment by mikenzb** [comment]
No update from author, please check "Apply Customizations" is enabled and you're playing through the new DMM mode, reopen issue if it still persists.
