### ISSUE TITLE
Taiha alert screen blood and screeen blur does not work

### ISSUE THREAD

**Issue by DLRevan** [KC3Kai/KC3Kai#1843]
### Versions:
Chrome version: 56.0.2924.87 

### Steps to reproduce:
Have a taiha ship in main fleet. 
Stay in home port with home port option on, or sortie with fleet containing taiha ship. 

### Actual behaviour:
No screen blood or screen blur appears when these options are enabled.

### Expected behaviour:
Screen blood and screen blur should be active when in home port with home port option enabled, or always on in sortie, as long as there is a taiha ship.

### Screenshots (if applicable):
Game screenshot with panel: http://i.imgur.com/f2m2V9E.png
Screenshot of options: http://i.imgur.com/sJVnj4e.png

Note: Panel red shade and heartbeat sound still work.

**Comment by mikenzb** [comment]
In the version 31 patch notes here #1789, there was a mention here that says 
`Almost all KC3 customization supported. Only the on-screen "annoying taiha alert" is not ported over. However, the devtools panel will still glow red if setting is enabled`

If you are playing via the new gamemode, this will be why.

**Comment by DLRevan** [comment]
Then I would appreciate if the options were disabled or if a note was added in the settings. I assumed that this was already re-added since after switching to the new mode recently, the option was still available in the settings.

**Comment by KnightBaron** [comment]
Will the feature be ported later or is it discontinued?

**Comment by mikenzb** [comment]
Going to close this issue, Would recommend you open up a new issue with the taiha alert suggestion.
