### ISSUE TITLE
unable to download replay image with tablet

### ISSUE THREAD

**Issue by throwawayttk** [KC3Kai/KC3Kai#1847]
### Screenshots (if applicable):

Using kc3 kai 31.1.0 on a tablet running latest version of win 10.  I can still download replays of pvp using the replay button.

**Comment by sinsinpub** [comment]
just pinch to zoom in, will be able to tap... 😂

**Comment by sinsinpub** [comment]
check if it's easier to tap after this commit 36fe0ff released
it may be still not large enough for touching 🤔

**Comment by Vultren** [comment]
Hey @throwawayttk what type of tablet are you using? I haven't seen much problem with sortie images on my Surface Pro 3.

**Comment by mikenzb** [comment]
Replay button already added into KC3 should hopefully should fix the issue, reopen if issue still persists.
