### ISSUE TITLE
Game hangs on loading screen after clicking play

### ISSUE THREAD

**Issue by Tedster59** [KC3Kai/KC3Kai#1851]
- Your Chrome version - via chrome://version/: 56.0.2924.87
- Your OS and its version: Windows 7 Home x64
- 32bit or 64bit? 32 bit
- Your KC3 Kai version - via chrome://extensions/ latest dev version at this time

### Versions:
31.1.0 dev build (current version at this time), 30.0.7 webstore

### Steps to reproduce:
open the game.

### Actual behaviour:
game hangs at the black loading screen with bouncing ship after clicking play.

### Expected behaviour:
game opens

### Screenshots (if applicable):
not mine, but exact same issue.  this is from the discord.
http://i.imgur.com/tr3KXQp.png

I'm guessing this is chrome related, but who knows if kc3kai is causing it.

**Comment by dragonjet** [comment]
talked to the same person, this occurs even with kc3 not installed.
