### ISSUE TITLE
Dev version duplicates quests if dmm_takeover.js is loaded in manifest

### ISSUE THREAD

**Issue by Nya-chan** [KC3Kai/KC3Kai#1852]
- [x] Your Chrome version - 56.0.2924.87
- [x] Your OS and its version - Win10 stable
- [x] 32bit or 64bit? 64bit
- [x] Your KC3 Kai version - 31.1.0 Dev
- [x] Which build you have tried running? Github version latest (updated fork from Nya-chan/KC3Kai)
- [x] Screenshots which accurately paint the issue(s) you are facing. - see below
- [x] A step by step method that you did to describe how you got to that issue.

### Steps to reproduce:
Run the game and go to quest room.

### Actual behaviour:
Every quest appears twice. This is because pages/game/dmm.html contains the factory modules, but in the manifest.json I get library/injections/dmm_takeover.js loaded, and it duplicates the factory HTML on lines 82 - 96 when it tries to create its own factory.

### Expected behaviour:
They should only appear once per quest

### Screenshots (if applicable):
![Screenshot](https://cdn.discordapp.com/attachments/205766705463427072/284114247682621440/unknown.png)

**Comment by sinsinpub** [comment]
which game mode? r u using DMM frame mode?

as `dmm.html` should not used by new DMM website mode at all.

**Comment by reinforce** [comment]
This happened for me when I have both normal and development KC3Kai enabled. After disabling one of them all works fine.

**Comment by Nya-chan** [comment]
@reinforce Will try that, might be the cause.

**Comment by Nya-chan** [comment]
Yes, that fixed it. Closing the issue for now (though if @sinsinpub is right, I wonder how this can happen w)
