### ISSUE TITLE
KC3Kai panel not detected by the game launcher

### ISSUE THREAD

**Issue by HakenBrowning** [KC3Kai/KC3Kai#1853]
- Browser : Vivaldi 1.8.755.3 x64 (Chromium 56.0.2924.88)
- Tested OS : W7 Pro x64, W10 Pro x64
- KC3Kai 31.1.0, webstore version

My problem is simple : the KanColle panel in the DevTools aren't detected by the main window, which stays on the "Play Kantai Collection via KC3改" initial panel. As a consequence, when I choose to boot the game "without panel", the panel shows all the usual informations, but all the ingame tools doesn't work.

### Steps to reproduce:
Just try to play the game, and open the KanColle panel in the DevTools.
### Actual behaviour:
The web page doesn't detect the panel, and doesn't boot automatically the game. Furthermore, all the tools that are supposed to work ingame doesn't work (like translations).
### Expected behaviour:
Game boot automatically, and ingame tools work.
### Screenshots:
[2 screenshots](http://imgur.com/a/ovIbu), the first one for KC boot, and the second one ingame.

**Comment by mikenzb** [comment]
Might I ask what gamemode you are playing as, when you press "Play Kantai Collection" from the dropdown menu do use open up the dev panel right away and if so did you make sure "Apply Customizations" is enabled.

Otherwise it sounds like your playing via API link as that happens where the dev panel will get stuck on "'Waiting for game actions"

**Comment by HakenBrowning** [comment]
I edited my initial comment to add screenshots, sorry I posted too quickly. I use the "Customize DMM website" mode.

**Comment by HakenBrowning** [comment]
Just a little bump, updated Vivaldi to last snapshot, based on Chromium 57.0.2987.74 x64 and KC3Kai to 31.1.1. Still not detected.
