### ISSUE TITLE
Game window is not framed up in version 31.1.0

### ISSUE THREAD

**Issue by LostLogia4** [KC3Kai/KC3Kai#1856]
- Your Chrome version - 54.0.2840.87
- Windows 7 32-bit
- Your KC3 Kai version - 31.1.0 Webstore
- New DMM game mode

### Screenshots (if applicable):
![untitled](https://cloud.githubusercontent.com/assets/12930396/23347269/e346f128-fcdb-11e6-966f-fe671ac69c40.jpg)

### Error Report (if applicable):
For some reason the new DMM mode didn't crop the image properly for me. Do I need to update the Chrome to get the frame to work?

**Comment by sinsinpub** [comment]
😓 ...i guess u might give us more info by yourself, such as: `Apply Customizations` enabled or not? subtitles, quest TL works or not? what does console look like? r u enabled webstore & dev extension at the same time?

**Comment by LostLogia4** [comment]
I don't see the Apply Customizations in S4ettings, As for subtitles and quest TL, I didn't enable the former, while the latter is operational.

**Comment by LostLogia4** [comment]
Turns out that the Apply Customizations is located in the direct.html page, while I had bookmarked the dmm.html page and **skipped** through it none the wiser.
