### ISSUE TITLE
Vote for display method of slotitem (equipment) count

### ISSUE THREAD

**Issue by sinsinpub** [KC3Kai/KC3Kai#1860]
KC3 has displayed max equipment count using API value of `api_max_slotitem` at panel, which is 497 without any purchase. but I'm also wondering why KC game show equipment max count (limitation) always with `api_max_slotitem`+3 (500 by default) at in-game UI (including PvP opponent's info).

There should not be any problem because we have actually only owned 500-3 equipment, except one thing: our equipment count checking of panel not match with game's (max - 20) when sortie to an event map, which might confuse new player.

Wanna vote: how to fix this issue?
 1. Always add 3 to `api_max_slotitem`, so at panel will display `nnn /500` by default, which looks consistently in-game. But have to let ppl know there are 3 shadow (reserved) items
 2. Just update the checking condition: will not change to red color until max - 17 (eg: `480 /497`) exceeded. But this might also confuse ppl: why wiki says it's max - 20 😅

**Comment by Javran** [comment]
I would prefer just adding 3 to it. I doubt anyone would ever count the # of their equipments by hand. and even if someone does it, it's very possible that he is aware of this fact and wants to actually verify it.

**Comment by dragonjet** [comment]
during the earlier days I've told people it was like that because at that point, ships stop dropping since equipment slots are full, though I am not sure if that was true at all or if it applies if ever

**Comment by sinsinpub** [comment]
i guess kc devs just intend to return max-3 to client side, wanna reserve 3 slots so that even a ship with  4 equips dropping, equip count still will not exceed the max 😂 

@dragonjet prefer which method?

**Comment by dragonjet** [comment]
I also prefer 1, so seems we all agree :)
