### ISSUE TITLE
Relaying devtool logs into strategy room?

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#1866]
since we can now double click on devtool icons and the library content pops up in SR, I'm wondering if we can create a new SR dev-only page that relays devtool logs (or just call another function in place of `console.*` family). could be very useful for devlopers and perhaps help users to troubleshot. also that I'm using a tiling window manager so opening a devtool of devtool is not always convenient.

**Comment by 107nationalstation** [comment]
Is simply use service.js for sending logs to gamepage feasible? A switch of "console MODE" or "gamepage MODE" maybe useful for both people , I think.
