### ISSUE TITLE
Planes stuck in event LBAS

### ISSUE THREAD

**Issue by sanga000** [KC3Kai/KC3Kai#1875]
The planes that I put in event LBAS are still shown as in the LBAS team, even when I equip them on a kanmusu. The LBAS icon in the game interface also shows that the LBAS team needs resupply (a red outline at the icon)

The Reppuu in the picture is supposed to be equipped on a Kaga, even though it says it's still in the event LBAS team.
![default](https://cloud.githubusercontent.com/assets/26204896/23589858/4fca3ad8-0210-11e7-8a0b-ba32b6c805cf.png)

Version 31.1.1 (Webstore version)

**Comment by mikenzb** [comment]
Issue should be fixed I think, I don't have any event LBAS bases in KC3 anymore, reopen if issue still persists.
