### ISSUE TITLE
Some remodel-able ships in leveling tab don't get marked as such

### ISSUE THREAD

**Issue by Nya-chan** [KC3Kai/KC3Kai#1879]
### Versions:
Chrome: 56.0.2924.87
OS: Win7 Pro, updated, 64bit
KC3Kai: 31.1.1 webstore version update
DMM Website mode

### Steps to reproduce:
Have some ship that's ready for remodel, further info unsure

### Actual behaviour:
The ship doesn't get marked as being able to get remodelled, even if she has the level for it

### Expected behaviour:
The ship should get marked as being able to get remodelled

### Screenshots (if applicable):
![screenshot](http://i.imgur.com/kjKSV2j.png)

### Error Report (if applicable):
As you can see on the screenshot, Fusou gets tagged, but Yamashiro doesn't; even though she is high enough level. The same happens with my Bismarck Kai - she's level 50 / goal 75, but doesn't get tagged as being able to get remodelled.

**Comment by Vultren** [comment]
So it turns out the reason for this is due to a condition in the remodel button.
the last condition sets it only if the ships current level is higher than the remodel level.
