### ISSUE TITLE
Black Screen when trying to play KanColle in I-Frame

### ISSUE THREAD

**Issue by SaberOfWo** [KC3Kai/KC3Kai#1881]
### Versions: - Chrome version - 56.0.2924.87 (Official Build) (64-bit)
- OS; Windows 10, 64bit
- KC3 Kai version; 31.1.1
Webstore version, playing in an I-Frame

**Comment by Tedster59** [comment]
please see https://github.com/KC3Kai/KC3Kai/pull/1789

**Comment by SaberOfWo** [comment]
Thanks for the information, works now. ^^
