### ISSUE TITLE
Request translation repo access

### ISSUE THREAD

**Issue by Rys3t** [KC3Kai/KC3Kai#1887]
For traditional chinese.
I found some of tcn subtitles are missing.

**Comment by Vultren** [comment]
@Rys3t most of us fork the repo then add the original to the upstream

**Comment by Rys3t** [comment]
Sorry..i don't get it.
what's that mean?

**Comment by Vultren** [comment]
Let's see... here's some info. I'm bad at explaining this right.

https://help.github.com/articles/configuring-a-remote-for-a-fork/
https://help.github.com/articles/syncing-a-fork/

**Comment by Rys3t** [comment]
You mean i need to create a remote repository first?

**Comment by Vultren** [comment]
@Rys3t you already have remote. it's your Rys3t/kc3-translations repo

**Comment by Rys3t** [comment]
OK.So what else i should do?

**Comment by Vultren** [comment]
Ok, do you have git on your computer? if so, have you cloned your repo to your computer?

**Comment by Rys3t** [comment]
Like this?
http://imgur.com/a/OVqZC

**Comment by Vultren** [comment]
Close, you have git bash so open it move to the directory you want to save the repo to using the cd command. then use ` git clone https://github.com/Rys3t/kc3-translations.git` to clone the repo to the directory. jump into the repo using `cd kc3-translations`  and use the `git remote add upstream https://github.com/KC3Kai/kc3-translations.git` command from earlier. that will allow you to sync with the main repo. finally use `git fetch upstream` to get the main master branch. To update your branch, just use `git merge upstream/master`

**Comment by Rys3t** [comment]
If i made any mistakes,please tell me.
http://imgur.com/a/cmE77

**Comment by Vultren** [comment]
yes, that's right. Now all you need to do is add your changes in the data/scn and data/tcn folders. Once you do that [use the git add](http://stackoverflow.com/questions/572549/difference-between-git-add-a-and-git-add) command to stage the changes and `git commit -m <Commit Message>` to commit the changes (I think that's right, don't normally use straight terminal). Don't forget to add the commit message. once committed use `git push` to add to your origin/master branch. After that you can do a pull request with the main repo.

**Comment by Rys3t** [comment]
Well...Is it correct?
http://imgur.com/a/LDoPU

**Comment by Rys3t** [comment]
Well...Is it correct?
http://imgur.com/a/LDoPU
https://github.com/KC3Kai/kc3-translations/pull/399
