### ISSUE TITLE
What is this "Health Metric" in SR profile page?

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#1895]
I noticed this feature with very misleading description has sneaked into master branch:

> Not confirmed yet, but some proofs show that server counts them for you. And higher values you got, higher risk you would receive 201 catbomb.

Where is this "some proofs"? This is very wrong, otherwise every top 500 players should have been receiving 201 catbomb all the time.

I'll not repeat myself: **features with unconfirmed info should never go straight into master branch**. And I see no reason not to put this into our repo's guileline: **never put our user at risk of things like unconfirmed feature without proof, or any other untested features**.

From now on, I have zero tolerance of things like this. As long as I have the write permission to this repo, except a silently added & unconfirmed feature, or a buggy/untested one to be reverted at any time on master branch. And I encourage every developer to do the same - I'd rather having a commit war between developers than having a problematic release that upsets users.

**Comment by Javran** [comment]
And I also don't like the name "Health Metric", what we are developing is a helper that assists players in their gameplay, making them aware of concepts like LoS, air power, gunfit, etc. are fine, but I see no particular reason to force value like what is healthy and what is not to users.

**Comment by Javran** [comment]
we probably need to address this before next release or this might confuse our users:

- in FAQ section of SR profile page, either remove the statement about relation between catbomb and sortie count or show the actual proof: a link to some trustworthy website (wikiwiki, wikia) should be good enough. 
- rename "Health Metric" to just "Sortie Statistics"

**Comment by sinsinpub** [comment]
there is nothing untested or unconfirmed thing by counting sorties & battles. (conversely, somethings like gunfit are definitely unconfirmed yet)

the name & FAQ is intended to give the hint to those 'rankers' like u. however no matter what it says, i believe they will still be the 'ranker'. so i don't care about the name and desc at all, it's open to be changed.

stop bind me to moral roast rack, u r not referee for 'every users', those pointless reasons are off-topic 😂 
i DO NOT care about ur feelings or need ur tolerance. i'm not ur parents or doctor to teach u how to live a healthy life. u r upset just because u r fulfilled. 最后奉劝你一句：少修仙，多养肝。

**Comment by Javran** [comment]
@sinsinpub 

> there is nothing untested or unconfirmed thing by counting sorties & battles. (conversely, somethings like gunfit are definitely unconfirmed yet)

I'm saying the relation between sortie count and 201 catbomb. and yes, gunfit is definitely unconfirmed, and that's the exact reason why it has to be landed onto master branch through PR.

> the name & FAQ is intended to give the hint to those 'rankers' like u. however no matter what it says, i believe they will still be the 'ranker'. so i don't care about the name and desc at all, it's open to be changed.

so at least it's good that you are open to suggestions.

> stop bind me to moral roast rack, u r not referee for 'every users', those pointless reasons are off-topic 

My apology if it sounds like I'm binding you to something like that. I'm just saying "Health Metric" is too suggesting and we would prefer a more neutral way of describing it.

> i DO NOT care about ur feelings or need ur tolerance. i'm not ur parents or doctor to teach u how to live a healthy life. u r upset just because u r fulfilled. 最后奉劝你一句：少修仙，多养肝。

I'd like to inform you this discussion is about "Health Metric", not the gameplay style of mine.

but yes I admit I can lose my temper and you are one of the victim. have my apology for that.

let's be civil. remember: this is a project that we work as a team, it's important to communicate and have discussion about making changes. it's understandable that you directly push things like slight improvement or data update to master branch and I'm totally fine with it.

however, introducing features silently like this is not a good thing, you have known to keep doing so several times, causing many troubles and you didn't seem to have regreted doing any of those. For most of the time I was trying to be nice, chosing to live with it and suggested you not to do that again. but you don't seem to listen. so tell me, what else would you do if one doesn't listen?

What I don't understand is why, while we can do PRs and maintain good quality control, you keep pushing new features directly onto master, while some of them are great indeed, others are perhaps buggy or controversal. If you are doing this because you don't agree with guidelines, could we have your own opinion about it?
