### ISSUE TITLE
Got stuck after I choose a server

### ISSUE THREAD

**Issue by Federican** [KC3Kai/KC3Kai#1903]
Versions:
- Crhome: 57.0.2987.110 (64-bit)
- Windows 10
- 64bit
- KanColle Command Center 改 31.2.0
- Screenshot 
![error2](https://cloud.githubusercontent.com/assets/26515055/24078158/e1c534f6-0c33-11e7-8824-1ff8be0a9936.jpg)

 `I'm` new and I got stuck on this screen after selecting a server. Tried advise to change PC time to Japanese, but it didn´t work. What do I do?

p.s. There is another person with this issue, but i couldn´t find how to solve it.

**Comment by richarddoge8079** [comment]
Seems like an API/network problem, have you tried the cache clear method?

**Comment by Tedster59** [comment]
@Federican have you set your clock to the japanese time?  This is necessary when selecting a server on beginning your account.

**Comment by dragonjet** [comment]
you need to be on japanese timezone as well, not just on japanese time. setting it to JP time would actually make your system clock wrong since your timezone is still local.

**Comment by LostLogia4** [comment]
How about adding a check for matching the local time to the network JST and pop up the "Incorrect time locale error"?

**Comment by Federican** [comment]
Thanks, yes the problem was the time zone I already changed Time Zone to Japanese and now is working THANKS

**Comment by Vultren** [comment]
Looks like everything is good. Now Closing
