### ISSUE TITLE
Can't access the game

### ISSUE THREAD

**Issue by Demonarx** [KC3Kai/KC3Kai#1906]
### Versions:
 Chrome version - 57.0.2987.110
 Windows 8.1 
 64 bit
 KC3 Kai version - 31.2.0
 webstore version 
 Customize DMM Website
### Steps to reproduce:
doesn't even start 
### Actual behaviour:
not working
### Expected behaviour:
starting the game so i can play
### Screenshots (if applicable):

![fdsfsdqg](https://cloud.githubusercontent.com/assets/26529361/24085148/9fb30c58-0d39-11e7-8a26-0e462505707a.PNG)

**Comment by DynamicSTOP** [comment]
Hi @Demonarx !
Can you try the  [following](https://github.com/KC3Kai/KC3Kai/wiki/Startup-problems#i-am-on-the-latest-still-no-game-window-or-i-see-some-katakana-about-adobe-flash-player
)?

**Comment by Demonarx** [comment]
I tried everything on the guide but it's still the same problem

**Comment by DynamicSTOP** [comment]
@Demonarx 
Ok. Let's start with simple things. On your screenshot there is warning sign right next to Sources tab. 
![default](https://cloud.githubusercontent.com/assets/9434504/24156241/ba79a99a-0e5e-11e7-8901-0489b7a67969.png)
Can you switch from KanColle tab to Sources and check what it's saying? 
It might be something like "code on this page is not responding or slow" or anything else related to performance. In this case just allow it to continue by clicking play button. It should be in warning message or inside Sources panel on the top right. 
![default](https://cloud.githubusercontent.com/assets/9434504/24156330/f22f7cca-0e5e-11e7-8a41-8b3d631a24b3.png)

Or it can say that something is missing, etc. In that case you can try to remove extension and install it again.


If it's not the case i would like to know what have you checked on customization screen. Have you switched apply customization and which one? 
![default](https://cloud.githubusercontent.com/assets/9434504/24156389/123ec872-0e5f-11e7-88b4-2070c2956f1b.png)

Right now it looks like there are problems with javascript and it was paused by chrome. That warning sign shouldn't be there.

**Comment by Demonarx** [comment]
i just can't seem to find the problem in Sources
![qdsfsfq](https://cloud.githubusercontent.com/assets/26529361/24177143/c3546052-0ee3-11e7-8c6d-753119c8ae9e.PNG)

and it said that javascript is blocked in this page 
![sdfsdfq](https://cloud.githubusercontent.com/assets/26529361/24177183/0f94af08-0ee4-11e7-8ed7-0e85be135f81.PNG)

and also all my toggle features are applied
![cvvwxcvw](https://cloud.githubusercontent.com/assets/26529361/24177210/42cce5ac-0ee4-11e7-926f-15c4620f82b5.PNG)

**Comment by Vultren** [comment]
You might want to unblock that. the extension runs on JS.

**Comment by Demonarx** [comment]
since i tried everthing and nothing worked i thought that the problem might be in chrom
so i uninstalled it and reinstalled it and now everything seems to work
thx for trying to help

**Comment by DynamicSTOP** [comment]
Added to startup problems page. 
Thanks for your report.
