### ISSUE TITLE
[Solved] I don't know what is wrong

### ISSUE THREAD

**Issue by Sabie** [KC3Kai/KC3Kai#1908]
NOTE: The KC3 kai functions however remains 100%, it did what it was supposed to do and it is did so perfectly, it was just that KC3 kai looks to me like it smokes some weed when I started it up. 

### Screenshots (if applicable):
The update page:
![uni 5](https://cloud.githubusercontent.com/assets/26548457/24107896/3fb4f63a-0d49-11e7-8fa4-ef59f16e4e2f.png)

![uni 2](https://cloud.githubusercontent.com/assets/26548457/24106922/9ba72b14-0d46-11e7-88d0-78854d4174fb.png)
This is the very thing I notice that some of the content are being put in different places

![uni 3](https://cloud.githubusercontent.com/assets/26548457/24107048/fb94935e-0d46-11e7-97b3-b4387708b527.png)
The KC3 kai look on start up

![uni 3](https://cloud.githubusercontent.com/assets/26548457/24107166/498539f6-0d47-11e7-9bcf-28421e92a856.png)

![uni 3](https://cloud.githubusercontent.com/assets/26548457/24107275/8a4701d6-0d47-11e7-836f-80f8396ba79f.png)
ON battle

Strategy room suffers the same fate, some of the sentences are oddly spaced
![uni 4](https://cloud.githubusercontent.com/assets/26548457/24107398/d59b1d34-0d47-11e7-91d9-5af1346a4349.png)

![uni 4](https://cloud.githubusercontent.com/assets/26548457/24107440/f1a78148-0d47-11e7-8a45-a9ba71abfe72.png)

**Comment by HitomaruKonpaku** [comment]
Did you try disabling all other extensions?

**Comment by Sabie** [comment]
I have not, but I only have adblock plus and I am sure Google docs is not the culprit. I have tried the set up in a fresh Chrome and still receive problem. ?? I am suspecting script setting for Privacy setting.

**Comment by Sabie** [comment]
Reinstall chrome and KC3 kai helped me.
