### ISSUE TITLE
Extension update notifications

### ISSUE THREAD

**Issue by DynamicSTOP** [KC3Kai/KC3Kai#1911]
![default](https://cloud.githubusercontent.com/assets/9434504/24156820/51f4f42c-0e60-11e7-9276-377d21121e0f.png)
:D

To prevent people from cursing next person in charge on a days when there are going to be release i suggest we start using update notifications. 

The idea is quite simple. I am 70% sure chrome won't allow us to make ajax requests outside of chrome://extension&dmm.com sandbox because of CORS and whatever else security rules, but we can use [gh-pages branch](https://pages.github.com/)  in which we ask for notification subscription and register some background js worker that will check once in a while for a version or txt file or anything else in that branch.

In an hour before merging to webstore we can update that file and people will see that at some particular time new version will be released and they better update before going to world6 boss or event LD.

What do you think?

**Comment by DynamicSTOP** [comment]
![default](https://cloud.githubusercontent.com/assets/9434504/24171092/bed83d4e-0e8b-11e7-8251-292b392eacc9.png)
No need for gh-pages though would be nice to have.

I think it would be even better to show it in kc3 tab inside devtools like new equip\ships so nobody will miss it.

**Comment by gensuihime** [comment]
External AJAX requests can be made iirc, just has to be to full addresses.

**Comment by DynamicSTOP** [comment]
yeah, just tried on https://raw.githubusercontent.com/KC3Kai/KC3Kai/master/update
the only thing to discuss is where would we store update info

**Comment by gensuihime** [comment]
Also speaking of this topic, it'd be kind of nice if KC3 didn't just open a new tab for update info without warning for the user. That's getting on people's nerves and I've had several people complain about it.  

Add an option to make it minimal intrusive maybe?

**Comment by DynamicSTOP** [comment]
I think it was more like chrome doing this, not us. Not sure.

**Comment by gensuihime** [comment]
I've never seen anything written that Chrome does this by default. There can't be a requirement for a new tab per update.
Since the update page is (presumably) autogenerated by what I can assume is JS, it has to be the extension.

**Comment by sinsinpub** [comment]
i can't get what are your real needs...?

@DynamicSTOP the 'cursing' has already gone. extension auto-updating by chrome will not cause kc3 forced auto-reload (or call it 'restart') any more. instead, kc3 detects and handles the onUpdate event, pop up the 'update page' (or desktop notification) to let user choose the timing to reload with updated extension.

@gensuihime as i mentioned above, the new tab of kc3 'update page' is not the only choice, have u and those guys tried this setting option?
![image](https://cloud.githubusercontent.com/assets/160240/24179742/f12ed87e-0eeb-11e7-9315-b3b4573e794b.png)

i'm glad that more ppl get passion to involve in kc3 project, but i do recommend all ppl who are new for kc3 (or even kc game), read and understand codes & mechanisms carefully before getting in.
there is a longer story about the update checking design, i may type more words for u if there is still problem.

**Comment by DynamicSTOP** [comment]
Sweet. No need for notification then. I was using dev version for more then half a year, so i wasn't having this problem at all.

**Comment by DynamicSTOP** [comment]
@sinsinpub 
guess i'll have no other choice then spend a weekend on understanding how kc3 actually works.

Since i guess you are the most experienced from all who is still going to work on kc3 could you tell what are the generals kc3 goals now? 
The only thing i was aware of is dj planning to move everything from devtools to page.

**Comment by gensuihime** [comment]
@sinsinpub
Maybe make some valid documentation before telling me I don't know anything - of course I don't. That's like asking to fix an engine without the blueprints. Mhm. Anywho, thanks for the info. Maybe make it popup default...
