### ISSUE TITLE
Write Req

### ISSUE THREAD

**Issue by gensuihime** [KC3Kai/KC3Kai#1912]
I wish to begin fixing issues and making mergereqs but since I have no idea who runs this shebang anymore, I don't know who to ask for write access. 
Normally I'd wait for DJ but irl work dictates that I have limited timeframes to contribute to this and thus I'm pushing this ahead on my timetable. I have seen this project since day 1 and do not wish to see it wither. So before I forget, I'm posting this. It's not an actual "issue" per se so I'll close after someone sees.

**Comment by Tedster59** [comment]
@dragonjet should be able to invite you to the project and give you permisisons.  I'm not really a programmer, but I have the ability to approve pull requests.

**Comment by gensuihime** [comment]
Still waiting on that after DM. Rip me

**Comment by gensuihime** [comment]
At this point in time, I've waited 24 hours for a response. If anyone can give write access I'd greatly appreciate it. I've already stated I'd join the project...

**Comment by gensuihime** [comment]
Actually, since I'm here and I saw that comment,
@sinsinpub you seem to be round these parts often. Can you change permissions around?

**Comment by Nya-chan** [comment]
@gensuihime You don't need write permission to start working - fork a copy, make changes, make a pull request.

**Comment by Tedster59** [comment]
^^^

**Comment by gensuihime** [comment]
The way I read DJs post everyone has the same perms. 
I may volunteer work but I am a stickler when it come to things in writing. It's not like this is hard since this project has no central management.

**Comment by gensuihime** [comment]
You either stick to the agreed rules or don't make rules at all.

**Comment by gensuihime** [comment]
@Nya-chan @Tedster59 I understand I can do work without Write pemissions but without writeperms, for one I can't close any issues, add documentation, or do ANYTHING without waiting for someone. I will never push anything to the branch without making a merge request but no write access effectively neuters my ability to edit the project in any form.

**Comment by gensuihime** [comment]
If this was a larger project with say, 20+ People I wouldn't fret but the only reason I am here is because I heard from a friend that this project is on unstable footing. Under that premise I would, once again, like write permissions.

Sorry for the fragmented message.

**Comment by dragonjet** [comment]
hi @gensuihime sorry for delay in response, I posted again in #1909 about my concerns before we proceed to permissions.

**Comment by Nya-chan** [comment]
@gensuihime Sorry for the notice, but this is still a free-time project. People have life and work and you shouldn't rush this stuff so much. It look aggressive, honestly.

**Comment by dragonjet** [comment]
@gensuihime I invinited you to KC3 github org, but on a team that still doesn't have write perms to the repo. However, I will add this team to write once the re-branding is cleared up. will close this for now.

**Comment by gensuihime** [comment]
Kk thx
