### ISSUE TITLE
Moving primary KC3 window out of developer tools panel?

### ISSUE THREAD

**Issue by gensuihime** [KC3Kai/KC3Kai#1921]
So, this has been bugging me since day one.

Why must KC3 be run inside the developer tools panel? (f12) 
It could just as easily be either 1) run inside the window Kancolle runs in, either as a sidetab or lower part of window, or 2) run in a separate popup window/tab. Not a huge problem but it's always bugged me and as a web designer, never made sense when there are many better ways to go about it.
I's like to hear thoughts on this.

**Comment by Nya-chan** [comment]
You can pop devtools panel out: ![Popped out](https://i.imgur.com/KVDNLL2.png)

**Comment by dragonjet** [comment]
two main reasons:

* `chrome.devtools.network` API is only accessible under the devtools environment. [docs](https://developer.chrome.com/extensions/devtools_network)
  * panel html/js is the only one who can receive network response bodies and thus process the data
  * an alternative is relay that data to background script, and send it to whereever UI would show it, but defeats the purpose of below

* people who play via DMM website (where in 99% of KC3's lifetime didn't have UI customizations), can still benefit from the information without worry of how we embed the viewer

**Comment by ethrundr** [comment]
As my memory serves, this topic has been discussed, suggested and then dropped for too many times to be counter properly.

The main reason is that some of the functionality inside KC3 requires the use of Chrome Devtools.

On the other hand, there is never lack of suspicion to our extension (and all other viewer as well) regarding what we do with the data. By using a different UI into a standalone viewer, undoubtedly there will rise concern that what we do with the data along the way. This concern is somehow lesser if we use this approach, as more people able to plainly see that the game itself is able to be played with or without the panel, which in the end, strengthen our claim that we only read and redisplays the data in a way user can easily understand -and nothing else out of it- (and which we really did).

**Comment by gensuihime** [comment]
Quite interesting. For those that use non-DMM website view though, it wouldn't hurt to implement non-devpanel window?

**Comment by Nya-chan** [comment]
Those are being slowly abandoned anyway because of Chrome issues, though.

**Comment by gensuihime** [comment]
@ethrundr Most end users aren't knowledgeable enough in this matter to actually know the details on how data is handled. But you do have an interesting point. Also it doesn't really change the functionality of the app anyway, just aesthetic issues.

Closed.

**Comment by ethrundr** [comment]
@gensuihime If you kept on the update and try to ask around, you'll be surprised seeing how much people doubted what we're doing with the data, especially when ban-fest is happening.

Some of them even go further and claim that our extension is the fault of those ban-fests.

**Comment by gensuihime** [comment]
There will always be dissenters but then again, making any product and releasing it means the developers acknowledge this. The code is open source so claims are not really valid without proof.
