### ISSUE TITLE
Documentation. You know, that thing that makes thing legible

### ISSUE THREAD

**Issue by gensuihime** [KC3Kai/KC3Kai#1925]
So, this project still suffers from lack of documentation. Any plans on adding this, as the people who actually coded before are now mostly MIA. It's not easy to pick up from bread crumb trails.

Or am I looking in the wrong place when there is documentation somewhere.

**Comment by gensuihime** [comment]
Something like one of my old projects:
https://github.com/vgstation-coders/vgstation13/wiki

**Comment by ethrundr** [comment]
We used to have a proper documentation per update released in our wiki, until around v28 or v29.

After that, most of the people here go too busy to have time updating it.

**Comment by ethrundr** [comment]
Discussion moved to #1928 
Label this as duplicate and closed.
