### ISSUE TITLE
Alignment issue with 31.3.0

### ISSUE THREAD

**Issue by Sinnermighty** [KC3Kai/KC3Kai#1931]
I just updated to 31.3.0 this morning, and now everything is horribly out of alignment. It was perfectly fine before this update.

### Versions:
- Chrome version - 56.0.2924.87 (Official Build) (64-bit)
- Windows 10 Home x64
- KC3Kai 31.3.0
- Webstore build
- The new Play Kantai Collection

### Steps to reproduce:
- Not sure how to reproduce, I just updated to the latest version and this is what I got.

### Actual behaviour:
Everything related to the extension seems out of line. The menu from the KC3 button, the landing page, the update page, and the game screen itself. 

### Expected behaviour:
Not be out of line.

### Screenshots (if applicable):
http://imgur.com/a/Xw60q

**Comment by Nya-chan** [comment]
This seems to happen from time to time to some people, no idea why so far (maybe some extension caching?). If you export KC3Kai data - reinstall - import KC3Kai data, it should get fixed.

**Comment by MegaAbsol** [comment]
Probably some files are broken; try exporting your game data, uninstalling+reinstalling kc3kai, and re-importing it?

**Comment by Sinnermighty** [comment]
That fixed it thank you. Backed up data, reinstalled and reimported. http://i.imgur.com/xFEdSnR.jpg
