### ISSUE TITLE
Event difficulty not hiding after closing fleet/nodes

### ISSUE THREAD

**Issue by Tibo442** [KC3Kai/KC3Kai#1932]
Event difficulty not hiding after opening and closing fleet/nodes buttons.

[Example](https://streamable.com/ben7h)
![Image](https://cloud.githubusercontent.com/assets/5676386/24334544/47aeb02e-126c-11e7-9da8-81b3c4d19f58.png)

**Comment by Nya-chan** [comment]
Fixed in #1941
