### ISSUE TITLE
Revamp the HP counter

### ISSUE THREAD

**Issue by Nya-chan** [KC3Kai/KC3Kai#1934]
The comment which I partially agree with, especially since the feature hides current (post-battle) HP amount: https://www.reddit.com/r/kancolle/comments/61n3r0/the_admirals_lounge/dfgfsq5/

Offered solution:
- revert the HP counter above the line to the old format (XX / YY)
- add the subtraction (- ZZ) directly to the HP bar

**Comment by sinsinpub** [comment]
move -hp to hp bar neither make sense. will be this (min default font-size 12px)
![image](https://cloud.githubusercontent.com/assets/160240/24350634/829e8908-1315-11e7-827d-c8fd9be169f7.png)

the only solution is an option for it. we are not their chef, will not feed everyone's favorite tasting.

**Comment by Nya-chan** [comment]
The hiding of a resulting HP state is a real issue, though. While now it shows the difference (which was hidden before), it also hides the result (which was not hidden before). We should ideally show both in some form - and if we're not showing both, the previous version was more user-friendly.

**Comment by sinsinpub** [comment]
> it also hides the result (which was not hidden before)

what u mean? it hides nothing, but only ` it shows the difference (which was hidden before)`

**Comment by Nya-chan** [comment]
There are three things:
- Initial HP (example: 70)
- Damage (example: 10)
- Resulting HP (example: 60)

31.2 and before showed Resulting HP / Initial HP (Damage was hidden)
31.3 shows Initial HP - Damage / Initial HP (Resulting HP is hidden)

**Comment by sinsinpub** [comment]
> 31.2 and before showed Resulting HP / Initial HP (Damage was hidden)

it's wrong, **before the next battle phase api call**, it only show 'Initial HP / Initial HP'

**Comment by Nya-chan** [comment]
Just tested it and you're right - then why not show something like Resulting HP / Initial HP (- Damage)?

**Comment by Nya-chan** [comment]
> how those users bare it

Can't understand that? :)

Anyway, it seems that we have a way to count the current HP (even though there's now a fourth value, apparently, Maximum HP)... and it should show somewhere, I think. I'll try to think of something and let you know here.

**Comment by Nya-chan** [comment]
> before battle result screen, the intermediate or final result hp can be gotten by simple subtraction.

That's exactly user unfriendly, though - nobody is going to "simply subtract" if they can avoid it :)

**Comment by Nya-chan** [comment]
How does this look like? Had to make the HP bar a bit taller, but the difference isn't that big, IMO.

![Screenshot](https://i.imgur.com/oS1Ezrv.png)

**Comment by ethrundr** [comment]
IMO, I like better the initial idea to show just the difference over the HP bar.
They can calculate the initial HP themselves by adding the difference shown with the current HP provided above the bar.

Don't feed people with too much convenient, they'll just ask for more.

**Comment by Nya-chan** [comment]
Implemented in #1941
