### ISSUE TITLE
Screenshot broken in multiple ways

### ISSUE THREAD

**Issue by Adrymne** [KC3Kai/KC3Kai#1936]
Identified 3 ways to break Screenshots. Fixes are currently a WIP.

1. Reload the extension from source, then try to take a screenshot.

Causes the `TMsg` sent from [`screenshotSpecialMode`](https://github.com/KC3Kai/KC3Kai/blob/383885db10ad60e4f3af2d141b62a72e8f781dd4/src/library/modules/Service.js#L559) to set `offset` to undefined. `chrome.runtime.lastError.message` gets set to "Could not establish connection. Receiving end does not exist".

(I don't think we need to fix this one; a regular user will probably never run into this, and it's easy to create a workaround for testing purposes.)

2. Take a screenshot with Output Mode set to "Imgur" (Filetype agnostic)

`ReferenceError: KC3Database is not defined` gets thrown from [`Screenshot.success()`](https://github.com/KC3Kai/KC3Kai/blob/383885db10ad60e4f3af2d141b62a72e8f781dd4/src/library/objects/Screenshot.js#L217).

3. Take a screenshot with Output Mode set to "New Tab" and Filetype set to "PNG".

Will sometimes open an empty tab. [`base64img`](https://github.com/KC3Kai/KC3Kai/blob/383885db10ad60e4f3af2d141b62a72e8f781dd4/src/library/objects/Screenshot.js#L229) is still being created correctly, so I suspect it's running into chrome's [URL size limit](https://bugs.chromium.org/p/chromium/issues/detail?id=69227).

There was also a report of it breaking with Output Mode set to "Download" and Filetype set to "PNG", but I was not able to reproduce it.

**Comment by DynamicSTOP** [comment]
Sometimes, for example during event LD, people expect screenshot feature to work any possible way it can. So i have a suggestion to add couple fallbacks.

- If any of two requests to imgur failed (ajax `error`), try new tab.
- If new tab failed (was using this in showcase exporter `dataURL.length >= 2 * 1024 * 1024`), do download.

**Comment by Adrymne** [comment]
Rather than checking the length each time, I was going to go with the suggestion in the linked thread and use a [blob URL](https://bugs.chromium.org/p/chromium/issues/detail?id=69227#c47) in all cases.

Good point regarding fallbacks. Maybe have a default order (download > new tab > imgur perhaps) then hoist the selected option?

**Comment by DynamicSTOP** [comment]
grabbing this blob idea for showcase exporter update

**Comment by Adrymne** [comment]
Fixed by #1948
