### ISSUE TITLE
Buggy Battle Replayer interface

### ISSUE THREAD

**Issue by Accelyte** [KC3Kai/KC3Kai#1940]
I believe this is unrelated to the extension, but since it's on the same repo I decided to post it here.
KanColle Battle Replayer v1.4.6

I'm on a laptop and the frames are out of place without a horizontal scrollbar. I had to use my mouse scroll wheel.
![chrome_2017-03-28_23-55-34](https://cloud.githubusercontent.com/assets/21363469/24431145/2aeb2d3a-1412-11e7-906f-2da879b0d25e.png)
![chrome_2017-03-28_23-55-44](https://cloud.githubusercontent.com/assets/21363469/24431146/2b0f1f4c-1412-11e7-98d6-cd04cbf0d692.png)

If you zoom out with the webpage in the wrong position, the webpage is locked. (I tried clicking my mouse scroll wheel but there is no response. Refreshing does not work either. This is only fixed if I go back to 100% zoom)
(P.S. If you open the fleet details and then zoom out you can scroll with the mouse scroll wheel again.)
![chrome_2017-03-28_23-58-27](https://cloud.githubusercontent.com/assets/21363469/24431193/751d1990-1412-11e7-81fd-11759073e759.png)

This makes the replayer quite unusable. The old interface worked better.

**Comment by Tedster59** [comment]
pinging @fourinone41 as this is his area.

**Comment by Vultren** [comment]
Can you give some specs? browser type, version. I just pulled the current build, and I don't see the problems that you are having. Can you check what the console says as well.

**Comment by HitomaruKonpaku** [comment]
@Accelyte can you tell me your screen resolution?

**Comment by Accelyte** [comment]
Using the latest Chrome, on 1366x768.
I'm guessing it's screen resolution that's messing it up, but I don't have a 1080p screen to test my theory.

**Comment by HitomaruKonpaku** [comment]
@Accelyte Can you try disable all other extension then load the web again? My resolution is 1366x768 and it still work fine

**Comment by ethrundr** [comment]
@Accelyte this may seem to be dumb, but have you check the zoom level for the specific replayer page?

Chrome has tendency to keep remembering zoom level for a certain page/domain, and will kept displaying zoomed content until it was manually reset.

**Comment by Accelyte** [comment]
That's what I was messing around; I know the zoom locks per webpage.
I recently tried opening the site on another computer, bit there wasn't a problem. Seems like my laptop/Chrome setup is the culprit. I'll keep it updated, it's probably another plugin. (Proper Blocker blocked the Macromedia Flash settings page, and I had gone through all the effort of resetting my chrome...)

**Comment by Accelyte** [comment]
Hmm...it seems to be working again. I didn't change any other settings or plugins. This is weird, but I guess the problem solved itself.
If something happens again I'll make a new thread. Thanks for the debugging help.
