### ISSUE TITLE
Itemcapacity is slightly off

### ISSUE THREAD

**Issue by newttk** [KC3Kai/KC3Kai#1943]
### Versions:

31.3.0

(From my point of view this issue has stared with 31.2.0 )

### Steps to reproduce:

Look at the panel / Try too craft something

### Actual behaviour:

The panel shows, that I've currently 1137 of 1140 items ( currently I've 260 Ship Slots). 

### Expected behaviour:

I can only have 1137 items (so no more drops/or crafting is possible), so the shown maximumnumber is wrong.

### Screenshots (if applicable):

![craft-pic](https://cloud.githubusercontent.com/assets/24959150/24513227/a281c2f6-15ab-11e7-98b1-895eea43bef1.PNG)

### Error Report (if applicable):

**Comment by Vultren** [comment]
this isn't a bug. they changed the display to include the 3 equips you can hold from drops, but that prevents you from building/crafting. I think that was what was said on the discord

**Comment by sinsinpub** [comment]
see #1860 nothing wrong, the same with game 😺
