### ISSUE TITLE
Monthly Reset broke KC3

### ISSUE THREAD

**Issue by Tedster59** [KC3Kai/KC3Kai#1944]
while not a proper issue report, a large number of sources are reporting that KC3kai has stopped working as of the monthly reset, either stuck at "waiting on game actions" or not updating mid sortie, including things like this.

http://i.imgur.com/lRmCExS.png

notgood.jpg

**Comment by Agc0de6** [comment]
All the same
![2017-04-01](https://cloud.githubusercontent.com/assets/14156630/24567827/bf0b1238-1678-11e7-85f7-434a82978fba.png)

**Comment by Vultren** [comment]
this has now been fixed
