### ISSUE TITLE
"Stuck in waiting for game actions"

### ISSUE THREAD

**Issue by Shinano-H** [KC3Kai/KC3Kai#1949]
- Chrome: 57.0.2987.133
- Win 8.1
- 64bit
- KC3: 31.3.1
- Webstore version as in the one from [Chrome Web Store](https://chrome.google.com/webstore/detail/kancolle-command-center-%E6%94%B9/hkgmldnainaglpjngpajnnjfhpdjkohh)

Description of issue:
KC3 patched automatically to latest version which is KC3 31.3.1 now I am unable to even load up the game all I see is the DMM blue background and the control panel saying waiting for game actions. This issue occurred previously only once however I was able to still play using DMM frame while I waited for patch. This current problem is on all version so DMM custom, DMM frame, and API link. I have tried reseting cookies and even tried VPN but no joy.

![kancolle issue](https://cloud.githubusercontent.com/assets/26857831/24590209/4d786a14-1824-11e7-9f59-7b2b7be81974.JPG)

**Comment by DynamicSTOP** [comment]
Hi!
1. From your screenshot it looks like you have 2 errors. Please switch to **console** tab and show us errors.
2. Are you able to play without KC3 ?
3. Do you have any extension that might block Flash or JavaScript?

**Comment by Shinano-H** [comment]
![kancolle issue 2](https://cloud.githubusercontent.com/assets/26857831/24590839/4703724a-182f-11e7-801a-7f2ac525c569.JPG)

I am tried playing without KC3 and still unable, and no I am not running anything that is blocking Flash or Javascript

**Comment by DynamicSTOP** [comment]
looks like same as #1917 
try to follow steps in this [comment](https://github.com/KC3Kai/KC3Kai/issues/1917#issuecomment-290715322)

**Comment by FOG-Yamato** [comment]
A fix to this is to clear your browser cache, fixed it for some users.

**Comment by Shinano-H** [comment]
So I have done all the above and still it doesn't work, however I did figure out the only way to play is to manual go to the DMM site and open it up there then open up the control panel

**Comment by ethrundr** [comment]
Have you tried open the natural DMM site gameplay without the customization?

**Comment by Shinano-H** [comment]
After opening it by the default DMM site without customizations it worked, and then I applied F12 to bring it up the control panel again and the problem seemed to resolve itself. It's safe to say you can close the ticket.
