### ISSUE TITLE
Update Tab cause flash plugin crash.

### ISSUE THREAD

**Issue by htomeload** [KC3Kai/KC3Kai#1954]
I saw mortification about update and when go to update page, it load a lot of abyssal ship and it cause flash plugin crash. I saw new weapon in update tab. :3

- Chromium 56.0.2924.76
- Ubuntu 16.04 LTS x64

### Steps to reproduce: 
- Open update tab in Strategy Room.
- Tab load update information.
- Plugin load CG of abyssal ships.

**Comment by ethrundr** [comment]
Abyssal CG IDs are being pushed into ID 1500s from the original of ID 500s

We're on our way implementing the fix, please wait for the update.

**Comment by Vultren** [comment]
With 31.4.0, this should be fixed so closing
