### ISSUE TITLE
Text and icon size option?

### ISSUE THREAD

**Issue by URSvAir14** [KC3Kai/KC3Kai#196]
I'm finding it difficult to read some of the text on the panel of the new version. Namely:

In battle mode:
- All text in the "fighting/ next node" panel that gives you the information of the current battle
- Everything in the "ship panel" (icons, names, ship type, health, and experience in particular)

In HQ mode:
- Everything in the "ship panel" (icons, names, ship type, health, and experience in particular)
- Expedition icons and expedition number

I'm finding that I still have maybe 100 pixels of empty vertical height with v10's layout on my smaller monitor, with a good 300 or so pixels of vertical height free on my biggest monitor. May it be possible to have text and icon size options to make it easier to read?

**Comment by LostLogia4** [comment]
Uh, uh, yeah. I've switched to the latest version and my first reaction in there are things my eyes can't quite unsee.
To wit:
- Ship list in Strategy Room now have pages. Forget it's massive font size,  it's has no spacing to speak of, which results to unreadable mess of list.
- The big box at the bottom right of the Admiral Panel is taking up quite a lot of space, which makes the fleet panel looking simply too small right now. Besides, can't you make the remaining fuel toggle available as well?
- Battle mode panel is okay, except that the "/" is missing from the available ship and equipment slots resulting in one big 100 number against one small 1XX.

**Comment by bamboo3250** [comment]
The variance of monitor size is a big concern here. Perhaps we may need options to choose for Small / Medium / Big size but the problem will come up when we update/add more features for the Panel.

**Comment by nicky008** [comment]
This quest timing font problem had been insisted me for many days when I firstly used the older version (around 8th), until my eyes already can deal with it.

The battle mode panel font size is alike the quest timing font's...

**Comment by bamboo3250** [comment]
For now, the size of Horizontal Layout is 550x450 and Vertical Layout is 800x300. The game screen is 800x450. When adding them together, we have:
- Game + H-Layout: 1350x450
- Game + V-Layout: 800x750

Some of common screen resolutions are: 
-* 1920x1080
-* 1366x768 (I'm using this)
-* 1280x1024
-* 1280x800
-* 1024x768
-* 800x600
 
So V-Layout can extend its height 300px more for `1920x1080` and 200px more for `1280x1024`. Meanwhile, H-Layout still can double its width for `1920x1080` but now it looks okay to me.

Maybe I can add more Javascript for V-Layout to deal with those large screens without creating another theme only for that.

**Comment by dragonjet** [comment]
@LostLogia4 the page numbers are actually intended, they're like peeking from behind the list since I also don't want them to take too much space. However, it is planned to have a button to enabled/disabled paging.

@nicky008 sorry, which one is the quest timing?

**Comment by nicky008** [comment]
@dragonjet  Ah, here...
![capture](https://cloud.githubusercontent.com/assets/10517990/8632134/510b1ea8-27c9-11e5-8865-c15b0df38286.PNG)

**Comment by nicky008** [comment]
@dragonjet Ah, this...
![capture3](https://cloud.githubusercontent.com/assets/10517990/8632731/fc122486-27e2-11e5-885a-8b327f6827a2.PNG)

**Comment by LostLogia4** [comment]
Mostly handled already quite some time ago, closing.
