### ISSUE TITLE
The game won't start and I'm getting an error message, started after I updated my chrome. 

### ISSUE THREAD

**Issue by MouretsuYuki** [KC3Kai/KC3Kai#1961]
### Versions:
Google Chrome:	57.0.2987.133 (Official Build) (32-bit)
KC3: 31.4.0

### Steps to reproduce:
Trying to start the game through KC3 kai
### Actual behaviour:
I get a error where the game won't load, with an error message in Japanese
### Screenshots (if applicable):
http://i.imgur.com/IL62AUW.png

**Comment by MouretsuYuki** [comment]
Nope, It was working earlier, then I updated chrome, restarted my browser and got this error.

**Comment by Vultren** [comment]
check chrome://components/ to see if you have flash updated

**Comment by MouretsuYuki** [comment]
I just updated flash and I'm still getting the same error.

**Comment by sinsinpub** [comment]
hey, just click the blue phone&pad icon here...
![image](https://cloud.githubusercontent.com/assets/160240/24782612/de6cad7a-1b79-11e7-995c-7e4c6f190d4b.png)

**Comment by MouretsuYuki** [comment]
Thank you so much! I knew it was something stupidly simple that I was missing. You're a life saver xD
