### ISSUE TITLE
Wrong air power values on the Land Bases tab

### ISSUE THREAD

**Issue by Bararun** [KC3Kai/KC3Kai#1964]
Chrome version: 57.0.2987.133 (64 bits)
OS: Windows 8.1
64 bits
KC3 Kai version: 31.4.0
Webstore version.
Play mode: Customized DMM website.

Steps to reproduce: Fill out the Land bases with the portrayed Land Base bombers on the screenshot. Try to get Air parity 6-5 Boss with CV Hime and 2 Wo flag.

Actual behaviour: air values on the kancollecalc screenshot (http://kancollecalc.web.fc2.com/air_supremacy.html)

Expected behaviour:  Air values on the KC3 screenshot

 Screenshots:

![airpower](https://cloud.githubusercontent.com/assets/8206011/24866833/a98f2c56-1e0b-11e7-89fc-e172eeac18a2.png)

**Comment by sinsinpub** [comment]
show me your settings of here:
![image](https://cloud.githubusercontent.com/assets/160240/24871521/6bae59fc-1e4c-11e7-96c8-b76446fc78b2.png)

**Comment by Bararun** [comment]
Air Whole Number Bonus

{"6":[0,1.35,3.5,7.1,11.4,16.8,17,25],"7":[0,1,1,1,2,2,2,3],"8":[0,1,1,1,2,2,2,3],"11":[0,1,1,3,3,7,7,9],"45":[0,1.35,3.5,7.1,11.4,16.8,17,25],"47":[0,1.35,3.5,7.1,11.4,16.8,17,25],"48":[0,1.35,3.5,7.1,11.4,16.8,17,25],"57":[0,1,1,3,3,7,7,9]}

Air Min-Max Bonus

{"6":[[0.026,0.845],[1,1.715],[3.212,3.984],[6.845,7.504],[11.205,11.786],[16.639,17],[16.999,17.205],[24.679,25.411]],"7":[[0,0],[0,1],[0,1],[0,1],[1,2],[1,2],[1,2],[1,3]],"8":[[0,0],[0,1],[0,1],[0,1],[1,2],[1,2],[1,2],[1,3]],"11":[[0,0],[0,1],[0,1],[1,3],[1,3],[3,7],[3,7],[7,9]],"45":[[0.026,0.845],[1,1.715],[3.212,3.984],[6.845,7.504],[11.205,11.786],[16.639,17],[16.999,17.205],[24.679,25.411]],"47":[[0.026,0.845],[1,1.715],[3.212,3.984],[6.845,7.504],[11.205,11.786],[16.639,17],[16.999,17.205],[24.679,25.411]],"48":[[0.026,0.845],[1,1.715],[3.212,3.984],[6.845,7.504],[11.205,11.786],[16.639,17],[16.999,17.205],[24.679,25.411]],"57":[[0,0],[0,1],[0,1],[0,1],[1,2],[1,2],[1,2],[1,3]]}

**Comment by Bararun** [comment]
Ok, looks like I had these values modified. I don't even know when it happened but I guess that settles it

**Comment by sinsinpub** [comment]
u may not modify them, just they are updated (or fixed). these settings make it possible to let pro player (like wiki editor) have their own values for verifying, but make us not able to update them without user's manual confirmation 😓 
just remember to have a check at update logs, don't miss a notice:
![image](https://cloud.githubusercontent.com/assets/160240/24887794/49ecd2f4-1e91-11e7-9288-723a36c0e37b.png)
