### ISSUE TITLE
[Suggestion] Blinking the resourse when its reach max regen cap 

### ISSUE THREAD

**Issue by quzzimi** [KC3Kai/KC3Kai#1967]
As suggested 
can u guy made the resourses in "BASIC" tab  blinking when it reached it max soft cap depend on HQ level ? 
even better if it show how many res to soft cap / how long to natural regen reach soft cap when hover it

**Comment by Nya-chan** [comment]
Blinking is probably no-go (unless it's in settings), since some people spend loooots of time above softcap during stockpiling. But changing colour is likely possible for all capped resources?

**Comment by FOG-Yamato** [comment]
The resource softcap can be coloured with yellow and when you reach the hardcap they can be coloured red.

**Comment by quzzimi** [comment]
well it just my suggestion 
yellow is good as well imo

**Comment by Tedster59** [comment]
apparently me merging the update closed this automatically.  TIL
