### ISSUE TITLE
[EN]Quotes tab not detecting substitute IDs

### ISSUE THREAD

**Issue by mikenzb** [KC3Kai/KC3Kai#1969]
It has come to my attention that merging [#419 in the translation repo](https://github.com/KC3Kai/kc3-translations/pull/419) has had an unexpected side effect, the quotes tab shows every line as missing because it can not see the _'new'_ substitute ID replacements, not sure about other language's quotes tab but I most differently can't see anything using [EN]quotes.json at the moment 😅

**Comment by Adrymne** [comment]
You can monkey-patch this by changing [these](https://github.com/KC3Kai/KC3Kai/blob/07b4772c9f4a53a0dda9ae61023d01b4afb80d5e/src/pages/strategy/tabs/quotes/quotes.js#L77-L78) lines to something like:
```javascript
if (shipLines && shipLines[KC3Translation.voiceNumToDesc(voiceNum)]) {
  src = shipLines[KC3Translation.voiceNumToDesc(voiceNum)];
```

[This](https://github.com/KC3Kai/KC3Kai/blob/07b4772c9f4a53a0dda9ae61023d01b4afb80d5e/src/pages/strategy/tabs/quotes/quotes.js#L165) line will need to be altered similarly.

I'm not familiar with this part of the code so it might take a bit before I'm ready to put up a PR (or someone else who is can take over, whichever).
