### ISSUE TITLE
KC3Kai not loading

### ISSUE THREAD

**Issue by EGRETTE** [KC3Kai/KC3Kai#1973]
### Steps to reproduce:Game just doesn't load.  It worked yesterday, but now screen stays blue and game doesn't load.  I get as far as control-shift-J, click Kancolle, then it holds on waiting for game actions.
I tried updating KC3, uninstalling and reinstalling it, restarting computer.  I might have left Kancolle running overnight last night before the problem began, but i'm not sure.  In the past, updatining the extension has solved similar trouble, but not this time.

### Screenshots (if applicable):
![image](https://cloud.githubusercontent.com/assets/27397158/24990038/30eb6dae-1fce-11e7-865a-b88b0ac4647a.png)

### Error Report (if applicable):Normally, I get no error message, but now it says
GET http://www.dmm.com/netgame/social/-/gadgets/=/app_id=854854/ 500 (Internal Server Error)
global.js:4 Uncaught TypeError: Cannot read property 'parentNode' of undefined
    at global.js:4
    at global.js:4
(anonymous) @ global.js:4
(anonymous) @ global.js:4

**Comment by Nya-chan** [comment]
500 server error is an error on DMM's side, I assume - nothing we can really do about it.

**Comment by FOG-Yamato** [comment]
Try to clear your cache and then try again.

**Comment by EGRETTE** [comment]
Thanks for your advice.   After clearing cache and cookies, then restarting my computer, I get a different error message:
KC3改 Messengers loaded
global.js:3 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

Game still doesn't load, just a light blue screen..

**Comment by FOG-Yamato** [comment]
That's a normal warning make sure you're logged into DMM and let it run.

**Comment by EGRETTE** [comment]
Finally got it to work, but it seems to require that I use a VPN client to sign on to a Japanese server first before the game connects.  I used to have to do that before I started using KC3 Kai and haven't needed to since until now.  It's loading a bit slower than usual now, too.  Any ideas what might have gone wrong and how I can avoid needing to use the VPN client?

Thanks for the help so far!

**Comment by FOG-Yamato** [comment]
Enable the cookie hack in KC3, that load time is dependent on your and VPNs internet speed

**Comment by EGRETTE** [comment]
Any idea why I now need to use the VPN client?  It's possible that a Windows update occurred just before the problem started or that I might have changed my Chrome settings.

**Comment by FOG-Yamato** [comment]
no idea, cookie hack should work just fine
