### ISSUE TITLE
Screenshot in new tab

### ISSUE THREAD

**Issue by LostLogia4** [KC3Kai/KC3Kai#198]
Is there a way to click the screenshot button without looking away from the game tab?
As far as I see it, this screenshot thingy is not tenable for momentary screenshot (like the in-battle phase) right now.

**Comment by McDohl** [comment]
smash the alt + printscreen or printscreen on your keyboard? :laughing:

**Comment by dragonjet** [comment]
hmm we can attempt binding a key for it, but there's no guarantee that the extension will recognize it

**Comment by dragonjet** [comment]
As of recent releases, `F9` key is now a shortcut to take a screenshot
