### ISSUE TITLE
Friend of mine having an issue with subtitles/translation

### ISSUE THREAD

**Issue by GenFungus** [KC3Kai/KC3Kai#1980]
As the title says, this isn't an issue I'm personally experiencing with KC3Kai; it's a friend who just got into playing Kancolle. Every time he starts up the "Customize DMM Website" option for KC3Kai, he gets a DMM frame and no subtitles or quest translations. I walked through the settings with him already to see if that would resolve anything and have removed the add-on and reinstalled it a few times, but he keeps having the same issue.

This is his information below:

### Versions:
- Chrome Version: 57.0.2987.133 (Official Build) (32-Bit)
- Windows 8.1, Core Edition
- 64bit
- 31.4.0
- Chrome Webstore Version
- Customize DMM Website

**Comment by FOG-Yamato** [comment]
Strange, that error is not from KC3 as far as I'm aware of, anything else he noticed in the console while KC3 ran, any warnings or errors besides that one?

**Comment by GenFungus** [comment]
I had him screenshot the script he was seeing in the DevTool, but that's really it. Kancolle runs fine; it's just the issues I mentioned up there, and he hasn't told me about any other error messages, or anything of the like. I was trying to navigate Avast to see if there was something running interference in that, since we both use it... but it's just that. We both use Avast and I don't run into this issue; never have.

**Comment by FOG-Yamato** [comment]
No worries, can you try and disable the AV and try again, and make sure there is no blugin that interferes with KC3.

**Comment by GenFungus** [comment]
@FOG-Yamato So... I got some stuff a bit mixed up. He's using AVG, not Avast like I thought he said he was earlier. Also, he had this DMM add-on that he deleted and can't get back now. Since that was removed, he keeps getting redirected to the Nutaku site... so this turned into a whole other mess, it seems.

**Comment by FOG-Yamato** [comment]
hmm, this seems like something is interfering with the DMM page, doing the redirect, let him double check the DMM website is in japanese and that DMM Cookie hack is enabled in KC3

**Comment by GenFungus** [comment]
@FOG-Yamato Well, he did that and now he's getting the proper Customize DMM Frame and subtitles and all that. He was having another few issues with the quest translation overlay as well, but we got that resolved on our own. Thank you for all your help with this issue!

**Comment by FOG-Yamato** [comment]
You're welcome
