### ISSUE TITLE
KC3 crashed on "reload extension" for new update

### ISSUE THREAD

**Issue by sanga000** [KC3Kai/KC3Kai#1988]
On clicking "reload extension", KC3 gave me no response indicating a successful reloading, and when I checked by clicking on the icon on chrome, it seemed to be not working at all.

![kc3 crash](https://cloud.githubusercontent.com/assets/26204896/25311324/84162216-2830-11e7-9659-465788bbd5cf.png)

**Comment by Tedster59** [comment]
we already pushed a hotfix, force update it.

**Comment by sanga000** [comment]
Does that mean I need to do a manual update by copying files into the "extension" folder of chrome?

**Comment by Tedster59** [comment]
https://www.howtogeek.com/64525/how-to-manually-force-google-chrome-to-update-extensions/

**Comment by sanga000** [comment]
Ah I see, thanks. Sorry if I bothered you.
