### ISSUE TITLE
[Suggestion] Multi Strategy Room

### ISSUE THREAD

**Issue by darkdragon241** [KC3Kai/KC3Kai#1994]
Like the tittle said I am wondering that is it possible to have more than 1 strategy room at the same time 

For Example:
I am using strategy room to search for my expedition history, so i can see which girl i'm lvling using expedition, when i change my expedition team. I can't remember the ship girl's kanji, so i have to switch to the ship list to see where that girl is (i use her lv to locate her position in the fleet) and then switch back to the expedition history until i finish the fleet. That why i thought that if i had 1 more strategy room it could be faster. The same thing when you use battle history.

**Comment by Nya-chan** [comment]
Right-click the tab - Duplicate. Report how it works (whether both tabs update - they should) in here ;3

**Comment by darkdragon241** [comment]
i don't know we can don that .-.
thanks for helping :x
