### ISSUE TITLE
Missing Icon from LBAS

### ISSUE THREAD

**Issue by mikenzb** [KC3Kai/KC3Kai#1997]
Found this minor bug while leveling planes in world 6, seems like `Kyoufuu Kai` doesn't yet have a icon for the LBAS base, not sure what else is missing but it might pay to check what else is missing with all the new equipments added recently.
![capture](https://cloud.githubusercontent.com/assets/5982780/25420392/05f12592-2aac-11e7-8616-a586cdaa4329.PNG)

Edit: `Type 0 Fighter Model 63 (Fighter-bomber)` also missing icon

**Comment by sinsinpub** [comment]
yep, i have forgot them either 😂 
for @KC3Kai/developers : updating that is quite easy. open SRoom Equip Library, select new item needs to be added, right-click the 3rd image (the one without fairy), save to kc3 `src\assets\img\plane` folder, then git add and commit these files. nothing else needs to be handled.
