### ISSUE TITLE
Changes to ship Index numbers made some old reports confusing.

### ISSUE THREAD

**Issue by sebsmith1** [KC3Kai/KC3Kai#2002]
For instance:
![Suzuya](http://i.imgur.com/cJYb8og.png)

No clue if this is something worth changing, but I saw no previous mention of it recently.

**Comment by Vultren** [comment]
@sebsmith1 
![image](https://cloud.githubusercontent.com/assets/10458410/25499766/828073d4-2b5a-11e7-93a3-4651b5ebfb38.png)

**Comment by Nya-chan** [comment]
Closing as solved
