### ISSUE TITLE
graphic error

### ISSUE THREAD

**Issue by blizzardpotato** [KC3Kai/KC3Kai#2004]
Please make sure that you have these details on hand when submitting your issue/bug report as this will greatly speed up the issue triage process -- thank you!

- Your Chrome version - via chrome://version/ chrome / kc3 31.5.2
- Your OS and its version
- 32bit or 64bit?
- Your KC3 Kai version - via chrome://extensions/
- Which build you have tried running? webstore version as in the one from [Chrome Web Store](https://chrome.google.com/webstore/detail/kancolle-command-center-%E6%94%B9/hkgmldnainaglpjngpajnnjfhpdjkohh) or Github variant (better known as developer builds).
- Which game play mode you are using?
- Screenshots which accurately paint the issue(s) you are facing.
- A step by step method that you did to describe how you got to that issue.
- A KC3 Error Report JSON file if you have faced an API error. To upload it, you might append `.txt` as file name extension.

After reading previous part of instruction, you can safely remove them now (including this line). Then fill up following part with your situation.

### Screenshots (if applicable):
![2017-04-28 14-10-50 23](https://cloud.githubusercontent.com/assets/28183501/25554030/23d94554-2cfe-11e7-8ee9-57cb18988d28.png)
![2017-04-28 14-10-36 30](https://cloud.githubusercontent.com/assets/28183501/25554031/29fdd738-2cfe-11e7-9f53-85c300493b6f.png)

**Comment by Vultren** [comment]
The conversion for this problem moved over to #2036, so I'm closing this one
