### ISSUE TITLE
Request/Suggestion: repair/construction dock interface QOL

### ISSUE THREAD

**Issue by KataLystTB** [KC3Kai/KC3Kai#2005]
Hi there, not sure if this has been suggested yet or not.  I have always wondered why the viewer can read and change things like the active quests and who is in the dock(s) at any particular time but chooses to always show the full four docks, regardless of how many you have unlocked at any time. I'm aware it may be there to show that there are four dock(s) that are unlockable and to fill in the otherwise empty space however I feel that there should be something to make it more clear that those extra docks aren't available.
My suggestion is something on the lines of either making the excess dock(s) invisible, and having them appear in the interface again when you enter the dock after purchasing/unlocking additional dock(s) like below; 
![image](https://cloud.githubusercontent.com/assets/28195734/25556567/1d4d36d4-2d42-11e7-99a8-4c139a4cf70c.png)
Alternatively, another solution would be to cross out the locked dock(s) like so; 
![image](https://cloud.githubusercontent.com/assets/28195734/25556651/7190ba12-2d43-11e7-943a-0db79cf3b1a7.png)
Apologies for the poor ms paint job, however it gets the point across. Having it done the same way the icons in the battle interface are done would be better as they are less visually intrusive. 
This change could be toggleable, as i'm sure there are many people that would have a particular preference (to show the 4 docks regardless or not).

**Comment by sinsinpub** [comment]
how about?
![image](https://cloud.githubusercontent.com/assets/160240/25557109/0206facc-2d3d-11e7-8b59-5a12917396f8.png)

**Comment by KataLystTB** [comment]
That's a much better solution actually, it looks much more aesthetically pleasing while being just as functional.
