### ISSUE TITLE
[Request] Add co library

### ISSUE THREAD

**Issue by Adrymne** [KC3Kai/KC3Kai#2006]
The [co](https://github.com/tj/co) library would make handling async simpler. For example, the [`runExportFuncs`](https://github.com/KC3Kai/KC3Kai/blob/35bccd577ac8583239c7c2070f5080da41af6214/src/library/modules/ImageExport.js#L134-L145) method could have been written as follows:

```Javascript
KC3ImageExport.runExportFuncs = co.wrap(function *(funcs) {
  for (let f of funcs) {
    try {
      return yield f();
    } catch (e) {
      KC3ImageExport.logError(e);
    }
  }
  throw new Error('ImageExport: export failed');
});
```

(Alternatively, enabling async/await via transpiler would work too.)

**Comment by sinsinpub** [comment]
advantage (and maybe disadvantage for some technical developers) of this project is its simplicity, or in other word: lite. except some necessary web UI libraries, all devs need to know is vanilla javascript (ofc currently ver ES2015, and feel good enough to handle async). the more libraries/frameworks/APIs introduced, its maintainer might be harder to find, i think.

**Comment by Adrymne** [comment]
async/await has native support, though. It's just that it wasn't introduced until Chrome 55, so we won't get access to it for a while - hence the request for (what is effectively) a polyfill.

**Comment by FOG-Yamato** [comment]
I'm preety sure async/await is already part of Chromium, I can gurantee it's part of NodeJS starting from v7.5
