### ISSUE TITLE
Increase contrast of buttons in dark theme

### ISSUE THREAD

**Issue by Accelyte** [KC3Kai/KC3Kai#2007]
![chrome_2017-04-30_15-04-31](https://cloud.githubusercontent.com/assets/21363469/25564963/5c212090-2db6-11e7-90fc-79766b84cc97.png)
![chrome_2017-04-30_15-04-41](https://cloud.githubusercontent.com/assets/21363469/25564965/6239e912-2db6-11e7-99c2-4cf97365435c.png)
It's hard to tell whether buttons are available or not since the two tones of grey are similar, would be great if there is a larger difference in the colour to distinguish them.
I'm not sure if this is the only tab with buttons like this though.

**Comment by sinsinpub** [comment]
how about?
![image](https://cloud.githubusercontent.com/assets/160240/25565173/2e765eb4-2df5-11e7-882b-049976cb344d.png)

**Comment by Accelyte** [comment]
That looks pretty obvious, so yea that would be good :)
Remember to change the View button that's tied to the From Sortie History option as well.

**Comment by sinsinpub** [comment]
the View button is not tied to 'From Sortie History'. it's always available, which also apply to 'Current Fleets' and 'Saved Fleets'

**Comment by Accelyte** [comment]
Oh, my bad.
