### ISSUE TITLE
[Request] Add fleet manager recall button directly to sortie history

### ISSUE THREAD

**Issue by MegaAbsol** [KC3Kai/KC3Kai#2008]
(I'm not sure if this is an existing request yet, feel free to close it if it is already. Also, I'm not sure if this already is implemented and I'm unaware of its existence.)

Oftentimes, I find myself going, "What was the fleet/equips I used last time I did this map?" So I go over to Battles -> Maps, finding the fleet, and looking at the sortie ID. Then I have to go back to Fleet Manager and manually input that ID in.

I feel that it'd be easier if there was a button on the sortie history that automatically put it into fleet manager and opened it up for me. Like that REP button for replays, but for opening up the fleet in the fleet manager. I acknowledge that it only saves about 2 clicks and typing in a few digits so it's probably not really important but it'd save a few seconds.

**Comment by sinsinpub** [comment]
just a hint: although it's not detail enough, at history u can still view the fleet/equips
![image](https://cloud.githubusercontent.com/assets/160240/26825056/2a5788f4-4ae6-11e7-8f02-77dd1a08978e.png)
