### ISSUE TITLE
[FR] Beginning of translation (Akashi's Arsenal, Ooyodo Event, Title screen quotes)

### ISSUE THREAD

**Issue by Kontchalowski** [KC3Kai/KC3Kai#2012]
Hello, I wanted to contribute to the french translation of Kancolle.
Some weeks ago, I began to translate the first lines of the quotes file.

https://pastebin.com/52zHFX1p

I would like to know if you're fine with it, and if there's still activity in the french side before to go further.

Thank you in advance.

**Comment by nonsensed** [comment]
Hey, thanks for the submission!

The FR translations have been inactive recently. I can't read French, but I've made a Pull Request with your submission in the translation repository. We'll see if we can get it in soon.


One thing is, if there is a `,` before `}`, there will be an error. For example,
```
        "425": "text",
        "426": "text",
        "427": "text",
    },
```
should be
```
        "425": "text",
        "426": "text",
        "427": "text"
    },
```

**Comment by nonsensed** [comment]
@Kontchalowski 
Although I'm closing this, it sounds as though you might be planning to translate more. By all means, please feel free! You can put them in this issue or make a new one.

**Comment by Kontchalowski** [comment]
Okay, thanks a lot!
