### ISSUE TITLE
Suzuya Kai Ni appearing in Enemy Encounters

### ISSUE THREAD

**Issue by moemoemudkip** [KC3Kai/KC3Kai#2018]
### Versions: 
Chrome: 57.0.2987.133
OS: Windows 10 Home, 64 bit
KC3 version: 31.5.2
### Steps to reproduce:
KC3 Strategy Room > Battles > Encounters
### Actual behaviour:
displays anchors and Suzuya k2 rather than enemies on most nodes
### Expected behaviour:
Display correct enemy encounters
### Screenshots (if applicable):
[https://gyazo.com/d98f37633aa3118f2a0e90ae136f90e8](url)

**Comment by Vultren** [comment]
![image](https://cloud.githubusercontent.com/assets/10458410/25639306/6f60e2ae-2f59-11e7-8765-f4eb06f3e786.png)

**Comment by Vultren** [comment]
@moemoemudkip that should fix your problem

**Comment by mikenzb** [comment]
Also if you don't see it under the bug fixes in the strategy room make sure you're on the latest version.
