### ISSUE TITLE
Admiral Dashboard Error

### ISSUE THREAD

**Issue by LucidAtray** [KC3Kai/KC3Kai#2038]
Please make sure that you have these details on hand when submitting your issue/bug report as this will greatly speed up the issue triage process -- thank you!

- Screenshots which accurately paint the issue(s) you are facing.
- A step by step method that you did to describe how you got to that issue.
- A KC3 Error Report JSON file if you have faced an API error. To upload it, you might append `.txt` as file name extension.

### Versions:

- Your Chrome version - via chrome://version/: 57.0.2987.133
- Your OS and its version: Windows 10
- 32bit or 64bit? 64bit
- Your KC3 Kai version - via chrome://extensions/: 31.6.2
- Which build you have tried running? Chrome Web Store
- Which game play mode you are using? The 'Play Kantai Collection' normal mode.

### Screenshots (if applicable):

![sin titulo](https://cloud.githubusercontent.com/assets/28507783/25781896/91d83d08-337a-11e7-9feb-25da50ad1d43.png)

**Comment by mikenzb** [comment]
This is the same issue as #2011, unfortunately there is no fix to this besides reinstalling your extension from my understanding.

**Comment by LucidAtray** [comment]
Oh, I didn't realize that, sorry! But as long as it works, I'm good :) it does indeed work as intented now that I reinstalled it. Thanks a lot!
