### ISSUE TITLE
About the discord channel

### ISSUE THREAD

**Issue by amazingfate** [KC3Kai/KC3Kai#2040]
I can't join server from the link showed in the Readme, there should be an invite link
![image](https://cloud.githubusercontent.com/assets/5022901/25797970/ff31dd2c-3411-11e7-8c12-e76a1826372b.png)

**Comment by DynamicSTOP** [comment]
1. Join Kancolle server https://discord.gg/RtSadWM
2. Go to `#club-list` channel and read how to join `#kc3-kai` channel

**Comment by amazingfate** [comment]
thank you very much!
