### ISSUE TITLE
API errors on new ships and equipments

### ISSUE THREAD

**Issue by october10th** [KC3Kai/KC3Kai#2042]
### Versions:
Chrome version -58.0.3029.96
OS and its version Mac OS X 10.11.6
64bit
KC3 Kai version - 31.6.2
### Steps to reproduce:
Put new ships or equipments into fleets and api errors will occur.

### Screenshots (if applicable):
1. New ships in 17 spring (Take Kunashiri for example)
![2017-05-08 7 09 55](https://cloud.githubusercontent.com/assets/4963914/25802181/bcc42f46-3423-11e7-9396-02dfdba97cbc.png)
2. Suzuya Kai Ni
![2017-05-08 7 11 13](https://cloud.githubusercontent.com/assets/4963914/25802203/d666bacc-3423-11e7-82ae-2ccb4778444b.png)
3. New equipments (Take 強風改 for example)
Zara due  not equipped with 強風改:
![2017-05-08 7 11 43](https://cloud.githubusercontent.com/assets/4963914/25802225/f57d7478-3423-11e7-8e13-f56d51b7a032.png)
Zara due  equipped with 強風改: 
![2017-05-08 7 26 27](https://cloud.githubusercontent.com/assets/4963914/25802300/4f99977a-3424-11e7-9ad1-fd964175a2eb.png)
![2017-05-08 7 11 59](https://cloud.githubusercontent.com/assets/4963914/25802226/f57eac12-3423-11e7-9fb7-416d7284dd90.png)

### Error Report (if applicable):
1.[KC3-Error-1494241783.txt](https://github.com/KC3Kai/KC3Kai/files/983295/KC3-Error-1494241783.txt)
2.[KC3-Error-1494241850.txt](https://github.com/KC3Kai/KC3Kai/files/983296/KC3-Error-1494241850.txt)
3.[KC3-Error-1494241913.txt](https://github.com/KC3Kai/KC3Kai/files/983299/KC3-Error-1494241913.txt)

Tried "Update abyssal IDs of database after 2017-04-05 maintenance" already.

**Comment by sinsinpub** [comment]
these errors are not supposed to be related with new equipment. i guess your storage data of ship & equipment might be out of syncing (corrupted?). u may try this:

 1. Close all your KC game & KC3 tabs first.
 2. Open KC3 Strategy Room, open its devtools (push Ctrl+Shift+I).
 3. Choose the `Console` tab, then execute following command to clear cached ship & equpment data only:
```
delete localStorage.ships; delete localStorage.gears
```
 4. Restart your KC game via KC3 to see if the data synced and no error any more.

**Comment by october10th** [comment]
It works!
Thank you.
