### ISSUE TITLE
Suggestion: Highlight New and First copy of each ship in Strategy Room

### ISSUE THREAD

**Issue by R-Jimenez** [KC3Kai/KC3Kai#2045]
Another quick suggestion:

In the strategy room shiplist, could we have a toggle or marker for new ships, or the first copy of each ship? Like a gold highlight or border, so that after a ttk gets a new ship after a few sorties, they know whether or not they have that ship, and can heartlock it.

Alternatively, can we just have heartlock be an icon in the ship list data row? That way a user can just sort by name and go down and see if there's a ship that isn't locked up.

**Comment by ethrundr** [comment]
This is actually a good idea, especially for the heartlock one.

I believe this idea has been sounded quite a long time ago, but never implemented.
Think this is a good time and reason to implement this.

**Comment by sinsinpub** [comment]
is there a simple and realizable way to tell which ship is the 'new ship'?
my max ship slot is 100, those ships i scrapped are always 'new' for me?

**Comment by ethrundr** [comment]
I think we can use the same approach as the equipments.
Regardless it is new or not to you, when it's the first copy of each ships, then we marked it as such.

When you scrapped that ship and got the same copy afterward, then that copy will also be marked as well. Maybe the correct term is not "new" ship, but "first of such" ship.

In case there are multiple copies of same ship existing in base, then the smallest ID will gain the mark.

**Comment by sinsinpub** [comment]
i guess i get u two... all my ships will be highlighted 😂 
but if just request for that, i can give u the the working alternative method:
filter heartlock: all
multi sort by: name > ID
then check the new ones with bigger ID, by toggling heartlock filter, to see if they are locked.

**Comment by R-Jimenez** [comment]
Decent workaround, and I'm glad dupe checking is in the pipeline, but that actually brought up another small styling issue.

I think it would be a good idea to keep the filter panel of the ship list fixed, and have the data table scroll internally. If you do want to do any serious filtering and investigation, it's nearly impossible if you're looking at more than a couple dozen ships, as you have to keep scrolling up and down to try and view differences. Just a thought, after trying out your solution.

**Comment by sinsinpub** [comment]
just check if it is satisfied after release.
