### ISSUE TITLE
boss gauges incorrect after reset difficult of E-5.

### ISSUE THREAD

**Issue by htomeload** [KC3Kai/KC3Kai#2046]
### Versions: 
- Chrome Version 58.0.3029.96 Built on Ubuntu , running on Ubuntu 16.04 (64-bit)
- KC3改 Development version 31.6.2

### Steps to reproduce:
- Have sorties until last dance of second boss in E-5.
- Reset difficult from Easy to Medium then back to Easy. (For avoid boss debuff is vanish in changing to Hard.)
- Get back to main screen then have sorties.

### Actual behaviour:
After reset difficult from Medium back to Easy, I notice that boss gauges icon is still be second boss. So I try to load new data by get back to main screen then have sorties. I notice on gauges when I have seconds sorties. 

### Expected behaviour:
boss gauges should be reset following in game.

**Comment by Vultren** [comment]
This seems to happen when there is more than one gauge. Same thing happened while I was on E2. It goes back to normal once the first bar is cleared.

**Comment by htomeload** [comment]
It is possible to have two boss gauges or more for one map ?
If it can, then maybe show one and hide other, active only current boss gauges.

**Comment by sinsinpub** [comment]
yep, truth is kc3 not supporting two gauge in one map yet. so hp gauge will overwrite tp gauge.
there is `api_eventmap.api_gauge_type` of `/mapinfo` api, we could save its value (with a default for normal maps) along with our map gauge data

another truth: kc3 cannot tell the different boss nodes for those maps more than one boss exists. my think is: also save the `api_bosscell_no` attribute of `/start` or `/next` api along. then kc3 will be able to determine which node is the correct boss node for the phase player is currently at.
tech issue is: `api_bosscell_no` will be random value if more than one edge leading to the boss node. it will be easy solved if our edges data have been completed. but if not, we have to save all the possible `api_bosscell_no` values for the detecting.

**Comment by sinsinpub** [comment]
btw, the last kill status issue after reset diff should be fixed on previous release. reopen this if further issue found
