### ISSUE TITLE
crash appeared  before selecting map (after updating to 31.6.3)

### ISSUE THREAD

**Issue by temacort** [KC3Kai/KC3Kai#2053]
- Your Chrome version - 	54.0.2840.71
- Win10 Version 1511 build 10586.916
- 64 bit
- KC3 Kai version 31.6.3
- KC3 Kai from Chrome Store
- Which game play mode you are using? Maybe Customized DMM (game mode by default)

Steps to reproduce: Click on launch fleet icon in the main menu then on battle icon (the red one)

Screenshots (if applicable): ![capture](https://cloud.githubusercontent.com/assets/6431443/25964747/2bcb21ec-3686-11e7-834c-97cb201a56a3.PNG)

Error Report (if applicable): [KC3-Error-1494524850.txt](https://github.com/KC3Kai/KC3Kai/files/994025/KC3-Error-1494524850.txt)

**Comment by mikenzb** [comment]
Same Issue as #2052, Should be fixed now in 31.6.4 so please upgrade your KC3 to the latest version and check again.
