### ISSUE TITLE
Suggestion: Option to stop Red shade animation taiha alert.

### ISSUE THREAD

**Issue by htomeload** [KC3Kai/KC3Kai#2057]
Red shade fading animation cause cpu run high, especially on my chromium which running on Ubuntu Gnome 16.04 LTS x64, it cause my cpu run up over 40% from usually.

Maybe it would be only transparent long range red shade. So it can be noticeable.

**Comment by sinsinpub** [comment]
u mean u wanna keep the noticeable red shade on panel without animation?
it seems bad performance of all kinds of animations for Chrome running on Linux 😓 none of other OS user reports such an issue.
if more ppl using Linux would like to +1 for u, i'm fine to add the option to disable animation.

**Comment by ethrundr** [comment]
Regardless the performance issue on OS-specific, giving option to turn it off is never hurt.

Keep in mind that not all of our user is using a adequate graphic nor memory to handle all features we implement inside KC3kai.

So, +1 from me for adding the option to disable the animation.

**Comment by sinsinpub** [comment]
as i've gotten only several reports about this: OS gets slow down no matter the animation is implemented by `Timer` or native CSS feature. not sure are they happening in all cases.

(not for this case) it will be hurt if unexpected issues found for standard (animation) features should be supported by browser (Chrome in this case). it's definitely not KC3's duty to handle them all 😂
