### ISSUE TITLE
Error: Icons in Panel and Strategy Room are out of place

### ISSUE THREAD

**Issue by RicoRisktaker** [KC3Kai/KC3Kai#2062]
### Versions: 
Google Chrome	58.0.3029.110 (Official Build) (64-bit)
Windows 8.1
KanColle Command Center 改 31.6.4 (Webstore)

### Screenshots:
![untitled1](https://cloud.githubusercontent.com/assets/28693022/26038331/19c45f64-3941-11e7-993a-28aa76f5a4af.png)
![untitled3](https://cloud.githubusercontent.com/assets/28693022/26038332/1dbcf0d6-3941-11e7-8547-af5ce1ccbf85.png)
![untitled4](https://cloud.githubusercontent.com/assets/28693022/26038333/2128e8ec-3941-11e7-9c32-594233f4ea04.png)
![untitled5](https://cloud.githubusercontent.com/assets/28693022/26038334/2206d2e2-3941-11e7-9a12-002e731bf2f6.png)

**Comment by Vultren** [comment]
Same problem as #2011. the bootstrap in the extension died. you need to uninstall and reinstall the extension.

**Comment by RicoRisktaker** [comment]
Thank you
