### ISSUE TITLE
[Suggestion/Request] Engagement form modifier QOL

### ISSUE THREAD

**Issue by KataLystTB** [KC3Kai/KC3Kai#2064]
Hi there,
Recently I've noticed that you can hover over the combat modifier in the battle prediction interface, and a tooltip will appear that shows an abbreviated version of the current modifier. I have wondered why this was needed as the abbreviation (at least in the English version, i'm not sure if its purpose is to display the abbreviated modifier in other languages) doesn't give any more information than the full name which is already shown. Therefore, I thought it would be a good QOL change to add the effect of the current modifier in the tooltip instead, assuming it doesn't currently serve a purpose similar to the one listed above.

The proposed change could look like this, colours are used to show the effective damage of the modifier and are taken from the health bars for consistency. 
![image](https://cloud.githubusercontent.com/assets/28195734/26056731/f000326a-39b9-11e7-921a-2d87df2410c2.png)

My apologies if UI adjustment suggestions are not encouraged but I feel it doesn't hurt to give feedback to make the UI more friendly towards users, especially newer ones that aren't entirely familiar with it.

**Comment by sinsinpub** [comment]
abbr. tooltip is just a result of swapping: it's the full-name on the tooltip in the past.

it's welcomed to enhance it, but there are more effects affected by engagement, not only modifier of damage.

**Comment by LostLogia4** [comment]
So is it something like 60-120% Firepower?

**Comment by sinsinpub** [comment]
i just committed the damage ones to en json as enwiki also does... anyone @KC3Kai/translators could update them with proper ones. see: https://github.com/KC3Kai/kc3-translations/commit/3a2acd43702ae693344f54289005ba62f7ebc020
