### ISSUE TITLE
Screen auto-adjusted problem

### ISSUE THREAD

**Issue by Kel786** [KC3Kai/KC3Kai#2069]
### Versions:
Chrome: Version 58.0.3029.110
OS: Window 10
KC3 Kai: 31.6.4
Built: Chrome Web Store

### Actual behaviour:
The game can work normally but the screen is not auto-adjusted by itself. Part of the main screen will be covered by the panel. If I pull the panel to let it become smaller, the right side of the panel will not be seen.

### Expected behaviour:
I didn't play Kancolle for a while but I still remember the screen will adjust itself.

### Screenshots (if applicable):
![5](https://cloud.githubusercontent.com/assets/24354589/26281836/a5193b54-3e35-11e7-9964-c6f4ac6f42ef.jpg)
![6](https://cloud.githubusercontent.com/assets/24354589/26281838/c31412be-3e35-11e7-8f3a-b2552876de92.png)

**Comment by sinsinpub** [comment]
game screen (the flash player) never auto adjust size (in fact, dmm side is trying to detect and disallow its size changed). u could change the zoom scale at kc3 settings, otherwise u may only adjust ur desktop resolution and chrome window size.
