### ISSUE TITLE
graphic error reoccurred

### ISSUE THREAD

**Issue by blizzardpotato** [KC3Kai/KC3Kai#2073]
Please make sure that you have these details on hand when submitting your issue/bug report as this will greatly speed up the issue triage process -- thank you!

- Your Chrome version - via chrome://version/ -  58.0.3029.110 (64-bit)
- Your OS and its version
- 32bit or 64bit?  - win 8,1 / 64bit
- Your KC3 Kai version - via chrome://extensions/ ver. 31.6.5 
- Which build you have tried running? webstore version as in the one from [Chrome Web Store](https://chrome.google.com/webstore/detail/kancolle-command-center-%E6%94%B9/hkgmldnainaglpjngpajnnjfhpdjkohh) or Github variant (better known as developer builds).
- Which game play mode you are using? - customize dmm website
- Screenshots which accurately paint the issue(s) you are facing.
- A step by step method that you did to describe how you got to that issue.
- A KC3 Error Report JSON file if you have faced an API error. To upload it, you might append `.txt` as file name extension.

After reading previous part of instruction, you can safely remove them now (including this line). Then fill up following part with your situation.

### Screenshots (if applicable):
![ssd](https://cloud.githubusercontent.com/assets/28183501/26389537/5b7eab16-4095-11e7-8f66-fb272f5f6bdd.JPG)
![sss](https://cloud.githubusercontent.com/assets/28183501/26389538/5b903a84-4095-11e7-9379-11ee044de580.JPG)

### Error Report (if applicable):

Since new update, error was frequent.

**Comment by blizzardpotato** [comment]
https://github.com/KC3Kai/KC3Kai/issues/2036

**Comment by mikenzb** [comment]
There is no need to open up more than one issue for the same problem
