### ISSUE TITLE
Suggestion: green indicator when a ship has reached the desired levelling value

### ISSUE THREAD

**Issue by Accelyte** [KC3Kai/KC3Kai#2082]
This is more useful than showing negative values, and it's easier to spot if you're not sorting the ships by XP needed.

**Comment by sinsinpub** [comment]
not sure if this is what u exactly want, but 'green' is already used by other condition.
![image](https://cloud.githubusercontent.com/assets/160240/26528309/63708c2e-43db-11e7-8b83-f056c9699144.png)

**Comment by Accelyte** [comment]
something like that, just for the sake of clarity.
