### ISSUE TITLE
wrong reward, the reward for b93 is only irako and mamiya, 1 of each, and no screws

### ISSUE THREAD

**Issue by rakkor** [KC3Kai/KC3Kai#2084]
[Please](url
![image](https://cloud.githubusercontent.com/assets/29032842/26538015/d7a3d08c-446d-11e7-819a-78c946d05150.png)
) make sure that you have these details on hand when submitting your issue/bug report as this will greatly speed up the issue triage process -- thank you!

- Your Chrome version - via chrome://version/
- Your OS and its version
- 32bit or 64bit?
- Your KC3 Kai version - via chrome://extensions/
- Which build you have tried running? webstore version as in the one from [Chrome Web Store](https://chrome.google.com/webstore/detail/kancolle-command-center-%E6%94%B9/hkgmldnainaglpjngpajnnjfhpdjkohh) or Github variant (better known as developer builds).
- Which game play mode you are using?
- Screenshots which accurately paint the issue(s) you are facing.
- A step by step method that you did to describe how you got to that issue.
- A KC3 Error Report JSON file if you have faced an API error. To upload it, you might append `.txt` as file name extension.

After reading previous part of instruction, you can safely remove them now (including this line). Then fill up following part with your situation.

**Comment by sinsinpub** [comment]
but your screenshot is showing B97... 😂 

ps. why put all things in the title... why don't remove those template texts? 😂

**Comment by nonsensed** [comment]
I just checked B93 and B97.

- B97 will have its reward list adjusted to no Screws.
- B93 should already correctly say its rewards as 1 Irako and 1 Mamiya.
- B99 will also be updated to show that it rewards 4 Screws.

Adjustments should occur in the next update. If this is still incorrect, notify me and provide a source of proof if possible. Thank you for your time.
