### ISSUE TITLE
World 5 support expedition is not recorded in KC3 map history

### ISSUE THREAD

**Issue by Accelyte** [KC3Kai/KC3Kai#2089]
KC3 v.31.6.7
Map history and replayer don't show ships or equipment used in world 5 support expeditions, the damage is still recorded. I don't remember if this was ever the case tho.
![chrome_2017-06-02_21-47-37](https://cloud.githubusercontent.com/assets/21363469/26744386/a6bda3b2-47dd-11e7-81f6-a47ae3b11313.png)
![chrome_2017-06-02_21-50-38](https://cloud.githubusercontent.com/assets/21363469/26744399/b1b00242-47dd-11e7-9e20-5f0cf54eed09.png)

**Comment by sinsinpub** [comment]
surprised that nobody found it for such a long time 😅 
to confirm: this bug should only affect world 5 boss support (exped 34), pre-boss support should work?

**Comment by Accelyte** [comment]
haven't tested it because I don't use it on 5-5, maybe you'll find some relevant code when you're fixing it? I don't have enough steel otherwise I would've tested it for you.
