### ISSUE TITLE
KC3KAI menu doesn't load(?)

### ISSUE THREAD

**Issue by Niccochi** [KC3Kai/KC3Kai#2101]
Hello! I already installed my KC3Kai long time ago, and i found this error..

- Chrome version : 58.0.3029.110 (Official Build) (32-bit)
- Windows 7
- 32bit 
- KC3Kai version 31.7.1
- I've run the webstore build
- The Play Kantai Collection mode
![1](https://user-images.githubusercontent.com/29390915/27063230-a21e2418-501a-11e7-8e1c-53c3d0d06d91.jpg)

I don't know why it happens.. I've re-installed my KC3Kai again and it works normally, anyone had the same problem?

**Comment by mikenzb** [comment]
This error normally occurs when your KC3 extension may be corrupted, a reinstall should fix it as you figured out.

It also happens when you clone the dev build of KC3 onto your PC without the TL (translation) files.

Reopen issue if you need help, otherwise will close for now.
