### ISSUE TITLE
Suzuya Kai Ni (CAV) is not appeared in badge.

### ISSUE THREAD

**Issue by htomeload** [KC3Kai/KC3Kai#2108]
### Versions: 
KC3Dev V.31.7.1
Chromium 58.0.3029.110 Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

### Steps to reproduce:
- use badge generator in KC3 (leave every options in checked).

I do reload ship lists by clicked on golden heart icon and use badge generator again but Suzuya kai ni still not appear.

I do manual check and she is appeared.

**Comment by Nya-chan** [comment]
It should be fixed, you might need to hard refresh the badge site, though, since the data is cached.
