### ISSUE TITLE
Japanese language display problem on PvP battle panel.

### ISSUE THREAD

**Issue by nicky008** [KC3Kai/KC3Kai#211]
![capture](https://cloud.githubusercontent.com/assets/10517990/8632265/b4378390-27ce-11e5-89cb-a5924bd9d9e2.PNG)

As you can see...

* Kanmusu and Equipment number's font is looking messed, bold and no backslash divided.
* My HQ level (and Kanmusu's level) is same above too.
* Quest wordings are lost. (Just show only "?".)

I'd rather use English display for this moment when the problem isn't solved yet. :<

PS. And what the number beside near the equipment symbol (both in Japanese and English display.) like this too. I'd wonder what's the meaning here...

![capture1](https://cloud.githubusercontent.com/assets/10517990/8632314/4b8d8630-27d0-11e5-8958-2f39dc1adccd.PNG)

**Comment by dragonjet** [comment]
Ah this is true, we haven't thoroughly  tested Japanese mode yet, which will be further tracked in #169. There is no definitely timeline yet for the Japanese mode

The numbers beside the equipment icons are the plane capacity for each slot.

**Comment by nicky008** [comment]
Which mean gun (and another not-plane equipment) equipped slot would also have the number shown here too, right?

**Comment by dragonjet** [comment]
yes, regardless of what they are wearing, it will always show the slot capacity.

this will be useful in moving forward when we use the battle mode as main interface since it will help players determine which slot to place which plane, without referring back to the wiki, while they are arranging a fleet.

**Comment by dragonjet** [comment]
Legacy theme not supported anymore, I believe this does not happen on Natsuiro theme as well
