### ISSUE TITLE
Suggestion Add number of DHSs/TokuDHSs in expediton panel

### ISSUE THREAD

**Issue by quzzimi** [KC3Kai/KC3Kai#2110]
Could you guys add  number of DHSs/TokuDHSs + amount of resources bonus from them in expediton panel 
and if you already reach the 20% softcap or not 
thank you very much 👍

**Comment by sinsinpub** [comment]
hover on resource values, u will see
![image](https://user-images.githubusercontent.com/160240/27284349-d857dc44-552a-11e7-968b-ff00d33d8cb6.png)

**Comment by quzzimi** [comment]
thanks alot 
didnt notice that :)
