### ISSUE TITLE
Suggestion: Secretary hourly notifications 

### ISSUE THREAD

**Issue by Dahzz** [KC3Kai/KC3Kai#2112]
Please make sure that you have these details on hand when submitting your issue/bug report as this will greatly speed up the issue triage process -- thank you!

- Your Chrome version - via chrome://version/
- Your OS and its version
- 32bit or 64bit?
- Your KC3 Kai version - via chrome://extensions/
- Which build you have tried running? webstore version as in the one from [Chrome Web Store](https://chrome.google.com/webstore/detail/kancolle-command-center-%E6%94%B9/hkgmldnainaglpjngpajnnjfhpdjkohh) or Github variant (better known as developer builds).
- Which game play mode you are using?
- Screenshots which accurately paint the issue(s) you are facing.
- A step by step method that you did to describe how you got to that issue.
- A KC3 Error Report JSON file if you have faced an API error. To upload it, you might append `.txt` as file name extension.

After reading previous part of instruction, you can safely remove them now (including this line). Then fill up following part with your situation.

**Comment by mikenzb** [comment]
Hourly lines show however aren't in sync due to the way of how the game handles it, see more info here #1243 

Most likely won't be fixed anytime soon.
