### ISSUE TITLE
Show improvement stars of equipment in reinforcement expansion

### ISSUE THREAD

**Issue by Shurichan** [KC3Kai/KC3Kai#2118]
Little quality of life thing, the improvement stars of the equips in reinforcement expansion could be shown like the stars of the equipment in normal slots.
![2017-06-29 21_18_15- - - - - dmm games](https://user-images.githubusercontent.com/13228415/27703808-423b37d0-5d11-11e7-85d2-f5e1ac28c820.png)

**Comment by Vultren** [comment]
Part of #2117

**Comment by mikenzb** [comment]
Should be part of the next KC3 update.
