### ISSUE TITLE
Cant play Kancolle, help!

### ISSUE THREAD

**Issue by jockey123** [KC3Kai/KC3Kai#2119]
Please make sure that you have these details on hand when submitting your issue/bug report as this will greatly speed up the issue triage process -- thank you!

- Chrome version - 59.0.3071.115
- OS - Windows 7
- 64bit
- KC3 Kai version - 31.7.2
- Build - webstore version [Chrome Web Store]
- Game Mode - Customize DMM Website
- ![error](https://user-images.githubusercontent.com/29840923/27772032-35e8964a-5f31-11e7-8fe9-5fc3dbf7928e.png)
- What i did before the error - I just update the KC3 and Google chrome and when i started to running the kancolle that error happens

**Comment by nonsensed** [comment]
This appears to be a problem with the game servers, not kc3. The servers were down for a while, so nobody could log in. I was finally able to log in just now, but I can't guarantee everyone can log in just yet.

May as well leave this open until the game servers stop acting up.

**Comment by jockey123** [comment]
Thanks for the help, you´re right.
