### ISSUE TITLE
Picture error

### ISSUE THREAD

**Issue by MorganGodFreman** [KC3Kai/KC3Kai#2120]
Every time I take a picture with the camera in KC3 only about 70% of the image is captured. I haven't fiddled with any of the settings of KC3 on this system yet, however I didn't find a setting that matched my [issue.](http://i.imgur.com/h1CFEmJ.jpg)

-Chrome ver. 59.0.3071.115
-Windows 10 ver. 14393.1358
-64bit
-KC3 ver. 31.7.2
-chrome store

**Comment by ethrundr** [comment]
Would you please re-upload the image result? 
Preferably directly to here, by dragging the image to the textbox, or clicking link at the bottom of this textbox.

Your link above redirects me to a "removed.png" image.

**Comment by MorganGodFreman** [comment]
![2017-07-04 18-15-58 36](https://user-images.githubusercontent.com/29901501/27845531-fb2fac22-60e4-11e7-90ff-4bbe1aa42f7d.jpg)

**Comment by mikenzb** [comment]
Can you go into the KC3 settings and try playing with the 'Device Pixel Ratio' settings under `Screenshots` to see if that fixes your issue.

Otherwise make sure you are also aren't zooming the KC3 page by clicking on the KC3 panel/background and pressing `CTRL` + `0` to reset the zoom.

**Comment by MorganGodFreman** [comment]
Thank you the Device Pixel Ratio fixed it. However there must be something about my laptop that just doesn't fit the screen correctly because no the image is in full, but there is a blue border. My Home Computer doesn't have this issue... Thank you none the less.

**Comment by mikenzb** [comment]
It might have something to do with your laptop screen resolution if I remember correctly, sometimes high screen resolutions will do that.
