### ISSUE TITLE
KC3 simulator support accuracy

### ISSUE THREAD

**Issue by Divinity123** [KC3Kai/KC3Kai#2124]
Hello there. I have been testing with different support fleet recently and I realise that the shelling support is way too accurate as compared to in-game. I suspect that the base accuracy term used by the simulator is 90, same as that of day time shelling. But there are multiple sources suggesting that it should be around 64 for BBs and somewhat lower for CVs.

Is there any chance to modify the base accuracy of shelling support by the simulator? Any way, if you need any help with Chinese translation, feel free to bug me on github or in my stream (https://www.twitch.tv/divinity_123).

sources:
http://nga.178.com/read.php?tid=8785343
http://nga.178.com/read.php?tid=8194190

Cheers.

**Comment by Divinity123** [comment]
Wrong repo

**Comment by ethrundr** [comment]
It's actually OK to leave the issue here, since kancolle-replay (simulator) is part of this project, only have different repo.

However, since you've posted there as well, I'll mark this one as duplicate.
