### ISSUE TITLE
game screen crash 

### ISSUE THREAD

**Issue by ToyBox456** [KC3Kai/KC3Kai#2133]
- Which game play mode you are using?

After reading previous part of instruction, you can safely remove them now (including this line). Then fill up following part with your situation.

### Screenshots (if applicable):
![default](https://user-images.githubusercontent.com/30473282/28629982-f883475a-7263-11e7-8670-3c9face48d47.PNG)

**Comment by mikenzb** [comment]
This sounds like the same error that happened in #2036, will close this issue for now. Please find more info the the previous issue that was opened.
