### ISSUE TITLE
How to change Admiral Dashboard's position

### ISSUE THREAD

**Issue by LucidAtray** [KC3Kai/KC3Kai#2135]
Hello. I just wanted to know if you can change the dashboard's position on screen. 

I've seen people who has it below the game, and others like me to the side of it. Is there a way to change its position, or it's automatic? I haven't found any option on settings, but maybe I just didn't realize it was referring to this. 

Thank you in advance.

**Comment by mikenzb** [comment]
In the 3 vertical dots menu in the top right you can set a dock side. 
![capture](https://user-images.githubusercontent.com/5982780/28749324-2d804010-7517-11e7-8383-9d4640787c41.PNG)
