### ISSUE TITLE
Ships not being displayed in Leveling tab

### ISSUE THREAD

**Issue by TenkaLion** [KC3Kai/KC3Kai#2140]
Chrome version: 59.0.3071.115

OS and version: Windows 10, version 1703

64-bit

KC3 Kai version: 31.7.4

I've tried running the Webstore version

I'm using the Customize DMM Website mode.

Screenshots:
[http://imgur.com/a/3YxnW](url)

Essentially, Yura isn't showing up in the Leveling tab despite being in my fleet and properly displaying in the Ship tab.

**Comment by Vultren** [comment]
She is most likely still in your [other ships] section. Have you updated the extension or refreshed(F5) the page?

**Comment by reinforce** [comment]
@TenkaLion Is your ship heartlocked? Leveling tab only display ships with heart lock.

**Comment by TenkaLion** [comment]
Thats's the one! I must've misclicked, thank you.
