### ISSUE TITLE
Support to new ship

### ISSUE THREAD

**Issue by vandojapan** [KC3Kai/KC3Kai#2163]
### Versions:
KC3:Release 31.9.1(Chrome Web Store Version) Chrome:60.0.3112.90(64bit)
### Steps to reproduce:
*I don't customize game page. I only have open KC3 Kai Information Panel.
1.Join the **"旗風"**(DD Hatakaze)*1 to fleet.
 *1 旗風 is 2017 Summer Event E-2 clear reward ship.
### Actual behaviour:
"Data processing error of KC3 Kai" dialog is displayed
### Expected behaviour:
I do not understand it because it was the first time I saw it.
### Screenshots (if applicable):
![image](https://user-images.githubusercontent.com/30983282/29251910-b3577122-8098-11e7-858b-e569380fcae4.png)
![image](https://user-images.githubusercontent.com/30983282/29251946-6f09db30-8099-11e7-9b9f-0f27c486ec81.png)

### Error Report (if applicable):
[KC3-Error-1502644029.txt](https://github.com/KC3Kai/KC3Kai/files/1220626/KC3-Error-1502644029.txt)

**Comment by sinsinpub** [comment]
your error seems weird, many other players get Hatakaze without problem anyway. i guess there is something wrong with ur local storage caches. try following steps:
 * Close the game and all other KC3 tabs, leave one Strategy Room (`戦闘指揮所`) page opened
 * Open Chrome Console (Ctrl + Shift + I for Windows), execute this command:
```
delete localStorage.ships; delete localStorage.gears; delete localStorage.raw;
```
 * Restart the game via KC3 to check if it solved

**Comment by vandojapan** [comment]
Thank you, it has been resolved
