### ISSUE TITLE
KC3 doesn't work (it works again)

### ISSUE THREAD

**Issue by Treehe** [KC3Kai/KC3Kai#2175]
edit: it works again

Can someone help me please?
Yesterday it still worked

KC3 version: 31.9.3
Chrome version: 60.0.3112.101
Windows 10 64bit
build from  Web Store
game play mode: Customize DMM Website

![error](https://user-images.githubusercontent.com/31164615/29488873-dcce89a8-8513-11e7-82e9-6b32f9be6eea.png)

**Comment by demzangg** [comment]
experiencing the exact same problem, after the update, somehow got internal server error...

**Comment by artutia** [comment]
I am experiencing the same problem too. Going to sleep leaving the computer running and after 3 hours i can not get access to kancolle anymore. Using VPN works but somehow it is very slow and when i tried to sortie i got disconnected. Please dragonjet fix it soon.

**Comment by mikenzb** [comment]
Might I ask what ISP you guys are with? there have been reports that if your ISP is Vodafone and you're in the EU, you're getting a bad connection to the game servers.

**Comment by artutia** [comment]
oh that seems to be true. I am in German and use Vodafone. Do you have any idea how to fix it?

**Comment by mikenzb** [comment]
You could try a proxy or VPN, otherwise you will need to wait for your ISP to fix the issue. You could try contacting them but I wouldn't expect much from them.
[
More info here.](https://www.reddit.com/r/kancolle/comments/6uq03i/help_game_frame_doesnt_appear/)

**Comment by sinsinpub** [comment]
it's known connection problem if server of u guys is `トラック泊地` (Truk Anchorage), see [tweet](https://twitter.com/KanColle_STAFF/status/898774844615020544)

**Comment by artutia** [comment]
No unfortunately, my server is 岩川基地 (Iwagawa Airfield).
