### ISSUE TITLE
Sortie log and prediction doesn't work

### ISSUE THREAD

**Issue by shawaota** [KC3Kai/KC3Kai#2180]
- Chrome Version 60.0.3112.101 (Official Build) (64-bit)
- Windows 10 Home Single Language 64bit
- KC3 Kai webstore version 31.9.3
I was doing events (E4 Easy) when the last update notice appeared. Before I updated KC3 the battle prediction and log run normally. After I closed the game window and updated KC3, I resumed my run on E4 E and even though the tab showed which enemy pattern I faced, it didn't show the prediction whether the enemies sunk or not and whether my ships get damaged or not. Then on boss node KC3 tab crashed and can't show the enemy pattern.
After that I checked on strategy room to see the battle log. It's none!
### Actual behaviour:
- Didn't show battle prediction (and briefly showed wrong battle prediction after the node ended)
- Didn't show damage prediction
- Recorded battle log shows on strategy room
### Expected behaviour:
- Show battle prediction (enemy pattern, damage to enemy, drop, air battle, planes status, formation, dll)
- Show damage prediction (kanmusu health bar reduced with nominal of damage along with color changes)
- Sortie history logs (maps, events, pvp) available and recorded 
![1503423611750](https://user-images.githubusercontent.com/31212757/29579154-1356d040-879c-11e7-870c-9428e994ce2a.jpg)
![1503424056689](https://user-images.githubusercontent.com/31212757/29579339-bf75c2a0-879c-11e7-921c-92400e17b144.jpg)
[KC3-Error-1503320493.txt](https://github.com/KC3Kai/KC3Kai/files/1239013/KC3-Error-1503320493.txt)

**Comment by mikenzb** [comment]
A restart should've fixed this issue, if not a restart of chrome should've fixed it.
@shawaota can you report back on if this issue still occurs on the latest update?

**Comment by shawaota** [comment]
Thanks, it's fixed now. If this happens again on next update I'll report it back.

**Comment by mikenzb** [comment]
I've run into this issue myself however it was one off issue, not sure what caused it but I was updating it and I reloaded it via the chrome extensions page and when I started KC3 and did a sortie I ran into the same issue.

Haven't run into it again so I presume it's fixed.

**Comment by ethrundr** [comment]
This issue usually happens when the connection between the Game, the Panel and the Strategy Room are broken, which most likely due to update on the KC3kai, or either one failed to load properly.

Sometimes it also caused by some script malfunctioning or hiccuped within the KC3kai Panel, rendering it unable to fetch the latest data.

Given the condition, restarting either extension or the browser will most likely solves this hiccup.
