### ISSUE TITLE
[Bug] Quest sync does not work due to size limits (causes memory leak)

### ISSUE THREAD

**Issue by mikenzb** [KC3Kai/KC3Kai#2183]
Paging @Adrymne 
![capture](https://user-images.githubusercontent.com/5982780/29562493-a25553ac-878d-11e7-89c3-4a83a3b23e62.PNG)

I've noticed my quest sync has not been working and I checked the error logs and I found the follow errors being spammed every 30 seconds or so, for some reason the failures of quest syncing will cause chrome to eat up memory because chrome is trying to send anonymous reports to google about said errors? (not quite sure why since it's turned off anyways)

If something could be done about this that would be nice otherwise I'll live with it turned off since it stops the memory leak.

Running ` localStorage.quests.length` displays an result of average result of `8500` - `9950`.

**Comment by sinsinpub** [comment]
a code i found to handle big item: https://github.com/kdzwinel/Context/blob/master/js/classes/HugeStorageSync.class.js

**Comment by Adrymne** [comment]
Can you pastebin your `localStorage.quests`? I want to make sure nothing strange is going on.

I suspect sinsin is probably right, though.

**Comment by mikenzb** [comment]
Returns the following response: 
```"{"q420":{"id":420,"type":1,"status":3,"progress":0},"qundefined":{"progress":0,"tracking":false},"q0":{"id":0,"type":0,"status":0,"progress":0,"tracking":false},"q624":{"id":624,"type":1,"status":3,"progress":0},"q164":{"id":164,"type":1,"status":3,"progress":0},"q293":{"id":293,"type":1,"status":3,"progress":0},"q165":{"id":165,"type":1,"status":3,"progress":0},"q166":{"id":166,"type":1,"status":3,"progress":0},"q294":{"id":294,"type":1,"status":3,"progress":0},"q625":{"id":625,"type":1,"status":3,"progress":0},"q627":{"id":627,"type":1,"status":3,"progress":0},"q630":{"id":630,"type":1,"status":3,"progress":0},"q629":{"id":629,"type":1,"status":3,"progress":0},"q632":{"id":632,"type":1,"status":3,"progress":0},"q631":{"id":631,"type":1,"status":3,"progress":0},"q167":{"id":167,"type":1,"status":3,"progress":0},"q633":{"id":633,"type":1,"status":3,"progress":0},"q168":{"id":168,"type":1,"status":3,"progress":0},"q295":{"id":295,"type":1,"status":3,"progress":0},"q169":{"id":169,"type":1,"status":3,"progress":0},"q296":{"id":296,"type":1,"status":3,"progress":0},"q170":{"id":170,"type":1,"status":3,"progress":0},"q801":{"id":801,"type":4,"status":3,"progress":0},"q802":{"id":802,"type":4,"status":3,"progress":0},"q803":{"id":803,"type":4,"status":3,"progress":0},"q804":{"id":804,"type":4,"status":3,"progress":0},"q805":{"id":805,"type":1,"status":3,"progress":0},"q806":{"id":806,"type":1,"status":3,"progress":0},"q234":{"id":234,"type":1,"status":3,"progress":2},"q297":{"id":297,"type":1,"status":3,"progress":0},"q421":{"id":421,"type":1,"status":3,"progress":0},"q171":{"id":171,"type":1,"status":3,"progress":0},"q172":{"id":172,"type":1,"status":3,"progress":0},"q808":{"id":808,"type":1,"status":3,"progress":0},"q809":{"id":809,"type":1,"status":3,"progress":0},"q634":{"id":634,"type":1,"status":3,"progress":0},"q810":{"id":810,"type":1,"status":3,"progress":0},"q811":{"id":811,"type":1,"status":3,"progress":0},"q812":{"id":812,"type":1,"status":3,"progress":0},"q813":{"id":813,"type":1,"status":3,"progress":0},"q807":{"id":807,"type":1,"status":3,"progress":0},"q173":{"id":173,"type":1,"status":3,"progress":0},"q635":{"id":635,"type":1,"status":3,"progress":0,"tracking":[[0,5]]},"q816":{"id":816,"type":1,"status":3,"progress":0},"q312":{"id":312,"type":1,"status":3,"progress":0,"tracking":[[4,4]]},"q636":{"id":636,"type":1,"status":3,"progress":0},"q814":{"id":814,"type":1,"status":3,"progress":0},"q815":{"id":815,"type":1,"status":3,"progress":0},"q174":{"id":174,"type":1,"status":3,"progress":0},"q817":{"id":817,"type":1,"status":3,"progress":0},"q818":{"id":818,"type":1,"status":3,"progress":0},"q175":{"id":175,"type":4,"status":3,"progress":0},"q640":{"id":640,"type":4,"status":3,"progress":0},"q819":{"id":819,"type":4,"status":3,"progress":0},"q176":{"id":176,"type":4,"status":3,"progress":0},"q820":{"id":820,"type":4,"status":3,"progress":0},"q639":{"id":639,"type":4,"status":3,"progress":0},"q823":{"id":823,"type":4,"status":3,"progress":0},"q824":{"id":824,"type":4,"status":3,"progress":0},"q821":{"id":821,"type":4,"status":3,"progress":0},"q313":{"id":313,"type":4,"status":3,"progress":0},"q641":{"id":641,"type":4,"status":3,"progress":1},"q825":{"id":825,"type":4,"status":3,"progress":0},"q642":{"id":642,"type":4,"status":3,"progress":0},"q644":{"id":644,"type":4,"status":3,"progress":0},"q646":{"id":646,"type":4,"status":3,"progress":2},"q177":{"id":177,"type":4,"status":3,"progress":0},"q826":{"id":826,"type":4,"status":3,"progress":0},"q827":{"id":827,"type":4,"status":3,"progress":0},"q828":{"id":828,"type":4,"status":3,"progress":0},"q830":{"id":830,"type":4,"status":3,"progress":0},"q647":{"id":647,"type":4,"status":3,"progress":2},"q829":{"id":829,"type":4,"status":3,"progress":0},"q831":{"id":831,"type":4,"status":3,"progress":0},"q832":{"id":832,"type":4,"status":3,"progress":0},"q833":{"id":833,"type":4,"status":3,"progress":0},"q178":{"id":178,"type":4,"status":3,"progress":0},"q834":{"id":834,"type":4,"status":3,"progress":0},"q835":{"id":835,"type":4,"status":3,"progress":0},"q179":{"id":179,"type":4,"status":3,"progress":0},"q836":{"id":836,"type":4,"status":3,"progress":0},"q837":{"id":837,"type":4,"status":3,"progress":0},"q422":{"id":422,"type":4,"status":3,"progress":0},"q649":{"id":649,"type":4,"status":3,"progress":2},"q838":{"id":838,"type":4,"status":3,"progress":0},"q314":{"id":314,"type":4,"status":3,"progress":0},"q648":{"id":648,"type":4,"status":3,"progress":2},"q705":{"id":705,"type":4,"status":3,"progress":0},"q839":{"id":839,"type":4,"status":3,"progress":0},"q650":{"id":650,"type":4,"status":3,"progress":2},"q423":{"id":423,"type":4,"status":3,"progress":0},"q651":{"id":651,"type":4,"status":3,"progress":2},"q840":{"id":840,"type":4,"status":3,"progress":0},"q841":{"id":841,"type":4,"status":3,"progress":0},"q652":{"id":652,"type":4,"status":3,"progress":2},"q842":{"id":842,"type":4,"status":3,"progress":0},"q843":{"id":843,"type":4,"status":3,"progress":0},"q844":{"id":844,"type":4,"status":3,"progress":0},"q653":{"id":653,"type":4,"status":3,"progress":2},"q655":{"id":655,"type":4,"status":3,"progress":2},"q654":{"id":654,"type":4,"status":3,"progress":2},"q845":{"id":845,"type":4,"status":3,"progress":0},"q657":{"id":657,"type":4,"status":3,"progress":2},"q846":{"id":846,"type":4,"status":3,"progress":0},"q847":{"id":847,"type":4,"status":3,"progress":0},"q656":{"id":656,"type":4,"status":3,"progress":0},"q658":{"id":658,"type":4,"status":3,"progress":2},"q848":{"id":848,"type":4,"status":3,"progress":0},"q659":{"id":659,"type":4,"status":3,"progress":0},"q849":{"id":849,"type":4,"status":3,"progress":0},"q850":{"id":850,"type":4,"status":3,"progress":0},"q315":{"id":315,"type":4,"status":3,"progress":0},"q851":{"id":851,"type":4,"status":3,"progress":0},"q853":{"id":853,"type":4,"status":3,"progress":0},"q852":{"id":852,"type":4,"status":3,"progress":0},"q180":{"id":180,"type":4,"status":3,"progress":0},"q855":{"id":855,"type":4,"status":3,"progress":0},"q856":{"id":856,"type":4,"status":3,"progress":0},"q181":{"id":181,"type":4,"status":3,"progress":0},"q661":{"id":661,"type":4,"status":3,"progress":0},"q858":{"id":858,"type":4,"status":3,"progress":0},"q662":{"id":662,"type":4,"status":3,"progress":0},"q425":{"id":425,"type":4,"status":3,"progress":0},"q857":{"id":857,"type":4,"status":3,"progress":0},"q643":{"id":643,"type":5,"status":3,"progress":1},"q854":{"id":854,"type":5,"status":3,"progress":0,"tracking":[[1,1],[1,1],[1,1],[1,1]]},"q637":{"id":637,"type":5,"status":3,"progress":0},"q663":{"id":663,"type":5,"status":3,"progress":0,"tracking":[[10,10]]},"q822":{"id":822,"type":5,"status":3,"progress":0,"tracking":[[2,2]]},"q182":{"id":182,"type":4,"status":3,"progress":0},"q183":{"id":183,"type":4,"status":3,"progress":0},"q664":{"id":664,"type":4,"status":3,"progress":0},"q859":{"id":859,"type":4,"status":3,"progress":0},"q665":{"id":665,"type":4,"status":3,"progress":0},"q860":{"id":860,"type":4,"status":3,"progress":0},"q666":{"id":666,"type":4,"status":3,"progress":1},"q667":{"id":667,"type":4,"status":3,"progress":0},"q668":{"id":668,"type":4,"status":3,"progress":0},"q426":{"id":426,"type":5,"status":3,"progress":0,"tracking":[[1,1],[1,1],[1,1],[1,1]]},"q861":{"id":861,"type":5,"status":3,"progress":0,"tracking":[[2,2]]},"q862":{"id":862,"type":5,"status":3,"progress":0,"tracking":[[2,2]]},"q184":{"id":184,"type":4,"status":3,"progress":0},"q249":{"id":249,"type":3,"status":3,"progress":0},"q256":{"id":256,"type":3,"status":1,"progress":0,"tracking":[[0,3]]},"q259":{"id":259,"type":3,"status":3,"progress":0},"q424":{"id":424,"type":3,"status":3,"progress":0,"tracking":[[4,4]]},"q311":{"id":311,"type":3,"status":3,"progress":0,"tracking":[[0,7]]},"q863":{"id":863,"type":4,"status":3,"progress":0},"q645":{"id":645,"type":3,"status":1,"progress":0},"q265":{"id":265,"type":3,"status":3,"progress":0,"tracking":[[10,10]]},"q257":{"id":257,"type":3,"status":3,"progress":0},"q264":{"id":264,"type":3,"status":3,"progress":0},"q628":{"id":628,"type":3,"status":1,"progress":0},"q266":{"id":266,"type":3,"status":3,"progress":0},"q626":{"id":626,"type":3,"status":1,"progress":0},"q660":{"id":660,"type":4,"status":1,"progress":0},"q213":{"id":213,"type":2,"status":2,"progress":1,"tracking":[[10,20]]},"q214":{"id":214,"type":2,"status":3,"progress":0,"tracking":[[36,36],[24,24],[12,12],[6,6]]},"q404":{"id":404,"type":2,"status":2,"progress":1,"tracking":[[17,30]]},"q410":{"id":410,"type":2,"status":3,"progress":0,"tracking":[[1,1]]},"q703":{"id":703,"type":2,"status":3,"progress":0,"tracking":[[15,15]]},"q411":{"id":411,"type":2,"status":1,"progress":0,"tracking":[[1,6]]},"q221":{"id":221,"type":2,"status":1,"progress":0,"tracking":[[10,50]]},"q220":{"id":220,"type":2,"status":2,"progress":0,"tracking":[[4,20]]},"q201":{"id":201,"type":1,"status":3,"progress":0,"tracking":[[1,1]]},"q303":{"id":303,"type":1,"status":3,"progress":0,"tracking":[[3,3]]},"q402":{"id":402,"type":1,"status":3,"progress":0,"tracking":[[3,3]]},"q503":{"id":503,"type":1,"status":3,"progress":0,"tracking":[[5,5]]},"q702":{"id":702,"type":1,"status":3,"progress":0,"tracking":[[2,2]]},"q211":{"id":211,"type":5,"status":2,"progress":0,"tracking":[[0,3]]},"q216":{"id":216,"type":1,"status":3,"progress":0,"tracking":[[1,1]]},"q210":{"id":210,"type":1,"status":3,"progress":0,"tracking":[[10,10]]},"q218":{"id":218,"type":1,"status":2,"progress":0,"tracking":[[0,3]]},"q605":{"id":605,"type":1,"status":3,"progress":0,"tracking":[[1,1]]},"q504":{"id":504,"type":1,"status":3,"progress":0,"tracking":[[15,15]]},"q606":{"id":606,"type":1,"status":3,"progress":0,"tracking":[[1,1]]},"q607":{"id":607,"type":1,"status":3,"progress":0,"tracking":[[3,3]]},"q608":{"id":608,"type":1,"status":3,"progress":0,"tracking":[[3,3]]},"q609":{"id":609,"type":1,"status":3,"progress":0,"tracking":[[2,2]]},"q619":{"id":619,"type":1,"status":3,"progress":0,"tracking":[[1,1]]},"q403":{"id":403,"type":1,"status":2,"progress":0,"tracking":[[2,10]]},"q302":{"id":302,"type":2,"status":1,"progress":0,"tracking":[[2,20]]},"q304":{"id":304,"type":1,"status":1,"progress":0,"tracking":[[2,5]]}}"```
