### ISSUE TITLE
[bug]Inccorect FP calculation display with CVB

### ISSUE THREAD

**Issue by quzzimi** [KC3Kai/KC3Kai#2187]
Inccorect FP calculation with cvb 
iirc , i reported this a while ago 
![image](https://user-images.githubusercontent.com/14950009/29652353-0747b7a2-88e0-11e7-940a-0163f88689d6.png)

**Comment by sinsinpub** [comment]
it's not simply `FP calculation`, it's shelling power of expedition support fleet. and our formula is out of date, not only CVB missed.
Updated at #2188 now.

btw, search through our issues, no another report found from u
