### ISSUE TITLE
sharing KC3 ship icons?

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#2190]
I'm wondering what's current kc3 dev teams opinion towards sharing KC3 ship icons? I'm not 100% sure, but it seems opendb is using it, and some other non-kc3 projects might benefit from it as well.

**Comment by DynamicSTOP** [comment]
it's under MIT, no?
https://github.com/KC3Kai/KC3Kai/blob/master/LICENSE

**Comment by Javran** [comment]
I see, so it's good to be used then, just to inform that I might use some ship icons and of course this will be properly acknowledged, thanks!
