### ISSUE TITLE
Stuck at Loading

### ISSUE THREAD

**Issue by ViNdanza** [KC3Kai/KC3Kai#2193]
waited for an hour still didn't finish load

![asdsfghjkl](https://user-images.githubusercontent.com/31355543/29727233-fc390684-8a0d-11e7-84d4-6ddbe1f52f9b.png)

**Comment by mikenzb** [comment]
Sounds like a network issue, can you try starting without KC3 open? (Disabled Customizations and starting via `...or start without the info panel.` button)

**Comment by ViNdanza** [comment]
tried and it keep loading but i can play it on Mozzila with VPN

**Comment by mikenzb** [comment]
Sounds like it's a network issue then and not a KC3 issue, most likely related to this #2175 or something very similar.

Try waiting a few days to see if it will fix itself.

**Comment by ViNdanza** [comment]
i think its my Chrome fault i tried Mozzilla with Cookie and its work fine but Chrome it keep loading

**Comment by mikenzb** [comment]
You could try clearing your cache and cookies in chrome then to see if that helps.

**Comment by ViNdanza** [comment]
no luck i clear cache and reinstall still same

**Comment by ethrundr** [comment]
Have you check your firewall rules, proxy and antivirus settings?

This might sound dumb, but some of the connection problems lies on misconfigured settings from one of three I mentioned just now.

Even if you never actively update those rules and settings, they sometimes adds rules automatically only by a simple click on the notification they gives to you. Often, users are simply clicking OK on each notification that appears, without actually realize what the notification is telling you.

**Comment by ViNdanza** [comment]
checked everything nothing wrong tho i gonna close this thread as i will play with Mozilla thx for the help
