### ISSUE TITLE
Air power is different from Poi, EO, KCV, etc.

### ISSUE THREAD

**Issue by gakada** [KC3Kai/KC3Kai#2194]
All other tools use the [internal proficiency hypothesis](http://ja.kancolle.wikia.com/wiki/%E8%89%A6%E8%BC%89%E6%A9%9F%E7%86%9F%E7%B7%B4%E5%BA%A6) to calculate air power (e.g., [Poi](https://github.com/poooi/poi/blob/master/views/utils/game-utils.es), [EO](https://github.com/andanteyk/ElectronicObserver/blob/master/ElectronicObserver/Utility/Data/Calculator.cs), [KCV](https://github.com/Grabacr07/KanColleViewer/blob/master/source/Grabacr07.KanColleWrapper/Models/AirSuperiorityPotential.cs), [kancolle-calc](http://kancolle-calc.net/data/calc.js), [kancollecalc](http://kancollecalc.web.fc2.com/air_supremacy.js)), which is basically

    floor(
      (aa + improvement bonus * improvement level + interceptor bonus) * sqrt(slot size)
      + sqrt(proficiency experience bonus / 10)
      + proficiency level bonus
    )

for each slot. While for KC3Kai it's the values in [ConfigManager.js](https://github.com/KC3Kai/KC3Kai/blob/master/src/library/managers/ConfigManager.js). Compared to Poi and EO:
* 艦上戦闘機 (6)/水上戦闘機 (45)/局地戦闘機 (48)/噴式戦闘機 (56): no 56 (0 for proficiency level bonus in Poi, but not in EO), otherwise seems like experimental values from 2015 shitaraba posts (maybe also interpreted wrong).
* 艦上爆撃機 (7)/艦上攻撃機 (8)/陸上攻撃機 (47)/噴式戦闘爆撃機 (57)/噴式攻撃機 (58): no 58, otherwise, e.g., [1, 3] instead of [sqrt(10), sqrt(12)].
* 水上爆撃機 (11): also, [7, 9] instead of [6 + sqrt(10), 6 + sqrt(12)].

In result, for a typical fleet air power can be lower by ~5 points in KC3Kai (even more lower for the lower bound).

**Comment by sinsinpub** [comment]
in fact i'm also wondering where have those values come from...
as they are config for now, please try to set this and check if i'm wrong or not:
```json
{"6":[[0,0.949],[1,1.549],[3.581,3.975],[7,7.324],[11.345,11.627],[16.646,16.898],[16.915,17.146],[25.162,25.464]],"7":[[0,0.949],[0,1.549],[1.581,1.975],[2,2.324],[2.345,2.627],[2.646,2.989],[2.915,3.146],[3.162,3.464]],"8":[[0,0.949],[0,1.549],[1.581,1.975],[2,2.324],[2.345,2.627],[2.646,2.989],[2.915,3.146],[3.162,3.464]],"11":[[0,0.949],[0,1.549],[2.581,2.975],[3,3.324],[3.345,3.627],[5.646,5.989],[5.915,6.146],[9.162,9.464]],"45":[[0,0.949],[1,1.549],[3.581,3.975],[7,7.324],[11.345,11.627],[16.646,16.898],[16.915,17.146],[25.162,25.464]],"47":[[0,0.949],[0,1.549],[1.581,1.975],[2,2.324],[2.345,2.627],[2.646,2.989],[2.915,3.146],[3.162,3.464]],"48":[[0,0.949],[1,1.549],[3.581,3.975],[7,7.324],[11.345,11.627],[16.646,16.898],[16.915,17.146],[25.162,25.464]],"57":[[0,0.949],[0,1.549],[1.581,1.975],[2,2.324],[2.345,2.627],[2.646,2.989],[2.915,3.146],[3.162,3.464]]}
```

type[2] 56, 58 are not implemented yet, no prove to tell which bonus they will be applied.

**Comment by gakada** [comment]
It's old values from wikia (or rather from tests published on shitaraba, but they were added on wikia right before [this](https://github.com/KC3Kai/KC3Kai/commit/760611389a371e54b49b1bbdfb33fd558d2d1a79#diff-9515268a2e36e92fc966603ca69d6025) commit, 25.411 was changed to 25.467 the same day on wikia :/).

For config, looks ok as approximation (only 3 digits). But for implementation, probably should use only [those](http://ja.kancolle.wikia.com/wiki/%E8%89%A6%E8%BC%89%E6%A9%9F%E7%86%9F%E7%B7%B4%E5%BA%A6#.E5.86.85.E9.83.A8.E7.86.9F.E7.B7.B4.E5.BA.A6.E4.BB.AE.E8.AA.AC.5B4.5D) values (first 3 rows, also not in config? as they don't change), then use [sqrt](http://ja.kancolle.wikia.com/wiki/%E8%89%A6%E8%BC%89%E6%A9%9F%E7%86%9F%E7%B7%B4%E5%BA%A6#.E5.88.B6.E7.A9.BA.E5.80.A4.5B4.5D), etc. for actual values.

Something else to note:
* Seems like Poi and EO use `0, 1, 1, 1, 1, 3, 3, 6` for 11, while KCV, ja.kancolle.wikia, kancolle-calc and kancollecalc use `0, 0, 1, 1, 1, 3, 3, 6`.
* The difference between lower and upper bounds is usually small (or even zero), so min, max, average, or range can be used as default displaying method (min for EO IINM).

**Comment by sinsinpub** [comment]
new values are indeed gotten by sqrt, i feel 3 decimals is good enough because final air power is displayed as approximation integer, and no multiplying applied to the proficiency bonus (no error amplified). will not need to change any implementation and just be fixed by updating the config 😃 

the range one is already default displaying, the simple average just reserved as an old method.
and i'm using the same extra bonus for type 11 from [wikiwiki](http://wikiwiki.jp/kancolle/?%B4%CF%BA%DC%B5%A1%BD%CF%CE%FD%C5%D9) and 検証wiki.

**Comment by gakada** [comment]
Well, `floor(3.581 + (12 + 7 * 0.2) * sqrt(12)) = 49` but `floor(2 + sqrt(25 / 10) + (12 + 7 * 0.2) * sqrt(12)) = 50` (零式艦戦53型(岩本隊) with || and 7 stars on 12 slot), there are quite a few other cases as well (if you loop for levels, slot sizes, aa, stars, bounds, types).

`0, 0, 1, 1, 1, 3, 3, 6` is also what vita version uses, not sure why it's different in EO/Poi.
