### ISSUE TITLE
add a button/trigger to stop logging battle data

### ISSUE THREAD

**Issue by ztjal** [KC3Kai/KC3Kai#2207]
for example, map 1-1, battle data is just junk data, meaningless.
1, add a buttom call "clean", let the people can click to clear battle data for current selected map.
2, add a checkbox call "log", let the people can choose whether to log battle data for current selected map.

**Comment by HitomaruKonpaku** [comment]
I asked for it already #2167 but... nvm

**Comment by ztjal** [comment]
ok, maybe add a checkbox to stop log battle data is fast and efficient.

**Comment by ethrundr** [comment]
Renaming the issue to match the one requested by @ztjal, since the original title is indeed duplicate of #2167.

Just to avoid misinterpreting the suggestion.
