### ISSUE TITLE
Capitalize remodel numbers in Foreign ships

### ISSUE THREAD

**Issue by Omegaxis8009** [KC3Kai/KC3Kai#2208]
Can the drei for Bismarck be capitalized? It feels out of place with the other ships who have Kai and Kai Ni capitalized

**Comment by nonsensed** [comment]
I have no problem with doing this for the English translation. I'll leave this for a few days just in case someone wants to give a compelling reason not to.

This would also apply to other foreign ships that don't capitalize their "two" equivalent as well.

I don't think the in-game text is a good reason not to capitalize them. In English, titles of this nature are capitalized. The only argument I can think of is if the German or Italian grammar rules necessitate not capitalizing the relevant words.

**Comment by LostLogia4** [comment]
If it's just your nitpicking, then this issue's not worth handling. You really should put a proper title in your issue.

**Comment by Tsubakura** [comment]
You want a reason why its uncapitalized? Because the [KC cards themselves doesn't capitalize them either.](https://vignette.wikia.nocookie.net/kancolle/images/0/02/FBB_Bismarck_drei_178_Card.jpg/revision/latest?cb=20150519041733)

But it does look out of place, I give you that.

**Comment by nonsensed** [comment]
Indeed. This is why I wrote:

_I don't think the in-game text is a good reason not to capitalize them._

I see it as something like translating "Me ga Iowa" as "Me am Iowa". Sure, it's what she said, but should it really be left that way?

**Comment by ethrundr** [comment]
My personal opinion is to stick with the original language's set of grammatical writing, if there is any.
German and Italian tend to not capitalize word that are not beginning of the sentence, names or buildings and nouns. Adhere to that, even though it is seems out of place, I do think we need to left it as is.

While for Kai and Kai Ni, Japanese does **not** has the set of grammatical rule to writing their language in romaji writing (this is not official writing after all, just a way on how us non-Japanese read them). Thus, the translation should follow the common grammatical rule.

**Comment by nonsensed** [comment]
Wait, aren't the "drei" and "due" nouns because they are part of the names of the ships?

**Comment by ethrundr** [comment]
AFAIK, it's not. But I might be mistaken as well.
Last time learning those languages is 2-3 yrs ago.

**Comment by nonsensed** [comment]
Alright, I've been doing entirely too much thinking about this subject and had some conversations outside of this github discussion.

- We generally fix bad grammar in subtitles when the game's English is incorrect.
- In English, capitalizing the `drei` in Bismarck would be the correct method.
- We already capitalize `Kai` in ship names. Not capitalizing `drei` is therefore inconsistent.
- We don't actually keep to the original language's text. For Russian ships, their names are romanized. Obviously, the same is true of Japanese ships. After considering this, I don't really think using German grammar rules necessarily matters for names in the English name translations.
- There's no rule about maintaining the game's in-game text for exactly the same reason. We already have a history of changing ship names from the in-game text.
- Any German or Italian translations can feel free to do what they want under their own capitalization rules. This change is only for the English translation.
