### ISSUE TITLE
Game Error 201x An Error 201 from the game API  

### ISSUE THREAD

**Issue by booobooo7** [KC3Kai/KC3Kai#2210]
hi everyone , 

recently facing a problem with this error code 201. 

Game Error 201x
An Error 201 from the game API has occured. This may be because you're still logged in on another game client or it may be related to macro detection. Exercise caution if you see this repeatedly.

any idea ? once popup , the game turn to catboom with this massage .

**Comment by nonsensed** [comment]
In this case, KC3 is only the messenger telling you what happened. It isn't causing the 201 errors to occur.

If you are seeing the 201 message a lot, this is an old topic and may have some outdated info, but see here:
http://himeuta.org/showthread.php?7333-Bot-detection-cat-errors-201-cat

**Comment by mikenzb** [comment]
Related to #1915, there is also some info there.

However there is nothing we can do about the 201 errors, will close this issue for now.
