### ISSUE TITLE
Some Japanese quotes incorrect

### ISSUE THREAD

**Issue by redpizza** [KC3Kai/KC3Kai#2214]
Hi there :D
I've found some Japanese subtitles issues.

- Hatsukaze (Kai): Equip(1) and Equip(2) are swapped each other. Battle quote is same as Join quote, it should be "はっきり言って、妙高姉さんのほうが私は怖いわ。". Yasen(2) should be "なんでこっち来るのよー！".
- Mizuho (Kai): Most quotes weird. Need to redone in overall.
- Akashi Kai: Poke(1)'s kanji is wrong, It should be "どうぞ、よろしくお願いたします！".
- Mochizuki (Kai): Equip(1) quote used by Equip(2). Equip(2) quote used by Equip(3). Equip(3) quote used by Equip(1). Attack quote is same as Battle quote, it should be "雷撃戦って…あぁ…ちょっと面倒…". Yasen(2) should be "射線は…まぁいっかぁ…適当でも。".
- Arashi (Kai): Battle's kanji is wrong, It should be "敵艦発見、合戦準備。撃ち方…始め！". Yasen(2) should be "天下の第四駆逐隊、まかり通る！くらえ！" for kanji issue.
- Hyuuga: Sortie quote has unnecessary space, It should be "伊勢のやつ、張り切り過ぎだ。". Equip(1) should be "この強化、どう戦力に影響するか…". Yasen(2) should be "敵艦隊は、何の為に攻めてくるのだ…？".
- Hyuuga Kai: Equip(1) has unnecessary character, It should be "まさかの航空戦艦の時代か？".
- Agano (Kai): Damaged(1) and Damaged(2) are swapped each other.
- Asashio (Kai): Damaged(1) and Damaged(2) are swapped each other.
- Asashio Kai Ni D: Damaged(1) should be "やだ、被弾？！やらせないっ！対空、対潜見張り、厳としてっ！"
- Mikazuki (Kai): Poke(1) and Poke(2) are swapped each other. Attack quote is same as Battle quote, it should be "当たって…っ！". Yasen(2) should be "砲雷撃戦、いっきまーす！".
- Shigure (Kai, Kai Ni): Damaged(1) and Damaged(2) are swapped each other.
- Kiyoshimo (Kai): Attack and Yasen(2) are swapped each other.
- Hagikaze (Kai): Damaged(3) quote has erratum, it should be "きゃああっ！？ま、まさか、舵をやられたの？復旧できる？お、お願い！". Yasen(2) quote is same as Atteck quote, it should be "砲撃開始！萩風、撃ちます！". 
- Junyou (Kai): Poke(1), Poke(2) and Poke(3) are same as Tone's Poke quotes for some reason.
- Junyou Kai Ni: Poke(1) is same as Tone's Poke quotes for some reason.
- Hayasui: Some quote uses Kai's quote. Poke(3) should be "提督さん、ターンテーブルは…その…いえ！問題ありません…大丈夫です。". Equip(2) should be "これなら…これなら艦隊の皆さんと一緒に戦えるかもしれません！". Sortie should be "第一補給部隊、旗艦速吸、抜錨！艦隊出撃です！" Yasen(2) should be "速吸航空隊、頼みます！". And, Yasen(1) should be "夜戦…っ、やるしかないです。主砲、砲戦用意、突入します！" for kanji issue.
- Hayasui Kai: Yasen(1) should be "夜戦…っ、やるしかないです。主砲、砲戦用意、突入します！" for kanji issue.
- Ooi Kai (Kai Ni): Yasen(2) should be "九三式酸素魚雷、やっちゃってよ！".
- Umikaze (Kai): Most quotes weird. Need to redone in overall.
- Matsukaze Kai: Kai's unique quotes not implemented: Join, Sortie, MVP
- Asakaze Kai: Kai's unique quotes not implemented: Intro, Join, Equip(2), Supply, Sortie
- Nowaki Kai: Yasen(2) should be "マリアナやレイテと比べれば、こんなのは！".
- Roma Kai: Attack quote uses Chinese kanji, it should be "戦艦ローマ、砲撃を開始する。主砲、撃て！"

That's all subtitle issues that I've found. But maybe there more misprint, other any issues.

**Comment by sinsinpub** [comment]
👍 glad to see this. because jp quotes are initially import from a Chinese wiki site, which should be auto crawled from old wikiwiki pages. there are many issues i know about old wrong dictation, swapped mess, typos. i have fixed some, but have no enough time to check them all lines by lines for each ships.

i'll double check these lines u mentioned. will be more appreciated if u can check and modify json directly and send us the pull request to [translation repo](https://github.com/KC3Kai/kc3-translations/tree/master/data/jp). 😸

**Comment by redpizza** [comment]
Thank you 👍 
I'll send pull request if I found other issues.

**Comment by sinsinpub** [comment]
![image](https://user-images.githubusercontent.com/160240/30357091-87f55b04-986f-11e7-9b5f-1efeb343dc89.png)
btw, if u enable this at settings, u can browse and check quotes more easily via `Strategy Room Dev-Only Quotes` page. if u use kc3 development version, can modify `quotes.json` and reload to see the changes immediately
![image](https://user-images.githubusercontent.com/160240/30357250-4c17cb66-9870-11e7-8fe3-c394d44a6841.png)
