### ISSUE TITLE
Duplicated ships missing in leveling

### ISSUE THREAD

**Issue by Z-Shang** [KC3Kai/KC3Kai#2224]
### Versions:
Chrome: 60.0.3112.113
OS: macOS 10.12.6 (64 bit)
KC 3 Kai: 31.9.6 from Chrome Store
### Steps to reproduce:
Collect more than one of the same ship, and check leveling page
### Actual behaviour:
Only some of the ships are shown in the leveling page
### Expected behaviour:
All of them are listed in the leveling page
### Screenshots (if applicable):
<img width="214" alt="2017-09-12 4 41 59" src="https://user-images.githubusercontent.com/859939/30353291-ddbc3602-97d9-11e7-9ccf-ed81d6190d8b.png">
<img width="710" alt="2017-09-12 4 44 42" src="https://user-images.githubusercontent.com/859939/30353292-e25b4cac-97d9-11e7-93ee-70ecb06db600.png">
(Leveling page sorted by name)

**Comment by mikenzb** [comment]
Are all those KTKMs locked?

IIRC the locking page only shows locked ships.

**Comment by Z-Shang** [comment]
I see, thanks a lot, sorry for the issue.
