### ISSUE TITLE
Still Cant Play

### ISSUE THREAD

**Issue by plyinglocket5** [KC3Kai/KC3Kai#2235]
I've downloaded this and tried everything but i still cant get the game to work can someone please help me here.

**Comment by Vultren** [comment]
We can't help you if you do not provide any of information that is asked for when you created an issue:

- Your Chrome version - via chrome://version/
- Your OS and its version
- 32bit or 64bit?
- Your KC3 Kai version - via chrome://extensions/
- Which build you have tried running? webstore version as in the one from [Chrome Web Store](https://chrome.google.com/webstore/detail/kancolle-command-center-%E6%94%B9/hkgmldnainaglpjngpajnnjfhpdjkohh) or Github variant (better known as developer builds).
- Which game play mode you are using?

Also have you tried playing without the panel?

**Comment by mikenzb** [comment]
No information provided from the OP, will assume that the issue has been fixed.

Feel free to reopen this issue or make a new one with information about said issue.
