### ISSUE TITLE
Outdated translation line

### ISSUE THREAD

**Issue by Ech0Sierra** [KC3Kai/KC3Kai#2236]
Outdated join translation for Oyashio

"456": {
        "Join": "DesDiv 15, Oyashio, ready to sortie! Straight ahead!",

"Desdiv 15, Oyashio. Ready to sortie! Steady as she goes!" = current wikia quote

**Comment by nonsensed** [comment]
It has been changed to
`15th Destroyer Division, Oyashio. I'm sortieing! Steady as she goes!`

This should appear in the next webstore update.

第十五駆逐隊 would be the full name of the Destroyer Division, not the abbreviation.

I would prefer not to use `Steady as she goes` if there is a better alternative for an acknowledgement phrase of this nature, but I agree that it should be changed from `Straight ahead`.

While I'm closing this issue, this can still be discussed if the change isn't one you agree with.
