### ISSUE TITLE
Kancolle Tab missing

### ISSUE THREAD

**Issue by midnightskylinse** [KC3Kai/KC3Kai#2239]
I can't find my kancolle tab in the dev tools. I'm running 64 bit with the latest version of KC3 from the Webstore. I'm using a browser called Vivaldi because Chrome doesn't save anything on my computer and I can't run extensions on it. (I am running the latest version of that browser right now.) 

![problem](https://user-images.githubusercontent.com/32233450/30779310-f28af1e2-a0a1-11e7-9102-314f329b227f.png)

Here's a screenshot.

**Comment by fajarmf94** [comment]
i think the bug is from the Vivaldi itself, all extension who use new tab in dev tool can not show the tab for the extension

**Comment by mikenzb** [comment]
Hi there,
We do not currently support Vivaldi or any of the other chromium based browsers as they tend to do changes which may break the devtools panel which is out of our control.

The best option would be to use Chrome or wait until Vivaldi fixes the issue as there is nothing we can do about it.
