### ISSUE TITLE
2 Bug for Kc3kai now, Tab Kancolle is missing and backup data not .kc3data

### ISSUE THREAD

**Issue by fajarmf94** [KC3Kai/KC3Kai#2240]
1. Kancolle Tab is Missing
i'm use Vivaldi Browser 1.12 and Kancolle Tab is missing after i update the browser. it's maybe a bug from the browser because all of the extension is missing from Developer tool tab like Adblock and others. so i will wait new fix from the Vivaldi

2. Backup data can not produce .kc3data
So, because of poin one, i want to backup data in Kc3kai from this Vivaldi 1.12 and want to uninstall and downgrade the version, the problem is when i clicked backup it not produce ***.kc3data but with something strange file name like ccbad511-a4d0-4a9f-8211-a8d15c102a77.zip. why this happen?

So here we are the detail:
Vivaldi Browser 1.12
Windows 8.1
64bit
31.9.9 Kc3kai ver.
i download from Webstore
Customized Kc3kai

![fgngfngf](https://user-images.githubusercontent.com/24492178/30779589-f4daddc2-a11e-11e7-9bf1-9d18a1cd8891.JPG)

**Comment by flixwito** [comment]
Have u extracted the files within the zip? It may contain .kc3data.

**Comment by mikenzb** [comment]
Hi there,
We do not currently support Vivaldi or any of the other chromium based browsers as they tend to do changes which may break the devtools panel which is out of our control.

The best option would be to use Chrome or wait until Vivaldi fixes the issue as there is nothing we can do about it.
