### ISSUE TITLE
Win rate when number of losses is zero

### ISSUE THREAD

**Issue by johnwahlig** [KC3Kai/KC3Kai#2243]
### Versions:
Google Chrome ver 61
KC3 ver 31.9.9
macOS High Sierra 10.13 64-bit

### Steps to reproduce:
When opening the `Strategy` tab, if the number of losses is zero, the win rate is null – should probably make this to be 100% somehow

### Screenshots (if applicable):
<img width="235" alt="screen shot 2017-09-27 at 9 38 37 am" src="https://user-images.githubusercontent.com/27918605/30916590-c6aee1f0-a367-11e7-9aa5-e9354b3ef648.png">

**Comment by sinsinpub** [comment]
show me your data of `localStorage.statistics`?
`null` is not supposed to happen, unless data is not correctly gathered from game api yet.
btw, `rate` is gotten by `win / (win + loss)`%, for your case, will be 100%. the only  `Infinity` case is completely new player whose `win + loss` is zero.

**Comment by mikenzb** [comment]
What sinsinpub meant is go to your strategy room and open up the devtools panel (F12) and go to the console tab and type in `localStorage.statistics` and show us the response,

**Comment by johnwahlig** [comment]
This is what I get back:

<img width="463" alt="screen shot 2017-09-28 at 7 58 40 am" src="https://user-images.githubusercontent.com/27918605/30965280-e05747da-a422-11e7-9736-0c7c3a918610.png">

**Comment by sinsinpub** [comment]
already refined handler, will not get `null` in future.
for now, u can try to go to this screen in game, then check the values again. (because api data of this screen offer more details)
![image](https://user-images.githubusercontent.com/160240/30965555-5ac5268a-a488-11e7-84c7-03e465d6986e.png)
