### ISSUE TITLE
API error with ending rank prediction disabled.

### ISSUE THREAD

**Issue by crandock83** [KC3Kai/KC3Kai#2246]
Just updated to 31.10.0

I've always had ending rank prediction, and ending hp prediction disabled since I don't like getting spoiled. With this latest update I'm getting API error and not getting any battle data if I have ending rank prediction disabled. If i enable ending rank prediction, it works fine and I don't get any errors.

![apierrror](https://user-images.githubusercontent.com/32389615/31014722-c3917d94-a55f-11e7-9492-91613379d982.jpg)

I do have error report, but it's not letting me upload it here even when I put it in zipped format.
[KC3-Error-1506685906.zip](https://github.com/KC3Kai/KC3Kai/files/1344255/KC3-Error-1506685906.zip)

ok it finally let me upload a zip file here, there's also a .txt version below.

**Comment by mikenzb** [comment]
Can you upload the error report for us?

**Comment by crandock83** [comment]
[KC3-Error-1506685906.txt](https://github.com/KC3Kai/KC3Kai/files/1344249/KC3-Error-1506685906.txt)

Here it is changed to .txt file format, it's not letting me upload a .zip here. Will this work fine if you change it back to .json?

**Comment by mikenzb** [comment]
This issue should be fixed in the next update, sorry for the inconvenience.
