### ISSUE TITLE
MVP prediction is not accurate if skilled carrier personnel is equipped on CV

### ISSUE THREAD

**Issue by jimmyzzxhlh** [KC3Kai/KC3Kai#2252]
### Steps to reproduce:
When a CV has 熟練艦載機整備員 equipped, the MVP prediction could be wrong as looks like it doesn't take the equipment into account that the CV is likely the first one to attack the enemy fleet.
### Screenshots (if applicable):
This is the replay:
https://i.imgur.com/UcEJUtU.png
See the second battle in 3-5. Ooi was predicted as the MVP, but since Taihou has 熟練艦載機整備員, she becomes the real MVP instead.

**Comment by sinsinpub** [comment]
please read change logs first.
there is no mvp prediction at all. the transparent mvp liked icon with question mark just gives a reference about who has dealt most damage in other phases besides opening airstrike. it's not related to `熟練艦載機整備員` at all.
