### ISSUE TITLE
not enough 2 expeditions 33 and 34

### ISSUE THREAD

**Issue by stalkerwork** [KC3Kai/KC3Kai#2268]
- Your Chrome version - 61.0.3163.100 (Официальная сборка) (64 бит) (cohort: Stable)
- Your OS and its version - windows10
- 64bit
- Your KC3 Kai version - KC3改 Версия 31.10.3

### Screenshots (if applicable):
![29987-clip-651kb 1](https://user-images.githubusercontent.com/12795161/31386489-9d7fcb2e-adcf-11e7-806e-194aecdcf716.jpg)

not enough 2 expeditions
33 and 34

**Comment by Nya-chan** [comment]
Expeditions 33 and 34 are sortie and boss suport ones, they aren't on the list on purpose since their mechanics vary greatly and they provide no resources. See here for more info: http://kancolle.wikia.com/wiki/Expedition#/Support_Expedition
