### ISSUE TITLE
KC3 crash when click

### ISSUE THREAD

**Issue by YukinoHara** [KC3Kai/KC3Kai#2269]
### I using Chrome ver 61.0.3163.100. Win 8.1 64bit
KC3 ver 31.10.3
Playing via DMM web and API link

**Comment by YukinoHara** [comment]
[[20130077] ErrorLog 2017-10-11.txt](https://github.com/KC3Kai/KC3Kai/files/1376509/20130077.ErrorLog.2017-10-11.txt)

**Comment by Vultren** [comment]
Can you show your console as well?

**Comment by YukinoHara** [comment]
Sr, I can't. 

I go to sleep after post this problem. And when I wake up, that problem dóe not happen anymore...
