### ISSUE TITLE
Wrong rank prediction when with enemy ships with -1 hp

### ISSUE THREAD

**Issue by Tibo442** [KC3Kai/KC3Kai#2284]
Predicted D rank for night while battle ended up as a B (fs sunk)
![wrong prediction](https://i.imgur.com/AWhKz5x.png)
![Parsed nb from logs](https://media.discordapp.net/attachments/205766705463427072/371636577983791105/unknown.png)
![Final/real rank](https://user-images.githubusercontent.com/5676386/31874811-7f13344a-b7cb-11e7-9ea5-b6e363fcdb00.png)

Replay: https://i.imgur.com/cvj6Zes.png
"Parsed night battle node" from log: https://pastebin.com/mY9R0qgY
Rank prediction debug; https://pastebin.com/aJnpuJeC

**Comment by sinsinpub** [comment]
:open: oops, this seems like a 'interesting' special case: ur enemy flagship's 'after hp' happens to be -1 which is considered as empty ship slot :joy:
