### ISSUE TITLE
KC3 panel not loading

### ISSUE THREAD

**Issue by G1N0G4M3** [KC3Kai/KC3Kai#2292]
### Versions:
62.0.3202.62 (Official Build) (64-bit) (cohort: 62_62_win)
Windows 7 - 64 bit
KC3 Kai 31.10.6 (Webstore)

### Steps to reproduce:
1) Open KC3 tab
2) Press F12
3) Click "Kancolle" tab

### Actual behaviour:
No "Waiting for game to load" prompt or any other activity, panel no longer loads.
![1](https://user-images.githubusercontent.com/8816849/32033816-6c8fa9ca-ba41-11e7-8b1d-efd7b4b3d6cc.PNG)
Console and network tabs shows this after multiple attempts:
![2](https://user-images.githubusercontent.com/8816849/32033829-809017a2-ba41-11e7-8669-f0fd5e07cb8f.PNG)
![3](https://user-images.githubusercontent.com/8816849/32033840-965f4788-ba41-11e7-8350-403d2ba1e685.PNG)
Exported error logs are empty. Tried checking the dev tools log tab, shows the following (top entry is the only one that got added after last attempt, others are from previous attempts) :
![4](https://user-images.githubusercontent.com/8816849/32033850-aadb0940-ba41-11e7-921d-8b30b403b871.PNG)

This started happening after the last update. I tried updating Chrome after the update and it didn't solve the problem. Also tried turning off my adblocker. I can still load the game without the info panel, and on my phone.

**Comment by RoyOzz** [comment]
I have some trouble, but if i launch kc without panel i'm get catbombed, also see that error 
![kc3trouble2](https://user-images.githubusercontent.com/33114466/32038602-d7daf88e-ba54-11e7-931f-0105cab6de3f.png)

**Comment by RoyOzz** [comment]
Find exit from my situation, changed the time zone of the computer to mine region(+7 GMT)

**Comment by sinsinpub** [comment]
confirm ur flash (configs of chrome) is enabled and flash player at DMM can be displayed as expected (via disabling kc3 temporarily);
try to configure or disable ur other extensions, such as web fonts, ad blocker, tamper.

**Comment by G1N0G4M3** [comment]
Updated KC3 to latest just now and tried disabling all extensions, Kancolle still runs on DMM. Also tried disabling all extensions except for KC3, closing my antivirus, and adding the --disable-remote-fonts flag to Chrome (is this correct?), problem still happens. What else can I try? And thank you.

**Comment by sinsinpub** [comment]
no idea for now. so ur KC game on DMM runs as expected, but KC3 panel seems not loaded?
i see some buggy things caused by new devtools features, but kc3 should still work on my side (latest 62.0.3202.75 stable channel).

try to open the devtools of kc3 devtools panel (via last menu item on right click context menu), and check if there is something exception at console?
and if there is none, try to reload (also via context menu) and check the Network tab to find any loading issue?

**Comment by G1N0G4M3** [comment]
Yep, only the KC3 panel doesn't work. Even the "start without info panel" option on the main tab works, just without the tools, translations, subs etc.
Console output of the KC3 panel, after opening the KC3 main tab, then the devtool panel:
![1](https://user-images.githubusercontent.com/8816849/32102798-77f13fb2-bb50-11e7-8ff8-77e1dfa5819e.PNG)
![2](https://user-images.githubusercontent.com/8816849/32102800-799f0006-bb50-11e7-809d-07d1daa5daad.PNG)
![3](https://user-images.githubusercontent.com/8816849/32102802-7b7f0060-bb50-11e7-8ba2-1d341fd16b91.PNG)
![4](https://user-images.githubusercontent.com/8816849/32102806-7fe33e6e-bb50-11e7-914e-827ac40b2b09.PNG)
Nothing seems to happen in the network tab when I try again and check:
![5](https://user-images.githubusercontent.com/8816849/32102953-0590e642-bb51-11e7-8958-6d248f3867fd.PNG)
Nothing happens when I reload the frame.

**Comment by sinsinpub** [comment]
guess i get the problem, i'll check the further reason myself.
for ur workaround, don't use `Plain` theme, go settings and change the panel theme to `Natsuiro`.

**Comment by G1N0G4M3** [comment]
KC3 works again after switching themes, thank you so much. ^^
