### ISSUE TITLE
Storing event debuffs

### ISSUE THREAD

**Issue by Tsubakura** [KC3Kai/KC3Kai#2304]
So, an issue I've seen is that an event debuff is never stored anywhere, due to the debuff sound getting triggered once only. As the debuff value is important for figuring out some branching related infos, I actually like to see it stored in some way.

Although I had an idea myself, it requires the KC3SortieManager.map_num to not update if it reaches the port, so that its value could be used when the debuff sound is triggered. I wonder if you guys might have an idea on making this work?

**Comment by sinsinpub** [comment]
np at all. `map.debuffSound` will keep the count of debuff sound being played.
just remind that there are more than 1 api flag to indicate 'boss debuff' used by kc devs in event history, such as: `/battle.api_boss_damaged`

**Comment by Tsubakura** [comment]
Does the debuff also take into account of new routes unlocked? 🤔
