### ISSUE TITLE
[Bug]KC3 API Error

### ISSUE THREAD

**Issue by devildelta** [KC3Kai/KC3Kai#2318]
- Chrome 62
- Win 7 64 Bit
- KC3 31.11.0 from [Chrome Web Store]

### Steps to reproduce:
1-1, not sure can be reproduced in other maps or pvp
### Actual behaviour:
Error message prompted. api_req_sortie/battle is mentioned. 
### Expected behaviour:
Nothing prompted. 
### Error Report (if applicable):
[KC3-Error-1510938584.json.txt](https://github.com/KC3Kai/KC3Kai/files/1483143/KC3-Error-1510938584.json.txt)

Cannot read property '7' of undefined
at window.KC3Node.KC3Node.engage (/library/objects.js:6:5178)
at Object.engageBattle (/library/managers.js:8:5619)
at Object.api_req_sortie/battle (/library/modules/Kcsapi.js:1:21518)
...

**Comment by mikenzb** [comment]
Happens every event, Kancolle devs have changed a lot of backend API data for the event which we will have to fix, we can't guarantee when this will be fixed.

**Comment by mikenzb** [comment]
Should be fixed in 31.11.1 however there maybe more API errors still out there, will close for now.
