### ISSUE TITLE
[Bug] Battle API Error

### ISSUE THREAD

**Issue by Rakshaal** [KC3Kai/KC3Kai#2321]
### Versions: 
Chrome 62.0.3202.94 (Official Build) (64-bit)
Windows 10 Pro Version 1703 OS Build 15063.726
KC3 Kai Version 31.11.0
### Steps to reproduce:
Enter any battle (Sortie or PVP) on any map

### Actual behaviour:
API Error, unable to update ship health in a battle, show battle rating, or drops
Ship health does still update upon returning from battle

### Expected behaviour:
Display drops, battle outcome, update ship health

### Error Report (if applicable):

[KC3-Error-1510946399.txt](https://github.com/KC3Kai/KC3Kai/files/1483561/KC3-Error-1510946399.txt)
[KC3-Error-1510946280.txt](https://github.com/KC3Kai/KC3Kai/files/1483562/KC3-Error-1510946280.txt)

**Comment by reinforce** [comment]
Seems duplicate of #2318
