### ISSUE TITLE
Battle Prediction bugs

### ISSUE THREAD

**Issue by Adrymne** [KC3Kai/KC3Kai#2329]
I'm pretty exhausted right now, so I'm just going to dump my notes. I'll continue working on a solution tomorrow if the issues are still outstanding.

**No attack battle ([api](https://cdn.discordapp.com/attachments/205766705463427072/381367406838415360/KC3-Error-1510995454.json))**
All the properties of `api_hougeki` are being set to `null`. The api data in question is from 5-4I; need to test whether it occurs on day battle nodes as well.

Thankfully this one seems pretty easy to fix, just update [this line](https://github.com/KC3Kai/KC3Kai/blob/d2a436a6b0fc3cf2d100917043b9aebd6d151d9f/src/library/modules/BattlePrediction/phases/Util.js#L41-L43) to `return (array || []).map(value => ({ [propName]: value }));`

**12v6 DB ([api](https://cdn.discordapp.com/attachments/205766705463427072/381379125538979851/KC3-Error-1510998246.json))**

The format for torpedo/raigeki phase has been updated for enemy single fleet, see `api_opening_atack`:

```
{
    api_frai: [-1, -1, -1, -1, -1, -1, -1, -1, 5, -1, -1, 3],
    api_fcl: [0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 1],
    api_fdam: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    api_fydam: [0, 0, 0, 0, 0, 0, 0, 0, 136, 0, 0, 95],
    api_erai: [-1, -1, -1, -1, -1, -1, -1],
    api_ecl: [0, 0, 0, 0, 0, 0, 0],
    api_edam: [0, 0, 0, 95, 0, 136.1, 0],
    api_eydam: [0, 0, 0, 0, 0, 0, 0],
  }
```
The `api_f*` properties (the player ships' attacks) now resembled the format for 12v12 battles, ~~but the `api_e*` properties don't seem to have changed (this is a 6 ship enemy fleet)~~.

Also, raigeki with a (single) 7 ship fleet looks like this:

```
{
  "api_frai":[-1,-1,-1,-1,-1,-1,5],
  "api_fcl":[0,0,0,0,0,0,2],
  "api_fdam":[0,0,0,0,0,0,0],
  "api_fydam":[0,0,0,0,0,0,164],
  "api_erai":[-1,-1,-1,-1,-1,-1,-1],
  "api_ecl":[0,0,0,0,0,0,0],
  "api_edam":[0,0,0,0,0,164,0],
  "api_eydam":[0,0,0,0,0,0,0]
}
```
So whether the data at `api_frai[6]`, `api_fydam[6]`, etc belongs to main or escort fleet depends on whether the player is using a single or combined fleet.

**12v12 NB ([api](https://cdn.discordapp.com/attachments/205766705463427072/381407530343071749/KC3-Error-1511004963.json))**

Similar issue to above; `api_at_list` now factors both fleets for its indices:

```
{
  ...
  api_hougeki: {
    ...
    api_at_list: [6, 7, 8, 9, 10, 11]
    ...
  }
  ...
}
```

Presumably `api_df_list` will as well, which would matter in NB vs enemy escort.

---

I suspect it might be possible to do away with the explicit main/escort fleet division and just use the indices, but that'll be something to look into when I'm not half asleep.

**Comment by Tedster59** [comment]
found an interesting one, prediction doesn't seem to like Air raid nodes with FCF used
![image](https://user-images.githubusercontent.com/21696818/32984351-2b5bd4ee-cc73-11e7-880e-4c5fbf55a632.png)
