### ISSUE TITLE
Kancolle Battle Replayer

### ISSUE THREAD

**Issue by ikhmala** [KC3Kai/KC3Kai#2330]
### Versions: 
 Your Chrome version - 62.0.3202.94 (Official Build) (64-bit)
- Your OS and its version Window 10 64bit
- 32bit or 64bit?
- Your KC3 Kai version -  31.11.1
- Webstore version as in the one from [Chrome Web Store (https://chrome.google.com/webstore/detail/kancolle-command-center-%E6%94%B9/hkgmldnainaglpjngpajnnjfhpdjkohh) 
- Customize DMM website

### Steps to reproduce:
I want to load the latest replay file from the event after downloading it from Battle>Event> the replay file. Then, I open the replayer in new tab, and load the new event replay but it didn't load and show a small red error as in screenshot.

### Actual behaviour:
Replay doesn't start or play.

### Expected behaviour:
Replay should start or play.

### Screenshots (if applicable):
![2017-11-18 21_56_14-kancolle battle replayer](https://user-images.githubusercontent.com/33784508/32981003-3399fbb6-ccac-11e7-83d8-dc954b70d560.png)

### Error Report (if applicable):
nope

**Comment by ethrundr** [comment]
Would you mind to share the replayer image as well for us to test out?
Anyway, tagging @fourinone41

**Comment by Vultren** [comment]
Taking a guess from the screenshot only, it looks like a JSON read error. the data might have been cut off too soon

**Comment by mikenzb** [comment]
Issue probably has been fixed considering this was a E1 sortie, try updating and try to download the same replay again.

**Comment by ikhmala** [comment]
Yup, the replay works as @mikenzb said. I think that had been fixed. Thank you
