### ISSUE TITLE
KC3 API error

### ISSUE THREAD

**Issue by SnipeyLul** [KC3Kai/KC3Kai#2336]
### Versions:
62.0.3202.94 (Official Build) (64-bit) (cohort: Stable)
Windows 10 Ver. 1709
KC3 Kai Version 31.11.1 (Version from Chrome Web Store)
DMM Website Kancolle

### Steps to reproduce:
I went into Event Map E-3 and every single submarine and normal node have the error, the only ones without error are the boss node and the air battle nodes
Edit : Night Battles too

### Actual behaviour:
Got an API error and the battle prediction does not update like the API errors you get before the 31.11.1 update

### Expected behaviour:
Not getting an API error 

### Screenshots (if applicable):
![image](https://user-images.githubusercontent.com/33799598/32988559-d2d74e6e-cd41-11e7-88d0-233198ef7dcf.png)

### Error Report (if applicable):
[KC3-Error-1511076655.json.txt](https://github.com/KC3Kai/KC3Kai/files/1485362/KC3-Error-1511076655.json.txt)

**Comment by mikenzb** [comment]
Combined fleet is not yet supported, our devs are working on it see #2329. There is no timeframe on when the fix will be out.
