### ISSUE TITLE
Scrap error

### ISSUE THREAD

**Issue by Ebira** [KC3Kai/KC3Kai#2338]
- Chrome 59.0.3071.115
- Debian 9 64bit
- KC3 Kai 31.11.1 webstore version.
- "Customize DMM website" play mode.

When I scrap a shipgirl that is present in any of the fleets, I'm getting this: 
![bug](https://user-images.githubusercontent.com/33803690/32990609-a4251258-cd6f-11e7-8ade-36d412127b75.png)

[KC3-Error-1511093534.txt](https://github.com/KC3Kai/KC3Kai/files/1485527/KC3-Error-1511093534.txt)

**Comment by HitomaruKonpaku** [comment]
Known bug.

This will be fix in #2334

**Comment by Ebira** [comment]
Well, sorry if you know about it too, but it's the same thing about modernization.
[KC3-Error-1511095752.txt](https://github.com/KC3Kai/KC3Kai/files/1485542/KC3-Error-1511095752.txt)

**Comment by mikenzb** [comment]
Yes we are aware of that too, this will be fixed in the next update.
