### ISSUE TITLE
Battle error

### ISSUE THREAD

**Issue by YukinoHara** [KC3Kai/KC3Kai#2340]
Please make sure that you have these details on hand when submitting your issue/bug report as this will greatly speed up the issue triage process -- thank you!

- Chrome version - 62.0.3202.94 - 64bit
-  Win 8.1 64bit
-  KC3 Kai version - 31.11.1
- Which game play mode you are using? - DMM web

This happen start when I go 5-3.

Play screen:
![screenshot 2017-11-19 21 16 53](https://user-images.githubusercontent.com/32711309/32991586-b25ef6f8-cd70-11e7-8dc8-d8d090045186.png)

Console:
![screenshot 2017-11-19 21 18 51](https://user-images.githubusercontent.com/32711309/32991588-b88e461e-cd70-11e7-9598-c97559870d9f.png)

Errorlog
[[20130077] ErrorLog 2017-11-19.txt](https://github.com/KC3Kai/KC3Kai/files/1485609/20130077.ErrorLog.2017-11-19.txt)

**Comment by mikenzb** [comment]
Please try this again with 31.11.2 should be fixed however reopen if it isn't.
