### ISSUE TITLE
Duplicate previous encounters

### ISSUE THREAD

**Issue by Drakylon** [KC3Kai/KC3Kai#2345]
Nodes visited before the Fall 2017 event are showing certain enemy compositions twice in the "previous encounters" section of the battle tab. These duplicates also show up in the strategy room's "Encounters" section, and enemy icons in that tab are showing the wrong ships. The "Clear erroneous entries in the Encounters tab" option in bug fixes does not work. Playing on Custom DMM Website option.

### Versions: 
Chrome ver. 62.0.3202.94
KC3Kai ver. 31.11.2

### Steps to reproduce: 
Seems to happen on any node visited before the Fall 2017 event, though I've only checked 4-3.

### Actual behaviour: 
There are duplicate enemy fleets in the "previous encounters" section when routing to nodes previously visited. For example, 4-3 F, D and K show the 5 submarine composition twice when there should only be one.

### Expected behaviour: 
There should not be any duplicate enemy fleets shown.

### Screenshots (if applicable): 
http://prntscr.com/hd54im
Strategy room is also showing incorrect icons: http://prntscr.com/hd5k28

**Comment by devildelta** [comment]
The same problem can still be reproduced in 31.11.5

**Comment by Vultren** [comment]
@Drakylon For the strategy room, looks like you have a combination of the old and new abyssal IDs in your encounters. Did you update you Abyssal DB from the player profile tab yet?

**Comment by mikenzb** [comment]
Issue has been fixed, running `Update Abyssal database IDs following the 2017-04-05 maintenance` followed by `Clear erroneous entries in the Encounters tab` fixed it.
