### ISSUE TITLE
KC only show 6 ships in Strategy Room

### ISSUE THREAD

**Issue by YukinoHara** [KC3Kai/KC3Kai#2359]
It's not a bug.

I think it is a forget.

**Comment by ethrundr** [comment]
Would you like to provide the screenshot?
Although it is obvious where and why, I think it's a good practice to provide screenshot on every report.

**Comment by mikenzb** [comment]
This is an expected bug, I noted something like this might happen in #2332 however I've not been able to confirm since I haven't started the event yet.

Maybe @sinsinpub can work on this when he comes back.

**Comment by ethrundr** [comment]
@mikenzb I'll confirm it later tonight, since I've cleared mine.
I think I'll do a quick 7SS E4 for the details.

**Comment by nonsensed** [comment]
Not really something you can confirm with a screenshot, but yeah the Fleet Manager in the Strategy Room only shows 6 ships if you have 7 ships in Fleet 3 with both Dark and Traditional themes.

**Comment by YukinoHara** [comment]
Screenshot:
![screenshot 2017-11-24 17 01 30](https://user-images.githubusercontent.com/32711309/33205356-3bc591ce-d139-11e7-87bd-7c458771da77.png)
![screenshot 2017-11-24 17 01 51](https://user-images.githubusercontent.com/32711309/33205357-3ca994d2-d139-11e7-8898-7f0c28e97f5c.png)

**Comment by mikenzb** [comment]
Will be fixed in the next release of KC3
