### ISSUE TITLE
Ship Locking Planner sizing and CSS override issues

### ISSUE THREAD

**Issue by transientinfinity** [KC3Kai/KC3Kai#2377]
If you zoom in on the Ship Locking Planner screen, the non-collapsable ship-lock windows compress the ship list to the point that it becomes extremely difficult to navigate. For example, running on a 1080p resolution and zoomed in to 175% (sitting some ~2 meters away from a small screen), after seven rows of shiplocks I'm only able to view eight ships in the ship list, and only about eight or nine lines of the filter menu. Depending on how much my eyes hate me that day, I may even be zoomed in to 200%, in which case I can only see five ships at that point.

I've tried overriding the styles in the KC3K settings page with

`
.tab_locking .scroll_fix {
	height: 100vh !important;
}
`

or even just absolute px values, but they seem to get overridden as soon as the page finishes loading, presumably when --shipListOffsetTop is set. Using the developer console will allow the styles to be overridden, but that has to be done every single time the page is loaded.

I don't really expect this to be addressed in the code, particularly since it wouldn't make much sense to collapse the lock windows given the page's purpose. I am using a legacy resolution on a legacy monitor and at a distance, so I expect the standard response would be either "buy a new monitor" or "sit closer to the screen". But some method of overriding the style without resorting to running KC3K as a local, custom version, that my extremely limited knowledge of CSS is apparently incapable of discovering, would be very helpful, and much appreciated.

- Your Chrome version - 62.0.3202.94 (Official Build) (64-bit) (cohort: Stable)
- Which build you have tried running? webstore version
- Resolution: 1920x1080 on a secondary monitor. 175% zoom.
![ship locking planner](https://user-images.githubusercontent.com/19354299/33359121-077369fe-d49b-11e7-996e-efdaccc2df93.png)

**Comment by DynamicSTOP** [comment]
Hi @transientinfinity !

Just tried to use your css with 175% zoom, looks fine on reload.  Are you sure you posted it into correct box in KC3 settings?
![image](https://user-images.githubusercontent.com/9434504/33361761-919efe28-d4ea-11e7-989a-b2da8b2f6a68.png)

**Comment by transientinfinity** [comment]
Ack. JFC. You're right. I added it to the panel box, because that's where I was previously adding the CSS to apply a blink effect for expedition requirements.

Much obliged. Now if you'll excuse me, I now have to leave yet another social media platform in humiliation.
