### ISSUE TITLE
[Feature Suggestion] Integrate battle log into panel 

### ISSUE THREAD

**Issue by KataLystTB** [KC3Kai/KC3Kai#2382]
Hi guys, I want to make a suggestion that I believe would be useful for some users, and is a feature that is already implemented (albeit currently buggy as a result of the new api) in the replayer in the form of a log showing the outcome of shelling (x hits y for z damage, et cetera).  
My proposal is that there would be a button placed somewhere on the panel UI (theres a few spaces where a small button similar in size to the fleet numbers button could fit, but this location is the easiest to show for the sake of demonstration).  I'm no expert on UI design so the fonts/formatting/general layout leaves much to be desired but essentially the goal was to have the data that is shown in the replay battlelog accessible from the game panel itself during the current sortie/battle in a readable format that hopefully isn't too hard to implement, at least on paper.

![image](https://user-images.githubusercontent.com/28195734/33423695-5078c0f2-d605-11e7-8db9-9fede68d91e0.png)

**Comment by Vultren** [comment]
I say, thank you for reminding me to update the battle log

**Comment by mikenzb** [comment]
Has been added in the 32.4.1 release, you are now able to open the battlelog by clicking on the world id under the Battle tab on the panel.
