### ISSUE TITLE
Taiha Lifebuoy Ring

### ISSUE THREAD

**Issue by DynamicSTOP** [KC3Kai/KC3Kai#2410]
Have an idea that i think worth a discussion. 

There is extensions that blocks requests, like [adblock](https://chrome.google.com/webstore/detail/adblock/gighmmpiobklfepjocnamgkkbiglidom) and there is kc3 extension that can watch over kc3 requests.
Why not to combine that and start blocking all requests in tab when someone proceeds with taiha ship? Generally imitate instant ALT+F4. 

For those who love kuso strats (e.g. 1-6) there might be a **kuso switch** somewhere in devtools panel.

This however means that kc3 will stop _only watching requests_ and players will become more lazy and in worst case of api change they can start saying **IT'S TOTALLY KC3 FAULT THAT I SUNK THAT SHIP!11** 

What do you think?

**Comment by DynamicSTOP** [comment]
Just downvote it if you don't like it. 

It's complicated, it should take into account damecons, godess etc. There are forgiving situation on maps (like right before N node on 1-6). Probably there are also some situations with subs and FS of escort fleet when it shouldn't be triggered. And i am not supporting adding this feature myself for various reasons. It's just an idea.

**Comment by sinsinpub** [comment]
as an option of alert, i think an overlay to prevent player clicking 'Next' button is acceptable, and i mentioned this before at chat.
Blocking network request raises the risk of macro detection / ban, just like no provider loves adblock. 'auto reload page' if checking true at `/next` api call (to prevent next `/battle` api call invoked) might be a possible option.

**Comment by DynamicSTOP** [comment]
Let's bury that.
