### ISSUE TITLE
Quest display bug

### ISSUE THREAD

**Issue by VyroVR** [KC3Kai/KC3Kai#2425]
### Versions:
Browser Opera 49.0 via the Install Chrome extension (come on, this is basically Chrome in different hat).
Win7 x64.
KC3 32.0.5 (webstore build), encountered on prior versions as well.

### Steps to reproduce:
This one is pretty iffy, it generally has something to do with launching the game and _then_ opening the viewer. Sometimes it bugs out, sometimes it doesn't. Haven't been able to reproduce it reliably so far.

### Actual behaviour:
The quest display section bugs out and tries to display quests that aren't there, overflowing the list - namely, the ones that were there when the viewer was last launched together with the game. Toggling the offending quests on/off seems to fix them, except monthlies I've already cleared tend to stick around for a while.

### Expected behaviour:
Six actual quests displayed. Whether the viewer is launched first or not.

### Screenshots (if applicable):
![quest](https://user-images.githubusercontent.com/35082098/34543166-a058488a-f0f0-11e7-9709-9d8ce5636205.png)
The Monthly [W5-1] had been cleared a couple days ago. Yet it is still displayed and overflows the queue.

### Error Report (if applicable):
There is none.

**Comment by mikenzb** [comment]
To clear quests you can click on the corresponding colored box next to the quest or go into the strategy room > flowchart and cancel any quests that have been cleared already.

This bug happens when you clear quests outside of KC3, eg on the android app or another viewer.
