### ISSUE TITLE
Quest Overlay covers in-game tooltip

### ISSUE THREAD

**Issue by dragonjet** [KC3Kai/KC3Kai#243]
*not really a big thing but i think the quest translation blocked whatever appears on that bubble and i cant clear the quest* - [Ryutan Wan Sparky](https://www.facebook.com/photo.php?fbid=946424708749367&set=o.120558182729&type=1)

![11692548_946424708749367_5481228545480590162_n](https://cloud.githubusercontent.com/assets/557312/8664147/66469a7a-2a05-11e5-9a05-4428487c1a20.jpg)

**Comment by bamboo3250** [comment]
Does the game have tooltip? I never knew O.o

**Comment by nicky008** [comment]
I remembered it. I think many quests (like the Tomonaga and Egusa too) have the bubble like it to hint the player about what should be done before finish it.

**Comment by dragonjet** [comment]
As of recent versions, `F10` clears overlays
