### ISSUE TITLE
New notice after maintenance

### ISSUE THREAD

**Issue by YukinoHara** [KC3Kai/KC3Kai#2436]
- Chrome 63.0.3239.132  - 64 bit
- Win 8.1 - 64 bit
- Your KC3 Kai version 32.0.8

Hi. It not a problem with KC3.
But I do not know where to ask. So pls help me, thk.

After maintenance 17 Jan, I was logged out DMM.
And this notice show up.
![6xbkavl](https://user-images.githubusercontent.com/5982780/35107259-5ceceeb6-fcd5-11e7-8cb3-ba10d56d7136.png)

Tried fake IP to login and I played normally. Even when I exit the VPN.
But today it show up again on my PC and the PC at my workplace.

**Comment by mikenzb** [comment]
I edited the issue to remove your email address, as for this popup you should just be able to click on the X and proceed as usual.

**Comment by YukinoHara** [comment]
It okay if I play without VPN?
