### ISSUE TITLE
Naganami k2 related api error

### ISSUE THREAD

**Issue by GcySun** [KC3Kai/KC3Kai#2446]
_### Versions:_
Google Chrome | 63.0.3239.132 (Official Build) (64-bit)
Revision | 2e6edcfee630baa3775f37cb11796b1603a64360-refs/branch-heads/3239@{#709}

macOS High Sierra | 10.13.4 Beta (17E139j) 
(64-bit)

KC3 32.1.0 downloaded from webstore

_### Steps to reproduce:_
Putting Naganami K2 into lineup, opening strat room tabs that loads Naganami k2 data

_### Actual behaviour:_
Putting Naganami K2 into lineup creates api error. 
Akashi tab doesn't load since Naganami k2 introduction.
Shiplist no longer loads after Naganami -> Naganami k2

_### Expected behaviour:_
No api errors

_### Screenshots (if applicable):_
https://imgur.com/a/cuBIF

_### Error Report (if applicable):_
{"title":"KC3改 encountered an error with game data.","message":"It seems there was an error when we tried to handle the game data for api_req_hensei/change. The game API might have changed, so some features may be broken or inaccurate","stack":"TypeError: Cannot read property '1' of undefined\n    at window.KC3Ship.KC3Ship.modernizeLeftStats (chrome-extension://hkgmldnainaglpjngpajnnjfhpdjkohh/library/objects.js:14:12715)\n    at Function.KC3Ship.buildShipTooltip (chrome-extension://hkgmldnainaglpjngpajnnjfhpdjkohh/library/objects.js:15:3810)\n    at window.KC3Ship.KC3Ship.htmlTooltip (chrome-extension://hkgmldnainaglpjngpajnnjfhpdjkohh/library/objects.js:15:3691)\n    at window.KC3NatsuiroShipbox.KC3NatsuiroShipbox.commonElements (chrome-extension://hkgmldnainaglpjngpajnnjfhpdjkohh/pages/devtools/themes/natsuiro/js/Shipbox.js:1:648)\n    at Number.<anonymous> (chrome-extension://hkgmldnainaglpjngpajnnjfhpdjkohh/pages/devtools/themes/natsuiro/natsuiro.js:2:3483)\n    at Function.each (chrome-extension://hkgmldnainaglpjngpajnnjfhpdjkohh/assets/js/global.js:2:2861)\n    at Object.Fleet (chrome-extension://hkgmldnainaglpjngpajnnjfhpdjkohh/pages/devtools/themes/natsuiro/natsuiro.js:2:3282)\n    at chrome-extension://hkgmldnainaglpjngpajnnjfhpdjkohh/pages/devtools/themes/natsuiro/natsuiro.js:1:20176\n    at Function.<anonymous> (chrome-extension://hkgmldnainaglpjngpajnnjfhpdjkohh/library/modules/Network.js:1:788)\n    at Function.each (chrome-extension://hkgmldnainaglpjngpajnnjfhpdjkohh/assets/js/global.js:2:2861)","request":"{\"url\":\"http://203.104.209.23/kcsapi/api_req_hensei/change\",\"headers\":{\"Date\":\"Wed, 31 Jan 2018 22:41:05 GMT\",\"Server\":\"nginx\",\"Connection\":\"keep-alive\",\"X-Powered-By\":\"PHP/5.3.3\",\"Content-Length\":\"55\",\"Content-Type\":\"text/plain\"},\"statusCode\":200}","params":"{\"api_ship_id\":\"4220\",\"api_id\":\"1\",\"api_verno\":\"1\",\"api_ship_idx\":\"0\"}","response":{"api_result":1,"api_result_msg":"成功"},"serverUtc":1517438465000,"kc3Version":"KanColle Command Center 改 32.1.0","dmmPlay":"true","gameTabUrl":"http://www.dmm.com/netgame/social/-/gadgets/=/app_id=854854/","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36","utc":1517438465214}

**Comment by sinsinpub** [comment]
it seems be irrelevant to new version... try this fix (at Strategy Room Profile page) and restart the game.
![image](https://user-images.githubusercontent.com/160240/35681145-6fc89b58-0797-11e8-9a00-05ea091bd18e.png)

**Comment by GcySun** [comment]
After messing around some more, turns out that the ships and equipment is updated only when the panel is open while starting and loading the game. Problem is my game freezes for 3-5 minutes if it does that.
For the last month I've used a no panel start to avoid this, Leading to the above bug with Naganami k2.
Is it normal for the loading with panel process to be freezing for sustained time? Loading without the panel just takes mere seconds

**Comment by GcySun** [comment]
Turning off the logging in network solves the freezing
