### ISSUE TITLE
Unable to mute Kancolle tab by right-clicking 

### ISSUE THREAD

**Issue by BlazinAce** [KC3Kai/KC3Kai#2452]
Please make sure that you have these details on hand when submitting your issue/bug report as this will greatly speed up the issue triage process -- thank you!

- Your Chrome version - via chrome://version/
- Your OS and its version
- 32bit or 64bit?
- Your KC3 Kai version - via chrome://extensions/
- Which build you have tried running? webstore version as in the one from [Chrome Web Store](https://chrome.google.com/webstore/detail/kancolle-command-center-%E6%94%B9/hkgmldnainaglpjngpajnnjfhpdjkohh) or Github variant (better known as developer builds).
- Which game play mode you are using?
- Screenshots which accurately paint the issue(s) you are facing.
- A step by step method that you did to describe how you got to that issue.
- A KC3 Error Report JSON file if you have faced an API error. To upload it, you might append `.txt` as file name extension.

After reading previous part of instruction, you can safely remove them now (including this line). Then fill up following part with your situation.

**Comment by mikenzb** [comment]
In Chrome version 64+ they have changed the way they handle site muting, now the way it works is that it will mute the whole audio output from that entire domain forever, if you would like to get the old option back please find more information [here](https://www.addictivetips.com/web/mute-tabs-in-chrome-64/).

**Comment by sinsinpub** [comment]
this issue should not be defined as kc3's 'bug' since it's caused by the change of Chrome / Chromium.
muting site of `dmm.com` domain should work as expected, but the game is indeed running under `osapi.dmm.com` domain, so i guess google devs might forget to also mute the sub-domains in frame pages 😓
