### ISSUE TITLE
Akashi's ship class is "Repair Ship"?

### ISSUE THREAD

**Issue by redpizza** [KC3Kai/KC3Kai#2455]
In Strategy Room Ship list, Akashi's ship class is shown as "Repair Ship".
It's not "Akashi Class"?

![default](https://user-images.githubusercontent.com/31765780/36107163-8dd5ef74-105c-11e8-8258-3fc10ba66f41.png)

**Comment by sinsinpub** [comment]
i guess 'cause it's `Repair Ships Akashi-Class` on [wikia](http://kancolle.wikia.com/wiki/Category:Repair_Ships)? and jp is `工作艦` not `明石型` 🤔

**Comment by redpizza** [comment]
Yes🤔
I also looked Wikipedia entry but there's no mention about class.
In-game library Akashi's entry not shows ship class.
![2018-02-13 14-19-38 39](https://user-images.githubusercontent.com/31765780/36135704-293248fa-10d0-11e8-89c6-60c56601c4ff.png)

So, no ship class?
and what is `ctype.json` based on?

**Comment by sinsinpub** [comment]
![image](https://user-images.githubusercontent.com/160240/36144443-fe202394-10e8-11e8-8820-72b36ddb10e5.png)
u have definitely missed this part, it's the ship class and `ctype` value in API data.

**Comment by redpizza** [comment]
WHAT?! this "lower part" means ship type
Usually, ship class is shown in "upper part" but Akashi's one is empty.
![2018-02-13 23-46-42 48](https://user-images.githubusercontent.com/31765780/36156258-d3c8877c-1119-11e8-9561-409ea2cb2979.png) ![2018-02-13 23-46-42 48a](https://user-images.githubusercontent.com/31765780/36156265-d857525a-1119-11e8-8f99-ee8b4962f7e1.png)
ex. picture of Amatsukaze's entry（陽炎型 9番艦） and Akashi's

but API says it's `工作艦`, then it's `工作艦`.

**Comment by sinsinpub** [comment]
hm, i think ur question is alright. there is indeed no text value defined as `工作艦` for `ctype` in API data. in-game, `ctype` texts are all images for the upper part, and Akashi is the special one with an empty upper image.
i just recall, the `ctype` with identical value `49` is explained by EO74's api memo as the same text with `stype: 19` which we also use. if we take the fact of empty image into account, her `ctype: 49` might be defined as `` (empty string) 😅

**Comment by redpizza** [comment]
Well, then... Akashi's ship class is undefined... :kissing:
