### ISSUE TITLE
Waiting for game actions...

### ISSUE THREAD

**Issue by kkReborn** [KC3Kai/KC3Kai#2456]
any help?
![z4et7yl7sui-7jv6smlubg](https://user-images.githubusercontent.com/36428547/36128808-9d07e788-1064-11e8-8a9c-7b5c4c52fd6f.png)

**Comment by mikenzb** [comment]
New to Kancolle? Press that red button to continue the setup process.

**Comment by kkReborn** [comment]
i know i've already did everything, anyway thanks
