### ISSUE TITLE
kancolle-db.net decommisioned

### ISSUE THREAD

**Issue by leeyc0** [KC3Kai/KC3Kai#2459]
https://twitter.com/about518/status/958339823852404740

The maintainer announced he already stopped kancolle-db.net, and the site is already unreachable. Some Japanese kancolle tool already removed the kancolle-db integration. So it's time for KC3Kai to remove the integration too.

FYI, kancolle-db already stopped updating since last event...

**Comment by WaltPeter** [comment]
Hi, does anyone know where is the database for kancolle-db.net stored? Or anyone have the backup? I searched through the github of the maintainer, about518, but I can't find something like JSON or CSV dataset...
