### ISSUE TITLE
Graphical glitch involving the game screen

### ISSUE THREAD

**Issue by micotaku** [KC3Kai/KC3Kai#2477]
- Chrome ver 64.0.3282.167 (Official Build) (64-bit)
- Win 8.1 64bit
- KC3 Kai ver 32.2.3

Been having this issue for months and only decided to post it now. The problem is that sometimes (don't know how to reproduce) that the game screen usually screws up really badly in terms of graphics, although i can interact with it (sortie, construct, daily, etc.) just fine. Here is an example:
![1](https://user-images.githubusercontent.com/36749563/36571698-357bf5d4-188c-11e8-9a65-26dec625b34c.PNG)

Do note that this glitch appears to be trying to "update" to the what should be shown but leaves part of it behind like so:
![2](https://user-images.githubusercontent.com/36749563/36571745-74e9072a-188c-11e8-9a88-189b734d57b8.PNG)
![3](https://user-images.githubusercontent.com/36749563/36571746-75d782a6-188c-11e8-80fb-71985ad4fea6.PNG)
The problem does seem to be fixed by closing and opening kc3 kai however (until it shows up again)

Have already tried clearing cache multiple times. Note that this is customize DMM mode

**Comment by DynamicSTOP** [comment]
@micotaku could you try resizing chrome window next time you have such glitches? 

something from here might help #2036 though i am not sure that we've found a stable way to avoid\fix this.

**Comment by micotaku** [comment]
ah yeah sorry for duplicate didnt know there was a previous post about this. thanks for replying, i will try out your suggestions the next time this happens

**Comment by DynamicSTOP** [comment]
To be honest, i think this is very very low priority right now, since everyone is expecting great things from HTML5 that would be released soon after event is ended.
