### ISSUE TITLE
I get a blank screen when trying to launch kc3, Flash is allowed,

### ISSUE THREAD

**Issue by LinkHuhDuh** [KC3Kai/KC3Kai#2488]
### Versions: Chrome - 64.0.3282.186 (Official Build) (64-bit) (cohort: Stable)
Windows 10 64 bit 
kc3 v 32.2.5
Chrome Web Store Version 
Using Customize DMM website
### Steps to reproduce:
1 - open kc3 https://gyazo.com/0b73ab883dc3170adbcaa385b990446b

2- hit f12 https://gyazo.com/e2d665530e50d3537f64939d030f20a0

3 - hit kancolle tab https://gyazo.com/d00c7d2248d59e147142754528d922a9

4- nothing shows
### Screenshots (if applicable):
https://gyazo.com/2a44cad1772f947fa8b83757c006da38
https://gyazo.com/f4f3ed07112455bce8956487ea6b0f2f
https://gyazo.com/c381cb6002423868303b3dc568f72f58

**Comment by mikenzb** [comment]
You seem to have of enabled the device mode, please press this button to disable it and kancolle should now load.
![unknown](https://user-images.githubusercontent.com/5982780/36931073-7ec0444c-1f13-11e8-908c-b79339997817.png)

**Comment by LinkHuhDuh** [comment]
Thank you so much @mikenzb
