### ISSUE TITLE
Erroneous ship sinking message

### ISSUE THREAD

**Issue by TawiTawiTeitoku** [KC3Kai/KC3Kai#2491]
Shimakaze sortied with full HP yet was shown sunk during the F node encounter by the KC3 panel. I immediately refreshed the game and saw Shimakaze was with 9/36 HP and recovered completely by normal docking.
I doubt if that is because of me using fewer than 6 ships in the first fleet, it really freaks me out and I hope that is only a display issue.
Sorry that I was unable to capture the scene at that time, yet I found a weird icon from the problematic sortie as marked with red arrow:

![image](https://user-images.githubusercontent.com/22593053/36949535-2048d850-202d-11e8-8969-bb77a25e2d40.png)

This icon seems appeared nowhere but that particular sortie, and the later sortie can confirm that no ship was actually sunk during the problematic one.

https://youtu.be/-iyc0fMn-wg
Video recording of that sortie was cut before F5, sorry for not being able to capture the entire flow of the error. 

### Versions:
Chrome version - 64.0.3282.186 (64-bit)
OS - Windows 7 Ultimate Service Pack 1
KC3 Kai version - 32.2.5 (webstore version)
Game play mode: dmm website (with overlay)

**Comment by mikenzb** [comment]
Thanks for the report, this was already reported and fixed in the 32.2.6 release.
