### ISSUE TITLE
LBAS Support not showing status on sortie

### ISSUE THREAD

**Issue by happyh0rse** [KC3Kai/KC3Kai#2501]
- Your Chrome version - 64.0.3282.186 (Official Build) (64-bit)
- Your OS and its version - Windows 10, 64bit
- Your KC3 Kai version - 32.3.1
- Which build you have tried running? Chrome Web Store version
- Which game play mode you are using? First mode (Customize DMM Website)

### Screenshots (if applicable): 
![image](https://user-images.githubusercontent.com/13378888/37523929-524daabc-2963-11e8-9349-5d193d3a24fa.png)

**Comment by mikenzb** [comment]
Should be fixed in 32.3.2
