### ISSUE TITLE
Frequent crashes while using KC3 Mac

### ISSUE THREAD

**Issue by UrFriendXD** [KC3Kai/KC3Kai#2509]
### Versions:
Chrome: 65.0.3325.162 (Official Build) (64-bit)
OS: macOS 10.13.3
64bit
KC3 Kai: 32.3.2
Version: Chrome Webstore version
Game mode: Customize DMM website

### Steps to reproduce:
Sortie and switching to other tabs or using other tabs in general while having the kancolle tab open.

### Actual behaviour:
Crashes frequently
Chrome freezes and becomes unresponsive. The sound from chrome still plays this includes YouTube videos and the kancolle tab.

### Expected behaviour:
No crash and all tabs are usable and working.
Only started happening in this version. Everything was working fine with previous versions.

**Comment by mikenzb** [comment]
A few updates later, has this issue fixed itself?

This was happening because of a bug introduced from the chrome side of things.

**Comment by UrFriendXD** [comment]
Yes, the issue has fixed itself. Thanks and keep up the good work!
