### ISSUE TITLE
Computer Freezing Issue

### ISSUE THREAD

**Issue by PoiDesuPoi** [KC3Kai/KC3Kai#2510]
### Versions: chrome://version/65.0.3325.181  Windows 64bit
KC3 Kai version - via chrome://extensions/32.3.2 
 webstore version Game Mode: Dmm custom
### Steps to reproduce:
Open the the Kancolle control pannel
### Actual behaviour:
Freezes computer slowing down all process to a point to be unable to do anything and crashs every other program
### Expected behaviour:
Opens panel, allowing smooth computer process
### Screenshots (if applicable):
Unable
### Error Report (if applicable):
Unable since computer freezing

**Comment by mikenzb** [comment]
Most likely related to #2509 
Reopen if issue still occurs to this day.
