### ISSUE TITLE
Suggestion: display ship levelling goals using ship ID instead of generic name

### ISSUE THREAD

**Issue by Accelyte** [KC3Kai/KC3Kai#2511]
Currently the levelling goals tab does not show levels for duplicate ships, so for example, you can't set goals for multiple Mikumas. I think it would be helpful to be able to track the levels of every specific ship.

**Comment by Tibo442** [comment]
Leveling tab only shows locked ships, when you lock your Mikuma's they'll be added to the leveling page

![21-29-11](https://user-images.githubusercontent.com/5676386/37735630-ef5a265c-2d4e-11e8-9cca-02005443be10.png)
![21-29-17](https://user-images.githubusercontent.com/5676386/37735624-ebe386e4-2d4e-11e8-900d-20ecb0789430.png)

**Comment by sinsinpub** [comment]
* yep, it shows dupe ships as long as locked
* it shows ship instance ID at tooltip, try to hover on their faces

**Comment by Accelyte** [comment]
That's interesting, because I currently have 4 mikumas and only 1 mikuma kai is showing in my levelling tab.
![chrome_2018-03-23_10-05-43](https://user-images.githubusercontent.com/21363469/37823593-d4760728-2e81-11e8-9df6-cef37c8bf7fc.png)
![chrome_2018-03-23_10-06-09](https://user-images.githubusercontent.com/21363469/37823603-da7a8f04-2e81-11e8-8cd5-f46bee69de47.png)

**Comment by sorewachigauyo** [comment]
Well, so that the non-permanent members of your fleet won't clutter the leveling screen and you can find the semi or permanent additions to your fleet

**Comment by sinsinpub** [comment]
in case almost everybody not read `Help Topics` (FAQ)
![image](https://user-images.githubusercontent.com/160240/37863868-9c9d76ae-2fa0-11e8-9f93-5958c6d7dd56.png)

**Comment by Accelyte** [comment]
Right, I see. Thanks.
