### ISSUE TITLE
Adobe Flash Player is blocked

### ISSUE THREAD

**Issue by moemoemudkip** [KC3Kai/KC3Kai#2512]
### Versions: Chrome: 64.0.3282.186 OS: Windows 10 64-bit version 1709
KC3 Kai version 32.3.2, webstore

### Screenshots (if applicable): https://i.imgur.com/PlIgaEV.png

chrome-extension://hkgmldnainaglpjngpajnnjfhpdjkohh/ is an exception in Flash's security settings.

**Comment by sinsinpub** [comment]
did you add it (`chrome-extension://hkgmldnainaglpjngpajnnjfhpdjkohh/`) to here: `chrome://settings/content/flash`?

**Comment by moemoemudkip** [comment]
That fixed it
