### ISSUE TITLE
Region's (RU) subtitles replace English one

### ISSUE THREAD

**Issue by soul950** [KC3Kai/KC3Kai#2525]
Please make sure that you have these details on hand when submitting your issue/bug report as this will greatly speed up the issue triage process -- thank you!

- Your Chrome version - via chrome://version/
- Your OS and its version
- 32bit or 64bit?
- Your KC3 Kai version - via chrome://extensions/
- Which build you have tried running? webstore version as in the one from [Chrome Web Store](https://chrome.google.com/webstore/detail/kancolle-command-center-%E6%94%B9/hkgmldnainaglpjngpajnnjfhpdjkohh) or Github variant (better known as developer builds).
- Which game play mode you are using?
- Screenshots which accurately paint the issue(s) you are facing.
- A step by step method that you did to describe how you got to that issue.
- A KC3 Error Report JSON file if you have faced an API error. To upload it, you might append `.txt` as file name extension.

After reading previous part of instruction, you can safely remove them now (including this line). Then fill up following part with your situation.

**Comment by soul950** [comment]
Everything is set to English (Global), still Ru subtitles replace English ones after 0.1 second or so.

**Comment by DynamicSTOP** [comment]
Check top bar of your first screenshot. 
![image](https://user-images.githubusercontent.com/9434504/38085251-7e97fe2a-3358-11e8-96e6-48f7e5d4fe82.png)
Chrome automatically translated from eng to russian. Turn that off and you will have eng quests.

**Comment by soul950** [comment]
...Yeah, that was it. As usual, i'm just being an idoit. *thnx, mate*

**Comment by Agc0de6** [comment]
@soul950 Раз так, тогда прошу помощи. Я один за всем не успеваю, так что лишние руки не помешают точно.

**Comment by DynamicSTOP** [comment]
А какой помощи то? Помогать переводить?

**Comment by Agc0de6** [comment]
@DynamicSTOP Конечно. Работы ещё много, а рук не хватает.

**Comment by DynamicSTOP** [comment]
@Agc0de6 посмотрел я на перевод :rofl: Я могу только с eng->ru помочь, с японским у меня всё совсем грустно.   

Какието особые правила по части спряжений или чего нибудь подобного есть?

**Comment by Agc0de6** [comment]
@DynamicSTOP Ну, имена по Хэпбёрну. Так, в принципе, более никаких требований более нет, лишь бы покультурней было и по-русски)))
Иностранцев с их "вставками" пока не трогаем, потом решим, когда дойдём.
