### ISSUE TITLE
Musashi Kai ni random derping.

### ISSUE THREAD

**Issue by Jasper1224** [KC3Kai/KC3Kai#2527]
- Chrome version - 65.0.3325.181
- Windows 10 build 16299 64 bit
- KC3 Kai version 32.4.2
- Which build you have tried running? Chrome Web store
- Which game play mode you are using? not sure what is meant here.
- Screenshots which accurately paint the issue(s) you are facing.

https://imgur.com/a/hGyvh

**Comment by Tsubakura** [comment]
April Fools

**Comment by Jasper1224** [comment]
So it is April Fools. Why specifically Musashi? Or are there others.

**Comment by Tsubakura** [comment]
If the joke is about Kiyoshimo, who else is a better fit than Musashi? :)
