### ISSUE TITLE
unable to use CSV export?

### ISSUE THREAD

**Issue by redpizza** [KC3Kai/KC3Kai#2534]
Is Profile data export broken?
those data export show Chrome's "This site can't be reached" page.

![g](https://user-images.githubusercontent.com/31765780/38451916-07719388-3a74-11e8-8eec-c9035dede186.png)

![default](https://user-images.githubusercontent.com/31765780/38451919-0fc3015c-3a74-11e8-82b1-7be5a4c47060.png)

- Chrome version - 65.0.3325.181 (Official Build) （64 ビット） (cohort: Stable)
- OS - Windows 10 version 1709 (build 16299.309) 64bit
- KC3 Kai version - 32.4.3
- this issue occurs on both of Webstore version and Dev build version

**Comment by sinsinpub** [comment]
ye, there is a known issue for chrome 65: https://github.com/eligrey/FileSaver.js/issues/408
