### ISSUE TITLE
Shipgirl in strat room -  leveling wrong level

### ISSUE THREAD

**Issue by touma242** [KC3Kai/KC3Kai#2538]
- Your Chrome version - via chrome://version/

65.0.3325.181 
- Your OS and its version

win 10 64 bit
- 32bit or 64bit?

64 bit
- Your KC3 Kai version - via chrome://extensions/

32.4.4
- Which build you have tried running? webstore version as in the one from [Chrome Web Store]

chrome webstore

### Versions:
last version had no problem

## Kagerouis shows as level 16 but I kai'd her yesterday and after the update this morning she does not show up as 27.
Equips and upgrade stats also don't show.
This is in all panels, leveling, ship list etc.
Also refreshed and restarted browser, cleared cache etc.

![schermopname 5](https://user-images.githubusercontent.com/38242334/38543822-f17a3f9c-3ca5-11e8-9aa6-d9ed3a9f5be9.png)
![schermopname 7](https://user-images.githubusercontent.com/38242334/38544057-a5dc322e-3ca6-11e8-9486-75ffd3ec61a2.png)

**Comment by mikenzb** [comment]
Not sure if it would help but you could give it a try anyways.

Go into the strategy room and under the profile tab run the following bug fixes:
* Rebuild ship remodel information caches
* Clear bugged Ships & Equipment caches

Make sure the game is closed when you run these patches

**Comment by touma242** [comment]
I have tried that but it didn't help. The problem still remains.

**Comment by sinsinpub** [comment]
...how many `Kagerou` u have owned? it seems be a simple thing. u r looking for the unlocked `Kagerou Kai (Lv 27)` at leveling page, but found a locked duplicated `Kagerou (Lv 16)`

Leveling page is designed for tracking exp & level those shipgirls whom u want to keep (heart-locked). unlocked ones are not shown intentionally, see page `Help Topics`, or see also #2511
btw, to identify dupe ships by in-game internal instance IDs, u can find them by hovering on ship face, or from Ship List page.

**Comment by touma242** [comment]
Thanks for helping, it seems something went wrong with custom fleets on the andoird app where I registered a non heart locked kagerou into it .
And when I went to the pc I had also a lvl 16 kagerou show up in the fleet list which show only heart locked ships and found it weird after a while nothing changed. 
Sorry for all the confusion the problem was on my end :S
