### ISSUE TITLE
Blurred Subtitle on the library

### ISSUE THREAD

**Issue by S0pina** [KC3Kai/KC3Kai#2546]
### Versions: Version 66.0.3359.117 (64 bits)
Windows 10 (64 bits)
KC3 ver. 32.4.5

### Steps to reproduce:

Keeping the mouse on the game panel while in the "shipgirl library"

### Actual behaviour:

The subtitles sometimes become blurry, and switching to another panel if a blurry subtitle is still on the screen blurs the next subtitle.

### Expected behaviour:

Non-blurry Subtitles

Also,  i think there is a missing word in Shikinami's quote when she enters damaged/heavily damaged state, since it reads "Hmm, I don't that I'll be worn out just like that[...]"

**Comment by sinsinpub** [comment]
can not understand ur description... which 'panel' (u mean chrome tab?) u r talking about? what can 'burred subtitle' mean? offer some screenshots?
or did u know this feature? 
![image](https://user-images.githubusercontent.com/160240/39091341-cedaa958-4624-11e8-8706-02f717067ca0.png)

**Comment by S0pina** [comment]
Oh I didn't know that it was a feature, I tried another display type and it fix the "problem".
Thank you, and sorry for my bad english and for being an idiot.
