### ISSUE TITLE
KC3 not detecting fleets (API changed or features broken/innacurate)

### ISSUE THREAD

**Issue by HarutaGinnosuke** [KC3Kai/KC3Kai#2547]
[KC3-Error-1524366239.json.txt](https://github.com/KC3Kai/KC3Kai/files/1935179/KC3-Error-1524366239.json.txt)
![capture4-22-2018-12 13 19 pm](https://user-images.githubusercontent.com/31546831/39091005-970714a6-4626-11e8-82ff-a211d4ea202c.jpg)
![capture4-22-2018-12 13 22 pm](https://user-images.githubusercontent.com/31546831/39091006-97274460-4626-11e8-9ba2-f8c939d7c3b8.jpg)

- Your Chrome version - 65.0.3325.181
- Win10 1709
- 64bit?
- Your KC3 Kai version - 32.4.5
- Webstore build
- DMM direct (No cookie, I'm in Japan)
- Screenshots which accurately paint the issue(s) you are facing.
- Loading the game and moving across any menu does this. 

KC3 doesn't detect fleet 1 and 2, whilst 3 and 4 shows up properly. Strategy room also becomes unresponsive when I switch to the Ship List tab.

I've been getting this error ever since I launched the game through DMM on my laptop. I was previously playing the game on my desktop back home, but since I just moved to another country, I've yet to gather enough parts to assemble a new desktop. 

Could it be a sync issue? I've already deleted my cache and cookies and it's still reproducing the same errors. If it is, since I'm going to eventually move to a permanent desktop, what should I do to prevent this issue from surfacing again?

**Comment by sinsinpub** [comment]
try `Clear bugged Ships & Equipment caches` link at Strategy Room Profile page

**Comment by HarutaGinnosuke** [comment]
That fixed the issue, thanks!
