### ISSUE TITLE
Strategy Room Ship List Filter Heartlock counter

### ISSUE THREAD

**Issue by dragonjet** [KC3Kai/KC3Kai#258]
_Hi, would you consider adding a separate counter for ships that aren't locked, I'd find it useful for modernisation etc._ - [Mamoo0692](http://kancolle.wikia.com/wiki/User_blog_comment:Dragonjet/KC3%E6%94%B9/@comment-Mamoo0692-20150714223029?permalink=283072#comm-283072)

**Comment by McDohl** [comment]
https://github.com/KC3Kai/KC3Kai/pull/920

**Comment by dragonjet** [comment]
I think this guy means the number of non-locked ships in the devtools panel itself

**Comment by McDohl** [comment]
I thought with the new heartlock filter it shows ships that not locked?

**Comment by McDohl** [comment]
![image](https://cloud.githubusercontent.com/assets/13024936/10862408/eb6c5158-7fd8-11e5-88e2-fe58c85ce499.png)

**Comment by dragonjet** [comment]
when it was reported I envisioned it going here

![ss 2015-10-31 at 03 32 15](https://cloud.githubusercontent.com/assets/557312/10862482/a10ea136-7fe4-11e5-8a85-48d3e0ad0ef2.jpg)

so when he sees oh I got two extra ships now, I can do modernization now

**Comment by Javran** [comment]
just spotted this issue and I happened to have done #1686 which is what he needs. closing.
