### ISSUE TITLE
[Bug] Ise KaiNi firepower has a wrong when equip 41cm Triple Gun Mount Kai Ni

### ISSUE THREAD

**Issue by yeshasuicide** [KC3Kai/KC3Kai#2593]
When Ise KaiNi equip 41cmKaiNi*2, base FP shows 90,but actually it should be 88
![qq 20180707153240](https://user-images.githubusercontent.com/17948412/42408249-2a89ab6a-81fc-11e8-9f67-b46bc5d467c6.png)
![qq 20180707153258](https://user-images.githubusercontent.com/17948412/42408250-2b442580-81fc-11e8-9243-211af4bdc259.png)
![qq 20180707153401](https://user-images.githubusercontent.com/17948412/42408251-2bce8716-81fc-11e8-99d1-f69fe7fdcd8f.png)
![qq 20180707153409](https://user-images.githubusercontent.com/17948412/42408252-2c0d5f18-81fc-11e8-8035-08058e2cc440.png)

**Comment by sinsinpub** [comment]
thank you for ur report, already fixed in commit a242113
it helps us to confirm what will happen when equip multiple 41cm K2
