### ISSUE TITLE
[Feature Request] Ship sunk protection. Show alert or overlay on "Continue/Retreat" screen, when fleet has critical damaged ship.

### ISSUE THREAD

**Issue by 0x384c0** [KC3Kai/KC3Kai#2595]
When fleet has **critical damaged ship** and player  **on "Continue/Retreat" screen**
then **show some overlay**, that **prevents** accidentally continuing of sortie.

Also this feature would be great at "start sortie" screen.

**Comment by mikenzb** [comment]
Was talked about earlier in this year as can be seen in #2410 

We decided it may not be worth implementing however if KC3 needs to be redesigned for the HTML5 changes it maybe worth considering again.

**Comment by 0x384c0** [comment]
Got it. Will wait until HTML5 version of game will be released.

**Comment by DynamicSTOP** [comment]
ref 2819
