### ISSUE TITLE
[Quarterly Ranking Points 2][5-1] s-rank display incorrectly

### ISSUE THREAD

**Issue by ztjal** [KC3Kai/KC3Kai#2601]
![001](https://user-images.githubusercontent.com/6552290/42935488-554133da-8b7c-11e8-8d75-c85e9b5f323e.jpg)
![002](https://user-images.githubusercontent.com/6552290/42935489-55780572-8b7c-11e8-9e49-72622f28b9e7.JPG)

**Comment by sinsinpub** [comment]
it's not supposed to happen if your 5-3, 5-4 parts are correctly tracked. maybe it's too late on kc3 updated to track it when you finish 5-1 in-game? 🤔

**Comment by ztjal** [comment]
no, i finish 5-1 first, mission show 50%, kc3 is 0 (0/1 5-1).
finish 5-4 later, mission show 80%, kc3 is 1 (1/1 5-4).
last finish 5-3, kc3 is 2 (1/1 5-3).

**Comment by ztjal** [comment]
yes, 5-1 i use 天龍改二，5-3&4 without her.
