### ISSUE TITLE
Custom Alert Sounds and Custom Backgrounds

### ISSUE THREAD

**Issue by MarshaMay** [KC3Kai/KC3Kai#2609]
### Screenshots (if applicable):
[![screenshot 1](https://user-images.githubusercontent.com/42124702/43691625-02b9bb54-98d4-11e8-9a9b-aa4740b43519.png)](url)
[![screenshot 2](https://user-images.githubusercontent.com/42124702/43691593-95e27e6c-98d3-11e8-8d1f-c94138b5b1be.png)](url)
[![screenshot 3](https://user-images.githubusercontent.com/42124702/43691601-a5fd7db0-98d3-11e8-9b94-db28cb0bd60e.png)](url)

**Comment by sorewachigauyo** [comment]
Which website have you been using to host your sound lines and background image? 

For custom sound lines, you can link them from wikia (or a third party hosting site) like https://vignette.wikia.nocookie.net/kancolle/images/2/2f/Murasame-Docking_Complete.ogg/revision/latest?cb=20150621090604 

For background image, you can use a website like imgur to host your image and link it from there.

**Comment by MarshaMay** [comment]
Heh, funny, I haven't used a website for the background images
before...sorry I'm a noob... and for the sound I got them from the Kancolle
Wikia at http://kancolle.wikia.com/wiki/Kancolle_Wiki. Also thatnks for the
imgur website, I hope it works as I'm about to test it out.

**Comment by MarshaMay** [comment]
Nevermind. The imgur links didn't work...

**Comment by sorewachigauyo** [comment]
For imgur, have you tried using the direct link?  
![image](https://user-images.githubusercontent.com/26541502/43815843-381c1580-9b04-11e8-87a1-ee1060bed5ea.png)

As for the wikia links, you can get them by right-clicking the little play icon and clicking copy link address 
![image](https://user-images.githubusercontent.com/26541502/43815980-18cf37e2-9b05-11e8-9124-ccbbe63c95b2.png)

I can't find the Yuudachi link, but I think the rest are what you are referring to.
https://vignette.wikia.nocookie.net/kancolle/images/2/27/Shiratsuyu-Returning_From_Sortie.ogg/revision/latest?cb=20150305015436

https://vignette.wikia.nocookie.net/kancolle/images/e/e3/Unryuu-Construction.ogg/revision/latest?cb=20150310062541
