### ISSUE TITLE
After the change server event,my history log is gone.

### ISSUE THREAD

**Issue by minelin** [KC3Kai/KC3Kai#2612]
After KC event of player change server,I have changed other server,but my KC3 history battles&expeditions logs is gone,plz tell me how can I recover these history logs?thank you!

- Your Chrome version - via chrome://version/ 
 68.0.3440.84
- Your OS and its version
Win7 pro
- 32bit or 64bit?
64bit
- Your KC3 Kai version - via chrome://extensions/
32.7.2

**Comment by mikenzb** [comment]
Please read the [32.7.1 patch notes](https://github.com/KC3Kai/KC3Kai/pull/2608) and run the implemented fix included in that update to fix your issue.
