### ISSUE TITLE
chrome 68.0.3440.106, win messages not auto clears up

### ISSUE THREAD

**Issue by ztjal** [KC3Kai/KC3Kai#2613]
when i update chrome 68.0.3440.106, win10(1803) messages not auto clears up.
the previous version of the chrome is no problem.

![default](https://user-images.githubusercontent.com/6552290/43888669-cf327cb6-9bf4-11e8-89ef-9f99b9466984.jpg)

**Comment by sinsinpub** [comment]
obviously it's chromium and win10's feature, not kc3's business.

to disable windows native (action center) notifications, try to disable this flag: `chrome://flags/#enable-native-notifications`

**Comment by ztjal** [comment]
thanks, that's solve. i need to manually turn off the chrome action center notification in Notifications & Actions.
