### ISSUE TITLE
In quest required ships page, add marks for already completed quests (feature request)

### ISSUE THREAD

**Issue by insulsa** [KC3Kai/KC3Kai#2615]
Now available quests have marks on them (#2221), while quests which have been completed before and quests which are not yet revealed don't have marks on them. Is it possible to further differentiate completed quests from the remaining, or offer an option to hide completed quests?

**Comment by sinsinpub** [comment]
it's possible to mark them different, but the disclaimer is: kc3 not designed to keep tracking your completed quests in a database. there are completed quests cached in your profile storage when you play via kc3, but there are kinds of reasons to lose them, for example: clicking the reset everything button in quest flowchart will clear the cache.
ofc if you completed quests without this kc3 activated (eg: played on other pc/android), there is no way to cache them at all.

so don't depend on those marks, they are just for your reference for now.

**Comment by insulsa** [comment]
What about algorithm deducing completed quests from current quests? If any subsequent quest B is available, while some quest A unlocks B, then we know A is completed. And if quest C is not available, while all prerequisite to quest C are marked as completed, then we know C is completed, too.
