### ISSUE TITLE
Old events and maps sortie history disappears after html implementation

### ISSUE THREAD

**Issue by Beregondz** [KC3Kai/KC3Kai#2621]
As soon as I complete any sortie in new maps the whole history disappear, only the new one shows up; I tried reloading a backup, everything is here until I sortie again.
Even if maps are completely different I'd like to keep records of the past and related replays, hope this can be fixed

Chrome Version 68.0.3440.106
Windows 10 home 64bit
KC3 Kai version 32.8.0

**Comment by sorewachigauyo** [comment]
Hello, did you recently succeed in transferring servers? If so, please follow the instructions on https://github.com/KC3Kai/KC3Kai/pull/2608 to fix the issue
