### ISSUE TITLE
Kanmusu Subtitles Inconsistant

### ISSUE THREAD

**Issue by GinWoozy** [KC3Kai/KC3Kai#2630]
### Versions:
Chrome Version: 68.0.3440.106
Windows 7 Home Premium, 64 bit.

### Actual behaviour:
-After a line is played once, subsequent subtitles for that/those lines do not appear. (Battle lines, poking secretary, etc) Sometime later, they begin to appear sporadically. 

### Expected behaviour:

-Subtitles should play every time a line is uttered.

**Comment by mikenzb** [comment]
Seems like a fix has been deployed from the KC devs side so this issue will now be closed.
