### ISSUE TITLE
World tabs in sortie history page gets pushed offscreen after selecting World 6

### ISSUE THREAD

**Issue by somrandus** [KC3Kai/KC3Kai#2631]
### Versions:
33.01

### Steps to reproduce:
1. Open Strategy Room.
2. Open the Sortie History page by clicking on Maps tab under Battles on left sidebar.
3. Click on World 6 tab on top.

### Actual behaviour:
A blank space appears after the World tabs, pushing All Runs and World 1 tabs offscreen, only leaving a small part of World 2 tab onscreen. Clicking on World 2 tab does not scroll the earlier tabs back into view.

### Expected behaviour:
The World tabs stay at their original positions when selecting World tabs.

### Screenshots (if applicable):
![2018-08-20_002431](https://user-images.githubusercontent.com/4956956/44310383-f368da80-a40f-11e8-991d-ce8f879ac6af.png)
![2018-08-20_002529](https://user-images.githubusercontent.com/4956956/44310382-f2d04400-a40f-11e8-9043-2a7318f940e4.png)

### Error Report (if applicable):
None.

**Comment by mikenzb** [comment]
Known bug will be fixed in the next release
