### ISSUE TITLE
Graf Zeppelin blueprint bug

### ISSUE THREAD

**Issue by atikabubu** [KC3Kai/KC3Kai#2648]
![image](https://user-images.githubusercontent.com/4551435/44959751-17d6b380-aef4-11e8-81e5-a8f60dacfe0b.png)

As seen in the image, the Ship Library shows Graf needing a BP to go Kai, when she doesn't.

**Comment by mikenzb** [comment]
Fixed in Release 33.1.4 #2650 
However do note it does now show the BP icon when similar items are required, when mousing over the BP icon it will show `Materials like blueprint required`

For example Shiratsuyu Kai Ni will still show this icon even though she just needs an action report.
