### ISSUE TITLE
Interface issues with KC3Kai and overlay prompts

### ISSUE THREAD

**Issue by JenkaTamar** [KC3Kai/KC3Kai#2665]
Kc3kai version is 33.2.5. Chrome Version 69.0.3497.92

Since yesterday I've been having a number of issues with the interface while ruining KC3Kai. Certain buttons don't respond to clicks or Movable interfaces like the LBAS screen on the LBAS plotting page won't move to expose nodes under the UI. If i run the game straight from DMM without KC3Kai then everything works normally, it's only when I launch from the KanColle Command center and then try to use the game that I run into these issues. Amusingly in regards to which buttons don't work in the main UI it can change from refresh to refresh. though it does seem to be related to follow on pages. IE I have 7 Fleet presets but if I click on preset 6 or 7 nothing happens. I can click on 1-5 and they properly change ships. IF I try to assign LBAS. I can choose any node not concealed by the LBAS UI element and can click the button to accept the strikes but the UI Itself won't move. And Most annoyingly The resupply button won't work from the fleet page.

Additional testing showed that there was a ship missing from preset 7 and without the developer window for KC3kai open it displayed a warning message with an additional button to click. That UI Element did not appear with the KC3Kai window open. I did not refresh the page just closed the KC3Kai developer window to restore function.

 Is there a way to back rev Kc3Kai?  I did not have these issues with the previous version that I can remember.

**Comment by sinsinpub** [comment]
good to know ur issue resolved... the fact is: both kc game and kc3 are not designed for touch device 😂
