### ISSUE TITLE
Auto adjust cannot fit with game screen size after change the game screen ratio

### ISSUE THREAD

**Issue by qqTaiga** [KC3Kai/KC3Kai#2675]
- Chrome version -  69.0.3497.100 (Official Build) (64-bit)
- KC3 Kai version - 33.2.10
- webstore version
- iFrame

After adjust the game screen ratio to 67%, the auto adjust still adjust the window according to the original game screen size.

*If use ctrl + scroll adjust the ratio will fit but the strategy room font will hard to see
![y tl88 pxm l0 z8 e k](https://user-images.githubusercontent.com/43560744/45990434-39722780-c0bb-11e8-9182-d713dcea6786.png)

**Comment by mikenzb** [comment]
Will be fixed in the 33.3.0 release.
