### ISSUE TITLE
Request translation repo access

### ISSUE THREAD

**Issue by ShinHKPDes** [KC3Kai/KC3Kai#2703]
https://github.com/KC3Kai/kc3-translations/pull/667

Well... One digit off for the trips.

Anyways, applying for direct write-access permissions for translation.

**Comment by ShinHKPDes** [comment]
Labels: Others and Translations

Can't label so there we go

**Comment by mikenzb** [comment]
Invite sent

**Comment by ShinHKPDes** [comment]
Thanks
