### ISSUE TITLE
Ledger fails to record resources spent after using "Fix bad data in the Resources, Consumables and Ledger tabs"

### ISSUE THREAD

**Issue by dice4321** [KC3Kai/KC3Kai#2706]
- Chrome version - 70.0.3538.77 (Official Build) (64-bit) (cohort: Stable)
- Windows 10
- 64bit
- Installed Version : 33.3.7 

Records battles perfectly, but doesn't show any resources spent/gained. I've tried to fix the ledger and keep my data by delete/reload/refresh the extension, exporting data, manually move the localStorage and IndexedDB, change from chrome to chromium with no results to fix the ledger. 
![ledger](https://user-images.githubusercontent.com/20022859/48051397-d5cb2780-e159-11e8-95be-827be9bcd7be.png)

![battles](https://user-images.githubusercontent.com/20022859/48051594-699cf380-e15a-11e8-9060-2cde47fb821b.png)

![fix bug](https://user-images.githubusercontent.com/20022859/48051567-5427c980-e15a-11e8-946b-8a1e134c5e20.png)

Is there a way to just delete the Resources, Consumables and Ledger data without touching the battle/events history?

**Comment by sinsinpub** [comment]
to clear all data of ledger without touching others, execute this under console of a Strategy Room page:
```
KC3Database.con.navaloverall.clear()
```

Alternatively, u can do it via devtools `Application` tab (of any Strategy Room page), expand `IndexedDB`, find table `navaloverall`, click the `Clear object store` button next to `Refresh` button:
![image](https://user-images.githubusercontent.com/160240/48109221-81bb6280-e281-11e8-82ab-b64d374a0d29.png)

**Comment by dice4321** [comment]
It worked! Thank you for your guidance.
