### ISSUE TITLE
Ships dissappear from the compare tab

### ISSUE THREAD

**Issue by kestein** [KC3Kai/KC3Kai#2714]
### Versions:
- _Chrome Version:_ 70.0.3538.110 (Official Build) (64-bit) (cohort: 70_110_Win)
- _Your OS and its version:_ 64 bit Windows 10 Pro Version 1803
- _Your KC3 Kai version_: 33.4.0
- _Which build you have tried running?_ webstore version
- _Which game play mode you are using?_ Strategy Room
### Steps to reproduce:
- Go to Strategy Room -> Compare tab
- Search for a ship not in the inital 4 (I did Akatsuki Kai Ni)
- Click on the ship
- Go to another tab
- Go back to the Compare tab
- Search for the previous ship again
### Actual behaviour:
- The ship does not appear in the suggested ships bar
### Expected behaviour:
- The ship should appear in the suggested ships bar
### Screenshots (if applicable):
![step_1](https://user-images.githubusercontent.com/1591568/48854757-83982200-ed67-11e8-95f5-0f72b183fa3b.PNG)
![step_2](https://user-images.githubusercontent.com/1591568/48854790-9b6fa600-ed67-11e8-8897-eb0b3b27dbc9.PNG)
### Error Report (if applicable):
N/A

The ships that have been selected persist among exiting the tab, however they are not redrawn when reentering the tab. From the example before adding another ship to compare brought up the missing ship in the "compare_list" container. When you remove the ship from that container then it will show up in searches again. I was going to take a crack at fixing it unless this tab is already undergoing work by someone else.

**Comment by sorewachigauyo** [comment]
Fixed in https://github.com/KC3Kai/KC3Kai/pull/2715
