### ISSUE TITLE
api_req_kaisou/slot_exchange_index error

### ISSUE THREAD

**Issue by ztjal** [KC3Kai/KC3Kai#2751]
KC3 : 33.6.4
------------------------------------------
when i change fighter, show this.
[KC3-Error-1548165841.zip](https://github.com/KC3Kai/KC3Kai/files/2783066/KC3-Error-1548165841.zip)

**Comment by sorewachigauyo** [comment]
Noted, will be fixed in the next release

**Comment by mikenzb** [comment]
Fixed in 33.7.0
