### ISSUE TITLE
[Bug]Error occurs when exchange equips btw items

### ISSUE THREAD

**Issue by yeshasuicide** [KC3Kai/KC3Kai#2752]
- Chrome version 70.0.3538.67 (正式版本) （64 位） (cohort: Stable Installs Only)
- OS Windows
- 64bit
- KC3 Kai version 33.6.4
- 
- 
![qq 20190123014841](https://user-images.githubusercontent.com/17948412/51554851-32182a80-1eb1-11e9-94dd-895c48d4c85b.png)
[KC3-Error-1548179339.txt](https://github.com/KC3Kai/KC3Kai/files/2783966/KC3-Error-1548179339.txt)

**Comment by mikenzb** [comment]
Fixed in 33.7.0
