### ISSUE TITLE
show first to anti-submarine bug

### ISSUE THREAD

**Issue by ztjal** [KC3Kai/KC3Kai#2757]
KC3版本 : 33.7.1
------------------------------

maybe not calculating 三式水中探信儀 +3 buff, e.g. 舞風改.

not a big problem.

![default](https://user-images.githubusercontent.com/6552290/51853665-c6780680-2363-11e9-8465-76714f43a9cc.png)

**Comment by ztjal** [comment]
sorry, i talking about the blue txt.
![default](https://user-images.githubusercontent.com/6552290/51899677-7eea8c80-23ee-11e9-9797-7892b924cb2a.png)

**Comment by sinsinpub** [comment]
talking about the opening asw threshold value, i did tests on escort light carrier that asw stat over 65 by bonus from 931 air group **CANNOT** meet the oasw condition.
so more tests may be required now:
 * asw >= 65 by torpedo bomber bonus on CVE can oasw?
 * asw >= 50 by TB bonus + Type 0 sonar on CVE can oasw?
 * asw >= 100 by sonar bonus can oasw?
 * asw >= 60 by bonus on DE can oasw?

it will help if u can test any of those, put your test result (eg: replay) here.

**Comment by ztjal** [comment]
all test in 1-5A

瑞鳳改二乙（LV99，asw=48） + Ju87C改二(KMX搭載機)（asw+9） + 零式艦戦63型(爆戦)（asw+2）+ Swordfish Mk.II(熟練)（asw+6）= 65，CANNOT oasw. ×

瑞鳳改二乙（LV99，asw=48） + Ju87C改二(KMX搭載機)（asw+9） + F4U-1D（asw+1） + 九七式艦攻(九三一空)（asw+7）= 65，it can oasw. √

瑞鳳改二乙（LV99，asw=48） + Ju87C改二(KMX搭載機)（asw+9） + 零式水中聴音機（asw+11）= 68，CANNOT oasw. ×

大鷹改二（LV99，asw=89） + 零式水中聴音機（asw+11）= 100，CANNOT oasw. ×

大鷹改二（LV99，asw=89） + Ju87C改二(KMX搭載機)（asw+9, buff+1）= 99，it can oasw. √

択捉改（LV91，asw=75） + SG レーダー(初期型)（asw+3）= 78，CANNOT oasw. ×

@sinsinpub
