### ISSUE TITLE
Fit bonus of Re.2001 aircraft for Aquila Kai and Graf Zeppelin Kai - December Ranking Reward

### ISSUE THREAD

**Issue by FirstDagger** [KC3Kai/KC3Kai#2758]
Fit bonus for Aquila and Graf Zeppelin

https://www.reddit.com/r/kancolle/comments/albl2e/news_december_ranking_rewards/efcks2n/

> Re.2001 CB改: +3 firepower, +6 bombing stat, +4 AA, +3 ASW, +1 accuracy, +2 evasion
Extra ~~+2 firepower~~ +4 firepower, +1 AA, ~~+1 evasion~~ +3 evasion when equipped by Aquila kai.
~~_Not sure whether the AA is counted as normal AA or as the fighter power._~~
Bonus AA is apparently not counted in AS calculation
Re.2005 kai now extra +1 AA and +2 evasion when equipped by Aquila kai and Graf Zeppelin kai.
Re.2001 OR kai now extra +1 firepower, +2 AA and +3 evasion when equipped by Aquila kai.
Re.2001 G kai now extra +3 firepower, +1 AA and +1 evasion when equipped by Aquila kai.

**Comment by sorewachigauyo** [comment]
To take note, gear bonus AA does not contribute to equip AA as well
https://twitter.com/DarkQuetzal/status/1090574141705474048

**Comment by sorewachigauyo** [comment]
Also, CB改 gives +4 firepower, not +3
