### ISSUE TITLE
Hyuuga K2 requires airmats but not listed

### ISSUE THREAD

**Issue by neptunia** [KC3Kai/KC3Kai#2788]
The newly implemented Hyuuga K2 requires a New Model Aerial Armament material to remodel, but is not listed under the the "Blueprints" tab of strategy room as needing such. 

~~turns out i was looking at the wrong commit There is no such function in /src/library/modules/RemodelDb.js for something like "CalcAirMat" (however, it does seem to calculate air mats required), and the relevant checks for PlayerManager.consumables.newAircraftBlueprint in /src/pages/strategy/tabs/blueprints/blueprints.js also seem to be missing. (I'm not sure if those are the only two relevant files).~~

Looking through the 3/27 update, it seems that the checks were added, but they don't show up for me.

**Comment by sinsinpub** [comment]
read `Help Topics` at top right, then click this:
![image](https://user-images.githubusercontent.com/160240/55270903-cfdc0b80-52df-11e9-946e-36849059eb30.png)

**Comment by neptunia** [comment]
I see, thanks!
