### ISSUE TITLE
Mark ships required by quests in Strategy Room Ship List.

### ISSUE THREAD

**Issue by Khanxay** [KC3Kai/KC3Kai#279]
Just a feature request. I was thinking a toggle could be put next to "Equip Stats: Yes No"  on the Ship List page and it would color the names of ships (like how fully modernized stats are colored) that are used in quests.

**Comment by Nya-chan** [comment]
This is probably obsolete now with the quest page? Or do we want to implement it as suggested (toggling option in ship list)?

**Comment by Javran** [comment]
@Nya-chan yep, I think with Required ships this can now be closed.
