### ISSUE TITLE
日向改二 equip S-51J buff wrong sign

### ISSUE THREAD

**Issue by ztjal** [KC3Kai/KC3Kai#2790]
KC3版本 : 33.8.8 
-----------------------
write the plus sign incorrectly and minus sign.

![无标题](https://user-images.githubusercontent.com/6552290/55290620-1a58a780-5408-11e9-9ac7-26f562b04980.jpg)

**Comment by sinsinpub** [comment]
thx for ur report, info on new equipment always insufficient/confused.
can u send the in-game screenshot before S-51J equipped (other slots must be the same)

btw, current wikiwiki info:
![image](https://user-images.githubusercontent.com/160240/55292446-bf31af80-541d-11e9-8152-eefb85bdc2d9.png)
swdn's info:
![image](https://user-images.githubusercontent.com/160240/55292459-dcff1480-541d-11e9-8a82-c95f2502ff95.png)

btw2, still no bonus info for `O Type Observation Autogyro Kai Ni`

**Comment by ztjal** [comment]
![before](https://user-images.githubusercontent.com/6552290/55316549-3c523880-54a1-11e9-9852-843f7566c7b2.JPG)

----------------------------------
瑞雲改二(六三四空) same wrong sign

![634](https://user-images.githubusercontent.com/6552290/55316572-470ccd80-54a1-11e9-8b3f-37b93c435693.jpg)

**Comment by sinsinpub** [comment]
😮 ur 2 screenshots show that S-51J gives Hyuuga K2 +5 evade... that's not matched with any other proofs. r u sure that ur ex-slot were equipping the same thing before/after S-51J?

screenshots from this guy says only +2 eva (Type 1 AP shell -> S-51J on slot5)
https://pbs.twimg.com/media/D2vWoXYUYAAFxvS.jpg:large

**Comment by ztjal** [comment]
![555](https://user-images.githubusercontent.com/6552290/55323540-e934b180-54b1-11e9-84da-40bd222cbf64.jpg)
![666](https://user-images.githubusercontent.com/6552290/55323545-eafe7500-54b1-11e9-85dd-97e0173bd634.jpg)
---------------------------
i say the “-” sign, the true is “+”.
next time i'll circle then first.
