### ISSUE TITLE
Akashi's Improvement Arsenal 三式弾 is blank

### ISSUE THREAD

**Issue by ztjal** [KC3Kai/KC3Kai#2807]
KC3版本 : 33.9.3 
---------------------------
![捕获](https://user-images.githubusercontent.com/6552290/56847728-83e9aa00-6911-11e9-93bd-38fac082282b.JPG)

**Comment by sinsinpub** [comment]
@Diablohu on Saturday 
![image](https://user-images.githubusercontent.com/160240/57004698-8c88fb80-6c03-11e9-880e-c2803e1ff7cb.png)

![image](https://user-images.githubusercontent.com/160240/57004734-dd005900-6c03-11e9-98a4-59bb7a05f3e2.png)

**Comment by Diablohu** [comment]
Thanks for posting

I'm sorry but I'm on a vacation from today. I will be update WCTF database as soon as I'm back after 2~3 days

**Comment by Diablohu** [comment]
fixed in https://github.com/TeamFleet/WhoCallsTheFleet-DB/commit/e476373400c89d4d75caf66a0993d9fd4607ec24
