### ISSUE TITLE
[Bug] Badge export have error when export from KC3Kai

### ISSUE THREAD

**Issue by htomeload** [KC3Kai/KC3Kai#2815]
Versions:
Chromium: 73.0.3683.86 (Official Build) (64-bit)
OS: Pop!_OS 18.04 LTS
KC3Kai: 33.9.5 [Chrome Web Store]
Game Mode: Customize DMM Website

Steps to reproduce:
- Go to Badge tab.
- Leave all option as checked.
- Click Export.

Actual behaviour:
Image not load.

Expected behaviour:
733 Images should be loaded.

Screenshots (if applicable):
<a href="https://imgur.com/NfXmHLe"><img src="https://i.imgur.com/NfXmHLe.png" title="source: imgur.com" /></a>

Error Report (if applicable):
Console shown error message

> Uncaught TypeError: Cannot use 'in' operator to search for 'inazuma1' in undefined
>     at Array.<anonymous> (kaini.min.js?version=18:1)
>     at f (jquery.min.js:1)
>     at Object.fireWith [as resolveWith] (jquery.min.js:1)
>     at Object.<anonymous> (jquery.min.js:1)
>     at f (jquery.min.js:1)
>     at Object.fireWith [as resolveWith] (jquery.min.js:1)
>     at r (jquery.min.js:3)
>     at XMLHttpRequest.r (jquery.min.js:3)

I try to open link new tab, then all image can be loaded. After that, I try to export again but result still same as said.

**Comment by Vultren** [comment]
That was a oversight that was missed while changing the way the data was loaded on the badge. It was fixed earlier today [here](https://github.com/Nya-chan/k2badge/pull/52). Should be back up now.
