### ISSUE TITLE
show error when back to home

### ISSUE THREAD

**Issue by ztjal** [KC3Kai/KC3Kai#2828]
KC3版本 : 33.10.2
========================
![000](https://user-images.githubusercontent.com/6552290/58900595-085df280-8732-11e9-8805-5576aeea39e4.jpg)

after V point battle, auto back to home, show this.

========================

maybe any strike aircraft is clean?

![001](https://user-images.githubusercontent.com/6552290/58900779-64287b80-8732-11e9-9c93-aef12fe2d32e.JPG)
![002](https://user-images.githubusercontent.com/6552290/58900785-668ad580-8732-11e9-98c1-af6f4ac15440.JPG)

**Comment by ztjal** [comment]
![004](https://user-images.githubusercontent.com/6552290/58957761-e3ba5700-87d3-11e9-8c53-58b5896abb4a.jpg)

**Comment by mikenzb** [comment]
Has updating ur KC3 fixed this problem?

**Comment by ztjal** [comment]
These problems will also arise when we attack E5. Later, we found that one thing in common is that we lost the battle against BOSS(C, D).

June 12 has completed the event, now do not want to go back to see the those maps of BOSS, this event is not friendly...

These problems should only arise during this event. Turn off the issue after the 25th...
