### ISSUE TITLE
Missing several expedition scorer list

### ISSUE THREAD

**Issue by tsusai90** [KC3Kai/KC3Kai#2845]
World 1 : A1, A2, A3
World 2 : B1, B2
![image](https://user-images.githubusercontent.com/22212342/60284377-942ffc80-9935-11e9-937a-5ae28942f9e7.png)

**Comment by sorewachigauyo** [comment]
The maintainer of the expedition scorer is no longer working on it. 
He has made a website that includes the updated expeditions at https://javran.github.io/kancepts/

**Comment by tsusai90** [comment]
thanks, i will closed the issue, unless someone bother to update kc3 version
