### ISSUE TITLE
Destroyer Escort Repair Time Prediction incorrect during sortie

### ISSUE THREAD

**Issue by Grunilg** [KC3Kai/KC3Kai#2849]
### Versions:

Google Chrome | 75.0.3770.100 (Offizieller Build) (64-Bit) (cohort: Stable)
Windows 10 OS Version 1803 (Build 17134.885) 64bit
KC3kai  33.10.6

### Steps to reproduce:

Damage a Destroyer Escort during Sortie and use the Mouseoverprediction (on the HP bar) for Repairtime during the sortie and upon return to the Port

### Actual behaviour:

Predicted Repairtime during sortie is twice the actual Repairtime

### Expected behaviour:

Repairtimes should match up according to http://en.kancollewiki.net/wiki/Docking#Repair_time Suspecting Error in Ship type multiplier (x1 instead of x0.5 for DE)

### Screenshots (if applicable):

![During Sortie](https://cdn.discordapp.com/attachments/550950152899395587/600230434990718980/unknown.png)
![At Homeport](https://cdn.discordapp.com/attachments/550950152899395587/600230565740019714/unknown.png)

**Comment by sinsinpub** [comment]
will be fixed along with new expeditions on next maint 🤔
