### ISSUE TITLE
task list BUG

### ISSUE THREAD

**Issue by mathyyj** [KC3Kai/KC3Kai#2853]
I find this bug:

first, I sign in Kancolle using KC3, and accept daily task such as "run 3 expeditions" 
then I sign in Kancolle on mobilephone, and finish  "run 3 expeditions" 
BUT! when I open Kancolle using KC3 again,  "run 3 expeditions"  still exists on KC3 board, and never refreshed until next day.

I hope it can be fixed, by adding some logical judgement into this, to avoid occupation on task lists in KC3 board

**Comment by sorewachigauyo** [comment]
Unfortunately, we are only able to detect your current quests when you enter the quest menu with kc3 active.

If you wish to clear the quest on the panel, you can refer to this https://github.com/KC3Kai/KC3Kai/issues/2425#issuecomment-355208391
