### ISSUE TITLE
Expedition 43's income resource is wrong

### ISSUE THREAD

**Issue by redpizza** [KC3Kai/KC3Kai#2854]
Expedition 43's income resource is wrong.
fuel gains swapped with baux gains.

![image](https://user-images.githubusercontent.com/31765780/61859919-0a5b5b00-af04-11e9-914f-45e77649e1ce.png)
![image](https://user-images.githubusercontent.com/31765780/61860074-4c849c80-af04-11e9-9844-cfdbf4f44994.png)

I'm using KC3改 version 33.10.8.

**Comment by sorewachigauyo** [comment]
Fixed in https://github.com/KC3Kai/KC3Kai/pull/2856/commits/a77fd7cce7257e1fd13f7d150de8ff4af22a14a1
