### ISSUE TITLE
Issue : Mission Stackings

### ISSUE THREAD

**Issue by tenshi04kuma** [KC3Kai/KC3Kai#2893]
- Chrome : 76.0.3809.132 (Official Build)
- 64bit
- KC kai installed version 34.0.5
- I use the WebStore version, I think...
- I Play Kantai Collection with the Github KC Kai.
- Screenshot : *See the screenshot below*
- I play Kantai Collection on PC but also on my phone and if I clear the mission on it, The mission will still be displayed on the KC Devtool

### Steps to reproduce:
Select the mission on PC, then it is displayed on the Devtool.
Quit PC game
Do the mission on phone and CLEAR it.
Quit Phone game
Then come back on PC but the mission is still displayed on the Devtool.
If you do it too much the missions stacks.
### Actual behaviour:
For now I have 4 missions cleared but still displayed on my Devtool
because I have them cleared on my phone while I was away.
### Expected behaviour:
I expected it to be cleared out of my Devtool, or at least give me a way to remove them.

### Screenshots :
![Capture d’écran (3)](https://user-images.githubusercontent.com/55600601/65353742-d9a85100-dc28-11e9-86aa-7a8946d302a2.png)

**Comment by nonsensed** [comment]
Unfortunately, there is no method to track quests completed while kc3kai is not running, which leads to the problem you're encountering.

In order to manually remove quests from the tracker, please click the colored square next to the quest name in the panel. After you've activated the square, moving between the game's main screen and the game's quest screen will remove the unwanted quest.

**Comment by tenshi04kuma** [comment]
Thanks so much for your help !
And Wow ! That's a fast response !

Télécharger BlueMail pour Android<http://www.bluemail.me/r?b=15635>
Le 21 sept. 2019, à 01:52, nonsensed <notifications@github.com<mailto:notifications@github.com>> a écrit:

Unfortunately, there is no method to track quests completed while kc3kai is not running, which leads to the problem you're encountering.

In order to manually remove quests from the tracker, please click the colored square next to the quest name in the panel. After you've activated the square, moving between the game's main screen and the game's quest screen will remove the unwanted quest.
