### ISSUE TITLE
Error when crafting equipment

### ISSUE THREAD

**Issue by MikuHatsune39** [KC3Kai/KC3Kai#2902]
### Versions:
Chrome version: 70.0.3538.110
OS: Windows 10 64bit
KC3 Kai version: 34.0.6

### Steps to reproduce:
Try to craft equipment

### Actual behaviour:
Gets an error popup

### Expected behaviour:
Displays the equipment that has been crafted

### Screenshots (if applicable):
![Screenshot](https://user-images.githubusercontent.com/32179075/66000763-17d02b00-e4db-11e9-9e95-1a16c09946ef.png)

### Error Report (if applicable):
[KC3-Error-1569963635.json.txt](https://github.com/KC3Kai/KC3Kai/files/3678503/KC3-Error-1569963635.json.txt)

**Comment by sorewachigauyo** [comment]
Fixed in https://github.com/KC3Kai/KC3Kai/pull/2900
Leave this open for now until https://github.com/KC3Kai/KC3Kai/pull/2897 is closed
