### ISSUE TITLE
Screenshot is broken

### ISSUE THREAD

**Issue by takase1121** [KC3Kai/KC3Kai#2915]
### Versions:
Chrome: `77.0.3865.90 (Official Build) (64-bit) (cohort: Stable)`
OS: `Windows 10 Pro 1903 (OS Build 19013.1102)`
Bitness: `64-Bit`
KC3Kai: `34.1.4`
From: Chrome Web Store
Play Mode: Customize DMM Website (default)

### Steps to reproduce:
Use the screenshot button on the panel in DevTools
![image](https://user-images.githubusercontent.com/20792268/68468521-27b5fa00-0253-11ea-8059-973ba9c47ba5.png)

### Actual behaviour:
Screenshot of the page like:
![image](https://user-images.githubusercontent.com/20792268/68468589-4916e600-0253-11ea-93fb-efdcb280e0ab.png)

### Expected behaviour:
What I actually get:
![2019-11-08 18-11-58 18](https://user-images.githubusercontent.com/20792268/68468602-4fa55d80-0253-11ea-87b4-3f7bdcb41bd7.png)

**Comment by nonsensed** [comment]
Hi, takase1121.

In the KC3 settings page, there is a section for screenshot settings. You'll find an option there called `Device Pixel Ratio`. Please try changing this option to see if any of the choices fix the issue.

**Comment by takase1121** [comment]
Changed my mode to `Auto` and it worked! Thanks!
