### ISSUE TITLE
API Error on 6-5 Boss (TsunDB) and Layout Issue

### ISSUE THREAD

**Issue by Cheesyfof** [KC3Kai/KC3Kai#2918]
- Chrome 78.0.3904.97 (Official Build) (64-bit) (cohort: Stable)
- Microsoft Windows 10 Pro 64bit 10.0.18362 Build 18362
- 34.1.4 webstore version
- "Customize DMM Website" mode

Issue 1:
Upon reaching the boss node of 6-5 via the south route (B-F-I-J-M) KC3 Kai throws an API error mentioning TsunDB. Error log attached. Run multiple times while clearing and got the error each time at the boss node. Side note, the error popups are too wide for the tall-layout in Moonlight.
[KC3-Error-1574201127.json.txt](https://github.com/KC3Kai/KC3Kai/files/3866345/KC3-Error-1574201127.json.txt)
![IssueError](https://user-images.githubusercontent.com/46071033/69193365-73ec1e80-0b1e-11ea-9fee-10bf629c3978.JPG)

Issue 2:
For some reason the game hasn't been showing quite so nicely. Pictured below. I've tried opening the game in a new tab and it persists.
![image](https://user-images.githubusercontent.com/46071033/69191603-bad81500-0b1a-11ea-9241-ca683e9f7fb6.png)

**Comment by Cheesyfof** [comment]
Why was this closed? The layout issue is still an issue :~(
![Untitled](https://user-images.githubusercontent.com/46071033/70143502-b6bc0380-1693-11ea-97b7-dd43e1a966a9.png)

**Comment by mikenzb** [comment]
Just wondering, are you on 100% zoom?
Try resetting your zoom using `CTRL` + `0`

**Comment by Cheesyfof** [comment]
It's on default zoom; zooming in and out doesn't fix it either.
The blank space does seem to be a bit of the website though as it's coloured white compared to the rest of the page:
![Capture](https://user-images.githubusercontent.com/46071033/70453516-cf1b8c00-1aa0-11ea-8a9b-769c4d15e91f.JPG)

**Comment by Cheesyfof** [comment]
Okay, so the images in my library weren't loading either (the ship list) so I reinstalled the extension and it seems to be fine now.
Forgot to do a backup beforehand so I've lost 3 days of stuff but I haven't really done all that much in those 3 days so it shouldn't be an issue. 👍
