### ISSUE TITLE
About the [Event History]

### ISSUE THREAD

**Issue by REAreaa** [KC3Kai/KC3Kai#2922]
- Chrome version 78.0.3904.108 (64bit)
- KC3 Kai version 34.1.5
- Running in the one from [Chrome Web Store]
- "Customize DMM Website" mode

Issue: Maybe this shouldn't be count as a bug, but may I have the event sortie record back please? Really want to save them down for a memorial. Thank You!

**Comment by sorewachigauyo** [comment]
The event sortie record is not removed.
![image](https://user-images.githubusercontent.com/26541502/70007473-69646700-15ab-11ea-9f53-db17217c9bd1.png)

If you mean the sorties for the current event, the ability to view them will be added with the next KC3 patch.

**Comment by mikenzb** [comment]
34.2.0 resolves this issue.
