### ISSUE TITLE
Bq6 does not count Asashimo Kai Ni

### ISSUE THREAD

**Issue by redpizza** [KC3Kai/KC3Kai#2927]
Quest Bq6 (精鋭「三一駆」、鉄底海域に突入せよ！) does not count Asashimo Kai Ni(578).

**Comment by sinsinpub** [comment]
eh... do u mean in-game Kai Ni counted, but kc3 quest tracking not counted?
should i fix both tracking condition and quest memo text?

**Comment by redpizza** [comment]
yus
in-game, Bq6 can clear with Asashimo Kai Ni. but KC3's quest tracker does not track.

https://github.com/KC3Kai/KC3Kai/commit/3196ec1775d3377f3f8429ce023c418427e31dab looks okay :D
