### ISSUE TITLE
OpenDB Submission API update required

### ISSUE THREAD

**Issue by WolfgangKurz** [KC3Kai/KC3Kai#2933]
![KanColle OpenDB](https://user-images.githubusercontent.com/20940566/71001895-8fe4df00-2121-11ea-82d3-0e2a8f4c78d8.png)

OpenDB's Equipment creation report API has been updated.

Current version of OpenDBSubmission not processing array data.

So, need to update like PoiDBSubmission.

Just call API 3 times when player used massive equipment creation.

api_ver should be `3`.
api_ver `2` works for now but it **deprecated**, will be ~removed~ soon.

Thanks.

**Comment by gakada** [comment]
Current payload is

https://github.com/KC3Kai/KC3Kai/blob/c71440d99da2eb2e1d667ed138738a6a087facd3/src/library/modules/OpenDBSubmission.js#L112-L118

so `apiver: 2` -> `apiver: 3`? No need to `parseInt` resources? And is it ok to not convert `-1` `api_slotitem_id` to `0` in `result` and send it as is?

**Comment by gakada** [comment]
here is
- `apiver: 3`
- not parsing resources
- failure is `0` in `result` as it was, equipment id otherwise

**Comment by WolfgangKurz** [comment]
OK, no problem. Thanks!

Please close this issue after released. :)

**Comment by gakada** [comment]
@WolfgangKurz it seems like API server is down https://downforeveryoneorjustme.com/opendb.swaytwig.com.
