### ISSUE TITLE
Updates for Chrome Store Version?

### ISSUE THREAD

**Issue by CyclonicPinna** [KC3Kai/KC3Kai#2946]
Hi there, thank you for building this useful Kancolle extension. I would like to ask if it is normal that updates for KC3Kai (downloaded from Chrome Store) are delayed, compared to the releases here on Github.

I am running KC3Kai 34.2.3 (Chrome Store version) in Google Chrome 78.0.3904.70 (x64) in a Windows 7 PC. I can see from the release history that there have been two newer versions, namely 34.2.4 and 34.3.0, while in Chrome Store, the latest version is still 34.2.3.

**Comment by sorewachigauyo** [comment]
As seen from https://github.com/KC3Kai/KC3Kai/pull/2947, Google has flagged us for not complying with their policy. The previous two releases were not released on the webstore for that reason. We have made the necessary adjustments and are pending their review.

**Comment by CyclonicPinna** [comment]
Good to know. Thank you for the information.
