### ISSUE TITLE
KC3Kai Back Ups Not Working/Not Saving as KC3Data

### ISSUE THREAD

**Issue by GinWoozy** [KC3Kai/KC3Kai#2958]
Hello,

Recently, I've tried to import a previous back up, but I noticed that it was saved as 2 JSON files (db.json, storage.json) instead of KC3Data and I cannot import them. Further backups result in the same thing.

Anyway to get around this?

**Comment by sorewachigauyo** [comment]
As per https://github.com/KC3Kai/KC3Kai/issues/2914 Chrome autorenames the `.kc3data` file extension to `.zip`

For now you can just rename it back to `.kc3data`

**Comment by GinWoozy** [comment]
> As per #2914 Chrome autorenames the `.kc3data` file extension to `.zip`
> 
> For now you can just rename it back to `.kc3data`

So, I should directly rename the zipfile, or should I take the 2 json files and put them into a folder named[username] date.kc3.data?

**Comment by sorewachigauyo** [comment]
Rename `<file>.zip` to `<file>.kc3data`

**Comment by GinWoozy** [comment]
> Rename `<file>.zip` to `<file>.kc3data`

Sorry if I'm misunderstanding, but I've tried to change the file name, but it picks it up as a folder and it won't upload both files at once either.

**Comment by GinWoozy** [comment]
Whoops never mind, realized I had to configure my file explorer options to change it.

Thank you!
