### ISSUE TITLE
Event battle can't be logged

### ISSUE THREAD

**Issue by lisongyuan99** [KC3Kai/KC3Kai#2961]
# Versions: 
Chrome 80.0.3987.132 
Windows 10 18363.657 64bit 
KC3 Kai 34.4.2 webstore version
### Steps to reproduce:
I've restore the backup file about two weeks ago, I found normal map's battle can be logged, but event's can't.
### Actual behaviour:
As the screenshots, I've reached 2020 winter event E1P3, but there is no battle log in it, and I can find Enemy Encounterss of E1P1 and P2.
### Screenshots (if applicable):
![2020-03-06 (1)](https://user-images.githubusercontent.com/42134107/76084819-c24cfc80-5feb-11ea-8e62-18550da2694e.png)
![2020-03-06 (2)](https://user-images.githubusercontent.com/42134107/76084836-c711b080-5feb-11ea-959e-df26cdf6ea14.png)
![2020-03-06 (3)](https://user-images.githubusercontent.com/42134107/76084840-c7aa4700-5feb-11ea-9858-1e9eadea099e.png)

**Comment by sorewachigauyo** [comment]
Your event history is logged. It will be displayed on the next release.

**Comment by martirsadota** [comment]
Have you tried manually changing the end of the URL from `#event-46` to `#event-47`? That should do for a workaround until KC3 gets updated

**Comment by lisongyuan99** [comment]
@martirsadota 
It works , thanks.
