### ISSUE TITLE
 Request translation repo access [Vietnamese]

### ISSUE THREAD

**Issue by haidang10897** [KC3Kai/KC3Kai#2968]
Hi, I'm 魁の光. I want to join the Vietnamese translation offcial team and i will translate to Vietnamese for Vietnam player. I've translated Quest, items, terms and useitem.json to Vietnamese. In the future, i have a plan to translate the hardest thing quotes.json and up-to-date files in Vietnamese Folder.
My current fork: https://github.com/haidang10897/kc3-translations
 
Sorry, i can't add labels

**Comment by HitomaruKonpaku** [comment]
You can just push to your repo and make pull request to KC3Kai/master

**Comment by mikenzb** [comment]
I've sent a invitation to the KC3 translators team.
