### ISSUE TITLE
Married ship has lower oil & ammunition consume than the same ship that is not married

### ISSUE THREAD

**Issue by KiKiBoss** [KC3Kai/KC3Kai#2985]
Married Ships have 15% oil & ammunition consume reduction but the panel shows the same.
EX:Mutsu(LV134) should be 153/191 rather than 180/225
![image](https://user-images.githubusercontent.com/63653725/80277246-4edc8700-8720-11ea-8ba8-cc30f58ba3d6.png)

**Comment by sinsinpub** [comment]
those values next to arrow are the masked (not displayed in-game) max fuel & ammo values of the ship, which never affected by marriage. the resupply costs are already reduced by 15% if ur ship not full-filled.
