### ISSUE TITLE
Remove <all_urls> permission from webstore builds.

### ISSUE THREAD

**Issue by mikenzb** [KC3Kai/KC3Kai#2989]
```
Dear Developer,

Your recent publish request for Google Chrome item "KanColle Command Center 改" with ID: hkgmldnainaglpjngpajnnjfhpdjkohh was rejected because it did not comply with our policies.

If you already have a published version of this item on the Chrome Web Store, it has not been affected and is still available.

Your item did not comply with the following section of our Program Policies:

"User Data Privacy"

Your product violates the "Use of Permissions" section of the policy, which requires that you:

Request access to the narrowest permissions necessary to implement your product’s features or services.
If more than one permission could be used to implement a feature, you must request those with the least access to data or functionality.
Don't attempt to "future proof" your product by requesting a permission that might benefit services or features that have not yet been implemented.
```

KC3 Webstore builds are constantly being rejected due to the `all_urls` permission in the manifest. If possible would it be viable to rework this permission somehow using `activeTab` instead? 

Would save us a lot of trouble trying to publish releases on the webstore.

**Comment by sinsinpub** [comment]
although i did the modification, but i'm not sure if it really works at all 😭 
this must be fully tested to see if `activeTab` really works with latest chrome version (google developer site says `activeTab` behavior has changed since m72) and current prime game mode: `Customize DMM Website`...

thank to my poor network, and my chromium is still m60, unfortunately i can only say without `<all_urls>`, it doesn't affect regular game play under `API Link` mode, and popup windows to different domains not listed in permissions are still working. perhaps screenshots (to be uploaded to imgur) or pushbullet notification will stop working? 🤔

**Comment by Tedster59** [comment]
tested latest dev branch on 
![image](https://user-images.githubusercontent.com/21696818/81218416-ca052f00-8fa3-11ea-87ea-70d96e179769.png)

Screenshots finding, using PNG filetype and normal pixel ratio:
- download mode will download a blank transparent image
- imgur and new tab modes work as expected
- the bug with screenshots being blurry if the chrome window is an odd number of pixels wide is back (or was never fixed)

blurry: https://cdn.discordapp.com/attachments/205766705463427072/707657083201257542/99d69ab3-edc9-45ef-8625-ee7b25f3f901.png
clear: https://cdn.discordapp.com/attachments/205766705463427072/707657088519897208/117a6df2-3c7e-4a9a-8c9d-4711b5028d40.png

**Comment by sinsinpub** [comment]
hm, the blank image, that's a 'new bug' after revoke `<all_urls>` permission...
by using the `activeTab` permission, we can't succeed `chrome.tabs.captureVisibleTab` before the extension is explicitly activated (for example, clicking the heart logo icon)
chrome console reports (`undefined` url is the failed image data base64 string):
![image](https://user-images.githubusercontent.com/160240/81246207-8238e300-9049-11ea-860a-44195fba8a4b.png)
after a kc3 menu clicking, the screenshot API will be executed successfully
![image](https://user-images.githubusercontent.com/160240/81247088-b31a1780-904b-11ea-9f7a-34f09cfab55a.png)

i found a discussion about this: https://stackoverflow.com/questions/25964869/chrome-screenshot-works-only-when-extension-is-clicked
the bug report: https://bugs.chromium.org/p/chromium/issues/detail?id=339703
but no solution except use `<all_urls>` there 😢 


blurry image may be a thing that 'worked as expected' as long as image is 'resized'. perhaps we can try to disable `imageSmoothingEnabled`?

**Comment by Tedster59** [comment]
Confirmed the "clicking" behavior, download option works once I click something within the dropdown.

**Comment by sinsinpub** [comment]
as a workaround, this check and box added when ss button is clicked...
to remind people there is a method to overcome it 🤣 
![image](https://user-images.githubusercontent.com/160240/81271409-9fd46f80-907e-11ea-942b-eac6d927a381.png)

**Comment by sinsinpub** [comment]
@Tedster59 so don't forget: to test more features other than screenshot, should be tested under new started game before the permission is invoked (eg, before clicking dropdown menu)

**Comment by Tedster59** [comment]
What else was problematic with this permission change?  I only recall screenshots being the specific issue with this.

**Comment by sinsinpub** [comment]
exactly no idea about it... i thought all chrome extension APIs of any`chrome.category.function` and CORS relevant network things affected by permissions.
but according tests and [this page](https://developer.chrome.com/extensions/tabs#method-captureVisibleTab), for now,
it seems only tab capture function API we are using in `chrome.tabs` category is sensitive enough to use `<all_urls>` 🤔 
perhaps a full checklist of chrome APIs we use by searching this regexp `\bchrome\.\w+\.` among whole project js files...

**Comment by sinsinpub** [comment]
it seems google still unhappy even `<all_urls>` removed. `all hosts` in log might caused by `"*://*/kcs2/index.php?api_root=/kcsapi*"` pattern in `content_scripts` section. but there is no wildcard for ip addresses can be used in match patterns, so that if all kc server ips listed there instead, new ip will not work for every time kc devs change a ip address... 🤔
