### ISSUE TITLE
File URLs broken with 34.6.0 update

### ISSUE THREAD

**Issue by Arill** [KC3Kai/KC3Kai#2993]
### Versions:
Chrome - 81.0.4044.138 64bit
OS - Win 10 Pro, version 1909, build 18363.836 64bit
KC3 Kai - 34.6.0, Chrome Web Store version
Using the Customize DMM webpage mode to play, KC3 on devtools dock.

### Steps to reproduce:
Using file URLs (file:///C:/Users/... for example) in places where KC3 would expect a regular URL format (as in panel background image, or importing custom CSS from an URL in the custom CSS box, using the @import directive,, for example).
File URLs permissions on "chrome://extensions/?id=hkgmldnainaglpjngpajnnjfhpdjkohh" is also enabled in this scenario.

### Actual behaviour:
Nothing happens, as if an invalid link was provided for said fields.

### Expected behaviour:
File URLs are able to load files stored locally as if they were regular URLs.

**Comment by sinsinpub** [comment]
not sure if this is related to new permission. as far as i recall, file url not work in devtools panel even if `Allow access to file URLs` enabled, but work for contents pages and etc... even in my old chromium and old kc3, i have to upload my background image for panel part to a site 🤔 

perhaps we need to add a `file:///*` permission to manifest, but who know if this will make google reviewer unhappy or not?

**Comment by sinsinpub** [comment]
do file urls work again for 34.6.2?

**Comment by Arill** [comment]
Yes they do. Thank you very much for looking into it :)
I hope the change doesn't make the store upset again lol
