### ISSUE TITLE
Error: Failed to set the 'player' property on 'Storage' ~

### ISSUE THREAD

**Issue by s-door** [KC3Kai/KC3Kai#2996]
### Versions:
Chrome version:
```
Google Chrome	83.0.4103.61 (Official Build) (64-bit)
Revision	94f915a8d7c408b09cc7352161ad592299f384d2-refs/branch-heads/4103@{#561}
OS	Linux
JavaScript	V8 8.3.110.9
Flash	32.0.0.371 /home/ubuntu/.config/google-chrome/PepperFlash/32.0.0.371/libpepflashplayer.so
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36
```
OS and its version: Ubuntu 18.04.4 LTS 64bit
KC3 Kai version: 34.6.1
build: webstore version
game play mode: Direct DMM website

### Steps to reproduce:
Logging in, and I sort out to 5-2, Occurred.

### Actual behaviour:
Popup error, but continually play the game.

### Expected behaviour:
No error.

### Screenshots (if applicable):
![image](https://user-images.githubusercontent.com/1191220/82721084-131fe780-9cf5-11ea-9030-e68b86902588.png)

### Error Report (if applicable):
[KC3-Error-1590205952.json.txt](https://github.com/KC3Kai/KC3Kai/files/4671108/KC3-Error-1590205952.json.txt)

#1356 related issue?
Is there a workaround?
![image](https://user-images.githubusercontent.com/1191220/82721625-c7237180-9cf9-11ea-8b9e-c91782ab89cf.png)

**Comment by sinsinpub** [comment]
yea, it seems ur HTML5 localStorage quota is reached... 5MBytes quota is expected.
you can always monitor the usage percent at this section in ur Strategy Room Profile page:
![image](https://user-images.githubusercontent.com/160240/82722129-66df0080-9cf6-11ea-853b-18eb5abbeb92.png)

to diagnose which types of data are taking your storage spaces, execute this script in SRoom page console, sizes in bytes taken by every keys will be listed in desc order: (do remember change the filter and tick verbose to show debug logs)
```js
var s=localStorage, ks={}; for (k in s) { if(s[k] && s.hasOwnProperty(k)) { ks[k]=k.length+s[k].length; } }; var sks=Object.keys(ks).sort((a, b)=>(ks[b]-ks[a])); for(k in sks) { console.debug(sks[k], ks[sks[k]]); }
```
check the output results of top keys, if:
 * `savedFleets` is there, try to delete some saved fleets in Fleet Manager page
 * `ships` or `gears` is there, try to rebuild them from scratch by clicking `Clear bugged Ships & Equipment caches` in `Bug Fixes` section of Profile page
 * `raw` should be a top one, 1.26MBytes. it's expected.
 * other keys should be reasonable under 100KBytes. if any large is found, tell me then.

**Comment by s-door** [comment]
Thank you for quick reply, I check data sizes, as below
![image](https://user-images.githubusercontent.com/1191220/82722972-12438180-9d06-11ea-9ee7-6714a857522e.png)

And after `Clear bugged Ships & Equipment caches`
![image](https://user-images.githubusercontent.com/1191220/82723073-1328e300-9d07-11ea-87b1-92d83427d604.png)

It looks like fixed! I appreciate your help!
