### ISSUE TITLE
I can't pass A6 Expedition

### ISSUE THREAD

**Issue by tinefanforvettel** [KC3Kai/KC3Kai#2998]
![image](https://user-images.githubusercontent.com/20445117/83260505-1e3ab200-a1e4-11ea-99f0-abc4fb683cd1.png)
I don't know what is codition to pass I had failed and gonna lost expedition map in this end of month

**Comment by tinefanforvettel** [comment]
Can anyone provide me what codition is such as all FP300+ LoS200+ ASW150+ or what formation to do and anything all calculations so I can proceed any further

**Comment by sorewachigauyo** [comment]
![image](https://user-images.githubusercontent.com/26541502/83271414-6cf44600-a1fc-11ea-8fd8-edae760f4ce2.png)
Estimated conditions
Also, monthly expeds reset on the 15th, not the end of the month, so you still have time

**Comment by tinefanforvettel** [comment]
![Screenshot_2020-05-30-00-29-18-61](https://user-images.githubusercontent.com/20445117/83317273-98efe580-a255-11ea-9cbe-37f8b55a37cd.jpg)
![Screenshot_2020-05-30-00-29-23-60](https://user-images.githubusercontent.com/20445117/83317275-9b523f80-a255-11ea-811a-33d79b8eda97.jpg)
Err.... give me some bucket instead
