### ISSUE TITLE
Import data doesn't work anymore!

### ISSUE THREAD

**Issue by Maxu6a** [KC3Kai/KC3Kai#3000]
Just reinstall a kc3. Then wanted to recover kc3 data from my saves. But it doesn't see them anymore. Left side is the kc3 saves on my HDD. Right side is how the kc3 see them(actually dont).
![Screenshot_375](https://user-images.githubusercontent.com/43726260/83803649-a1ad4500-a6b5-11ea-9af4-08054f3d4791.png)

**Comment by planetarian** [comment]
Due to a different issue, your backups are being saved as .zip files rather than .kc3data files. You will need to either change their extensions or just tell kc3's import dialog to show all files instead of just .kc3data files.

**Comment by Maxu6a** [comment]
> Due to a different issue, your backups are being saved as .zip files rather than .kc3data files. You will need to either change their extensions or just tell kc3's import dialog to show all files instead of just .kc3data files.

Thx. I didn't smart enough to choose "all files" when looking for save data.
