### ISSUE TITLE
Quests overlay error.!

### ISSUE THREAD

**Issue by Alcaztra** [KC3Kai/KC3Kai#3001]
### Versions: 
 Chrome 83.0.4103.97 (Official Build) (64-bit) (cohort: Stable)
 Windows 10 OS Version 1909 (Build 18363.836) - 64bit
 KC3 34.6.3 from [Chrome Web Store], mode:  Customize DMM Website
### Steps to reproduce:
+ Overlay quests not change.
### Actual behaviour:
Overlay quests description show in quest's page 1, change to other page, page 1's overlay content still show on. 
### Expected behaviour:
Overlay quests description must change content when change to other quest page.
### Screenshots (if applicable):
![image](https://user-images.githubusercontent.com/39544463/84107863-fe5b8780-aa48-11ea-9a6a-0d32a059cc11.png)
![image](https://user-images.githubusercontent.com/39544463/84107885-0a474980-aa49-11ea-8001-fb094c8b512d.png)

**Comment by DynamicSTOP** [comment]
see discussion in #2966
