### ISSUE TITLE
Expeditions A5, A6, B5, and E1 don't show up in Moonlight 

### ISSUE THREAD

**Issue by StorianLogi** [KC3Kai/KC3Kai#3003]
Chrome 83.0.4103.97
Windows 10 Version 1909 64bit
KC3 version 34.6.3 (webstore)

The newest monthly expeditions don't show up in the expedition planner when using Moonlight theme.
![image](https://user-images.githubusercontent.com/20170728/84837429-f83b4d00-afec-11ea-8efd-bc662f9e5962.png)
![image](https://user-images.githubusercontent.com/20170728/84837445-025d4b80-afed-11ea-971c-98cbbe1479b3.png)

I poked around using inspect element and found that, [while there is HTML for A5 and A6 (but not B5 and E1) in moonlight.html](https://github.com/KC3Kai/KC3Kai/blob/68f79432dd1183907d8fcd0e9d3e9175ebc95948/src/pages/devtools/themes/moonlight/moonlight.html#L233), for some reason they seem to be selectively not being displayed by moonlight.js or any other module, even though I couldn't find any code specifically whitelisting or blacklisting certain expeditions.

Thanks for your help!

**Comment by StorianLogi** [comment]
@fourinone41 has a quick fix for this by adding a scrollbar to the expedtion panel, which reveals A5 and A6.
```
.module.activity .activity_body {
    height: 237px;
    overflow-y: auto;
}
```
This fix makes the issue just a matter of adding B5 and E1 to moonlight.html.

**Comment by sinsinpub** [comment]
should have been fixed already in `develop` branch.
btw, migrating `Quest` tab to moonlight...

**Comment by StorianLogi** [comment]
Just got the webstore update. This is perfect! Thanks sinsin.
