### ISSUE TITLE
Night SS CI is not displayed for new equipment [383] Late Model 53cm Bow Torpedo Mount (8 tubes)

### ISSUE THREAD

**Issue by devildelta** [KC3Kai/KC3Kai#3011]
### Versions:
- KC3 Kai version - 34.7.0
### Steps to reproduce:
- Equip any SS(V) with the equipments
    - [383] Late Model 53cm Bow Torpedo Mount (8 tubes)
    - any of [211] Submarine Radar & Passive Radiolocator (E27) or [210] Submarine Radar 
& Waterproof Telescope
### Expected behaviour:
- Displaying Night Torpedo CI in Night Torpedo Attack detail list of ship icon:hover. 
- The reference for Night Torpedo CI is from [JP wiki](https://wikiwiki.jp/kancolle/%E5%BE%8C%E6%9C%9F%E5%9E%8B53cm%E8%89%A6%E9%A6%96%E9%AD%9A%E9%9B%B7%288%E9%96%80%29) `潜水艦53cm艦首魚雷(8門)の上位互換。あちらと違い後期型艦首魚雷(6門)同様の専用カットインがある。`
- According to the description from [here](https://wikiwiki.jp/kancolle/%E5%BE%8C%E6%9C%9F%E5%9E%8B%E8%89%A6%E9%A6%96%E9%AD%9A%E9%9B%B7%286%E9%96%80%29), there should be also the SS Torpedo CI for two Late Model series Torpedo Mounts `1.6倍の2回攻撃`, which may suggest the same bug would happen when [383] and other Late Model series are equipped. But I don't have two of them so no screenshot can be shown. But the logic there should be the same.
### Actual behaviour:
- Displaying no CI in detail list of ship icon:hover. 
### Screenshots (if applicable):
SS equip [383] and [211]
![20200705-01](https://user-images.githubusercontent.com/9845381/86524165-15f42780-beb2-11ea-9e45-dd2bc2c2c958.png)
SSV equip [383] and [211]
![20200705-02](https://user-images.githubusercontent.com/9845381/86524186-6075a400-beb2-11ea-94d5-8ca337ee4cf4.png)
(as part of cross-check, [383] provided a +1 torpedo synergy to go-ya, which is not applicable to ro-chan)

I used to prepare a screenshot of the CI for your reference, and then I took a permission request in my knee.

IMO it is simply not updated yet rather than a bug.

**Comment by devildelta** [comment]
![2020-07-05 12-27-25 87](https://user-images.githubusercontent.com/9845381/86524871-e990d900-beba-11ea-8915-113d6816fcb4.jpg)

**Comment by sinsinpub** [comment]
new torpedo id added in develop branch. i was just waiting to see if there is a new power modifier for it, any news from testers?
