### ISSUE TITLE
"Play via API Link" stopped working after the last update

### ISSUE THREAD

**Issue by Eankun** [KC3Kai/KC3Kai#3042]
### Versions:
Tried on
Chromium 76.0.3809.100 (Official Build) (64-bit) and Chromium 86.0.4240.75 (Official Build) (64-bit)
OS	Windows 10 OS Version 1809 (Build 17763.1457) 64 Bit
KanColle Command Center 改 34.8.6 (from Chrome Web Store)
Playing via API Link, since other modes (Play via DMM on Frame and Customize DMM Website) make my game really unresponsive, laggy and slow to restart.
I'm using Chromium Portable for almost exclusive KC playing, so it has no extensions unrelated to KC except Ublock Origin.

### Steps to reproduce:
Right after 16.10.2020 update 'Play via API Link' option stopped working. 
I get API link just fine, but game won't start afterwards. It worked fine before (15.10 and before that). Now after starting the game I see an error I never saw before (screenshot 1) or, after cache clearing, just black screen with no network traffic (screenshot 2).
KC3Kai log returns "申し訳ありませんがブラウザを再起動し再ログインしてください。" message.
This is very frustrating to me, since API Link was the fastest way for me to play, and it was very reliable.
I understand that "In some Chrome versions (55+), the API Link is not detected by the panel. It gets stuck at 'Waiting for game actions.." but I don't think that this error is connected to my browser version (since it worked the day before the game update).
Just to be on safe side, I tried updating my browser bersion (from Chromium 76 to Chromium 86) and tried reprodusing it on several different PCs and Laptops. The error persisted.

### Screenshots (if applicable):
1: https://i.imgur.com/ATrGPfM.jpg
after cache clear
2: https://i.imgur.com/zXMWUTr.jpg

### Error Report (if applicable):
[[12095864] ErrorLog 2020-10-17.txt](https://github.com/KC3Kai/KC3Kai/files/5395036/12095864.ErrorLog.2020-10-17.txt)

**Comment by sinsinpub** [comment]
because kc official developers want to limit u guys only play game inside dmm domain, so they have changed codes yesterday, and this happen.

not mention details of tech info for now, just simple solution: play via DMM on frame mode or DMM website mode above.

perhaps i will commit a different workaround to try to make API link mode work, but it will not be changed that it's our own risk to use that which not allowed by game.

**Comment by Eankun** [comment]
I see. Thank you for quick answer, I really hope it will be possible to bring API Link mode back somehow!

**Comment by sinsinpub** [comment]
btw, play via dmm site should not 'make my game really unresponsive, laggy', u may try an ad-block extension like `ublock origin` to stop those ad/sns/analytics sub-frames and scripts being loaded. will feel better.

**Comment by Eankun** [comment]
I'm using ublock and it works, still this way of playing is much slower than API one. Especially if I need to refresh the browser tab.

**Comment by Eankun** [comment]
It seems that the problem was fixed in 34.8.7?
Everything works just fine for me, thank you so much. Shall we close the issue?

**Comment by sinsinpub** [comment]
yea, u could close.
it's not 'everything works'. all the in-game sound settings (volume, hourlines, etc) are not saved & loaded. they are always default values.
