### ISSUE TITLE
ASW power of Basic panel in Chinses shows as ellipsis

### ISSUE THREAD

**Issue by lisongyuan99** [KC3Kai/KC3Kai#3051]
Please make sure that you have these details on hand when submitting your issue/bug report as this will greatly speed up the issue triage process -- thank you!

- Your Chrome version 86.0.4240.193
- win10 2004
- 64bit?
- Your KC3 Kai version 34.9.0
- Which build you have tried running? webstore version 
- Screenshots which accurately paint the issue(s) you are facing.
![屏幕截图(8)](https://user-images.githubusercontent.com/42134107/99648556-20dcdc80-2a8e-11eb-8099-d28275c9287b.png)
![屏幕截图(9)](https://user-images.githubusercontent.com/42134107/99648572-25a19080-2a8e-11eb-8c9f-e0e2147a5a88.png)

**Comment by sinsinpub** [comment]
before the fix released, suggest u change font setting in Chrome:
`chrome://settings/fonts`
![image](https://user-images.githubusercontent.com/160240/99649838-aad97500-2a8f-11eb-9976-147182f65583.png)
`最小字号`改为11（简中默认值应该是12）

**Comment by lisongyuan99** [comment]
It works, thanks
