### ISSUE TITLE
Expedition B2 Requirement Error

### ISSUE THREAD

**Issue by RyuHoshixio** [KC3Kai/KC3Kai#3082]
In this [picture,]
![Capture](https://user-images.githubusercontent.com/77955159/105670364-e6733e00-5f1b-11eb-9f53-945148aaf38b.JPG)
shows that expedition B2 requirements are Firepower, Anti Air and Line of Sight.
But,
![Capture1](https://user-images.githubusercontent.com/77955159/105670449-0a368400-5f1c-11eb-9bce-44d7b1a4a09d.JPG)
I failed the expedition, thus I went up to [https://wikiwiki.jp/kancolle/%E9%81%A0%E5%BE%81](url) and check the exact requirements, 
![Capture2](https://user-images.githubusercontent.com/77955159/105670875-b8dac480-5f1c-11eb-8381-eaa4b12d2afc.JPG)
It has 4 requirements in total, with the one in KC3改 missing the Anti-Submarine>160 requirements.

Thanks you guys for making this amazing extension, keep up the good work.

**Comment by sinsinpub** [comment]
there was a typo in data making asw cond not checked. will be fixed to 160 asw.
but a fact to remind: do not trust stats like asw from any aircraft. let total asw as higher as possible if they have to be used.
(some new implemented exped's asw requirement is intentionally set to +10 higher than wiki's known value

**Comment by RyuHoshixio** [comment]
@sinsinpub I see, thanks for the information. Btw, i found another issue here with quest translation.

![image](https://user-images.githubusercontent.com/77955159/105708418-6b2b7f80-5f4f-11eb-9230-a2d82b1e280a.png)

In english, everything is fine showing the Reiwa mission, but when i switch to Simplified Chinese...

![image](https://user-images.githubusercontent.com/77955159/105708345-4a632a00-5f4f-11eb-833e-b3bcb48cf06b.png)

I dont know if you can read Chinese but I can tell you that even though the Mission code is the same 2102LQ6, the description of the mission was about the winter mission, which you can see the sortie requirement is not the same, as the english one has world 2 to sortie but the Chinese one doesn't have.

Again, thanks for the hard work.

**Comment by sinsinpub** [comment]
unfortunately, there is a long time that nobody updates Chinese translations for both tcn and scn...
quest description incorrect because those quests are reusing ID numbers used in the past
what i can do for now is removing outdated scn texts, let them just shown in English

**Comment by RyuHoshixio** [comment]
> unfortunately, there is a long time that nobody updates Chinese translations for both tcn and scn...
> quest description incorrect because those quests are reusing ID numbers used in the past
> what i can do for now is removing outdated scn texts, let them just shown in English

I see, thank you very much. I will consider doing the translation with my free time, as I love both the game and KC3.
