### ISSUE TITLE
Images in Ship Library are linked to a game server directly

### ISSUE THREAD

**Issue by toshocho** [KC3Kai/KC3Kai#3102]
### Versions:
Chrome: 89.0.4389.90 (Official Build) （64 ビット） (cohort: Stable)
KC3Kai: 35.0.5

### Steps to reproduce:
1. Open 戦闘指揮所 (Strategy Room)
2. Open Ship Library

### Actual behaviour:
Ship images were loaded from a game server directly.

This behavior causes to overload game servers outside game play.
And it might be violating the terms of the agreement
(https://twitter.com/KanColle_STAFF/status/759682230063013888).

### Expected behaviour:
Ship images were loaded from a plugin resource.

### Screenshots (if applicable):
![harusame_direct_link](https://user-images.githubusercontent.com/8425698/112744036-60d14480-8fd7-11eb-8542-d0f43d308b4b.png)

Original Report
- https://i.imgur.com/v2I5qq2.png from [艦これ ツール Wiki 各種ツールへのリンク](https://wikiwiki.jp/kancolletool/toolsfront)

**Comment by sinsinpub** [comment]
nope, I don't think so.
1. these links are the same with your in-game links. so they are cached by browser's file cache system. `overload game server(s)` is not true.
   if they think adding extra requests outside game play to game server is not good, then it's the user's bad who makes clicks around library and ask kc3 making these extra requests. it's the same thing if player browse in-game library every pages.
2. that wiki's editors misunderstood many things. if loading images from game server is not good. `poi`, `EO74` are all doing the same thing (and they have cache system either). but they still think those viewers are safe because they just have no method to inspect and revert the direct links.

**Comment by sinsinpub** [comment]
well, adding another words: All these viewers/tools are placed in grey zone, even without the image links problem. Violating KC official terms or not, is completely explained by Tanaka & staff themselves. Using them is at user's own risk, this is always true.

**Comment by toshocho** [comment]
Thank you for reply.

But I feel disappointment to be tagged type:wontfix.
Cache works almost, but not always.
Any out-game request could not control and predict by the developer.
It might cause interferences with other player's comfortable play, I think.


> 1. these links are the same with your in-game links. so they are cached by browser's file cache system. `overload game server(s)` is not true.

Almost true. But it was false when the game was updated, and players cleared caches.


> then it's the user's bad who makes clicks around library

This is the player's responsibility as you say.
But KC3kai users includes that wiki editors and me might not know that.
So, there has a risk of overloads of game servers unintentionally, I think.


> well, adding another words: All these viewers/tools are placed in grey zone, even without the image links problem.

This is true.
But Japanese tools except of browsers avoid *any* API call or link to game servers. Because it avoids any server load, and takes care for other player's comfort plays.

So almost Japanese tools prepare resources internally within citation use.

**Comment by sinsinpub** [comment]
there is no reason to prepare all game assets 'internally'. even doing this, when game updates, the resources syncing will still impact game server, the same result.
as I said, the Japanese tool `EO74` (七四式電子観測儀) also loads library images from game server, as long as they are updated, without citation use.
and as I said, kc3 never make any API call, never aggressively link image to game server.
kc3 does always take care of player's comfort plays.

**Comment by sinsinpub** [comment]
btw, thank to IP ban of game, the real 'internal' cache tool [KCCacheProxy](https://github.com/Tibowl/KCCacheProxy) should be introduced to you, if the key point is: browser's cache cannot comfort player.
to bypass foreigners ban, and to speed up resources loading, many players not live in Japan have to use it.

**Comment by toshocho** [comment]
Thank you for technical explanations. There was a lack of my understanding.
I understood so close this issue.
