### ISSUE TITLE
screenshot bug

### ISSUE THREAD

**Issue by jackjtr** [KC3Kai/KC3Kai#3134]
### Versions:
Chrome 90.0.4430.212 64bit
Windows 10 ver 18363 64bit
KC3 Kai version 35.1.6 webstore version
Game play mode  Customize DMM Website

### Steps to reproduce:
1. Set browser's zooming to 50%
2. Take screenshot and then you will get picture 1
3. Set browser's zooming to 100%, then resize it to show scrollbar
4. Take screenshot and then you will get picture 2

### Actual behaviour:
got abnormal screenshot since June 17th

### Expected behaviour:
get normal screenshot

### Screenshots (if applicable):
zooming 50%
![2021-06-18 20-46-00 68](https://user-images.githubusercontent.com/6552755/122564141-9be39100-d077-11eb-8cf5-399f8d601dd8.png)

zooming 100%
![2021-06-18 20-51-08 30](https://user-images.githubusercontent.com/6552755/122564184-a3a33580-d077-11eb-8dea-5d123ff644b2.png)

history
![image](https://user-images.githubusercontent.com/6552755/122566132-cafb0200-d079-11eb-99a2-7e713eb736c6.png)

### Error Report (if applicable):
none

**Comment by sinsinpub** [comment]
workaround before fix released:
 * don't zoom page via browser, set game window size via `Game Player Scale` in kc3 settings
 * use 2 legacy modes instead if possible: dmm frame or api mode

**Comment by jackjtr** [comment]
> workaround before fix released:
> 
> * don't zoom page via browser, set game window size via `Game Player Scale` in kc3 settings
> * use 2 legacy modes instead if possible: dmm frame or api mode

After testing these two workarounds, both got screenshots in low image quality  (size changed from 1500*900 to 750*450).
I used to split windows in half so that I can play 2 games (or watch video while playing a game) at the same time, although my laptop is 1080p.
Maybe I have to play it in a maximized browser and kc3 console in a separated window, in order to get screenshots like before.
Hope that the fix will be released soon, because The Spring Event will be ending at June 22th. :)

**Comment by sinsinpub** [comment]
I think u have misunderstood something... ss size change is irrelevant to this issue, it's the same behavior before this.

game's original resolution now is 1200*720, kc3's screenshot function is capturing the page content via chrome api, and cropping to get the actual image what u see. there are 3 factors affecting size: os's monitor scale setting, chrome's page zoom, kc3's player scale. u will get 1500*900 sized image as long as final scale is 125%, no matter which zoom method u use.
btw, to get the original size screenshot, even under non-100% zoom level or partially covered by docked panel, u could always right-click on game screen, then choose 'Save image as...'

**Comment by jackjtr** [comment]
Thanks for the explanation.

Well, I just wanted to say that the resolution changed from 1500**900 to 750**450 when I set DPR=Auto, OS scale=125%, kc3 player size from 100% to 50%, browser zooming from 50% to 100%. 
I think it is probably caused by the factor of kc3 player size 50%, because browser zooming scale rate will not affect the image data size from the canvas. In fact, I can always get 1200**720 sized pictures through the context menu options, no matter how much the browser zooming scale rate is.

> btw, to get the original size screenshot, even under non-100% zoom level or partially covered by docked panel, u could always right-click on game screen, then choose 'Save image as...'

right-click and save as just cannot work for all the situations, such as new coming ship droping or boss battle scenes.
