### ISSUE TITLE
Stuck when access Strategy Room Ships Library page on Linux

### ISSUE THREAD

**Issue by HLM319** [KC3Kai/KC3Kai#3191]
### Versions:

- Your Chrome version: Chromium 98.0.4758.102(also tested on *Chrome 98.0.4758.102* and *Edge 98.0.1108.62*)
- Your OS and its version: Arch Linux 64bit
- Your KC3 Kai version: 35.3.9(*webstore* and *developer build*)

### Steps to reproduce:

- access Strategy Room -> Library -> Ships in any way.

### Actual behaviour:

- The whole extension stucks until reload the extension manually.
- It occurs on a brand new developer build.
- It doesn't occurs every time, but most of the time.

#### Errors that extension page gives(maybe helpless but)

- When double click a character icon on devtools to access the Ships Library page, it gaves errors like:
```
Unchecked runtime.lastError: The message port closed before a response was received.

Context
_generated_background_page.html

Stack Trace
_generated_background_page.html:0 (anonymous function)


Unchecked runtime.lastError: The message port closed before a response was received.

Context
devtools://devtools/bundled/devtools_app.html?remoteBase=https://chrome-devtools-frontend.appspot.com/serve_file/@273bf7ac8c909cde36982d27f66f3c70846a3718/&can_dock=true&dockSide=undocked

Stack Trace
pages/devtools/themes/natsuiro/natsuiro.html:0 (anonymous function)
```

I know that it's probably not a problem of kc3 but of my OS(or settings). But I'm still wondering if I could get some help.

By the way, if there's a critical difference between the Ships Library page and the Equipment Library page implemention that makes one page causes the problem but the other not?

**Comment by HLM319** [comment]
ok, I did some more tests.
The problem seems to be some changes from tag *33.9.5* to *33.10.0* which makes kc3 incompatible with my OS.
At 33.10.0, the extension stucks at the line
https://github.com/KC3Kai/KC3Kai/blob/752abe32158e0b464647b613ec459f7ff63c8f97/src/pages/strategy/tabs/mstship/mstship.js#L493
But at 35.3.9, it stucks at line 44 here
https://github.com/KC3Kai/KC3Kai/blob/ef472d889ae01c9806894ac574ced5f4f07cc16a/src/library/objects/StrategyTab.js#L39-L44
Though I'm not familar with js, it's really makes no sence. So...it's more like an asyn implemention problem than some code problem to me(maybe? idk).

I'll change to some other Linux distro or a brand new Arch Linux to try to find why.
I'll keep this issue open that maybe I can find some workaround.

**Comment by HLM319** [comment]
I found that the browser just stuck when try to load too many images(over around 900) in a page. So I just comment these lines as a workaround.
https://github.com/KC3Kai/KC3Kai/blob/ef472d889ae01c9806894ac574ced5f4f07cc16a/src/pages/strategy/tabs/mstship/mstship.js#L107-L109
It just works fine!

**Comment by sinsinpub** [comment]
Ive no idea if that's the real point causing the issue. but loading too many tiny images of ship library page is a fact, irrelevant to kc3 version, but the more ships implemented by the game

so I added a lazy loading mechanism to the page (will only load current visible 40+ icons)
can u try the `develop` branch and tell me if the issue still there?

**Comment by HLM319** [comment]
@sinsinpub 
Sorry for the late reply.

I've just tried the develop branch. The page works fine for me now. (exactly after 0a41bee62c981d6549d44760854eefc61e26e0ac)

Really appreciate your work.
