### ISSUE TITLE
[Feature] Levelling Tab in Strategy Room

### ISSUE THREAD

**Issue by LostLogia4** [KC3Kai/KC3Kai#326]
![value](https://cloud.githubusercontent.com/assets/12930396/8764567/fd6a2a70-2e15-11e5-9aca-c7f2ed131963.png)

I've already drafted a spreadsheet for mass leveling as shown above (could upload it but too lazy to document it).

Anyway, from the spreadsheet I could draft the required features for leveling calculator:
- Predicted/actual number of sorties and resources. (accumulated when she's the fleet flagship)
- Required amount of EXP to final remodel for all fleet members.
- End result level of non-flagship and flagship/nonflag ratio of 3:1.
- EXP acquisition history. (record grade and flagship EXP)
- EXP, MVP & grade ranking ratio.

(total fuel/ammo) = (base fuel/ammo cost of all fleet member) / 5 * number of sorties + (base ammo cost of all fleet member) / 10 * number of night battle entries
To remodel, say, Souryuu and Hiryuu together, Souryuu as the flagship must have three times of Hiryuu's EXP requirement.

**Comment by dragonjet** [comment]
Ah this is nice :+1: like exp calculator from KCV right? with added features of resource and other efficiency hints

**Comment by LostLogia4** [comment]
Well, indeed. I've never used KCV though, so no idea about its EXP calculator, but that's the draft feature if we're gonna have one in this extension.

**Comment by NicolaosGreene** [comment]
Are there any plans to implement this any time soon?

**Comment by LostLogia4** [comment]
If only I know Javascript, I would...

**Comment by Javran** [comment]
hmm, maybe I can take over this, although busy atm.

**Comment by dragonjet** [comment]
ah same here, can't do much for these weekdays, but the good thing is, the event end, which I've been making as basis for webstore release has again been moved, so that's like additional week for v19 XD who knows maybe we can make it there including this and all the expedition pages :smile:

**Comment by Crazyteitoku** [comment]
@dragonjet I looked at your original planned date for webstore release was event's end. I was like... :scream: .. the amount of documentation awaiting me to address and all might even kill me considering I haven't even finished the event (don't ask, I may have stretched myself a bit too thin). :sweat: I'll try and get some more documentation done when my real life becomes a bit more lax once again. :sweat_smile:

**Comment by LostLogia4** [comment]
Since nobody started working this yet, I'll pull out the formula needed to reduce the workload for this feature:

number of sorties = (remodel EXP - current EXP) / base EXP / flagship modifier / mvp ratio
flagship modifier = 1.5 if yes, 1 if no.
mvp ratio = 2 * (chances of MVP in percentage)

Required fuel = (total base fuel cost) / 5 * number of sorties + (required for repairs)
Required ammo = (total base fuel cost) / 5 * number of sorties + ( number of yasen / 10 )
Required steel and bauxite = (recorded on repair/resupplies)

Needed feature: MVP prediction.

**Comment by dragonjet** [comment]
I forgot to mark this
