### ISSUE TITLE
Stuck at "Waiting for game actions"

### ISSUE THREAD

**Issue by RakaFD** [KC3Kai/KC3Kai#3260]
- Chrome Version : 108.0.5359.72
- Win11
- 64bit?
- KC3 Kai Release 35.6.1

So i tried to login today and it show me this. I've already doing some research to help me solve this, and all of them didn't work at all, a few methods i've already tried is removing cache, disabling site isolation, and forcing cookie hack. Can anyone help me fix this? I didn't know what else to do since i wasn't a tech guy, any help would be appreciated, thanks. 

![Screenshot 2022-12-06 162702](https://user-images.githubusercontent.com/64367362/205875842-bb3e12bd-061f-4541-a83b-37bc7b16e9d9.png)

Error message

![image](https://user-images.githubusercontent.com/64367362/205877188-23085144-18f0-47de-a19d-7e334c65a000.png)

**Comment by Grunilg** [comment]
The game is currently undergoing maintenance.

**Comment by sinsinpub** [comment]
'today' the game is still under maintenance, of course u can't login... u can at least know the maint time schedule from kc3 menu (50+ minutes left until now
![image](https://user-images.githubusercontent.com/160240/205881782-7d3ac87c-c4e7-4397-a362-958dcaa2d572.png)

info u offered not help to diagnose anyway.

**Comment by RakaFD** [comment]
Wow, i didn't notice that, thanks mate!
