### ISSUE TITLE
Strategy Room Dark Theme

### ISSUE THREAD

**Issue by dragonjet** [KC3Kai/KC3Kai#33]
as requested by [echo](http://www.twitch.tv/echoholic)

**Comment by LostLogia4** [comment]
We already have Natsuiro, right? Or are we gonna make a dark "plain" theme?

**Comment by dragonjet** [comment]
ah this one is for the strategy room, not for panel. right now the only UI enhancement branch is `dev-stratmenu` by @Yukinyaa we'll see how that does first then experiment on color schemes after

**Comment by Yukinyaa** [comment]
@dragonjet I'm not working on it D: I thought it was not very convenient
