### ISSUE TITLE
Third LoS Formula, Verify Second Formula

### ISSUE THREAD

**Issue by dragonjet** [KC3Kai/KC3Kai#331]
As reported, we have different value for second formula,

and there a new third formula we haven't implemented

**Comment by LostLogia4** [comment]
Do we even have the slightest reference for the third formula?

**Comment by dragonjet** [comment]
https://github.com/andanteyk/ElectronicObserver/blob/master/ElectronicObserver/Utility/Data/Calculator.cs#L243

seems

`dive x 0.6 + torp x 0.8.....`

**Comment by c933103** [comment]
this formula is called 2-5 (Fall)(Simplified)

**Comment by dragonjet** [comment]
ah for this, unless requested by the community, will leave it as it is xD

**Comment by c933103** [comment]
Relevant raw Japanese document: http://jbbs.shitaraba.net/bbs/lite/read.cgi/netgame/13745/1400461230/420

**Comment by dragonjet** [comment]
formula 33 has been implemented in 30.1.1
PR: https://github.com/KC3Kai/KC3Kai/pull/1352
Release: https://github.com/KC3Kai/KC3Kai/pull/1355
