### ISSUE TITLE
Real time morale indicator

### ISSUE THREAD

**Issue by URSvAir14** [KC3Kai/KC3Kai#337]
Is it possible to have a morale indicator work in real time? This way it'd make it much easier to know when you should be able to go for another sortie when you're farming or grinding (ie, 2-3, 3-2a etc). 

The server increments morale by 3 points for every 3 minutes in the game, so for any hour (calling it x for simplicity) it will increment it at:
x:00
x:03
x:06
x:09
...
x:51
x:54
x:57
This pattern works for my main account and my spare account, and I'm fairly sure this is the general pattern despite never reading this on Himeuta or on the wiki.

To implement the feature you could set up a timer whenever you appear at the main screen and set it to the time until the next morale increment (so at x:03:56 you set the timer to 0:02:04). When the timer has elapsed, you increment morale and then set the timer for 3 minutes. 

I would add this feature myself, but I don't know web programming that well.

**Comment by dragonjet** [comment]
*KanColle Viewer has a built in feature that gives you the timer until when your fatigue is fully restored. This timer can be set to a custom morale number instead of the standard 40 (i.e. 15 or 47) and it will ring an alarm telling you your ship hit that fatigue/morale level. Would be nice if this could be implemented at least for the first fleet.* - @SanaNoHana

**Comment by SanaNoHana** [comment]
I'm also confused on how the morale timer works in game. It just has several numbers on the bottom of the panel that doesn't make any clear indications on whose fatigue needs to recover.

I think what would be cool is that the circle that tells us the ship's fatigue value have like a counter meter. Like there's a green circle timer around the fatigue number and when every three minutes pass the fatigue goes down.

**Comment by dragonjet** [comment]
yea, I'm also visualizing a "clock"-like animation that completes the rotation every 3 minutes. But our timing will not be 100% accurate. What we can do is just start the timer when we receive the morale value

**Comment by c933103** [comment]
logbook included a timer for next morale increment time in its main interface, and claim the time could shift +/-8s but sometime i encountered a drift more than that.

p.s. i don't know how it exactly work, but if it is following server time, it should use a implementation which would work when 1. local time is not accurate or 2. when user is in a timezone like UTC+7:20 where the time offset from server time is not diviable by 3
