### ISSUE TITLE
Auto response to fleet changes option

### ISSUE THREAD

**Issue by LostLogia4** [KC3Kai/KC3Kai#345]
Basically the displayed fleet in Admiral Panel automatically changes to displays the fleet the any of the fleet member or their equipment is changed.
For example, if you're changing an equip for your secretary ship while viewing the 4th fleet in the panel, the fleet will be changed to view the 1st fleet.

**Comment by bcc32** [comment]
What happens when you swap a ship in fleet 1 with a ship in fleet 2?

**Comment by dragonjet** [comment]
@bcc32 true. probably we focus on the fleet where the source ship is. So if you click from 2nd fleet to switch for someone on 4th fleet, we focus on 2nd fleet, coz in-game, by that time you're on the 2nd fleet.

**Comment by LostLogia4** [comment]
Uh, it didn't change? Or it simply show the Fleet 2 briefly.

**Comment by LostLogia4** [comment]
Didn't even know why I closed this issue...

**Comment by dragonjet** [comment]
toplel I was surprised as well :v
