### ISSUE TITLE
Quest Progress Display Bug

### ISSUE THREAD

**Issue by ethrundr** [KC3Kai/KC3Kai#418]
On the Bw1 quest (Sortie 36x, Encounter 24 bosses, Win vs 12 bosses, 6 S-ranks13/36) it only shows the progress of the first milestone, which is 36 sorties, while the rests can't be seen. This happens on the flowchart as well as on the panel. Following screenshots was taken from the Strategy Room and Admiral Panel Home:
![screen shot 2015-07-27 at 23 45 17](https://cloud.githubusercontent.com/assets/13522800/8908910/9c3de4a8-34b9-11e5-9a0d-36a65bec5ab7.png)
![screen shot 2015-07-27 at 23 45 25](https://cloud.githubusercontent.com/assets/13522800/8908914/9eee3c7a-34b9-11e5-8d65-acf93d9fb888.png)

However, while on the Battle Mode, hovering the mouse over will bring all the details correctly:
![screen shot 2015-07-28 at 00 06 51](https://cloud.githubusercontent.com/assets/13522800/8914395/045a64c4-34da-11e5-85be-34a32d84340c.png)

Also, some quests also still not updated by the time we're going back to the Port. So far that I've seen: Bw2, Bw3. It'll just being updated when reaching 50% mark and 80% mark by re-accessing the quest page, and I do believe that this is not how the Quest Tracker should be.

**Comment by bamboo3250** [comment]
Could you re-check Bw2 and Bw3? I think it should have worked correctly by now.

**Comment by ethrundr** [comment]
ok, gonna recheck them today, since it's monday already.

**Comment by dragonjet** [comment]
we tried that before, but the space really is the problem xD

**Comment by ethrundr** [comment]
how about if we shrink the font by one or two points?
a bit little is not a problem in my opinion, as long as still readable~

**Comment by dragonjet** [comment]
still 4 requirements too long for that small box XD

**Comment by ethrundr** [comment]
well then the only option left is to enable the hover, which will reveal the complete data :D

**Comment by Crazyteitoku** [comment]
The issue has long been addressed to with the quest tracker now able to more accurately track and reset quests (from its panel) as well as the ability to highlight completed quests.

Closing this, if need be we can re-open it again.
