### ISSUE TITLE
Combined Fleet Graphical Glitch

### ISSUE THREAD

**Issue by ethrundr** [KC3Kai/KC3Kai#471]
Just trying opening the vertical, and entering the combined fleet mode, and this what I got on 300px setting:
![screen shot 2015-08-04 at 05 51 39](https://cloud.githubusercontent.com/assets/13522800/9047555/b8dee77e-3a6d-11e5-8791-fd8a5035d483.png)
There's a text overlaying with the Main fleet's flagship.

Also, when switching from vertical to horizontal while in the Combined Fleet mode, this what I got:
![screen shot 2015-08-04 at 05 54 38](https://cloud.githubusercontent.com/assets/13522800/9047557/ba502bfe-3a6d-11e5-960d-209d443ed411.png)
My suggestion is to add the switch button on horizontal mode as well, to prevent this glitch from happening, and user can simply switch back to the single fleet mode while in horizontal without need to switch back to vertical first, although it'll be fixed on the next sortie/pvp.

**Comment by dragonjet** [comment]
ah this is known, the horizontal truly is not yet complete, and those two boxes are outlines from the design stage, which were not implemented up to this day :laughing:
