### ISSUE TITLE
Red circles on resource node in Horizontal mode

### ISSUE THREAD

**Issue by LostLogia4** [KC3Kai/KC3Kai#483]
Not sure if this was intended but in v13.2 it seems like all nodes (tested both resource and empty nodes) are indicated by red color regardless if it's a battle node or not.

Update: Apparently happens only in horizontal mode.

**Comment by bamboo3250** [comment]
Actually, it was only red nodes in Horizontal layout from the start. When I worked on Vertical Layout, I added more color to it but still kept Horizontal layout unchanged. So now only Vertical has colorful nodes while Horizontal does not. It was intended.

**Comment by LostLogia4** [comment]
Oh, okay. When would the colored nodes be implemented in horizontal layout as well?

**Comment by dragonjet** [comment]
probably, so let's keep this entry open xD

**Comment by bamboo3250** [comment]
Yeah, I would like to keep it like that for a little longer to see how it goes xD

**Comment by dragonjet** [comment]
Legacy theme not supported, natsuiro theme has colored nodes on both orientations
