### ISSUE TITLE
[Enhancement] Translation Quest B22

### ISSUE THREAD

**Issue by McDohl** [KC3Kai/KC3Kai#487]
I think we need to update B22 quest details. After Abukuma Kai Ni and 3-2 recent changes now you can use CL as flagship too
![682e7967d65574d395cfe357786de2ad](https://cloud.githubusercontent.com/assets/13024936/9082074/1c0cec0c-3b94-11e5-9db6-d736d2cf1bda.png)

meanwhile our translation (taken from english translation): 
"244": {
        "name": "Deploy the Destroyer Division 30 (Gen-1)",
        "desc": "Deploy a fleet that consists of Mutsuki (\u7766\u6708), Kisaragi (\u5982\u6708), Yayoi (\u5f25\u751f), Mochizuki (\u671b\u6708) and up to 2 additional DDs to world 3-2 and encounter the boss. C rank or above is required."
    },

**Comment by dragonjet** [comment]
hmmm. are the two additional destroyers actually requirement of just hint or the wikia writer to remind readers that only DDs can sortie to it?

we'd have to base it on the in-game JP description

**Comment by nicky008** [comment]
From Wikiwiki, it is already updated...

"「第三十駆逐隊(一次)」の4隻（「睦月」「如月」「弥生」「望月」）+他に軽巡洋艦（旗艦）・駆逐艦がいてもOK"

"Having four ships of the Destroyer Division 30 (Gen-1) (Mutsuki, Kisaragi, Yayoi, Mochizuki), plus other one (flagship) light cruiser and one destroyer are OK"

**Comment by dragonjet** [comment]
imho we should still follow in-game description rather than base it on community advice. We do offer on-screen translation and its best to translate raw.

though really, I'm haven't really done any translation to know what is acceptable mainstream, so I might be in the wrong there.

**Comment by nicky008** [comment]
I personally agree with you, @dragonjet, too. But if the mainstream (especially the foreign ttks) is say "yes" to change it, then we need to do.

**Comment by McDohl** [comment]
gonna close this
