### ISSUE TITLE
Screenshot issues

### ISSUE THREAD

**Issue by aikamiteitoku** [KC3Kai/KC3Kai#49]
Screenshots don't work at all when you are playing on the actual DMM site, neither tab nor download.
It does work when you are playing via "DMM frame" or "API Link", except that it doesn't actually make a screenshot of the game itself, instead it seems to be a screenshot of the upper left corner of the browser that's also really zoomed in. 
![1430932740_4](https://cloud.githubusercontent.com/assets/12278840/7499373/6ec59db8-f427-11e4-8102-608e89631c39.jpg)
I have the KC3 Kai panel at the horizontally at the bottom of the screen btw. Although I tried putting the panel vertically, it still just makes a zoomed in screenshot of the upper left corner.
I'm also on OSX/Mac and on the Kanoya Airfield server, if this helps.

Oh and I had that issue since the old KC3 by the way

**Comment by dragonjet** [comment]
hm this is a weird bug, must be connected to OS. I'll need to gather more info from other Mac users if they have the same problem

question though, what version of Chrome are you using?

thanks for reporting~

**Comment by aikamiteitoku** [comment]
Version 42.0.2311.135 (64-bit), it's up to date it says

**Comment by nevrending** [comment]
I'm on OSX 10.10.3 , same version of Chrome ( 42.0.2311.135 (64-bit) )
Tried putting the panel horizontally and vertically but I can't reproduce @aikamiteitoku 's issue
What version of OSX are you using @aikamiteitoku ?

**Comment by aikamiteitoku** [comment]
I'm also on OSX 10.10.3, it's a Macbook Pro with 13-inch retina display

**Comment by razgriz1412** [comment]
I also have this issue since previous version of KC3kai, both horizontally and vertically.
I'm on OSX 10.10.3, MacbookPro 13" Retina 2013, Chrome Version 44.0.2403.89 beta (64-bit).

**Comment by ethrundr** [comment]
I also have the same issue here. The screenshot button not work after the DMM Frame feature "closed" and "moved" to direct DMM Website play.
I'm on OSX 10.9.5, Chrome version 44.0.2403.107 (64-bit), MacbookPro 15" (Mid 2012)

**Comment by dragonjet** [comment]
@ethrundr ah yes, when the DMM gameplay moved to direct website, unfortunately screenshot will not work there. Only API links have screenshot atm

**Comment by ethrundr** [comment]
@dragonjet is it possible to make the screenshot feature works on the DMM direct gameplay in future? Since it's really sucks to do snip each time I want to take screenshot, and I definitely won't playing over the API link.

**Comment by dragonjet** [comment]
hm yes it's possible in the future, though we'll need to make a new issue for it, this one is for the wrong cropping of the screenshots xD

**Comment by ethrundr** [comment]
let me open new one then~

**Comment by Crazyteitoku** [comment]
Seems like the same issue is now affecting windows users but with version 18.1:
![](http://i.imgur.com/qL2lVqQ.png)

[More information on bug report here] (http://kancolle.wikia.com/wiki/User_blog_comment:Dragonjet/KC3%E6%94%B9/@comment-89.245.3.253-20150907170054?permalink=328610#comm-328610)

**Comment by NicolaosGreene** [comment]
I do wonder what causes this bug, anything I can do to help find information since it is effecting me as well?
