### ISSUE TITLE
Weird Bugs

### ISSUE THREAD

**Issue by SanaNoHana** [KC3Kai/KC3Kai#490]
http://i.imgur.com/zulsFio.png

The name of KC3 Kai is all fucked up.

Also the error on the bottom. I don't know how to get rid of it, it doesn't affect gameplay in any way, but it pops out every time I open a new KC3 Kai Interface.

**Comment by ethrundr** [comment]
It has been reported in #474 and has been solved

**Comment by SanaNoHana** [comment]
What about the bottom error? Is it a part of the issue?

**Comment by SanaNoHana** [comment]
Also DD can you add my Himueta Profile to contribution page? Its the same username is my GitHub account.

**Comment by dragonjet** [comment]
the yellow warning in the console cannot be avoided. it is not harmful though. My advice is to close that box by pressing the button between the :warning: 1 and the *cog icon*

will add your himeuta link
