### ISSUE TITLE
Region Cookie Autoscanner not working?

### ISSUE THREAD

**Issue by SanaNoHana** [KC3Kai/KC3Kai#496]
I read the patch notes and tried to enter the DMM site for KanColle and Kanpani Girls. Neither works, and I keep getting the region error screen. Am I doing anything wrong?

**Comment by SanaNoHana** [comment]
Nevermind. I got it to work.

However, I keep running into the same problem with Kanpani girls with your other cookie app. I can get to the game page, but it stalls and never loads or loads all broken assets. The only way around this is to use a VPN. I have no idea what it could be...

**Comment by c933103** [comment]
something like https://github.com/yuyuvn/KanColleViewer/pull/67 would probably help in kancolle side

**Comment by dragonjet** [comment]
which other cookie app? :o If you meant the EditThisCookie, it is recommended to turn it off if you're already using this. Otherwise, it's not just DMM vs KC3改, but the other extension will join in with unexpected results XD
