### ISSUE TITLE
Outdated Webstore Preview

### ISSUE THREAD

**Issue by LostLogia4** [KC3Kai/KC3Kai#499]
No, seriously. How long is the preview pics has gone unupdated? The layout and design has changed a whole lot since v10.

**Comment by ethrundr** [comment]
And I just wanted to post issue about this.....
As far as I remembered, it was screenshot from around v8 or v9, am I right?

**Comment by dragonjet** [comment]
iirc the previews are from v1 :laughing: 

right now I have no plans to update it, since even now it already has errors on the webstore dashboard xD

![ss 2015-08-07 at 12 56 18](https://cloud.githubusercontent.com/assets/557312/9128973/d4296322-3d03-11e5-9382-9f4968e2dc08.png)

**Comment by ethrundr** [comment]
@dragonjet XD that error
well, errors aside, having up-to-date images of the extension is a must, at least the v10 screenshots....

**Comment by dragonjet** [comment]
yep, keeping this entry open until I upload new ones xD

**Comment by ethrundr** [comment]
@dragonjet and, when will it be? XD

**Comment by dragonjet** [comment]
when I get my first UR on SIF :3

**Comment by ethrundr** [comment]
@dragonjet so it's seems the answer is nearly never :s

**Comment by ReiFan49** [comment]
![cbmamsauiae78sw](https://cloud.githubusercontent.com/assets/9847780/9150531/b3609bf6-3e07-11e5-8d6d-636fbcc1dbbe.jpg)
gonna supporting you from behind, for those hopes

**Comment by nicky008** [comment]
Just SR is still so hard for mine... don't need to say more about UR. :<

**Comment by ethrundr** [comment]
by the way, why this thread turns to be LL thread :laughing:

**Comment by dragonjet** [comment]
still aint got my UR

**Comment by dragonjet** [comment]
https://chrome.google.com/webstore/detail/kancolle-command-center-%E6%94%B9/hkgmldnainaglpjngpajnnjfhpdjkohh
