### ISSUE TITLE
Cleared Map Bar

### ISSUE THREAD

**Issue by ethrundr** [KC3Kai/KC3Kai#516]
I think the map bar on cleared map should be greyed out, not stay green as it is now:
![screen shot 2015-08-08 at 15 02 27](https://cloud.githubusercontent.com/assets/13522800/9149308/a45ae98c-3dde-11e5-913a-2a51abe88a40.png)

**Comment by dragonjet** [comment]
Legacy theme not supported anymore.
Bar is grayed out on Natsuiro theme
