### ISSUE TITLE
Scrap equipment still on Strategy Room

### ISSUE THREAD

**Issue by dragonjet** [KC3Kai/KC3Kai#534]
_Is it just me or in new version when scrap equipment, equipment list in strategy room not updated.  Refreshing strategy room will not updated, refreshing the game will update it tough._ - [Tsusai](http://kancolle.wikia.com/wiki/User_blog_comment:Dragonjet/KC3%E6%94%B9/@comment-Tsusai-20150806155149?permalink=294778#comm-294778)

**Comment by LostLogia4** [comment]
Is thus bug still prevalent...?

**Comment by Nya-chan** [comment]
This doesn't seem to happen anymore - tested it by scrapping 12.7 gun, after refreshing the strategy room the equipment count got lowered.

**Comment by Javran** [comment]
@Nya-chan did you test it without refreshing the game? if so then we can consider this problem being solved.

**Comment by sinsinpub** [comment]
...I think I had it fixed long time ago by just add `KC3GearManager.save()` :joy:
could close this for now.

**Comment by Nya-chan** [comment]
@Javran Yes, the only thing I did in the game was scrapping the gun and then I worked with Strategy room only, I didn't even leave the equipment tab.

**Comment by Javran** [comment]
@Nya-chan great then, so that's everything settled with this issue.
