### ISSUE TITLE
[Discussion] Keep track of Node Letters

### ISSUE THREAD

**Issue by bamboo3250** [KC3Kai/KC3Kai#540]
This thread is mainly for keeping track of Node Letter feature.  Anyone wants to contribute can post the finding here or in @Javran 's file https://gist.github.com/Javran/c5c7bf8d40524559b7d9

World 1-1: 3/3 :white_check_mark: 
World 1-2: 4/4 :white_check_mark: 
World 1-3: 9/9 :white_check_mark:
World 1-4: 13/13 :white_check_mark:
World 1-5: 10/10 :white_check_mark: 
World 1-6: 17/17 :white_check_mark: 

World 2-1: 6/6 :white_check_mark: 
World 2-2: 8/8 :white_check_mark: 
World 2-3: 12/12 :white_check_mark: 
World 2-4: 19/19 :white_check_mark: 
World 2-5: 15/15 :white_check_mark: 

World 3-1: 6/6 :white_check_mark: 
World 3-2: 10/10 :white_check_mark: 
World 3-3: 13/13 :white_check_mark: 
World 3-4: 20/20 :white_check_mark: 
World 3-5: 15/15 :white_check_mark: 

World 4-1: 12/12 :white_check_mark: 
World 4-2: 13/13 :white_check_mark: 
World 4-3: 21/21 :white_check_mark: 
World 4-4: 14/14 :white_check_mark: 
World 4-5: 14/19 :black_medium_square: (`A->C`, `G->F`, `F<->I`, `H->K` and `J->L` are unknown)

World 5-1: 12/12 :white_check_mark: 
World 5-2: 12/14 :black_medium_square: (`G -> H` and `I->J` are unknown)
World 5-3: 14/14 :white_check_mark: 
World 5-4: 17/20 :black_medium_square: (`C->G`, `G->I` and `L->M` are unknown)
World 5-5: 11/18 :black_medium_square: (`B->K`, `K->M`, `K->J`, `J->I`, `I<->G`, `G->H` and `I->H` are unknown)

World 6-1: 13/13 :white_check_mark: 
World 6-2: 18/18 :white_check_mark: 
World 6-3: 12/12 :white_check_mark: 

**Summer 2015**
E1: 10/10 :white_check_mark: 
E2: 14/17 :black_medium_square: (`B->K`, `H->L` and `J->L` are unknown)
E3: 14/17 :black_medium_square:
E4: 15/18 :black_medium_square:
E5: 13/18 :black_medium_square:
E6: 15/23 :black_medium_square:
E7: 22/26 :black_medium_square:

**Fall 2015**
E1: 14/14 :white_check_mark: 
E2: 17/17 :white_check_mark: 
E3: 13/13 :white_check_mark: 
E4: 19/19 :white_check_mark: 
E5: 14/19 :black_medium_square:

**Comment by NicolaosGreene** [comment]
I'll start trying to remember to add more of mine as I do these

**Comment by bamboo3250** [comment]
@NicolaosGreene thanks a lot :laughing:

**Comment by NicolaosGreene** [comment]
Is there a way to move between E and I on 2-3? I have never seen that happen so I think there are only twelve routes so I might be wrong.

**Comment by bamboo3250** [comment]
I also doubt that. But since it's shown as a route, there may be a composition that can go through that route. We cannot eliminate that possibility unless the KanColle dev say so.

**Comment by NicolaosGreene** [comment]
Fair enough, heck maybe the new oiler will be able to go though there.

**Comment by NicolaosGreene** [comment]
getting all of 5-5 mapped would be a terror >< I hate that place and the other routes are worse than the main one.

**Comment by bamboo3250** [comment]
ikr :smile:  let's complete easy maps first, since the easier the map is, the more players will likely run through that map.

**Comment by NicolaosGreene** [comment]
Added some routes on 4-4 and 5-2

**Comment by c933103** [comment]
https://myfleet.moe/entire/sta/drop_stage this site include map-number-probability-nodeposition-droprate stat.

**Comment by bamboo3250** [comment]
Updated map 4-4 and 5-2 #544

**Comment by NicolaosGreene** [comment]
@c933103 We are looking at the association between path ids and node letters. That site does not list path ids which is the data we can extract with KC3Kai. Therefore, we need users to submit which path ids go with which nodes.

**Comment by c933103** [comment]
@NicolaosGreene it does. just click the 羅針盤for each eamap, and then click on each edge to edge row to show path

**Comment by Javran** [comment]
I also suspect there is no route between I and E for 2-3, and in the `api_start2` response you can actually guess this:

If you search `start2` in network dev page,

![2015-08-09_131614_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/9156001/de2fd1a8-3e98-11e5-80cb-60b3b3c68079.png)

Copy everything after `svdata=` and paste it to any JSON visualizer like [this](http://jsonviewer.stack.hu/)

And go to `api_data.api_mst_mapcell`:

![2015-08-09_131923_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/9156014/4c749a36-3e99-11e5-9ee3-e2633fe41187.png)

I guess elements in `api_mst_mapcell` are route ids, and each element has a `api_map_no` which I suspect is the map. So element 0~3 are for map 1-1 as shown above, 4 elements in total while there are 3 actually routes.

For map 1-2, there are actually 4 routes, and 4~8 in `api_data.api_mst_mapcell` are for map 1-2, so 5 elements:

![2015-08-09_132315_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/9156034/ff0644ce-3e99-11e5-831c-cc4b8d7c616f.png)

My observation is that there are `n+1` elements for a map that has `n` routes.
If you keep doing this, you'll find map 2-3 has only 13 elements, 49~61 in `api_mst_mapcell`:

![2015-08-09_132946_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/9156049/bf1566aa-3e9a-11e5-9b7f-a0c33a8d8c78.png)

This could be one way to verify how many routes are there in a map.

**Comment by bamboo3250** [comment]
oh wait, the page @c933103 gave us just now really can show the relationship between edges and nodes. I will spend tonight to investigate it. If it correctly shows us what we need, I can complete the table before v16 release tomorrow :open_mouth:

**Comment by bamboo3250** [comment]
@Javran I never thought about finding the node/route information there. If the API data says so, then we can conclude that there is no route between I and E. It could be that KanColle dev shows a "route" there to troll us :joy:

**Comment by ethrundr** [comment]
oh god, like to join, but cannot online for the next two days due to RL issues :cry:

**Comment by NicolaosGreene** [comment]
@c933103 I never knew that part existed on there. Sorry for that.

**Comment by bamboo3250** [comment]
I have completed all maps, except for 4-5, 5-4 and 5-5. You guys can find unknown routes in the first post. Those are mystery we have to find out now. 

And try to check with Wikia notation while doing sortie at other maps as well. 

PS: Before I thought Wikia just randomly assigned letters to the nodes but now it seems that is not the case. Wikia and https://myfleet.moe/entire/sta/drop_stage seem to be perfectly in sync with each other.

**Comment by c933103** [comment]
...i believe node letters are written on the map, at least it is the case for 1-6 that i have just visit (except node N)

**Comment by bamboo3250** [comment]
That's not true for early maps such as 1-1, 1-2, ... or 2-3. Only recent maps (1-6 or event maps) have letters written on in-game map.

**Comment by NicolaosGreene** [comment]
Figures that the 5-5 drum route would not be on there, that one is very unpleasant. The 5-4 one doesn't look too bad, it's just the less efficient route on one side and some RNG on the other. 5-2 is more at the mercy of the RNG to get those paths. The ones on 4-5 are not too bad but they will need some luck for I->F The rest should be strait forward though

**Comment by nicky008** [comment]
5-5 is really the most unfriendly testing ground...

**Comment by NicolaosGreene** [comment]
Indeed

**Comment by bamboo3250** [comment]
Update E1 and E2

**Comment by dragonjet** [comment]
wow who finished e3?

**Comment by bamboo3250** [comment]
Not me, I just finished E1 Hard, Agano last hit :grin: 

![screen shot 2015-08-11 at 9 18 23 am](https://cloud.githubusercontent.com/assets/8078323/9188070/776f6e42-400a-11e5-854e-2f51f20bd83d.png)

**Comment by dragonjet** [comment]
is that on dev build? xD
last I checked the HP gauge is `undefined` something lol
I'm just on my first kill E-1
not using any buckets so it will take me a very very long while

**Comment by bamboo3250** [comment]
yes, I fixed it last night on the commit https://github.com/bamboo3250/KC3Kai/commit/681fea8e9008063a9893e95ac3678e33868aab05

Every full boss kill will deduct the bar by 150 HP :kissing_closed_eyes:

**Comment by nicky008** [comment]
Last dance with 190 HP... :laughing: 

New abyssal DD (2nd and 3rd position on @bamboo3250's above pic) is really a bit trolling.

**Comment by bamboo3250** [comment]
True, especially for shelling phase. I failed to kill the boss on the last dance many times mostly because the shelling phase in the day battle taiha'ed 3-4 my DDs :sob:

**Comment by bamboo3250** [comment]
Update E4, E5 and E6

**Comment by bamboo3250** [comment]
Update E5, E6 and E7 in #632

**Comment by Crazyteitoku** [comment]
I was thinking of opening up an issue with this case as a bug report (and reference it to this issue number) but thought there might not be of a such a need.

Flonnaru (via kancolle.wikia) mentioned a bug with how unresolved node numbers shows up on the panel as undefined:
![](http://i.imgur.com/1mKHUJ5.png)

For reference Flonnaru was sortieing 5-4 and encountered the issue whereby the name of the map is displayed in two lines (as opposed to one) and with the second line being obscured by other information in place.

Perhaps an idea would be for unresolved node letters is to mark them as "?" somehow as a stopgap measure until all the node letters becomes known? It might be a way to:
*Prevent bug reports with cases like these (with map name spread across two lines).
*At least somehow keep the map and node name as a single line or something.

Just a thought based on the minor bug report. :laughing:

**Comment by bamboo3250** [comment]
@Crazyteitoku That "undefined" is the difficulty of the map, which is not available in normal map (in this case, it is map 5-4). It's not related to the node letters and has been solved in the latest github version.

**Comment by Crazyteitoku** [comment]
@bamboo3250 oh crap! my bad. I thought that was to do with node numbers. Thanks. :persevere:

**Comment by dragonjet** [comment]
wait is that undefined as of latest pull? that was fixed already

**Comment by Crazyteitoku** [comment]
@dragonjet no, that "bug report" came from Flonnaru so chances are he is using the webstore version which would have that bug. I don't have a chance to try it out because I haven't even gotten world 5 unlocked.

It looks like Flonnaru will be keen on checking out this upcoming release once it is out. :smile:

**Comment by dragonjet** [comment]
:+1:

**Comment by ReiFan49** [comment]
recently i found out E-5 have untracked one, which is no.17
but don't have the node movement record, because they reported it to me **after finished the cosplay** and the laptop have battery leak....

i'll update the data with the fleet&equip composition

**Comment by ReiFan49** [comment]
updated 1 node of salmon run

**Comment by ReiFan49** [comment]
retracking this issue again?

**Comment by bamboo3250** [comment]
@ReiFan49 I think you can just commit and push. I will update the first post later when have more time.

**Comment by bamboo3250** [comment]
Updated Node Letter for this season event via #1048

**Comment by McDohl** [comment]
@bamboo3250 H to I = 10
![image](https://cloud.githubusercontent.com/assets/13024936/11312840/58282afa-900b-11e5-8190-e3f72632a90b.png)

**Comment by bamboo3250** [comment]
@McDohl thanks, updated route H to J via ac7f53b64fcd975549db1ce01b167fbaa778ed7c.

**Comment by bamboo3250** [comment]
btw, did you go through J to K @McDohl ?

**Comment by McDohl** [comment]
ah, I not do that, I can test it for you

**Comment by McDohl** [comment]
J to K = 19
![image](https://cloud.githubusercontent.com/assets/13024936/11313708/90233c14-9011-11e5-95e6-da2704150308.png)

**Comment by bamboo3250** [comment]
thanks, now E4 is done :+1:

**Comment by ethrundr** [comment]
@bamboo3250 want me to test out E5?
I can do that while debuffing

**Comment by ethrundr** [comment]
For E5:
A-B: 2
B-E: 5
E-H: 8

Sorry can't give a screenshot, forgot to do it :laughing:

**Comment by bamboo3250** [comment]
@ethrundr great! Added those nodes in ce800b571feb5fa995d22f42c3b045e4d4642448 :+1:

**Comment by ethrundr** [comment]
I'll update for C-F, F-I and I-J later on after I cleared the map :laughing:

**Comment by ethrundr** [comment]
I think we need not to continue track for the Fall event, as it'll end by tomorrow, right?
@bamboo3250

**Comment by bamboo3250** [comment]
True, there is no update from KC3Kai between today and tmr so eventually nobody will see those updated node letters. We can conclude the Fall event here :laughing:

**Comment by Javran** [comment]
solved by #1668
