### ISSUE TITLE
Translate API Gameplay Page

### ISSUE THREAD

**Issue by Yukinyaa** [KC3Kai/KC3Kai#551]
Many non-english Korean users are having hard time.
<a href="http://m.dcinside.com/view.php?id=kancolle&no=2481861&page=1&serVal=Kc3&s_type=all&ser_pos=">this user</a> think element tab is KC3 viewer.

Also, korean users use term "Token Link" instead of "API link" so they are pritty confused.

Sorry for bad english tho

**Comment by Yukinyaa** [comment]
html itself with language button could solve it

**Comment by dragonjet** [comment]
hm, sorry, not sure what you meant by "html itself with language button"?

**Comment by Yukinyaa** [comment]
ㄴ like this : <img src="http://www.nsteam.org/tutorial/tutorial_language.png">

**Comment by Yukinyaa** [comment]
Could more easy to make then adding all those lines to translation file

**Comment by dragonjet** [comment]
oh I see what you mean. thanks. though will probably only after event

**Comment by Yukinyaa** [comment]
had browsed through source, but just adding translation file will be good.

**Comment by ReiFan49** [comment]
well, as the [Token toggle disabled] is translate-able, why not for the whole page?
looks fun to make it happen.

**Comment by ReiFan49** [comment]
bumping this after #825
