### ISSUE TITLE
Add number of starting gears for new ships in defeq.json

### ISSUE THREAD

**Issue by bamboo3250** [KC3Kai/KC3Kai#557]
422 Teruzuki
443 Libeccio
451 Mizuho
453 Kazagumo
458 Umikaze
459 Kawakaze
460 Hayasui

**Comment by Javran** [comment]
I guess we can now use data from WhoCallsTheFleet and eventually get rid of `defeq.json`

**Comment by sinsinpub** [comment]
...i notice default equip slots count (`defeq.json`) is not used so frequently, just for refreshing the gear count on panel when new ship drops... and after backing to home port, the gear count will be fixed despite of `defeq` data missing. i guess few ppl switch to basic tab during sortieing to see how many gears they have gained 😓

**Comment by Javran** [comment]
closeing because we are now using WhoCallsTheFleetDb as an alternative to this.
