### ISSUE TITLE
[Suggestion]Window Size Modification

### ISSUE THREAD

**Issue by Yukinyaa** [KC3Kai/KC3Kai#560]
![image](https://cloud.githubusercontent.com/assets/10284996/9175975/8977515a-3fc3-11e5-8805-edad65c32bf5.png)
had to use other plugin to fit window size to game window

think this operation could be added to KC3.
(Well, It's something convenient :p)

**Comment by dragonjet** [comment]
hmm

perhaps something like `Settings` > `API Game Screen` > `Game Player Scale` could suffice?

**Comment by Yukinyaa** [comment]
"Game Player Scale" only  changes game flash's size.
What I'm trying to say is, that by some method, Changing window viewport's size to fit the game screen

**Comment by LostLogia4** [comment]
iinm this feature already been implemented?
Feel free to reopen it if it wasn't fully implemented.
