### ISSUE TITLE
[Suggestion] Add EXP Acquired in Sortie History.

### ISSUE THREAD

**Issue by LostLogia4** [KC3Kai/KC3Kai#572]
With the advent of variable EXPs, it'll help tremendously for our leveling attempts if we could track the base EXP per node.

Additionally, we should keep track of the MVP-er is we were to implement the EXP calculator.

**Comment by ReiFan49** [comment]
this is happened in 1-6 too right?

**Comment by ReiFan49** [comment]
![image](https://cloud.githubusercontent.com/assets/9847780/9673889/cc927cbc-52d3-11e5-8859-c3ce2f4ce17c.png)
_(:3

**Comment by LostLogia4** [comment]
Already fulfilled, closing.
