### ISSUE TITLE
D11 shows the wrong count

### ISSUE THREAD

**Issue by NicolaosGreene** [KC3Kai/KC3Kai#579]
D11 calls for a total of 7 runs of expedition 37 or 38 in a week which includes the one that you previously did for D9. Therefore, the counter for this quest should start on 1/7 rather than 0/7 since the program uses the 50% and 80% markers to auto-correct itself.

**Comment by ReiFan49** [comment]
now it recalls me back, pre-event mode, spam exped 38 with 1SS 5DD,
one two three *recorrect!* four five six sven.

did you actually mean.. "shares the same counter" ?

**Comment by NicolaosGreene** [comment]
Effectively it shares the same counter, yes.

**Comment by NicolaosGreene** [comment]
They way the game handles it internally seems to imply that it is a 7 counter that was incremented by 1 by D9. At least based on what the 50% and 80% markers show.

**Comment by dragonjet** [comment]
oh my, I read the thread multiple times I wasn't able to follow. was it that our counting is wrong or is there another in-game bug that counts two quests at the same time even only one of them is activated?

**Comment by NicolaosGreene** [comment]
Sorry that I said this in an odd manner. It is the latter. You have to do D9 first, which requires you to do Expedition 37 or 38. However, this one being done is applied towards the 7 needed for D11. However, D9 is prerequisite for D11 so I was saying that the counter for D11 should start at 1/7 rather than 0/7 because of this.

**Comment by dragonjet** [comment]
hmm this is a good time for me to test this. I have just done D9. starting D11 now. If I see it marked complete at 6/7 then we do have to do something xD

**Comment by NicolaosGreene** [comment]
At 3/7 you should be able to navigate to the quest at it will say 50% thus changing it to 4/7, but you could do that other as well.

**Comment by dragonjet** [comment]
yep, I wont visit the quest page. I wanna see a natural counting without auto adjustments to see if the extra 1 really applies

**Comment by NicolaosGreene** [comment]
I shall await your test then

**Comment by dragonjet** [comment]
will get my results probably tomorrow afternoon. this will be my last exped for the day so around 2 more of the 2-hr runs tmr

but I'm afraid I might not avoid opening the quest page by then

**Comment by ReiFan49** [comment]
avoid the expedition page right?
peeking out the questlist might refer the page that should be avoided too

**Comment by dragonjet** [comment]
confirmed. only 6/7 and it was marked complete when I went to the quests page

![ss 2015-08-12 at 06 36 39](https://cloud.githubusercontent.com/assets/557312/9222047/4204017e-4121-11e5-8034-74306b5831d5.jpg)

**Comment by dragonjet** [comment]
https://github.com/KC3Kai/kc3-translations/commit/77db9129a5d2ed73238088f8363247e7e1c2f861
