### ISSUE TITLE
[Suggestion] Highlighting

### ISSUE THREAD

**Issue by JD-Kurotoshigami** [KC3Kai/KC3Kai#584]
I'd like for the strategy room to be able to "highlight" the name of a shipgirl/equipment when clicked... so that it can be used for planning for events, especially for ones with ship locking
it would also be great if it has an auto tag of which part it is already locked...
do note that I meant for these two as separate things... one for the ones already used, and one for planning who to use

**Comment by dragonjet** [comment]
jede, what about this?
https://github.com/dragonjet/KC3Kai/issues/580

can suffice?

**Comment by JD-Kurotoshigami** [comment]
yea sumthing like that but... i think it will be easier for the ttk if it is just click rather than click and drag...
like when we click the LoS, it changes from old,new, and sum

**Comment by dragonjet** [comment]
but how can they specify which color they want to mark it to? xD

**Comment by JD-Kurotoshigami** [comment]
as i said just like the LoS checker (default theme) click then it will be changed

**Comment by dragonjet** [comment]
no plans to implement on-click tag. will settle for current locking planner tab in strategy room as drag-drop
