### ISSUE TITLE
Branching still using numbers instead of Node letters

### ISSUE THREAD

**Issue by ethrundr** [KC3Kai/KC3Kai#603]
This is happening on 31-5, probably onwards as well:
![screen shot 2015-08-13 at 04 01 32](https://cloud.githubusercontent.com/assets/13522800/9233809/1e61a29a-4170-11e5-81e1-07822404f9d9.png)

Also, there are one node in 31-4 that also still in numbers, which happens on Node E:
![screen shot 2015-08-12 at 22 28 26](https://cloud.githubusercontent.com/assets/13522800/9233826/3819dec8-4170-11e5-82b4-b4f47361f572.png)

**Comment by bamboo3250** [comment]
@ethrundr Why you go so fast? :cry: I will update those node letters after I finish integrating the Damage Calculation's new API :kissing_closed_eyes:

**Comment by ethrundr** [comment]
@bamboo3250 okay then~
erm.... more ship and resource in reserves, I think? :smiley:

**Comment by bamboo3250** [comment]
Oh btw, not related to the issue, I noticed the level of ships is hidden by the HP bar when it is greater than 99 in your picture. We should take note that as well.

**Comment by ethrundr** [comment]
@bamboo3250 I just realized that, actually.....

BTW, to helps you, here's the node letters of the route I used:
2 --> Node B
5 --> Node E
4 --> Node D
16 --> Node F
9 --> Node I
11 --> Node K
14 --> Node Z
![screen shot 2015-08-13 at 04 27 05](https://cloud.githubusercontent.com/assets/13522800/9234393/96f8f372-4173-11e5-9b52-dcd2b7ae1bfc.png)

**Comment by bamboo3250** [comment]
@ethrundr thanks, this helps a lot :+1: I'll update it soon.

**Comment by ethrundr** [comment]
@bamboo3250 by the way, is your update includes 31-6? If yes, I'll test it there later, since I just finished my E5 :laughing:

**Comment by bamboo3250** [comment]
@ethrundr yes, it should cover the most common routes for most of people but it hasn't been merged yet xD

**Comment by ethrundr** [comment]
@bamboo3250 okay then :D gonna wait for dragonjet  to wake up and do the merge :laughing:

**Comment by dragonjet** [comment]
merged. which pull was it? xD

**Comment by ethrundr** [comment]
I believe it's this one: #607

**Comment by dragonjet** [comment]
wait, do we keep this or track further on #540 ?

**Comment by bamboo3250** [comment]
I think we should close this and keep track in #540. Is that okay? @ethrundr

**Comment by dragonjet** [comment]
all further maps will be tracked on #540
