### ISSUE TITLE
Upon returning to port, gear count reset but ship count

### ISSUE THREAD

**Issue by ReiFan49** [KC3Kai/KC3Kai#630]
0. all themes
1. do sortie 
2. ask RNG for a drop (at least two or more, for accurate result)
3. remember the number of equipment count before sortie (on my case, 450)
4. keep going until the sortie ends (on my case, 2 drops, 2 DD, 2 slots)
5. once first port call received, 452->450
6. once second port call received, 450->452 (this one is correct, and stops)

(ps: i'm afraid of resetting the pending counter is not allowed on the end of sortie...)

**Comment by ReiFan49** [comment]
well, i guess its because the `slotitem` is called before port, and have "obsolete" data on it..
let's say my Hiyou have plane proficiency level of 4,4,4,4 upon returning sortie, it still 4,4,4,4, but when i check equipment page, it's already 5,4,4,4.

and its updated due to modernization for Yukikaze

**Comment by dragonjet** [comment]
ah maybe pendingGearCount is reset on end sortie?

**Comment by ReiFan49** [comment]
well, but the thing that should be avoided that, pendingGearCount should not be kept after 2nd port call, because it's `slotitem` is already counted with the new ship one....

**Comment by dragonjet** [comment]
hm that's true

**Comment by ReiFan49** [comment]
fixed along with referencing issue
