### ISSUE TITLE
About Event Sortie Page

### ISSUE THREAD

**Issue by ReiFan49** [KC3Kai/KC3Kai#635]
now after map difficulties is totally supported,
i guess there's something that need to be checked back about event sortie page...
1. is it intentional that non-cleared map use no gauge instead `curhp` and `maxhp` ?
   Status: **OK**
2. for every sortie, it might have a difficulty data attached to it (new db ver right ...). what i'm thinking is, decorate the info box either in total collapsed form or at least expanded (not fully expanded is OK, but not collapsed) with difficulty marker.
   
   what i'm thinking is similar like this
   ![Easy](https://cloud.githubusercontent.com/assets/9847780/9287425/ab431da4-433e-11e5-824f-cf8f2db6bdc5.png)
   ![Normal](https://cloud.githubusercontent.com/assets/9847780/9287396/c9761bf2-433c-11e5-9274-6ab11fa5baf8.png)
   _explanation: a text with "my usual rotation" style, attached with a gradient that makes the sortie_box more colorful (but there's **no rainbows** for any difficulty marker, easy green, normal orange, hard red)_
   Status: **OK**
3. decorate the map clear (not per sortie, but the map selection) with difficulty marker (either a medal like in-game, or something that i cannot think off...)
   Status: Ongoing (using single-letter marker)

**Comment by dragonjet** [comment]
for event maps, non-cleared has `...hp`, but for ExOps, it has `kills`

I agree with 2, where they can also see which difficulty they got a drop or something.

and 3 is something important too, on which difficulty it was cleared.

btw I forgot game mechanics but can one change difficulty after clearing?

**Comment by ethrundr** [comment]
my own opinion, since I loved something simple and not too flashy:

for no.2 and 3, if it's using just a simple difficulty marker, I'm on for it. but if it's involving gradient or such, somehow I'm objecting it. the current one is already good and simple enough, no need to make it more flashy.

if its purpose to notify only the difficulties, only marker is enough in my opinion.

however, at any rate, this will be important to be implemented. just keep it as simple as possible, yet still informative.

**Comment by dragonjet** [comment]
ah for 2 and 3 we'll just add the ribbon image beside the map name

**Comment by ReiFan49** [comment]
ok, i'll wait the event badge to come,
while waiting, the number 1, is... lol
"Not cleared" + `noclearnogauge` class on event maps.
that's why i'm asking this xD (gonna push this one)

**Comment by ethrundr** [comment]
@ReiFan49 Isn't the badges can be acquired directly from the cleared maps?

anyway, I missed the trolls on the Natsuiro theme :cry:

**Comment by ReiFan49** [comment]
no no... the file for the extension...
something like "MedalC.png" "MedalB.png" "MedalA.png", and put it as overlaying element that does not interfere (`pointer-events:none`) with either `sortie_box` or `map_info`

i'll put "Just do it!" on 1HP left, come on, `info_troll` can be anywhere as long as its enabled right?
(i remember LSC #JustDoIt ... oh -> #278)

**Comment by ethrundr** [comment]
@ReiFan49 I already have it toggled to enable, but in Natsuiro it's not appearing. probably @dragonjet doesn't provide the label to contain these trolls XD

**Comment by ReiFan49** [comment]
sortie on easy rank might have been planted with `info_troll`

yes. it's "EASY MODO!" (cannot find good pic on danbooru, i'm sure there are many kancolle's easy modo picture lol)

**Comment by ethrundr** [comment]
@ReiFan49 LOL that troll XD

**Comment by ReiFan49** [comment]
![image](https://cloud.githubusercontent.com/assets/9847780/9294156/e4140018-446e-11e5-8042-d85cbfd35b1f.png)
`_(:3/|_)_`

**Comment by dragonjet** [comment]
@ReiFan49 yea I think it's too flashy xD

**Comment by ReiFan49** [comment]
leaving a text only might give a way for translation (might use css trick like stamp lol)
~~also, should we make a new issue regarding trolls (lol trolls are srsbsns xD) too?~~

**Comment by dragonjet** [comment]
what if it's just border color? something light,and not a hard contrasting color

**Comment by ReiFan49** [comment]
text with border color for sortie difficulty marker, sounds good (should we put a dev only config?)

i'll give one letter marker for map page, indicating the difficulty for the upcoming sortie. (too lazy until connection on my home got better lol)

(ps: need help for easy modo background for map difficulty lol)

**Comment by dragonjet** [comment]
wait I got lost there, what text with border color? XD
I was thinking more like

![ss 2015-08-18 at 08 04 14](https://cloud.githubusercontent.com/assets/557312/9329469/5630d65a-45e4-11e5-88f5-dfcdadae6c1b.png)

**Comment by ReiFan49** [comment]
![image](https://cloud.githubusercontent.com/assets/9847780/9329757/92f065e8-45de-11e5-9153-24befa90dcc5.png)
this one

**Comment by dragonjet** [comment]
ohh so that's what you mean :+1: we can probably put the text on the expanded version, just so that it won't interfere with the buttons, or if behind the buttons the better

**Comment by ReiFan49** [comment]
expanding with `expanded` class, however well, it's .... lol

not expanded -> expanded: difficulty name suddenly appears (i'm using css -psuedo after- lol)
expanded -> collapsed: difficulty name suddenly disappears...

**Comment by dragonjet** [comment]
or what if just simple vertical text with css transform:

![diff](https://cloud.githubusercontent.com/assets/557312/9330733/af4ffeec-45ed-11e5-9caa-1eadfde99414.png)

**Comment by ReiFan49** [comment]
hmmm i need to put some trolls on easy modo, so it's not so sufficient lol (added a workaround to make expansion to not to show the psuedo-after attribute)

**Comment by nicky008** [comment]
I suggest this; "LUBE", "HELL" and "REKT"...

**Comment by ReiFan49** [comment]
leaving those on `terms.json`

	"EventHistoryRank1"  : "EASY",
	"EventHistoryRank2"  : "NORMAL",
	"EventHistoryRank3"  : "HARD",
	"EventHistoryRank1X" : "KIDS CHOICE",
	"EventHistoryRank2X" : "HELL AF",
	"EventHistoryRank3X" : "GET REKT SON",
