### ISSUE TITLE
[Bug] Vertical panel doesn't adjust well between Single and Combined Mode

### ISSUE THREAD

**Issue by LostLogia4** [KC3Kai/KC3Kai#636]
Applies in Vertical mode:
The panel responds to Combined Fleet sorties, but the option to toggle EXP/morale/equip/fuel option is absent.

After returning to single fleet mode, the Battle mode panel stays in Combined Fleet display, and doesn't display single fleet node encounters.

**Comment by dragonjet** [comment]
is this on default theme?

**Comment by LostLogia4** [comment]
Yes.
