### ISSUE TITLE
Boss E7 icon

### ISSUE THREAD

**Issue by bamboo3250** [KC3Kai/KC3Kai#645]
@dragonjet http://s708.photobucket.com/user/dragonjet25/library/KC3%20Abyss%20Icons?sort=9&page=6
Why is Air Defense Princess's hair taken instead of her face? :sweat_smile:

**Comment by ethrundr** [comment]
:scream: you're on E7 already?

**Comment by bamboo3250** [comment]
@ethrundr yeah, E7 is a true nightmare. After about 1x runs, I just scratched the boss 184/2000 hp bar.  :sweat:

**Comment by dragonjet** [comment]
oh lol idk what happened, let's leave it like that for some trolling xD

**Comment by ethrundr** [comment]
@bamboo3250 still stuck at E6 due to resource runs out :sob:

**Comment by bamboo3250** [comment]
@ethrundr how much is your resource now? How much did you lose? :scream:

**Comment by Crazyteitoku** [comment]
Abyssal Akiduki's face is cancerous - that is why only her hair is shown instead. :stuck_out_tongue_winking_eye:

**Comment by ethrundr** [comment]
@bamboo3250 less than 10k remaining, loss around 50k so far from E1 to E6
3 kills to go to get graduated from this map :cry:

**Comment by bamboo3250** [comment]
Finally my nightmare ended here :sob: 

![screen shot 2015-08-17 at 9 08 13 pm](https://cloud.githubusercontent.com/assets/8078323/9305826/f4f2f21e-4526-11e5-9e31-

Last hit based Shigure
2a276d70a902.png)
![screen shot 2015-08-17 at 9 08 11 pm](https://cloud.githubusercontent.com/assets/8078323/9305827/f5deb5a0-4526-11e5-9905-9b9dd4013678.png)

My third Maruyu drop in this event
![screen shot 2015-08-17 at 9 08 53 pm](https://cloud.githubusercontent.com/assets/8078323/9305828/f75d69b2-4526-11e5-844d-65fac6458324.png)

And the cutie :blush: 
![screen shot 2015-08-17 at 9 13 37 pm](https://cloud.githubusercontent.com/assets/8078323/9305829/f8c426ba-4526-11e5-8bb9-9346f98e56cc.png)
![screen shot 2015-08-17 at 9 13 56 pm](https://cloud.githubusercontent.com/assets/8078323/9305832/fb137092-4526-11e5-8213-b19faf47e560.png)

**Before event:**
Fuel: 295131
Ammo: 206940
Steel: 275145
Baux: 122380

**After E7:**
Fuel: 121845 (-173286)
Ammo: 105459 (-101481)
Steel: 152133 (-123012)
Baux: 76046 (-46334)

![screen shot 2015-08-17 at 9 17 39 pm](https://cloud.githubusercontent.com/assets/8078323/9305837/001be1f0-4527-11e5-8b49-d99213543707.png)

**Comment by LostLogia4** [comment]
Congrats. I've just cleared E5 now.
That aside, that's quite a whole lot of resources spent on E7 Easy there... idk if I could even clear it...

**Comment by bamboo3250** [comment]
@LostLogia4 The amount of resources I spent on E7 is more than E1-E6 combined. It's the result of 121 runs in that hell. But when you know the trick, that number and the lost will be much smaller.

**Comment by dragonjet** [comment]
wow you were hiding 300k fuel before :open_mouth: 
and now it's around 120k :open_mouth: 
now I doubt if my resources can last

**Comment by Crazyteitoku** [comment]
@ethrundr welp can't say that I have gotten that far into the event, am still stuck at E-2 hard but going to wind that difficulty level down. Surely my time will come to meet that cancerous abyssal where I was hoping to get Akiduki. Sadly no reports of any of the Autumn/Fall 2014 rewards were made available.

@bamboo3250 Congrats! the amount of resources you had is... :scream: I just hope that I could get my ends cleared as well but I am still too far away.

**Comment by bamboo3250** [comment]
@Crazyteitoku I'm sure that getting AS+ is the key of this event. WIth Air Supremacy, thing will be much easier. Contact is also a big bonus though. 

@dragonjet then you'd better not send support expedition for E7. With random branching rule and trolling from the first node sub, those will be wasted :sweat_drops:

**Comment by LostLogia4** [comment]
@bamboo3250 121 runs... huh? That's about the number of sorties I have to run to get Ooyodo.
Does that mean we'll have to turn our CVs into Reppuu Mules again?

**Comment by nicky008** [comment]
And now, I wonder my buckets left will be enough for doing E-8? :cold_sweat:

**Comment by LostLogia4** [comment]
The Kancolle's equivalent of The Skull Reaper... huh?

**Comment by nicky008** [comment]
The devs are surely the meme generators and :trollface: since 2013...

**Comment by bamboo3250** [comment]
@LostLogia4 Use Reppuu for the sake of your resources, not just bauxite but fuel and steel of repair cost as well. Saiun should also be taken into consideration for getting Contact.

**Comment by LostLogia4** [comment]
@bamboo3250 How many Reppuus and bombers I shout put in then? is there any point in hgetting contact if I have no bombers?

**Comment by bamboo3250** [comment]
@LostLogia4 for the ship equipped with Saiun, you should put the bomber on the second/third highest plane capacity slot. For the rest it should be put on the last slot. As long as the bombers are not shot down completely, our CVs still can deal damage significantly. The remaining slot should be filled with Reppuu to get AS+ so that only 10% of bombers are shot down (If it is just AS, up to 40% of bombers will be shot down).

**Comment by nicky008** [comment]
For Easy mode... When I used STF, I need at least 5 Reppuus for AS+ on the bose node and 2 best bombers for doing some damages. Bose node has <200 AP. (Excluding debuffing on her AA by passing northern route to rekt BWS' node first.)
