### ISSUE TITLE
[Suggestion] Sortie History

### ISSUE THREAD

**Issue by JD-Kurotoshigami** [KC3Kai/KC3Kai#655]
![1853](https://cloud.githubusercontent.com/assets/13150941/9297457/a4a47dc4-44da-11e5-8005-3ed75cfda631.JPG)
I think it would be better if there are buttons above just like the ones here but are for "all" of the runs 
ex : 
Show all Nodes, Show all Formations, Hide all Enemies, etc
so that when some want to compare their runs it would be easier to just press one button and not press each run
sorry can't explain it well...

**Comment by dragonjet** [comment]
ahh that's possible

**Comment by Nya-chan** [comment]
Implemented and thus closing
