### ISSUE TITLE
[Suggestion] Refresh Toggle

### ISSUE THREAD

**Issue by ReiFan49** [KC3Kai/KC3Kai#673]
ok, since i'm bad at putting things (i mean, UX), i guess, i'll request this to others

API Page: either right side or left side, a toggle to refresh the swf if catbombed, (yes. this is a dangerous toggle)
using the following code will refresh the swf. **directly**
`$(".game-swf").attr("src","about:blank").attr("src",localStorage.absoluteswf)`

DMM Page: requires injection with deep iframe (iirc, 2-3 iframe stacks)

DevTools: i miss the [Idb] toggle (i wonder why it was still documented)

To do list:
:white_check_mark: API Page (sample simple xD)
:black_medium_square: DMM Injection
:black_medium_square: <kbd>Idb</kbd> whereabouts xD

**Comment by dragonjet** [comment]
ah we shouldn't do auto-refresh in any scenario
let him refresh by himself and read the catbomb popup

even if it's a toggle, this might cause unnecessary problems with skrubs
I meet alot regularly getting tagged multiple times a day on Facebook posts asking for help 

not everyone has decent knowledge about these and might get abused which may lead to larger problems that could even stain the KC3改 name

**Comment by ReiFan49** [comment]
no, it's not auto-refresh....
looks like another toggle to put "In-page Refresh" should be there too...

about "put such script" ? well it just for the developer task (well, on that case, i'll simulate it first in case of misunderstanding or others) lol.
(using that piece of code in api page, makes every catbomb is refreshable for me)

**Comment by dragonjet** [comment]
lel I can't visualize XD

**Comment by ReiFan49** [comment]
![image](https://cloud.githubusercontent.com/assets/9847780/9330823/f1fd053a-45e5-11e5-884b-44f58af6d4e4.png)
here you go

**Comment by dragonjet** [comment]
hm, alright :+1:

though if only by default disabled on settings.

some people (including me) have the whole window set only yo 800x480, so having that will actually be overlaid above the game, e.g.:

![ss 2015-08-18 at 09 19 36](https://cloud.githubusercontent.com/assets/557312/9330901/def7090a-45ee-11e5-96a1-d2ecc7e3d545.jpg)

**Comment by ReiFan49** [comment]
either putting it behind the game frame, or move it to the upper side (since the game usually interacts from bottom to the top, but not the topmost and requires N times click to make this behaviour run, to prevent.. "oh shit i pressed the toggle.. and i almost killed AA hime-chan on Hard mode and it's 23:55 JST" lol

**Comment by ethrundr** [comment]
Personally, I disagree with adding this button, especially with some people out there who are really abusing refresh.

When people abuses refresh know about this button, enabling it, use it more and more, then get banned, they most likely will blame us for putting the button there, as most people who aren't know will assume EVERYTHING we put is safe to be used (and sometimes, abused as well). I came up with this statement based on my own experience dealing with those who are using KC3kai.

**Comment by dragonjet** [comment]
hmm I understand @ethrundr points.
I share the same concern, but I only agreed if it's disabled by default.
Now that he gave examples, I started to visualize players.

True, this might also get abused knowing them, not just the skrubs who don't know what they're doing, but also those who know but just want to abuse it for their gaming purposes.

And yes we don't want a KC3改 mechanism to be a part of it, even indirectly. We should just have them use the browser's F5 function, even us stopping them for a reload confirmation. But we should do a refresh mechanism, which is known to cause ban.

**Comment by ethrundr** [comment]
If this really want to be implemented, then I suggest to add a re-confirmation upon enabling the setting.
This is to prevent people from checking the wrong option, then click them accidentally.

I don't want anyone getting banned because of this feature.

**Comment by dragonjet** [comment]
hm well technically it's not bannable. but it's a tool that can be abused to a ban.

they can do spam F5 on their own, and this is something that will promote that, not just technically, but also psychologically:

They will think "*The KC3改 devs put this here for a reason, and we should use it, they think it's alright to spam F5 that's why they made it easier for us to do it.*"

Not everyone gets catbomb very often, and in those cases they should review the message themselves, and proceed to troubleshoot it, either they go to DMM play page or whatever, but from the point of catbomb, they should do things themselves.

I really don't suggest adding this feature now.

**Comment by ethrundr** [comment]
> They will think "<i>The KC3改 devs put this here for a reason, and we should use it, they think it's alright to spam F5 that's why they made it easier for us to do it.</i>"

This is exactly what I'm concerned about.

**Comment by dragonjet** [comment]
For <kbd>Idb</kbd>, I added functions to the profile page in Strategy Room, **Clear Histories**.

You may test it if you want. I don't wanna XD

Also I'll do the DMM injection when the time comes for it

**Comment by ReiFan49** [comment]
i guess it's not the <kbd>Idb</kbd> that i remember long ago lol
(however, sounds like refresh toggle should not be added, yes, third-grade college gonna starts soon)

**Comment by dragonjet** [comment]
refresh toggle at API page was done. no need to implement at other game modes.
