### ISSUE TITLE
[Feedback] Natsuiro as default theme

### ISSUE THREAD

**Issue by dragonjet** [KC3Kai/KC3Kai#684]
I'd like to know what everyone thinks about setting `Natsuiro` as default theme

This will only apply to those new installs, but as you know, existing players will already have the config on the localStorage and will not be affected.

If you wanna read a bit more about why natsuiro even existed when we already have a working default panel:

* It all started with people asking how to get back to "Battle Mode" when they accidentally clicked *Exit Battle Mode* in the middle of sortie.
* Default panel also started to show some UI problems, with texts, overflows, etc. and mostly related to spacing, to the oldies, you might remember how we went through this phase XD
* I wondered there must be something we can do to resolve all this, and so I thought, we should just use the Battle Mode as the main theme, since almost everything is there anyway. The only things missing were the bucket counts, etc. So I made the issue:
  * #187 *New theme using Battle Mode as main interface*
* That one basically became the Natsuiro theme we know today
* From there, we started pushing out more features, but only applied to Natsuiro. I feel that the current default theme is getting far outdated as time goes by.

We might change "Default" theme name to "Legacy". I'm also seeing a time where we stop supporting the Legacy theme.

I would certainly like to know @bamboo3250's input on this since he's the maintainer who worked hard on the vertical orientation.

#### Tasks
:black_medium_square: #337 Morale Timers
:black_medium_square: Color Schemes
:black_medium_square: Include 420px version in vertical
:black_medium_square: Switch the between day battle and night battle background
:black_medium_square: Expedition helper to activity tabs
:black_medium_square: Level tooltip on combined ship boxes

**Comment by Crazyteitoku** [comment]
I quite like natsuiro theme actually, sans the few things missing from default theme.

However I can also see why default theme is getting deprecated but I don't think that would appease much to certain audiences who aren't into dark themes. If at all possible to just make Default theme look similar to Natsuiro except it is white and uses themes that were once used by Default theme itself.

**Comment by dragonjet** [comment]
Ah with that, I'm thinking about color schemes. Just having an array of hexes that affect styling. but the html/css/js will remain `natsuiro`. I don't wanna do another there just for light-colored version XD another thing to maintain.

**Comment by Crazyteitoku** [comment]
That is true lel or you probably just need more devs who are keen on having a light theme to go maintain it themselves xD

**Comment by bamboo3250** [comment]
For the sake of KC3Kai, we should move forward even when that means we have to give up something we have put a lot of effort on. There are many problems in Default theme that we struggled to find out a solution but in the end we went to deadlock. It happened exactly one month ago. Now we have Natsuiro theme, which can solve those problems far more than I expected. Developing a new feature is interesting but maintaining for all themes is not. We don't have enough human resources to keep everything in sync. Therefore, I also foresee the time we have to leave Default theme to focus more on Natsuiro. I believe that is the right way we should go for a better interface, better UX.

**Comment by Crazyteitoku** [comment]
Yeah for now it would be best to definitely not continue maintaining aesthetics when there's still plenty of features yet to be implemented amongst the plethora of ideas that are sporadically being invented.

On the other hand I am a fan of modularising everything. If say the themes could be modularised in some sort of a "container" where it may one day have good documentation - other keen people who wants to take on the role of maintaining other themes etc can do so themselves. This way at least part of the flexibility is retained without having to sacrifice the amount of people we have.

**Comment by McDohl** [comment]
bye bye default themes, will miss you a lot

**Comment by ethrundr** [comment]
I fully support to make Natsuiro the default theme. This theme provides lot of information in that small, limited space. Also, the lack of "modes" like what we have in the Default one make this one better: you need not to switch modes between each actions in the game.

But keep in mind that after making this default theme, we cannot just abandon the old default theme. We still need to make it as up to date as the Natsuiro, with its personal behavior and uniqueness.

Anyway, the crafting prediction still not appearing in Natsuiro, or did I mistakenly turn it off?

**Comment by LostLogia4** [comment]
Before we can set the Natsuiro theme as default though, I personally still have the trouble as follows:
- Lack of 420px version in vertical, which means it'll look very awkward in 
- Most world maps don't have bars, so they'll look a tad awkward when you sortie out to 1-1.
- Crafting prediction didn't appear in Natsuiro, as explained by ethrundr.

One more feature I would like if possible to have is to change the background between day battle and night battle background, preferably by toggles in the panel or something.

**Comment by ReiFan49** [comment]
i'll miss the natural night battle trolls.
aside of that, maintaining default is way harder than natsuiro lol. (twice checking as usual)

crafting box will appear on activity...

**Comment by ethrundr** [comment]
@ReiFan49 well if we want to keep that theme there, we need to keep maintain it and update it, so people can choose which one they prefer to use and having no significant lack of information in eithe theme.

If this proved to be hard later on, we can just discontinue the work in that theme, or in other words, dropping it out of KC3kai.

**Comment by ReiFan49** [comment]
@ethrundr well, harder due to copy-paste thingy on horizontal.js and vertical.js,
just like sortie nodes differences on those orientation...

**Comment by dragonjet** [comment]
Added @LostLogia4's comments to #582

**Comment by McDohl** [comment]
oh finally another person that wants 420px for vertical :+1:
maybe put that expedition helper to activity tabs, since I use that a lot xD

**Comment by LostLogia4** [comment]
Tested the natsuiro theme again and it looks like combined fleet have some layout problems.
First thing to do is to put the levels before the hull classification, move the morale circle up to free up space for fuel and ammo.

**Comment by dragonjet** [comment]
I opted to remove the levels from the combined mode, they can just switch to fleets 1-2-3-4 if they want to see the level, it's one click away. The idea is that you only use combined mode when sortieing event maps, where you already have your composition built. It's not like grinding 3-2A where you need to see ship levels each time.

The morale circle is on its current position right now to make space for long ship names above it.

![ss 2015-08-21 at 12 00 09](https://cloud.githubusercontent.com/assets/557312/9401072/33458216-47fc-11e5-9f11-aac5f06f8c81.jpg)

About the buttons, I think the combined fleet is on its right order though. Traditional buttons first before the specialized one. There are more cases / maps that you'll need single fleet than combined.

**Comment by Crazyteitoku** [comment]
@dragonjet I am kind of mixed on that approach. I mean sure it does look nicer without it but for new players who also happens to be levelling their ships during events it may require more clicking "effort".

A suggestion to combat that might be to implement the levels as a tooltip for on:mouseover events. Just a thought.

**Comment by ethrundr** [comment]
I'm agree with @dragonjet. We need not to add the ship's level on the combined fleet node, since during event, people won't be too concerned about their ship levels.

However, since we now can detected whether a combined fleet is formed or not, how about if we also redirect the panel to the combined fleet mode when the sortie starts and combined fleet mode is used? (Actually I don't know whether this is already implemented or not, since I always switch to Combined mode manually before starting the sortie).

**Comment by dragonjet** [comment]
hm tooltip sounds alright

**Comment by McDohl** [comment]
hmmph dj, what happens to strategy room shortcut at panels XD

**Comment by dragonjet** [comment]
hm I am unsure
