### ISSUE TITLE
An alternative view specialized for expeditions?

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#685]
I'm purposing an alternative, togglable view specialized for expeditions (by togglable I meant a view that user can open and close at will), because it is not always necessary to show user detailed info about expeditions (at least for me, I only look at these info when planning expeditions and preparing fleet members)

not good at UI designing, just drafting what it would roughly look like:

![2015-08-19_101804_3360x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/9358772/d1824f60-465b-11e5-9cd8-57b358638505.png)

And each slot shows ship info (important info for expeditions):

![2015-08-19_101826_3360x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/9358775/d3e16dae-465b-11e5-8a0c-531a270ac94c.png)

The dropdown list will be grayed out if the fleet has been sent out or is a part of a combined fleet,
otherwise user can choose one of the expedition and see related info about it.

A status bar shows one of the following:

* the fieet is a combined fleet
* remaining time if a fleet is running
* requirement not met / potential problems (resupply, morale) (only one at a time for saving space)
* "Ready" if all requirement checks are passed.

Since it'll be specialized for expeditions, I think it's reasonable to put all fleets into one single view,
so user won't have to click between fleets.

**Comment by NicolaosGreene** [comment]
The one thing I could think of that could be useful that isn't on here is a net income/per time, though that isn't a necessary feature and I would find this to be helpful myself

**Comment by Javran** [comment]
@NicolaosGreene I also think an hourly net income will be helpful, but this might be a little bit tricky, the problem is, the resource should be divided by the duration between when you sent the fleet and when you interact with game UI to get back the fleet, not the expedition time itself.

what we could do is maybe taking as division the maximum of expedition time and the time since the fleet is sent.

**Comment by dragonjet** [comment]
Ah yes, we can add this on the strategy room, this would be the same as #30?

**Comment by Javran** [comment]
@dragonjet I'm actually suggesting putting it on devtools page, just leave a button to turn it on and off. The strategy room is not responsive to fleet member changes but an expedition qualification check is mostly about fleet members.

**Comment by dragonjet** [comment]
hmm that is gonna be difficult though.
This will also mean all themes will need to integrate this view.

I have an idea but I'm not sure if it will work, there's a button that will add another tab on the devtools, so that it will have its own page.

**Comment by JD-Kurotoshigami** [comment]
speaking of expeditions, i was wondering where did the "able to go to exped a,b,c,d" things in natsuiro theme...
also it could help a lot of people if you can include a "how many times exped X was done, Great Success, Success, Fail, 50/50 item gotten or not," much like the sortie history but for each of the expeds and has a clear number of how many times you ran that exped and results

**Comment by dragonjet** [comment]
or, we can add a new tab beside Basic, Battle, and Activity, named "Expeds"

This tab will contain an expedition number selector, and the gross income, resupply cost, etc I think there will also be enough space for ready status

The ship boxes don't need to be updated though since it already contains level, supply and morale

**Comment by Javran** [comment]
I agree with you. My idea of having an expedition-specialized view is to show info only related to expeditions. But I'm happy to go with the current layout and having a new tab, the modification would be minimal.

**Comment by dragonjet** [comment]
let me try playing with the layout on adobe sometime today if it can fit

is it alright to only have flagship level, total level, and composition in the requirement not met section?
for resupply status, we also already have it below the ship list

**Comment by Javran** [comment]
There are actually a list of requirements:

```purescript
data ShipRequirement
  = ShipLevel Int -- at least level n for a ship
  | ShipTypeOneOf (Array SType) -- the ship type is one of ...
  | ShipDrum Int -- at least carry n drums

data FleetRequirement
  = Flagship ShipRequirement
  | FleetLevel Int -- fleet level count is at least n
  | FleetDrum Int -- fleet has at least n drums in total
  | FleetShipWithDrum Int -- at least n ships should carry drums
  | FleetSTypeCount Int (Array SType) -- at least n ships should match one of the stype
  | FleetShipCount Int -- at least n ships in this fleet

type ExpeditionRequirement = Array FleetRequirement
```

The fleet info and the expedition number is the input,
the output is a list of `FleetRequirement` objects, we can show requirements not met one at a time, just like how we deal with Weekly Sortie 1 conditions previously.

**Comment by Javran** [comment]
forget about `ShipDrum`, it's not used.
btw how does translation work? I might be able to work out an interface for it.

**Comment by dragonjet** [comment]
translation? If it's from JS, the  `KC3Meta.term("messageCode")`, if it's on HTML, it just needs to have a `class="i18n"`, but the inner text would be the messageCode

**Comment by nekoworkshop** [comment]
@KC3Kai/developers  If no one is working on this feature at the moment I might take it over and push it forward a little bit.

**Comment by Javran** [comment]
@nekoworkshop I don't think someone is working on this. Feel free to take over xD

**Comment by nekoworkshop** [comment]
Here is a prototype I've been working on. Space in the tab area is so limited that I found it impossible (at least for me) to put in everything about expedition into it . I suggest we  make a fullly featured expedition planner in the Strategy Room while use the tab as a checker.

Let me know what you guys think about the UI @Javran @dragonjet 

![image](https://cloud.githubusercontent.com/assets/1346257/10115032/f63586f2-63c9-11e5-887b-cc3b1a9cfcf1.png)

**Comment by Javran** [comment]
@nekoworkshop nice work! since the requirement check takes most of the space, I'd suggest show one at a time (ellipsis could be used if there are more than one unmet requirment)

**Comment by nekoworkshop** [comment]
@Javran That's one of the problem bothering me. If I counted them right then there should be 9 cases when an expedition could fail. That's low morale, ill supplied and the 7 cases from your list. Obviously we can't put them all on the screen (they won't all happen at the same time either, though) but I think it's quite common for a fleet being disqualified for a few criterias, say 2 or 3, when you're adjusting your expedition fleet.

I think 3 should be a sweet point (2 if we really need that space.). In that way a player can fix his fleet compositon in one shot instead of changing a ship only to find that there's other problem.

**Comment by nekoworkshop** [comment]
Here is another layout. By putting the requirements in the tab it will be very convinent for user to adjust his fleet. I removed the resupply costs but it can be deducted from the net income so it shouldn't be a problem.

![image](https://cloud.githubusercontent.com/assets/1346257/10115592/fae5028e-63da-11e5-9f9b-c4c291fd6f0a.png)

**Comment by dragonjet** [comment]
ah that's great progress, mean time I'll rethink the overall UI on how we can make this bigger so we can even support more tabs like this in the future

**Comment by Javran** [comment]
just had some talk with @nekoworkshop will be working on providing some new API for this :)

**Comment by nekoworkshop** [comment]
I'm working on the dropdown menu but I'm not sure if I should show the expedition number only or put on the full expedition name. 

I never used the number since the Japanese name is much easier to remember but I don't know how it works for you guys who don't speak Japanese.  Does number make more sense to you or do you always keep a translated expedition list at hand when you play ?

@KC3Kai/developers  @KC3Kai/translators

**Comment by dragonjet** [comment]
Ah every I knew in the game so far had always used expedition numbers. never knew there were people who refer to them by name, except ofc for the occasional use of tokyo express which is a popular one, but other than that I always see numbers.

I'd prefer "Expedition 1", "Expedition 2".. so on in a single drop down, probably tree'd into their worlds, [somethign like this](http://jsfiddle.net/20mhf21b/). I'm not sure about the expedition name, we also have to add another translation file XD

**Comment by nekoworkshop** [comment]
Then that would be nice. I prefer using the number too since it's too much trouble to adjust the layout when you have no idea how long the text could be ( I know we have a germany translator...). We might at least be able to show the name of currently selected expedition though if nobody really care what it is called we can save the space for something else.

Here is the prototype for the menu.

http://jsfiddle.net/h3zxtwfd/2/

I'm afraid we can't put all of the expeditions into a single level of menu but the prototype fits pretty well in the tab area.

**Comment by kololz** [comment]
It would be nice if it also included Great Success Chance calc, which will be useful people like me who dont know the max number of drums

**Comment by dragonjet** [comment]
@nekoworkshop ah that also works :+1:  dw when you do push it, we'll try to adjust UI if needed later on

@kololz ah that would probably be best for the expedition scorer, the main purpose of the tab is to check requirements *after* the player has picked an expedition he wants to go to

**Comment by McDohl** [comment]
@Javran I believed we can close this issue?

**Comment by Javran** [comment]
@McDohl yeah I think so, cheers!
