### ISSUE TITLE
[Ask] Config Reset

### ISSUE THREAD

**Issue by ethrundr** [KC3Kai/KC3Kai#697]
I'd like to ask, is it true that upon the 18.1 update, all the config was reseted to the default "factory" value?
Since, few moments ago, I just pulled the commits, reload my KC3kai (using `location.reload()` in the console), and all my previous saved settings were gone, just like I'm re-installing this extension anew....

This will make a bit of ruckus out there later if released and suddenly all users found out that their saved settings were gone after updating, without prior notice.

**Comment by ReiFan49** [comment]
```javascript
load : function(){
	// Get old config or create dummy if none
	var oldConfig = JSON.parse(localStorage.config || "{}");
	
	// Check if old config has versioning and if its lower version
	if( !oldConfig.version || (oldConfig.version < this.defaults().version) ){
		// Old config is an old version, clear it, set defaults, and save on storage
		localStorage.removeItem("config");
		$.extend(this, this.defaults());
		this.save();
	}else{
		// Merge defaults, then old config values to ConfigManager
		$.extend(this, this.defaults(), oldConfig);
	}
}
```

sounds like, Yes.

**Comment by ethrundr** [comment]
If it's true then we should make a prior announcement to the update, that all config will be lost.
That way, our user can have enough time to back up all their setting, to re-setting the KC3kai after the update (and reset).

**Comment by ReiFan49** [comment]
AH, so that's why i don't see the battle stamps... i just realized it.... has been reset.

**Comment by dragonjet** [comment]
ah yes I incremented the config version on the 18.1 commit which was designed to reset all saved config

I would advise user to save their background URLs before publishing to webstore though

**Comment by ReiFan49** [comment]
well, but it means.. enforces the theme to be natsuiro right?
on the other issue it was stated... "default theme user will keep its theme as being used one"

**Comment by dragonjet** [comment]
ah yes, scrap the *will keep existing theme* statement, I only said it because that's what will happen naturally as of that point. But right now with the config version increased, the natural thing that will happen is that they get all defaulted back.

**Comment by ethrundr** [comment]
This was done with the official update release, I believe?

**Comment by dragonjet** [comment]
yes and it will apply to everyone regardless if they had it before or not
