### ISSUE TITLE
[Strategy Room][Suggestion] Sortie History: Equipment Listing

### ISSUE THREAD

**Issue by ethrundr** [KC3Kai/KC3Kai#703]
I don't know (and don't found) whether this issue is already being discussed or not yet.

Several of my friends on FB suggested that we also list the equipment each ship used (at least the main ship and the escort ship) on the sortie history listing, both for normal maps and event maps.

If it's using too much space, we can just put icons beside the ship icon, like in the panel or in the Ship List, and the name of each equipment, as well as it's modding level, will be shown as tooltip.

We also can make it toogle-able, by clicking the ship's icon, so the detail in the fleet listing will be alternating between the ship name + level, and their equipments.

**Comment by ReiFan49** [comment]
good news that equipment are stored on database,

**Comment by dragonjet** [comment]
yea, it's as @ReiFan49 said. all equipment are actually saved on sortie history ever since.

but it's only the master ID of the equipment, no plane level nor improvement stars

**Comment by ethrundr** [comment]
@dragonjet well at least we can track what equipment the ships are using from a specific map....

**Comment by dragonjet** [comment]
yep, I guess we can uhm. adjust the sortie history to show it. though can't do it soon XD

**Comment by ReiFan49** [comment]
maybe i'll give the proto to @ethrundr tonight, will have a busy time to cosplay today xD

**Comment by ReiFan49** [comment]
i'll do only for event page for now, for testing phase.

**Comment by Javran** [comment]
already implemented: fleet manager can load fleet compo with equipments from any sortie history.
closing.
