### ISSUE TITLE
Transferring KC3改 Repository Ownership

### ISSUE THREAD

**Issue by dragonjet** [KC3Kai/KC3Kai#714]
I recently made this GitHub organization:
https://github.com/KC3Kai

I will start inviting people there to join, if you haven't been invited yet, no worries I have not added everyone yet since the GitHub username auto-complete is messing with me right now.

I made 3 teams: 
* Translators - read-write
* Developers - read-write
* Testers - read-only (*though I'd like to know if github has any feature for allowing rewrite access to issue tracker, right now iirc they can only create, not manage*)

If you're not yet invited, comment here and tell which team you'd like to belong to.

The advantages to developers is that you no longer need to create a pull request to be able to push onto the main repo. Since the repo is owned by the organization, and everyone is a part of the organization, you have direct write-access.

We can also "assign" everyone to issue tracker. Previously we weren't able to do so and can only assign direct collaborators.

This is the same for translators, technically, there's no difference in access between developers and translators, and is only for the name.

Now, my problem is, transferring the repository.
Has anyone tried this on GitHub before?
I read [their guide](https://help.github.com/articles/transferring-a-repository/), but if someone here has experience on it, I'd like some tips XD

last note: everyone has to update their local git remotes when we do transfer

**Comment by Crazyteitoku** [comment]
@dragonjet if you want I can also help do some invitations. I actually am for this idea considering how the setup we have here is kind of mixed balls to say the least :laughing:

**Comment by ethrundr** [comment]
@dragonjet regarding us the Reporters, will we be included in, or not?

**Comment by Crazyteitoku** [comment]
@ethrundr I believe for now reporters will be categorised as testers which is pretty much the same thing personally. :smile:

**Comment by dragonjet** [comment]
ah that's true, @ethrundr you should actually be under testers since you're on dev build xD

**Comment by bcc32** [comment]
I'd like to be added to Testers.  Well, reporters, but testers once I figure out how to install dev build.  Hopefully once the academic year gets started up I might be able to start contributing to the code base.

**Comment by NicolaosGreene** [comment]
https://github.com/dragonjet/KC3Kai/wiki/Setup-development-build actually explain how setup the dev build decently. I personally recommend git cloning if you know how to set it up since that is the easiest way to keep the files up to date.

**Comment by Crazyteitoku** [comment]
@bcc32 what @NicolaosGreene said I agree. The ZIP "builds" lacks concurrent versioning system and if you are using that you need to also be aware of the fact that you cannot update that copy as it lacks an important file: ".git". Besides, there are plenty of other quirks in-store once you choose to use the actual git method rather than going for zipped builds such as the ability to "rewind back" changes and troubleshoot/tracking down issues more easily.

**Comment by nicky008** [comment]
I think this new group management system has no any problem in the joining for any current members.

For newer incoming members, might need new invitations both here and new settled org before having new repos as usual.

**Comment by bcc32** [comment]
@NicolaosGreene Weird.  Looks like the Wiki main page doesn't have a link to the development build setup but the sidebar outline does.  The only thing I needed was instructions for loading into Chrome since I've never done Chrome development before.  Git is a wonderful thing.

**Comment by LostLogia4** [comment]
Hmm, so I'll be invited as a tester, huh?
One thing I have recently found out is the method to backup and migrate from webstore version to developer version. I'll be writing it up and wanted to included in this wiki entry. I'll be posting it here tomorrow at the earliest.

**Comment by bamboo3250** [comment]
@LostLogia4 congratz. There is no difference in facebook KC fan groups though :joy: 

btw, I'm looking forward to new house. Have you decided when you will move the repo there? @dragonjet

**Comment by LostLogia4** [comment]
@bamboo3250 Best part about this that it costs me less than a fifth of what you spent for E7. Lucky win is a win I guess.

**Comment by ethrundr** [comment]
@LostLogia4 just keep calm about that XD fortunately, my group is kinda softer about that, so I can brag about my clearing there~

looking forward to the new place~

**Comment by LostLogia4** [comment]
@ethrundr Good for you, since I'd rather be the last to brag, even if I am probably the first to get a touch to the shining moon in the group. Two of my friend are doing it on Normal and Hard respectively, with far less resources than I do, while another one simply don't have the resources to pull it off just yet.

**Comment by bamboo3250** [comment]
@LostLogia4 That was great. Now I regret depending too much on RNG without trying various composition and equipment. That resulted in a huge loss in resources when making the same mistake repeatedly as you can see. I know I could have done better than that. However, on the bright side, E7 was where I said goodbye to my single marital status with Kongou, Fusou and Yamashiro. So those lost was not that bad after all :blush:

**Comment by nicky008** [comment]
E8 (in this season) is really harder than the E7. Even doing in Easy, E7 is still not a favorite choice for farming new ships... :no_good:

**Comment by LostLogia4** [comment]
@bamboo3250 Hot sure how you did it but I simply sent out the fleet that I thought would have the best chance to reach the boss and defeat it and basically pray to RNG.

Also, I'll be posting the first two aria for my kekkon kakkamori soon. Look forward to it.

**Comment by ethrundr** [comment]
@nicky008 well not for me though... I'm doing E8 on E4 for that "Sea Wind" XD

**Comment by NicolaosGreene** [comment]
I just got to E6 myself but thats because I'm terrible at stockpiling fuel, E5 was a breath of fresh air after E4 though, I had over 5 runs on the last kill where she ended sub 20 but didn't die.

**Comment by ethrundr** [comment]
E4 and E5 is really a breather in these event, between the early and late combined-fleet maps....
having a fun resource-hoarding session during E5, using Akitsushima, then retreat on the preboss node XD

**Comment by NicolaosGreene** [comment]
Actually E-3 was easy for me, cleared with only 1 extra run, I did over 50 runs to clear E-4, RNG hated me on it

**Comment by ethrundr** [comment]
The only map that makes my sortie count exceed 1 page in the history is E6...
I can manage to clear the rest with 20 runs or less.... Maybe just my luck this time, or due to I do this in easy or medium difficulty XD

**Comment by NicolaosGreene** [comment]
Ah, I've been doing it in hard which has been "fun"

**Comment by ethrundr** [comment]
That "fun" XD
I'd like to do hard as well, but having a resource shortage even before event start forces me to reconsider....

**Comment by dragonjet** [comment]
ah let's do the transfer on the event ending maintenance on sept 2

**Comment by NicolaosGreene** [comment]
Could I request an invitation to a group as a tester I just realized I forgot to say that ><

**Comment by ethrundr** [comment]
I'd like to have it too, if the testers team already up~

**Comment by LostLogia4** [comment]
Took a little while, but I've setup my own Twitch account for the [virtual marriage](http://www.twitch.tv/lostlogia4) with my waifu to-be.
[GitHub](http://github.com)

The first two aria is available [here](http://kancolle.wikia.com/wiki/Thread:317677).

**Comment by dragonjet** [comment]
oh and since the game moved maintenance, let's also move the transfer to sept 7 xD

**Comment by jy19** [comment]
Not sure where best to ask this after going through the issues page so just decided on this thread..If I'd like to contribute to kc3kai code wise, would I have to be invited to the developer team or should I just fork the repo and submit a pull request?

**Comment by dragonjet** [comment]
for now you can fork it, and create pull requests, once you've contributed a few enhancements or features, I'll send an invite for the dev team so you can push directly onto repo.

Though right now we haven't transferred yet, so everyone's still on a fork

**Comment by dragonjet** [comment]
I'll go ahead and transfer it now.

If you haven't been added to the organization yet, comment here, and put the team you'll be in

**Comment by ethrundr** [comment]
@dragonjet  BTW, lilttle bit curious regarding the Testers team, 
With current rights, are we able, or not able, to set the label ourselves on the issue?
If we supposed to be able to do so, I'd need to find it out how, since it seems I still can't do it now
But if we are not able to, then fine.

**Comment by dragonjet** [comment]
right now the testers team can manage labels and assignments of issues, and even be assigned to it as well, even self-assign. afaik - is what the settings are, but I can't test it.

for those already in team, can already request addition to translation team without the initial requirements specific on `kc3-translations` readme

**Comment by ethrundr** [comment]
@dragonjet hmm....
as far as I see, I only can post new, reply and editing my own issues.
still can't (or least, still not figured how to do so) to add labels and assign other person

**Comment by dragonjet** [comment]
ah i think i know, the testers team do not have write access
