### ISSUE TITLE
[Suggestion] "Need Resupply" Label Remaster

### ISSUE THREAD

**Issue by ethrundr** [KC3Kai/KC3Kai#719]
I think that the supply indicator should be updated from "Supply good" (100% supply) to "Need resupply" (< 100% supply) after the sortie was ended, or the player return to the homeport, and not at the middle of sortie, unless the supply status already low enough up to the point will risking the sortie if continued (like, less than 30% or so). The reason is, even if the player knows that their ship is running out of supplies, there is no way for the to replenish it while in the middle of a sortie.

This screenshot is taken in the middle of 2-3 sortie:
![screen shot 2015-08-23 at 04 40 26](https://cloud.githubusercontent.com/assets/13522800/9425634/d7c5c0ca-4951-11e5-94ce-008572259597.png)
(ps, please disregard the morale timer. it was being discussed in other issue already)

Also, when one of the supplies (fuel and ammo, also planes if the fleet consist of ship that able to carry planes) running out, also set the notification to be more "urgent". If possible, also highlight the ship that require resupply.

Last, I think that it'll be a good idea to let the user set themselves at what supply level they want to be notified to resupply their ships, just like the minimum morale setting.

**Comment by ReiFan49** [comment]
![image](https://cloud.githubusercontent.com/assets/9847780/9795706/629196b0-581c-11e5-993e-a571e5d839e5.png)

**Comment by dragonjet** [comment]
Let's merge this into #789
