### ISSUE TITLE
[Ask] What happened to the heartlocks in strategy room?

### ISSUE THREAD

**Issue by LostLogia4** [KC3Kai/KC3Kai#720]
Seems like it was gone in favor for night battle FP in latest webstore version...

**Comment by bamboo3250** [comment]
Yes, there is not enough space for the heartlock so it's pushed to outside of the table xD

**Comment by NicolaosGreene** [comment]
Is there a reason we can't widen the table further?

**Comment by dragonjet** [comment]
we're limited to 800px, the same width as the game

**Comment by NicolaosGreene** [comment]
Might we want to make the stats toggle-able then so that we can see the ones that we are interested in then?

**Comment by NicolaosGreene** [comment]
Another option would be a scrollbar for when it is overflowing as well.

**Comment by LostLogia4** [comment]
How about a toggle option between firepower + torpedo and night battle firepower?

**Comment by dragonjet** [comment]
it would be nice if there's a column selector where you can enable/disable columns, but I guess that's too much for a hard-coded table like ours. At these times we'd want to use JS plugins for table, but I'm always concerned about filesize of the extension in the webstore

**Comment by bamboo3250** [comment]
I would go down to "column selector" route. There will be some must-have columns and some optional columns for the column selectors. Hopefully I can finish it at the end of this week. I would be busy since new semester has come though.

**Comment by dragonjet** [comment]
:+1:

**Comment by mdms-scott** [comment]
@dragonjet Out of curiosity, is the 800px limitation self imposed or some kind of actual restriction? (Modifying the css inline to increase the width of the table seems to show things fine)

**Comment by dragonjet** [comment]
@mdms-scott it's self-imposed, knowing that the game width is `800px` and most people would open the strategy room in the same window as the game

**Comment by mdms-scott** [comment]
@dragonjet Ahh, makes sense, although I would kind of assume that most people using the strategy room will also have the KC3 panel open and thus would have a wider window, but the column selector route makes it kind of unnecessary.  It occurs to me that the strategy room could be reactive I suppose?

**Comment by dragonjet** [comment]
hm I though about this in the first redesign i think around v10, but sticked to fixed 800px, for the purpose of this app, to make it look how we want it to, and is exactly the same for all users.

Other than this app, I use responsive layouts in all websites I make, which easily supports mobile phones and tablets, and desktop alike. However, this is not a website and will primarily be viewed from a desktop, which have a minimum of 800px for the game, so with both points imho we should stay fixed width.

Thanks for the suggestion though, made me think twice, and will keep this in mind from now on

**Comment by McDohl** [comment]
closed, can use the heartlock filter
