### ISSUE TITLE
Expedition-related Features

### ISSUE THREAD

**Issue by dragonjet** [KC3Kai/KC3Kai#722]
Moved to #821

**Comment by Javran** [comment]
I recall you are discussing deprecating the old theme somewhere before, for the panel, I think we can start working on the purposed view only for natsuiro since the old one is deprecating anyway (maybe need a branch instead of merging into the master branch, as I think there will be lots of work so don't expect it to come very soon).

And for the strategy room, I think that's not that urgent as we already have [a prototype](http://javran.github.io/tmp/expedition-plan.html) to play with.

But I need someone to cooperate on implementing these featues as I have no idea how to write an UI and put all stuff in it. btw is @bamboo3250 still interested in this?

**Comment by Crazyteitoku** [comment]
@Javran here is the link to the discussion of old theme: https://github.com/dragonjet/KC3Kai/issues/684

**Comment by bamboo3250** [comment]
@Javran I feel it would be better if I leave it to dragonjet or someone else since I will be busy in the next few months. Really sorry about that :pray:

**Comment by dragonjet** [comment]
alright I'll help with the panel UI, though we need to decide on how to integrate #685, via a separate devtools tab, or directly on natsuiro theme.

If natsuiro theme, I'm twisting my head checking where we can insert this XD

**Comment by Javran** [comment]
@Crazyteitoku thanks for the link, seems the opinion tends to set natsuiro as default but not clear about how to deal with the old one

@bamboo3250 don't worry about it, I'm also just taking my spare time doing this ;)

@dragonjet thanks for helping, do you like this idea:
we add a button right after "fit" and "screenshot", call it "expedition" or something, clicking on it opens up a view (just like battle mode before) and on top of it we can have whatever related to expeditions. (not sure if I'm actually introducing exactly the same old default-theme-vs-battle-mode  problem into natsuiro xD) and also in the new view, add a button in the same place to make it "toggable"

**Comment by dragonjet** [comment]
ah let's continue the UI discussion on #685

**Comment by Javran** [comment]
FYI, byproduct of my library: https://gist.github.com/Javran/07e07ef81638f2b9cec0#file-fuckgisteditoren-md fleet minimal cost composition for each expedition.

**Comment by Javran** [comment]
And for the strategy room, I've updated http://javran.github.io/tmp/expedition-plan.html to provide an option for numbers of available fleets. Can it be integrated into KC3改 and provide a better UI?

**Comment by dragonjet** [comment]
ah if we integrate the scorer table, does this close #301 or was it another?

I can see the second bullet on 301 is the scorer, but I think the first bullet already pertains to #685?

**Comment by Javran** [comment]
yep, #685 is for the first bullet and the scorer is for the second bullet. but to fully address the second bullet we need one more thing: a planner that user can sort ship list by resupply cost, morale, etc. and experiment fleet compositions (similar to the one in the devpage, this is to allow user try fleet compositions without operating on the game UI or affect the fleet composition in game)

**Comment by dragonjet** [comment]
ah one last question, this means #404 can also be closed because it will also be a part of #685?

I'm trying to fit the scorer table now on the actual strategy room, and see if the shiplist costs can still fit

**Comment by Javran** [comment]
yeah, I think so.

For the ship list cost, can it be placed on a separated page? this is actually what I'd prefer, because planning which expeditions to go and planning fleet composition for a certain expedition are two things.
But it's fine if the ship list can also be fitted into the same page.

**Comment by bamboo3250** [comment]
@dragonjet can I ask you what software you use to design HTML-based UI? Adobe Muse? :open_mouth:

**Comment by dragonjet** [comment]
@Javran Ah yes I was thinking the same thing, the exped table is already taking up the whole 680px strategy room width atm :laughing: 

@bamboo3250 Muse? Love Live? lol jk, I'm just using Adobe Flash, is the software grew up in since I was a kid, so the controls are more compatible for my hands.

**Comment by Javran** [comment]
also just for some future plan, having a separated page for ship list woud be better if we introduce a way to save and load fleet compositions, you'll also have an idea about which ship to sparkle next.

**Comment by nicky008** [comment]
Making a new room with 2 pages for it is not bad idea. The space for now is so being limited to do more detail explanations.

**Comment by Javran** [comment]
@dragonjet I see those help texts on Expedition Scorer page, and think this information would be helpful:

The minimal resupply cost is calculated base on this: https://gist.github.com/Javran/07e07ef81638f2b9cec0#file-expedition-minimal-costen-md
the table also includes a fleet composition for achieving the corresponding minmal cost

**Comment by dragonjet** [comment]
added

**Comment by ReiFan49** [comment]
![image](https://cloud.githubusercontent.com/assets/9847780/9656825/a8e24e6e-5265-11e5-96a4-e19278dd1c80.png)
randomly do this. (CSS messup,)

feature added
- expedition logger (simple mode, feel free to complete this)
- expedition listener (natsuiro only for now, feel free to complete this)
- expedition cancellation timer reaction

**Comment by Javran** [comment]
now we've immigrated to an org repo, I think we can open up a new branch for implementing these features, btw for now is someone working on the devpage part?

**Comment by dragonjet** [comment]
ah yes I've also started branches such as `dev-subtitle`, just recommend to prepend `dev-` for branches worked on

I'm not yet onto the expeditions, and still have some R&D going on for subtitles

**Comment by dragonjet** [comment]
Moving list to #821
