### ISSUE TITLE
Wrong Boss Gauge

### ISSUE THREAD

**Issue by dragonjet** [KC3Kai/KC3Kai#724]
"*Hi just want to highlight that there might be some calculations error(or dmg to meat shield hime counts in)with the event tab. Currently just started doing E6 hard. First run did 319 dmg to CV hime...2nd run sank her. So should be 319+350 = 669 HP gone but KC3 report shows 1920/2700 HP.*" - [Nexdea](http://kancolle.wikia.com/wiki/User_blog_comment:Dragonjet/KC3%E6%94%B9/@comment-Nexdea-20150822043113?permalink=313839#comm-313839)

Probably related to #662 where I suspect, when it's an overkill, and gives negative boss HP something goes wrong? I still haven't confirmed this.

**Comment by bamboo3250** [comment]
But does it really matter when we just get the actual data from KC server?

**Comment by dragonjet** [comment]
it updates when the user goes to the in-game map list, but right now as of #662 we manually deduct the boss HP damage to the local gauge. Some have complained they already did another kill and the gauage doesn't change in strategy room

**Comment by bamboo3250** [comment]
Oh I see. I didn't follow that change. I just skimmed through the code. I guess it is because when going to night battle, the original HP is not updated (still full HP) so the damage from day battle is added twice to the `gaugeDamage`.

**Comment by dragonjet** [comment]
I did opposite, followed the issue, but not the code, gg :laughing:

**Comment by ReiFan49** [comment]
`gaugeDamage` cannot increase over it's flagship HP (`gaugeDamage` is always calculated either in boss node or any flagship damage)

**Comment by bamboo3250** [comment]
```
if(this.gaugeDamage > -1)
			this.gaugeDamage = this.gaugeDamage + Math.min(this.originalHPs[7],this.originalHPs[7] - this.enemyHP[0].currentHp);
```

It is true if the player does not go into night battle. What if the `originalHPs` here is still the one before day battle? I believe the `setAsOriginalHP` is set to `false` so it will not be updated at night battle.

**Comment by dragonjet** [comment]
no similar reports this year, might have really been fixed by the patch that referenced this thread
