### ISSUE TITLE
New feature: daily equipment improvement list

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#738]
There is a list on [Chinese KC wiki](http://zh.kcwiki.moe/wiki/Template:%E8%A3%85%E5%A4%87%E6%94%B9%E4%BF%AE%E6%97%A5) for equipments that can be improved today. Maybe we can do something similar in KC3Kai's strategy room?

**Comment by NicolaosGreene** [comment]
If we did it would be wise to indicate which ships allowed for that improvement, possibly by tooltip. We could also have all the ones on that day show but the ones you don't have ships for greyed out.

**Comment by dragonjet** [comment]
Additional notes

* Going to the arsenal factory calls `api_req_kousyou/remodel_slotlist`
* No unique request params
* This will yield the following sturcture
```
{
	"api_result":1,
	"api_result_msg":"成功",
	"api_data":[
		{
			"api_id":101,
			"api_slot_id":2,
			"api_req_fuel":10,
			"api_req_bull":30,
			"api_req_steel":60,
			"api_req_bauxite":0,
			"api_req_buildkit":1,
			"api_req_remodelkit":1,
			"api_req_slot_id":0,
			"api_req_slot_num":0
		},
		{
			"api_id":232,
			"api_slot_id":27,
			"api_req_fuel":10,
			"api_req_bull":0,
			"api_req_steel":20,
			"api_req_bauxite":30,
			"api_req_buildkit":4,
			"api_req_remodelkit":2,
			"api_req_slot_id":0,
			"api_req_slot_num":0
		},
		{
			"api_id":332,
			"api_slot_id":46,
			"api_req_fuel":10,
			"api_req_bull":0,
			"api_req_steel":30,
			"api_req_bauxite":30,
			"api_req_buildkit":2,
			"api_req_remodelkit":1,
			"api_req_slot_id":0,
			"api_req_slot_num":0
		}
	]
}
```

Although we don't really need the API for this, since we'll need to hard-code improvable gear onto a separate JSON file, might as well add this while I'm playing

**Comment by LostLogia4** [comment]
@dragonjet So we can auto-update the improvement list whenever a new improvement option is introduced?

**Comment by dragonjet** [comment]
yep, though users will need to wait for next webstore release for them to see new options on the list, just like translations

**Comment by dragonjet** [comment]
update: there's an `akashi.json` in data folder.
it should contain equipment IDs per day,
with each one being an array of ships that can show it

too much work lel :laughing:

**Comment by LostLogia4** [comment]
I'm working on akashi.json now.

**Comment by dragonjet** [comment]
Added akashi tab on Strategy Room.
