### ISSUE TITLE
stype depends on the language?

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#746]
I recently switched to Japanese version and find `stype` of a ship is changed according to the language the user is using: while it expects `DD` as input, it actually gets `駆逐`. This breaks my script, is it possible to always use the English version of stype?

**Comment by dragonjet** [comment]
hm this might be a little difficult now since all translations are loaded via ajax synchronously at the start. The only way is to add a duplicate stype holder on `Meta.js` what loads english specifically.

**Comment by Javran** [comment]
is there any other ship type "identifiers" I can use?

**Comment by dragonjet** [comment]
stype itself is a number xD

**Comment by Javran** [comment]
I guess this also affects the docking time calculation. 

Today I found that when switching to Japanese version, it produces wrong result.

![2015-09-05_185623_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/9701624/235f0d94-5400-11e5-8372-b1e6fafe429d.png)

![2015-09-05_185702_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/9701625/265e9bb8-5400-11e5-90ef-30b84a9fbedf.png)

**Comment by dragonjet** [comment]
is it possible to pass in  the stype number like in

`src\data\translations\en\stype.json`

the numbers are actually the one on game data with `api_stype`, the shiptype codes are even taken from json so there's also an additional conversion just to pass it into the helper functions

**Comment by Javran** [comment]
so `stype` number are corresponding to array indices of `src/data/translation/<lang>/stype.json` ?

if they are consistent, I can adapt the API.

**Comment by dragonjet** [comment]
yep, they are consistent, and actually has its own entry in the game master data:

http://kancolle.ageofturb.com/decodes/2015-08-21_16-23/stype-2

**Comment by Javran** [comment]
ah nice, will be working on it.

**Comment by Javran** [comment]
I just added two new API in commit 7cc7353

 * `dockingInSecJSNum(stypeId, level, curHp, maxHp)`
 * `facilityInSecJSNum(stypeId, level, curHp, maxHp)`

they are almost `dockingInSecJS` and `facilityInSecJS` except that first arg is a number instead of a string.

Can someone adjust the repair time calculation to use these two API?

**Comment by nicky008** [comment]
@Javran what's the different between `curHp`, `maxHP` and normal `HP`? Are these new args for the newly APIs?

**Comment by dragonjet** [comment]
@nicky008 ah these are the parameters we'll need to pass to @Javran's functions, and is implemented on `Ship.js:repairTime()`

**Comment by nicky008** [comment]
@dragonjet Don't mind. I just understand it now. :3

**Comment by Javran** [comment]
I just pushed e6341c33 for fixing the `stype` problem for legacy theme.
