### ISSUE TITLE
[Poll] Timer mode toggle

### ISSUE THREAD

**Issue by bcc32** [KC3Kai/KC3Kai#748]
Do others think it would be useful to have the timers for morale recovery, repair time, etc. be able to toggle between remaining time and time of completion (i.e., on the clock)?  I'm thinking of adding it but I don't want to bother too much if it's not needed.

**Comment by ReiFan49** [comment]
akashi time vs repair time,
akashi time requires maximum number of repair facility + akashi (1 akashi = 2 ship, 1 repair facility = +1ship)

repair time requires stacked over waiting the docks

**Comment by bcc32** [comment]
Well Akashi can repair two ships without repair facility but one of those has to be Akashi herself.  Also Akashi repair doesn't work on ships that are chuuha/taiha.

What I meant in the original post, though, was to toggle between [2:30 remaining] and [will finish at 5:30 p.m.] (assuming the current time is 3 p.m. for example).

**Comment by dragonjet** [comment]
hm that's actually good, if you're going AFK because of morale, and instead of adding 03:33:00 to your current time which might need some basic time arithmetic where not everyone is good at

**Comment by ReiFan49** [comment]
![image](https://cloud.githubusercontent.com/assets/9847780/9716236/f96c5b8e-5591-11e5-8df6-e42980f1907b.png)
(since i haven't tried the cannot repair on previous ver, before this patch come)
is this ok?

**Comment by bcc32** [comment]
eb9dd2a6

**Comment by minhhieu98587** [comment]
but how download work
kancolle why error please help me!!

**Comment by bcc32** [comment]
@minhhieu98587 Is your question related to this feature?  If not, please open a new issue so that it is easier to track.
