### ISSUE TITLE
Subtitles when shipgirls speak

### ISSUE THREAD

**Issue by dragonjet** [KC3Kai/KC3Kai#751]
Yes, just like in the animes, when a shipgirl speaks, add an overlay on what she said

**Comment by ReiFan49** [comment]
some of the scene might interrupt the moment they're talking,
also we need to guess/find out the duration of each dialogue...

(and a new json~, use array of kanmusu voice for easier on formatting)

**Comment by dragonjet** [comment]
ah you can check the `dev-subtitle` branch, I got it working only for U-511 kai for now, and the start game voices. The duration is `2 sec + (each character of the quote x 50 millisec)`

**Comment by LostLogia4** [comment]
Can we add an option to leave it out of battles? Cuz it'll be a handful when you're in a tight battle like in E7.

**Comment by dragonjet** [comment]
What happens right now is that the subtitles overrwrite for the latest one who spoke, they won't overlap nor show together, so it'll always just be a readable one-line/two-liner

atm there are 270+ shipgirls supported, but there's alot more i think 100+ missing

**Comment by bamboo3250** [comment]
I just tried the `dev-subtitle` branch. How to activate this feature? I'm so hyped for this one :laughing:

**Comment by SerialConvort** [comment]
Yeah I would like to know this as well.

**Comment by dragonjet** [comment]
hm I messed up the branch actually XD
pulled in from master, which I shouldn't have done.

but to get a preview of this, when you checkout to `dev-subtitle` branch, you'll need to reload the extension because there are edits to `Service.js` which is the background script running for chrome, so simply refreshing will not work. Restarting browser will work too.

At my latest test now it works on the game start voices but doesn't show when you get to the home port onwards. I will see what happened, but it should be minor thing I left out when the branch got messed up.

What I'm planning in moving forward is to copy specific code edits from the branch and start a new `dev-subtitle2` coz the current one idk so messed up. This taught me never to pull from master for feature branches.

**Comment by dragonjet** [comment]
by the way @nicky008 what do we put for these 3 subtitles on akashi shops and ooyodo quest page

http://125.6.189.247/kcs/sound/kc9999/1.mp3
http://125.6.189.247/kcs/sound/kc9999/2.mp3
http://125.6.189.247/kcs/sound/kc9999/3.mp3

**Comment by dragonjet** [comment]
alright re-implemented the branch, now `dev-subtitles` with S. so you may need to pull all branches again. using the same reminders as above, you may now see subtitles working if you checkout to this new branch

**Comment by bamboo3250** [comment]
Yay, excited to check it :laughing:

**Comment by bamboo3250** [comment]
@dragonjet I tried and got this error

![screen shot 2015-09-11 at 4 43 35 pm](https://cloud.githubusercontent.com/assets/8078323/9810597/7573034e-58a4-11e5-99fa-22e0be4cf2d1.png)

**Comment by dragonjet** [comment]
oh there are no quotes for `vi` :v
switch to `en` for the moment xD

**Comment by bamboo3250** [comment]
right, I realized it just now. will use `en` temporarily then xD

**Comment by bamboo3250** [comment]
Yes, it works :laughing: :+1: 

![screen shot 2015-09-11 at 4 47 44 pm]:(https://cloud.githubusercontent.com/assets/8078323/9810671/f484ce38-58a4-11e5-92d7-ac32884e7996.png)

**Comment by dragonjet** [comment]
ah not everyone is supported yet though, iirc starting from Hiryuu Kai Ni onwards, in the time of release, not library number.

I remember I had a JSON file of all quotes back when I was working for himeuta.net. But that was a long time ago and ships released and remodeled after that don't have quotes yet.

**Comment by bamboo3250** [comment]
I guess the `quotes.json` will be the biggest file ever in KC3Kai. It now has nearly 10k lines and is still increasing :open_mouth: 

Btw, it still shows subtitles whenever I go to home port. Do you hear your secretary's voice when going to home port? @dragonjet

**Comment by dragonjet** [comment]
oh my I didn't notice `515kb` and not yet complete, multiply that with all languages, and we get a big bang

**Comment by LostLogia4** [comment]
How are we gonna fit all that texts into the extension? Not to mention who's gonna handle the quote updating?

**Comment by dragonjet** [comment]
every season at that

**Comment by LostLogia4** [comment]
Only sane way I could think to do this is to build a quote database in kancolle wikia and use it use it as reference on kc3kai... but...

**Comment by bamboo3250** [comment]
@dragonjet they do but you mentioned that it didn't work in the comment above :sweat_smile: 

`At my latest test now it works on the game start voices but doesn't show when you get to the home port onwards. I will see what happened, but it should be minor thing I left out when the branch got messed up.`

**Comment by dragonjet** [comment]
ah that was before I fixed the branch into `dev-subtitles` with S :laughing:

**Comment by bamboo3250** [comment]
but then if we use wikia as data source, can we somehow translate it into other languages?

**Comment by dragonjet** [comment]
oh mai headaches, good thing we started doing branching coz this will take time to figure out and finalize. onward to v30 :v

**Comment by nicky008** [comment]
@dragonjet Now I can't check because the `jp` is still being messed up. :v

(But, don't mind. I used my friend's PC and it works now on `en`.)

**Comment by dragonjet** [comment]
on the `dev-subtitles` branch?

**Comment by nicky008** [comment]
Yes...

**Comment by Fujihita** [comment]
You can always offer different language builds, or downloadable language packs using the updater (after the user chooses a language in the setting or something).

**Comment by dragonjet** [comment]
hm the problem with dynamic files is that chrome treats it as "corrupted" if it detects a file that wasn't present when it was first installed. The same reason why sound files should be online URL and not local XD

**Comment by bamboo3250** [comment]
@dragonjet Can I add `quotes.json` for `vi`? :grin:

**Comment by bamboo3250** [comment]
btw, whenever I switch to subtitles branch, this error also pops up 

```
git -c diff.mnemonicprefix=false -c core.quotepath=false -c credential.helper=sourcetree checkout dev-subtitles 
M	src/data/lang
Your branch is up-to-date with 'origin/dev-subtitles'.
Switched to branch 'dev-subtitles'


git -c diff.mnemonicprefix=false -c core.quotepath=false -c credential.helper=sourcetree submodule update --init --recursive 
No submodule mapping found in .gitmodules for path 'src/data/lang'
Completed with errors, see above
```

Should I just ignore it?

**Comment by dragonjet** [comment]
I am unsure what that is, try pulling latest `dev-subtitles`?

**Comment by bamboo3250** [comment]
I think that is because the `dev-subtitles` branch is created before the submodule but I'm not sure how to resolve it. I'm on the latest `dev-subtitles`

**Comment by dragonjet** [comment]
@bamboo3250 I pushed the submodules onto the subtitles branch, can switch to it, pull, switch master and switch back?

**Comment by bamboo3250** [comment]
<a href="http://www.youtube.com/watch?feature=player_embedded&v=4d4sGi4Ru_0
" target="_blank"><img src="http://img.youtube.com/vi/4d4sGi4Ru_0/0.jpg" 
width="240" height="180" border="10" /></a>

Finally I can marry Verniy. It was a very long journey. Above is the first experience of marriage with subtitle in KC3Kai :blush:

**Comment by Agc0de6** [comment]
@bamboo3250, Verniy says: "//// Боже мой, you are embarrassing me... ////"

**Comment by bamboo3250** [comment]
Talk to Verniy: "Haha that's nothing to be embarrassed of."

Verniy is one of my DDs that have been with me from the very first day after all :laughing:

**Comment by Crazyteitoku** [comment]
Oh wow, congrats @bamboo3250! Now soon @LostLogia4's marriage is due as well, in ~9 days time.

**Comment by LostLogia4** [comment]
There is a large schedule gap in my college timetable so I don't have to delay my marriage by too much, for better or worse..

**Comment by dragonjet** [comment]
@bamboo3250 can I use your marriage picture with subs to post on the facebook page? can I mention your name?

**Comment by bamboo3250** [comment]
@dragonjet ah yes, just mention me as bamboo3250 :+1:

**Comment by dragonjet** [comment]
OH! I didn't see it was clickable XD

**Comment by mdms-scott** [comment]
@dragonjet sorry for posting in an old thread, just happened to stumble on this. What happened to this branch? dev-subtitles doesn't seem to have been updated in quite some time?

**Comment by dragonjet** [comment]
@mdms-scott we only have quotes for a few girls. It's just a matter of copying them from the wikia, but we don't have a manpower for it - but before that we haven't finalized on the process on how to do it. @bamboo3250 made a module on the KC3 Website for people to contribute and copy-paste quotes from the wikia, but our website it down at the moment :sweat_smile:

**Comment by LostLogia4** [comment]
just so you know, the ship voices has version params as well, same as api_version in api_mst_shipgraph. Only exceptions are those whose api_version is 1, which doesn't have the params in the link at all.

**Comment by dragonjet** [comment]
@LostLogia4  ah yes this is a problem we need to address together with seasonal lines

**Comment by mdms-scott** [comment]
@dragonjet got bored this evening and hacked https://github.com/mdms-scott/kk_wiki_scraper together.  Need to clean it up some, work out the last few corner cases, and get the data structure to actually line up, but it sure beats copying and pasting everything.

**Comment by dragonjet** [comment]
oh this looks very nice, I'll try some of your files in `/output` :+1:

**Comment by Javran** [comment]
just an idea: could https://crowdin.com/ be used for moving subtitles from wikia or other sources for other languages? I saw other softwares are using it for outsourcing i18n stuff. and it works fine.

**Comment by dragonjet** [comment]
Update: `dev-subtitles` branch working again, with the help of @gakada's functions and the mapping idea from the poi mod. which involves voiceline mapping, by looping all 500 ship IDs and looping all voicelines to generate all filenames each tagged with its voice line number. then when the voice is loaded just lookup the filename from the mapping and you already have the line number. with that, you can easily determine which quote that was.

**Comment by dragonjet** [comment]
I'll be keeping this open until we're done double-checking subtitles at

https://docs.google.com/spreadsheets/d/1wg7pCv3l6g8BfOye3-DbrCuYDhTvSX4h1UuiRCp0_K8

**Comment by dragonjet** [comment]
since most fixes were done by @nonesensed, closing this.

If there are other correction, let's make a new thread, and specifying a small list of those that still need edits.
