### ISSUE TITLE
Automatic Game Starting

### ISSUE THREAD

**Issue by JD-Kurotoshigami** [KC3Kai/KC3Kai#752]
been busy with other things that i forgot to mention this...
Why does the game automatically start when clicking "Play via API Link" (before clicking "Start the Game Anyway"
I hear the game start voices when the page loads and if I'm fast enough(click the "start the game anyway,cpu, and net) it shows the game's "Game Start" then refreshes...

**Comment by dragonjet** [comment]
dats not possible :open_mouth:

**Comment by JD-Kurotoshigami** [comment]
it happens to me though... 'happens' not 'happened' :)

**Comment by JD-Kurotoshigami** [comment]
btw by refreshes I mean just like what happens when you click the green circle 5 times

**Comment by ReiFan49** [comment]
i remember i have met something like this..
that's why i put about:blank as the iframe source though,

i wonder if its related to cache or something...

**Comment by dragonjet** [comment]
hm first time I've heard about this though, out of all playthroughs this is the only report of its kind.

I'm not sure about cache though, it is possible if you use Ctrl+Shift+T to reopen the game with some states retained from the last you closed it, but accessing it via menu sounds very unlikely to me.

Does it happen most of the time or all the time?

We might get around this by setting iframe src to blank via script on document load, but it was supposed to be blank in the first place. The API link URL is not attached to the iframe until you click the `Start game anyway` button.

**Comment by ReiFan49** [comment]
```javascript
function ActivateGame(){
	waiting = false;
	$(".box-wrap").css("background", "#fff");
	$(".box-wait").hide();
	$(".box-game")
		.prepend("<iframe class=game-swf frameborder=0></iframe>")
		.find(".game-swf")
		.attr("src", localStorage.absoluteswf)
		.end()
		.show();
	$(".box-wrap").css("zoom", ((ConfigManager.api_gameScale || 100) / 100));
}
```
should we do this?

**Comment by NicolaosGreene** [comment]
I can say that I have experienced this bug as well. Though I never bother clicking fast enough to see if it refreshed on me.

**Comment by dragonjet** [comment]
no similar reports this year, might have really been fixed by the patch that referenced this thread
