### ISSUE TITLE
Battle Prediction doesn't work after the update

### ISSUE THREAD

**Issue by bamboo3250** [KC3Kai/KC3Kai#769]
most recent PvP battle data http://pastebin.com/Xn2qcGRg
@Javran if you are interested

**Comment by ethrundr** [comment]
oh @bamboo3250 opened this first...
was opening the same issue at #770

**Comment by bamboo3250** [comment]
@ethrundr I also saw yours just now lol. I'll try normal sortie to see if this happens there or not but very likely thing will be the same.

**Comment by bamboo3250** [comment]
Yup, same problem happens in normal sortie as well

Battle data: http://pastebin.com/9QUVYCLa

**Comment by Javran** [comment]
@bamboo3250  I have tried both of your data, it seems to work:
![2015-09-07_043900_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/9712748/d5024eb0-551a-11e5-9315-7c0aa405954e.png)

![2015-09-07_044225_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/9712751/d8313ad8-551a-11e5-845b-e71f9bd6c2fa.png)

Do these results look good?

**Comment by bamboo3250** [comment]
Yes, those results are correct. Then we need more investigation into this :sweat:

**Comment by LostLogia4** [comment]
Even with the battle prediction off the enemy parameters simply won't show up.

**Comment by Javran** [comment]
At least the lib still works, on the bright side, they doesn't seem to change the data format or remove fields from it (like last time).

**Comment by dragonjet** [comment]
someone reported on facebook too, will try playing after i finish wikia patch notes

**Comment by admiralpoi** [comment]
Missing the enemies, condition, and air battle results on live sortie. It is still recorded and displayed properly in strategy room though
![untitled](https://cloud.githubusercontent.com/assets/13688790/9713024/f51b333e-5578-11e5-81b1-1081d210950a.jpg)

**Comment by bamboo3250** [comment]
Okay, I get the reason. The `PlayerManager.combinedFleet` now becomes `undefined` instead of `0` so it redirected the battle data to `result = DA.analyzeRawSurfaceTaskForceBattleJS(battleData); `.

**Comment by dragonjet** [comment]
ohh nice can you guys try pushing directly without pull-request, we haven't tried that before, I wanna see it work first :laughing:

**Comment by dragonjet** [comment]
oh yay! look we can assign anyone now :v

**Comment by bamboo3250** [comment]
okay, I'll try pushing the fix in a few minutes xD
