### ISSUE TITLE
Update new quests after update

### ISSUE THREAD

**Issue by bamboo3250** [KC3Kai/KC3Kai#771]
New Sortie quest
```
{
        "api_no": 286,
        "api_category": 2,
        "api_type": 1,
        "api_state": 1,
        "api_title": "鎮守府正面の対潜哨戒を強化せよ！",
        "api_detail": "鎮守府正面の対潜哨戒を強化し、海上資源輸送路の安全を確立せよ！",
        "api_get_material": [
          300,
          300,
          0,
          0
        ],
        "api_bonus_flag": 1,
        "api_progress_flag": 0,
        "api_invalid_flag": 0
      },
```

New PvP quest
```
{
        "api_no": 311,
        "api_category": 3,
        "api_type": 6,
        "api_state": 2,
        "api_title": "精鋭艦隊演習",
        "api_detail": "同日中に「演習」で7回以上「勝利」をおさめ、我が精鋭艦隊の練度を示そう！",
        "api_get_material": [
          0,
          400,
          0,
          200
        ],
        "api_bonus_flag": 1,
        "api_progress_flag": 0,
        "api_invalid_flag": 0
      }
```

**Comment by McDohl** [comment]
missing 1 more sortie quest, the 3-5

**Comment by ethrundr** [comment]
Unfortunately, the prerequisites for the 3-5 quest is still a mystery, so I can't help on getting the data :(
Haven't unlocked it myself....

**Comment by McDohl** [comment]
{"api_no":285,
"api_category":2,
"api_type":1,
"api_state":2,
"api_title":"「空母機動部隊」北方海域に進出せよ！",
"api_detail":"航空母艦を旗艦とした空母機動部隊を北方AL海域方面に展開、敵戦力を撃滅せよ！",
"api_get_material":[500,0,500,0],
"api_bonus_flag":1,
"api_progress_flag":0,
"api_invalid_flag":0}

**Comment by dragonjet** [comment]
I'll do it, yes it's just usually copied from wikia xD

**Comment by nicky008** [comment]
@McDohl I'm just doing another section, EN to JP section. :3

**Comment by McDohl** [comment]
@nicky008 :open_mouth: I was thinking maybe gonna tag you because you are the one doing EN to JP xD

**Comment by ethrundr** [comment]
OOT for a while, how to unlock that 3-5 quest XD

**Comment by McDohl** [comment]
you need to clear 6 subs daily quest xD

**Comment by ethrundr** [comment]
gosh... daily 6 subs....
