### ISSUE TITLE
[Suggestion] Lighter Background, maybe?

### ISSUE THREAD

**Issue by ethrundr** [KC3Kai/KC3Kai#773]
Little bit hard to read the text, especially on bright screen.....
![screen shot 2015-09-07 at 18 53 15](https://cloud.githubusercontent.com/assets/13522800/9714277/cfa6e1a2-5591-11e5-9b84-3b0e45047373.png)

Maybe make the background lighter or the text darker is a better.....
Also, while we're at this, how about adding the tooltip, explaining WHY it is danger?
After reconsidering, putting only "Danger" text somehow is not really convincing enough......

**Comment by nicky008** [comment]
Lighter BG or Darken font?

* IMO, I think the text should be darker (black font as the old way with red BG is enough).
* The `charsize` is not enough for now. You might need other responsive ways like moving the box down to the below or popup click for double-checking.

**Comment by ReiFan49** [comment]
double checking? already done i guess ?
![image](https://cloud.githubusercontent.com/assets/9847780/9714723/17e821aa-5584-11e5-8883-aed74557349b.png)

**Comment by dragonjet** [comment]
ah just a heads up, I'm also planning to change the settings page for a bit. There had been multiple instances that users ask what this is, what it does, and one user was even frustrated he was like "it's like you want us to guess what each of these does" or something like that. Well it's true, and we need tooltips or description for each setting, apart from the wiki, where we do not have time to update xD

**Comment by ethrundr** [comment]
@ReiFan49 what I mean is not double-check, but a short explanation of why we declare that as dangerous setting. User need to know about that without need to open the wiki.

If the tooltip can be implemented on each setting it's better, but we also can do the approach of creating a F.A.Q menu on the client extension. Here, everything the user should and would like to know is provided.

**Comment by nicky008** [comment]
Hmm, so the next point is adding more short descriptions and also have an easy way to read them.

Personally, I think we need more minor restructurings in setting page architecture, as the newer and newer options are keep growing today. This is one of more steps needed to do in the future.

**Comment by ethrundr** [comment]
I do think expandable sections are good idea to be implemented, as it will help user find the section he wanted to, and need not to navigating through the whole setting page just to find one item....

**Comment by dragonjet** [comment]
@ReiFan49 I'd also wanna take over this, wanna do a run-through of all layouts and whatsoevers, will also add those descriptions per setting for 19.2 this friday

**Comment by nicky008** [comment]
I'm waiting to see this, need centralized UI.

**Comment by ethrundr** [comment]
So all layout and UI are now being reworked by @dragonjet eh?

**Comment by Crazyteitoku** [comment]
@dragonjet mind you the event was hectic and there was only really one wiki documenter at the time whom happens to just be busy trying to do many things at once :laughing:

Anyway with now KC3 Kai project being assigned as an organisation perhaps the burden on me alone is somewhat lessened. I'll try and pull my weight to get more documentation up but there's no guarantees that people will read them just like how it is for every other wiki websites. :+1:

**Comment by Crazyteitoku** [comment]
Lel I can't assign more than one person. Stuff it, I'll have a look at writing more documentation up later on.

**Comment by ethrundr** [comment]
anyway for the warning last line:
"Make sure you're know what to do before"
Seems bit off...

Thus, I suggest to change it to:
"Make sure you know what you are going to do"

**Comment by dragonjet** [comment]
lol where is this, alright @Crazyteitoku no rush :v

**Comment by ReiFan49** [comment]
terms.json `SettingsChuuiWarningDangerousFeature` key (ps: 注意=>chuui)

**Comment by dragonjet** [comment]
closing this in favor of the settings redesign at #810
