### ISSUE TITLE
Expedition related: ship grouping

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#774]
maybe this can be added to #722 

the idea is to have some groups of ships that run expeditions together, this might be good when doing ship sparkling.

as we are also planning for a strategy room page for expedition-ship selection, this can be combined into that page.

**Comment by dragonjet** [comment]
hm there was a similar idea back on the days where users can save a list of fleets, and he can name it what he want "E-7 debuff", or "Exped 21", which will be useful not only for expeditions but for all instances where you need to remember a specific compo.

Right now what people do is go back to the sortie history to check which ships were used, but having a dedicated system to remember compositions wouldn't hurt.

There are remnants of this idea on the current version, as seen on Strategy Room, there is a disabled tab under "Fleet", named "Teams"

**Comment by Javran** [comment]
originally my idea is to make it easy when looking for non-sparkled ships to sparkle, and now ship list does this very job well. and also now we can view history fleet compo through fleet manager. I'd say this issue can be considered done.
