### ISSUE TITLE
[Asset Bug] Image not appearing

### ISSUE THREAD

**Issue by ethrundr** [KC3Kai/KC3Kai#777]
Don't know whether this only me or not, but this what I get whenever my expedition is returning
![screen shot 2015-09-07 at 22 49 19](https://cloud.githubusercontent.com/assets/13522800/9718013/e0079bce-55b2-11e5-9450-9d797729f14d.png)
This was expedition 2, which the item supposed to be bucket.

My latest build was e5056c9

**Comment by bamboo3250** [comment]
I just checked the api data returned when Exp 2 came back. I got a bucket but the api data showed the item id as -1 while it showed the id as 10 for small coin box. It's really weird.

**Comment by ethrundr** [comment]
Just got my expedition 21 returned, and yes, the furniture box icon is appearing normally

**Comment by McDohl** [comment]
steel text also is hard to see

**Comment by ethrundr** [comment]
Ah now you mention it...
Ammo and steel text need to have lighter color....

**Comment by McDohl** [comment]
or maybe get it's own div like resources node
![image](https://cloud.githubusercontent.com/assets/13024936/9720643/392d1a60-55ba-11e5-8113-feb712fe73f3.png)

**Comment by ethrundr** [comment]
It's better, and yet, the user also able to directly distinguish what resources they got and how many each...

**Comment by ReiFan49** [comment]
![image](https://cloud.githubusercontent.com/assets/9847780/9720901/3ea099ba-55bd-11e5-9509-d900025d6867.png)
i still don't understand what does the number mean from 1 to 3 on `api_useitem_flag`

(also, i just rushed before ownership transfer.. those materials actually planned to have background color like the construction color)

**Comment by ethrundr** [comment]
@ReiFan49 so the one doing this is you.....
I'm not surprised anymore then to see bugs here and there on this feature :laughing:

**Comment by dragonjet** [comment]
@ReiFan49, can I do the layout for the expedition activity?

**Comment by ReiFan49** [comment]
whoa, it's ok, my one just placeholder though ....

**Comment by dragonjet** [comment]
pushed a resigned that looks like this, but does not fix missing icons because I don't know how to generate the empty result xD

![ss 2015-09-08 at 07 49 29](https://cloud.githubusercontent.com/assets/557312/9734319/9463b8a8-5664-11e5-9b45-eceb53d7ed92.jpg)

**Comment by nicky008** [comment]
We can put the missed icon later but for now, it's really looking "far better" than the past. :relaxed:

**Comment by ReiFan49** [comment]
@dragonjet  the great success translation based on `.exp_status[0123]` class or not xD ? (i forgot to implement the css style for that lol)

missing items are hidden by default for now, as per one of my commit

**Comment by dragonjet** [comment]
@ReiFan49 ah nope, I figured it will stay gold  even on GS, success or fail. User will figure out coloring by the image.

**Comment by ethrundr** [comment]
wow the new UI looks very nice~

**Comment by ethrundr** [comment]
@dragonjet I got this one now......
![screen shot 2015-09-09 at 11 17 01](https://cloud.githubusercontent.com/assets/13522800/9751824/68b8a4cc-56e4-11e5-9934-b1c2c850ad54.png)

Since it's local asset, I think there is nothing to do with my connection, is it?

**Comment by dragonjet** [comment]
whoops! i forgot to include the images onto the commit :laughing:

**Comment by ethrundr** [comment]
lol @dragonjet :laughing:

**Comment by dragonjet** [comment]
pushed

**Comment by ethrundr** [comment]
it's working now! XD
![screen shot 2015-09-09 at 11 56 34](https://cloud.githubusercontent.com/assets/13522800/9752337/e7d64b06-56e9-11e5-82ab-8060b056f7aa.png)

**Comment by ReiFan49** [comment]
is cancelled expedition equal to failure expedition per current commit? (haven't checked, class in 1 minute)

**Comment by dragonjet** [comment]
@ReiFan49 right now the image is both fail for canceled and real fail, but the text follows what you added before. Doesn't use classes though

**Comment by ethrundr** [comment]
@ReiFan49 I'll test for it.

**Comment by McDohl** [comment]
@dragonjet steels and ammo gain are swapped xD

**Comment by lackofdream** [comment]
It still shows that I got nothing while in fact i got a bucket.
![screenshot_2015-09-09_17-02-55](https://cloud.githubusercontent.com/assets/8641779/9756429/1a3c577c-5715-11e5-8662-bd08e4bd97d4.png)
![screenshot_2015-09-09_17-05-21](https://cloud.githubusercontent.com/assets/8641779/9756431/24142a72-5715-11e5-9084-8f143221523c.png)

**Comment by ethrundr** [comment]
oh lol I don't even realize that :laughing:

**Comment by freezebear** [comment]
ermm.. how about Furniture Box? i got a small size, but the indicator is medium size.. 
![image](https://cloud.githubusercontent.com/assets/12047229/9756505/4ac5eb4a-570d-11e5-839b-18111faf96e3.png)

**Comment by ethrundr** [comment]
@freezebear ah I already reported that as well XD

**Comment by freezebear** [comment]
hue... didn't see it.. sorry.. =w=;

**Comment by ethrundr** [comment]
np. by having more report it assure that the error is not on my side only.
actually second report is somehow necessary when dealing with bugs....

**Comment by dragonjet** [comment]
oh wait is @lackofdream a new dev build tester? we haven't released that UI on webstore

and true @McDohl steel and ammo are swapped :sob: its because it's `float:left` so it'll be clockwise, but in-game is counter clockwise :sob:

**Comment by ReiFan49** [comment]
@dragonjet on that case, devs make some mistake on value mapping.
like api_deck and spi_deck, yet i still unable to figure out how to tell these kind of data bug from the kancolle client itself.

**Comment by nicky008** [comment]
If the devs used `0` or `1`, I'd not be surprised much.

But... hey, `-1`? Srsly devs? :sweat_smile:

**Comment by ethrundr** [comment]
lolwut...... `-1` for bucket.....
I won't be surprised if later on we have item with ID `-2` and so on then :laughing:

**Comment by bamboo3250** [comment]
We need to check for the flamethrower and devmat as well. Don't know what is the value of them.

**Comment by nicky008** [comment]
@bamboo3250 I heard the Furniture Box also has the wrong mapping value too.

**Comment by bamboo3250** [comment]
yes, It was correct before so I think it's just a minor bug. It can be fixed soon but if we don't know the other two items' values, we cannot move on.

**Comment by bamboo3250** [comment]
We can try Expedition 7 (1 hour) for the flamethrower and Expedition 20 (2 hours) for the devmat.

**Comment by McDohl** [comment]
I'm running expedition 16 atm (it gives 2 torches and 2 devmats), but it will need lots time 14 hours left xD

**Comment by bamboo3250** [comment]
Okay, I'm doing both 7 and 20. Hopefully they will come out xD

**Comment by ReiFan49** [comment]
minor mapping values comes out due to the array starts from index of zero, and the useitem id **requires non-zero index** instead, 

(ps: check 8a398c37c89dfd31ba530ad09f2a0cd4371927d6)

**Comment by bamboo3250** [comment]
Flamethrower
`"api_useitem_flag":[2,0],"api_get_item1":{"api_useitem_id":-1,"api_useitem_name":null,"api_useitem_count":1}}}`

Devmat
`,"api_useitem_flag":[3,0],"api_get_item1":{"api_useitem_id":-1,"api_useitem_name":null,"api_useitem_count":1}}}`

So I assume for bucket, flamethrower and devmat, they use `api_useitem_flag` instead of `api_get_item1`.

**Comment by ReiFan49** [comment]
ah, maybe that answers what i'm confused about `api_useitem_flag` thing.....
fixing my commit before pushing it then..

**Comment by bamboo3250** [comment]
greate :+1: 

btw, when there is no item, it can be like this `,"api_useitem_flag":[0,0]}}` (`api_get_item1` is `undefined`)

**Comment by ReiFan49** [comment]
oh lol, i messed up with the branch..... 
![image](https://cloud.githubusercontent.com/assets/9847780/9777249/c19ef5c6-578b-11e5-879e-70b4e8443763.png)

**Comment by dragonjet** [comment]
seems I'm the only one on this end of the world's timezone, everyone is on while I sleep XD

This might have helped if I liked it earlier
http://kancolle.ageofturb.com/decodes/2015-09-07_15-48/useitem-1
http://kancolle.ageofturb.com/decodes/2015-09-07_15-48/useitem-2
http://kancolle.ageofturb.com/decodes/2015-09-07_15-48/useitem-3
and so on..

here are the numbers:
http://kancolle.ageofturb.com/decodes/2015-09-07_15-48/useitem

**Comment by ethrundr** [comment]
which timezone are you in XD
well at least I can tell that me and @ReiFan49 constantly pulling an all-nighter, especially on weekends, so don't mind with our online times :laughing:

**Comment by dragonjet** [comment]
oh I'm at gmt+8, almost same time as JP

**Comment by ethrundr** [comment]
+7 here~

**Comment by NicolaosGreene** [comment]
I am -6, but I keep exceptionally odd hours

**Comment by LostLogia4** [comment]
GMT+8 on my area here. Just saying.

**Comment by dragonjet** [comment]
@LostLogia4 what country? we might be neighbors :v

**Comment by LostLogia4** [comment]
@dragonjet Pretty sure that I'm not living anywhere near your home though, since Brunei was a sea voyage away from where I live. And this is one of the country near where I live.

**Comment by nicky008** [comment]
+7 but not in the same country as @ethrundr :kissing_smiling_eyes:

**Comment by ethrundr** [comment]
@nicky008 so the only one confirmed to living near so far just me and @ReiFan49 eh....
actually we're not that near, we live in different city, but occasionally we met with each other, so yeah, can be counted as "near", right? :laughing:

**Comment by nicky008** [comment]
can be counted though :wink:

**Comment by Crazyteitoku** [comment]
GMT +10h here

**Comment by McDohl** [comment]
i'm using https://github.com/KC3Kai/KC3Kai/commit/450573017a55fd59080c607cd33db8e3c7cb0910 version. and got this error
![image](https://cloud.githubusercontent.com/assets/13024936/9795005/8423add0-5818-11e5-88b5-bf178d906b98.png)

this is the api info 
```
svdata={"api_result":1,"api_result_msg":"\u6210\u529f","api_data":{"api_ship_id":[-1,649,338,1694,1243],"api_clear_result":2,"api_get_exp":80,"api_member_lv":107,"api_member_exp":4165134,"api_get_ship_exp":[120,80,80,80],"api_get_exp_lvup":[[324390,331000],[287044,296200],[188348,188500],[92517,94600]],"api_maparea_name":"\u93ae\u5b88\u5e9c\u6d77\u57df","api_detail":"\u8f38\u9001\u8239\u56e3\u306e\u5b89\u5168\u3092\u56f3\u308b\u305f\u3081\u306b\u3001\u8239\u56e3\u306b\u540c\u884c\u3057\u3066\u3001\u3053\u308c\u3092\u8b77\u885b\u3057\u3088\u3046\uff01","api_quest_name":"\u6d77\u4e0a\u8b77\u885b\u4efb\u52d9","api_quest_level":3,"api_get_material":[300,300,30,30],"api_useitem_flag":[0,0]}}
```

**Comment by ReiFan49** [comment]
it's semicolon and comma issue though,
fixing on latest commit

**Comment by ethrundr** [comment]
Isn't it better to show how much of the item we get? Just the icon like this is kinda confusing on how much item we get:
![screen shot 2015-09-11 at 13 27 01](https://cloud.githubusercontent.com/assets/13522800/9807083/fa0e7a8c-5888-11e5-8548-2f87747cbd48.png)

Expeditions will only gives at most two kind of items, so there is no need to reserve spaces....

**Comment by nicky008** [comment]
Just adding only one char more for a number of item is not bad though, abundant spaces on dat line...

**Comment by ReiFan49** [comment]
@dragonjet forgot to change span to `.expres_item_text` :laughing:

**Comment by dragonjet** [comment]
aye let me check that XD

**Comment by ReiFan49** [comment]
gonna push it xD

**Comment by dragonjet** [comment]
I put it back as `<div>` of latest commit, I doubt it will follow width, height if left as `span`, unless its `display:block`.

**Comment by ethrundr** [comment]
Pulling and testing~
Luckily I have one expedition returning.

**Comment by dragonjet** [comment]
my fleet 2 exped num 2 just returned

![ss 2015-09-11 at 01 10 21](https://cloud.githubusercontent.com/assets/557312/9807479/7c3c8ccc-5886-11e5-9af8-830fd1ae9e75.jpg)

**Comment by ethrundr** [comment]
LOL the same expedition I have here :laughing: 
![screen shot 2015-09-11 at 14 11 06](https://cloud.githubusercontent.com/assets/13522800/9807502/0b666fe6-588f-11e5-802e-458c11abcd74.png)

**Comment by dragonjet** [comment]
I guess we can close this issue now?

**Comment by nicky008** [comment]
Mine has no problem also :p
