### ISSUE TITLE
Bug with KC3Kai

### ISSUE THREAD

**Issue by hbhbenny647** [KC3Kai/KC3Kai#778]
Battle prediction is not working on map 3-5 even though the option is enabled?

![screenshot 24](https://cloud.githubusercontent.com/assets/13168067/9718330/c6401eac-55b5-11e5-9a1a-b8878abc3343.png)
![screenshot 25](https://cloud.githubusercontent.com/assets/13168067/9718331/c643f126-55b5-11e5-98fe-f1ae7fcf049d.png)

**Comment by javiergonz** [comment]
same problem here!

**Comment by McDohl** [comment]
https://github.com/KC3Kai/KC3Kai/issues/769
