### ISSUE TITLE
Plane Slots on Strategy Room shiplist

### ISSUE THREAD

**Issue by dragonjet** [KC3Kai/KC3Kai#779]
https://www.facebook.com/dragonjetmkii/posts/10153256696482730

**Comment by ReiFan49** [comment]
![image](https://cloud.githubusercontent.com/assets/9847780/9726635/f608711a-561f-11e5-859e-6fc0ed875148.png)

**Comment by dragonjet** [comment]
hm it kinda blocks out the plane color

**Comment by ReiFan49** [comment]
hmmm, should the empty one only like on legacy theme that shows the slot?

**Comment by dragonjet** [comment]
ah sure we can use that way

**Comment by ReiFan49** [comment]
![image](https://cloud.githubusercontent.com/assets/9847780/9726921/30982192-5623-11e5-8f9c-705fbf65b579.png)
keep the circle?

**Comment by dragonjet** [comment]
hm you may push it, and I'll try to play around with its UI some other time

**Comment by ethrundr** [comment]
my opinion, when the ships already had equipped items, how if we put the plane slot value (again) as tooltip?

**Comment by dragonjet** [comment]
oh and one more option is that, this may be a part of the shiplist enhancement crusade, remember the one where user can select which columns to show, since the data keeps growing, we still haven't added back heartlock

**Comment by ethrundr** [comment]
ah yes, I also noticed that the 5th slot is not yet included in the list...

by the way, finally I has decided to whom I'll give my expansions.
the first goes to my 1st wife Zuikaku and the second one goes to my 7th wife Taihou.
the rest is still unused~

**Comment by dragonjet** [comment]
quite a harem you got there

**Comment by McDohl** [comment]
wait is he echo's rival? xD

**Comment by LostLogia4** [comment]
Speaking of waifu, I'll be marrying Murasame on 23th September 1600 GMT+9
![250835](https://cloud.githubusercontent.com/assets/12930396/9734259/1b0492d4-5664-11e5-89ae-7e329f1546ad.png)

**Comment by bamboo3250** [comment]
@LostLogia4 Oh my guess is wrong haha xD 
anyway, noted. I'll be there. :smirk:

**Comment by LostLogia4** [comment]
@bamboo3250 What, you're guessing she's Shigure-chan?

**Comment by dragonjet** [comment]
my bet was akashi though, guess i lost

**Comment by bamboo3250** [comment]
@LostLogia4 That's right. It was really unexpected xD May I know the reason you chose Murasame-chan? I'm so curious :open_mouth:

**Comment by ethrundr** [comment]
10 wives so far, and about triple the amount XD @dragonjet 
all the ring has been bought already~

**Comment by ReiFan49** [comment]
another waifu thread lol

**Comment by nicky008** [comment]
This E8 farming for the Summer event made my Abukuma reach to lv.99 so easily.

Abukuma is really deserved for my new 210฿ (700￥) ring... (a bit hurt with stronger Yen in the Q3 though :sweat_smile:)

**Comment by ethrundr** [comment]
While me still being entranced by Teruzuki's line.....

**Comment by McDohl** [comment]
@ReiFan49 mind if I change text color to black, it kinda hurts my eyes xD

**Comment by ReiFan49** [comment]
@McDohl since it gives a dark color, brighter color might good to counter it's dark background,
on that case, is white fine for you? :3

**Comment by McDohl** [comment]
@ReiFan49 yes

**Comment by nicky008** [comment]
@McDohl it's interesting that I remembered you have the same issue about color brightness when the early version of Natsuiro theme is implemented here too. :3

**Comment by McDohl** [comment]
@nicky008 :open_mouth: you remembered it, I'm actually moved utaha-senpai :sweat_smile:

**Comment by LostLogia4** [comment]
@bamboo3250 She's been with me from the start (part of the 1st-gen destroyer team when I was a newbie), plus her overall enthralling combination of personality, voice and style makes her the ideal Kanmusu as my waifu.

**Comment by bamboo3250** [comment]
@LostLogia4 That's so nice. I wish I had someone that I can devote all of my heart to like that. Murasame, indeed, has a lot of charm points. Having her as your secretary must be great. Anyway, I'm looking forward to your wedding day :laughing:

**Comment by LostLogia4** [comment]
On second thought, the college timetable is out and... it looks like I'll have to delay my marriage for two days on 25th September.

**Comment by ethrundr** [comment]
For me, my first waifu, as well as the one obtaining my quest ring is no less than Zuikaku.

Despite her lines, for me, she looks worrying about the Admiral as much as she worry about her sister Shoukaku. Not less, she has very huge contribution, if not the greatest, among all my ships in service now. Almost all map that permit the usage of CV will have her joining in the fleet, and most of the time, she is the key for me to reaching victory. I marry her right after she reached level 99, in May 11th last year.
