### ISSUE TITLE
Quest Translations without WebStore release

### ISSUE THREAD

**Issue by dragonjet** [KC3Kai/KC3Kai#780]
The idea is that, when there is an untranslated quest, it will ajax-load the quest json from github master branch, and save data about the missing quests on localStorage. So the flow is, if quest missing, check localStorage, if none, get master quest json, if exists save localStorage, if not default nonexistent text

This is similar to how `popup.js` loads the `update` json to get the timer for next WebStore release

**Comment by ethrundr** [comment]
If it's possible, then why not.
This way we can decreasing the usual question after new quest update:
"What is this quest? There is no translation"
