### ISSUE TITLE
Sortie History is blank

### ISSUE THREAD

**Issue by dragonjet** [KC3Kai/KC3Kai#781]
* no console errors
* IndexedDB still contains the event sorties

![ss 2015-09-08 at 11 24 34](https://cloud.githubusercontent.com/assets/557312/9725798/34708b44-561c-11e5-8f21-4922e308ec8f.png)

**Comment by ReiFan49** [comment]
inverse with this?
![image](https://cloud.githubusercontent.com/assets/9847780/9725866/a83c6a64-5614-11e5-8111-f7ec4c4de927.png)

(also, if i remember, single paged or blank, based to invisible error that is not catched..)

**Comment by ethrundr** [comment]
wasn't it better to keep the mapped version one, rather than grouped into one tab like what we have now?

the purpose of Sortie History is to track each map sortie and results, not to track the event sortie as a whole, in my opinion

**Comment by dragonjet** [comment]
oh so it's because the maps are now not in `map_info` thus it doesn't show up on the list

**Comment by ethrundr** [comment]
is it possible to make a manual div for each past event?

**Comment by dragonjet** [comment]
yep, I'll do this one too. I haven't done much coding during the event, got rusty and I'd like to get familiar with the app again :laughing:

**Comment by nicky008** [comment]
A nice rework. :+1:

**Comment by ReiFan49** [comment]
i'm afraid i know why...
`sortie.diff = sortie.diff || maps["m"+sortie.world+sortie.mapnum].difficulty || 0;`

pointing to undefined variable... and...
`sortie.diff = sortie.diff || (maps["m"+sortie.world+sortie.mapnum] || {difficulty:0}).difficulty || 0;`

**Comment by dragonjet** [comment]
oh it's because of difficulty variable? or is that a different bug from the list not showing up? as I can see there are two bugs, one that doesn't show the map list, and one that doesnt show the sortie list XD

I was planning on using data from IndexedDB to show the list, meaning if a user did only up to E-4 only those maps will show.

**Comment by ethrundr** [comment]
well at least for now, the sortie can be categorized per map.

my suggestion for next event, each map's difficulty and last status are also logged internally, not fully dependent with the `api_data`. that way, when we switch to manual styling after the event ends, we still able to get the difficulties the player was chosen before, as well as their last status of the map: cleared, last kill or on progress~
