### ISSUE TITLE
No more one minute advanced in Docking and Expedition completion after the update

### ISSUE THREAD

**Issue by bamboo3250** [KC3Kai/KC3Kai#783]
I just noticed it recently. Could someone check it again?

**Comment by Crazyteitoku** [comment]
On git commit: a6c5fd69b4a6e2ea85739ae2875b3f571844ca1f docking completion still has one minute advancement. I just checked on both accounts (one of the actually isn't mine) and I can't replicate the issue.

**Comment by bamboo3250** [comment]
This is not issue of KC3Kai but KanColle game. Before when it only had 1 minute left, it considered as completed but now it doesn't seem so. It could be my laptop clock is not synchronous with the server clock so I need other to double check it.

**Comment by dragonjet** [comment]
hm this is actially prevalent across the playerbase, not sure if its their system clock or what, but you might wanna check what is the exact second advance on your side, some get it ~45 sec

**Comment by bamboo3250** [comment]
I checked with in-game clock. When it only had 30 seconds left, I tried accessing the main screen and the expedition fleet didn't return

**Comment by dragonjet** [comment]
or probably not on our side? there are these server shens happening even now about account transferring and server strengthening

**Comment by ethrundr** [comment]
@bamboo3250 imo, there are two possible answers for this:
*The gap is getting smaller, which means Devs already tried to solve this issue, but not able to completely do so.
*Your computer clock is not synchronized well enough with the server clock.

Also, on my side it used to be around 48-53 seconds, forgot the exact value. Going to check it later.

**Comment by McDohl** [comment]
@bamboo3250 I still get the 1 minute advanced for expedition

**Comment by bamboo3250** [comment]
I see, thank everyone. So that's my tablet's problem. When I tried switching back to my laptop, it still had 1 minute advanced. Closing this issue now.
