### ISSUE TITLE
Translation Repository

### ISSUE THREAD

**Issue by dragonjet** [KC3Kai/KC3Kai#784]
To move the whole translation directory onto a separate repository.
* Translation team will get write access to the new repo
* Translation team will lose write access from main repo

https://github.com/KC3Kai/kc3-translations

* Add new repository as **git submodule** to the main repo
* Retain JSON validation for travis-kun

I will be in charge of syncing the submodule to its recent commit for the main repo
`git submodule foreach git pull origin master`
[from this](http://stackoverflow.com/a/1032653/483704)

----

About translation issues, do you guys think it should be posted on the new repo's tracker or keep it here to be centralized?

----

Right now it is still advised to continue pushing to the main repo, until further greenlight

**Comment by nicky008** [comment]
Good step, for more nice and tidy repos.

I think when there are more translators work here (and more complex work, hard to do double checking but you still need the urgently work - this is the most critical point), this policy should be enhanced.

PS. Travis-kun's fanart needed...

**Comment by Crazyteitoku** [comment]
Unless there was a way to split the tracker on the main repo to deal with translation as well as KC3 Kai issues with itself I can imagine things will get messy in the long run. Right now however the issues with translations aren't a real issue otherwise personally as most of them are coming from external sources and therefore have their own ways of tracking. :laughing: 

I am all in for the changing read/write access for translators as they generally don't need write access to the main repo unless they happen to be a developer.

**Comment by dragonjet** [comment]
lol travis-kun's fanart.

for now I'm still figuring out how to add it as a submodule since, the translation repo, had to have the files on another subdirectory `/data` for travis-kun's json verification. Where in adding it as submodule to main repo will make it `/data/translations/data/en..` which is not what we want

**Comment by NicolaosGreene** [comment]
Who/what exactly is travis-kun? I have seen him referenced several times.

**Comment by ReiFan49** [comment]
this guy
![http://github.com/travis-ci/travis.rb](https://camo.githubusercontent.com/ea6828045b2dcd9770732d272586c5567bedfef3/687474703a2f2f61626f75742e7472617669732d63692e6f72672f696d616765732f7472617669732d6d6173636f742d32303070782e706e67)

**Comment by nicky008** [comment]
That's why we need new Travis-kun fanart ASAP... :kissing_smiling_eyes:

**Comment by Crazyteitoku** [comment]
Travis-kun, ahh yes the front runner for being the test dummy on various projects. He is the (beta) tester that combines a portion of what (beta) testers and what debuggers usually do. Without Travis-kun, most of the (beta) testers would be facing even more troubling issues for this project such as (but are not restricted to):
* Unable load the extension due to some extra/straying characters.
* Be faced with broken functionalit{y,ies} simply because of again extra/straying characters that should not be there.

When I started off contributing to this project I was mainly a beta tester and after having nuked my profile data, etc a few times I waited for @dragonjet to hop onto kc chat and to ask him if the developer version of KC3 Kai ok to be pulled again. You can imagine how I was somewhat a little fearful. :laughing: just kidding. That isn't to say Travis-kun could cover all bases but it is definitely a decent "stop gap" for some testing purposes. Ever since @dragonjet introduced me to Travis I can be somewhat relieved. :stuck_out_tongue_closed_eyes: 

Anyway, we have Travis-ci that is accessible from the project front page and appears as part of readme.md from memory: https://travis-ci.org/KC3Kai/KC3Kai . Travis-ci also appears in at push requests to ensure that the newly contributed codes are somewhat bug free as well.

**Comment by dragonjet** [comment]
gonna add this on readme files from now on

![travis2](https://cloud.githubusercontent.com/assets/557312/9787493/d922f80e-57f5-11e5-9eae-29e013e5c2b9.png)

I now implemented permission on the repositories and teams, related to #714

Right now I don't know how this actually works since it's my first time managing a GitHub organization, but I added write access to teams and their supposed projects, and removed those not directly related to it.

Theoretically the permissions I put in are the correct ones but [I got confused at how GitHub implemented it](https://help.github.com/articles/permission-levels-for-an-organization-repository/). Please let me know if anything is wrong, like you didn't get access to what you're supposed to, or got access to things you usually couldn't.

**Comment by RanFoxRun** [comment]
I just worked on https://github.com/KC3Kai/kc3-translations without problems... I just selected the file, edited or added what I had translated and go.

**Comment by dragonjet** [comment]
:open_mouth: if those are updated translations, you might wanna push it here as well XD I haven't added that repo as a submodule so it might get overwritten later on

**Comment by dragonjet** [comment]
### News

@KC3Kai/translators you may start pushing to the new repo
https://github.com/KC3Kai/kc3-translations

All of you have write access to that, so no more pull requests, commit then push to a centralized workflow.

Just remember travis-kun is watching. He's the one that validates JSON files. If anything is wrong he will say build error. during these times the app may get JS errors or empty texts)

![travis](https://cloud.githubusercontent.com/assets/557312/9811460/01e19066-58aa-11e5-9aa2-1fbe913d44ee.png)

**Comment by RanFoxRun** [comment]
Oh, it may be OT but the thing that gave problems in the items file I think it was a ":" that, I don't know why, was red instead of the color of the rest of the code.... what did I do wrong to get that error on a simple ":"?



p.s. I went back and looked at the code with more attention: I canceled, without realizing it, a "," on the line before, I'm sorry, I'll be more careful next time :/

**Comment by dragonjet** [comment]
:+1: will close this, but translators can still comment if there's any question

**Comment by hufuhufu** [comment]
I'm still confused here
Should i clone the kc3-translation repo or use `git submodule`

**Comment by nicky008** [comment]
@hufuhufu As usual, just clone the repo like our everyday translating work. Don't need to use the submodule.

**Comment by hufuhufu** [comment]
Oh ok
Kinda confused there xD
Will try it tomorrow

**Comment by dragonjet** [comment]
just wanna know are you guys using git in command line or somethign like tortoisegit?

**Comment by nicky008** [comment]
Used console mode Git sometimes, but today I use web and desktop Github.

**Comment by ethrundr** [comment]
I use GitHub Desktop to pull the new updates, the use git command line to sync my fork.

**Comment by dragonjet** [comment]
hm I've seen GitHub desktop, but I prefer tortoisegit.
I can manually work on windows explorer
![ss 2015-09-11 at 09 49 01](https://cloud.githubusercontent.com/assets/557312/9816329/f49b15a6-58ce-11e5-934c-d5c73e5eaa4f.png)

while having this right click menu
![ss 2015-09-11 at 09 50 31](https://cloud.githubusercontent.com/assets/557312/9816376/296a5f44-58cf-11e5-8c3e-0b3181c80921.png)

you can easily do the things needed like the mentioned `submodule update`

you can also enter the windows folder `\src\data\lang\...` and the right click menu there will be for the sub-repo, you can pull-commit-push on the sub-repo directly without re-cloning the TL repo

**Comment by FluffyPanzer** [comment]
I will change to Tortoisegit as Git Desktop keeps breaking my stuff, it did it again!

**Comment by dragonjet** [comment]
### Quick Guide

1) Pull the latest commit from the main repo `github.com/KC3Kai/KC3Kai/`
2) Execute `git submodule update --init -- "src/data/lang"`
3) You should now see a `lang` folder inside `data`, no more `translations`
4) Enter `lang` folder, and you should see something like another repo (coz it is, it's a submodule, meaning our main repo points to another)
5) Make your changes, and pull-commit-push as usual, but make sure you are running the git commands inside the `lang` directory.

This is easier with tools such as `tortoisegit` where you just right-click the explorer (screenshot on an earlier comment)

**Comment by nicky008** [comment]
tortoisegit is better in my idea, but somehow the earlier works was not so complex to use it.

And... @dragonjet, is so kindly to bring the guide here also. haha

**Comment by ReiFan49** [comment]
developers... wait..

![image](https://cloud.githubusercontent.com/assets/9847780/9817537/c69606c6-58cd-11e5-962a-2d16e52435db.png)
:sob:

**Comment by Agc0de6** [comment]
cryin'

**Comment by ReiFan49** [comment]
oh man... sorry for deleting (my previous comment) that,
i guess my university blocks port 22 :sob:

![image](https://cloud.githubusercontent.com/assets/9847780/9817563/f887e38e-58cd-11e5-950c-962cdfb0e2e1.png)

**Comment by FluffyPanzer** [comment]
Welp, when I try to commit using TortoiseGit it looks okay but it says (No Branch) and so when I commit and ignore the error my stuff is just lost in the Github limbo I guess because I can't find it anywhere.

![ss 2015-09-11 at 12 46 56](https://cloud.githubusercontent.com/assets/10162193/9819263/58769f42-5883-11e5-9699-c839d04a6cb6.png)

**Comment by dragonjet** [comment]
@ReiFan49 sure both works fine

@FluffyPanzer you'll first need to pull, probably using the "git fetch" from the tortoise right click menu.

when commiting, make sure it says " commit -> master". If not, and you have already fetched, on the expanded right-click menu, switch-checkout branch, and select `master`, not `remote/master`

**Comment by FluffyPanzer** [comment]
Uh I think it worked now? I did Pull-Commit-Push and the file is now updated on the ES folder. This is scary, might mess something up that I shouldn't lol

**Comment by hufuhufu** [comment]
@dragonjet Thanks for the guide :satisfied:
I just tried pushing a commit and it works :+1:

**Comment by ReiFan49** [comment]
well, @dragonjet with this system, for every developer that wanting to register new terms (usually me xD) must request/pull normally right 'w') ?

**Comment by kololz** [comment]
well dayum I didn't used git before
got this error
any help?

git.exe submodule update --init -- "src/data/lang"

error: pathspec 'src/data/lang' did not match any file(s) known to git.
Did you forget to 'git add'?


git did not exit cleanly (exit code 1) (578 ms @ 2015/9/12 上午 09:05:41)

**Comment by hufuhufu** [comment]
@kololz have you pull the latest build?

**Comment by kololz** [comment]
I installed the latest build on github
I've tried to use pull function before but I got the error code 128

**Comment by dragonjet** [comment]
@ReiFan49 hm that's a point, not all developers have write access to the translation repo, maybe I should add the team to it

@kololz it needs a pull first, what was the error message when you git pull?

**Comment by kololz** [comment]
Cant do that right now. Been outside for 5 hours, and need 40 mins to get home from where I am.

**Comment by kololz** [comment]
git.exe pull -v --progress "https://github.com/KC3Kai/KC3Kai" master

From https://github.com/KC3Kai/KC3Kai
* branch            master     -> FETCH_HEAD
error: Entry '.travis.yml' would be overwritten by merge. Cannot merge.


git did not exit cleanly (exit code 128) (2766 ms @ 2015/9/12 下午 06:34:37)

**Comment by Crazyteitoku** [comment]
@kololz I think if you have made any changes to that file you might want to either push it or stash it elsewhere.

I have seen similar sort of error message but on a different platform:
````
$ git pull
remote: Counting objects: 434, done.
remote: Compressing objects: 100% (76/76), done.
remote: Total 434 (delta 243), reused 208 (delta 208), pack-reused 150
Receiving objects: 100% (434/434), 240.08 KiB | 194.00 KiB/s, done.
Resolving deltas: 100% (304/304), completed with 69 local objects.
From https://github.com/dragonjet/KC3Kai
   3117238..093aa22  master     -> upstream/master
 * [new branch]      Vietnamese_Translation_7 -> upstream/Vietnamese_Translation_7
 * [new branch]      dev-DeckBuilderExport -> upstream/dev-DeckBuilderExport
 * [new branch]      dev-subtitles -> upstream/dev-subtitles
 * [new branch]      dev-translation -> upstream/dev-translation
 * [new branch]      i18n-gameweb -> upstream/i18n-gameweb
   d940654..4fc53cd  webstore   -> upstream/webstore
 * [new tag]         19.2       -> 19.2
Updating 3117238..093aa22
error: Your local changes to the following files would be overwritten by merge:
        src/assets/js/global.js
Please, commit your changes or stash them before you can merge.
Aborting
````

**Comment by kololz** [comment]
well, I just found that I should use a empty folder to pull,
but now I encountered this
git.exe submodule update --init -- "src/data/lang"

Cloning into 'src/data/lang'...
error: cannot spawn C:\Program Files (x86)\Git\bin\ssh.exe: No such file or directory
fatal: unable to fork
Clone of 'git@github.com:KC3Kai/kc3-translations.git' into submodule path 'src/data/lang' failed


git did not exit cleanly (exit code 1) (1079 ms @ 2015/9/12 下午 08:17:42)

**Comment by Crazyteitoku** [comment]
Make sure that your ssh.exe is within Program Files (x86)\Git\bin?

Alternatively you can probably just set it as a %PATH% variable or really just double check your %PATH% and edit as necessary.

**Comment by kololz** [comment]
git.exe submodule update --init -- "src/data/lang"

Cloning into 'src/data/lang'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:KC3Kai/kc3-translations.git' into submodule path 'src/data/lang' failed


git did not exit cleanly (exit code 1) (3203 ms @ 2015/9/12 下午 08:22:40)

**Comment by Crazyteitoku** [comment]
You'll probably need to add the host as needed. Here was what I saw on my end:

````
$ git submodule update --init -- "src/data/lang"
Submodule 'src/data/lang' (git@github.com:KC3Kai/kc3-translations.git) registered for path 'src/data/lang'
Cloning into 'src/data/lang'...
Warning: Permanently added the RSA host key for IP address '192.30.252.129' to the list of known hosts.
Enter passphrase for key '/home/foo/.ssh/id_rsa':
remote: Counting objects: 179, done.
remote: Compressing objects: 100% (124/124), done.
remote: Total 179 (delta 64), reused 166 (delta 51), pack-reused 0
Receiving objects: 100% (179/179), 200.98 KiB | 173.00 KiB/s, done.
Resolving deltas: 100% (64/64), done.
Checking connectivity... done.
Submodule path 'src/data/lang': checked out '5de5c7e57a47418e8ca25b82b4e6c97ae7d69597'
$
````

**Comment by kololz** [comment]
I wonder how? Don't know how to add host

**Comment by kololz** [comment]
well anyway, I can finally start the KC3Kai, but somehow there is still question I want to ask.
So I do submodule update to the lang folder, but I found that the translations are not the newest right now.
Is it working as intended?

**Comment by dragonjet** [comment]
when you go into the lang folder, you can git pull from there, it will pull the translation repo instead of the main files. As long as you're inside the lang folder, may it be command line or tortoisegit.

**Comment by kololz** [comment]
I see. It worked right now.

**Comment by Crazyteitoku** [comment]
Just leaving this here as I am only commenting on the convenience of git CLI that it is also fairly intuitive and it is also somewhat OT. :sweat_smile: 

````
$ git pull
remote: Counting objects: 614, done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 614 (delta 340), reused 337 (delta 337), pack-reused 261
Receiving objects: 100% (614/614), 98.79 KiB | 0 bytes/s, done.
Resolving deltas: 100% (448/448), completed with 82 local objects.
From https://github.com/dragonjet/KC3Kai
   093aa22..cd9cc32  master     -> upstream/master
 * [new branch]      dev-KancolleDBSubmission -> upstream/dev-KancolleDBSubmission
   57c1aa7..c74a140  dev-subtitles -> upstream/dev-subtitles
   9223493..2c1b78a  i18n-gameweb -> upstream/i18n-gameweb
   4fc53cd..d6ba0ac  webstore   -> upstream/webstore
 * [new tag]         20.1       -> 20.1
 * [new tag]         20.0       -> 20.0
Fetching submodule src/data/lang
Enter passphrase for key '/home/foo/.ssh/id_rsa': 
remote: Counting objects: 362, done.
remote: Compressing objects: 100% (179/179), done.
remote: Total 362 (delta 248), reused 136 (delta 136), pack-reused 47
Receiving objects: 100% (362/362), 109.45 KiB | 0 bytes/s, done.
Resolving deltas: 100% (250/250), completed with 29 local objects.
From github.com:KC3Kai/kc3-translations
 * [new branch]      Agc0de6-patch-1 -> origin/Agc0de6-patch-1
   5de5c7e..a96478a  master     -> origin/master
Updating 093aa22..cd9cc32
Fast-forward
 README.md                                                  |   2 +-
 src/assets/img/client/morale/1.png                         | Bin 0 -> 968 bytes
 src/assets/img/client/morale/2.png                         | Bin 0 -> 1000 bytes
 src/assets/img/client/morale/3.png                         | Bin 0 -> 852 bytes
 src/assets/img/client/morale/4.png                         | Bin 0 -> 1034 bytes
 src/assets/img/social/ma.png                               | Bin 0 -> 766 bytes
 src/assets/img/social/sk.png                               | Bin 0 -> 1204 bytes
 src/assets/img/social/we.png                               | Bin 1310 -> 4050 bytes
 src/assets/img/ui/export.png                               | Bin 0 -> 971 bytes
 src/data/developers.json                                   |  49 ++++++++++++++++++++------
 src/data/lang                                              |   2 +-
 src/data/settings.json                                     |  35 ++++++++++++++-----
 src/library/managers/ConfigManager.js                      |   6 +++-
 src/library/managers/PlayerManager.js                      |  19 +++++++---
 src/library/managers/ShipManager.js                        |   3 +-
 src/library/managers/SortieManager.js                      |  24 +++++++++++++
 src/library/managers/TimerManager.js                       |   3 +-
 src/library/modules/Database.js                            |  16 +++++++--
 src/library/modules/Kcsapi.js                              |  30 ++++++++++++----
 src/library/modules/Meta.js                                |   2 ++
 src/library/modules/Network.js                             |  24 +++++++++++--
 src/library/objects/Fleet.js                               |  10 ++++++
 src/library/objects/Node.js                                |  26 ++++++++++++--
 src/library/objects/Quest.js                               |  15 ++++++++
 src/library/objects/Screenshot.js                          |   6 ++--
 src/library/objects/SettingsBox.js                         |   6 ++--
 src/library/objects/Timer.js                               |  18 +++++-----
 src/manifest.json                                          |   2 +-
 src/pages/devtools/themes/default/horizontal/horizontal.js |   6 ++--
 src/pages/devtools/themes/default/vertical/vertical.js     |   6 ++--
 src/pages/devtools/themes/natsuiro/img/exportdeck.png      | Bin 0 -> 2111 bytes
 src/pages/devtools/themes/natsuiro/js/Shipbox.js           |  13 +++++--
 src/pages/devtools/themes/natsuiro/natsuiro.css            |  38 ++++++++++++++++++--
 src/pages/devtools/themes/natsuiro/natsuiro.html           |   9 ++---
 src/pages/devtools/themes/natsuiro/natsuiro.js             | 234 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++----------------------------------------
 src/pages/game/api.html                                    |   6 ++--
 src/pages/game/api.js                                      |  11 +++++-
 src/pages/popup/popup.css                                  |  22 ++++++++----
 src/pages/popup/popup.html                                 |  20 +++++++++--
 src/pages/popup/popup.js                                   |  98 ++++++++++++++++++++++++++++++---------------------
 src/pages/strategy/sortielogs.js                           |  10 ++++--
 src/pages/strategy/tabs/aircraft/aircraft.js               |  38 ++++++++++++++++++++
 src/pages/strategy/tabs/profile/profile.js                 |   4 +--
 src/pages/strategy/tabs/screenshots/screenshots.css        |  44 ++++++++++++++++++++++-
 src/pages/strategy/tabs/screenshots/screenshots.html       |  20 +++++++++--
 src/pages/strategy/tabs/screenshots/screenshots.js         |  36 +++++++++++++++++--
 src/pages/strategy/tabs/wikia/wikia.js                     |  44 +++++++++++++++++++++++
 update                                                     |   6 ++--
 48 files changed, 750 insertions(+), 213 deletions(-)
 create mode 100644 src/assets/img/client/morale/1.png
 create mode 100644 src/assets/img/client/morale/2.png
 create mode 100644 src/assets/img/client/morale/3.png
 create mode 100644 src/assets/img/client/morale/4.png
 create mode 100644 src/assets/img/social/ma.png
 create mode 100644 src/assets/img/social/sk.png
 create mode 100644 src/assets/img/ui/export.png
 create mode 100644 src/pages/devtools/themes/natsuiro/img/exportdeck.png
$
````
