### ISSUE TITLE
what happened to this?

### ISSUE THREAD

**Issue by convoicon** [KC3Kai/KC3Kai#785]
![image](https://cloud.githubusercontent.com/assets/13990697/9733819/4e851fac-5669-11e5-9b6c-f20874fbdf50.png)
I think the word got overlap on each other

**Comment by bamboo3250** [comment]
Vietnamese translation for those words is not available yet. I'll spend some time to work on them soon.

**Comment by dragonjet** [comment]
the UI is also under works and will change where the words are

**Comment by convoicon** [comment]
Don't worry about the translation. But good work with the UI :+1:

**Comment by dragonjet** [comment]
19.2 has updated UI
