### ISSUE TITLE
Adding improvement levels on equips

### ISSUE THREAD

**Issue by LostLogia4** [KC3Kai/KC3Kai#786]
Now that we already have plane rank numbers already, how about the equipments? Is it possible to retrieve and display the improvement levels as well?

**Comment by nicky008** [comment]
:+1: I agree too.

**Comment by dragonjet** [comment]
hm on the panel? like, the same tiny box as the plane level?

**Comment by nicky008** [comment]
I guess @LostLogia4 might think as you, @dragonjet thought?

**Comment by dragonjet** [comment]
I'm not sure I can follow wat u said :V

**Comment by nicky008** [comment]
A..Alright :relaxed:

**Comment by LostLogia4** [comment]
Same spot as plane levels. It's not like we need to know the plane slots when it was already been occupied with an equipment right?

**Comment by dragonjet** [comment]
looks like

![ss 2015-09-14 at 10 30 41](https://cloud.githubusercontent.com/assets/557312/9852313/42a36f2e-5b30-11e5-9c23-76273c434d84.jpg)
