### ISSUE TITLE
Suggestions for expedition scorer

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#792]
Related #722, few suggestions about the scorer.
## Select by expedition time

Like what we have in the ship list:

![2015-09-08_205616_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/9750907/31895e56-566c-11e5-9987-7c61ac3b91c2.png)

We can make a similar selector for selecting expeditions that takes less than `x` hours (`x` could be 7 / 12 / 24)

A more flexible way would be to have a text box for user to input x.
## Great success

Run expeditions with all-sparkling fleet will have an almost guaranteed great success,
which could have an impact on the result table. I'm thinking about having another checkbox for each expedition, if user can form a sparkling fleet for that expedition, he can check it and the gross income will be multiplied by `1.5` when doing calculation.

For now I haven't implemented this, but this will be the very next feature in my lib.
## User experience
- Remember expedition selections, AFK time, etc.
- Like ship list, highlight current item as mouse moves over
- For expedition list, it is possible to click on the text to toggle checkbox?

**Comment by nicky008** [comment]
One question; Is textclick and checkbox toggle combi method better than leaving only the checkbox be clickable as the current?

**Comment by Javran** [comment]
@nicky008 maybe having a clickable text would be better, as there are more spaces for user to click. I can imagine user clicks on a text and it turns into a different color as an indication.

**Comment by nicky008** [comment]
Whoa, the latter is also far good too.

**Comment by dragonjet** [comment]
hm aren't all expeditions gs-able? coz if they are, it's just like multiplying everything by 1.5 and would be same result?

aye I also forgot to add the text as a label for the checkbox

**Comment by Javran** [comment]
I guess all expeditions are GS-able, but you'll(at least for me) only GS few of them, as sparkling takes time and is boring XD. (e.g. what I usually do is to only sparkle several 1CL5DD fleets, as this works for 5/13/21/24/37/38, for rest of the expeditions, I just use the normal setup)

**Comment by JD-Kurotoshigami** [comment]
suggestion :
add buckets/devmats/coinboxes in the priorities :)

**Comment by NicolaosGreene** [comment]
Speaking of great success, does the expedition scorer factor in the chance of great success from drum expeditions?

**Comment by Javran** [comment]
@JD-Kurotoshigami some related discussions are in #740 

@NicolaosGreene GS is not yet taken into account. Dealing with landing craft could be complicated, I'm not sure how to do it for now.

**Comment by LostLogia4** [comment]
@Javran Pretty much every expeditions can bring 4 landing crafts now, only exception is 37 because of its composition.

**Comment by Javran** [comment]
@LostLogia4 you meant Abukuma kai2 can only carry 3 of them? I can leave an option in my lib to allow passing number of available landing crafts to it, wondering how the UI will become though.
