### ISSUE TITLE
Wrong resource position in expedition result

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#803]
Using commit c8fcca7b2e

![2015-09-09_124417_3360x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/9768314/c6aecc12-56f0-11e5-8fb8-720efe9aa39c.png)

Ammo and steel positions are wrong.

**Comment by McDohl** [comment]
same reports to https://github.com/KC3Kai/KC3Kai/issues/777
