### ISSUE TITLE
Battle Prediction on Night Battle PvP

### ISSUE THREAD

**Issue by giodss** [KC3Kai/KC3Kai#806]
It seems that the prediction is not working on PvP night battle on the latest build, I've already tried this one for several times. Anyone got this same issue?

**Comment by freezebear** [comment]
i'll test it.. might taking a while... 
low connection X_X

**Comment by freezebear** [comment]
works for me..
"Day Batle"
![image](https://cloud.githubusercontent.com/assets/12047229/9778294/07c2f236-57a1-11e5-9d8e-5cebabac7ac5.png)

"Night Batle"
![image](https://cloud.githubusercontent.com/assets/12047229/9778269/b8904ab0-57a0-11e5-9fba-b12fd1e954bb.png)

i think it just matter of connection or something ?

**Comment by giodss** [comment]
hmm, I will test again for the next PvP period, maybe yes, it was just my poor connection

**Comment by giodss** [comment]
it seems that it was my internet which is bad last time, it is all good now
