### ISSUE TITLE
Cannot use quest tracking when quest translation is turned off.

### ISSUE THREAD

**Issue by nekoworkshop** [KC3Kai/KC3Kai#807]
The font used in quest translation looks quite awkward in Japanese so I decided to turn it off while keeping the quest tracking. 

![with translation](https://cloud.githubusercontent.com/assets/1346257/9777999/b0b723b2-5738-11e5-9bbb-4e0beeeebf07.PNG)

However after I disabled quest translation quest tracking stopped working completely as well. According to api.js if quest translation is disabled the questOverlay function will return immediately, no matter ConfigManager.api_tracking is true or not.

I'm not sure whether this behavior is intended. If it's not I may fix it so that both feature can be turned on or off independently. Here is a screenshot from my patched version.
![fixed](https://cloud.githubusercontent.com/assets/1346257/9778090/d8734fec-5739-11e5-97df-d93c19052fde.PNG)

**Comment by dragonjet** [comment]
ah if you already have this patch, you may create a pull-request for this, this is a welcomed enhancement

**Comment by nekoworkshop** [comment]
Thank you dj. I have submitted the patch.
