### ISSUE TITLE
[Suggestion] Daily Naval Resource Ledger

### ISSUE THREAD

**Issue by LostLogia4** [KC3Kai/KC3Kai#809]
We already have resource & consumable graphs, but it didn't tell a thing about where did those resources come from and where they're spent on. I think it'll help tremendously if we could add a trial balance or something to compare the resource income and outflow.

Income Category:
- Daily Regeneration
- Expedition
- Quests
- In-map resource nodes (such as 1-6 and 2-3)
- Salvaging (from scrapped kanmusus and equips)

Outflow Category:
- Sorties (divided into maps) : considered as liability
- Resupply : considered as liability servicing
- Construction & Development
- Remodels

**Comment by ReiFan49** [comment]
i guess mixing it with #878 makes the database smaller and simpler?

~~ps: let's propose the database structure before moving on to adding it~~
what i'm thinking about this one...
```
Data Lodger
ID       integer     PRIMARY
HQ       char[8]
Time     long        represents date/time in UnixStamp
Type     char[1..10] represents the respective data
Changes  integer     represents expenses/income of the type
```

**Comment by LostLogia4** [comment]
I thought we already had a database for that since the resource graph was introduced?

**Comment by ReiFan49** [comment]
hmm from what i get, it does the similar thing like harvest moon,
every income and outcome is counted, by looking out the delta/gain/loss per time unit (1 hour)

the database for resource/consumables itself, does not contain why it does increase/decrease, or by what it does change...

**Comment by LostLogia4** [comment]
@ReiFan49 So we have a separate database to record their triggers?

**Comment by ReiFan49** [comment]
yes, 
daily regen is the tricky one i guess, (i cannot and might attempt the regen one :sweat_smile: )
because sortie resource gain is suspended until normally retreat/end of sortie route right?

**Comment by LostLogia4** [comment]
For the daily regen, compare the resource when the api_port with call that come immediately before it.
Then compare the time between the call and you get the regenerated resource value.

**Comment by ethrundr** [comment]
Even if this got implemented, my `Daily Regeneration` part will stay 0 until the next event :laughing: 
All of my resource already far exceed the regen limit XD

**Comment by ReiFan49** [comment]
for every hour, there'll be a list that consists the change of this one,
it's like
```Javascript
{
  "h20102010":[
    {type:"regen",materials:[0,0,0,3,0,0,0,0]},
    {type:"cons-ship",materials:[-4000,-6000,-6000,-2000,0,-10,-20,0]},
    {type:"dest-slot",materials:[1,2,0,0,0,0,0,0]},
    {type:"dest-ship",materials:[2,4,11,0,0,0,0,0]},
  ],
  "h20102011":[
    {type:"regen",materials:[60,60,60,20,0,0,0,0]},
    {type:"cons-ship",materials:[-4000,-6000,-6000,-2000,0,-10,-20,0]},
    {type:"cons-ship",materials:[-4000,-6000,-6000,-2000,0,-10,-20,0]},
    {type:"cons-ship",materials:[-4000,-6000,-6000,-2000,0,-10,-20,0]},
    {type:"cons-ship",materials:[-4000,-6000,-6000,-2000,0,-10,-20,0]},
  ],
}
```

**Comment by LostLogia4** [comment]
@ReiFan49 Works okay for data representation, but that leaves the question on how to track the different resource income/expense that spans several hours.

**Comment by ReiFan49** [comment]
spans for N hours i guess concat the list...

**Comment by ReiFan49** [comment]
[v] remodelling consumption
[ ] quest clear reward
[ ] expedition reward
[ ] expedition consumption
[ ] sortie resource node bonus
[ ] sortie consumption
[ ] practice consumption
[ ] akashi remodelling consumption
[ ] construction/development consumption

**Comment by LostLogia4** [comment]
Seems like we got a long way to go...

**Comment by ReiFan49** [comment]
oh no.... i almost push the current lodger system lol,
which shows only net income for every action.... (ship consumption mixed with sortie/exped gain)

**Comment by dragonjet** [comment]
ping~ can we close this or there are remaining bits and pieces apart from the separate entries such as https://github.com/KC3Kai/KC3Kai/issues/1148

**Comment by LostLogia4** [comment]
close it after this [pull request](https://github.com/KC3Kai/KC3Kai/pull/1104) is resolved

**Comment by LostLogia4** [comment]
Already released, closing.
