### ISSUE TITLE
[Translation] Preview ES translation

### ISSUE THREAD

**Issue by FluffyPanzer** [KC3Kai/KC3Kai#814]
Hi, I am the one translating KC3Kai to Spanish and I would like to know if there's a way to preview in-game the translation as the Español/Spanish option is still not implemented on the Settings menu.

Thanks.

**Comment by dragonjet** [comment]
oh sorry will add this today as an option, forgot to include on settings xD

**Comment by FluffyPanzer** [comment]
Thanks!

**Comment by dragonjet** [comment]
aye, will close this issue when I push the new settings with the commit xD

**Comment by FluffyPanzer** [comment]
Sorry I dont know how this stuff works lol

**Comment by dragonjet** [comment]
Added on 99b4a64f12b3aa8fd7312e6037111e8e7183ce1e
