### ISSUE TITLE
[Feature Request] Integration with myfleet.moe

### ISSUE THREAD

**Issue by nekoworkshop** [KC3Kai/KC3Kai#815]
Here are two of those sites I have used.

### http://kancolle-db.net/ 艦これ統計データベース(仮)
This site gathers information regarding drops, construction, crafting and such. For example :

Got some resources to spend on LSC but don't know which recipie you should try to get Yamato ?
![image](https://cloud.githubusercontent.com/assets/1346257/9800970/2e5ca882-57de-11e5-9f84-37b36e9b1a59.png)

Wanted to get your hand on Umikaze but heard some rumor about other drop site besides E-4 boss node?
![image](https://cloud.githubusercontent.com/assets/1346257/9801141/4cf708cc-57df-11e5-91ef-ac78b5a4e8b5.png)

Those data offers valuable insight of the loot system (Though I wish they could also collect and share data regarding combat resolution since there is still debates/myths about damage calculation and other mechanices ) or can become a mythbuster ( "Does this node really drop X ship?" ) if needed.

### https://myfleet.moe/ MyFleetGirls
Basically an online Strategy Room. The concept behind this site is the same as our Strategy Room ( tracking and analysing). 

Currently some area of our strategy room is still under construction and there are plans to reform existing rooms. Although we might not have resources to spend here I believe those sites can offer some inspriation about our strategy room.

*Technical info regarding this feature:
kancolle-db.net have forked some most used Kancolle tools by Japanese players. I had a quick look on their standalone telemetry tool and it turned out they only take raw API response (with the API token removed, of course.).*

**Comment by nekoworkshop** [comment]
Shame on me... It's already mentioned here #690

**Comment by c933103** [comment]
Myfleetmoe do not want to receive data from third party client software.

**Comment by nekoworkshop** [comment]
Thanks for the heads up. I had to dig the issue list to find out the authors's opinion about this since he didn't say anything in the frontpage. https://github.com/ponkotuy/MyFleetGirls/issues/226

**Comment by ethrundr** [comment]
@nekoworkshop well at least, we know that more people are in for syncing our data with the kancolle-db

**Comment by nekoworkshop** [comment]
@ethrundr To me I would use the word "contribute" rather than "sync" since we are all making efforts to make a better world. Sadly jerks do exist and the exact reason why the author of MyFleetGirls claims that he would not accept any data from third-party tools is the potential vulnerability on the server.

Anyway I've just dropped a message on twitter to the maintainer of kancolle-db since he didn't reply to dj's post in his repo. Hope I can hear from him soon.

**Comment by ethrundr** [comment]
@nekoworkshop thanks for the help. having someone communicate with the owner in his own language seems assuring.

**Comment by nicky008** [comment]
@ethrundr My voice in the last month for him is not enough yet, so this time I bring more people to beg the admin. :stuck_out_tongue_closed_eyes:

**Comment by nekoworkshop** [comment]
@nicky008 Just being curious, how did you contact him?

Also could you add a properiate label to this issue ? I can change the title but that's the highest permission I have at the moment. Don't want to mess up our issue section.

**Comment by ethrundr** [comment]
problem is, I don't know which label should I give for this XD
will append "other" label for now, maybe.

**Comment by dragonjet** [comment]
hm isn't `feature` the short for `feature-request`? xD

I think this one counts as a feature as well, but if we already have an existing issue for kancolle-db at #690, shall we make this dedicated to myfleet.moe?

**Comment by ethrundr** [comment]
@dragonjet myfleet.moe is worth to try, but from what the admin said, we have lesser chance to collaborate with it rather than kancolle-db, however, let's make this dedicated for myfleet.moe~

**Comment by nekoworkshop** [comment]
@dragonjet I've always treated `feature` as `feature-request`. Hope I didn't get it wrong :3

At the moment the maintainer of myfleet.moe doesn't allow submission from any third-party tools. We can make this dedicated for myfleet.moe. Hope one day we can come back to this issue when the author changes his mind.

I'll follow up in #690 if I got any response from the author of Kancolle-db.

**Comment by ethrundr** [comment]
OK. I'll change the title then~

**Comment by nicky008** [comment]
@nekoworkshop I had send my private tweet to him a month ago but he answered me back he was busying and would consider this somwhow.

**Comment by nekoworkshop** [comment]
@nicky008 I see... I bet he won't be too happy if we keep asking that every month. Just deleted my tweets and let's wait for a good time to resend the request.

**Comment by ethrundr** [comment]
Erm, why this is closed?
Let we just kept this opened until there are clear result to our request....

**Comment by nekoworkshop** [comment]
At the moment the author of MyFleetGirls has clearly stated that he would not accept any third-party tools submission.
As for Kancolle-DB, I have got the permission and agent key from the author https://github.com/KC3Kai/KC3Kai/issues/690#issuecomment-139502124
Sorry for the confusion. If you prefer we keep the issue open until the author of MyFleetGirls changes his mind then it's OK.

**Comment by ethrundr** [comment]
@nekoworkshop just to make clear: are we still going to wait for his response or we will drop the attempt to try to negotiate with him?

if we want to still waiting for it, then let's leave this opened until then.
if we are going to drop the idea, then let's we close this.

**Comment by nekoworkshop** [comment]
@ethrundr I didn't know his attitute towards third party tools before I created this issue. I was assumuing he is open to every one since even the source code of the server is on github.

Considering the fact no Kancolle tools have successfully aquired his permission ( heard about some developers talking about their offers being turned down) I would say chance is almost zero. I suggest we give up and close the issue.

**Comment by ethrundr** [comment]
Okay then. I'll re-close this issue.

**Comment by nekoworkshop** [comment]
Thank you ethrundr. Next time I'll let you know before I close a issue.
