### ISSUE TITLE
a bug in sortie history? or i did something worng

### ISSUE THREAD

**Issue by qqzzxx** [KC3Kai/KC3Kai#816]
![qq 20150910163734](https://cloud.githubusercontent.com/assets/14226337/9803720/629ffa4e-57da-11e5-8e44-8fcb8e7f55de.jpg)
 something like this,,no detail for the sortie history
i was doin 2-3 for daily

**Comment by ReiFan49** [comment]
i thought it was the same as #781 
there's no console error right?

**Comment by qqzzxx** [comment]
i dont know if this is a error
![qq 20150910171107](https://cloud.githubusercontent.com/assets/14226337/9804122/2c829a2a-57df-11e5-8412-1cf98cc6fe2e.jpg)

**Comment by ReiFan49** [comment]
not that one though..

**Comment by dragonjet** [comment]
yea, this is most likely webstore version (19.1) and does not include the latest patches to the sortie history, which makes it duplicate of #781

I did include it on the [v19 changelogs](https://github.com/KC3Kai/KC3Kai/wiki/Changelog%3A-Version-19#strategy-room) though

**Comment by ethrundr** [comment]
let me test this one on our build
luckily, I haven't pulled anything yet since last night XD

**Comment by dragonjet** [comment]
wait it is?

unfortunately I cannot test this anymore. I fked up my local copy, and so I recloned and reloaded the unpacked extension. bai bai history

**Comment by ethrundr** [comment]
on our dev copy, it's already working.
probably the 19.1 is the one that not working.

**Comment by qqzzxx** [comment]
ok, thx for the respond 
just saw next update coming in tomorrow

**Comment by ethrundr** [comment]
@qqzzxx the update it's tonight in JST, not tomorrow :laughing:

**Comment by dragonjet** [comment]
alright, gonna close this in favor of #781 

If there's still a bug after 19.2 webstore in a few minutes, then let's continue on #781 which will not be closed
