### ISSUE TITLE
[Feature Request] Fleet Marking on Ship List

### ISSUE THREAD

**Issue by ethrundr** [KC3Kai/KC3Kai#819]
One request comes to me and @ReiFan49 via our KC Local Group:

"On the strategy room, how about if there is a mark, indicating in which fleet the ship is included in, or at least to indicate that she is already included in the active fleet.

Having no marker on the Strategy Room's Ship List sometimes makes me quite difficult to know and decide which ship I should use."

Personally, I'm in favor for this, to make our shiplisting is closer to the actual listing the game has, especially when now we still not implementing the two-step sorting method (any and ID), like the actual game do for the listing.

**Comment by dragonjet** [comment]
o>--<

:+1: but we're not yet doing sub-sorting atm, but I like the idea of marking

**Comment by ReiFan49** [comment]
for now leaving the "include any ships on fleet, or exclude it"

**Comment by ethrundr** [comment]
for the first "trial", I suggest to tweak the ID number of the ship:
- If she is idle, set the default BG
- If she is on fleet, set with other color to indicate that she is already on fleet. Might also added with a tooltip, says in which fleet she is in, like "Fleet 1" or such.

**Comment by Javran** [comment]
should have been implemented - ships currently in fleet is highlighted by background color on their names in ship list tab.
