### ISSUE TITLE
Issue Index

### ISSUE THREAD

**Issue by dragonjet** [KC3Kai/KC3Kai#821]
#### Critical Bugs

These are the bugs that break user experience.

| Status | Location | Description | Version |
| --- | --- | --- | --- |
| :black_medium_square: #804 | Battle | Sinking prevents prediction on succeeding nodes |  |
| :black_medium_square: #49 | Screenshot | Screenshot captures wrong area on screen |  |
---
#### Expedition

Expedition-related features spearheaded by @Javran 

| Status | Location | Description | Version |
| --- | --- | --- | --- |
| :white_check_mark: #685 | Panel | Alternative view specialized for expeditions | v22 |
| :white_check_mark: #30 | Strategy | Expedition Shiplist for Planning | v22 |
| :white_check_mark: : #103 | Strategy | Expedition History |  |
| :black_medium_square: #774 | Strategy | Fleet compositions |  |
| :black_medium_square: #792 | Strategy | Expedition scorer enhancement |  |
---
#### Game Goals

The idea is that the users can set their in-game goals, like I aim to remodel this ship, or grind this ship to `Lv.XX` or I need to sparkle this set of ships. These goals will be tracked and updated each time he progresses, e.g. showing how many sorties left (exp calculator) even without re-inputting all values again. or show who else from the sparkling queue are not yet done, or how many sorties/levels before I can remodel her.

| Status | Location | Description | Version |
| --- | --- | --- | --- |
| :white_check_mark: #27 | Strategy | Experience Calculator | v24 |
| :black_medium_square: #61 | Strategy | Sparkling queue |  |
| :white_check_mark: | Strategy | Leveling Goals | v24 |
---
#### Database submissions

To let the players contribute their data to the greater community, we should have the app be able to submit data onto popular online databases.

| Status | Location | Description | Version |
| --- | --- | --- | --- |
| :white_check_mark: #690 | Network | kancolle-db.net | **19** |
| :black_medium_square: ~~#815~~ | ~~Network~~ | ~~myfleet.moe~~ |  |
| :white_check_mark: #952 | Network | poi-statistics | **22** |
---
#### Settings, About, Help/Wiki

Started as a Settings page interface overhaul, redesigning it on Adobe made it larger because of the ideas of incorporating Settings page, About page and Strategy Room into one page, now with collapsible categories to avoid very long menus. With the addition of new documentation translations, help will also now be moved in-app and included in the aforementioned redesign.

| Status | Location | Description | Version |
| --- | --- | --- | --- |
| :black_medium_square: #810 | Settings | Merge Settings, About, Strategy, Help pages |  |
| :black_medium_square: #800 | DocRepo | Wiki translation |  |
| :white_check_mark: #832 | About | Add more credits and license copy |  |
---
#### New Features

These are the other individual features, ideas, suggestions that are not parts of a larger module

| Status | Location | Description | Version |
| --- | --- | --- | --- |
| :black_medium_square: #31 | Strategy | Ship Memorial |  |
| :black_medium_square: #17 | Strategy | Device Sync |  |
| :black_medium_square: #16 | Timers | Have timers persist even if game is closed |  |

**Comment by ethrundr** [comment]
how to make tabling like that o.o

**Comment by nicky008** [comment]
@ethrundr Just looking at the code by "edit comment" button :3

**Comment by ReiFan49** [comment]
@ethrundr the table markdown indeed

**Comment by dragonjet** [comment]
ill be adding more sections. navigating the 7-page issue tracker is getting harder :v
I remember those days we try to keep it ~60 open issue :cry:

**Comment by ethrundr** [comment]
@nicky008 ah! I forgot I can do that to see the code... XD

**Comment by nicky008** [comment]
@dragonjet But this time, you are not alone here like the earlier months...

(/me looking at @ethrundr )

**Comment by ethrundr** [comment]
eh? who are you looking to, @nicky008? me?

**Comment by dragonjet** [comment]
not enuf label colors :v

**Comment by ethrundr** [comment]
LOL XD

**Comment by ethrundr** [comment]
Translation Issue:

#551 api.html translation
#828 web.html translation

**Comment by ethrundr** [comment]
as per our discussion in #815, we currently decided to drop the attempt to collaborating with the myfleet.moe, based on the creator's reaction towards other third-party softwares.

**Comment by dragonjet** [comment]
updated list

**Comment by ethrundr** [comment]
anyway, in the **Game Goals** section, why there are two `Sparkling queue` there?

**Comment by ReiFan49** [comment]
i guess yes, (except for your 90% suggestion xD)

**Comment by dragonjet** [comment]
@ethrundr I copy paste row and edit. Forgot to remove extra copies :v
All of those three from #789 are done? Haven't checked it out myself.

**Comment by ethrundr** [comment]
@dragonjet the only thing remaining is to set the setting filter. now it's capped at 5 bar for minimum supply setting, where it actually should be capped at 9 (90%), or even 10 (100%). I just want to give the full flexibility to the user to set their own limitation for supplies.

for the main feature itself, it's already completed.

**Comment by dragonjet** [comment]
oh I see, yes that 90% is justifiable

**Comment by dragonjet** [comment]
using new github "Projects" tab we can close these "index"-type issues
