### ISSUE TITLE
Expedition results missing

### ISSUE THREAD

**Issue by bcc32** [KC3Kai/KC3Kai#823]
I haven't been getting expedition results starting sometime in the last two days.  Did something happen or have I misconfigured?

**Comment by ethrundr** [comment]
@bcc32 have you pulled the latest commit? the expedition result should be shown perfectly by now:
![screen shot 2015-09-11 at 14 11 06](https://cloud.githubusercontent.com/assets/13522800/9808146/54b93626-5897-11e5-92e2-da43a5507e74.png)

it's on 8ac0ae3 now....

**Comment by bcc32** [comment]
I was at 8bebded, shouldn't have had any problems.  It was working before just fine and stopped working at one point; I was just wondering whether it was temporarily removed.  I'll wait for my expeds to return and see if the results show correctly.

**Comment by SerialConvort** [comment]
No this was during a 2-3 run for Orel, the battle tab stayed this way during the whole sortie albeit it was still working properly but was still faded.

**Comment by dragonjet** [comment]
hm, are you on master branch? try the latest commit

**Comment by bcc32** [comment]
It's working on 8ac0ae3.  Not sure why I was having problems.
