### ISSUE TITLE
Translate the Direct DMM Gameplay Interface (web.html)

### ISSUE THREAD

**Issue by Agc0de6** [KC3Kai/KC3Kai#828]
Verniy says: "If translators could do this, it'll be хорошо!"

**Comment by ReiFan49** [comment]
the scope is wider than #551

**Comment by ethrundr** [comment]
Actually there are already thread about this in #551

**Comment by dragonjet** [comment]
alright so #551 is for api, and this is for web(dmm) :+1:

**Comment by Agc0de6** [comment]
@dragonjet What if we do this page as in popup.html?

**Comment by dragonjet** [comment]
yep, should be the same thing, add `i18n` class and the html tag content should be the `term` variable

**Comment by Agc0de6** [comment]
ok, go tryin'

**Comment by dragonjet** [comment]
ah I should also mention to do this on a feature branch. we shouldn't release this until all other languages have added theirs

**Comment by Agc0de6** [comment]
nono, i would try this locally on my computer. If it'll work, I'ii mention it.

**Comment by dragonjet** [comment]
ah sure :+1:

**Comment by Agc0de6** [comment]
I just tried this and all text dissappeared. Maybe I missed something?

**Comment by dragonjet** [comment]
you might need to add `KC3Translation.execute();` inside the document.ready function

and also import
```
<script type="text/javascript" src="../../../../library/modules/Translation.js"></script>
```
on the html file

**Comment by Agc0de6** [comment]
i tried english version. Maybe I added wrong tag...

**Comment by Agc0de6** [comment]
@dragonjet I imported script in html file and added function in css file. It still not workin'. Please check:
https://drive.google.com/file/d/0B9rXgGtUpp05N292YkVidTNhYlk/view?usp=sharing
https://drive.google.com/file/d/0B9rXgGtUpp05bUNuNEo0WmEwZ00/view?usp=sharing
https://drive.google.com/file/d/0B9rXgGtUpp05dXlPQVBIWnBOLU0/view?usp=sharing

**Comment by dragonjet** [comment]
ah~ sorry I also forgot to mention, you may need KC3Meta which loads the built-in JSON files (translations included).

Since we're past 19.2, I will edit the html and js files, while you may push the new terms to:
https://github.com/KC3Kai/kc3-translations

I will await the terms so I can input them on the html

**Comment by Agc0de6** [comment]
Ok. I'll translate values of terms

**Comment by dragonjet** [comment]
`web.html` updated at 9223493516c0ba3b72c40ffe88b5ec2ec9cc6599

**Comment by Agc0de6** [comment]
it still not working *WALL*

**Comment by dragonjet** [comment]
I just merged your translation, I'll need to update the main repo as well XD

**Comment by dragonjet** [comment]
under the `i18n-gameweb` branch

![ss 2015-09-11 at 09 54 09](https://cloud.githubusercontent.com/assets/557312/9816445/a90cc93a-58cf-11e5-8d35-e24331963a13.png)

**Comment by dragonjet** [comment]
in order to close this issue, other languages must also add their translations for these variables

**Comment by Agc0de6** [comment]
Verniy says: "УРРРАААААААА!!!"

**Comment by nicky008** [comment]
**УРРРАААААААА!!!**

**Comment by Agc0de6** [comment]
@nicky008 :+1:

**Comment by Agc0de6** [comment]
@dragonjet i switched the branch to i18n-gameweb but it still without text.

**Comment by Agc0de6** [comment]
@dragonjet I believe this'll work for api.html too, if we'll add some terms for API related text.

**Comment by Agc0de6** [comment]
![default](https://cloud.githubusercontent.com/assets/14156630/9823869/70e376d6-58e2-11e5-9479-219f12433230.PNG)

**Comment by dragonjet** [comment]
ah sure, though I'd like to change some variable names if that's ok? I'd like to start it off with a page-specific name such as `DMMStartNowButton` instead of `ButtonDesc`. The translations are global and there might be another button somewhere, future translators might get confused what those are for.

**Comment by Agc0de6** [comment]
@dragonjet this button also has its place on API.html, second button from this document should have API related term like ForgetAPIButton

**Comment by dragonjet** [comment]
Yep, will leave the final variable names here when applied

**Comment by dragonjet** [comment]
I believe these are all the variables
```
"GameDMMRedirect" : "You will be redirected to play directly on DMM website",

"GameAPIRemoveTitle" : "Remove API link",
"GameAPIRemoveDesc" : "If in any case you want to remove the saved API Link from this extension:",
"GameAPIRemoveBtn" : "Forget the API Link",

"GameAPINoExist" : "You have do not have any recorded API Link",
"GameAPIGetTitle" : "To get a new API link",
"GameAPIGetDesc" : "Use the <img src=\"../popup/img/refresh.png\" /> <strong>Refresh API Link</strong> from the <img src=\"../../assets/img/logo/16.png\" /> <strong>KC3改 menu</strong> at the top-right of your  browser.",
"GameAPIExistTitle" : "To use Existing API links",
"GameAPIExistDesc" : "If you already have an API Link on hand, you may input it here:",
"GameAPIExistBtn" : "Use API Link",
"GameAPIWhatTitle" : "What is an API Link?",
"GameAPIWhatDesc" : "These are direct URLs to your game, <em>recognized as</em> or <em>associated with</em> your account. As long as you carry this link, you are automatically \"logged-in\" and can then bypass login via DMM, therefore eliminating the need to go through VPN each time you open the game.",
"GameAPIRemindTitle" : "Reminder for New Players",
"GameAPIRemindDesc" : "Do not use KC3改 while you have not yet passed through the lottery process. This viewer assumes that the account being logged-in while extracting API Links is already playable. Once you have joined a server, you will also need to input your admiral name while not in API link.",
"GameAPIAltTitle" : "Alternatives",
"GameAPIAltDesc" : "If you do not prefer API links and desire to play KanColle naturally on DMM portal, the <img src=\"../popup/img/dmm.png\" /> <strong>Play on DMM Website</strong> from the <img src=\"../../assets/img/logo/16.png\" /> <strong>KC3改 menu</strong> also supports the <kbd class=\"light\">F12</kbd> panel with the same startup mechanics as this.",


"GameStartDashTitle" : "To start the game with Admiral Dashboard",
"GameStartDashDesc" : "To start your game and get critical information on your HQ and fleet statuses, you can open the Admiral Dashboard. This will show you information such as HQ Rank, Ship slots, Equipment LoS, Air Fighter Power, Fleet Speed, Morale, etc. You may activate this via:",
"GameStartDashWin" : "For Windows / Linux",
"GameStartDashOr" : "or",
"GameStartDashMac" : "While on Mac",
"GameStartDashChrome" : "When the Chrome panel opens, there will be a tab \"<strong>KanColle</strong>\"",
"GameStartNowTitle" : "Just Let Me Play Now",
"GameStartNowDesc" : "If you want to opt out of all those features and just want to start the game now...",
"GameStartNowBtn" : "Start the game anyway",
```

**Comment by Agc0de6** [comment]
@dragonjet GameStartDashTitle~GameStartNowBtn terms are same texts like my AdmiralDashboardText~ButtonDesc. Maybe we should choose one version?

**Comment by dragonjet** [comment]
let's use the `GameStartDashTitle`~`GameStartNowBtn`. these are the ones I mentioned I like to change names because the original are too general, and having it just `ButtonDesc` maybe confusing for future translators

**Comment by nekoworkshop** [comment]
@dragonjet 
I was working on the Japanese translation but didn't find the definition for 
`What do you mean direct? No more frame? B-but my custom background!`
and 
`If you want to play with custom backgrounds, go use API links! Click here to read more about this change.` in the latest en/terms.json
https://github.com/KC3Kai/kc3-translations/blob/master/data/en/terms.json

**Comment by ReiFan49** [comment]
"Direct access?" (means direct to DMM)
"No more frame? My Custom BG ;w;)!" (API link play use a frame, and a customizable background)
"Use API links if you need to customize the page around the game frame" (somehow, you can change the blue background by your favorite picture, only in API link play)

**Comment by dragonjet** [comment]
@nekoworkshop ah I removed those since I think everybody knows it these days. It was just a notice when people got used to DMM frames.

**Comment by nekoworkshop** [comment]
I see. I bet they would expect to see the DMM site instead of a page of warning and info when they click a button called "Play on DMM site"

**Comment by Agc0de6** [comment]
@dragonjet ok, will change terms
