### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by Agc0de6** [KC3Kai/KC3Kai#830]
![default](https://cloud.githubusercontent.com/assets/14156630/9817015/e4ea972c-58b9-11e5-9462-d600966c5996.PNG)
What we can do about this?

**Comment by dragonjet** [comment]
where is this showing?

**Comment by ReiFan49** [comment]
it just a log though o.o )

**Comment by Agc0de6** [comment]
In extensions tab. Visually text on popup.html is lost.

**Comment by dragonjet** [comment]
have you tried this?

https://github.com/KC3Kai/KC3Kai/issues/784#issuecomment-139556574

**Comment by nicky008** [comment]
Like this?
![blankout](https://cloud.githubusercontent.com/assets/10517990/9817112/f790f340-58db-11e5-9e54-1f826d03ee47.png)

**Comment by Agc0de6** [comment]
![default](https://cloud.githubusercontent.com/assets/14156630/9817162/ab7a7362-58ba-11e5-8c90-fbfe822cd6a5.PNG)
and there too

**Comment by dragonjet** [comment]
try running

```
git submodule update --init -- "src/data/lang"
```

**Comment by Agc0de6** [comment]
@nicky008 Yeah

**Comment by Agc0de6** [comment]
@dragonjet where i should do this?

**Comment by dragonjet** [comment]
on the main repo, not the translation repo

**Comment by Agc0de6** [comment]
@dragonjet submodule update result

git.exe submodule update --init -- "src/data/lang"

Submodule 'src/data/lang' (git@github.com:KC3Kai/kc3-translations.git) registered for path 'src/data/lang'
Cloning into 'src/data/lang'...
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:KC3Kai/kc3-translations.git' into submodule path 'src/data/lang' failed


git did not exit cleanly (exit code 1) (21750 ms @ 11.09.2015 20:00:38)

**Comment by NicolaosGreene** [comment]
I am having similar issues pulling the down the new clone as well

**Comment by ReiFan49** [comment]
try to use the https version of the repo ?
![image](https://cloud.githubusercontent.com/assets/9847780/9818520/4614ff74-58d3-11e5-8b03-2f33cb657d6a.png)

**Comment by Agc0de6** [comment]
@ReiFan49 HOW.U.DID.THAT?

**Comment by ReiFan49** [comment]
`git config -e`
`notepad .gitsubmodule`

edit the url of the submodule into the https link copy of the repo

**Comment by Agc0de6** [comment]
@ReiFan49 and to save?

**Comment by ReiFan49** [comment]
both of them opens default text editor, so basically use a normal save to keep the change, and close the window to make the change happen

**Comment by NicolaosGreene** [comment]
I actually use SmartGit, since I find it easier to understand. I just needed to know I need to initialize it as a submodule.

**Comment by Agc0de6** [comment]
yes, i did that!

**Comment by dragonjet** [comment]
the only thing that bothers me when using https link is that is always asks for username/pass each time I connect XD

but when you try the first time, you couldve have tried it again, this is sometimes a github problem repository sometimes dont exist, and happens to me even on normal setup, and when I try github is down, even the website. and the error message doesnt seem to be a submodule problem since it's a subrepo access, but if you've made it work now then its alright :v
