### ISSUE TITLE
Any reason to represent needed XP to next HQ Lv in negative number ?

### ISSUE THREAD

**Issue by nekoworkshop** [KC3Kai/KC3Kai#831]
![image](https://cloud.githubusercontent.com/assets/1346257/9818528/17392b46-5877-11e5-91b6-0fb755e2f7bb.png)

To me it's kind of unintuitive. If this behavior is not intended I may fix it.

**Comment by bcc32** [comment]
I think it's pretty common to use negative numbers to refer to stuff remaining.  A lot of video players I know report current time in the video as positive and remaining time as negative.

**Comment by nicky008** [comment]
As for I know now, unlike the main HQ's level above there is no any clickable choices in representing that needed EXP yet.

PS. I personally think the `jp` version text of `Next` level is a bit too long?

**Comment by nekoworkshop** [comment]
In this case a negative number is representing the "*relative position*" instead of "*distance*" (which can never be negative). Just like I'll never say "There is still -6 minutes to go." as well as "-25445 exps to next level."

It really depends on whether you treate this "next" thing as "my current exp gauge *positon* relative to a full gauge"  or "*how many* exp I need to get to reach next value"


@nicky008 I'm fixing those over-size translation right now. Didn't expect we have such cramped text area...

**Comment by bcc32** [comment]
I think it is fine to remove the negative sign if the label "Next" is there.  That would make more sense than having both "Next" and the negative sign at the same time.

**Comment by dragonjet** [comment]
hm this is first used on ship exps, under the level on the fleet panel. instead of putting `1000` which would usually mean 1000 "current" exp, it is then made negative `-1000` to indicate 1000 remaining.

On older versions this was `Next: 1000`, a positive number becuase there was something to indicate that it was the remaining exp until next level, but because of space concerns, "Next" was removed, and was replaced by just the negative sign

**Comment by nekoworkshop** [comment]
So now that we have the "Next" back, shall we go back using positive numbers ?

**Comment by ReiFan49** [comment]
sounds like yes, both timer and value required will stay unsigned right?
wait for me >w<

**Comment by nekoworkshop** [comment]
Let the Chief Maid do her job :3

**Comment by nicky008** [comment]
@ReiFan49 It's not 2AM yet so don't hurry up like yesterday...
![capture](https://cloud.githubusercontent.com/assets/10517990/9820526/6ea7a6dc-58ef-11e5-85ee-87aa027a94e5.PNG)

**Comment by ReiFan49** [comment]
somewhere on the japanese dictionary writes this..

"Midnight / 2AM", and 2AM is not good xD (i should do some _imperishable_ someday again)

**Comment by dragonjet** [comment]
> Let the Chief Maid do her job :3

lol

**Comment by dragonjet** [comment]
checked it now, seems the negative sign is removed, without visible sideeffects.

closing, feel free to re-open in case anything
