### ISSUE TITLE
License concerns 

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#832]
There are existing quest translations in various languages. As for Simplified Chinese there is http://zh.kcwiki.moe that provides a full list of quest translations, published under [CC BY-NC-SA 3.0](http://creativecommons.org/licenses/by-nc-sa/3.0/).

**Comment by Javran** [comment]
hit enter accidentally XD
anyway what I want to say is, the license says

> You must give appropriate credit, provide a link to the license, and indicate if changes were made

maybe we could have a list of links in our about page, crediting things we've used in this project.
(I thought there was one in old versions but now it's gone .. any reason about that?)

**Comment by nicky008** [comment]
Up to the decision of the translators for each language (except `jp` and `troll` XD). If you think you have already used licensed (aka. already have an owner) sources or have a doubt in license of the sources you used, you should give a credit for them too. 

For the last question, I think who can answer this is @dragonjet.

**Comment by dragonjet** [comment]
hm the problem is that the source was `SA` means share-alike, and the end-product must also be on the same license, but we're on `MIT`. Though if it's from a wiki, most wikis are CC BY SA by default but is not strictly observed. We already copy quests from the en wikia which is also CC BY SA. Though out of respect, we must add these credits as well. Will add these source on about page.

**Comment by nekoworkshop** [comment]
My two cents : Credit the source but leave the SA thing alone, considering the chance we meet a copyright troll and the hassle of changing our license around.

**Comment by Javran** [comment]
+1

**Comment by c933103** [comment]
How about having the main repo as MIT and the translation folder as ccbysa? The SA part of that cc exist for the reason that if someone take something labelled as SA, those content must be SA too.

**Comment by nicky008** [comment]
Main repo should have the `MIT` as intend from the first, for the translation related folder, `SA` is easier and clearer in managing the contents.

**Comment by c933103** [comment]
p.s. There are different version of Chinese quest translation available online, kcwiki and MoeGirlPedia's KanColle Department are in ccbyncsa while zh wikia use ccbysa. ccbyncsa do not compatible with ccbysa nor MIT. So supposingly content from kcwiki cannot be used under ccbysa or MIT, unless you obtained explicit permission from the one who originally author those content. Or maybe zoning scn translation as ccbyncsa might work too? But that mighy be a bit too complicated.

**Comment by dragonjet** [comment]
hm alright, so main repo would remain `MIT` and translation repo would become `CC BY NC SA`, I guess the non-`NC` would be compatible with `NC` since more restrictions?

**Comment by c933103** [comment]
cc by nc sa and cc by sa are exclusive afaik.

**Comment by nicky008** [comment]
Yeah, these two things are difference.

**Comment by dragonjet** [comment]
what if each language has its own license file? I think most of our languages here are hand-written by our translators and is not restricted by licenses of other sites

**Comment by KyoriAsh** [comment]
What if zh.kcwiki.moe gives permission for using the material?

**Comment by Javran** [comment]
I'll write an email to kcwiki then.

**Comment by c933103** [comment]
@Javran KyoriAsh is the one who responsible for content on kcwiki and the one who originally produce the quest page on zh.kcwiki.moe.

**Comment by Javran** [comment]
@c933103 lol I wasn't aware of this, so can we ask @KyoriAsh's opinion here?
but since it's been published & editted on wiki for a while, the contribution is also made by many other kcwiki editors.

**Comment by KyoriAsh** [comment]
Well originally we didn't think of licensing issue, so we "accidentally" chose CC-BY-NC-SA, but right now it can't be reversed as we actually aimed for CC-BY-SA for more compatibility and in order to change that wiki license, we need zh all editors to agree.

Nevertheless, you're free to use our materials, just treat it as CC-BY-SA, ignore that NC part...

**Comment by Javran** [comment]
ah that's great, thanks @KyoriAsh !

**Comment by dragonjet** [comment]
thanks @KyoriAsh~ I don't know how I forgot it but I'll definitely include these credits on the about page in the upcoming version
