### ISSUE TITLE
Request translation repo access

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#833]
would like to help on translation :)

**Comment by nekoworkshop** [comment]
I thought developers had access to translation repos.

Let me know if you need more hand for zh-cn translation. Though there doesn't seem like much left to do, except the quests.

**Comment by Javran** [comment]
I tried but I didn't have the write access.
yep for now there's not much left except quests. but I guess in the future we would need a zh-cn translation for strategy room / wiki.

**Comment by nekoworkshop** [comment]
Try this :3
![image](https://cloud.githubusercontent.com/assets/1346257/9821282/5b4149ee-5887-11e5-9f3d-c5ae0f69f4dc.png)


The strategy room is still under construction but I just realized that text in there are hard-coded at the moment (correct me if I'm wrong). Anyway it will be a long way to go.

As for the zh-cn wiki I would suggest leave it to tieba/weibo/acfun/bilibili/3dm/Ali213/ or any other Chinese communities.  That's collective intelligence from *1.4 billion* nodes.

**Comment by Javran** [comment]
Thanks, already contributing through PRs :)

for zh-cn wiki I meant https://github.com/KC3Kai/KC3Kai/wiki
I heard there are plans of translating them.

**Comment by dragonjet** [comment]
added XD
