### ISSUE TITLE
Stuck on "troll" language

### ISSUE THREAD

**Issue by SmokeyTheButt** [KC3Kai/KC3Kai#836]
Been having this issue since I've pulled 19.2

![ss 2015-09-11 at 01 38 16](https://cloud.githubusercontent.com/assets/13164250/9823191/6953d292-588a-11e5-8e09-ae95bf3f4cf7.png)

I read on FB that by going into the config and changing the language to "en" instead of "troll" that that would fix it. However, when I went into the config, the language was already set to "en". I tried reentering it to maybe see if it'd trick it back, but I had no luck.

**Comment by nekoworkshop** [comment]
You may modify the settings from localStorage directly. Sorry for my bad drawing...
![image](https://cloud.githubusercontent.com/assets/1346257/9823513/aa79dd98-5894-11e5-979f-d65e7121f029.png)

**Comment by SmokeyTheButt** [comment]
Yeah, I tried doing that before. No luck. Even switched to "jp" and nothing shows up still.

**Comment by Agc0de6** [comment]
@SmokeyTheButt just reinstall KC3

**Comment by nekoworkshop** [comment]
@SmokeyTheButt  Please note that a Japanese translation patch I submitted few hours ago broke the interface and it happened to look exactly the same as the problem you're having. Since I have fix the problem for Japanses translation I suggest you have another try or put in `en`.

**Comment by Agc0de6** [comment]
@nekoworkshop do as said in #830

**Comment by SmokeyTheButt** [comment]
Even after reinstalling it still does it. Hmm... I'm not really sure what else to try here. I might as well just wait till the next stable release.

**Comment by SerialConvort** [comment]
Yeah I'm having this problem as well now.

**Comment by ReiFan49** [comment]
well, troll language actually activated via __Troll Comments__ toggle,
by having the troll language tiself is loaded... somehow.. (it's not my intention)

**Comment by SmokeyTheButt** [comment]
I suppose it is not "troll" comments necessarily. There's probably
something else causing it if the language was already "en" and troll
comments were disabled before-hand.

**Comment by dragonjet** [comment]
I'm thinking this is related to
https://github.com/KC3Kai/KC3Kai/issues/784#issuecomment-139556574

**Comment by nekoworkshop** [comment]
A glimpse of the console message would be very helpful. I suppose JSON parser might have something to say...

**Comment by ReiFan49** [comment]
after checked the troll language...

it's because troll data failed to load on src/data/lang/**data**/troll

**Comment by SmokeyTheButt** [comment]
I assume this is what you mean @nekoworkshop ?
![ss 2015-09-11 at 08 14 29](https://cloud.githubusercontent.com/assets/13164250/9829235/bf52b712-58c1-11e5-9c80-1961b964a13c.png)

**Comment by nekoworkshop** [comment]
You got it. Looks like @ReiFan49 already got what she need, though :3
