### ISSUE TITLE
Different color for fleet requiring resupply

### ISSUE THREAD

**Issue by AlanSchaeffer** [KC3Kai/KC3Kai#841]
If any of the unselected fleets is in need of resupply, their buttons could be highlighted in some way to indicate the fact. Maybe some red outline like it shows in the resupply screen?

**Comment by dragonjet** [comment]
Applies to all four fleets, either selected or not:

![ss 2015-09-14 at 10 06 27](https://cloud.githubusercontent.com/assets/557312/9851733/dc4b6f04-5b2c-11e5-8541-55e93691f9e9.jpg)

![ss 2015-09-14 at 10 07 04](https://cloud.githubusercontent.com/assets/557312/9851748/f387caaa-5b2c-11e5-895b-176fcff51e33.jpg)

Additionally, indicates taiha, which changes the button color, but does not affect selected fleet which remains yellow. There should be plenty more indicators of taiha on currently selected fleet.

![ss 2015-09-14 at 10 10 48](https://cloud.githubusercontent.com/assets/557312/9851835/78c85b76-5b2d-11e5-8d77-80f68f2863f2.jpg)
