### ISSUE TITLE
Changing layout inside the devtools panel

### ISSUE THREAD

**Issue by AlanSchaeffer** [KC3Kai/KC3Kai#842]
This is a request I wanted to create here for some time but I've been a bit busy lately, sorry if it has already been created;
I read another issue referenced where there is word about the old layout being discontinued, so maybe this here loses it's validity unless other views are created for specific purposes like the one from issue #685.
This might just not be possible anyway, as I have no clue how differently each layout works and whatever many states and different data that can't be easily shared among them;
The idea is that the layout could be changed on the fly (a button, a selector, or maybe some way to reload the setting from the config), without the need to reopen kancolle to get the newly selected layout (I think you could also close the F12 panel an reopen it to reload, but I didn't think of that at the time). The original problem I had was during the start of the event, I wanted to get the possible expedition icons so I had to close the game and change the setting to the default theme, and would forget to change it back once I was done and on the next day I would not notice I was on the theme where combined fleet didn't work until I was mid-sortie :p 
Currently, I think it could be useful to get specialized views like the one suggested to be able to fully utilize the panel space.

**Comment by dragonjet** [comment]
unfortunately, we're already deep into the interface that this is not possible at the code's current state. probably in an overhaul for kc3 kai ni or something, but sadly not in the foreseeable future.
