### ISSUE TITLE
battle panel doesn't work

### ISSUE THREAD

**Issue by smarthsu** [KC3Kai/KC3Kai#848]
![image](https://cloud.githubusercontent.com/assets/14250548/9832295/c79b2610-59a8-11e5-9e60-8cf52fbae3ba.png)

it shows nothing at start point(e.g 2-3 c) and become normal when moving to next point

**Comment by nekoworkshop** [comment]
Addressed in #826

@ReiFan49 Did the hotfix rolled out to the store ?

**Comment by ReiFan49** [comment]
not yet, still 19.2 so far.

**Comment by nekoworkshop** [comment]
Any suggestion for our friend here ? Maybe wait for the next update ?

**Comment by ethrundr** [comment]
Let's call for @dragonjet 

More and more complaints about this error is coming up. Like the 19.1 before, let's we implement a hotfix here in 19.3, as soon as possible. I'm feeling the later we hold this un-updated, the more dupe reports like this will be coming by.

**Comment by dragonjet** [comment]
Yea we could only wait for `v20` this friday >.<
Unless should we do `19.3`? Sounds extra work :v

**Comment by smarthsu** [comment]
thank you guys
お疲れさま

**Comment by ethrundr** [comment]
@dragonjet I suppose we can do 19.3 by Monday or Tuesday, just for this fix.
Waiting till Friday is bit long for me, as the reports are coming per hour, not per day now....

**Comment by SerialConvort** [comment]
Yeah I have this problem too, waiting for the fix.

**Comment by dragonjet** [comment]
@ethrundr alright will schedule it Tuesday.
I have a meeting on tonight and tomorrow so

though can refresh me what thread was this related to again?

**Comment by ReiFan49** [comment]
#826 ?
well, on webstore version i don't have localStorage.maps, and errors same like that w')~
