### ISSUE TITLE
Suggestion: notify user to refresh their API link at the beginning of each month?

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#851]
the title says it all, it doesn't seem to be mentioned in any conspicuous place.
One of my friend complained about the boss HP didn't get reset and it turned out that he was totally unaware of the API link issue.

**Comment by ethrundr** [comment]
Ah this might be a good idea. 

The notification should appear along with the timed monthly quest reset.
Not much people know that they need to refresh their API at least once a month, but lot of them are using API to play.....

**Comment by ReiFan49** [comment]
sounds like there'll be no toggle for this right ?

**Comment by bcc32** [comment]
I like this.  Probably put it on the api play page?

**Comment by Javran** [comment]
@bcc32 I'm thinking about the same thing, just need some description on api play page so user would have a better chance of reading it...

**Comment by AlanSchaeffer** [comment]
Could we have an option to automatically refresh the API link when you go Play via API Link, before opening the game, if the current saved link is not associated with the current month?

**Comment by dragonjet** [comment]
ah yes, @bamboo3250 implemented something like this before for monthly quest reset. Maybe we can look at how its done (it was something I surrendered to before).

**Comment by ethrundr** [comment]
@AlanSchaeffer I like the idea of "automatic refresh" actually. However, user will have chance to opt-out from the automatic refresh. Like, let's say, when new month coming and his API still the last month's, below (or beside) the "Play Now" button, there will appear another button, called "Refresh Your API for This Month" or similar to it.

This way, they both get notification that they need to change API link, as well as the option to do so, however it is not enforced. Not everyone has decent connection during their first connection in the new month, so just let the user do it by themselves, we just provide the alert and "easier way" to do it.

**Comment by SerialConvort** [comment]
Sounds like a good idea to me as well.

**Comment by bamboo3250** [comment]
The automatically refresh for daily, weekly and monthly quests is in `QuestManager.js` but it is for 5 AM JST (or 8PM GMT from the previous day). You may want to change some parameters to change it to midnight JST.

**Comment by ethrundr** [comment]
@bamboo3250 nah, imo it's sill fine to stick to the monthly reset. setting it 5 hours late for the notification is not that crucial, as the EO maps stays there for a whole month. also, most people also tend to do it on the second day onwards, while those who aiming for rank will do it even more later, around in mid-month or so.

**Comment by mikenzb** [comment]
The API has been phased out in chrome version 55, Issue no longer applies?
