### ISSUE TITLE
Ability to mute sounds on the fly

### ISSUE THREAD

**Issue by Arbiter1479** [KC3Kai/KC3Kai#852]
Dear KC3 Kai Devs,

I'm suggesting the ability to mute the in-game sounds of Kancolle on the fly, similar to Kancolle Viewer. Would it be possible to implement such a function? 

Regards,
Arbiter1479.

**Comment by LostLogia4** [comment]
I've been asking for this since [Issue 324] (https://github.com/KC3Kai/KC3Kai/issues/324). but it seems like we didn't get around to implement it.

**Comment by dragonjet** [comment]
To be continued on #324, I will add notes there as well
