### ISSUE TITLE
Elite Fleet Practice Counter not working

### ISSUE THREAD

**Issue by JD-Kurotoshigami** [KC3Kai/KC3Kai#853]
The counter for this quest isn't tracking the progress
its still in 0/7 even after clearing pvp

**Comment by SerialConvort** [comment]
Its a new quest so DJ probably hasn't caught up to it, its a one time quest only so all ya need to do is finish it really.

**Comment by nekoworkshop** [comment]
@bcc32 Is this about the quest tracking feature you implemented in https://github.com/KC3Kai/KC3Kai/pull/796 ?

**Comment by dragonjet** [comment]
@JD-Kurotoshigami are you on 19.2? I did my elite pvp and iirc it counts

**Comment by bcc32** [comment]
@nekoworkshop aye that's the one.

It was working for me, probably need to update to latest.

**Comment by bcc32** [comment]
@SerialConvort According to the wiki this quest is monthly.

**Comment by SerialConvort** [comment]
Ah good to know then.

**Comment by JD-Kurotoshigami** [comment]
@dragonjet yep I'm on 19.2 
update warning v19.3 in 45 hours

**Comment by bcc32** [comment]
Looks like the most important line was lost in the merge/revert kerfuffle (read "epic battle between @McDohl and Travis-kun").

Anyway I've fixed it.  Should be counting now.

```diff
commit 64dc18740f287d1e06405229524742b0a8391084
Author: Aaron L. Zeng <a2z@mit.edu>
Date:   Sun Sep 13 03:07:59 2015 -0400

    fix C8 merge/revert kerfuffle

diff --git a/src/library/modules/Kcsapi.js b/src/library/modules/Kcsapi.js
index 4a45225..1c6f4ac 100644
--- a/src/library/modules/Kcsapi.js
+++ b/src/library/modules/Kcsapi.js
@@ -705,6 +705,7 @@ Previously known as "Reactor"
                        if(["A","B","S","SS"].indexOf(response.api_data.api_win_rank) > -1){
                                KC3QuestManager.get(304).increment(); // C3: Daily Exercises 2
                                KC3QuestManager.get(302).increment(); // C4: Weekly Exercises
+                               KC3QuestManager.get(311).increment(); // C8: Elite Fleet Practice^M
                        }
                        
                        KC3Network.trigger("PvPEnd", { result: response.api_data });

```

**Comment by McDohl** [comment]
@bcc32 ah, my bad :(

**Comment by bcc32** [comment]
Merging is hard kek

**Comment by dragonjet** [comment]
64dc18740f287d1e06405229524742b0a8391084
