### ISSUE TITLE
Plane slot not updated upon return?

### ISSUE THREAD

**Issue by LostLogia4** [KC3Kai/KC3Kai#855]
One question I gotta ask, why did the plane ranks is updated on resupplies when the API call is called when the fleet has returned from sortie?

**Comment by ReiFan49** [comment]
well, basically this one is slot_item similar issue, that requires delayed request based on what i observed..

#630 is similar one becuase its still related to slotitem though,

**Comment by dragonjet** [comment]
probably just a `KC3Network.trigger("Fleet");` inside `api_get_member/slot_item`

**Comment by ReiFan49** [comment]
tried with that, but the slot count blinks to previous value in a short time

**Comment by dragonjet** [comment]
mana burn so he can't blink

**Comment by dragonjet** [comment]
mine updated on home port after PvP, that also qualifies right?

**Comment by ReiFan49** [comment]
uh oh.. i forgot about that... (only thinks about sortie xD)

**Comment by ReiFan49** [comment]
oh well, after i checked back, since pvp does not need the gear slot update suspension,
it already updates the fleet whenever port and slot_item is called (consecutively)

closing this and #630 then
