### ISSUE TITLE
[Suggestion] Pick resources/consumables that will be shown in the graph

### ISSUE THREAD

**Issue by JD-Kurotoshigami** [KC3Kai/KC3Kai#856]
![image](https://cloud.githubusercontent.com/assets/13150941/9835607/5530cc8e-5a2e-11e5-90ee-2d4dd4c5aa52.png)
I can't compare my consumables without hovering the cursor over each because of the high dev mats... so if we can select what will be shown(or what will not be shown) i think that we will get to see it better

**Comment by dragonjet** [comment]
dupe #73
