### ISSUE TITLE
Panel shiplist go empty when scrapping someone on fleet

### ISSUE THREAD

**Issue by dragonjet** [KC3Kai/KC3Kai#857]
Similar to #680, but when scrapping a member of the selected fleet in the panel

![ss 2015-09-13 at 05 08 25](https://cloud.githubusercontent.com/assets/557312/9836047/3d5c9526-5a3c-11e5-80cd-f75b18a0a345.png)

**Comment by McDohl** [comment]
![image](https://cloud.githubusercontent.com/assets/13024936/9836173/a7527e30-5a39-11e5-876d-3cde0e41e7db.png)

**Comment by ReiFan49** [comment]
zombie ship?

**Comment by ethrundr** [comment]
Not happening in my copy, though...
However it does happen during remodelling....

**Comment by dragonjet** [comment]
you probably have @ReiFan49's fix 91f5ea530339da341ca4ba819d614a187536d927?

**Comment by McDohl** [comment]
I just pulled reifan fix and its working now
