### ISSUE TITLE
console error when choosing maps

### ISSUE THREAD

**Issue by McDohl** [KC3Kai/KC3Kai#858]
I got this log error
![image](https://cloud.githubusercontent.com/assets/13024936/9836188/23f6903e-5a3a-11e5-81bb-19533a29c17e.png)
![image](https://cloud.githubusercontent.com/assets/13024936/9836192/4b4d371e-5a3a-11e5-8502-f52da9bfa3c5.png)

**Comment by ReiFan49** [comment]
i thought it has been push.... 
it should be Object.keys(maps).indexOf(ctr)
