### ISSUE TITLE
[Ask] Big, Bad, Gray Button~

### ISSUE THREAD

**Issue by ethrundr** [KC3Kai/KC3Kai#859]
What is this left button used for?
![screen shot 2015-09-13 at 20 17 21](https://cloud.githubusercontent.com/assets/13522800/9836439/d91a9b6c-5a54-11e5-9238-dcc0635743aa.png)

The image is really not telling anything to me, to be honest, not like the rest two buttons......

edit: sorry, wrong image XD

**Comment by ReiFan49** [comment]
exports for kancolledb,
for details ask @nekoworkshop

**Comment by McDohl** [comment]
you can hover your mouse there, it will show you info on tooltips

**Comment by nekoworkshop** [comment]
Now you know I suck at UI designing. I've been asking for advice about it in my commits but seems like nobody ever bothered reading them...

Anyway sorry for the confusion and thank you for bring up the issue to everyone.

**Comment by ReiFan49** [comment]
@nekoworkshop me too xD

**Comment by nekoworkshop** [comment]
@ReiFan49 Nah... Still a lot to learn and you guys surly do a better work than me...

BTW the button is for exprot deck composition to `http://www.kancolle-calc.net/deckbuilder`, not KancolleDB at `http://kancolle-db.net/`, in case you didn't make a typo.

**Comment by dragonjet** [comment]
forgot to tag this issue, but it now uses a new icon as of 0fcfcdf8517e8fec58195b80b9e387cd8af76a64
