### ISSUE TITLE
Change the way how sortie/pvp/expedition win rates are updated.

### ISSUE THREAD

**Issue by nekoworkshop** [KC3Kai/KC3Kai#861]
Currently KC3Kai only updates win rate when reading response from api_get_member/record therefore if a player have freshely installed KC3Kai, the win rates will stay at 0% until he check his record in game.

![image](https://cloud.githubusercontent.com/assets/1346257/9841135/f9a8c056-5a69-11e5-89f1-0e1df9d5ef64.png)

I suggest we update the win rate by calculating win and lose counts from api_port/port. By that way it guarantees that win rate is not zero as long as the game starts.
https://github.com/KC3Kai/KC3Kai/blob/master/src/library/modules/Kcsapi.js#L65

**Comment by dragonjet** [comment]
ah that is one of the most asked questions in the early days. However, we cannot just compute win-loss ratio by the counts. The game calculates it differently, and I don't know why/how. I definitely get different rates vs manual calculated. I even think it's because rates are somewhat time-based or calculates only those done for the past month or something.

**Comment by dragonjet** [comment]
e.g.

![ss 2015-09-14 at 11 09 35](https://cloud.githubusercontent.com/assets/557312/9841339/1a79c58e-5ad1-11e5-95c8-8febf2d8423d.png)

```
2186 - 178 = 2008
2008 / 2186 = 91.86%
```
but record screen data says 92.47%

**Comment by dragonjet** [comment]
reviewed my math 101, sure :v

**Comment by nekoworkshop** [comment]
Shouldn't it be `2186 / (2186 + 178) = 0.9247038917` ?

**Comment by ethrundr** [comment]
manual math calculation for the default value....
have thought about this before, but always forget to mention it here.... XD

**Comment by ReiFan49** [comment]
the math returns the same value.

SortieWin/(SortieWin+SortieLoses)
PvPWin/(PvPWin+PvPLoses)
ExpeditionSeikou/ExpeditionTotal
