### ISSUE TITLE
Move the Green Button

### ISSUE THREAD

**Issue by JD-Kurotoshigami** [KC3Kai/KC3Kai#862]
![image](https://cloud.githubusercontent.com/assets/13150941/9841671/b422841c-5add-11e5-8a6c-46493223006f.png)
I suggest that this button be moved to a different place... or let the user be able to click and drag it(?)

**Comment by ethrundr** [comment]
I prefer to let use move it at free, though making it possible is quite a feat....

**Comment by mikenzb** [comment]
I'm not too sure what this green button is but going to close this issue as I don't think it applies anymore, reopen if needed.
