### ISSUE TITLE
Cant Enter Game

### ISSUE THREAD

**Issue by SerialConvort** [KC3Kai/KC3Kai#866]
Once I updated, my game no longer works and is stuck on only this, anyone knows how to fix it?

![](https://i.gyazo.com/c96ad3af52625425050cd5dabc46150d.png)

**Comment by bcc32** [comment]
What console error are you getting in Chrome?

**Comment by ReiFan49** [comment]
it still merging though, git merge

**Comment by dragonjet** [comment]
try this
```
git pull
cd src/data/lang
git pull
cd ../../../
```

**Comment by SerialConvort** [comment]
Ah sorry for the really late responses, was watching some videos. I tried Git merge and what you recommended DJ, it still isn't fixing itself sadly.

![](https://i.gyazo.com/965f0e94466ac0cf84ec5861f1c986c6.png)

**Comment by nekoworkshop** [comment]
@SerialConvort Try switch to Console tab and post the error messages.

**Comment by SerialConvort** [comment]
![](https://i.gyazo.com/57bbe708e5d0f79abf662f39beec4bbc.png)

**Comment by dragonjet** [comment]
oh that one, have you tried this?
https://github.com/KC3Kai/KC3Kai/issues/784#issuecomment-139556574

since you're on `dev-subtitles` branch:
`git submodule update --init -- "src/data/lang"`

then do the
```
git pull
cd src/data/lang
git pull
cd ../../../
```

**Comment by nekoworkshop** [comment]
There you go.

![image](https://cloud.githubusercontent.com/assets/1346257/9866940/d0eec3c2-5b36-11e5-9918-1d0b8742414a.png)

Switch language to en solved the problem.

**Comment by SerialConvort** [comment]
How do I switch to en?

**Comment by nekoworkshop** [comment]
Resources->Local Storage->settings

![image](https://cloud.githubusercontent.com/assets/1346257/9866977/32800164-5b37-11e5-9274-23a4711388de.png)

**Comment by SerialConvort** [comment]
![](https://i.gyazo.com/5a98c9c04455d614b034b7e959eaa85f.png)

It was like this when I looked here, its already en so do I do something else?

**Comment by nekoworkshop** [comment]
Then do what dj said. If the problem still exists, refresh the page several times and see if some different error pops up. Also click on the 
![image](https://cloud.githubusercontent.com/assets/1346257/9867170/918d7ed8-5b38-11e5-8af6-b3030d98f9b5.png) small traingle in front of the error message to get a stack trace.

**Comment by SerialConvort** [comment]
I tried DJs method earlier, but didn't comment on it cause I don't know what Tortoise is at all ;-; other than that I tried what he suggest and it didn't fix it.

![](https://i.gyazo.com/9d5d18a778ea8e663c089cf7bec0542b.png)

**Comment by Crazyteitoku** [comment]
Tortoise(git) is another frontend management of git repository program. It is still documented on the [KC3 Kai github wiki page] (https://github.com/KC3Kai/KC3Kai/wiki/Setup-development-build#option-tortoisegit)

**Comment by SerialConvort** [comment]
Downloaded it, I don't know how to use this at all :c

**Comment by dragonjet** [comment]
when you've installed tortoise, you should right new right-click menu entries when you right-click a git-enabled folder

**Comment by SerialConvort** [comment]
So for the last day or so I've been trying to use tortoise to no avail at all. Whenever I try to merge anything or submodule update it says the merge is not possible since there is unmerged files. Where could I find these files because I have been looking nonstop and don't know which is unmerged at all.

**Comment by dragonjet** [comment]
try this on root kc3kai directory

`git.exe submodule update --init --merge --remote -- "src/data/lang"`

**Comment by SerialConvort** [comment]
I tried it but the problem still persists. I checked and it says both src/data/lang and src/pages/game/api.html needs merge.

![](https://i.gyazo.com/42f4508f3305bc22926d7ffa8112fec1.png)

**Comment by Crazyteitoku** [comment]
Try:
````
git reset --merge
````

http://stackoverflow.com/questions/6006737/git-merge-errors

**Comment by SerialConvort** [comment]
I did that then tried merging upstream and master again, but got these conflicts.

![](https://i.gyazo.com/6eb13ce3b90de75c10a618d3b7970957.png)

**Comment by dragonjet** [comment]
lol delete the directory and re-clone it. as long as you dont reinstall it on chrome extension page and clone on the same directory, it will not clear history

**Comment by SerialConvort** [comment]
The src onwards directory or another/multiple directory? Also by clone do you mean copy paste or something else cause I'm bad..

**Comment by Crazyteitoku** [comment]
"clone" as in:
````
git clone
````
Which is often used to "initialise" and pull the data from the repository. It is the first thing one does if they want a local copy of some git project.

You may as well do it in a new folder. By the way, if you haven't figured out, folder and directory are the same terminology, just used on different platforms.

**Comment by SerialConvort** [comment]
Ah thanks for the Clarification on clone and the directory terminology. So I tried to clone src but it is saying fatal: repository 'src' does not exist. Do I clone another directory or is there something else?

**Comment by Crazyteitoku** [comment]
What you needed to do is something like:
````
git clone https://github.com/KC3Kai/KC3Kai.git
````

The word "src" is not really meant to be used literally - it implies "source" and normally one would replace it with whatever the actual details are meant to be there. It is similarly with the case of [foobar] (https://en.wikipedia.org/wiki/Foobar). :laughing:

**Comment by SerialConvort** [comment]
Ok the game is now working after I did some random stuff. But now I cant git fetch upstream and the whenever I switch to dev-subtitles the problem reappears. (And apparently I made 91 commits somewhere, don't know how to fix that)

![](https://i.gyazo.com/e72aee70ace3aa259543a197b5974988.jpg)

**Comment by Crazyteitoku** [comment]
I think you missed a space in between the two dashes and the first double quote:
````
git submodule update --init --"src/data/lang"
````
appears to be the wrong syntax and hence you get a short help. The correct syntax should be:
````
git submodule update --init -- "src/data/lang"
````
Upon correct usage it should look something like [this] (https://github.com/KC3Kai/KC3Kai/issues/784#issuecomment-139753217)

**Comment by SerialConvort** [comment]
The problem still persists ;-;

![](https://i.gyazo.com/be432dc0377336aa494a90dec5b47f6e.png)

**Comment by Crazyteitoku** [comment]
Had a look back to the start of this issue and I really don't see there was any need to do:
````
git fetch upstream
````
Also according to [git-fetch manual pages] (https://www.kernel.org/pub/software/scm/git/docs/git-fetch.html) normally this step isn't required and unless you have upstream defined git fetch would normally fetch origin by default.

**Comment by SerialConvort** [comment]
Kk but the main problem still persists whenever I go to checkout dev-subtitles, is there any way to fix this?

**Comment by dragonjet** [comment]
ah since you can now freely switch branches, you can do my suggestion

```
git submodule update --init --merge --remote -- "src/data/lang"
git pull
cd src/data/lang
git pull
cd ../../../
```

**Comment by Crazyteitoku** [comment]
@SerialConvort Not that I have anything to be able to contribute to the issue of dev-subtitles but just another FYI case; when using CLI, if a program/syntax/command returns an empty line or even nothing and then returns you to prompt it usually means that the program or whatever has exited either successfully/without errors or miserably/with errors (miserably is often the source of poor programming habits but you won't see that happening with the likes of git for instance).

So in perspective of when you had to run that same command twice:
```` git.exe submodule update --init --merge --remote -- "src/data/lang" ````
Wasn't a necessity really because the program acknowledges the first time you did it and that it has exited gracefully. Not wanting to grill you here or anything but really just fyi. :sweat_smile:

**Comment by dragonjet** [comment]
but we're still not sure if his copy of `dev-subtitles` branch has already init the tl repo

**Comment by SerialConvort** [comment]
I am now getting this you are not on a branch/there is no tracking problem OTL

![](https://i.gyazo.com/ce30d9b36515d5465097e418b0c1cd66.png)

**Comment by Crazyteitoku** [comment]
This case sort of brings me back to memories where I was checking out an older version, way back before we had travis-kun and the splitting of the repositories up.

Not exactly sure how to solve this case to be honest, it seems like you may have checked out a specific version but forgot to rebase it. The best way might be is to checkout the latest version via their SHA-1 checksum and to do git pull again.

**Comment by dragonjet** [comment]
this is already re-cloned?

**Comment by SerialConvort** [comment]
Yes this is the recloned version, Ill get back to this matter tomorrow gotta sleep now.

**Comment by SerialConvort** [comment]
Since I have solved the main problem of entering the game, ill just close this issue. :v
