### ISSUE TITLE
Battle mode

### ISSUE THREAD

**Issue by baoke344** [KC3Kai/KC3Kai#867]
I just changed my PC. When I installed KC3 again but when i went  to sorties the battle mode did not appear like it was. Everything working normal, only on battle mode have problem. What wrong with my new PC. How can i fix it ?

**Comment by McDohl** [comment]
dupes on https://github.com/KC3Kai/KC3Kai/issues/826 and https://github.com/KC3Kai/KC3Kai/issues/848

just wait for new release
