### ISSUE TITLE
its been 3ver. of kc3kai,my Resource and Sortie history still not working

### ISSUE THREAD

**Issue by qqzzxx** [KC3Kai/KC3Kai#868]
using 20 right now 
i tried to reset them in 2 ways(reset in profile and in chrome resources tap.indexeDB)
the resources history like this show nothing
![qq 20150915002426](https://cloud.githubusercontent.com/assets/14226337/9870404/5c569bca-5b40-11e5-80d6-2bb3b50404c8.jpg)
the sortie history shows like this:
![qq 20150915002451](https://cloud.githubusercontent.com/assets/14226337/9870412/68b7e810-5b40-11e5-94fb-e5cc08fdb2e6.jpg)

there's no error in Console, but had several warning shows up
![qq 20150915002507](https://cloud.githubusercontent.com/assets/14226337/9870458/de642efc-5b40-11e5-93fa-b844d5b6ce2d.jpg)

**Comment by Crazyteitoku** [comment]
1. The changes upon resetting the data in the LocalDB aren't immediate. They need to take minimum of an hour for at least something to be shown in the very first graph.
2. The console warnings aren't relevant to the cause of the issue. So ideally what is needed here is your screenshot of your LocalDB table for the resources over a few periods of time.
3. Which method are you using to play the game? Playing via API Link or Naturally via DMM? If both, which one you play more often on?
4. Which OS are you using and which version of KC3 Kai are you using? You did note that you are using version 20 but is that the developer's version of KC3 Kai?

**Comment by qqzzxx** [comment]
1:was waiting for days, no,never showed
3:only playing via API Link, never tried via DMM
4:using WIN10 right now, CHROME ver is 45.0.2454.85 m (64-bit).
KC3KAI is chrome store ver. 20

**Comment by Crazyteitoku** [comment]
Ok I made a mistake, I meant IndexDB and not LocalDB as I first stated it.

The main thing now is to check to see if each of the IndexDB stores for the resources section are actually non-zero data. I have provided a screenshot of mine but of course with my personal information omitted:
![kc3-kai-indexdb-resource-tab](https://cloud.githubusercontent.com/assets/12234182/9871587/0ec341e0-5bd8-11e5-82cc-51f64a6de3e3.png)

The rest of your responses seems to be all is in order.

If the information stored in IndexDB for resources are actually non-zero you might want to try using the development version of KC3 Kai, reset the data and play with the development version of KC3 Kai for a bit to see if there are any changes.

**Comment by qqzzxx** [comment]
dont know what wrong with my computer or chrome...
cant even use development version of kc3 
![qq 20150915183206](https://cloud.githubusercontent.com/assets/14226337/9873050/3bfcbd6c-5bd8-11e5-987c-052fd45a46a7.jpg)

**Comment by Crazyteitoku** [comment]
Ah for that you need to pull the KC3 Kai translations. I was under the assumption you were using the ZIP builds as they were already "grunted". If you are using tortoisegit or something like that I believe there was a light discussion on how to do it [here] (https://github.com/KC3Kai/KC3Kai/issues/784#issuecomment-139556574)

**Comment by qqzzxx** [comment]
still doesnt work under development version
and here is my screenshot of resources.
one thing that i noticed all my "HOUR" shows "null"
![qq 20150915044753](https://cloud.githubusercontent.com/assets/14226337/9875698/231b2838-5b65-11e5-89c3-6b12329658a4.jpg)

**Comment by dragonjet** [comment]
try using the releases when attempting to install development build
https://github.com/KC3Kai/KC3Kai/releases

**Comment by qqzzxx** [comment]
still not working in development build . same as chrome store ver.
its possible because of ShimakazeGo?

**Comment by Crazyteitoku** [comment]
I had a quick search on Google to see what it is and well [this] (http://kancolle.wikia.com/wiki/Thread:145740#7) seems to explain it.

If it is a proxy server that your browser that has to go through, and if it is not sending server time from the response headers which is easily captured if you have something like LiveHTTPHacker extension for instance or really just use the network tab on developer console within the Chrome.

![chromium-network-tab](https://cloud.githubusercontent.com/assets/12234182/9895672/7a24de10-5c75-11e5-9271-00afd5ff9e2e.png)

**Comment by dragonjet** [comment]
@qqzzxx can you check if your network history has that date entry same as @Crazyteitoku's screenshot

**Comment by qqzzxx** [comment]
there is no Date in Deck tap...
so that is why？

**Comment by Crazyteitoku** [comment]
That is why yes, as per @dragonjet already stated [here] (https://github.com/KC3Kai/KC3Kai/issues/868#issuecomment-140560378)

It really is the case of poor proxy configuration from ShimakazeGo or the lack thereof configuration really.

If you disable the proxy and try playing the game without it for at least a day, presumably all is well again.

**Comment by qqzzxx** [comment]
already worked 
thx Crazyteitoku and dragonjet....
![qq 20150915212351](https://cloud.githubusercontent.com/assets/14226337/9896396/3034fc3e-5bf0-11e5-941c-468f9c23e3de.jpg)

**Comment by Crazyteitoku** [comment]
As an afterthought to this issue, maybe you can ask the maintainers behind ShimakazeGo project to either make their proxy server a transparent type of proxy or really to pass on the date and time from the server so that it won't break viewers. :laughing:

**Comment by SerialConvort** [comment]
Lol XD

**Comment by dragonjet** [comment]
and then game client checks for date headers, all those without gets banned, :v
