### ISSUE TITLE
Quest title overlapping

### ISSUE THREAD

**Issue by nicolas22g** [KC3Kai/KC3Kai#869]
There a small interface bug.

C7 quest have an issue of quest title overlapping on quest requirement

![nicolas22g 2015-09-15 12-02-48 78](https://cloud.githubusercontent.com/assets/14291618/9873741/06d7290a-5ba2-11e5-99be-4c07a74ec7d1.jpg)

**Comment by ReiFan49** [comment]
i remember someone reported this with italian translation...

**Comment by LostLogia4** [comment]
Already improvised a shorter title/description, closing.
