### ISSUE TITLE
[Usability] Equipment levels on panel are somewhat difficult to read 

### ISSUE THREAD

**Issue by NicolaosGreene** [KC3Kai/KC3Kai#870]
I find the current equipment levels being in white (#fff) somewhat difficult to read. Thus I tried a few colors including the current one used for plane proficiency (#ff0) and found it easier to read on that color. I don't know if other have experienced similar problems or what they think about this possible color change.

**Comment by Javran** [comment]
+1 for this, I also think they are a little hard to read.

**Comment by LostLogia4** [comment]
Won't small gold-yellow number on navy background be even harder to read?

**Comment by NicolaosGreene** [comment]
I found the yellow to actually contrast better than the white, but your opinion may differ. If you want to see for yourself change ~\src\pages\devtools\themes\natsuiro\natsuiro.css line 1365 from "color: #fff;" to "color: #ff0;"
