### ISSUE TITLE
Sortie win ratio in Strategy Room not correctly a percentage

### ISSUE THREAD

**Issue by denniskrq** [KC3Kai/KC3Kai#871]
My sortie win ratio in Strategy Room shows up as 0.97% instead of the 97% as it should be. Unfortunately, I'm not familiar enough with JSON and localstorage parsing to tinker with the code myself, so I'm posting this issue here.
![image](https://cloud.githubusercontent.com/assets/6935917/9883057/f224991c-5ba5-11e5-92d5-3531757a2503.png)

**Comment by ReiFan49** [comment]
someone forgot to multiply by 100..

**Comment by Javran** [comment]
reseting the value through localStorage works, maybe it's a bug in past version ...

**Comment by Javran** [comment]
I think the commit responsible for this is f23a7c0d08149f3da84915316e415d4e9dcf2080

**Comment by ReiFan49** [comment]
well, i checked my own localStorage have the same issue too

**Comment by Javran** [comment]
as a quick fix, you can go to the in-game statistics page then the value should be reset to the correct one.

**Comment by dragonjet** [comment]
ah @Javran right, if the rates already exist in the localStorage, we won't overwrite it. The older versions have the decimals, while new versions save it in its percent.

**Comment by ReiFan49** [comment]
the actual rate presented in string,
so we might treat those strings as old version calculation.
