### ISSUE TITLE
leftover quest from event

### ISSUE THREAD

**Issue by kirogami** [KC3Kai/KC3Kai#872]
![untitled](https://cloud.githubusercontent.com/assets/14297614/9883216/668a5c6e-5c0b-11e5-8144-4a527c906f2d.jpg)

leftover quest from the summer event is still there

**Comment by McDohl** [comment]
hi, how about trying to reset all quest at strategy room -> flowchart. but it will make your quest counter completely messed up. so I suggest note the counter and readjust the quest value manually

**Comment by dragonjet** [comment]
maybe on the flowchart, it will have its own entry and its own (x) button?

**Comment by kirogami** [comment]
there we go, thank you
