### ISSUE TITLE
Completed Quests Stuck in KC3 Window

### ISSUE THREAD

**Issue by Jekrel** [KC3Kai/KC3Kai#874]
I have completed quests that just hang out in the KC3 window after I turn them in. For some reason, the translations stopped working, and during that time, I turned in those quests, and now they won't go away. Picture 1 shows what the panel has, and 2 and 3 show that I don't have those quests.
![1](https://cloud.githubusercontent.com/assets/14301186/9889425/64e9f09c-5bc8-11e5-8e65-043b86d04db5.PNG)
![2](https://cloud.githubusercontent.com/assets/14301186/9889424/64e9c572-5bc8-11e5-8541-5130c90052e5.PNG)
![3](https://cloud.githubusercontent.com/assets/14301186/9889426/64ed2da2-5bc8-11e5-907c-579800945358.PNG)

**Comment by McDohl** [comment]
go to strategy room -> flowchart 
click the red X icon on respective quest

**Comment by Jekrel** [comment]
Thanks.
