### ISSUE TITLE
[Urgent-Critical] Battle Error causes ship data not to update every node. (sink alert)

### ISSUE THREAD

**Issue by dragonjet** [KC3Kai/KC3Kai#875]
As reported to me on facebook, the HPs and ship data do not update after every node. It's stuck on the "prediction" after advancing. This will be tragic for those not attentive and might get their shipfus sunk.

![ss 2015-09-16 at 05 58 05](https://cloud.githubusercontent.com/assets/557312/9891307/0b781bf4-5c38-11e5-880c-27f8649c9036.png)

Tragic for those not using prediction, and their ship HP will not update mid-sortie

**Comment by Crazyteitoku** [comment]
Ah yeah your blog page on kancolle wikia has been garnering similar distaste on that issue;
* http://kancolle.wikia.com/wiki/User_blog_comment:Dragonjet/KC3%E6%94%B9/@comment-%E3%81%BF%E3%81%A1%E3%82%8B-20150915123710?permalink=331929#comm-331929
* http://kancolle.wikia.com/wiki/User_blog_comment:Dragonjet/KC3%E6%94%B9/@comment-Beregondz-20150915193006?permalink=332071#comm-332071

**Comment by dragonjet** [comment]
ah thanks for covering up @Crazyteitoku I didn't check the wikia >.<

**Comment by Crazyteitoku** [comment]
@dragonjet No problem, gotta admit that I have also been slacking off elsewhere as well and need to pull more weight - should have also filed a bug report as needed. :sweat:
