### ISSUE TITLE
In-game node marker

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#877]
when sortieing, we could mark nodes with its corresponding letter (maybe using things similar to the in-game quest translation).

**Comment by LostLogia4** [comment]
Already implemented in edges.json, closing

**Comment by Javran** [comment]
umm I'll reopen it because this is not the same as node-tracking, I was thinking about marking node letters on nodes when going sortie.

**Comment by dragonjet** [comment]
but event maps these days come with node letters already XD

**Comment by mikenzb** [comment]
^ but but... think of all the other non-event maps? I could see this being very useful for some people including myself. 
Maybe one day we could mouse over the node letter overlays and get some data on that node like AS/AS+ numbers? probably not gonna happen but you get what I'm trying to say.

**Comment by dragonjet** [comment]
but the whole map is shown when the ship is animating, other than that it's compass or a shipfu saying _yay fuel_. I don't think there's a long time where the screen stays at the map xD

**Comment by sinsinpub** [comment]
I like the idea, adding node letter to game screen for old maps helps to identify node without keeping wiki picture opened :+1:

**Comment by Javran** [comment]
already implemented, closing.
