### ISSUE TITLE
Strategy Room Translation Problem

### ISSUE THREAD

**Issue by Agc0de6** [KC3Kai/KC3Kai#879]
![vk_saved_photo_ 635780453412050978](https://cloud.githubusercontent.com/assets/14156630/9915547/1d512c46-5cd1-11e5-9993-c7d3521ec899.jpg)
One of our translation testers switched to Legacy theme and got this. Russian language set.

**Comment by ReiFan49** [comment]
it's not legacy part :(

it's strategy room....

**Comment by dragonjet** [comment]
oh sorry I did not mention this

The ones in red box should not be translated and those on green box should.
The `good` and `bad` are CSS classes and should remain english.
Those short-hand codes on the left can be translated, and is used on places with limited space

![ss 2015-09-17 at 09 20 46](https://cloud.githubusercontent.com/assets/557312/9922640/9d858e7e-5d1d-11e5-94ee-c067881cfc8c.png)

**Comment by Agc0de6** [comment]
Oh.
