### ISSUE TITLE
is there anyway that i can use HD shipgirl and UI with kc3kai

### ISSUE THREAD

**Issue by qqzzxx** [KC3Kai/KC3Kai#880]
because the resources history and other function.

i cant use ShimakazeGo, so there is no cache file 
is thers anyway that i can use HD shipgirl and UI with kc3kai

**Comment by dragonjet** [comment]
nope, and we'll ever implement this because of our "standards".
we usually avoid tinkering with game client no matter how safe.

**Comment by c933103** [comment]
Plus, shimakazego's dev encrypted all their HDizationproject's file so that can only work if you are using shimakazego.

**Comment by LostLogia4** [comment]
Locked it because it seems to be attracting the wrong sort of attention now.
