### ISSUE TITLE
Emoticon Image Change?

### ISSUE THREAD

**Issue by LostLogia4** [KC3Kai/KC3Kai#883]
Wonder if it's possible to change the emoticons for good and great morale to these? The existing ones looks rather pale...
![3](https://cloud.githubusercontent.com/assets/12930396/9977220/26b8f12a-5f32-11e5-84d8-4738016b1b73.png) = good
![4](https://cloud.githubusercontent.com/assets/12930396/9977221/31ef6970-5f32-11e5-8b82-0a4957538347.png) = great

EDIT: Updated for conversion to PNG and removal of white edges (which didn't go well with dark background).

**Comment by JD-Kurotoshigami** [comment]
+1 to this

**Comment by dragonjet** [comment]
nice one @JD-Kurotoshigami thanks :laughing: 
also btw the current ones im using came from game files -3-

**Comment by LostLogia4** [comment]
@dragonjet For a local game asset it certainly is of a surprisingly poor quality...

Seems like I've gotten this jagged background even after removing some artefacts...
![smile](https://cloud.githubusercontent.com/assets/12930396/9981715/61b12a16-5ff7-11e5-905d-0e64b230f585.png)

**Comment by JD-Kurotoshigami** [comment]
i think it would be easier if you just draw/redraw it...

**Comment by LostLogia4** [comment]
@JD-Kurotoshigami Bad at redrawing, sadly...

**Comment by dragonjet** [comment]
thanks @JD-Kurotoshigami, as everyone knows, he's our master artist

**Comment by LostLogia4** [comment]
@dragonjet Huh? I'm the one who found the emoticon in the first place, and it wasn't redrawn yet, if it were to.

**Comment by dragonjet** [comment]
ah i mean XD it's an advance thank you since I'm hinting @JD-Kurotoshigami  to redraw it, sorry kind of a behavior in our country >.<

**Comment by bamboo3250** [comment]
Lol, i was also confused. What an interesting behavior xD

**Comment by LostLogia4** [comment]
yeah lol. Guess we'll leave that to @JD-Kurotoshigami

oh, and the [wedding](http://www.twitch.tv/lostlogia4) is just 10 hours away now.
It'll have the ring quest, the ceremony and the futon quest. Hopefully I can complete the latter without rng trolling the route too much...

**Comment by JD-Kurotoshigami** [comment]
da heck :'D
I didn't visit github for a while and never noticed this (I blame machine problem)
at least give me a pm @dragonjet

**Comment by JD-Kurotoshigami** [comment]
well... could you try these out if it still has the white things
![good](https://cloud.githubusercontent.com/assets/13150941/10309474/c2542620-6c77-11e5-90f0-dda380027a9f.png)
![great](https://cloud.githubusercontent.com/assets/13150941/10309475/c2571a2e-6c77-11e5-92a7-a6bb6320d2e7.png)

**Comment by LostLogia4** [comment]
Passable, but it looks rather flat compared to compared to the :( and :o emoticon in the same folder.

**Comment by JD-Kurotoshigami** [comment]
what do you mean flat? also may i see the :( and :o ones

**Comment by LostLogia4** [comment]
It's located in this [directory](https://github.com/KC3Kai/KC3Kai/tree/master/src/assets/img/client/morale).
![1](https://github.com/KC3Kai/KC3Kai/blob/master/src/assets/img/client/morale/1.png)
![2](https://github.com/KC3Kai/KC3Kai/blob/master/src/assets/img/client/morale/2.png)

**Comment by SerialConvort** [comment]
+1

**Comment by JD-Kurotoshigami** [comment]
![goodv2](https://cloud.githubusercontent.com/assets/13150941/10334689/c6ea9386-6d26-11e5-93a8-7a641591736c.png)
![greatv2](https://cloud.githubusercontent.com/assets/13150941/10334690/c710c9d4-6d26-11e5-8971-eb082f7a45c2.png)
here made the borders darker

**Comment by LostLogia4** [comment]
Nicely done.

**Comment by LostLogia4** [comment]
Can include this image into the next version, anyone?
