### ISSUE TITLE
(Suggestion) Experiences Calculation

### ISSUE THREAD

**Issue by convoicon** [KC3Kai/KC3Kai#886]
I think we should make a calculation for leveling up a girl.
For example Hibiki is lvl 50 how many 4-3 or 1-5 runs to do until she 70?
Each map has a differences exp + mvp + fs or just mvp or just fs.
It just my thinking. :+1:

**Comment by LostLogia4** [comment]
Discussed earlier in #326 #27.

**Comment by dragonjet** [comment]
ah by the way @LostLogia4 I added you last time to Managers team, this should let you edit issues and add tags. Not sure how to confirm the invitation though, should be same as the original kc3kai org invite

**Comment by LostLogia4** [comment]
@dragonjet Necrothreading, yeah, but seems like the invite is at the [organization page](https://github.com/KC3Kai).
