### ISSUE TITLE
Lingering quests from event

### ISSUE THREAD

**Issue by dragonjet** [KC3Kai/KC3Kai#887]
To those who failed to do the event quests. Who do not want to reset all quests.
Add ability to remove them. probably same as the controls as the recurring quests on strategy room

**Comment by ReiFan49** [comment]
don't forget about "hishimochi"-ish quest,
so basically the point of this upgrade is...

if the quest is still lingering around after the expiration date (we put it manually ofc), it'll be removed automatically like usual dailies expiration or others.
