### ISSUE TITLE
Shiplist blank, no timer faces, everything else works

### ISSUE THREAD

**Issue by dragonjet** [KC3Kai/KC3Kai#888]
Only saw screenshots but it's been 4 or 5 reports that this happens.

http://kancolle.wikia.com/wiki/File:Screen_Shot_2015-09-17_at_22.58.39.png

**Comment by ReiFan49** [comment]
ummm i'm afraid one of the slotitem is either not registered or somewhat buggy,
i remember having a 12cm from a certain ship and it breaks the shiplist (which makes the list empty, like usual flagship remodel)

**Comment by dragonjet** [comment]
separate report but similar case:

guided him on how to debug and found this

![12081625_10207496555639389_567089630_n](https://cloud.githubusercontent.com/assets/557312/10368667/031d5c98-6e09-11e5-8a44-feac7b4e2d31.jpg)

**Comment by dragonjet** [comment]
Found fix to this common problem

* Refresh the game screen without closing the panel
* Chooose "*Start Game Anyway*"
* Wait until player reaches home port screen
