### ISSUE TITLE
haul reports

### ISSUE THREAD

**Issue by dragonjet** [KC3Kai/KC3Kai#889]
[report](https://www.facebook.com/dragonjetmkii/posts/10153294535242730)
:recycle: ~~enable sound or any notification when morality is restore full, which mean 49)~~ #958

[report](https://www.facebook.com/dragonjetmkii/posts/10153313177662730)
:x:  ~~is it possible to update plane count after each battle end, i know the battle log show how many plane lost, but i am not sure which slot of plane is lost, so.... wish to able to know remaining plane in each slot on each battle end~~ (**wontfix**)
:recycle: ~~possible to update contact result on sortie ? like which plane make contact at the node~~ #960
:recycle: ~~is it possible too to act on AACI which ship does the cut-in at the sortie history~~ #959

**Comment by ReiFan49** [comment]
- plane count on ships? hmmm guessing is the best option though,
- AACI? i remember it was stored somewhere on `api_kouku` and `api_kouku2`, maybe i should check 1-6 log huh
- Contacting plane? API data gives the plane master ID that contacts right?

**Comment by dragonjet** [comment]
i think (1) is doable each time morale is less than minimum on settings, it will countdown (*if it doesn't already, i haven't been playing*) and pop a sound similar to timers upon zero.

(2) aren't we already doing this? because iirc we get `ship_deck` after each battle, and those iirc contained all ship data including slots, which would naturally show up when we call `Fleet` listener after each battle/compass.

(3) I'm not sure about this though, last I remember there are different types of detection, one done by planes or by radar, but for contact - I haven't checked the API enough.

(4) same, I'm not sure which part of API tells this -.- coz it's also possible client-side is making the checks, there are specific rules on who does the AACI and no need to server-side for that - just a guess.

**Comment by bamboo3250** [comment]
(3) the API returns item id of the plane that does contact (if no contact, it returns -1) so it's totally possible to do it.

**Comment by ReiFan49** [comment]
```JSON
api_air_fire: {
  api_idx: 3,
  api_kind: 1,
  api_use_items: [122, 3, 106]
}
```

akizuki performing AACI

**Comment by dragonjet** [comment]
all possible enhancements branched out into their own issues
