### ISSUE TITLE
Toggle between Rankless/Ranked Fighter Power

### ISSUE THREAD

**Issue by LostLogia4** [KC3Kai/KC3Kai#892]
Can we have the ranked fighter power displayed with a plane symbol with chevron insignia and toggle with the unranked one?

**Comment by ethrundr** [comment]
The question is, has the formula for the ranked planes accurate?

**Comment by LostLogia4** [comment]
Not sure about accuracy part but this aircalc should be as accurate as it could get.
http://kcascalculator.azurewebsites.net/

**Comment by ethrundr** [comment]
We need to make sure it's accurate though, for everything we put into the extension.
Since, as I experienced so far, all our users are taking everything we put on there as true.

**Comment by Javran** [comment]
how aircraft proficiency affects the calculation is still under investigation but I suspect the exact formula will be figured out very late. but meanwhile I think it doesn't hurt to have an estimated one.
for user concerns, we can make this feature disable by default, and tell user it's experimental in settings' description text.

**Comment by LostLogia4** [comment]
Already implemented, closing.
