### ISSUE TITLE
Light damage (yellow) cannot akashi

### ISSUE THREAD

**Issue by dragonjet** [KC3Kai/KC3Kai#894]
@Javran I'm not sure about mechanics of this, but is this non-akashiable?

http://kancolle.wikia.com/wiki/User_blog_comment:Dragonjet/KC3%E6%94%B9/@comment-Tcm91-20150922105320?permalink=334645#comm-334645

image:
http://kancolle.wikia.com/wiki/File:4xFP8ZS-1-.png

**Comment by Javran** [comment]
maybe something is wrong with the predicate, I didn't write that part.

the result looks good from my lib:
![2015-09-23_135530_3360x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/10053553/ca26146c-61fa-11e5-9fe0-477d40acbb45.png)

**Comment by ReiFan49** [comment]
akashiable - must not in sortie, must not repaired, must not expedition/away
if i remember correctly
