### ISSUE TITLE
Request translation repo access [Thai (th)]

### ISSUE THREAD

**Issue by arialypse** [KC3Kai/KC3Kai#897]
Request translation repo access

Hi, i'm Arialypse from KC-TH (https://github.com/KC-TH) and we will translation KC3 files for Thai player.

My team has 2 member for invitation to access
@Arialypse
@Anime-Thai

**Comment by Crazyteitoku** [comment]
Added, welcome aboard!

**Comment by Anime-Thai** [comment]
I have not received an email invitation to access

Please email invitation to me again

Thank you very much

**Comment by Crazyteitoku** [comment]
@Anime-Thai sorry about that, I thought @arialypse only meant him/herself. Invitation has been sent to you now. :sweat_smile:

**Comment by Crazyteitoku** [comment]
@dragonjet we'll need to add these two people to the credits page: https://github.com/KC3Kai/KC3Kai/issues/142

**Comment by dragonjet** [comment]
yep keeping this open until they're added to the about page

**Comment by dragonjet** [comment]
Added @arialypse and @Anime-Thai to dev list, and TH to language settings as of
5e5bb7df69742a63abd593e17839a0215c736bc9

Though can you guys confirm if the language is called "ภาษาไทย" natively? xD
We use the native writing of the language name for the settings.
Also, you can add your links to #142 or just comment here so we can add them to your about page entries.

**Comment by arialypse** [comment]
Yes, we confirm "ภาษาไทย" for Language setting.

**Comment by dragonjet** [comment]
thanks :+1:
