### ISSUE TITLE
Quest Update 25 Sept 2015

### ISSUE THREAD

**Issue by McDohl** [KC3Kai/KC3Kai#898]
Shoukaku composition quest :
```
{
"api_no":161,
"api_category":1,
"api_type":1,
"api_state":1,
"api_title":"「第五航空戦隊」を再編成せよ！",
"api_detail":"「翔鶴」「瑞鶴」と随伴駆逐艦「朧」「秋雲」を基幹とした第五航空戦隊を再編成せよ！",
"api_get_material":[300,0,0,300],
"api_bonus_flag":1,
"api_progress_flag":0,
"api_invalid_flag":0
}
```

Ashigara composition quest : 
```
{
"api_no":163,
"api_category":1,
"api_type":1,
"api_state":1,
"api_title":"「第十六戦隊(第一次)」を編成せよ！",
"api_detail":"「足柄」を旗艦として「球磨」「長良」を擁する、第十六戦隊(第一次)を編成せよ！",
"api_get_material":[150,150,150,0],
"api_bonus_flag":1,
"api_progress_flag":0,
"api_invalid_flag":0
}
```

sortie quest to bashi island (2-2) @Crazyteitoku thanks for the data:
```
{
"api_no":289,
"api_category":2,
"api_type":1,
"api_state":1,
"api_title":"「第十六戦隊(第一次)」出撃せよ！",
"api_detail":"「第十六戦隊(第一次)」をバシー島沖に展開、敵艦隊を撃滅せよ！",
"api_get_material":[200,0,200,0],
"api_bonus_flag":1,
"api_progress_flag":0,
"api_invalid_flag":0
}
```

**Comment by NicolaosGreene** [comment]
B50 Sortie Shoukaku, Zuikaku, Oboro, Akigumo to 5-2
{
"api_no":287,
"api_category":2,
"api_type":1,
"api_state":2,
"api_title":"「第五航空戦隊」珊瑚諸島沖に出撃せよ！",
"api_detail":"再編成した「第五航空戦隊」を珊瑚諸島沖に展開、敵機動部隊を捕捉撃滅せよ！",
"api_get_material":[0,500,0,0],
"api_bonus_flag":1,
"api_progress_flag":0,
"api_invalid_flag":0
}

B51 Sortie Nachi K2, Ashigara K2, Tama, and Kiso to 3-1
{
"api_no":288,
"api_category":2,
"api_type":1,
"api_state":1,
"api_title":"新編「第二一戦隊」北方へ出撃せよ！",
"api_detail":"新編「第二一戦隊」を基幹とする艦隊で北方海域モーレイ海に出撃、敵を撃滅せよ！",
"api_get_material":[300,300,0,0],
"api_bonus_flag":1,
"api_progress_flag":0,
"api_invalid_flag":0
}

Also how do you get those grey boxes for the data?

**Comment by dragonjet** [comment]
@NicolaosGreene which gray boxes?

**Comment by dragonjet** [comment]
Added all new quests, there are around 2 or 3 quests that we have no ID yet, but I added them after the last ID of each quest type

https://github.com/KC3Kai/kc3-translations/commit/1e3f03ff46a6de5e138b07beacf93f5af9d2aa1e

**Comment by McDohl** [comment]
@dragonjet  I think he mean like this
```
try put 
` ` ` 
without space bar
` ` `
```

**Comment by dragonjet** [comment]
oh! I'm using second monitor for github, and it's not vivid colors so everything seemed white to me :laughing: when I moved to first monitor I saw the gray box

**Comment by NicolaosGreene** [comment]
@McDohl That is what I meant thanks!

**Comment by McDohl** [comment]
I believe this, its the correct ID, for now going to close this till further news

**Comment by McDohl** [comment]
re-open because lacking the F21 quest

**Comment by dragonjet** [comment]
F21 is from #905?

**Comment by McDohl** [comment]
no F12 is the scrapping 7 equipments after doing 80 hours expedition

**Comment by McDohl** [comment]
@dragonjet should we close this issue for now?
