### ISSUE TITLE
[Question] Where are the ships icons saved?

### ISSUE THREAD

**Issue by kololz** [KC3Kai/KC3Kai#899]
Yeah, just asking where the database is, scanned the whole database and found nothing about those ship girl icons. I want to get to know where the database is and perhaps I might want to revamp/add some of these to the database in order to sync the future updates faster.

**Comment by nekoworkshop** [comment]
It's on DJ's photobucket.(･∀･)

http://s708.photobucket.com/user/dragonjet25/profile/

**Comment by kololz** [comment]
wut-wait... ITS OUT OF EXPECTATIONS :v

**Comment by kololz** [comment]
Btw I got too bored and helped DJ with these :v
![shoukakuk2akc3kaiicon](https://cloud.githubusercontent.com/assets/12908497/10115532/837bf668-643d-11e5-834a-11f1be7e0c14.png)
![shoukakuk2kc3kaiicon](https://cloud.githubusercontent.com/assets/12908497/10115533/8384ac90-643d-11e5-9d61-ea8617227d5d.png)

**Comment by dragonjet** [comment]
ah thanks! gonna upload them right now
