### ISSUE TITLE
Is kc3kai possible on android?

### ISSUE THREAD

**Issue by c933103** [KC3Kai/KC3Kai#901]
It would be possible to intercept communication from android client to server by asking user to set a system proxy that mandate all wifi traffic to go through certain port and let the app monitor the specific port and it probably can display some info by overlaying them on top of the game, but is it actually doable? And is there enough people help to do that after it release?

**Comment by dragonjet** [comment]
I doubt we'll stray away from our Chrome extension environment, most we could probably go into would be to support other browsers since the codebase is already built, just a matter of porting. But if we're gonna do a new "interceptor"/viewer from scratch, I doubt we'd give more efforts on that XD
