### ISSUE TITLE
Exercises quest tracking problem

### ISSUE THREAD

**Issue by bcc32** [KC3Kai/KC3Kai#903]
Quest tracking is counting the victories from before Daily Exercises 2 is selected towards the 5 victories required, but the game doesn't consider these as part of the progress towards the quest.

**Comment by bcc32** [comment]
Actually, Weekly Exercises is having a weird problem too.  Reset just happened today and already 20/20.  Something changed with quest tracking?

**Comment by McDohl** [comment]
PvP too

**Comment by bcc32** [comment]
2fcd524139d0ce6feef1f084693f4847a89e2a46 refactored battle results and added PvP to resultScreenQuestFulfillment()

Should be a short fix.

**Comment by bcc32** [comment]
Fixed 78b4ecd26c29241744684f083acf4c6e4e7b063e

**Comment by bcc32** [comment]
Missed Daily Exercises 1: fixed in d96291ca9a0998a5c57b8b5de053e24693463d6e
