### ISSUE TITLE
Quest Bug? 

### ISSUE THREAD

**Issue by RredderR** [KC3Kai/KC3Kai#905]
![kc3kai bug](https://cloud.githubusercontent.com/assets/14126825/10162607/17288216-66df-11e5-81b5-d3b8908a03e3.png)

Can you put the translation for this quest? Thanks.

**Comment by McDohl** [comment]
are you using webstore version or GitHub version? I believe its done on https://github.com/KC3Kai/KC3Kai/issues/898 
quest api_no :288

**Comment by RredderR** [comment]
I use the Dev version.

**Comment by McDohl** [comment]
weird, it should be working, mind to pull latest GitHub version and translation too?

**Comment by RredderR** [comment]
I'm sorry?

**Comment by Crazyteitoku** [comment]
Which dev. version are you using @RredderR or specifically how did you obtain your own copy of dev. version?

**Comment by RredderR** [comment]
@Crazyteitoku I believe my Dev version is V.20 ('Cause V20.1 is just about to be released). And sir DragonJet told me to download the dev version when I joined his KC3Kai Tester team. I forgot where I downloaded the zip file, though. But I think I got it here on GitHub. I'll just wait for the issue to be resolved.

**Comment by dragonjet** [comment]
you can redownload 20.1 from here
https://github.com/KC3Kai/KC3Kai/releases/tag/20.1

dev versions will say "*next version to be release in..*" but will never be updated automatically. Only webstore releases get auto updates.

you'll need to redownload the latest release from
https://github.com/KC3Kai/KC3Kai/releases
and overwrite the old folder

**Comment by RredderR** [comment]
Thanks sir
