### ISSUE TITLE
[OLD BUG] Fleet 1 Battle Prediction

### ISSUE THREAD

**Issue by RredderR** [KC3Kai/KC3Kai#906]
I'm not sure if you guys are still working about this bug. KC3 can't still predict the damages I will receive, Enemy vessels, Ship prize, etc.

**Comment by dragonjet** [comment]
is it the same as this?

http://vignette1.wikia.nocookie.net/kancolle/images/0/0c/Screen_Shot_2015-09-17_at_22.58.39.png/revision/latest?cb=20150918030100

**Comment by RredderR** [comment]
Mine still shows the kanmusus in fleet 1.

**Comment by Crazyteitoku** [comment]
Can you provide screenshots with your bug reports? it is hard for others to clarify exactly what issue you are facing. The lack of descriptions isn't helping much either.

**Comment by McDohl** [comment]
is it by any chance still related to your old issue? https://github.com/KC3Kai/KC3Kai/issues/772

**Comment by dragonjet** [comment]
ah~ it must be because he never got 20.1 because dev versions don't auto-update, similar to the discussion in #905

**Comment by dragonjet** [comment]
@RredderR let us know if you still encounter this after getting version 20.1

**Comment by RredderR** [comment]
@dragonjet Please close :P
