### ISSUE TITLE
[Suggestion] KC3Kai Global Chat

### ISSUE THREAD

**Issue by RredderR** [KC3Kai/KC3Kai#907]
KC3Kai Global Chat - We're not sure if KC's devs will ever put one. Better if we put it ourselves for KC3Kai users. 1 chat section which unites all servers/server to server chat. There should also be a chat section for devs like us (for plans or such).

**Comment by dragonjet** [comment]
perhaps something like this?
https://gitter.im/KC3Kai

**Comment by McDohl** [comment]
there is already global chat at gitter

**Comment by Crazyteitoku** [comment]
As @dragonjet and @McDohl there is already this same topic being pointed out: https://github.com/KC3Kai/KC3Kai/issues/876

**Comment by LostLogia4** [comment]
Hmm, a chat system could come in handy with the friend system we're discussing in #864.
A global chat though, I don't really think DJ's micro server could really handle the potential chatting traffic.

Speaking of chat system, there are times where we're so busy that we can't afford to get distracted, so we'll need to add a (silent) busy mode as well.

**Comment by dragonjet** [comment]
to be honest I tried looking for embeddable global chatrooms for the "Social System" overlay, but so sad unable to get one. So I'm thinking of just putting dev twitter on it :(

but if someone knows of a free, unlimited embeddable chatroom, please do link :v

**Comment by RredderR** [comment]
Is there such thing as an embed-able  chatroom, though?

**Comment by RredderR** [comment]
Oor we could embed a Pacman/Mario game just in case the player gets bored/still waiting for something.

**Comment by RredderR** [comment]
'Cause I know an embeddable Mario game

**Comment by LostLogia4** [comment]
@RredderR Game within a game? C'mon, this isn't a VR game...

**Comment by Crazyteitoku** [comment]
Wait, a game within a chatroom whilst the user's are waiting for their bugs/issues to be addressed? that might not be a bad idea but would be a new paradigm.

A game within a game? I think people tend to multitask these days that playing an extra game within the game is somewhat redundant.

**Comment by dragonjet** [comment]
with the new interface of the social system, I scrapped the right panel and the feed will take up all the remaining space to the right. No need for the chatroom nor dev twitter widget

See: http://puu.sh/kteAf.jpg

**Comment by dragonjet** [comment]
by the way, closing this in favor of #864
