### ISSUE TITLE
Translation Bug for Chitose/Chiyoda A

### ISSUE THREAD

**Issue by LostLogia4** [KC3Kai/KC3Kai#912]
The current English ships.json left Chitose and Chiyoda A untranslated...
Not sure why, but it seems like adding "_A":"-A" didn't work...

**Comment by ReiFan49** [comment]
hmmm
```Javascript
/* STDIN  */ KC3Meta.shipName("千代田航改二")
/* STDOUT */ "Chiyoda-Kou Kai Ni"
/* STDIN  */ KC3Meta.shipName("千代田甲")
/* STDOUT */ "Chiyoda -A"
```
Chiyoda + _A right?

**Comment by LostLogia4** [comment]
Well, yeah...

**Comment by McDohl** [comment]
is this still occurred?

**Comment by LostLogia4** [comment]
Glad that u asked...
![spaced](https://cloud.githubusercontent.com/assets/12930396/10862640/c7ceaa26-7feb-11e5-9e10-35d40d252002.png)

**Comment by LostLogia4** [comment]
Long solved and overdue, closing.
