### ISSUE TITLE
Bd2 marks as completed when doing practice mode battles 

### ISSUE THREAD

**Issue by NicolaosGreene** [KC3Kai/KC3Kai#914]
In version 35a774aba2a376562496c6e6307f5c59c9ea8db4 if you have Bd2 active and do a practice battle it marks the quest as complete even though practice battles do not fulfill the conditions to clear it.

**Comment by ReiFan49** [comment]
uh oh....

**Comment by NicolaosGreene** [comment]
checked it and it seems to be working now closing the issue
