### ISSUE TITLE
Expedition complete overlay

### ISSUE THREAD

**Issue by bcc32** [KC3Kai/KC3Kai#916]
Overlay is appearing three times upon return of first expedition instead of once per expedition.  I had three expeditions complete when I open KC today and I saw some overlay three times in rapid succession.  Dunno when this feature was added but I thought whoever added it would see this somewhere in their notifications.

**Comment by dragonjet** [comment]
which overlay is this?

**Comment by bcc32** [comment]
Hmmm...  I saw a blank overlay on the ship faces when Extedition Return (where shipfaces scroll across the screen).  If nobody is working on something like that maybe it was a bug in KC client?  Can someone confirm?

**Comment by bcc32** [comment]
It was something wrong with KC client, looks like.  Closing.
