### ISSUE TITLE
More like an improvement on quest translation

### ISSUE THREAD

**Issue by Tamachan12** [KC3Kai/KC3Kai#919]
「水上打撃部隊」南方へ！
Surface Attack Fleet, toward South

This quest in specific is translated as the follow:

Deploy 3 BB(V), 1 CL + 2 Ships to 5-1 and Score a Rank S

Would suggest adding(No FBB) since the quest doesnt seem to work with them.

**Comment by LostLogia4** [comment]
Added the suggested comment [here](https://github.com/KC3Kai/kc3-translations/pull/19).
