### ISSUE TITLE
Bug with Extra Maps?

### ISSUE THREAD

**Issue by Yanjiejiu** [KC3Kai/KC3Kai#922]
The extra-map didn't renew until i signed in from the official site.

**Comment by LostLogia4** [comment]
Worked as intended for me. What did you "didn't renew"?

**Comment by Yanjiejiu** [comment]
i'm sorry if i have confused you! My english is very poor......
"didn't renew"means that the haemal strand of the "Extra Operation maps" wasn't reset

**Comment by LostLogia4** [comment]
You mean the map themselves isn't reset? Then it was not a problem on our side.

**Comment by Javran** [comment]
@Yanjiejiu KC3改 uses [API link](http://kancolle.wikia.com/wiki/Tutorial:_Proxy_Connection#API_Links). That saves you from getting a VPN but you'll have refresh it at the beginning of each month so EO maps can reset. There is a plan for notifying user (see #851) but no one seems to work on that for now.
