### ISSUE TITLE
expedition 32 experience 

### ISSUE THREAD

**Issue by c933103** [KC3Kai/KC3Kai#923]
Some on wikia think there are error in how kc3kai show it? http://kancolle.wikia.com/wiki/Expedition/Reference_tables#comm-340425

**Comment by ReiFan49** [comment]
the experience is not an exact number.
if you see expedition, the expedition differs per katori level, kanmusu level, flagship modifier, 200% luck modifier

**Comment by c933103** [comment]
200% luck modifier?
