### ISSUE TITLE
C7 title overflow

### ISSUE THREAD

**Issue by bcc32** [KC3Kai/KC3Kai#924]
![auto 2015-10-06 16-51-10 64](https://cloud.githubusercontent.com/assets/1239097/10322147/755bc422-6c4a-11e5-9f70-e7f4f8b523b5.png)

Wraps over to the next line and covers up the description

**Comment by SerialConvort** [comment]
I normally just ignore it if it ever happens, once you clear some quests or clear the quest that is buggy it cleans up itself.

**Comment by LostLogia4** [comment]
Shortened the quest title [here](https://github.com/KC3Kai/kc3-translations/pull/21).
