### ISSUE TITLE
Issue on korean translation

### ISSUE THREAD

**Issue by stryer2** [KC3Kai/KC3Kai#926]
In the korean translation version

Dail sortie 7 (original : 南西諸島海域の制海権を握れ!) (suggested korean : 남서제도해역의 제해권을 잡아라!)
 is wrongly translated as (적 북방함대 주력을 격멸하라!), which is translation for weekly sortie 7 (敵北方艦隊主力を撃滅せよ！)

The description also wrongly written to clear 3-3~3-5, instead of 2-1~2-5
suggested descrition: 남서제도해역(2-1~2-5) 보스전에서 5회 승리

On english version, the translation is fine. So i geuss that korean translation was put incorrectly.

**Comment by dragonjet** [comment]
@rephira @YukiNyaa712

**Comment by rephira** [comment]
Yes. This was already identified and the fixes were on their way. Thx for pointing out again though.

**Comment by McDohl** [comment]
I believe its done by reph. gonna close this issue
