### ISSUE TITLE
Pacific Saury Quest

### ISSUE THREAD

**Issue by McDohl** [KC3Kai/KC3Kai#927]
```
{
"api_no":290,
"api_category":2,
"api_type":1,
"api_state":1,
"api_title":"秋刀魚漁：「秋刀魚」を収獲しよう！",
"api_detail":"近海及び北方海域の漁場に展開する敵艦隊を撃破して、「秋刀魚」を3尾入手せよ！",
"api_get_material":[300,0,0,0],
"api_bonus_flag":1,
"api_progress_flag":0,
"api_invalid_flag":0
}
```

**Comment by dragonjet** [comment]
and these seem to be 291 and 292

秋刀魚漁：「秋刀魚」をもっと収穫しなきゃ！
秋刀魚10尾入手でクリア
燃料550　三式水中探信儀　伊良湖3

秋刀魚漁：もっと頑張ってもいいのよ！
秋刀魚？尾入手でクリア
燃料800/弾薬300/鋼材300/ボーキ300　艦隊大漁旗？　他？

**Comment by dragonjet** [comment]
https://github.com/KC3Kai/kc3-translations/commit/185c6499277eb4aef1b5df4dbbe06084effa595c
