### ISSUE TITLE
Pike/Saury counter

### ISSUE THREAD

**Issue by dragonjet** [KC3Kai/KC3Kai#928]
Pike:
http://kancolle.jetri.co/decodes/2015-10-09_16-24/useitem-68

Saury:
http://kancolle.jetri.co/decodes/2015-10-09_16-24/useitem-69

Add these two as temporary replacement to either `torch`, `screw` or `coin` in the consumable counts on the Basic tab

Also add fish to drop icons at end battle

**Comment by LostLogia4** [comment]
Can't we just toggle between them instead?

**Comment by dragonjet** [comment]
probably but it'll take more time and effort for items that will not stay after the mini-event
