### ISSUE TITLE
API link got invalidated after every refreshing

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#929]
not sure if this happens to you guys, it seems refreshing the game results in catbomb now. one solution is to refresh API link, or play directly via DMM.

**Comment by LostLogia4** [comment]
Happens to me as well. Seems like we got an indirect deterrence to PvP now.

**Comment by McDohl** [comment]
I got this too. this is from api_start2 申し訳ありませんがブラウザを再起動し再ログインしてください。
from google translate : There is no excuse, but please re-login to restart the browser.

**Comment by Crazyteitoku** [comment]
I think @dragonjet was working frantically on the new changes, basically api_start2 is no longer allowed or something.

@McDohl More like,"I am very sorry but please reload and re-login your browser." with my non-existent Japanese.

I think the KC devs basically made these changes in a bid to prevent botters from using bots to farm for the fishes. https://twitter.com/KanColle_STAFF/status/652412135889199104

**Comment by LostLogia4** [comment]
Happens to me as well. Seems like we got an indirect deterrence for PvP refreshing now.

Further testing indicates that this only happens when it is forcefully disconnected or refreshed. Closing the browser still retains the API link.

**Comment by JD-Kurotoshigami** [comment]
been wondering about this and i think would now be relevant...
can the "Play in DMM Website" have no scroll bars?
by that i mean make it appear the same as when playing using API
removing the other things except the game itself...
or just show a specific space(game area)

also haven't tried again but in the past the kc3kai features doesn't seem to apply when playing via dmm
....
well could it be possible that by clicking "Play by API" it would automatically refresh the API
...
sorry for jumbled thoughts

**Comment by dragonjet** [comment]
https://www.facebook.com/dragonjetmkii/posts/10153356029262730

**Comment by Javran** [comment]
@JD-Kurotoshigami you can definitely remove scroll bars, go to "Element" tab in devtool, and try to delete some nodes.

![2015-10-09_081333_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/10393438/e134ac30-6e5d-11e5-9572-70946a48908d.png)

so far I've managed to delete vertical one, not sure about the horizontal one though.

**Comment by JD-Kurotoshigami** [comment]
does deleting elements get saved when i close and reopen chrome?
if it does I'm fine with it...

**Comment by dragonjet** [comment]
nope, but we still have DMM injection CSS that was used back when we had DMM frames. it isolates the game area only.

**Comment by Javran** [comment]
it doesn't ... what you can do is to experiment what can be removed and write Greasemonkey script to do so xD

**Comment by JD-Kurotoshigami** [comment]
well that isolation and injection was what i was asking about :'D
i thought it doesn't work anymore since it doesn't happen now :'D

**Comment by dragonjet** [comment]
closing since we have DMM Frames at 43c44e6a86da48e81b095336c8f4b9323e7f0de6
