### ISSUE TITLE
[Suggestion] Auto API Refresh

### ISSUE THREAD

**Issue by JD-Kurotoshigami** [KC3Kai/KC3Kai#930]
Add an option to auto refresh api link every F5 or "Play by API link"
This could be turned on or off in the settings

**Comment by ethrundr** [comment]
here's my opinion:

- For the meantime while API expires as one-time use only, each click with the "Play by API link" will automatically refresh your API.

- Regarding API gameplay, @ReiFan49 previously has implemented an "F5" button. Why won't we add feature, that by pressing that button, your API will be automatically refreshed.

And, of course, the feature need to be toggle-able in the setting for those who want to manually update their API.

**Comment by dragonjet** [comment]
>Add an option to auto refresh api link every F5 or "Play by API link"
This could be turned on or off in the settings

>For the meantime while API expires as one-time use only, each click with the "Play by API link" will automatically refresh your API.

Refreshing API link applied to "Play via API Link" menu, see if this would suffice.

>Regarding API gameplay, @ReiFan49 previously has implemented an "F5" button. Why won't we add feature, that by pressing that button, your API will be automatically refreshed.

still, refreshing the API would involve closing the current window, revisiting DMM, and re-opening the API startup screen, which would be the same function as the main menu

**Comment by dragonjet** [comment]
Closing as of 21.1 43c44e6a86da48e81b095336c8f4b9323e7f0de6
