### ISSUE TITLE
Quest codes

### ISSUE THREAD

**Issue by AlanSchaeffer** [KC3Kai/KC3Kai#931]
Not sure if this is any bit relevant at all, but could we have the one time quests have the same naming as in the kancolle wiki? My guess is that there is no consensus on what these quests should be called and the kancolle wikia just happens to have one possible naming to it, so maybe have it as an option or maybe a plugin or something?
Here's an example: in my quest flowchart I have quest 133
![quest 133](https://cloud.githubusercontent.com/assets/11778507/10407288/535d13e0-6ebf-11e5-982e-a7eeb43efd87.png)
; in the wiki, it is actually quest A33: http://kancolle.wikia.com/wiki/Quests#A33
This one is a coincidence that they both end with the same two numbers, I thought it was related, but for example the Unryuu flagship is 143 in the flowchart and A41 in the wiki.

**Comment by dragonjet** [comment]
hm iirc the wikia is naming it as the quest is released, which is probably the correct way to do it but will have problem for quests released at the same time. I remember this during the SN operation quests, we have different IDs than wikia so we can't just convert the first digit into letter.

**Comment by ethrundr** [comment]
the possible way is altering the wikia entry, so wikia will also contain the original quest ID as what we have on KC3kai.

this way, KC3kai users can easily track with the numbers only, as well as the non-KC3kai users start to get accustomed with the original ID, since there's high chance the other third-party app like ours using this ID instead.

**Comment by dragonjet** [comment]
yes, the quest IDs we follow are true for in-game. it's kind of like the map nodes before, we don't have the same list because wikis just invent them

**Comment by ethrundr** [comment]
@dragonjet that's why, if possible we should change the numbering in the wiki.
If changing is impossible, adding details about the actual numbering is necessary.

**Comment by mikenzb** [comment]
Quest codes from wikia already added into KC3.
