### ISSUE TITLE
Docking page features

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#932]
just copying TODO list from #925 
would spend some time this weekend working on them.
feel free to comment / give suggestions about this feature here :)

see branch [dev-docking-page](https://github.com/KC3Kai/KC3Kai/tree/dev-docking-page) for the latest version.

- [x] ~~Refresh the page when switching to it, so remaining docking time will be up-to-date, for now the page refreshes when sorting, but not when switching from other strategy room pages~~ (user can reload page, not a big deal) 

- [x] `PlayerManager` now adds a field `dockingShips` to localStorage and `docking.js` reads it directly, I guess a better way would be to have some API in `PlayerManager` for reading the data.

- [x] shouha / chuuha / taiha status is calculated individually instead of using existing methods in ship object. would be nice to move this part into ship object so other modules can use.

- [x] Mark ships on expedition (like those docking ships but with another color)

- [x] ~~Show some alternative texts when no ship needs repair~~ (not worth the effort)

- [x] Help topics

- [x] Don't show facility time when a ship is docking

**Comment by Javran** [comment]
all tasks are either aborted or done. PR #940 is ready to land.

@dragonjet this feature is pretty much done. feel free to tweak xD

**Comment by dragonjet** [comment]
thanks :+1: 
will do tweaks on master branch if still needed :smile:
