### ISSUE TITLE
Quest stuck

### ISSUE THREAD

**Issue by AlanSchaeffer** [KC3Kai/KC3Kai#933]
This bug just happened here, using version 21 from webstore. The daily modernization quest got stuck. I already completed a bunch of quests today so it isn't like every single quest is doing this. I managed to capture these two logs on the console, not sure if they are related but my guess is they are:
![sem titulo](https://cloud.githubusercontent.com/assets/11778507/10408021/6717fe9e-6eca-11e5-9986-01cbe0863ea9.png)

EDIT: it happened to another quest just now, I think this whole 'kc3 session' is bugged right now and won't work until I reopen it

**Comment by dragonjet** [comment]
does this still happen in 21.1?

**Comment by AlanSchaeffer** [comment]
I'll have to keep testing. I'm not sure what causes this, and as soon as I closed the KC3 panel and opened it again, it didn't happen again.

**Comment by ethrundr** [comment]
the stuck is simply because the panel unable to sync with the flowchart in the strategy room.

for us which using devbuild and update the extension manually, this usually happens when we update one and forget to reload the other. at least, that what happened on my side.

**Comment by thedeathwar** [comment]
so... is there a way to make'em gone?

**Comment by Crazyteitoku** [comment]
Have you tried going through strategy room > quests > flowchart to clear them off?

**Comment by thedeathwar** [comment]
Thanks, that really helped! I didn't even realise the flowchart function existed until now.
Thank you very much.

**Comment by McDohl** [comment]
re-open, derped :(

**Comment by Crazyteitoku** [comment]
This is a really old bug and at this point in time I am unsure whether or not should we leave this issue opened or not as we haven't heard anything back from @AlanSchaeffer.

**Comment by thedeathwar** [comment]
am I the only one experiencing it more often after the new update?

**Comment by dragonjet** [comment]
alright, to finally solve this we must also detect the quest reward API call.
Right now marking complete relies on the questlist and if it's state=3
If we use the quest reward call, we should also re-mark as complete AND remove from actives

**Comment by AlanSchaeffer** [comment]
Sorry I didn't give any update on this;
That was pretty much the only instance it happened to me; I heard from a friend that also uses KC3 that it happened to him somewhat recently, but that's all I got

**Comment by thedeathwar** [comment]
Awesome! Just finished my weekly and monthly quest without encountering the problem.
Thank you very much for your hard work!

**Comment by AlanSchaeffer** [comment]
Hi, it just happened again with 24.3, two quests stuck

**Comment by dragonjet** [comment]
alright we probably have to do this next

>alright, to finally solve this we must also detect the quest reward API call.
Right now marking complete relies on the questlist and if it's state=3
If we use the quest reward call, we should also re-mark as complete AND remove from actives

probably next version.
alot has been reporting on facebook as well
