### ISSUE TITLE
[Bug] Negative Health Value After Consuming Damage Control

### ISSUE THREAD

**Issue by ethrundr** [KC3Kai/KC3Kai#937]
My Zuikaku has her 5th slot equipped with Damage Control, and upon usage, when entering the Night Battle, her health showing the negative value instead of reverting into the last state before sinking:
![screen shot 2015-10-11 at 04 17 42](https://cloud.githubusercontent.com/assets/13522800/10412887/99a4bb3a-6fcf-11e5-9afd-bc19524bfe4c.png)

**Comment by dragonjet** [comment]
#493 #804 related?

**Comment by ReiFan49** [comment]
anything about damecon prediction is #493

**Comment by ethrundr** [comment]
Also one more thing, if possible, remove the damecon icon after being used XD
Somehow it's bit confusing when the icon is not removed upon use, even though it'll be removed by the game once the battle ends.

**Comment by Javran** [comment]
damecon has been taken into account by the battle prediction module. closing.
