### ISSUE TITLE
Quests Not Translating 

### ISSUE THREAD

**Issue by SmokeyTheButt** [KC3Kai/KC3Kai#938]
So I feel this might be because I'm trying out "Play via DMM on Frame", but this has been happening to me since then. Quests translation don't pop up and quests don't go away upon completion. Just curious as to why this is happening... I understand there has been some issues with APIs recently. 

 I am on the latest webstore update fyi 

![ss 2015-10-10 at 03 18 54](https://cloud.githubusercontent.com/assets/13164250/10413057/64919fb6-6f62-11e5-803c-27e059b718db.png)

**Comment by ethrundr** [comment]
Playing via direct DMM turns off the quest translation, since as per current, we still unable to do overlaying on the DMM gameplay.

Playing via DMM frame is similar to direct DMM gameplay, the difference just we take only the game frame instead of displaying the whole page.

**Comment by SmokeyTheButt** [comment]
Ah okay! Thank you for replying!

**Comment by ethrundr** [comment]
Your welcome, and glad can help you :)
I'll close the issue now~

**Comment by JD-Kurotoshigami** [comment]
ehh?
I'm also playing using DMM on Frame and no problem with the translations...

**Comment by dragonjet** [comment]
yea, DMM frame should already have on-screen translations.
smokes what language, and is it enabled on settings?
quest TL and quest tracking checkboxes?

**Comment by SmokeyTheButt** [comment]
English language, it is enabled, and it works when I do API

**Comment by dragonjet** [comment]
perhaps, you might wanna try what the console says when you get in-game, as you open the quest pages

**Comment by SmokeyTheButt** [comment]
Got it, I'm not at my computer right now, but I'll be sure to screencap
once I'm able

**Comment by SmokeyTheButt** [comment]
Okay so now they're starting to pop up. Nothing appeared in the console.

**Comment by dragonjet** [comment]
:+1:
