### ISSUE TITLE
screenshot on webstore outdated

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#947]
while the legacy theme is deprecated, screenshot on webstore is not updated.

**Comment by ethrundr** [comment]
I believe I already asked @dragonjet to change it several versions earlier...
guess he still hasn't change it, eh?

**Comment by Javran** [comment]
It hasn't been changed. should be an easy task, I open this issue just for keeping a reminder.

![2015-10-12_124049_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/10433279/8f3492c8-70de-11e5-8bde-add5f5c6d9a4.png)

**Comment by ReiFan49** [comment]
nico nico niiiiii
#499

**Comment by dragonjet** [comment]
alright then I will update webstore pics even without UR since Pile-sama came here for a concert

**Comment by ethrundr** [comment]
@dragonjet argh.... I wish I can come to watch Pile...... :cry:

**Comment by dragonjet** [comment]
I was on the front row I was like so starstruck as she sand around 7~8 songs, probably 4 μ

to be further tracked on #499
