### ISSUE TITLE
poi-statistics DB submission

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#952]
similar to kancolle-db integration,
send item crafting / ship drop / ship construction results to [poi-statistics](http://db.kcwiki.moe/).

self-assigned, probably make some progress this weekend.

**Comment by c933103** [comment]
see https://github.com/poooi/poi/issues/460

**Comment by Javran** [comment]
@c933103 thanks for the info :)

implemented `create_item`, `create_ship` and `dropship`.
await further discussion on https://github.com/poooi/poi-server/issues/1 to continue:

- [ ] server side CORS support
- [ ] set `origin` field instead of setting User-Agent (which is impossible for a chrome extension).

**Comment by Javran** [comment]
done.
