### ISSUE TITLE
[Bug][Devbuild] KC3 menu isn't working? 

### ISSUE THREAD

**Issue by mikenzb** [KC3Kai/KC3Kai#953]
So I thought I would try out the devbuild today and I was greeted with a KC3 Kai menu that wasn't working.
![capture](https://cloud.githubusercontent.com/assets/5982780/10557434/9aae8f08-7509-11e5-91c9-e33e0fb2e4e2.PNG)
Any idea what might be causing this? I tried to download a zip clone and the same issue came up, I'm currently using Git and TortoiseGit to pull down new versions.

I'm also using the 64bit (beta) version of Chrome (Version 47.0.2526.16 beta-m) I'm not sure if this might be causing the issue with the devbuild but I dobut it as my webstore version works fine.

**Comment by dragonjet** [comment]
on tortoisegit, also do a "Submodule update"
check `init` and `remote tracking branch`

**Comment by mikenzb** [comment]
ugh... tortoisegit isn't playing nice with me now... 
![capture](https://cloud.githubusercontent.com/assets/5982780/10557478/0426a1e0-750b-11e5-84bc-5f18787233f9.PNG)

**Comment by dragonjet** [comment]
you're using ssh, you'll need to have SSH keys on your computer and entered onto github.

for easier git, use http link from the repo home page

**Comment by mikenzb** [comment]
Ah right thanks for that, that fixed it.
Went and added in a SSH key to my github account and recloned with my ssh key in tortoisegit and all is well after that.

**Comment by dragonjet** [comment]
:+1:
