### ISSUE TITLE
Battle Result: Show AACI

### ISSUE THREAD

**Issue by dragonjet** [KC3Kai/KC3Kai#959]
Originally from #889
On battle tab during sortie, show the ship that performed AACI if it was triggered

https://github.com/KC3Kai/KC3Kai/issues/889#issuecomment-142190312
> akizuki (4th ship on slot) performing AACI
```
"api_air_fire": {
  "api_idx": 3,
  "api_kind": 1,
  "api_use_items": [122, 3, 106]
}
```

**Comment by LostLogia4** [comment]
Here's the icon for it:
![](https://files.gitter.im/KC3Kai/Public/ZfUF/thumb/aaci.png)

**Comment by sinsinpub** [comment]
is this icon supposed to display at battle activity panel or ship list panel?
and is cut-in type or gear items to be showed? (if items list is an array of slotitem master id, I think latter may be better as it represents the type already)

btw api descs from 74EO
```
api_stage2		：航空戦2　対空砲火
			api_f_count		：味方艦載機数(艦攻/艦爆数)
			api_f_lostcount	：〃撃墜数
			api_e_count		：敵〃
			api_e_lostcount	：
			api_air_fire	：対空カットイン
				api_idx			：発動艦のインデックス 0から始まる
				api_kind		：カットイン種別
									 1：高角砲x2/電探
									 2：高角砲/電探
									 3：高角砲x2
									 4：大口径主砲/三式弾/高射装置/電探
									 5：高角砲+高射装置x2/電探
									 6：大口径主砲/三式弾/高射装置
									 7：高角砲/高射装置/電探
									 8：高角砲+高射装置/電探
									 9：高角砲/高射装置
									10：高角砲/集中機銃/電探
									11：高角砲/集中機銃
									12：集中機銃/機銃/電探
									14：高角砲/対空機銃/電探
									15：高角砲/対空機銃
									16：高角砲/対空機銃/電探
									17：高角砲/対空機銃
				api_use_items	：表示装備IDリスト
```

**Comment by sinsinpub** [comment]
@LostLogia4 would u do a favor to create two small and dark icon (27 x 27) for natsuiro theme with transparent background and `-x.png` version for not triggered (like this one:https://github.com/KC3Kai/KC3Kai/blob/master/src/assets/img/ui/dark_support-x.png)?

i have no any image editor installed on this computer for now :sweat_smile: 

btw, i'm going to add the AACI icon to the battle flags line, and it's 180px width just fit for adding 1 more icon (30px) if margin removed which looks too 'compact'... any idea XD?

**Comment by LostLogia4** [comment]
I can made a mini icon just fine, but how am I supposed to design the "not triggered" icon? :sweat_smile:

**Comment by sinsinpub** [comment]
@LostLogia4 yes, I thought it was 'no sign over that icon' :smile: anyway @dragonjet said he's making the icon.

**Comment by LostLogia4** [comment]
![aaci-mini](https://cloud.githubusercontent.com/assets/12930396/14580905/a78f6954-0410-11e6-9f23-51adefc5ff4c.png)
I think this is as good as I could do with the design
