### ISSUE TITLE
KC3Kai Dev not working

### ISSUE THREAD

**Issue by RredderR** [KC3Kai/KC3Kai#961]
![kc3kai bug](https://cloud.githubusercontent.com/assets/14126825/10569378/c7415af6-7657-11e5-9f10-34dfd90e433d.png)

Please help/fix. I did a gitpull already. Could it be my SSH key?

**Comment by Crazyteitoku** [comment]
You didn't do a submodule update.

**Comment by RredderR** [comment]
![kc3kai bug](https://cloud.githubusercontent.com/assets/14126825/10570193/e86b06fe-7662-11e5-8fab-176a439543fb.png)

@Crazyteitoku ??

**Comment by Crazyteitoku** [comment]
@RredderR see [here](https://github.com/KC3Kai/KC3Kai/issues/953)

**Comment by RredderR** [comment]
@Crazyteitoku Do I have to regularly update my SSH key as well?

**Comment by Crazyteitoku** [comment]
@RredderR see [here](http://security.stackexchange.com/questions/14983/how-often-should-an-ssh-key-pair-be-changed) for more information.

**Comment by RredderR** [comment]
@Crazyteitoku Working on it

**Comment by RredderR** [comment]
@Crazyteitoku I generated a new SSH key, cloned the HTTPS dev build because the SSH one doesnt work, and did a submodule update. 
![kc3kai bug](https://cloud.githubusercontent.com/assets/14126825/10570610/6577cd6c-7668-11e5-8706-b4cb7b337f13.png)
Still like this.

**Comment by Crazyteitoku** [comment]
@RredderR did you add your newly generated SSH key into your github account?

**Comment by RredderR** [comment]
@Crazyteitoku Yes.

**Comment by RredderR** [comment]
@Crazyteitoku I'll try it again

**Comment by SmokeyTheButt** [comment]
I've been following along with this, and I'm at the same point.

**Comment by RredderR** [comment]
@Crazyteitoku It still doesn't work. I also checked the connection of my SSH key. It says that I have successfully did it.

**Comment by RredderR** [comment]
@SmokeyTheButt Are you experiencing this too?

**Comment by SmokeyTheButt** [comment]
@RredderR Yup, I've had this issue since before Summer Event, and I never figured out how to fix it.

**Comment by Crazyteitoku** [comment]
http://stackoverflow.com/questions/3431314/github-no-supported-authentication-methods-available

**Comment by RredderR** [comment]
I think @dragonjet should help us too.

**Comment by Crazyteitoku** [comment]
Also,
http://stackoverflow.com/questions/2643502/git-permission-denied-publickey as well as
https://www.mediawiki.org/wiki/Gerrit/TortoiseGit_tutorial . The latter link is for a very rough guide on setting up tortoisegit. Even though the guide was meant for mediawiki some of the concepts can also be applied for cases such as this.

**Comment by SmokeyTheButt** [comment]
This is awfully confusing if I'm being completely honest. But then again I'm not the most intelligent on how git works.

**Comment by RredderR** [comment]
@Crazyteitoku I'm so coonfuuseed. I'm not sure what to do next. I did what I did last time I experienced this.

**Comment by mikenzb** [comment]
Oh I'm the poster of that issue a few days ago when you re-clone make sure u select this in tortoisegit: 
![capture](https://cloud.githubusercontent.com/assets/5982780/10571815/27b5842e-769f-11e5-9a19-fe5501742c0a.PNG)
Load your SSH key in there then try and do the submodule update again and it should work, (that's after u add in the same key into your github account)

**Comment by RredderR** [comment]
@mikenzb how do I load my SSH key in there?

**Comment by Crazyteitoku** [comment]
@RredderR click on the ... box and point to your SSH file that you have generated.

**Comment by SmokeyTheButt** [comment]
I was able to do it through puTTY keygen and created a private .ppk file after I uploaded it to my github account.

**Comment by mikenzb** [comment]
@RredderR The 3 dots then point it to the PPK file aka your ssh key.

Also I copy and pasted the SSH text info into github before that*

**Comment by RredderR** [comment]
I forgot where my SSH key is located ;_;

**Comment by mikenzb** [comment]
*facepalm* make a new one and reupload it to github then try again, remove the old key

**Comment by RredderR** [comment]
@mikenzb Found it. It is not a PPK file.

**Comment by mikenzb** [comment]
You want to save the private key. That's the PPK file, the public key has no extension if I'm not mistaken

**Comment by RredderR** [comment]
@mikenzb I can't open the key. It's says (Open SSH - SSH2 private key). Does it really have to be a PPK file?

**Comment by mikenzb** [comment]
It has to be a private key yeah, just go remake your SSH using the PuTTYgen program under the tortoisegit folder in your start menu, and save the private key somewhere safe while you're doing that u should have a bunch of random letters/numbers come up on that program, you want to copy that and paste it under the github SSH keys

**Comment by RredderR** [comment]
@mikenzb You totally lost me. Here's what I did: https://help.github.com/articles/generating-ssh-keys/

**Comment by mikenzb** [comment]
![capture](https://cloud.githubusercontent.com/assets/5982780/10572330/e5f3552a-76a3-11e5-94cb-36835812bc83.PNG)

**Comment by RredderR** [comment]
Do I still have to install PuTTY? Or does Tortoisegit have it?

**Comment by mikenzb** [comment]
Tortoisegit should have it if I'm not mistaken check for me if u want.

**Comment by RredderR** [comment]
@mikenzb Do I generate a key first? Since this is my first time use with PuTTY.

**Comment by mikenzb** [comment]
Yeah generate a new key, it will ask you to move your mouse around randomly to do so then save the private key.

**Comment by RredderR** [comment]
This is taking too long. Is this normal?

**Comment by RredderR** [comment]
I guess I have to move my mouse.

**Comment by mikenzb** [comment]
While yes? it does say to randomly move your mouse yeah?

**Comment by RredderR** [comment]
Still not working ;_;

**Comment by mikenzb** [comment]
Did you add the SSH key text to github and did you reclone again?

**Comment by RredderR** [comment]
@mikenzb I generated a key again, I add the newly generated key on my GIThub SSH Keys, and I cloned the dev builed in SSH link (Didn't use HTTPS), then I used my PPK to do so, but it failed.

**Comment by mikenzb** [comment]
Just use HTTPS link with the load putty key there with the PPK file and it should work.

**Comment by RredderR** [comment]
@mikenzb I used the HTTPS link and used my putty key in cloning the link. I still can't do a submodule.

**Comment by bamboo3250** [comment]
Shouldn't use SSH. I tried using public-private keys beforbefore but that didn't work. Use HTTPS instead by changing the configuration file to make it look like this.

![screen shot 2015-10-19 at 4 54 11 pm](https://cloud.githubusercontent.com/assets/8078323/10573472/3bdf7616-7682-11e5-8019-4c1d5409f601.png)

**Comment by mikenzb** [comment]
Well I'm at a lost than sorry.. That was all I knew (and what worked for me).... try do the above then and if someone else can follow up.

**Comment by RredderR** [comment]
@Crazyteitoku @mikenzb do I:
>download the HTTP clone
>clone it with my PPK
>then perform a submodule update?

**Comment by mikenzb** [comment]
>then perform a submodule update? 

Did u tick the init and remote tracking branch, [as what dragonjet said](https://github.com/KC3Kai/KC3Kai/issues/953#issuecomment-148892262)?

**Comment by RredderR** [comment]
@mikenzb Still not working.

**Comment by dragonjet** [comment]
try using HTTPS git link as @bamboo3250 said. github recommends this more than ssh

**Comment by dragonjet** [comment]
if you're free tomorrow @RredderR we could setup teamviewer so I can try control your computer

**Comment by RredderR** [comment]
@dragonjet I'll inform you when. I'm not so sure if I'm free tomorrow.

**Comment by ReiFan49** [comment]
@dragonjet umm, i almost want to throw a PR about changing .gitmodules from git:// kc3-translation (SSH) into https:// one, is it ok to push it directly? (i'll tell tortoise/gitshell for this first)

**Comment by dragonjet** [comment]
@ReiFan49  sure, that would probably help pre-solve these issues

**Comment by RredderR** [comment]
@dragonjet One question. When I type the run ssh agent command thingy, is there supposed to be another program/application for ssh agent which will open up?

**Comment by dragonjet** [comment]
right click > git gui here > help > show ssh key

add that one to your account

**Comment by RredderR** [comment]
@dragonjet Thank you sir. It's now fixed.
