### ISSUE TITLE
Misplaced Ship in the Akashi Menu

### ISSUE THREAD

**Issue by denniskrq** [KC3Kai/KC3Kai#963]
For every single day, the ships available to improve Quad O2 Torpedos display Ooi Kai twice (once where she's supposed to be and once where Kitakami Kai is supposed to be). A very minor error, but it'll probably bother people with OCD

**Comment by LostLogia4** [comment]
I've already fixed that one actually. Gotta wait for the next webstore version...

**Comment by ethrundr** [comment]
Since the newest Devbuild already fixed this, I'm going to close the issue.
If this happens later on the Webstore version, we can just simply reopen this issue again.
