### ISSUE TITLE
poi-statistics Submission Error

### ISSUE THREAD

**Issue by ethrundr** [KC3Kai/KC3Kai#964]
Poi DB Submission Failure: Connection Timed Out

![screen shot 2015-10-21 at 00 17 23](https://cloud.githubusercontent.com/assets/13522800/10611907/4ca8c094-7789-11e5-8594-816e0841e399.png)

![screen shot 2015-10-21 at 00 19 01](https://cloud.githubusercontent.com/assets/13522800/10611921/5c529ae2-7789-11e5-9a66-b94ab44c8b92.png)

Complete console report:
![screen shot 2015-10-21 at 00 21 29](https://cloud.githubusercontent.com/assets/13522800/10611991/d7e0b18a-7789-11e5-9076-906a24525adb.png)

Latest pull on 7367e26. Is this error on our side or their side or my connection?

**Comment by Javran** [comment]
I think the server is down, same error here.

**Comment by Javran** [comment]
@ethrundr I think the server is now available, are you still seeing these warnings?

**Comment by ethrundr** [comment]
@Javran haven't test it yet, gonna report whether it still there or not in approx. 2h from now

**Comment by ethrundr** [comment]
Yep it's worked already. Closing this now~
