### ISSUE TITLE
[UI Bug] Supply Over 100%

### ISSUE THREAD

**Issue by arghblargh** [KC3Kai/KC3Kai#966]
Probably a very rare case, but my Noshiro somehow has 129% ammo, causing the ammo bar to spill over the border and the panel telling me that I need to resupply.

![image](https://cloud.githubusercontent.com/assets/7242357/10684825/9c8b038c-7906-11e5-91bc-7e6db7a09c1c.png)

**Comment by ethrundr** [comment]
129% and need resupply..... :laughing:
