### ISSUE TITLE
Invite for KancolleLoader alpha test

### ISSUE THREAD

**Issue by LostLogia4** [KC3Kai/KC3Kai#970]
Just opened up a new repo [here] (https://github.com/LostLogia4/KancolleLoader), currently it only loads BGMs for now, because, you know, there are too many CGs to include for a public project as it is right now.

The real reason for the invite though, is because the project do have [quite a few issues](https://github.com/LostLogia4/KancolleLoader/issues) to resolve before it can be announced.

**Comment by Crazyteitoku** [comment]
Hey @LostLogia4 I just spoke to @Javran and he seems to be interested in seeing where he can help out. You should hang around on [gitter.im](https://gitter.im/KC3Kai/Public) too, anyway he mentioned this that may help: https://htmlpreview.github.io/

Here is the bit of conversation in context:
![](http://i.imgur.com/ocSi8Fw.png)

**Comment by LostLogia4** [comment]
Authorized gitter now. Seems like I was a bit late to join the party.

**Comment by Crazyteitoku** [comment]
Ah well at least you can go back and check the history by constantly scrolling back up to see what has been said. At least that would be some form of catch up.

Other than that I think there is always a chance in the future however.

**Comment by dragonjet** [comment]
forked it on my account

**Comment by dragonjet** [comment]
wrong button

**Comment by LostLogia4** [comment]
Already passed alpha testing, closing.
