### ISSUE TITLE
Facebook page

### ISSUE THREAD

**Issue by dragonjet** [KC3Kai/KC3Kai#971]
@KC3Kai/developers 
@KC3Kai/managers 
@KC3Kai/testers 
@KC3Kai/translators 
I have put up a new Facebook page on
https://www.facebook.com/kc3kai

If you have facebook account, give me your facebook email and I'll add you guys as admins so you can post your own announcements and share some previews to features you're working on.

**Comment by arialypse** [comment]
Email: arialypse@zeitvier.com
FB: https://www.facebook.com/Arialypse

**Comment by bcc32** [comment]
zeng.aaron.l@gmail.com
https://m.facebook.com/sezvar

**Comment by JD-Kurotoshigami** [comment]
maybe add the fb link in the "about" page?

**Comment by VRarara** [comment]
https://www.facebook.com/bayuuyab.fu

**Comment by dragonjet** [comment]
@JD-Kurotoshigami yep, actually planning to make it as popup when you open the menu for the first time :laughing: 

@VRarara will need the facebook email, you may PM it on gitter.

**Comment by JD-Kurotoshigami** [comment]
@dragonjet ayyy popup _(:3 
btw even the facebook name will do if you're friends

**Comment by dragonjet** [comment]
yep thats why I'm able to add you immediately :laughing:

**Comment by ethrundr** [comment]
well I've been added to the page, but since I'd also like to add you guys as friend, might as well leaving my FB link here:

https://www.facebook.com/pygmalion.x

**Comment by hufuhufu** [comment]
arif.hermawan12@gmail.com

How about the old page?

**Comment by ReiFan49** [comment]
https://www.facebook.com/ReiFan49
wait, i guess facebook have it's own "e-mail" for peoples that have a username such as `ReiFan49@facebook.com`, but i haven't tried to login with that (only login with username only, no facebook email domain)

**Comment by ethrundr** [comment]
@hufuhufu the old page is using @dragonjet's page, right?
So it's about time we have separate page fro KC3kai now, as the Repo itself already moved for some time

**Comment by dragonjet** [comment]
http://puu.sh/kZ413.png

**Comment by ReiFan49** [comment]
oh lol :sweat_smile:, at least that is the function of `@facebook.com` emails though...

**Comment by freezebear** [comment]
email : ren.scarlet17@gmail.com
FB : https://www.facebook.com/freezebear17
so... what will this page do / post ? about KC3kai only or we can post about KC like pics or something??

**Comment by dragonjet** [comment]
only kc3 kai stuff, like previews to features we're working on, also, it's nice if those who are already added to introduce youself :laughing: probably include a pic of your waifu or home port just so the post has an attachment. pure text posts tend to get less reach and engagement.

like the rule on the page admin group I'm in (IAL), we should also limit the post at 4-hour interval from each other. so if someone has already posted within the interval, you may schedule it (it's on the dropdown in the post button)

**Comment by RanFoxRun** [comment]
e-mail: ranfoxrun@gmail.com
facebook: https://www.facebook.com/GiuseppeBausilio

**Comment by ethrundr** [comment]
anyway if someone here added me on FB, please leave me a message as well :laughing: 

got too many friend requests daily, so most of the time I won't bother checking the request unless there is a message left....

**Comment by dragonjet** [comment]
^ same here, I only accept those with 5 mutual friends or more - is my first requirement :laughing:

**Comment by dragonjet** [comment]
gonna close this when we add the fb page on either menu or about page at v23

**Comment by ReiFan49** [comment]
hmm i wonder how i introduce my basic gameplay page lol... (no bg)... no out of topics or something right :sweat_smile: ?

**Comment by dragonjet** [comment]
@ReiFan49 I've talked to @kololz on fb chat, casual posts are fine, if it's not a day of webstore release. 

Other than webstore days we can post casual stuff - but first it would be nice to introduce yourself if not yet.

Then later on could post previews to things you are working on, or anything related. e.g. kololz recently posted a survey on what people's backgrounds are, I posted something about Ooi looking at kitakami in the icons, next time I'm planning to post what their wishlist are - anything you can think of kancolle-related.

**Comment by ethrundr** [comment]
I'll post something to the page during event later on :laughing:
