### ISSUE TITLE
Refresh bar suddenly disappeared.

### ISSUE THREAD

**Issue by meepawned** [KC3Kai/KC3Kai#972]
I'm a newcomer in kancolle. I always refreshing the API link when the connection become unstable, however, the Refresh API Bar was disappeared.

And my question is: is this a new update or an Issue?

Sorry for a dumb question, as I told you, i was a newcomer here.

**Comment by dragonjet** [comment]
Play via API link now refreshes it automatically

**Comment by meepawned** [comment]
Oh. I see. Thanks.
