### ISSUE TITLE
Show if BB's equipment overweight or not in kc3kai?

### ISSUE THREAD

**Issue by c933103** [KC3Kai/KC3Kai#977]
Rely on external data, but external data still not comprehensive

**Comment by Crazyteitoku** [comment]
I somehow don't think that won't get implemented unless all the factors have been tested out. Otherwise it would be implemented with all these warnings (probably) stating that the feature is experimental.

**Comment by ethrundr** [comment]
Too much uncertainty with this issue, although I'm not against the idea.
A lot of work and research will be required if we really want to implement this one.

**Comment by dragonjet** [comment]
yea, usually I just check the wikia but there are only mentions of it, no numbers to workwith
