### ISSUE TITLE
Add Taiha Alert settings for low-spec computers

### ISSUE THREAD

**Issue by NicolaosGreene** [KC3Kai/KC3Kai#980]
If I have Annoying Taiha Alert on and a ship gets Taiha'd I cannot see anything but my background color. I can still click on things but I can't see anything.

**Comment by ethrundr** [comment]
That's why it is called "Annoying" :laughing:

**Comment by LostLogia4** [comment]
Can we get a screenshot of it?

**Comment by dragonjet** [comment]
you could use the devtools inspector to select `class="box-wrap"`
then on the styles list, see under `.critical`
disable one of each css style and see which line will bring back the visuals

**Comment by NicolaosGreene** [comment]
disabling -webkit-filter: blur(1px); returns the visuals. Furthermore, when I played on my desktop (which is significantly more powerful) I also noticed there was a sound effect that was to go with it that seems to be dead on my laptop, I suspect that this feature may be not usable on low end machines. Because of this you may want to have an alternate version that makes the side panel red like it does now and possibly sends an alert for those who run on a low end devices.

**Comment by ethrundr** [comment]
The best solution is to let the user modify what they want to stay active as the alert (sounds, flashing red on panel, bloods, blur) after they activated the alert, and one of those feature should be selected, so they will still have the Taiha alert, but on their own preferences.

This is to compensate those who are playing on low-end devices, or while doing resource-intensive works such as scanning the computer for viruses or copying huge chunks of data in or out of the device internal harddisk.

Alternatively, instead letting them choose, we make another preset (let say only include the flashing panel and sound), called as "Annoying Taiha Alert - Low-spec Mode", or similar to it, that is predefined (user cannot change it by themselves without altering the code) by the code. This submenu should only be appear after the main "Annoying Taiha Alert" has been selected and activated. When the "Annoying Taiha Alert" is deactivated, then this submenu will be gone altogether until they activate the menu again.

**Comment by dragonjet** [comment]
yea additional settings should suffice, though I was originally planning to leave it be coz I thought I was looking at a relatively small group of people using that - as it is by default disabled.

**Comment by ethrundr** [comment]
@dragonjet if you look to my group, lot of them are expecting that bloody alerts, dubbing it for their secretary "got her period" :laughing: 
and yeah, most of them has low-spec laptops (not even a computer, but a laptop instead, which usually far lower than a computer)

**Comment by ethrundr** [comment]
reminding about this one.
more and more people complained about the memory usage of current alert, so it's about time I think we finish this one

@dragonjet

**Comment by dragonjet** [comment]
Fixed in #1424
