### ISSUE TITLE
Girls icons are not appeared in blow pannel

### ISSUE THREAD

**Issue by RedDanDelions** [KC3Kai/KC3Kai#981]
![qqwe](https://cloud.githubusercontent.com/assets/15372744/10808598/96393cb8-7e30-11e5-96e9-7e81ca7f7132.jpg)

First, Please understand that I'm not good at english guys... sorry...

today I found Kc3Kai and installed this in the morning.

but there were problems about icons.

I wanna wach my kanmusues TT

I'v tried to fix this problems by googling, but can't fix in now...

plz help me , guys TT

**Comment by dragonjet** [comment]
it might be that photobucket.com is blocked?

**Comment by hufuhufu** [comment]
Could you try to go to http://photobucket.com ?
Maybe your service provider blocked the site

**Comment by RedDanDelions** [comment]
dragonjet,hufuhufh// I think photobucket.com is blocked....

what should i do? TT

**Comment by RedDanDelions** [comment]
um........
I'd like to give up almost..... why can't access photobucket?!  (sigh)

**Comment by dragonjet** [comment]
hm this is a problem. i can't think of anything right now to bypass this except probably VPN but that's usually not a good choice XD

**Comment by RedDanDelions** [comment]
dragonjet // Oh My GOD!!!!!!!!!!!!!!!!!!!!!!

I Find what is the problem!!!

The Problem is the FXXX my university's library of Wifi !!!!!!

maybe, i try using mobile tethering and Successfully KC3 Kai works!!!!

oh dear.... what am i doing in this time?!

so... all everythings go back to access damn library wifi...... 

I really thank you guys, dragonjet and hufuhufu!!!

I'll enjoy KC3 Kai Now!!!!

**Comment by dragonjet** [comment]
:+1:
