### ISSUE TITLE
[Taiha Alert] Blur effect performance degrade

### ISSUE THREAD

**Issue by bcc32** [KC3Kai/KC3Kai#982]
Blur effect seems to slow down the game and depending on your system it might make KanColle respond slower to clicks and stuff.  Is there a similar effect that might be less computation-intensive?

**Comment by ReiFan49** [comment]
sounds like client-based problem, well blur uses extra process though, instead making a static thing, it makes a transparency thingy right? (well, i know using blur is somewhat laggy esp. after have 16px offset or more lol)

**Comment by bcc32** [comment]
Yeah this is definitely not a performance degrade within KC3Kai per se, just an issue with the fact that blur, at least on my machine (Macbook Air), tends to slow down the client rather uncomfortably.

**Comment by NicolaosGreene** [comment]
I figured out that my issues in #980 was caused by the blur effect so if you have weak enough graphics  it just kills it altogether.

**Comment by dragonjet** [comment]
Changed #980 to "*Add Taiha Alert settings for low-spec computers*" so this is directly similar, and will be further tracked there
