### ISSUE TITLE
Exit confirmation not working

### ISSUE THREAD

**Issue by bcc32** [KC3Kai/KC3Kai#985]
Noticed that this started happening around when Kadokawa changed how API links needed to be refreshed.

**Comment by dragonjet** [comment]
play via API link or DMM frame? can't check play via API link now coz maintenance but DMM frame exit confirmation works on my side. probably on settings or the game has not yet started?

**Comment by bcc32** [comment]
Play via API link.  I'll check again after maint.

**Comment by McDohl** [comment]
its working on my end tho

**Comment by ReiFan49** [comment]
hmmm maybe i'll take a look at this

**Comment by dragonjet** [comment]
confirmed bug as somebody else commented on the wikia about this

**Comment by ReiFan49** [comment]
```Javascript
console.log(ConfigManager.api_askExit==1,!trustedExit,!waiting,!localStorage.extract_api)
==> VM598:2 true true true false
```
i thought `localStorage.extract_api` is a boolean, but it was a string... orz

**Comment by ReiFan49** [comment]
![image](https://cloud.githubusercontent.com/assets/9847780/10861520/23366ea8-7fb5-11e5-9a95-cc368703052a.png)
