### ISSUE TITLE
Photobucket images are no longer cached

### ISSUE THREAD

**Issue by LostLogia4** [KC3Kai/KC3Kai#986]
Is it just me, or is the KC3kai icons are no longer cached now that Photobucket has enforced no-cache in their cache control?

![cacheissue](https://cloud.githubusercontent.com/assets/12930396/10836963/13d66470-7eef-11e5-98c1-8375e32a6d6c.jpg)

It also causes the icons in Admiral Panel to flicker as well, because the images have to be redownloaded.

**Comment by Javran** [comment]
same here, I also noticed ship icons flicker quite frequently today.

**Comment by dragonjet** [comment]
seems we need to change host

**Comment by Javran** [comment]
wondering what's the problem with keeping them locally?

**Comment by LostLogia4** [comment]
@Javran Then the newest kanmusu won't get their icon until the next webstore version.

**Comment by Javran** [comment]
then what about using local icons and fall back if not found?

**Comment by dragonjet** [comment]
tbh it's the filesize XD
right now without zuikaku k2s,
the icon folder it's already 1.96mb, larger than the app itself

**Comment by Javran** [comment]
what about lazily downloading & saving them somewhere locally?

**Comment by dragonjet** [comment]
not possible atm, there's a mechanism on chrome that checks extension files - if something was modified / added it will mark as corrupt (the reason why we could only use external URLs when setting custom sound alerts)

haven't tested for images though. but not sure if we're also able to do filesystem changes via JS on chrome. screenshot only "downloads" it, but not really file saving

**Comment by Javran** [comment]
what about saving them as indexeddb blobs?

**Comment by dragonjet** [comment]
hm that's possible but if that's gonna be the case I'd rather pack it on assets folder XD
blobs also can't be cached and I'm seeing performance issues esp chrome already ram-heavy
if my math is right we'll arrive at 3~4mb total zipped size after this

**Comment by Javran** [comment]
so can we do it lazily? assets are downloaded as needed and then stored locally, by that we don't have to download them all at once or pack assets in our extension.
also I think these icons are unlikely to be changed, store them permanently is fine.

**Comment by dragonjet** [comment]
4.28mb zipped total after packing ships and abyss icons into the extension
I think this is fine to just include them on assets instead of relying on third-party hosts.
It will also solve those many reports of photobucket being blocked by ISP

**Comment by dragonjet** [comment]
https://github.com/KC3Kai/KC3Kai/commit/1db46086dd404e140ebf57f7ff738bb6acaac2e3
