### ISSUE TITLE
Quest Update 30 Oct 2015

### ISSUE THREAD

**Issue by McDohl** [KC3Kai/KC3Kai#989]
```
{"api_no":626,
"api_category":6,
"api_type":6,
"api_state":2,
"api_title":"精鋭「艦戦」隊の新編成",
"api_detail":"要熟練搭乗員：練度max「零戦21型」搭載「鳳翔」秘書艦で「零戦21型」x2「九六艦戦」x1廃棄！",
"api_get_material":[0,0,0,50],
"api_bonus_flag":1,
"api_progress_flag":0,
"api_invalid_flag":0}
```

**Comment by LostLogia4** [comment]
{"api_no":627,
"api_category":6,
"api_type":1,
"api_state":2,
"api_title":"機種転換",
"api_detail":"「零戦21型(熟練)」搭載空母を秘書艦にして、新たに「零戦52型」を2つ廃棄！",
"api_get_material":[0,0,0,50],
"api_bonus_flag":1,
"api_progress_flag":0,
"api_invalid_flag":0}

{"api_no":630,
"api_category":6,
"api_type":1,
"api_state":2,
"api_title":"「艦戦」隊の再編成",
"api_detail":"練度max「零戦21型(熟練)」搭載「瑞鶴」が秘書の状態で、「零戦21型」を2つ廃棄！",
"api_get_material":[0,0,0,50],
"api_bonus_flag":1,
"api_progress_flag":0,
"api_invalid_flag":0}

**Comment by dragonjet** [comment]
oh wow thanks

**Comment by dragonjet** [comment]
updated on https://github.com/KC3Kai/kc3-translations/commit/9828ea53ce251b8b115d743aac6e15a8ef8a919a which will be included in 22.2

last three missing IDs 631, 632. 522

**Comment by LostLogia4** [comment]
'''
{"api_no":632,
"api_category":6,
"api_type":1,
"api_state":2,
"api_title":"機種転換",
"api_detail":"練度max「零戦21型(付岩本小隊)」搭載「瑞鶴」秘書艦で、「零戦52型」を2つ廃棄！",
"api_get_material":[0,0,0,50],
"api_bonus_flag":1,
"api_progress_flag":0,
"api_invalid_flag":0}
'''

**Comment by McDohl** [comment]
@LostLogia4 thanks for the report :+1: 
@dragonjet I added the F27=631, F29=632 and F30=633 on https://github.com/KC3Kai/kc3-translations/commit/052a21faff6f6d4c2d45485290e7282e52a63400

**Comment by dragonjet** [comment]
:+1:
