### ISSUE TITLE
Panel not updating after loading preset ships

### ISSUE THREAD

**Issue by Double13** [KC3Kai/KC3Kai#992]
I know its a new feature in the game but.
When you load in a new preset fleet in the game the panel does not update until you leave the fleet creator page (or whatever its called). however if you change one ship you only update that single ship.

**Comment by dragonjet** [comment]
This is supported as of 22.1 check if you have the latest version
#988

**Comment by Double13** [comment]
O sorry seems I still run the 22.0 version.

**Comment by dragonjet** [comment]
:+1:
