### ISSUE TITLE
Missing icon for Zuikaku Kai Ni

### ISSUE THREAD

**Issue by LostLogia4** [KC3Kai/KC3Kai#997]
Zuikaku Kai Ni (both forms) didn't get her icon pic, even though it's already in the extension asset file.

Didn't test this with armored version cuz I have no plan to remodel her right now, but from PvP it turns out the armored version didn't have the image as well.

Also, her icon is still the same old "flattened version" from yesterday.

Sidenote: Michishio Kai's image were waaay off.

**Comment by ethrundr** [comment]
I have her in the Armored version and it's still not there

**Comment by dragonjet** [comment]
hm it's supposedly added on 6f2bb3ecdf7dfe9a8beed7643fb508f5bf2cba9b

**Comment by LostLogia4** [comment]
Already added but not displayed. At all.

**Comment by ethrundr** [comment]
update: it's already displayed per the latest pull
