### ISSUE TITLE
Taiha Alert triggers but no animation on-screen on API play

### ISSUE THREAD

**Issue by dragonjet** [KC3Kai/KC3Kai#998]
triggers but only the f12 panel gets the red inner glow, heartbeat sound plays
no screen animation.
only on API gameplay
DMM frame works

- as reproted on facebook

**Comment by ethrundr** [comment]
since this discussing about the alert, I'd like to ask when the bloods will be displayed?

I've tested several times with the alert in DMM frame, and the most I can get is the blur. no bloods :cry:

**Comment by dragonjet** [comment]
hm thats odd, anything on the console like 404 something?
